<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>2-Dimensional Array</string>
	<key>scopeName</key>
	<string>source.2da</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>name</key>
			<string>meta.header.2da</string>
			<key>begin</key>
			<string>(?x) \A
[ \t]* (2DA\s+V(?:\d+\.\d+)) # Format signature
[ \t]* (?:(\S.*?) [ \t]*)?     # Unexpected junk
$ \s*</string>
			<key>end</key>
			<string>(?!\G)$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#default</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.file-signature.2da</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.format-version.2da</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.unexpected-characters.2da</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.header.2da</string>
			<key>begin</key>
			<string>\A[ \t]*(\S+)[ \t]*$</string>
			<key>end</key>
			<string>(?!\G)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#default</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.body.2da</string>
			<key>begin</key>
			<string>^</string>
			<key>end</key>
			<string>(?=A)B</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.column-headers.2da</string>
					<key>contentName</key>
					<string>constant.other.reference.link</string>
					<key>begin</key>
					<string>\G</string>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#headers</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.records.2da</string>
					<key>begin</key>
					<string>(?!\G)^</string>
					<key>end</key>
					<string>(?=A)B</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#row</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>blankEntry</key>
		<dict>
			<key>name</key>
			<string>keyword.operator.null-value.2da</string>
			<key>match</key>
			<string>(?:\G|^|(?&lt;=\s))\*{4}(?=\s|$)</string>
		</dict>
		<key>default</key>
		<dict>
			<key>name</key>
			<string>meta.default-value.2da</string>
			<key>begin</key>
			<string>(?:\G|^)[ \t]*(?:(DEFAULT(:))[ \t]*)?</string>
			<key>end</key>
			<string>(?=[ \t]*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#value</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.default-value.2da</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.colon.2da</string>
				</dict>
			</dict>
		</dict>
		<key>float</key>
		<dict>
			<key>name</key>
			<string>constant.numeric.float.decimal.2da</string>
			<key>match</key>
			<string>[-+]?(?:[0-9]+\.[0-9]+|\.[0-9]+)(?=\s|$)</string>
		</dict>
		<key>headers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>entity.name.column.header.unquoted.2da</string>
					<key>match</key>
					<string>[^&quot;\s]+</string>
				</dict>
				<dict>
					<key>name</key>
					<string>entity.name.column.header.quoted.2da</string>
					<key>match</key>
					<string>(&quot;)(?=\w)[^&quot;]+(&quot;)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.header.begin.2da</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.header.end.2da</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>integer</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.numeric.integer.dec.decimal.2da</string>
					<key>match</key>
					<string>[-+]?[0-9]+(?=\s|$)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.integer.hex.hexadecimal.2da</string>
					<key>match</key>
					<string>[-+]?0[Xx][A-Fa-f0-9]+(?=\s|$)</string>
				</dict>
			</array>
		</dict>
		<key>row</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?:\G|^)[ \t]*(\d+)(?=\s|$)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.integer.row-index.2da</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.column-separator.2da</string>
					<key>match</key>
					<string>[ \t]+</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#value</string>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>string.quoted.double.2da</string>
					<key>begin</key>
					<string>&quot;</string>
					<key>end</key>
					<string>(&quot;)|([^&quot;]*?)(?=[ \t]*$)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.2da</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.2da</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.unclosed-string.2da</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>string.unquoted.2da</string>
					<key>match</key>
					<string>(?![-+]?\d)[^\s&quot;]+</string>
				</dict>
			</array>
		</dict>
		<key>value</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#blankEntry</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#float</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#integer</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>2da</string>
	</array>
</dict>
</plist>
