<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Augmented Backus-Naur Form</string>
	<key>scopeName</key>
	<string>source.abnf</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#main</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>assignment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.increment.abnf</string>
					<key>match</key>
					<string>=/</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.colon.non-standard.abnf</string>
					<key>match</key>
					<string>:+=</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.abnf</string>
					<key>match</key>
					<string>=</string>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>name</key>
			<string>comment.line.semicolon.abnf</string>
			<key>begin</key>
			<string>;</string>
			<key>end</key>
			<string>$</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.abnf</string>
				</dict>
			</dict>
		</dict>
		<key>core-rules</key>
		<dict>
			<key>name</key>
			<string>support.constant.reference.core-rule.abnf</string>
			<key>match</key>
			<string>(?x)
\b (?&lt;!-)
(ALPHA|BIT|CHAR|CRLF|CR|CTL|DIGIT|DQUOTE
|HEXDIG|HTAB|LF|LWSP|OCTET|SP|VCHAR|WSP)
\b (?!-)</string>
		</dict>
		<key>group</key>
		<dict>
			<key>name</key>
			<string>meta.group.abnf</string>
			<key>begin</key>
			<string>\(</string>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#rhs</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.round.bracket.begin.abnf</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.round.bracket.end.abnf</string>
				</dict>
			</dict>
		</dict>
		<key>main</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#rule</string>
				</dict>
			</array>
		</dict>
		<key>optional</key>
		<dict>
			<key>name</key>
			<string>meta.optional.abnf</string>
			<key>begin</key>
			<string>\[</string>
			<key>end</key>
			<string>\]</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#rhs</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.square.bracket.begin.abnf</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.square.bracket.end.abnf</string>
				</dict>
			</dict>
		</dict>
		<key>prose</key>
		<dict>
			<key>name</key>
			<string>string.other.prose.abnf</string>
			<key>begin</key>
			<string>&lt;</string>
			<key>end</key>
			<string>&gt;</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.abnf</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.abnf</string>
				</dict>
			</dict>
		</dict>
		<key>quantifier</key>
		<dict>
			<key>name</key>
			<string>meta.quantifier.abnf</string>
			<key>match</key>
			<string>([0-9]*)(\*)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.decimal.integer.int.abnf</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.logical.repetition.asterisk.star.abnf</string>
				</dict>
			</dict>
		</dict>
		<key>reference</key>
		<dict>
			<key>name</key>
			<string>variable.parameter.argument.identifier.reference.abnf</string>
			<key>match</key>
			<string>[A-Za-z][-A-Za-z0-9]*</string>
		</dict>
		<key>rhs</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#assignment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#terminal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#quantifier</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#group</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#optional</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#core-rules</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#reference</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#prose</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.logical.or.alternation.pipe.abnf</string>
					<key>match</key>
					<string>/</string>
				</dict>
			</array>
		</dict>
		<key>rule</key>
		<dict>
			<key>name</key>
			<string>meta.ruleset.$2.abnf</string>
			<key>contentName</key>
			<string>meta.rhs.abnf</string>
			<key>begin</key>
			<string>(?:^|\G)(\s*)([A-Za-z][-A-Za-z0-9]*)</string>
			<key>end</key>
			<string>^(?!\1\s+\S)|^(?=\S)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#rhs</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.lhs.abnf</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.leading.abnf</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.rule.identifier.abnf</string>
				</dict>
			</dict>
		</dict>
		<key>string</key>
		<dict>
			<key>name</key>
			<string>string.quoted.double.abnf</string>
			<key>begin</key>
			<string>&quot;</string>
			<key>end</key>
			<string>&quot;</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.abnf</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.abnf</string>
				</dict>
			</dict>
		</dict>
		<key>terminal</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.terminal.numeric.decimal.abnf</string>
					<key>begin</key>
					<string>(%)(d|D)</string>
					<key>end</key>
					<string>(?=$|[;()\[\]{}\s])</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>invalid.illegal.syntax.abnf</string>
							<key>match</key>
							<string>[0-9A-Fa-f]*[^-\s0-9.;()\[\]{}][^-.;()\[\]{}]*</string>
						</dict>
						<dict>
							<key>name</key>
							<string>constant.numeric.integer.int.decimal.abnf</string>
							<key>match</key>
							<string>[0-9]+</string>
						</dict>
						<dict>
							<key>name</key>
							<string>punctuation.separator.range.dash.hyphen.abnf</string>
							<key>match</key>
							<string>-</string>
						</dict>
						<dict>
							<key>name</key>
							<string>keyword.operator.concatenation.abnf</string>
							<key>match</key>
							<string>\.</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.terminal.percentage-sign.abnf</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.type.modifier.radix.abnf</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.terminal.numeric.hexadecimal.hex.abnf</string>
					<key>begin</key>
					<string>(%)(x|X)</string>
					<key>end</key>
					<string>(?=$|[;()\[\]{}\s])</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>invalid.illegal.syntax.abnf</string>
							<key>match</key>
							<string>[0-9A-Fa-f]*[^-\s0-9A-Fa-f.;()\[\]{}][^-.;()\[\]{}]*</string>
						</dict>
						<dict>
							<key>name</key>
							<string>constant.numeric.integer.int.hexadecimal.hex.abnf</string>
							<key>match</key>
							<string>[0-9A-Fa-f]+</string>
						</dict>
						<dict>
							<key>name</key>
							<string>punctuation.separator.range.dash.hyphen.abnf</string>
							<key>match</key>
							<string>-</string>
						</dict>
						<dict>
							<key>name</key>
							<string>keyword.operator.concatenation.abnf</string>
							<key>match</key>
							<string>\.</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.terminal.percentage-sign.abnf</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.type.modifier.radix.abnf</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.terminal.numeric.binary.bin.abnf</string>
					<key>begin</key>
					<string>(%)(b|B)</string>
					<key>end</key>
					<string>(?=$|[;()\[\]{}\s])</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>invalid.illegal.syntax.abnf</string>
							<key>match</key>
							<string>[0-1]*[^-\s0-1.;()\[\]{}][^-.;()\[\]{}]*</string>
						</dict>
						<dict>
							<key>name</key>
							<string>constant.numeric.integer.int.binary.bin.abnf</string>
							<key>match</key>
							<string>[0-1]+</string>
						</dict>
						<dict>
							<key>name</key>
							<string>punctuation.separator.range.dash.hyphen.abnf</string>
							<key>match</key>
							<string>-</string>
						</dict>
						<dict>
							<key>name</key>
							<string>keyword.operator.concatenation.abnf</string>
							<key>match</key>
							<string>\.</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.terminal.percentage-sign.abnf</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.type.modifier.radix.abnf</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>abnf</string>
	</array>
</dict>
</plist>
