<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Adobe Font Metrics</string>
	<key>scopeName</key>
	<string>source.afm</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#resources</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#main</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>amfmSpecific</key>
		<dict>
			<key>name</key>
			<string>meta.${2:/downcase}.afm</string>
			<key>begin</key>
			<string>^(Start(Descendent|Direction|Axis|Master))(?:\s+(\S.*))?</string>
			<key>end</key>
			<string>^End\2\s*$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#main</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.start.${2:/downcase}.afm</string>
				</dict>
				<key>3</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#hex</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#integer</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.end.${2:/downcase}.afm</string>
				</dict>
			</dict>
		</dict>
		<key>array</key>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>end</key>
			<string>\]|(?=$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#array</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numbers</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#psLiteral</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.list.bracket.square.begin.afm</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.list.bracket.square.end.afm</string>
				</dict>
			</dict>
		</dict>
		<key>bestGuessHighlights</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\G\s*(true|false)(?=\s|$)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#boolean</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>^(?:\s+[-+]?[.\d]+)+\s*$</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#numbers</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>^\s*(\[.*\])\s*$</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#array</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#main</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>^\s*&lt;[A-Fa-f0-9]+&gt;\s*$</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#hex</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>(?:(?:^|\s+)/[^\s\[\];]+)+\s*$</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#psLiteral</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>variable.assignment.afm</string>
					<key>match</key>
					<string>^.+$</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.afm</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>boolean</key>
		<dict>
			<key>name</key>
			<string>constant.language.boolean.$1.afm</string>
			<key>match</key>
			<string>(?&lt;!\w)(true|false)(?!\w)</string>
		</dict>
		<key>bracketedString</key>
		<dict>
			<key>name</key>
			<string>string.quoted.double.bracketed.afm</string>
			<key>begin</key>
			<string>\(</string>
			<key>end</key>
			<string>\)|(?=$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#bracketedString</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.bracket.round.begin.afm</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.bracket.round.end.afm</string>
				</dict>
			</dict>
		</dict>
		<key>charMetricInnards</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#delimiter</string>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.character.code.hexadecimal.afm</string>
					<key>match</key>
					<string>\G(CH)\s+(&lt;[^&gt;\s]++&gt;)\s*(?=;|$)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.assignment.codepoint.afm</string>
						</dict>
						<key>2</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#hex</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.character.code.decimal.afm</string>
					<key>match</key>
					<string>\G(C)\s+([-+]?\d+)\s*(?=;|$)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.assignment.codepoint.afm</string>
						</dict>
						<key>2</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#integer</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.metric.character.width.afm</string>
					<key>begin</key>
					<string>(?&lt;=\s|^|;)(W[01]?|VV)(?=\s|;|$)</string>
					<key>end</key>
					<string>(?=;|$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#numbers</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.assignment.character-width.afm</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.metric.character.width.afm</string>
					<key>match</key>
					<string>(?&lt;=\s|^|;)(W[01]?(X|Y))(?:\s+([-+]?[\d.]+)\s*)(?=\s|$|;)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.assignment.${2:/downcase}-width.afm</string>
						</dict>
						<key>3</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#integer</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.metric.character.name.afm</string>
					<key>match</key>
					<string>(?&lt;=\s|^|;)(N)(?:\s+([^;\s]+))?\s*(?=\s|$|;)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.assignment.character.name.afm</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.parameter.identifier.afm</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.metric.bounding-box.afm</string>
					<key>begin</key>
					<string>(?&lt;=\s|^|;)(B)(?=\s|$|;)</string>
					<key>end</key>
					<string>(?=$|;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#numbers</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.assignment.metric.afm</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.metric.next-ligature.afm</string>
					<key>begin</key>
					<string>(?&lt;=\s|^|;)(L)(?=\s|$|;)</string>
					<key>end</key>
					<string>(?=$|;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#name</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.assignment.metric.afm</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>charMetrics</key>
		<dict>
			<key>name</key>
			<string>meta.metrics-list.afm</string>
			<key>begin</key>
			<string>^(StartCharMetrics)(?:\s+(\d+))?\s*$</string>
			<key>end</key>
			<string>^EndCharMetrics\s*$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.unencoded.character.metrics.afm</string>
					<key>begin</key>
					<string>^\s*(?=C\s+-\d)</string>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#charMetricInnards</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.character.metrics.afm</string>
					<key>begin</key>
					<string>^\s*</string>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#charMetricInnards</string>
						</dict>
					</array>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.start.metrics.afm</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.decimal.integer.afm</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.end.metrics.afm</string>
				</dict>
			</dict>
		</dict>
		<key>comment</key>
		<dict>
			<key>contentName</key>
			<string>comment.line.afm</string>
			<key>begin</key>
			<string>^Comment(?=\s|$)</string>
			<key>end</key>
			<string>$</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.start-comment.afm</string>
				</dict>
			</dict>
		</dict>
		<key>compositesData</key>
		<dict>
			<key>name</key>
			<string>meta.composites.afm</string>
			<key>begin</key>
			<string>^(StartComposites)(?:\s+([-+]?\d+))?\s*$</string>
			<key>end</key>
			<string>^EndComposites</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.composition.afm</string>
					<key>begin</key>
					<string>^CC(?=\s|$|;)</string>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#delimiter</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\G\s+([^;\s]+)(?:\s+([-+]?\d+))?</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>string.unquoted.parameter.identifier.afm</string>
								</dict>
								<key>2</key>
								<dict>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#integer</string>
										</dict>
									</array>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>match</key>
							<string>(?&lt;=;|\s)(PCC)\s+([^;\s]+)</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.char-comp.afm</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>string.unquoted.parameter.identifier.afm</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>include</key>
							<string>#numbers</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.char-comp.afm</string>
						</dict>
					</dict>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.start.metrics.afm</string>
				</dict>
				<key>2</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#integer</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.end.metrics.afm</string>
				</dict>
			</dict>
		</dict>
		<key>delimiter</key>
		<dict>
			<key>name</key>
			<string>punctuation.delimiter.metrics.semicolon.afm</string>
			<key>match</key>
			<string>;</string>
		</dict>
		<key>globalInfo</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.${1:/downcase}-name.afm</string>
					<key>begin</key>
					<string>^(Font|Full|Family)Name(?=\s|$)</string>
					<key>end</key>
					<string>^|$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#paramName</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.${1:/downcase}-name.afm</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.writing-directions.afm</string>
					<key>begin</key>
					<string>^MetricsSets(?=\s|$)</string>
					<key>end</key>
					<string>^|$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#paramInteger</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.metrics-sets.afm</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.is-monospaced-font.afm</string>
					<key>begin</key>
					<string>^IsFixedPitch(?=\s|$)</string>
					<key>end</key>
					<string>^|$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#paramBoolean</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.is-fixed-pitch.afm</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.notice.afm</string>
					<key>begin</key>
					<string>^Notice(?=\s|$)</string>
					<key>end</key>
					<string>^|$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#paramString</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.notice.afm</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.revision.afm</string>
					<key>begin</key>
					<string>^Version(?=\s|$)</string>
					<key>end</key>
					<string>^|$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#paramString</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.version.afm</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.weight.afm</string>
					<key>begin</key>
					<string>^Weight(?=\s|$)</string>
					<key>end</key>
					<string>^|$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#paramString</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.weight.afm</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.italic-angle.afm</string>
					<key>begin</key>
					<string>^ItalicAngle(?=\s|$)</string>
					<key>end</key>
					<string>^|$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#paramNumber</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.italic-angle.afm</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.bounding-box.afm</string>
					<key>begin</key>
					<string>^FontBBox(?=\s|$)</string>
					<key>end</key>
					<string>^|$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#paramNumbers</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.font-bbox.afm</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.encoding-scheme.afm</string>
					<key>begin</key>
					<string>^EncodingScheme(?=\s|$)</string>
					<key>end</key>
					<string>^|$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#paramString</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.encoding-scheme.afm</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.underline-property.${1:/downcase}.afm</string>
					<key>begin</key>
					<string>^Underline(Position|Thickness)(?=\s|$)</string>
					<key>end</key>
					<string>^|$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#paramNumber</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.underline-${1:/downcase}.afm</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.metric.${1:/downcase}-height.afm</string>
					<key>begin</key>
					<string>^(Cap|X)Height(?=\s|$)</string>
					<key>end</key>
					<string>^|$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#paramNumber</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.${1:/downcase}-height.afm</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.metric.${1:/downcase}.afm</string>
					<key>begin</key>
					<string>^(Descender|Ascender)(?=\s|$)</string>
					<key>end</key>
					<string>^|$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#paramNumber</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.${1:/downcase}.afm</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.metric.${1:/downcase}.afm</string>
					<key>begin</key>
					<string>^(CharacterSet|AxisType|AxisLabel)(?=\s|$)</string>
					<key>end</key>
					<string>^|$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#paramString</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.metadata.afm</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.metadata.${1:/downcase}.afm</string>
					<key>begin</key>
					<string>^(Characters|EscChar|MappingScheme)(?=\s|$)</string>
					<key>end</key>
					<string>^|$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#paramNumber</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.metadata.afm</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.metadata.${1:/downcase}.afm</string>
					<key>begin</key>
					<string>^(IsBaseFont|IsFixedV|IsCIDFont)(?=\s|$)</string>
					<key>end</key>
					<string>^|$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#paramBoolean</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.metadata.afm</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.metadata.${1:/downcase}.afm</string>
					<key>begin</key>
					<string>^(CharWidth|VVector|Masters|Axes|Std[HV]W)(?=\s|$)</string>
					<key>end</key>
					<string>^|$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#paramNumbers</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.metadata.afm</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.metadata.${1:/downcase}.afm</string>
					<key>begin</key>
					<string>^(WeightVector|BlendDesign(Positions|Map)|BlendAxisTypes)(?=\s|$)</string>
					<key>end</key>
					<string>^|$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#array</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#numbers</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#psLiteral</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.metadata.afm</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>hex</key>
		<dict>
			<key>name</key>
			<string>constant.numeric.integer.hexadecimal.afm</string>
			<key>match</key>
			<string>(&lt;)(?:[A-Fa-f0-9]+|([^&gt;\s]+))(&gt;)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.hex.bracket.angle.begin.afm</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.syntax.bad-characters.afm</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.hex.bracket.angle.end.afm</string>
				</dict>
			</dict>
		</dict>
		<key>integer</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.numeric.integer.octal.afm</string>
					<key>match</key>
					<string>(?&lt;!\w)[-+]?(?=0)\d+</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.integer.decimal.afm</string>
					<key>match</key>
					<string>(?&lt;!\w)[-+]?\d+</string>
				</dict>
			</array>
		</dict>
		<key>kerningData</key>
		<dict>
			<key>name</key>
			<string>meta.kerning-data.afm</string>
			<key>begin</key>
			<string>^(StartKernData)\s*$</string>
			<key>end</key>
			<string>^EndKernData\s*$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^(StartTrackKern)(?:\s+([-+]?\d+))?\s*$</string>
					<key>end</key>
					<string>^EndTrackKern\s*$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#kerningTrack</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.start.metrics.afm</string>
						</dict>
						<key>2</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#integer</string>
								</dict>
							</array>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.end.metrics.afm</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>begin</key>
					<string>^(StartKernPairs[0-1]?)(?:\s+([-+]?\d+))?\s*$</string>
					<key>end</key>
					<string>^EndKernPairs\s*$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#kerningPairs</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.start.metrics.afm</string>
						</dict>
						<key>2</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#integer</string>
								</dict>
							</array>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.end.metrics.afm</string>
						</dict>
					</dict>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.start.metrics.afm</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.end.metrics.afm</string>
				</dict>
			</dict>
		</dict>
		<key>kerningPairs</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.kerning-pair.by-codepoint.afm</string>
					<key>begin</key>
					<string>^KPH(?=\s|$)</string>
					<key>end</key>
					<string>^|$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\G((?:\s+&lt;[^&gt;\s]*&gt;)+)\s+</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#hex</string>
										</dict>
									</array>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>include</key>
							<string>#numbers</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.kern-pair.afm</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.kerning-pair.by-name.afm</string>
					<key>begin</key>
					<string>^KP[XY]?(?=\s|$)</string>
					<key>end</key>
					<string>^|$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\G((?:\s+\S+){1,2})</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#name</string>
										</dict>
									</array>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>include</key>
							<string>#numbers</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.kern-pair.afm</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>kerningTrack</key>
		<dict>
			<key>begin</key>
			<string>^(TrackKern)(?=\s|$)</string>
			<key>end</key>
			<string>^|$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#numbers</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.track-kern.afm</string>
				</dict>
			</dict>
		</dict>
		<key>main</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#real</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#integer</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#array</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#globalInfo</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#kerningData</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#charMetrics</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#compositesData</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#amfmSpecific</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#direction</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#primaryFonts</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#reserved</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#userDefined</string>
				</dict>
			</array>
		</dict>
		<key>name</key>
		<dict>
			<key>name</key>
			<string>string.unquoted.parameter.identifier.afm</string>
			<key>match</key>
			<string>[^;\s]+</string>
		</dict>
		<key>numbers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#real</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#integer</string>
				</dict>
			</array>
		</dict>
		<key>paramBoolean</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\G\s+(true|false)\s*$</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#boolean</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>include</key>
					<string>#paramInvalid</string>
				</dict>
			</array>
		</dict>
		<key>paramInteger</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\G\s+([-+]?[0-9]+)\s*$</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#integer</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>include</key>
					<string>#paramInvalid</string>
				</dict>
			</array>
		</dict>
		<key>paramInvalid</key>
		<dict>
			<key>match</key>
			<string>\G\s+(\S+.+)\s*$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.syntax.type.afm</string>
				</dict>
			</dict>
		</dict>
		<key>paramName</key>
		<dict>
			<key>match</key>
			<string>\G\s+(\S+.*)\s*$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.identifier.afm</string>
				</dict>
			</dict>
		</dict>
		<key>paramNumber</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\G\s+([-+]?(?:\d*\.\d+|\d+))\s*$</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#real</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#integer</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>include</key>
					<string>#paramInvalid</string>
				</dict>
			</array>
		</dict>
		<key>paramNumbers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#real</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#integer</string>
				</dict>
				<dict>
					<key>name</key>
					<string>invalid.illegal.syntax.type.afm</string>
					<key>match</key>
					<string>(?![-+0-9.])\S+</string>
				</dict>
			</array>
		</dict>
		<key>paramString</key>
		<dict>
			<key>name</key>
			<string>variable.assignment.afm</string>
			<key>match</key>
			<string>\G\s+(\S.*)\s*$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.afm</string>
				</dict>
			</dict>
		</dict>
		<key>paramVar</key>
		<dict>
			<key>match</key>
			<string>\G\s+(\S.*)\s*$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.afm</string>
				</dict>
			</dict>
		</dict>
		<key>primaryFontLine</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>invalid.illegal.syntax.empty-field.afm</string>
					<key>match</key>
					<string>(?&lt;=^|\s|;)(?:PC|PL|PN)(?=\s*;)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.primary-coordinates.afm</string>
					<key>begin</key>
					<string>(?&lt;=^|\s|;)PC(?=\s|$)</string>
					<key>end</key>
					<string>(?=;|$|[A-Z])</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#real</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#integer</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>variable.assignment.metadata.afm</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;=\s|;)(P[LN])\s+</string>
					<key>end</key>
					<string>(?=;|$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#bracketedString</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#delimiter</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.assignment.metadata.afm</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>include</key>
					<string>#delimiter</string>
				</dict>
			</array>
		</dict>
		<key>primaryFonts</key>
		<dict>
			<key>name</key>
			<string>meta.primary-fonts.afm</string>
			<key>begin</key>
			<string>^(StartPrimaryFonts)(?:\s+([-+]?\d+))?\s*$</string>
			<key>end</key>
			<string>\bEndPrimaryFonts(?=\s|$)|(?!P)(?=\w)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#delimiter</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#primaryFontLine</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.start.font-list.afm</string>
				</dict>
				<key>2</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#integer</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.end.font-list.afm</string>
				</dict>
			</dict>
		</dict>
		<key>psLiteral</key>
		<dict>
			<key>name</key>
			<string>support.language.constant.literal.afm</string>
			<key>match</key>
			<string>(/)[^\s\[\];]+</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.literal.slash.afm</string>
				</dict>
			</dict>
		</dict>
		<key>real</key>
		<dict>
			<key>name</key>
			<string>constant.numeric.float.afm</string>
			<key>match</key>
			<string>(?&lt;!\w)[-+]?\d*\.\d+</string>
		</dict>
		<key>reserved</key>
		<dict>
			<key>match</key>
			<string>^([A-Z][A-Za-z0-9]+)(?=\s)(.*)$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.reserved.afm</string>
				</dict>
				<key>2</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#bestGuessHighlights</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>resources</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.metrics.file-resource.afm</string>
					<key>begin</key>
					<string>^(StartFontMetrics)\s+(\d+(?:\.\d+)?)?\s*$</string>
					<key>end</key>
					<string>^(EndFontMetrics)\s*$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#main</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.start.file.afm</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.float.decimal.version-number.afm</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.end.file.afm</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.composite.metrics.file-resource.afm</string>
					<key>begin</key>
					<string>^(StartCompFontMetrics)\s+(\d+(?:\.\d+)?)?\s*$</string>
					<key>end</key>
					<string>^(EndCompFontMetrics)\s*$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#main</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.start.file.afm</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.float.decimal.version-number.afm</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.end.file.afm</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.master.metrics.file-resource.afm</string>
					<key>begin</key>
					<string>^(StartMasterFontMetrics)\s+(\d+(?:\.\d+)?)?\s*$</string>
					<key>end</key>
					<string>^(EndMasterFontMetrics)\s*$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#main</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.start.file.afm</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.float.decimal.version-number.afm</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.end.file.afm</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>userDefined</key>
		<dict>
			<key>match</key>
			<string>^([a-z][A-Za-z0-9]+)(?=\s)(.*)$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.custom.afm</string>
				</dict>
				<key>2</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#bestGuessHighlights</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>afm</string>
	</array>
</dict>
</plist>
