<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Antlers (Statamic Syntax)</string>
	<key>scopeName</key>
	<string>text.html.statamic</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#php-tag</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#statamic-comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#frontMatter</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#antlers-tags</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>antlers-conditionals</key>
		<dict>
			<key>name</key>
			<string>keyword.control.statamic</string>
			<key>match</key>
			<string>(?&lt;!:)(/?else|/?elseif|/?if|/?unless|endif|endunless|unlesselse|stop)</string>
		</dict>
		<key>antlers-constants</key>
		<dict>
			<key>match</key>
			<string>(\G|\s|\b)(true|TRUE|false|FALSE|yes|YES|no|NO|null|as)\s</string>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language.statamic</string>
				</dict>
			</dict>
		</dict>
		<key>antlers-expression</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>punctuation.terminator.expression.statamic</string>
					<key>match</key>
					<string>;</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#antlers-strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#antlers-numbers</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.key.statamic</string>
					<key>match</key>
					<string>=&gt;</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.class.statamic</string>
					<key>match</key>
					<string>-&gt;</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#statamic-explicit-tags</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#statamic-core-tags</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.comparison.statamic</string>
					<key>match</key>
					<string>===|==|!==|!=|&lt;&gt;</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.string.statamic</string>
					<key>match</key>
					<string>\&amp;=?</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.statamic</string>
					<key>match</key>
					<string>=|\+=|\-=|\*\*?=|/=|%=|\|=|\^=|&lt;&lt;=|&gt;&gt;=</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.logical.statamic</string>
					<key>match</key>
					<string>(?i)(!|\?\?|\?=|\?|&amp;&amp;|&amp;|\|\|)|\b(and|or|xor)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.bitwise.statamic</string>
					<key>match</key>
					<string>(?i)\b(bwa|bwo|bxor|bnot|bsl|bsr)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.comparison.statamic</string>
					<key>match</key>
					<string>&lt;=&gt;|&lt;=|&gt;=|&lt;|&gt;</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.arithmetic.statamic</string>
					<key>match</key>
					<string>\-|\+|\*\*?|/|%</string>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.array.statamic</string>
					<key>begin</key>
					<string>(arr|list|switch)\s*(\()</string>
					<key>end</key>
					<string>\)|(?=\?&gt;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#antlers-expression</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.construct.statamic</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.array.begin.bracket.round.statamic</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.array.end.bracket.round.statamic</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;!@){(\s?)</string>
					<key>end</key>
					<string>(\s?)}</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#antlers-expression</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#antlers-tag-parameter-variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#antlers-language-operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#antlers-variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#antlers-modifier-pipe</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#antlers-variable-modifier-name</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#antlers-variable-modifiers</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#antlers-constants</string>
				</dict>
			</array>
		</dict>
		<key>antlers-language-operators</key>
		<dict>
			<key>match</key>
			<string>(\w+)[\s]</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.statamic</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#antlers-numbers</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#language-operators</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>antlers-modifier-pipe</key>
		<dict>
			<key>name</key>
			<string>keyword.operator.other.statamic</string>
			<key>match</key>
			<string>(\|)</string>
		</dict>
		<key>antlers-numbers</key>
		<dict>
			<key>name</key>
			<string>constant.numeric.statamic</string>
			<key>match</key>
			<string>0|[1-9](?:_?[0-9]+)*</string>
		</dict>
		<key>antlers-strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string-double-quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-single-quoted</string>
				</dict>
			</array>
		</dict>
		<key>antlers-tag-parameter-variable</key>
		<dict>
			<key>match</key>
			<string>(:?([\S:]+?)(=)(&apos;|&quot;)([^\4]*?)(\4))</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>:([\S:]+?)(=)(&apos;|&quot;)(.*?)(\3)</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.other.attribute-name</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.assignment.statamic</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.string.begin.statamic</string>
								</dict>
								<key>4</key>
								<dict>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#antlers-expression</string>
										</dict>
									</array>
								</dict>
								<key>5</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.string.end.statamic</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>match</key>
							<string>([\S]+?)(=)((&apos;|&quot;)(.*?)(\4))</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.other.attribute-name</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.assignment.statamic</string>
								</dict>
								<key>3</key>
								<dict>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#string-single-quoted</string>
										</dict>
										<dict>
											<key>include</key>
											<string>#string-double-quoted</string>
										</dict>
									</array>
								</dict>
							</dict>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>antlers-tags</key>
		<dict>
			<key>name</key>
			<string>meta.embedded.block.statamic</string>
			<key>begin</key>
			<string>(?&lt;!@){{(?!\$)(\s?)</string>
			<key>end</key>
			<string>(\s?)}}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#statamic-comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#php-tag</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#antlers-conditionals</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#antlers-expression</string>
				</dict>
			</array>
		</dict>
		<key>antlers-variable</key>
		<dict>
			<key>match</key>
			<string>(/?\w+)(:)?(\w+)?</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.statamic</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.statamic</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.statamic</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>antlers-variable-modifier-name</key>
		<dict>
			<key>match</key>
			<string>(\s)?(\|)(\s)?(\w+((^:([a-zA-Z0-9-_/-@]+)){1,2})?|((-|\+|\*|/|\^|\%):(\d*)?\.?(\d+)))+</string>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.statamic</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>support.function.statamic</string>
				</dict>
			</dict>
		</dict>
		<key>antlers-variable-modifiers</key>
		<dict>
			<key>match</key>
			<string>(\s)?(\|)(\s)?(\w+((:([a-zA-Z0-9-_/-@]+)){1,2})?|((-|\+|\*|/|\^|\%):(\d*)?\.?(\d+)))+</string>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.statamic</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>support.function.statamic</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#antlers-expression</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>core-tag-names</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>entity.name.tag.statamic</string>
					<key>match</key>
					<string>(?i)\b(taxonomy|cookie|user_groups|user_roles|collection|asset|nocache|vite|mount_url|form|assets|cache|can|dd|ddd|dump|get_content|get_error|get_errors|get_files|glide|in|increment|installed|is|iterate|foreach|link|locales|markdown|member|mix|nav|not_found|404|obfuscate|parent|partial|path|query|range|loop|redirect|relate|rotate|route|scope|section|session|set|structure|svg|theme|trans|trans_choice|user|users|widont|yields|yield|slot|once|noparse|view|stack|push)\b</string>
				</dict>
			</array>
		</dict>
		<key>frontMatter</key>
		<dict>
			<key>contentName</key>
			<string>meta.embedded.block.frontmatter</string>
			<key>begin</key>
			<string>\A-{3}\s*$</string>
			<key>end</key>
			<string>(^|\G)-{3}|\.{3}\s*$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.yaml</string>
				</dict>
			</array>
		</dict>
		<key>language-operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>support.function.array.statamic</string>
					<key>match</key>
					<string>(?i)\b(pluck|take|skip|arr|orderby|groupby|merge|where|switch|bwa|bwo|bxor|bnot|bsl|bsr|if|elseif|else|void)(\b)</string>
				</dict>
			</array>
		</dict>
		<key>php-tag</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.embedded.block.statamic</string>
					<key>contentName</key>
					<string>source.php</string>
					<key>begin</key>
					<string>&lt;\?(?i:php|=)?(?![^?]*\?&gt;)</string>
					<key>end</key>
					<string>(\?)&gt;</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.html.php</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.begin.statamic</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.end.statamic</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>source.php</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.embedded.line.statamic</string>
					<key>contentName</key>
					<string>source.php</string>
					<key>begin</key>
					<string>(?&lt;!@){{([\$\?]\s?)</string>
					<key>end</key>
					<string>(\s?)[\$\?]}}</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.html.php</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.begin.statamic</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.end.statamic</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>source.php</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.embedded.line.statamic</string>
					<key>contentName</key>
					<string>source.php</string>
					<key>begin</key>
					<string>&lt;\?(?i:php|=)?</string>
					<key>end</key>
					<string>(\?)&gt;</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.html.php</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.begin.statamic</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.end.statamic</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>source.php</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>statamic-comments</key>
		<dict>
			<key>name</key>
			<string>comment.block.statamic</string>
			<key>begin</key>
			<string>{{#</string>
			<key>end</key>
			<string>#}}</string>
		</dict>
		<key>statamic-core-closing-tags</key>
		<dict>
			<key>match</key>
			<string>\/(\w+)+</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.statamic</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#core-tag-names</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>statamic-core-tags</key>
		<dict>
			<key>match</key>
			<string>\G(/?\w+)+</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.statamic</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#core-tag-names</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>statamic-explicit-tags</key>
		<dict>
			<key>match</key>
			<string>\G(/?%\w+)+</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.statamic</string>
				</dict>
			</dict>
		</dict>
		<key>string-double-quoted</key>
		<dict>
			<key>name</key>
			<string>string.quoted.double.statamic</string>
			<key>begin</key>
			<string>&quot;</string>
			<key>end</key>
			<string>&quot;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?&lt;!@){(\s?)</string>
					<key>end</key>
					<string>(\s?)}</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#antlers-expression</string>
						</dict>
					</array>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.statamic</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.statamic</string>
				</dict>
			</dict>
		</dict>
		<key>string-single-quoted</key>
		<dict>
			<key>name</key>
			<string>string.quoted.single.statamic</string>
			<key>begin</key>
			<string>&apos;</string>
			<key>end</key>
			<string>&apos;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.character.escape.statamic</string>
					<key>match</key>
					<string>\\[\\&apos;]</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;!@){(\s?)</string>
					<key>end</key>
					<string>(\s?)}</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#antlers-expression</string>
						</dict>
					</array>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.statamic</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.statamic</string>
				</dict>
			</dict>
		</dict>
	</dict>
	<key>injections</key>
	<dict>
		<key>text.html.statamic</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#statamic-comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#antlers-tags</string>
				</dict>
			</array>
		</dict>
		<key>text.html.statamic - (meta.embedded | meta.tag | comment.block.statamic), L:(text.html.statamic meta.tag - (comment.block.statamic | meta.embedded.statamic))</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
			</array>
		</dict>
		<key>text.html.statamic - (meta.embedded | meta.tag), L:((text.html.statamic meta.tag) - (meta.embedded.block.php | meta.embedded.line.php)), L:(source.js - (meta.embedded.block.php | meta.embedded.line.php)), L:(source.css - (meta.embedded.block.php | meta.embedded.line.php))</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#php-tag</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>antlers.html</string>
		<string>antlers.php</string>
		<string>antlers.xml</string>
	</array>
</dict>
</plist>
