<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Apollo Guidance Computer</string>
	<key>scopeName</key>
	<string>source.agc</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#main</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>comment.line.number-sign.agc</string>
					<key>begin</key>
					<string>#</string>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>disable-todo</string>
							<key>match</key>
							<string>TODO|FIXME|CHANGED|XXX|IDEA|HACK|NOTE|REVIEW|NB|BUG</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.agc</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>comment.annotation.numeric.agc</string>
					<key>match</key>
					<string>^\t[-+]\d+(?=\t)</string>
				</dict>
			</array>
		</dict>
		<key>identifier</key>
		<dict>
			<key>name</key>
			<string>entity.name.identifier.agc</string>
			<key>match</key>
			<string>^(?!\$)(?:[^#\s]{1,7}\t|[^#\s]{8})</string>
		</dict>
		<key>inclusion</key>
		<dict>
			<key>name</key>
			<string>meta.preprocessor.include.directive.agc</string>
			<key>begin</key>
			<string>^\$</string>
			<key>end</key>
			<string>(?=\s)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.directive.agc</string>
				</dict>
			</dict>
		</dict>
		<key>main</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inclusion</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#identifier</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#opcode</string>
				</dict>
			</array>
		</dict>
		<key>number</key>
		<dict>
			<key>name</key>
			<string>constant.numeric.agc</string>
			<key>match</key>
			<string>[-+]\d+(?:\.\d+)?D?</string>
		</dict>
		<key>opcode</key>
		<dict>
			<key>name</key>
			<string>meta.opcode.agc</string>
			<key>begin</key>
			<string>(?&lt;=\t)([^#\s]+)(?=\s|$)</string>
			<key>end</key>
			<string>$|(?=#)|[^#\s]+</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.function.opcode.agc</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.operand.agc</string>
				</dict>
			</dict>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>agc</string>
	</array>
</dict>
</plist>
