<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>AsciiDoc</string>
	<key>scopeName</key>
	<string>text.html.asciidoc</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#heading_inline</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#heading-block</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#heading-blockattr</string>
		</dict>
		<dict>
			<key>name</key>
			<string>comment.block.passthrough.macro.doubledollar.asciidoc</string>
			<key>begin</key>
			<string>\$\$(?!\$)</string>
			<key>end</key>
			<string>\$\$(?!\$)</string>
		</dict>
		<dict>
			<key>name</key>
			<string>comment.block.passthrough.macro.tripeplus.asciidoc</string>
			<key>begin</key>
			<string>\+\+\+(?!\+)</string>
			<key>end</key>
			<string>\+\+\+(?!\+)</string>
		</dict>
		<dict>
			<key>name</key>
			<string>comment.line.double-slash.asciidoc</string>
			<key>match</key>
			<string>(//).*$\n?</string>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.block-level.asciidoc</string>
			<key>begin</key>
			<string>(?x)^
				(?=	([/+-.*_=]{4,})\s*$
				|	([ \t]{1,})
				|	[=]{1,6}\s*+
				|	[ ]{0,3}(?&lt;marker&gt;[-*_])([ ]{0,2}\k&lt;marker&gt;){2,}[ \t]*+$
				)</string>
			<key>end</key>
			<string>(?x)^
				(?!	\1
				|	([ \t]{1,})
				|	[=]{1,6}\s*+
				|	[ ]{0,3}(?&lt;marker&gt;[-*_])([ ]{0,2}\k&lt;marker&gt;){2,}[ \t]*+$
				)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#block_quote</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block_raw</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#heading_inline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#heading-block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#separator</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>name</key>
			<string>markup.list.unnumbered.asciidoc</string>
			<key>begin</key>
			<string>^[ ]{0,3}([*+-])(?=\s)</string>
			<key>end</key>
			<string>^(?=\S)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#list-paragraph</string>
				</dict>
			</array>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.list_item.asciidoc</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>markup.list.numbered.asciidoc</string>
			<key>begin</key>
			<string>^[ ]{0,3}[0-9]+(\.)(?=\s)</string>
			<key>end</key>
			<string>^(?=\S)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#list-paragraph</string>
				</dict>
			</array>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.list_item.asciidoc</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>comment.block.asciidoc</string>
			<key>begin</key>
			<string>^([/+-.*_=]){4,}\s*$</string>
			<key>end</key>
			<string>^\1{4,}\s*$</string>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.disable-asciidoc</string>
			<key>begin</key>
			<string>^([/+.]){4,}\s*$</string>
			<key>end</key>
			<string>^[/+.]{4,}\s*$</string>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.paragraph.asciidoc</string>
			<key>begin</key>
			<string>^(?=\S)(?![=-]{3,}(?=$))(?!\.\S+)</string>
			<key>end</key>
			<string>^(?:\s*$|(?=[ ]{0,3}&gt;.))|(?=[ \t]*\n)(?&lt;=^===|^====|=====|^---|^----|-----)[ \t]*\n</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
				<dict>
					<key>name</key>
					<string>markup.heading.0.asciidoc</string>
					<key>match</key>
					<string>^(={3,})(?=[ \t]*$)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.heading.asciidoc</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>markup.heading.1.asciidoc</string>
					<key>match</key>
					<string>^(-{3,})(?=[ \t]*$)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.heading.asciidoc</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>markup.heading.2.asciidoc</string>
					<key>match</key>
					<string>^(~{3,})(?=[ \t]*$)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.heading.asciidoc</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>markup.heading.3.asciidoc</string>
					<key>match</key>
					<string>^(\^{3,})(?=[ \t]*$)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.heading.asciidoc</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>markup.heading.4.asciidoc</string>
					<key>match</key>
					<string>^(\+{3,})(?=[ \t]*$)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.heading.asciidoc</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>attribute-entry</key>
		<dict>
			<key>name</key>
			<string>variable.other</string>
			<key>match</key>
			<string>^:[-_. A-Za-z0-9]+:\s*(.*)\s*$</string>
		</dict>
		<key>attribute-reference</key>
		<dict>
			<key>name</key>
			<string>variable.other</string>
			<key>match</key>
			<string>{[-_. A-Za-z0-9]+}</string>
		</dict>
		<key>attribute-reference-predefined</key>
		<dict>
			<key>name</key>
			<string>support.variable</string>
			<key>match</key>
			<string>{(?i:amp|asciidoc-dir|asciidoc-file|asciidoc-version|author|authored|authorinitials|backend-docbook|backend-xhtml11|backend-html4|docbook-article|xhtml11-article|html4-article|docbook-book|xhtml11-book|html4-book|docbook-manpage|xhtml11-manpage|html4-manpage|backend|backslash|basebackend|brvbar|date|docdate|doctime|docname|docfile|docdir|doctitle|doctype-article|doctype-book|doctype-manpage|doctype|email|empty|encoding|filetype|firstname|gt|id|indir|infile|lastname|level|listindex|localdate|localtime|lt|manname|manpurpose|mantitle|manvolnum|middlename|nbsp|outdir|outfile|reftext|revision|sectnum|showcomments|title|two_colons|two_semicolons|user-dir|verbose)}</string>
		</dict>
		<key>block_quote</key>
		<dict>
			<key>name</key>
			<string>comment.block.asciidoc</string>
			<key>begin</key>
			<string>^([/+-.*_=]){4,}\s*$</string>
			<key>end</key>
			<string>^\1{4,}\s*$</string>
		</dict>
		<key>block_raw</key>
		<dict>
			<key>name</key>
			<string>markup.raw.block.asciidoc</string>
			<key>match</key>
			<string>\G([ ]{4}|\t).*$\n?</string>
		</dict>
		<key>bracket</key>
		<dict>
			<key>name</key>
			<string>meta.other.valid-bracket.asciidoc</string>
			<key>match</key>
			<string>&lt;(?![a-z/?\$!])</string>
		</dict>
		<key>character-replacements</key>
		<dict>
			<key>name</key>
			<string>constant.character.asciidoc</string>
			<key>match</key>
			<string>\(C\)|\(R\)|\(TM\)|--(?!-)|\.\.\.(?!\.)|-&gt;|&lt;-|=&gt;|&lt;=</string>
		</dict>
		<key>escape</key>
		<dict>
			<key>name</key>
			<string>constant.character.escape.asciidoc</string>
			<key>match</key>
			<string>\\[-`*_#+.!(){}\[\]\\&gt;:]</string>
		</dict>
		<key>heading</key>
		<dict>
			<key>name</key>
			<string>markup.heading.asciidoc</string>
			<key>contentName</key>
			<string>entity.name.section.asciidoc</string>
			<key>match</key>
			<string>(?m)^(\S+)$([=-~^+])+\s*$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.heading.asciidoc</string>
				</dict>
			</dict>
		</dict>
		<key>heading-block</key>
		<dict>
			<key>name</key>
			<string>markup.heading.asciidoc</string>
			<key>match</key>
			<string>^\.(\w.*)$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.heading.asciidoc</string>
				</dict>
			</dict>
		</dict>
		<key>heading-blockattr</key>
		<dict>
			<key>name</key>
			<string>markup.heading.asciidoc</string>
			<key>match</key>
			<string>^\[\[?(\w.*)\]$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.heading.asciidoc</string>
				</dict>
			</dict>
		</dict>
		<key>heading_inline</key>
		<dict>
			<key>name</key>
			<string>markup.heading.asciidoc</string>
			<key>contentName</key>
			<string>entity.name.section.asciidoc</string>
			<key>begin</key>
			<string>\G(={1,6})(?!=)\s*(?=\S)</string>
			<key>end</key>
			<string>\s*(=*)$\n?</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.heading.asciidoc</string>
				</dict>
			</dict>
		</dict>
		<key>inline</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#line-break</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#line-page-break</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#line-ruler</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#escape</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#passthrough-macro-trippleplus-inline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#passthrough-macro-doubledollar-inline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#character-replacements</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#text-xref</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bracket</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#raw</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#text-quote-single</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#text-quote-double</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#text-quote-other</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#text-bold-unconstrained</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#text-italic-unconstrained</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#text-monospace-unconstrained</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#text-unquoted-unconstrained</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#text-footnote</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#text-indexterm</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#text-macro</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#text-image</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#text-anchor</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#text-link</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#text-mail-link</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#text-bold</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#text-italic</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#text-monospace</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#text-unquoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#text-footnote</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#attribute-entry</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#attribute-reference-predefined</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#attribute-reference</string>
				</dict>
			</array>
		</dict>
		<key>line-break</key>
		<dict>
			<key>name</key>
			<string>constant.character.escape.asciidoc</string>
			<key>match</key>
			<string>(?&lt;=\S)\s+\+$</string>
		</dict>
		<key>line-page-break</key>
		<dict>
			<key>name</key>
			<string>constant.character.escape.asciidoc</string>
			<key>match</key>
			<string>^&lt;{3,}$</string>
		</dict>
		<key>line-ruler</key>
		<dict>
			<key>name</key>
			<string>constant.character.escape.asciidoc</string>
			<key>match</key>
			<string>^&apos;{3,}$</string>
		</dict>
		<key>list-paragraph</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.paragraph.list.asciidoc</string>
					<key>begin</key>
					<string>\G\s+(?=\S)</string>
					<key>end</key>
					<string>^\s*$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>passthrough-macro-doubledollar-inline</key>
		<dict>
			<key>name</key>
			<string>comment.block.passthrough.asciidoc</string>
			<key>match</key>
			<string>(?:\[.*\])?\$\$(?!\$).+\$\$(?!\$)</string>
		</dict>
		<key>passthrough-macro-trippleplus-inline</key>
		<dict>
			<key>name</key>
			<string>comment.block.passthrough.asciidoc</string>
			<key>match</key>
			<string>(?:\[.*\])?\+\+\+(?!\+).+\+\+\+(?!\+)</string>
		</dict>
		<key>raw</key>
		<dict>
			<key>name</key>
			<string>markup.raw.inline.asciidoc</string>
			<key>match</key>
			<string>(`+)([^`]|(?!(?&lt;!`)\1(?!`))`)*+(\1)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.asciidoc</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.asciidoc</string>
				</dict>
			</dict>
		</dict>
		<key>separator</key>
		<dict>
			<key>name</key>
			<string>meta.separator.asciidoc</string>
			<key>match</key>
			<string>\G[ ]{0,3}([-*_])([ ]{0,2}\1){2,}[ \t]*$\n?</string>
		</dict>
		<key>text-anchor</key>
		<dict>
			<key>name</key>
			<string>markup.underline.link.anchor.asciidoc</string>
			<key>match</key>
			<string>(?:\[\[.*?\]\])|(?:\banchor:[^\[\s]+(?:\[.*?\])?)</string>
		</dict>
		<key>text-bold</key>
		<dict>
			<key>name</key>
			<string>markup.bold.asciidoc</string>
			<key>begin</key>
			<string>(?&lt;!\w)(\*)(?=\S)</string>
			<key>end</key>
			<string>(?&lt;=\S)(\1)(?!\w)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.bold.asciidoc</string>
				</dict>
			</dict>
		</dict>
		<key>text-bold-unconstrained</key>
		<dict>
			<key>name</key>
			<string>markup.bold.asciidoc</string>
			<key>begin</key>
			<string>(\*\*)(?=\S)</string>
			<key>end</key>
			<string>(?&lt;=\S)(\1)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.bold.asciidoc</string>
				</dict>
			</dict>
		</dict>
		<key>text-footnote</key>
		<dict>
			<key>name</key>
			<string>string.quoted.single.asciidoc</string>
			<key>match</key>
			<string>\bfootnote(?:ref)?:\[.*?\]</string>
		</dict>
		<key>text-image</key>
		<dict>
			<key>name</key>
			<string>markup.underline.link.image.asciidoc</string>
			<key>match</key>
			<string>\b(?:image|link):[^\[\s]+(?:\[.*?\])?</string>
		</dict>
		<key>text-indexterm</key>
		<dict>
			<key>name</key>
			<string>string.quoted.single.asciidoc</string>
			<key>match</key>
			<string>(?:\bindexterm2?:\[.*?\])|(?:\(\(\(?.*?\)?\)\))</string>
		</dict>
		<key>text-italic</key>
		<dict>
			<key>name</key>
			<string>markup.italic.asciidoc</string>
			<key>begin</key>
			<string>(?&lt;!\w)(&apos;|_)(?=\S)</string>
			<key>end</key>
			<string>(?&lt;=\S)(\1)((?!\1)|(?=\1\1))(?!\w)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.italic.asciidoc</string>
				</dict>
			</dict>
		</dict>
		<key>text-italic-unconstrained</key>
		<dict>
			<key>name</key>
			<string>markup.italic.asciidoc</string>
			<key>begin</key>
			<string>(__)(?=\S)</string>
			<key>end</key>
			<string>(?&lt;=\S)(\1)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.italic.asciidoc</string>
				</dict>
			</dict>
		</dict>
		<key>text-link</key>
		<dict>
			<key>name</key>
			<string>markup.underline.link.inet.asciidoc</string>
			<key>match</key>
			<string>\b(?:http|mailto):[^\[\s]+(?:\[.*?\])?</string>
		</dict>
		<key>text-macro</key>
		<dict>
			<key>name</key>
			<string>string.quoted.single.asciidoc</string>
			<key>match</key>
			<string>\S+::[^\[\s]+(?:\[.*?\])?</string>
		</dict>
		<key>text-mail-link</key>
		<dict>
			<key>name</key>
			<string>markup.underline.link.email.asciidoc</string>
			<key>match</key>
			<string>\b[^@\s]+@[^@\s]+\b</string>
		</dict>
		<key>text-monospace</key>
		<dict>
			<key>name</key>
			<string>string.interpolated.asciidoc</string>
			<key>match</key>
			<string>(?&lt;!\w)([\+`]).*(\1)(?!\w)</string>
		</dict>
		<key>text-monospace-unconstrained</key>
		<dict>
			<key>name</key>
			<string>string.interpolated.asciidoc</string>
			<key>match</key>
			<string>(\+\+).*(\1)</string>
		</dict>
		<key>text-quote-double</key>
		<dict>
			<key>name</key>
			<string>string.quoted.double.asciidoc</string>
			<key>match</key>
			<string>(?&lt;!\w)(?:\[.*\])?``(?!`).*&apos;&apos;(?!&apos;)(?!\w)</string>
		</dict>
		<key>text-quote-other</key>
		<dict>
			<key>name</key>
			<string>string.quoted.single.asciidoc</string>
			<key>match</key>
			<string>(?&lt;!\w)(?:\[.*\])?([~^]).*(\1)(?!\w)</string>
		</dict>
		<key>text-quote-single</key>
		<dict>
			<key>name</key>
			<string>string.quoted.single.asciidoc</string>
			<key>match</key>
			<string>(?&lt;!\w)(?:\[.*\])?`(?!`).*&apos;(?!&apos;)(?!\w)</string>
		</dict>
		<key>text-unquoted</key>
		<dict>
			<key>name</key>
			<string>string.unquoted.asciidoc</string>
			<key>match</key>
			<string>(?&lt;!\w)(#).*(\1)(?!\w)</string>
		</dict>
		<key>text-unquoted-unconstrained</key>
		<dict>
			<key>name</key>
			<string>string.unquoted.asciidoc</string>
			<key>match</key>
			<string>(##).*(\1)</string>
		</dict>
		<key>text-xref</key>
		<dict>
			<key>name</key>
			<string>markup.underline.link.xref.asciidoc</string>
			<key>match</key>
			<string>(?:&lt;&lt;.*?&gt;&gt;)|(?:\bxref:[^\[\s]+(?:\[.*?\])?)</string>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>asciidoc</string>
		<string>adoc</string>
		<string>asc</string>
	</array>
</dict>
</plist>
