<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Astro</string>
	<key>scopeName</key>
	<string>source.astro</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#scope</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#frontmatter</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>attributes</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#attributes-events</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#attributes-keyvalue</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#attributes-interpolated</string>
				</dict>
			</array>
		</dict>
		<key>attributes-events</key>
		<dict>
			<key>name</key>
			<string>meta.attribute.$1.astro</string>
			<key>begin</key>
			<string>(on(s(croll|t(orage|alled)|u(spend|bmit)|e(curitypolicyviolation|ek(ing|ed)|lect))|hashchange|c(hange|o(ntextmenu|py)|u(t|echange)|l(ick|ose)|an(cel|play(through)?))|t(imeupdate|oggle)|in(put|valid)|o(nline|ffline)|d(urationchange|r(op|ag(start|over|e(n(ter|d)|xit)|leave)?)|blclick)|un(handledrejection|load)|p(opstate|lay(ing)?|a(ste|use|ge(show|hide))|rogress)|e(nded|rror|mptied)|volumechange|key(down|up|press)|focus|w(heel|aiting)|l(oad(start|e(nd|d(data|metadata)))?|anguagechange)|a(uxclick|fterprint|bort)|r(e(s(ize|et)|jectionhandled)|atechange)|m(ouse(o(ut|ver)|down|up|enter|leave|move)|essage(error)?)|b(efore(unload|print)|lur)))(?![\\w:-])</string>
			<key>end</key>
			<string>(?=\s*+[^=\s])</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>=</string>
					<key>end</key>
					<string>(?&lt;=[^\s=])(?!\s*=)|(?=/?&gt;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>meta.embedded.line.js</string>
							<key>begin</key>
							<string>(?=[^\s=&lt;&gt;`/]|/(?!&gt;))</string>
							<key>end</key>
							<string>(?!\G)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>name</key>
									<string>string.unquoted.astro</string>
									<key>match</key>
									<string>(([^\s\&quot;&apos;=&lt;&gt;`/]|/(?!&gt;))+)</string>
									<key>captures</key>
									<dict>
										<key>0</key>
										<dict>
											<key>name</key>
											<string>source.js</string>
										</dict>
										<key>1</key>
										<dict>
											<key>patterns</key>
											<array>
												<dict>
													<key>include</key>
													<string>source.js</string>
												</dict>
											</array>
										</dict>
									</dict>
								</dict>
								<dict>
									<key>name</key>
									<string>string.quoted.astro</string>
									<key>begin</key>
									<string>([&quot;])</string>
									<key>end</key>
									<string>\1</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>match</key>
											<string>([^\n\&quot;/]|/(?![/*]))+</string>
											<key>captures</key>
											<dict>
												<key>0</key>
												<dict>
													<key>patterns</key>
													<array>
														<dict>
															<key>include</key>
															<string>source.js</string>
														</dict>
													</array>
												</dict>
											</dict>
										</dict>
										<dict>
											<key>name</key>
											<string>comment.line.double-slash.js</string>
											<key>begin</key>
											<string>//</string>
											<key>end</key>
											<string>(?=\&quot;)|\n</string>
											<key>beginCaptures</key>
											<dict>
												<key>0</key>
												<dict>
													<key>name</key>
													<string>punctuation.definition.comment.js</string>
												</dict>
											</dict>
										</dict>
										<dict>
											<key>name</key>
											<string>comment.block.js</string>
											<key>begin</key>
											<string>/\*</string>
											<key>end</key>
											<string>(?=\&quot;)|\*/</string>
											<key>beginCaptures</key>
											<dict>
												<key>0</key>
												<dict>
													<key>name</key>
													<string>punctuation.definition.comment.begin.js</string>
												</dict>
											</dict>
											<key>endCaptures</key>
											<dict>
												<key>0</key>
												<dict>
													<key>name</key>
													<string>punctuation.definition.comment.end.js</string>
												</dict>
											</dict>
										</dict>
									</array>
									<key>beginCaptures</key>
									<dict>
										<key>0</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.string.begin.astro</string>
										</dict>
									</dict>
									<key>endCaptures</key>
									<dict>
										<key>0</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.string.end.astro</string>
										</dict>
									</dict>
								</dict>
								<dict>
									<key>name</key>
									<string>string.quoted.astro</string>
									<key>begin</key>
									<string>([&apos;])</string>
									<key>end</key>
									<string>\1</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>match</key>
											<string>([^\n\&apos;/]|/(?![/*]))+</string>
											<key>captures</key>
											<dict>
												<key>0</key>
												<dict>
													<key>patterns</key>
													<array>
														<dict>
															<key>include</key>
															<string>source.js</string>
														</dict>
													</array>
												</dict>
											</dict>
										</dict>
										<dict>
											<key>name</key>
											<string>comment.line.double-slash.js</string>
											<key>begin</key>
											<string>//</string>
											<key>end</key>
											<string>(?=\&apos;)|\n</string>
											<key>beginCaptures</key>
											<dict>
												<key>0</key>
												<dict>
													<key>name</key>
													<string>punctuation.definition.comment.js</string>
												</dict>
											</dict>
										</dict>
										<dict>
											<key>name</key>
											<string>comment.block.js</string>
											<key>begin</key>
											<string>/\*</string>
											<key>end</key>
											<string>(?=\&apos;)|\*/</string>
											<key>beginCaptures</key>
											<dict>
												<key>0</key>
												<dict>
													<key>name</key>
													<string>punctuation.definition.comment.begin.js</string>
												</dict>
											</dict>
											<key>endCaptures</key>
											<dict>
												<key>0</key>
												<dict>
													<key>name</key>
													<string>punctuation.definition.comment.end.js</string>
												</dict>
											</dict>
										</dict>
									</array>
									<key>beginCaptures</key>
									<dict>
										<key>0</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.string.begin.astro</string>
										</dict>
									</dict>
									<key>endCaptures</key>
									<dict>
										<key>0</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.string.end.astro</string>
										</dict>
									</dict>
								</dict>
							</array>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.key-value.astro</string>
						</dict>
					</dict>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.astro</string>
							<key>match</key>
							<string>.*</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>attributes-interpolated</key>
		<dict>
			<key>contentName</key>
			<string>meta.embedded.expression.astro source.tsx</string>
			<key>begin</key>
			<string>(?&lt;!:|=)\s*({)</string>
			<key>end</key>
			<string>(\})</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.tsx</string>
				</dict>
			</array>
		</dict>
		<key>attributes-keyvalue</key>
		<dict>
			<key>name</key>
			<string>meta.attribute.$1.astro</string>
			<key>begin</key>
			<string>([_@$[:alpha:]][:._\-$[:alnum:]]*)</string>
			<key>end</key>
			<string>(?=\s*+[^=\s])</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>=</string>
					<key>end</key>
					<string>(?&lt;=[^\s=])(?!\s*=)|(?=/?&gt;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#attributes-value</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.key-value.astro</string>
						</dict>
					</dict>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.astro</string>
							<key>match</key>
							<string>.*</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>attributes-value</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#interpolation</string>
				</dict>
				<dict>
					<key>name</key>
					<string>string.unquoted.astro</string>
					<key>match</key>
					<string>([^\s&quot;&apos;=&lt;&gt;`/]|/(?!&gt;))+</string>
				</dict>
				<dict>
					<key>name</key>
					<string>string.quoted.astro</string>
					<key>begin</key>
					<string>([&apos;&quot;])</string>
					<key>end</key>
					<string>\1</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.astro</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.astro</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>string.template.astro</string>
					<key>begin</key>
					<string>(`)</string>
					<key>end</key>
					<string>\1</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.tsx#template-substitution-element</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>name</key>
			<string>comment.block.astro</string>
			<key>begin</key>
			<string>&lt;!--</string>
			<key>end</key>
			<string>--&gt;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>invalid.illegal.characters-not-allowed-here.astro</string>
					<key>match</key>
					<string>\G-?&gt;|&lt;!--(?!&gt;)|&lt;!-(?=--&gt;)|--!&gt;</string>
				</dict>
			</array>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.astro</string>
				</dict>
			</dict>
		</dict>
		<key>frontmatter</key>
		<dict>
			<key>contentName</key>
			<string>source.ts</string>
			<key>begin</key>
			<string>\A(-{3})\s*$</string>
			<key>end</key>
			<string>(^|\G)(-{3})|\.{3}\s*$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.ts</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
			</dict>
		</dict>
		<key>interpolation</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>contentName</key>
					<string>meta.embedded.expression.astro source.tsx</string>
					<key>begin</key>
					<string>\{</string>
					<key>end</key>
					<string>\}</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>\G\s*(?={)</string>
							<key>end</key>
							<string>(?&lt;=})</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.tsx#object-literal</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>include</key>
							<string>source.tsx</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.begin.astro</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.end.astro</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>scope</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tags</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#interpolation</string>
				</dict>
				<dict>
					<key>name</key>
					<string>text.astro</string>
					<key>begin</key>
					<string>(?&lt;=&gt;|})</string>
					<key>end</key>
					<string>(?=&lt;|{)</string>
				</dict>
			</array>
		</dict>
		<key>tags</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tags-raw</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tags-lang</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tags-void</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tags-general-end</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tags-general-start</string>
				</dict>
			</array>
		</dict>
		<key>tags-end-node</key>
		<dict>
			<key>match</key>
			<string>(&lt;/)(.*?)\s*(&gt;)|(/&gt;)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.tag.end.astro punctuation.definition.tag.begin.astro</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.tag.end.astro</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tags-name</string>
						</dict>
					</array>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>meta.tag.end.astro punctuation.definition.tag.end.astro</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>meta.tag.start.astro punctuation.definition.tag.end.astro</string>
				</dict>
			</dict>
		</dict>
		<key>tags-general-end</key>
		<dict>
			<key>name</key>
			<string>meta.scope.tag.$2.astro</string>
			<key>begin</key>
			<string>(&lt;/)([^/\s&gt;]*)</string>
			<key>end</key>
			<string>(&gt;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.tag.end.astro punctuation.definition.tag.begin.astro</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.tag.end.astro</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tags-name</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.tag.end.astro punctuation.definition.tag.end.astro</string>
				</dict>
			</dict>
		</dict>
		<key>tags-general-start</key>
		<dict>
			<key>name</key>
			<string>meta.scope.tag.$2.astro</string>
			<key>begin</key>
			<string>(&lt;)([^/\s&gt;/]*)</string>
			<key>end</key>
			<string>(/?&gt;)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tags-start-attributes</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tags-start-node</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.tag.start.astro punctuation.definition.tag.end.astro</string>
				</dict>
			</dict>
		</dict>
		<key>tags-lang</key>
		<dict>
			<key>name</key>
			<string>meta.scope.tag.$1.astro meta.$1.astro</string>
			<key>begin</key>
			<string>&lt;(script|style)</string>
			<key>end</key>
			<string>&lt;/\1\s*&gt;|/&gt;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.lang.json.astro</string>
					<key>begin</key>
					<string>\G(?=\s*[^&gt;]*?(type|lang)\s*=\s*([&apos;&quot;]|)(?:text\/)?(application\/ld\+json)\2)</string>
					<key>end</key>
					<string>(?=&lt;/|/&gt;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tags-lang-start-attributes</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.lang.javascript.astro</string>
					<key>begin</key>
					<string>\G(?=\s*[^&gt;]*?(type|lang)\s*=\s*([&apos;&quot;]|)(module)\2)</string>
					<key>end</key>
					<string>(?=&lt;/|/&gt;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tags-lang-start-attributes</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.lang.$3.astro</string>
					<key>begin</key>
					<string>\G(?=\s*[^&gt;]*?(type|lang)\s*=\s*([&apos;&quot;]|)(?:text/|application/)?([\w\/+]+)\2)</string>
					<key>end</key>
					<string>(?=&lt;/|/&gt;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tags-lang-start-attributes</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#tags-lang-start-attributes</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tags-start-node</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tags-end-node</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>tags-lang-start-attributes</key>
		<dict>
			<key>name</key>
			<string>meta.tag.start.astro</string>
			<key>begin</key>
			<string>\G</string>
			<key>end</key>
			<string>(?=/&gt;)|&gt;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#attributes</string>
				</dict>
			</array>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.astro</string>
				</dict>
			</dict>
		</dict>
		<key>tags-name</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>support.class.component.astro</string>
					<key>match</key>
					<string>[A-Z][a-zA-Z0-9_]*</string>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.tag.custom.astro entity.name.tag.astro</string>
					<key>match</key>
					<string>[a-z][\w0-9:]*-[\w0-9:-]*</string>
				</dict>
				<dict>
					<key>name</key>
					<string>entity.name.tag.astro</string>
					<key>match</key>
					<string>[a-z][\w0-9:-]*</string>
				</dict>
			</array>
		</dict>
		<key>tags-raw</key>
		<dict>
			<key>name</key>
			<string>meta.scope.tag.$1.astro meta.raw.astro</string>
			<key>contentName</key>
			<string>source.unknown</string>
			<key>begin</key>
			<string>&lt;([^/?!\s&lt;&gt;]+)(?=[^&gt;]+is:raw).*?</string>
			<key>end</key>
			<string>&lt;/\1\s*&gt;|/&gt;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tags-lang-start-attributes</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tags-start-node</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tags-end-node</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>tags-start-attributes</key>
		<dict>
			<key>name</key>
			<string>meta.tag.start.astro</string>
			<key>begin</key>
			<string>\G</string>
			<key>end</key>
			<string>(?=/?&gt;)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#attributes</string>
				</dict>
			</array>
		</dict>
		<key>tags-start-node</key>
		<dict>
			<key>name</key>
			<string>meta.tag.start.astro</string>
			<key>match</key>
			<string>(&lt;)([^/\s&gt;/]*)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.astro</string>
				</dict>
				<key>2</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tags-name</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>tags-void</key>
		<dict>
			<key>name</key>
			<string>meta.tag.void.astro</string>
			<key>begin</key>
			<string>(&lt;)(area|base|br|col|embed|hr|img|input|link|meta|param|source|track|wbr)(?=\s|/?&gt;)</string>
			<key>end</key>
			<string>/?&gt;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#attributes</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.astro</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.astro</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.astro</string>
				</dict>
			</dict>
		</dict>
	</dict>
	<key>injections</key>
	<dict>
		<key>L:(meta.script.astro) (meta.lang.js | meta.lang.javascript | meta.lang.partytown | meta.lang.node) - (meta source)</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.embedded.block.astro</string>
					<key>contentName</key>
					<string>source.js</string>
					<key>begin</key>
					<string>(?&lt;=&gt;)(?!&lt;/)</string>
					<key>end</key>
					<string>(?=&lt;/)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>L:(meta.script.astro) (meta.lang.json) - (meta source)</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.embedded.block.astro</string>
					<key>contentName</key>
					<string>source.json</string>
					<key>begin</key>
					<string>(?&lt;=&gt;)(?!&lt;/)</string>
					<key>end</key>
					<string>(?=&lt;/)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.json</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>L:(meta.script.astro) (meta.lang.ts | meta.lang.typescript) - (meta source)</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.embedded.block.astro</string>
					<key>contentName</key>
					<string>source.ts</string>
					<key>begin</key>
					<string>(?&lt;=&gt;)(?!&lt;/)</string>
					<key>end</key>
					<string>(?=&lt;/)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.ts</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>L:meta.script.astro - meta.lang - (meta source)</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.embedded.block.astro</string>
					<key>contentName</key>
					<string>source.js</string>
					<key>begin</key>
					<string>(?&lt;=&gt;)(?!&lt;/)</string>
					<key>end</key>
					<string>(?=&lt;/)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>L:meta.style.astro - meta.lang - (meta source)</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.embedded.block.astro</string>
					<key>contentName</key>
					<string>source.css</string>
					<key>begin</key>
					<string>(?&lt;=&gt;)(?!&lt;/)</string>
					<key>end</key>
					<string>(?=&lt;/)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.css</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>L:meta.style.astro meta.lang.css - (meta source)</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.embedded.block.astro</string>
					<key>contentName</key>
					<string>source.css</string>
					<key>begin</key>
					<string>(?&lt;=&gt;)(?!&lt;/)</string>
					<key>end</key>
					<string>(?=&lt;/)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.css</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>L:meta.style.astro meta.lang.less - (meta source)</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.embedded.block.astro</string>
					<key>contentName</key>
					<string>source.css.less</string>
					<key>begin</key>
					<string>(?&lt;=&gt;)(?!&lt;/)</string>
					<key>end</key>
					<string>(?=&lt;/)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.css.less</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>L:meta.style.astro meta.lang.postcss - (meta source)</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.embedded.block.astro</string>
					<key>contentName</key>
					<string>source.css.postcss</string>
					<key>begin</key>
					<string>(?&lt;=&gt;)(?!&lt;/)</string>
					<key>end</key>
					<string>(?=&lt;/)</string>
					<key>patterns</key>
					<array>
						<dict>

						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>L:meta.style.astro meta.lang.sass - (meta source)</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.embedded.block.astro</string>
					<key>contentName</key>
					<string>source.sass</string>
					<key>begin</key>
					<string>(?&lt;=&gt;)(?!&lt;/)</string>
					<key>end</key>
					<string>(?=&lt;/)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.sass</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>L:meta.style.astro meta.lang.scss - (meta source)</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.embedded.block.astro</string>
					<key>contentName</key>
					<string>source.css.scss</string>
					<key>begin</key>
					<string>(?&lt;=&gt;)(?!&lt;/)</string>
					<key>end</key>
					<string>(?=&lt;/)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.css.scss</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>L:meta.style.astro meta.lang.stylus - (meta source)</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.embedded.block.astro</string>
					<key>contentName</key>
					<string>source.stylus</string>
					<key>begin</key>
					<string>(?&lt;=&gt;)(?!&lt;/)</string>
					<key>end</key>
					<string>(?=&lt;/)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.stylus</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>astro</string>
	</array>
</dict>
</plist>
