<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Avro</string>
	<key>scopeName</key>
	<string>source.avro</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#decorators</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#protocol</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#contents</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>collections</key>
		<dict>
			<key>name</key>
			<string>meta.collection</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>contentName</key>
					<string>meta.type.collection.avro</string>
					<key>begin</key>
					<string>\b(array|map)\s*&lt;</string>
					<key>end</key>
					<string>&gt;</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#types</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#decorators</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#declared_type</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.collection.avro</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>name</key>
			<string>meta.comments</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>comment.line.double-slash.avro</string>
					<key>begin</key>
					<string>//</string>
					<key>end</key>
					<string>$</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.avro</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>comment.block.avro</string>
					<key>begin</key>
					<string>/\*</string>
					<key>end</key>
					<string>\*/</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.avro</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>constants</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.language.avro</string>
					<key>match</key>
					<string>\b(true|false|null)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.avro</string>
					<key>match</key>
					<string>\b[A-Z][A-Z0-9_]*\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.avro</string>
					<key>match</key>
					<string>\b-?[0-9]+(\.[0-9]*)?\b</string>
				</dict>
			</array>
		</dict>
		<key>contents</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#decorators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#record</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#error</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#declaration</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#import</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#union</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#fixed</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#collections</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#throws</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#declared_type</string>
				</dict>
			</array>
		</dict>
		<key>decimal</key>
		<dict>
			<key>match</key>
			<string>\b(decimal)\s*\(([^)]+)\)([^;]*)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type.logical.avro</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.decimal.length</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>name</key>
							<string>constant.numeric.avro</string>
							<key>match</key>
							<string>\b[0-9]+\b</string>
						</dict>
					</array>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>meta.decimal.avro</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#decorators</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#variable</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>declaration</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>contentName</key>
					<string>meta.enum.declaration.avro</string>
					<key>begin</key>
					<string>\b(enum)\s+(\w+)\s*{</string>
					<key>end</key>
					<string>}</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#decorators</string>
						</dict>
						<dict>
							<key>name</key>
							<string>variable.other.enummember.avro</string>
							<key>match</key>
							<string>\b\w+\b</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.struct.enum.avro</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.avro</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>declared_type</key>
		<dict>
			<key>name</key>
			<string>entity.name.type</string>
			<key>match</key>
			<string>\w+</string>
		</dict>
		<key>decorators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.decorator</string>
					<key>contentName</key>
					<string>meta.decorator.avro</string>
					<key>begin</key>
					<string>(@[-\w]+)\s*\(</string>
					<key>end</key>
					<string>\)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#object</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.decorator.name.avro</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>name</key>
									<string>keyword.control.avro</string>
									<key>match</key>
									<string>@(aliases|namespace|order)</string>
								</dict>
								<dict>
									<key>name</key>
									<string>entity.name.tag.avro</string>
									<key>match</key>
									<string>@[-\w]+</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>error</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>contentName</key>
					<string>meta.error.avro</string>
					<key>begin</key>
					<string>\b(error)\s+(\w*)\s*{</string>
					<key>end</key>
					<string>}</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#decorators</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#field</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.struct.error.avro</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.avro</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>field</key>
		<dict>
			<key>name</key>
			<string>meta.field</string>
			<key>begin</key>
			<string>(?=\S)</string>
			<key>end</key>
			<string>;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#decorators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#field_base_type_entry</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#field_user_type_entry</string>
				</dict>
			</array>
		</dict>
		<key>field_base_type_entry</key>
		<dict>
			<key>name</key>
			<string>meta.field.base.avro</string>
			<key>begin</key>
			<string>(?=(?:map|array|union|int|long|string|boolean|float|double|null|bytes|decimal|date|time_ms|timestamp_ms))</string>
			<key>end</key>
			<string>(?=;)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#types</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#decorators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#field_default_value</string>
				</dict>
			</array>
		</dict>
		<key>field_default_value</key>
		<dict>
			<key>name</key>
			<string>meta.default.avro</string>
			<key>begin</key>
			<string>=</string>
			<key>end</key>
			<string>(?=;)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#object</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constants</string>
				</dict>
			</array>
		</dict>
		<key>field_user_type_entry</key>
		<dict>
			<key>name</key>
			<string>meta.field.user.avro</string>
			<key>begin</key>
			<string>\b\w+</string>
			<key>end</key>
			<string>(?=;)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#decorators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#field_default_value</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.avro</string>
				</dict>
			</dict>
		</dict>
		<key>fixed</key>
		<dict>
			<key>match</key>
			<string>\b(fixed)\b([^(]+)\(([^)]+)\)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type.logical.avro</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.fixed.avro</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#decorators</string>
						</dict>
						<dict>
							<key>name</key>
							<string>entity.name.type.avro</string>
							<key>match</key>
							<string>\w+</string>
						</dict>
					</array>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>meta.fixed.length</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>name</key>
							<string>constant.numeric.avro</string>
							<key>match</key>
							<string>\b[0-9]+\b</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>function</key>
		<dict>
			<key>name</key>
			<string>meta.function</string>
			<key>contentName</key>
			<string>meta.function.parameters.avro</string>
			<key>begin</key>
			<string>\b([\w`]+)\s*\(</string>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#function_param</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.function.name.avro</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>entity.name.function.avro</string>
							<key>match</key>
							<string>\w+</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>function_param</key>
		<dict>
			<key>name</key>
			<string>meta.function.param</string>
			<key>begin</key>
			<string>(?!=\))</string>
			<key>end</key>
			<string>,|(?=\))</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\w+</string>
					<key>end</key>
					<string>,|(?=\))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#decorators</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#variable</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#function_param_default_value</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.function.param.type</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#types</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#declared_type</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#decorators</string>
				</dict>
			</array>
		</dict>
		<key>function_param_default_value</key>
		<dict>
			<key>name</key>
			<string>meta.default.avro</string>
			<key>begin</key>
			<string>=</string>
			<key>end</key>
			<string>(?=[,)])</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#object</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constants</string>
				</dict>
			</array>
		</dict>
		<key>import</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(import)\s+(idl|protocol|schema)\s+([^;]+);</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.avro</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.avro</string>
						</dict>
						<key>3</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#strings</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.struct.avro</string>
					<key>match</key>
					<string>\b(protocol|record)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.other.avro</string>
					<key>match</key>
					<string>\b(oneway)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.control.avro</string>
					<key>match</key>
					<string>(@namespace|@extends|@import)\b</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#types</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.avro</string>
					<key>match</key>
					<string>\b(true|false|null)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.avro</string>
					<key>match</key>
					<string>\b[A-Z][A-Z0-9_]*\b</string>
				</dict>
			</array>
		</dict>
		<key>object</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\[</string>
					<key>end</key>
					<string>\]</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#object</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>{</string>
					<key>end</key>
					<string>}</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#object</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
			</array>
		</dict>
		<key>protocol</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(protocol)\s+(\w+)\s*{</string>
					<key>end</key>
					<string>}</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#contents</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.struct.avro</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.avro</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>record</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>contentName</key>
					<string>meta.record.avro</string>
					<key>begin</key>
					<string>\b(record)\s+(\w+)\s*{</string>
					<key>end</key>
					<string>}</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#field</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.struct.record.avro</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.avro</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>name</key>
			<string>string.quoted.double.avro</string>
			<key>begin</key>
			<string>&quot;</string>
			<key>end</key>
			<string>&quot;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.character.escape.avro</string>
					<key>match</key>
					<string>\\.</string>
				</dict>
			</array>
		</dict>
		<key>throws</key>
		<dict>
			<key>name</key>
			<string>meta.throws</string>
			<key>begin</key>
			<string>\bthrows\b</string>
			<key>end</key>
			<string>(?=;)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>name</key>
					<string>entity.name.type.avro</string>
					<key>match</key>
					<string>\b\w+\b</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.avro</string>
				</dict>
			</dict>
		</dict>
		<key>types</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#union</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#decimal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#collections</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.type.primitive.avro</string>
					<key>match</key>
					<string>\b(int|long|string|boolean|float|double|null|bytes)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.type.logical.avro</string>
					<key>match</key>
					<string>\b(date|time_ms|timestamp_ms|uuid)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.type.primitive.avro</string>
					<key>match</key>
					<string>\b(uint|void)\b</string>
				</dict>
			</array>
		</dict>
		<key>union</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>contentName</key>
					<string>meta.type.union.avro</string>
					<key>begin</key>
					<string>\b(union)\s*{</string>
					<key>end</key>
					<string>}</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#types</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#declared_type</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.struct.union.avro</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>variable</key>
		<dict>
			<key>match</key>
			<string>(`?)(\w+)(`?)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.name.escape.avro</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.name.avro</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.name.escape.avro</string>
				</dict>
			</dict>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>avdl</string>
	</array>
</dict>
</plist>
