<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>BASIC</string>
	<key>scopeName</key>
	<string>source.basic</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>name</key>
			<string>entity.name.tag.basic</string>
			<key>match</key>
			<string>^\s*\d+</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((?i)THEN|ELSE|GO\s*TO|GOSUB)\s*(\d+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.basic</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.basic</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.numeric.basic</string>
			<key>match</key>
			<string>\b(?:\d\.|\d+\.\d+|\.\d+|\d+)(?:[Ee][-+]?\d+)?\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>string.quoted.double.basic</string>
			<key>match</key>
			<string>&quot;[^&quot;]*&quot;</string>
		</dict>
		<dict>
			<key>name</key>
			<string>comment.line.basic</string>
			<key>match</key>
			<string>(?i:REM.*|^&apos;.*| &apos;.*)</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.control.basic</string>
			<key>match</key>
			<string>\b(?i:FOR|TO|NEXT|IF|THEN|ELSE|GO\s*TO|GOSUB|RETURN)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>entity.name.type.basic</string>
			<key>match</key>
			<string>\b(?i:\?|\&amp;|\!|ABSOLUTE|ACCESS|AS|BASE|BEEP|BLOAD|BSAVE|CALL|CASE|CHAIN|CHDIR|CIRCLE|CLEAR|CLOSE|CLS|COLOR|COM|COMMON|CONST|DATA|DECLARE|DEF|DEFDBL|DEFINT|DEFLNG|DEFSNG|DEFSTR|DIM|DO|DRAW|END|ENVIRON|ERASE|ERROR|EXIT|FIELD|FILES|FUNCTION|GET|HOME|IF|INPUT|INPUT#|IOCTL|KEY|KILL|LET|LINE|LOCATE|LOCK|LOOP|LPRINT|LSET|MKDIR|NAME|NEW|ON|OPEN|OPTION|OUT|PAINT|PALETTE|PCLEAR0|PCLEAR1|PCOPY|PEN|PLAY|PMAP|PMODE0|POKE|PRESET|PRINT|PRINT#|PSET|PUT|RANDOMIZE|READ|REDIM|REM|RESET|RESTORE|RESUME|RMDIR|RSET|RUN|SCREEN|SEEK|SELECT|SHARED|SHELL|SLEEP|SOUND|SOUNDRND|STATIC|STOP|STRIG|SUB|SWAP|SYSTEM|TIMER|TROFF|TRON|TYPE|UNLOCK|USING|VIEW|WAIT|WEND|WHILE|WINDOW|WRITE)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>entity.name.function.basic</string>
			<key>match</key>
			<string>\b(?i:BIN|CHR|COMMAND|DATE|ENVIRON|ERDEV|HEX|INKEY|INPUT|IOCTL|LAFT|LCASES|LEFT|LTRIM|MID|MKD|MKDMBF|MKI|MKL|MKS|MKSMBF|OCT|RIGHT|RTRIM|SPACE|SPC|STR|STRING|TAB|TIME|UCASE|UPS|VARPTR)\$</string>
		</dict>
		<dict>
			<key>name</key>
			<string>entity.name.function.basic</string>
			<key>match</key>
			<string>\b(?i:ABS|ASC|ATN|BRK|CDBL|CINT|CLNG|COS|CSNG|CSRLIN|CTL|CVD|CVDMBF|CVI|CVL|CVS|CVSMBF|D2R|EOF|ERDEV|ERL|ERR|EXP|FILEATTR|FIX|FRE|FREEFILE|HEIGHT|INP|INSTR|INT|ITM|LBOUND|LEN|LG|LIN|LN|LOC|LOF|LOG|LOG10|LPOS|NINT|NUM|PEEK|PEN|POINT|POS|R2D|REC|RND|SADD|SCREEN|SEEK|SETMEM|SGN|SIN|SPA|SPC|SQR|SQRT|STICK|STRIG|SYS|TAB|TAN|TIM|TIMER|TYP|UBOUND|VAL|VALPTR|VALSEG|VARPTR|VARSEG|WIDTH)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.operator.basic</string>
			<key>match</key>
			<string>\^|\+|-|\*\*|\*|/|=|&lt;&gt;|&lt;=|=&lt;|&gt;=|=&gt;|&lt;|&gt;|\b(?i:MOD|NOT|AND|OR)\b</string>
		</dict>
	</array>
	<key>fileTypes</key>
	<array>
		<string>bas</string>
	</array>
</dict>
</plist>
