<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Berry</string>
	<key>scopeName</key>
	<string>source.berry</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#controls</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment-block</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#function</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#member</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#identifier</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#number</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operator</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment-block</key>
		<dict>
			<key>name</key>
			<string>comment.berry</string>
			<key>begin</key>
			<string>\#\-</string>
			<key>end</key>
			<string>\-#</string>
			<key>patterns</key>
			<array>
				<dict>

				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>name</key>
			<string>comment.line.berry</string>
			<key>begin</key>
			<string>\#</string>
			<key>end</key>
			<string>\n</string>
			<key>patterns</key>
			<array>
				<dict>

				</dict>
			</array>
		</dict>
		<key>controls</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.control.berry</string>
					<key>match</key>
					<string>\b(if|elif|else|for|while|do|end|break|continue|return|try|except|raise)\b</string>
				</dict>
			</array>
		</dict>
		<key>function</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>entity.name.function.berry</string>
					<key>match</key>
					<string>\b([a-zA-Z_][a-zA-Z0-9_]*(?=\s*\())</string>
				</dict>
			</array>
		</dict>
		<key>identifier</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>identifier.berry</string>
					<key>match</key>
					<string>\b[_A-Za-z]\w+\b</string>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.berry</string>
					<key>match</key>
					<string>\b(var|static|def|class|true|false|nil|self|super|import|as)\b</string>
				</dict>
			</array>
		</dict>
		<key>member</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\.([a-zA-Z_][a-zA-Z0-9_]*)</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.berry</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>number</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.numeric.berry</string>
					<key>match</key>
					<string>0x[a-fA-F0-9]+|\d+|(\d+\.?|\.\d)\d*([eE][+-]?\d+)?</string>
				</dict>
			</array>
		</dict>
		<key>operator</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.operator.berry</string>
					<key>match</key>
					<string>\(|\)|\[|\]|\.|-|\!|~|\*|/|%|\+|&amp;|\^|\||&lt;|&gt;|=|:</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>string.quoted.double.berry</string>
					<key>match</key>
					<string>&quot;(\\.|[^&quot;])*&quot;</string>
				</dict>
				<dict>
					<key>name</key>
					<string>string.quoted.single.berry</string>
					<key>match</key>
					<string>&apos;(\\.|[^&apos;])*&apos;</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>be</string>
	</array>
</dict>
</plist>
