<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Bikeshed</string>
	<key>scopeName</key>
	<string>source.csswg</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>name</key>
			<string>string.quoted.double.csswg</string>
			<key>match</key>
			<string>&lt;&lt;[^&gt;]+&gt;&gt;</string>
		</dict>
		<dict>
			<key>name</key>
			<string>string.quoted.double.csswg</string>
			<key>match</key>
			<string>&lt;\{[^}]+\}&gt;</string>
		</dict>
		<dict>
			<key>name</key>
			<string>string.quoted.double.csswg</string>
			<key>begin</key>
			<string>{{</string>
			<key>end</key>
			<string>\}\}</string>
		</dict>
		<dict>
			<key>name</key>
			<string>string.quoted.double.csswg</string>
			<key>begin</key>
			<string>\[=</string>
			<key>end</key>
			<string>=]</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.other.biblioLink.csswg</string>
			<key>match</key>
			<string>\[\[[^\]]+\]\]</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.language.csswg</string>
			<key>match</key>
			<string>\[[^\]]+\]</string>
		</dict>
		<dict>
			<key>name</key>
			<string>string.quoted.double.csswg</string>
			<key>begin</key>
			<string>&apos;&apos;</string>
			<key>end</key>
			<string>&apos;&apos;</string>
		</dict>
		<dict>
			<key>name</key>
			<string>string.quoted.single.csswg</string>
			<key>match</key>
			<string>(?&lt;!\w)&apos;[^&apos;]+&apos;</string>
		</dict>
		<dict>
			<key>name</key>
			<string>invalid.illegal.heading.csswg</string>
			<key>begin</key>
			<string>&lt;h\d</string>
			<key>end</key>
			<string>&lt;/h\d&gt;</string>
		</dict>
		<dict>
			<key>name</key>
			<string>variable.parameter.definition.csswg</string>
			<key>begin</key>
			<string>&lt;dfn[^&gt;]*&gt;</string>
			<key>end</key>
			<string>&lt;/dfn&gt;</string>
		</dict>
		<dict>
			<key>name</key>
			<string>string.quoted.double.csswg</string>
			<key>begin</key>
			<string>&lt;a[ &gt;]</string>
			<key>end</key>
			<string>&lt;/a&gt;</string>
		</dict>
		<dict>
			<key>name</key>
			<string>entity.production.csswg</string>
			<key>begin</key>
			<string>&lt;pre\s+class=.*?prod.*?&gt;</string>
			<key>end</key>
			<string>&lt;/pre&gt;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#production</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#definition</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>name</key>
			<string>entity.metadata.csswg</string>
			<key>begin</key>
			<string>&lt;pre\s+class=.*?metadata.*?&gt;</string>
			<key>end</key>
			<string>&lt;/pre&gt;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>^(?i)(Abstract|Advisement Class|Assertion Class|Assume Explicit For|At Risk|Audience|Block Elements|Boilerplate|Can I Use Url|Canonical Url|Complain About|Custom Warning Text|Custom Warning Title|Date|Deadline|Default Biblio Status|Default Highlight|Default Ref Status|ED|Editor|Editor Term|Former Editor|Group|H1|Ignore Can I Use Url Failure|Ignored Terms|Ignored Vars|Include Can I Use Panels|Indent|Infer Css Dfns|Inline Github Issues|Issue Class|Issue Tracker Template|Issue Tracking|Level|Line Numbers|Link Defaults|Logo|Mailing List Archives|Mailing List|Markup Shorthands|Max Toc Depth|No Editor|Note Class|Opaque Elements|Prepare For Tr|Previous Version|Repository|Revision|Shortname|Status Text|Status|Test Suite|Text Macro|Title|Toggle Diffs|TR|Translate Ids|Translation|URL|Use &lt;I&gt; Autolinks|Use Dfn Panels|Version History|Warning|Work Status)\s*:\s*(.*)$</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.knownKeyName.csswg</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.csswg</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>^\s*(![\w -]+)\s*:\s*(.*)$</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.other.customKeyName.csswg</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.csswg</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>^\s*([\w -]+)\s*:\s*.*$</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.unknownKeyName.csswg</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<dict>
			<key>name</key>
			<string>entity.propdef.csswg</string>
			<key>begin</key>
			<string>&lt;pre\s+class=.*?(propdef|descdef).*?&gt;</string>
			<key>end</key>
			<string>&lt;/pre&gt;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>^\s*(?i)(Name|Value|For|Initial|Applies to|Inherited|Percentages|Media|Computed value|Animation type|Canonical order|Logical property group)\s*:\s*(.*)$</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.keyName.csswg</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.csswg</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>^\s*([\w -]+)\s*:\s*(.*)$</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.other.unknownKeyName.csswg</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.csswg</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<dict>
			<key>name</key>
			<string>entity.name.tag.csswg</string>
			<key>begin</key>
			<string>&lt;/?[a-z]</string>
			<key>end</key>
			<string>&gt;</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>definition</key>
		<dict>
			<key>name</key>
			<string>variable.parameter.definition.csswg</string>
			<key>begin</key>
			<string>&lt;dfn( |&gt;)</string>
			<key>end</key>
			<string>&lt;/dfn&gt;</string>
		</dict>
		<key>production</key>
		<dict>
			<key>name</key>
			<string>constant.other.production.csswg</string>
			<key>match</key>
			<string>&lt;&lt;[^&gt;]+&gt;&gt;</string>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>bs</string>
	</array>
</dict>
</plist>
