<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Boogie</string>
	<key>scopeName</key>
	<string>source.boogie</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#constants</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>name</key>
			<string>string.other.attribute.boogie</string>
			<key>begin</key>
			<string>{\s*:</string>
			<key>end</key>
			<string>}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>name</key>
			<string>entity.name.block.boogie</string>
			<key>match</key>
			<string>(\s*([^: ]+):(
|))</string>
		</dict>
		<dict>
			<key>name</key>
			<string>punctuation.terminator.boogie</string>
			<key>match</key>
			<string>;</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>comment.line.double-slash.boogie</string>
					<key>match</key>
					<string>(//).*$\n?</string>
				</dict>
				<dict>
					<key>name</key>
					<string>comment.block.boogie</string>
					<key>begin</key>
					<string>/\*</string>
					<key>end</key>
					<string>\*/</string>
				</dict>
			</array>
		</dict>
		<key>constants</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.language.boolean.boogie</string>
					<key>match</key>
					<string>(?&lt;![\w$.])(true|false)(?![\w$.])</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.integer.boogie</string>
					<key>match</key>
					<string>(?&lt;![\w$.])[0-9]+(?![\w$.])</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.bitvector.boogie</string>
					<key>match</key>
					<string>(?&lt;![\w$.])[0-9]+bv[0-9]+(?![\w$.])</string>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>storage.type.declaration.boogie</string>
					<key>match</key>
					<string>\b(axiom|const|function|implementation|procedure|type|var)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>storage.modifier.boogie</string>
					<key>match</key>
					<string>(?&lt;![\w$.])(complete|extends|finite|free|unique|where)(?![\w$.])</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.other.specification.boogie</string>
					<key>match</key>
					<string>\b(requires|ensures|modifies|returns|invariant)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.control.boogie</string>
					<key>match</key>
					<string>\b(break|call|async|par|while|goto|return)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.control.conditional.boogie</string>
					<key>match</key>
					<string>\b(if|then|else)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.control.statement.boogie</string>
					<key>match</key>
					<string>\b(assert|assume|havoc|yield)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.boogie</string>
					<key>match</key>
					<string>(:=)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.other.old.boogie</string>
					<key>match</key>
					<string>\bold\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.other.logical.quantifier.boogie</string>
					<key>match</key>
					<string>\b(forall|exists|lambda)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.logical.boogie</string>
					<key>match</key>
					<string>::</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.logical.unary.boogie</string>
					<key>match</key>
					<string>!</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.logical.binary.boogie</string>
					<key>match</key>
					<string>&lt;==&gt;|==&gt;|&lt;==|&amp;&amp;|\|\|</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.comparison.boogie</string>
					<key>match</key>
					<string>==|!=|&lt;=|&gt;=|&lt;:|&lt;|&gt;</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>name</key>
			<string>string.quoted.double.boogie</string>
			<key>begin</key>
			<string>&quot;</string>
			<key>end</key>
			<string>&quot;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.character.escape.boogie</string>
					<key>match</key>
					<string>\\.</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>bpl</string>
	</array>
</dict>
</plist>
