<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Browserslist</string>
	<key>scopeName</key>
	<string>text.browserslist</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#marketshares</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#dates</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#versions</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#browsers</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#sections</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#configs</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>browsers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>string.unquoted.browserslist</string>
					<key>match</key>
					<string>(?i)\b(Android|Baidu|BlackBerry|bb|Chrome|ChromeAndroid|and_chr|Edge|Electron|Explorer|ie|ExplorerMobile|ie_mob|Firefox|ff|FirefoxAndroid|and_ff|iOS|ios_saf|Node|Opera|OperaMini|op_mini|OperaMobile|op_mob|PhantomJS|QQAndroid|and_qq|Safari|Samsung|UCAndroid|and_uc|kaios)\b</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>comment.line.number-sign.browserslist</string>
					<key>begin</key>
					<string>#</string>
					<key>end</key>
					<string>
</string>
				</dict>
			</array>
		</dict>
		<key>configs</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>entity.name.class.browserslist</string>
					<key>match</key>
					<string>@\w+\/browserslist-config(-.+)?</string>
				</dict>
				<dict>
					<key>name</key>
					<string>entity.name.class.browserslist</string>
					<key>match</key>
					<string>\bbrowserslist-config-\w+\b</string>
				</dict>
			</array>
		</dict>
		<key>dates</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.numeric.date.browserslist</string>
					<key>match</key>
					<string>\d{4}(-\d{1,2}){0,2}</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.date.browserslist</string>
					<key>match</key>
					<string>years?</string>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.control.browserslist</string>
					<key>match</key>
					<string>(&lt;=?|&gt;=?|,)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.control.browserslist</string>
					<key>match</key>
					<string>\b(not|and|or|extends|in|last|since|cover|supports)\b</string>
				</dict>
			</array>
		</dict>
		<key>marketshares</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.numeric.browserslist</string>
					<key>match</key>
					<string>(\d*\.)?\d+%</string>
				</dict>
			</array>
		</dict>
		<key>sections</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>entity.name.function.browserslist</string>
					<key>match</key>
					<string>defaults</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.browserslist</string>
					<key>match</key>
					<string>(\[|\])</string>
				</dict>
				<dict>
					<key>name</key>
					<string>entity.name.function.browserslist</string>
					<key>match</key>
					<string>(?!\[)(.+)(?=\])</string>
				</dict>
			</array>
		</dict>
		<key>versions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.numeric.browserslist</string>
					<key>match</key>
					<string>\b\d+(.\d+){0,2}\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.browserslist</string>
					<key>match</key>
					<string>(?i)\b(esr|tp|all|dead|unreleased|major|versions?)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.node.browserslist</string>
					<key>match</key>
					<string>(?i)\b(current|maintained?)\b</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>.browserslistrc</string>
		<string>browserslist</string>
	</array>
</dict>
</plist>
