<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>CDS</string>
	<key>scopeName</key>
	<string>source.cds</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>\b(aspect|(abstract\s+)?entity)\b</string>
			<key>end</key>
			<string>(?&lt;=})(;)?|(;)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>:</string>
					<key>end</key>
					<string>(?={|;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#identifiers</string>
						</dict>
						<dict>
							<key>name</key>
							<string>punctuation.separator.object.cds</string>
							<key>match</key>
							<string>,</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.cds</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>include</key>
					<string>#bracedElementDef</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#identifiers</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.strong.cds</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.terminator.statement.cds</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.terminator.statement.cds</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i)\b(extend)\s+((context|service|aspect|entity|projection|type)\s+)?(\S+)(\s+(with)(\s+(actions|definitions|columns|elements|enum))?|(?=\s*{))</string>
			<key>end</key>
			<string>(?&lt;=})(;)?|(;)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#bracedElementDef</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#identifiers</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.separator.object.cds</string>
					<key>match</key>
					<string>,</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.strong.cds</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.cds</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>identifier.cds</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>keyword.cds</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>keyword.cds</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.terminator.statement.cds</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.terminator.statement.cds</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;!\.)\b(annotate)\b\s*[\w.]+\b\s*\b(with)?\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.strong.control.import.cds</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.strong.control.import.cds</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.import.cds</string>
			<key>begin</key>
			<string>(?&lt;!\.)\b(import|using)(?!\s*:)\b</string>
			<key>end</key>
			<string>(;)|\n</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>{</string>
					<key>end</key>
					<string>}</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(?:\b(default)\b|\b([$_a-zA-Z][$_a-zA-Z0-9]*)\b)\s*(\bas\b)\s*(?:(\bdefault\b|\*)|\b([$_a-zA-Z][$_a-zA-Z0-9]*)\b)</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>variable.language.default.cds</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>variable.other.module.cds</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>keyword.strong.cds</string>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>invalid.illegal.cds</string>
								</dict>
								<key>5</key>
								<dict>
									<key>name</key>
									<string>variable.other.module-alias.cds</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>name</key>
							<string>punctuation.separator.object.cds</string>
							<key>match</key>
							<string>,</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>name</key>
							<string>variable.other.module.cds</string>
							<key>match</key>
							<string>\b([$_a-zA-Z][$_a-zA-Z0-9]*)\b</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.modules.begin.cds</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.modules.end.cds</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>(?:(\*)|(?=\D)(\b[\$\.\w]+\b))\s*(\bas\b)\s*(?=\D)(\b[\$\.\w]+\b)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.language.import-all.cds</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.module.cds</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.strong.control.cds</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>variable.other.module-alias.cds</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>variable.language.import-all.cds</string>
					<key>match</key>
					<string>\*</string>
				</dict>
				<dict>
					<key>name</key>
					<string>variable.language.default.cds</string>
					<key>match</key>
					<string>\b(default)\b</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.strong.control.cds</string>
					<key>match</key>
					<string>(?i)\b(from)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>variable.other.module.cds</string>
					<key>match</key>
					<string>\b([$_a-zA-Z][$_a-zA-Z0-9]*)\b(?=.*\bfrom\b)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.separator.object.cds</string>
					<key>match</key>
					<string>,</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.strong.control.import.cds</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.terminator.statement.cds</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.export.cds</string>
			<key>match</key>
			<string>\b(export)\b\s*\b(default)\b(?:\s*)\b((?!\bclass\b|\blet\b|\bvar\b|\bconst\b)[$_a-zA-Z][$_a-zA-Z0-9]*)?\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.cds</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.language.default.cds</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.other.module.cds</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.export.cds</string>
			<key>begin</key>
			<string>(?&lt;!\.)\b(export)(?!\s*:)\b</string>
			<key>end</key>
			<string>(?=;|\bclass\b|\blet\b|\bvar\b|\bconst\b|$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#numbers</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>{(?=.*\bfrom\b)</string>
					<key>end</key>
					<string>}</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(?:\b(default)\b|\b([$_a-zA-Z][$_a-zA-Z0-9]*)\b)\s*(\bas\b)\s*(?:\b(default)\b|(\*)|\b([$_a-zA-Z][$_a-zA-Z0-9]*)\b)</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>variable.language.default.cds</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>variable.other.module.cds</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>keyword.control.cds</string>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>variable.language.default.cds</string>
								</dict>
								<key>5</key>
								<dict>
									<key>name</key>
									<string>invalid.illegal.cds</string>
								</dict>
								<key>6</key>
								<dict>
									<key>name</key>
									<string>variable.other.module-alias.cds</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>name</key>
							<string>meta.delimiter.object.comma.cds</string>
							<key>match</key>
							<string>,</string>
						</dict>
						<dict>
							<key>name</key>
							<string>variable.other.module.cds</string>
							<key>match</key>
							<string>\b([$_a-zA-Z][$_a-zA-Z0-9]*)\b</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.modules.begin.cds</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.modules.end.cds</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?![\p{L}$_]){</string>
					<key>end</key>
					<string>}</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(?:\b(default)\b|\b([$_a-zA-Z][$_a-zA-Z0-9]*)\b)\s*(\bas\b)\s*(?:\b(default)\b|(\*)|\b([$_a-zA-Z][$_a-zA-Z0-9]*)\b)</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>invalid.illegal.cds</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>variable.other.module.cds</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>keyword.control.cds</string>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>variable.language.default.cds</string>
								</dict>
								<key>5</key>
								<dict>
									<key>name</key>
									<string>invalid.illegal.cds</string>
								</dict>
								<key>6</key>
								<dict>
									<key>name</key>
									<string>variable.other.module-alias.cds</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>name</key>
							<string>meta.delimiter.object.comma.cds</string>
							<key>match</key>
							<string>,</string>
						</dict>
						<dict>
							<key>name</key>
							<string>variable.other.module.cds</string>
							<key>match</key>
							<string>\b([$_a-zA-Z][$_a-zA-Z0-9]*)\b</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.modules.begin.cds</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.modules.end.cds</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>variable.language.import-all.cds</string>
					<key>match</key>
					<string>\*(?=.*\bfrom\b)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>variable.language.default.cds</string>
					<key>match</key>
					<string>\b(default)\b</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.control.cds</string>
					<key>match</key>
					<string>(?i)\b(from)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>variable.other.module.cds</string>
					<key>match</key>
					<string>\b([$_a-zA-Z][$_a-zA-Z0-9]*)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.delimiter.object.comma.cds</string>
					<key>match</key>
					<string>,</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operators</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.export.cds</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.method.cds</string>
			<key>begin</key>
			<string>\b(?:(static)\s+)?(?!(?:break|case|catch|continue|do|else|finally|for|if|export|import|using|package|return|switch|throw|try|while|with)[\s\(])([$_a-zA-Z][$_a-zA-Z0-9]*)\s*(\()(?=(?:[^\(\)]*)?\)\s*{)</string>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#function-params</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.static.cds</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.cds</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.cds</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.cds</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.class.cds</string>
			<key>match</key>
			<string>\b(class)(?:\s+([$_a-zA-Z][$_a-zA-Z0-9]*))?(?:\s+(extends)\s+([$_a-zA-Z][$_a-zA-Z0-9]*))?\s*($|(?={))</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.class.cds</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.class.cds</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.cds</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.other.inherited-class.cds</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.type.arrow.cds</string>
			<key>match</key>
			<string>=&gt;</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.type.var.cds</string>
			<key>match</key>
			<string>(?&lt;!\.|\$)\b(let|var)\b(?!\$)</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.modifier.cds</string>
			<key>match</key>
			<string>(?&lt;!\.|\$)\b(get|set|const)\b(?!\$)</string>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.control.yield.cds</string>
			<key>match</key>
			<string>(?&lt;!\.)\b(yield)(?!\s*:)\b(?:\s*(\*))?</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.cds</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.cds</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.language.cds</string>
			<key>match</key>
			<string>\b(false|Infinity|NaN|null|true|undefined)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>variable.language.cds</string>
			<key>match</key>
			<string>(?&lt;!\.)\b(super|this)(?!\s*:)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>punctuation.terminator.statement.cds</string>
			<key>match</key>
			<string>\;</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\[)(\])</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.begin.cds</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.end.cds</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>begin</key>
			<string>{</string>
			<key>end</key>
			<string>}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.begin.cds</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.end.cds</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.begin.cds</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.end.cds</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.brace.square.cds</string>
			<key>match</key>
			<string>\[|\]</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.class.cds</string>
			<key>match</key>
			<string>(?&lt;=new )([$_a-zA-Z][$_a-zA-Z0-9]*)(?!\w)</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.class.cds</string>
			<key>match</key>
			<string>(?&lt;= instanceof )([$_a-zA-Z][$_a-zA-Z0-9]*)(?!\w)</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.class.cds</string>
			<key>match</key>
			<string>(?&lt;!\w)([$_a-zA-Z][$_a-zA-Z0-9]*)(?=\.prototype\b)</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.other.cds</string>
			<key>match</key>
			<string>(?i)(?&lt;=\.)(prototype)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.function-call.cds</string>
			<key>match</key>
			<string>(?&lt;!\w)([$_a-zA-Z][$_a-zA-Z0-9]*)(?=\()</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#numbers</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operators</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#identifiers</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>bracedElementDef</key>
		<dict>
			<key>begin</key>
			<string>{</string>
			<key>end</key>
			<string>}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#extendElement</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#elementDef</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.begin.cds</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.end.cds</string>
				</dict>
			</dict>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name</string>
					<key>match</key>
					<string>@\(?[\w.]+\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>comment.block.documentation.cds</string>
					<key>begin</key>
					<string>/\*\*(?!/)</string>
					<key>end</key>
					<string>\*/</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.begin.cds</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.end.cds</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>comment.block.cds</string>
					<key>begin</key>
					<string>/\*</string>
					<key>end</key>
					<string>\*/</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.begin.cds</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.end.cds</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>comment.line.double-slash.cds</string>
					<key>match</key>
					<string>//.*</string>
				</dict>
			</array>
		</dict>
		<key>elementDef</key>
		<dict>
			<key>begin</key>
			<string>(?=\()|\b(virtual(?:\s+))?(key(?:\s+))?(masked(?:\s+))?(element(?:\s+))?</string>
			<key>end</key>
			<string>(?=})|(;)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#bracedElementDef</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\(</string>
					<key>end</key>
					<string>\)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>[$_a-zA-Z][$_a-zA-Z0-9]*|\&quot;[^\&quot;]*(\&quot;\&quot;[^\&quot;]*)*\&quot;|!\\[[^\\]]*(\\]\\][^\\]]*)*\\]</string>
							<key>captures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>entity.name.type.attribute-name.cds</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>include</key>
							<string>#operators</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.scope.begin.cds</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.scope.end.cds</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>begin</key>
					<string>([$_a-zA-Z][$_a-zA-Z0-9]*|&quot;[^&quot;]*(&quot;&quot;[^&quot;]*)*&quot;|!\[[^\]]*(\]\][^\]]*)*\])(?=\s*[:{,])</string>
					<key>end</key>
					<string>(,)|(?=\s*[:{])</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.attribute-name.cds</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.object.cds</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>^\s*([$_a-zA-Z][$_a-zA-Z0-9]*|&quot;[^&quot;]*(&quot;&quot;[^&quot;]*)*&quot;|!\[[^\]]*(\]\][^\]]*)*\])\s*$</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.attribute-name.cds</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>include</key>
					<string>#identifiers</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numbers</string>
				</dict>
				<dict>

				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.cds</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.strong.cds</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.cds</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.cds</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.terminator.statement.cds</string>
				</dict>
			</dict>
		</dict>
		<key>escapes</key>
		<dict>
			<key>name</key>
			<string>constant.character.escape.cds</string>
			<key>match</key>
			<string>\\([xu$]\{?[0-9a-fA-F]+}?|.|$)</string>
		</dict>
		<key>extendElement</key>
		<dict>
			<key>begin</key>
			<string>\b(?=extend\b.*\bwith\b)</string>
			<key>end</key>
			<string>(?&lt;=})(;)?|(;)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\bextend\b</string>
					<key>end</key>
					<string>\bwith\b</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>keyword.cds</string>
							<key>match</key>
							<string>element(?!(?:\s*/\*.*\*/\s*|\s+)?with\b)</string>
						</dict>
						<dict>
							<key>name</key>
							<string>entity.name.type.attribute-name.cds</string>
							<key>match</key>
							<string>[$_a-zA-Z][$_a-zA-Z0-9]*|&quot;[^&quot;]*(&quot;&quot;[^&quot;]*)*&quot;|!\[[^\]]*(\]\][^\]]*)*\]</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.strong.cds</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.cds</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>begin</key>
					<string>{</string>
					<key>end</key>
					<string>}</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#extendElement</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#elementDef</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.scope.begin.cds</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.scope.end.cds</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#identifiers</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operators</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.begin.cds</string>
					<key>match</key>
					<string>\(</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.end.cds</string>
					<key>match</key>
					<string>\)</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numbers</string>
				</dict>
			</array>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.terminator.statement.cds</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.terminator.statement.cds</string>
				</dict>
			</dict>
		</dict>
		<key>function-params</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?=[\p{L}$_])</string>
					<key>end</key>
					<string>(?=[,)/])</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>variable.parameter.function.cds</string>
							<key>match</key>
							<string>\G[$_a-zA-Z][$_a-zA-Z0-9]*</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
			</array>
		</dict>
		<key>identifiers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>identifier.cds</string>
					<key>match</key>
					<string>[$_a-zA-Z][$_a-zA-Z0-9]*|&quot;[^&quot;]*(&quot;&quot;[^&quot;]*)*&quot;|!\[[^\]]*(\]\][^\]]*)*\]</string>
				</dict>
			</array>
		</dict>
		<key>interpolation</key>
		<dict>
			<key>name</key>
			<string>meta.embedded.line.cds</string>
			<key>contentName</key>
			<string>source.cds</string>
			<key>begin</key>
			<string>\${</string>
			<key>end</key>
			<string>(})</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>{</string>
					<key>end</key>
					<string>}</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.brace.curly.cds</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.brace.curly.cds</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.begin.cds</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.end.cds</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>source.cds</string>
				</dict>
			</dict>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>support.class.cds</string>
					<key>match</key>
					<string>(?&lt;!\.|\$)\b(Association\s*(?:\[[0-9.eE+, *-]*\]\s*)?to\s*(?:(many|one)\s*)?|Composition\s*(?:\[[0-9.eE+, *-]*\]\s*)?of\s*(?:(many|one)\s*)?|(Binary|Boolean|DateTime|Date|DecimalFloat|Decimal|Double|Int(16|32|64)|Integer64|Integer|LargeBinary|LargeString|Number|String|Timestamp|Time|UInt8|UUID)\s*(\([^()]*\))?)(?!\$|\s*:)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>invalid.illegal.cds</string>
					<key>match</key>
					<string>(?&lt;!\.|\$)\b(await)\b(?!\$|\s*:)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>invalid.deprecated.cds</string>
					<key>match</key>
					<string>(?&lt;!\.|\$)\b(implements|interface|package|private|protected|public)\b(?!\$|\s*:)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>invalid.illegal.cds</string>
					<key>match</key>
					<string>(?&lt;!\.|\$)\b(class|static|extends)\b(?!\$|\s*:)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.cds</string>
					<key>match</key>
					<string>(?i)(?&lt;!\.|\$)\b(all|and|any|asc|between|by|case|cast|cross|desc|distinct|element|elements|escape|except|excluding|exists|first|from|full|group|group by|having|in|inner|intersect|into|is|join|last|left|like|limit|many|minus|mixin|not null|not|null|nulls|offset|one|or|order by|outer|redirected to|select|some|top|type of|union|where|with)\b(?!\$|\s*:)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.strong.cds</string>
					<key>match</key>
					<string>(?i)(?&lt;!\.|\$)\b(as|key|on|type)\b(?!\$|\s*:)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.cds</string>
					<key>match</key>
					<string>(?&lt;!\.|\$)\b(after|always|analysis|array of|async|asynchronous|auto|both|cache|column|columns|configuration|current|cycle|day|default|depends|detection|disabled|documents|else|enabled|end|every|existing|export|extended|extract|fast|flush|fulltext|fuzzy|generated|getnumservers|hana|hash|hour|identity|import|increment|index|keeping|language|layout|leading|masked|maxvalue|merge|migration|mime|mining|minute|minutes|minvalue|mode|month|name|new|no|off|only|others|overlay|parameters|partition|partitioning|partitions|phrase|preprocess|priority|projection|projection on|queue|range|ratio|reset|returns|right|roundrobin|row|search|second|separators|start|storage|store|subtype|sync|synchronous|table|technical|temporary|text|then|token|trailing|trim|unique|unload|value|values|virtual|when|with parameters|year)\b(?!\$|\s*:)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.strong.cds</string>
					<key>match</key>
					<string>(?&lt;!\.|\$)\b(abstract|action|actions|annotation|aspect|context|define|entity|enum|event|expose|extend|facet|function|namespace|service|view)\b(?!\$|\s*:)</string>
				</dict>
			</array>
		</dict>
		<key>numbers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.numeric.hex.cds</string>
					<key>match</key>
					<string>(?&lt;!\w|\$)0[xX][[:xdigit:]]+\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.binary.cds</string>
					<key>match</key>
					<string>(?&lt;!\w|\$)0[bB][01]+\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.octal.cds</string>
					<key>match</key>
					<string>(?&lt;!\w|\$)0[oO][0-7]+\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.cds</string>
					<key>match</key>
					<string>(?&lt;!\w|\$)[+-]?[0-9]+(&apos;.&apos;[0-9]+)?([eE][+-]?[0-9]+)?(?!\w)</string>
				</dict>
			</array>
		</dict>
		<key>operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.compound.cds</string>
					<key>match</key>
					<string>%=|\+=|\-=|\*=|(?&lt;!\()/=</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.compound.bitwise.cds</string>
					<key>match</key>
					<string>&amp;=|\^=|&lt;&lt;=|&gt;&gt;=|&gt;&gt;&gt;=|\|=</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.comparison.cds</string>
					<key>match</key>
					<string>!==|!=|&lt;=|&gt;=|===|==|&lt;|&gt;</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.logical.cds</string>
					<key>match</key>
					<string>&amp;&amp;|!|\|\|</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.bitwise.cds</string>
					<key>match</key>
					<string>&amp;|\||\^|~</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.cds</string>
					<key>match</key>
					<string>\:\s*(localized)\s+</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.cds</string>
					<key>match</key>
					<string>[?:]</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.logical.cds</string>
					<key>match</key>
					<string>!</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.cds</string>
					<key>match</key>
					<string>=|\:</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.decrement.cds</string>
					<key>match</key>
					<string>\-\-</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.increment.cds</string>
					<key>match</key>
					<string>\+\+</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.arithmetic.cds</string>
					<key>match</key>
					<string>%|\*|/|\-|\+</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>string.quoted.single.cds</string>
					<key>begin</key>
					<string>&apos;</string>
					<key>end</key>
					<string>&apos;(?!&apos;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>meta.single-quote.doubled.cds</string>
							<key>match</key>
							<string>&apos;&apos;</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.cds</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.cds</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>string.quoted.other.template.cds</string>
					<key>begin</key>
					<string>`</string>
					<key>end</key>
					<string>`</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#interpolation</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#escapes</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.cds</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.cds</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>cds</string>
	</array>
</dict>
</plist>
