<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Ceylon</string>
	<key>scopeName</key>
	<string>source.ceylon</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>name</key>
			<string>comment.singleline.ceylon</string>
			<key>match</key>
			<string>//.*$</string>
		</dict>
		<dict>
			<key>name</key>
			<string>comment.shebang.ceylon</string>
			<key>match</key>
			<string>^#!/.*$</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.control.ceylon</string>
			<key>match</key>
			<string>\b(assembly|module|package|import|alias|class|interface|object|given|value|assign|void|function|new|of|extends|satisfies|adapts|abstracts|in|out|return|break|continue|throw|assert|dynamic|if|else|switch|case|for|while|try|catch|finally|then|let|this|outer|super|is|exists|nonempty)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.other.ceylon</string>
			<key>match</key>
			<string>\b(doc|by|license|see|throws|tagged|shared|abstract|formal|default|actual|variable|late|native|deprecated|final|sealed|annotation|suppressWarnings|static)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>entity.name.class.ceylon</string>
			<key>match</key>
			<string>([A-Z][a-zA-Z0-9_]*|\\I[a-zA-Z0-9_]+)</string>
		</dict>
		<dict>
			<key>name</key>
			<string>variable.other.ceylon</string>
			<key>match</key>
			<string>([a-z][a-zA-Z0-9_]*|\\i[a-zA-Z0-9_]+)</string>
		</dict>
		<dict>
			<key>name</key>
			<string>string.verbatim.ceylon</string>
			<key>begin</key>
			<string>&quot;&quot;&quot;</string>
			<key>end</key>
			<string>&quot;&quot;&quot;</string>
		</dict>
		<dict>
			<key>name</key>
			<string>string.ceylon</string>
			<key>begin</key>
			<string>&apos;</string>
			<key>end</key>
			<string>&apos;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.character.escape.ceylon</string>
					<key>match</key>
					<string>\\.</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>name</key>
			<string>string.template.head.ceylon</string>
			<key>begin</key>
			<string>&quot;</string>
			<key>end</key>
			<string>&quot;|(``)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.character.escape.ceylon</string>
					<key>match</key>
					<string>\\.</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>name</key>
			<string>string.template.midOrtail.ceylon</string>
			<key>begin</key>
			<string>``</string>
			<key>end</key>
			<string>&quot;|``</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.numeric.binary.ceylon</string>
			<key>match</key>
			<string>\$(([01]+(_[01]+)+)|[01]+)</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.numeric.hexa.ceylon</string>
			<key>match</key>
			<string>#(([0-9ABCDEF]+(_[0-9ABCDEF]+)+)|[0-9ABCDEF]+)</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.numeric.floating.ceylon</string>
			<key>match</key>
			<string>-?(([0-9]+(_[0-9]+)+)|[0-9]+)\.(([0-9]+(_[0-9]+)+)|[0-9]+)(([eE]-?(([0-9]+(_[0-9]+)+)|[0-9]+))|[kmgtpKMGTP])?</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.numeric.decimal.ceylon</string>
			<key>match</key>
			<string>-?(([0-9]+(_[0-9]+)+)|[0-9]+)[kmgtpKMGTP]?</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>name</key>
			<string>comment.multiline.ceylon</string>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>ceylon</string>
	</array>
</dict>
</plist>
