<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Clean</string>
	<key>scopeName</key>
	<string>source.clean</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#marks</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#literals</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operators</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#delimiters</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>commentBlock</key>
		<dict>
			<key>name</key>
			<string>comment.block.clean</string>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.begin.clean</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.end.clean</string>
				</dict>
			</dict>
		</dict>
		<key>commentDoc</key>
		<dict>
			<key>name</key>
			<string>comment.block.documentation</string>
			<key>begin</key>
			<string>/\*\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.gfm</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.documentation.begin.clean</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.documentation.begin.clean</string>
				</dict>
			</dict>
		</dict>
		<key>commentLine</key>
		<dict>
			<key>name</key>
			<string>comment.line.double-slash.clean</string>
			<key>begin</key>
			<string>//</string>
			<key>end</key>
			<string>$</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.clean</string>
				</dict>
			</dict>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#commentDoc</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#commentBlock</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#commentLine</string>
				</dict>
			</array>
		</dict>
		<key>delimiters</key>
		<dict>
			<key>name</key>
			<string>punctuation.separator</string>
			<key>match</key>
			<string>[,;(){}]</string>
		</dict>
		<key>keywordGeneral</key>
		<dict>
			<key>name</key>
			<string>keyword.control.clean</string>
			<key>match</key>
			<string>\b(if|let|in|with|where|case|of|class|instance)\b</string>
		</dict>
		<key>keywordImport</key>
		<dict>
			<key>name</key>
			<string>keyword.control.import.clean</string>
			<key>match</key>
			<string>\b(implementation|definition|system|module|from|import|qualified|as)\b</string>
		</dict>
		<key>keywordReserved</key>
		<dict>
			<key>name</key>
			<string>keyword.reserved.clean</string>
			<key>match</key>
			<string>\b(special|code|inline|foreign|export|ccall|stdcall|generic|derive|infix(l|r)?|otherwise|dynamic)\b</string>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#keywordGeneral</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywordImport</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywordReserved</string>
				</dict>
			</array>
		</dict>
		<key>literalBool</key>
		<dict>
			<key>name</key>
			<string>constant.language.boolean.clean</string>
			<key>match</key>
			<string>\b(True|False)\b</string>
		</dict>
		<key>literalChar</key>
		<dict>
			<key>name</key>
			<string>constant.character.clean</string>
			<key>match</key>
			<string>&apos;([^&apos;\\]|\\(x[0-9a-fA-F]+|\d+|.))&apos;</string>
		</dict>
		<key>literalHex</key>
		<dict>
			<key>name</key>
			<string>constant.numeric.integer.hexadecimal.clean</string>
			<key>match</key>
			<string>\b[+~-]?0x[0-9A-Fa-f]+\b</string>
		</dict>
		<key>literalInt</key>
		<dict>
			<key>name</key>
			<string>constant.numeric.integer.decimal.clean</string>
			<key>match</key>
			<string>\b[+~-]?[0-9]+\b</string>
		</dict>
		<key>literalOct</key>
		<dict>
			<key>name</key>
			<string>constant.numeric.integer.octal.clean</string>
			<key>match</key>
			<string>\b[+~-]?0[0-7]+\b</string>
		</dict>
		<key>literalReal</key>
		<dict>
			<key>name</key>
			<string>constant.numeric.float.clean</string>
			<key>match</key>
			<string>\b[+~-]?[0-9]+\.[0-9]+(E[+-]?[0-9]+)?\b</string>
		</dict>
		<key>literalString</key>
		<dict>
			<key>name</key>
			<string>string.quoted.double.clean</string>
			<key>begin</key>
			<string>&quot;</string>
			<key>end</key>
			<string>&quot;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escaped_character</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.clean</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.clean</string>
				</dict>
			</dict>
		</dict>
		<key>literals</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#literalChar</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literalInt</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literalOct</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literalHex</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literalReal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literalBool</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literalString</string>
				</dict>
			</array>
		</dict>
		<key>mark</key>
		<dict>
			<key>name</key>
			<string>markup.heading.clean</string>
			<key>begin</key>
			<string>/// #+ </string>
			<key>end</key>
			<string>$</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.clean</string>
				</dict>
			</dict>
		</dict>
		<key>marks</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#mark</string>
				</dict>
			</array>
		</dict>
		<key>operatorComposition</key>
		<dict>
			<key>name</key>
			<string>keyword.operator.composition.clean</string>
			<key>match</key>
			<string>\s+o\s+</string>
		</dict>
		<key>operatorGeneral</key>
		<dict>
			<key>name</key>
			<string>keyword.operator.clean</string>
			<key>match</key>
			<string>[-~@#$%^?!+*&lt;&gt;\\/|&amp;=:.]+</string>
		</dict>
		<key>operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#operatorGeneral</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operatorComposition</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>icl</string>
		<string>dcl</string>
	</array>
</dict>
</plist>
