<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Firestore Rules</string>
	<key>scopeName</key>
	<string>source.firestore</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#main</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>accessControl</key>
		<dict>
			<key>name</key>
			<string>storage.modifier.access-control.firestore</string>
			<key>match</key>
			<string>\b(get|list|read|create|update|delete|write)\b(?=[\s,:;]|$)</string>
		</dict>
		<key>arithmetic</key>
		<dict>
			<key>name</key>
			<string>keyword.operator.arithmetic.firestore</string>
			<key>match</key>
			<string>[-+*/%]</string>
		</dict>
		<key>basicTypes</key>
		<dict>
			<key>name</key>
			<string>storage.type.$1.firestore</string>
			<key>match</key>
			<string>\b(request|math|user|duration|string|int|cloud)\b</string>
		</dict>
		<key>booleans</key>
		<dict>
			<key>name</key>
			<string>constant.language.boolean.$1.firestore</string>
			<key>match</key>
			<string>\b(true|false)\b</string>
		</dict>
		<key>comment</key>
		<dict>
			<key>name</key>
			<string>comment.line.double-slash.firestore</string>
			<key>begin</key>
			<string>//</string>
			<key>end</key>
			<string>$</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.firestore</string>
				</dict>
			</dict>
		</dict>
		<key>comparisons</key>
		<dict>
			<key>name</key>
			<string>keyword.operator.comparison.firestore</string>
			<key>match</key>
			<string>!!|&amp;&amp;|\|\||[!=]==?|&gt;=|&lt;=|&lt;&lt;[&lt;=]?|&gt;&gt;[&gt;=]?|[=!&gt;&lt;|&amp;]</string>
		</dict>
		<key>functionName</key>
		<dict>
			<key>name</key>
			<string>entity.name.function.firestore</string>
			<key>match</key>
			<string>[.\s\(][a-zA-Z]+(?=\()</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#punctuation</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>functionParameter</key>
		<dict>
			<key>name</key>
			<string>variable.parameter.function.firestore</string>
			<key>match</key>
			<string>\b(?&lt;![&apos;&quot;])[a-zA-Z0-9_]+(?![&apos;&quot;])\b</string>
		</dict>
		<key>functionParameterList</key>
		<dict>
			<key>name</key>
			<string>meta.function.parameters.firestore</string>
			<key>begin</key>
			<string>\(</string>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#functionParameter</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#main</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.bracket.round.firestore</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.end.bracket.round.firestore</string>
				</dict>
			</dict>
		</dict>
		<key>globalFunc</key>
		<dict>
			<key>name</key>
			<string>support.function.global.$1.firestore</string>
			<key>match</key>
			<string>^\s*(service|match|allow)(?=\s)</string>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.control.$1.firestore</string>
					<key>match</key>
					<string>\b(if|in|return|is)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.null.firestore</string>
					<key>match</key>
					<string>\b(null)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>storage.type.function.firestore</string>
					<key>match</key>
					<string>\b(function)\b</string>
				</dict>
			</array>
		</dict>
		<key>main</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#pathMatchLiteral</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#pathMatchVariable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#basicTypes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#functionName</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#functionParameterList</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#globalFunc</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#accessControl</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#booleans</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comparisons</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#arithmetic</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#typeMember</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#punctuation</string>
				</dict>
			</array>
		</dict>
		<key>number</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.numeric.decimal.float.firestore</string>
					<key>match</key>
					<string>(?x)
-?[0-9]+\.[0-9]* | # 1.2, -3.4, -3.
-?      \.[0-9]+   # .12, -.34, -.3</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.decimal.integer.firestore</string>
					<key>match</key>
					<string>-?[0-9]+</string>
				</dict>
			</array>
		</dict>
		<key>pathMatchLiteral</key>
		<dict>
			<key>name</key>
			<string>string.unquoted.path.firestore</string>
			<key>match</key>
			<string>(/)[-a-zA-Z0-9_]+(?=[\s/])</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.slash.firestore</string>
				</dict>
			</dict>
		</dict>
		<key>pathMatchVariable</key>
		<dict>
			<key>name</key>
			<string>string.unquoted.path.interpolation.firestore</string>
			<key>match</key>
			<string>(?x)
(/)         #1
({)         #2
([^}]+?)    #3
((=)\*+)?  #4-5
(})         #6
(?=[\s/])</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.slash.firestore</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.section.begin.firestore</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.path.match.firestore</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.wildcard.firestore</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.key-value.firestore</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.section.end.firestore</string>
				</dict>
			</dict>
		</dict>
		<key>punctuation</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.colon.key-value.firestore</string>
					<key>match</key>
					<string>:</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.terminator.statement.semicolon.firestore</string>
					<key>match</key>
					<string>;</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.separator.delimiter.comma.firestore</string>
					<key>match</key>
					<string>,</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.definition.bracket.curly.begin.firestore</string>
					<key>match</key>
					<string>{</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.definition.bracket.curly.end.firestore</string>
					<key>match</key>
					<string>}</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.definition.bracket.square.begin.firestore</string>
					<key>match</key>
					<string>\[</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.definition.bracket.square.end.firestore</string>
					<key>match</key>
					<string>\]</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.definition.bracket.round.begin.firestore</string>
					<key>match</key>
					<string>\(</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.definition.bracket.round.end.firestore</string>
					<key>match</key>
					<string>\)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.definition.full-stop.dot.period.firestore</string>
					<key>match</key>
					<string>\.</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>string.quoted.double.firestore</string>
					<key>begin</key>
					<string>&quot;</string>
					<key>end</key>
					<string>&quot;</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.firestore</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.firestore</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>string.quoted.single.firestore</string>
					<key>begin</key>
					<string>&apos;</string>
					<key>end</key>
					<string>&apos;</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.firestore</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.firestore</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>typeMember</key>
		<dict>
			<key>name</key>
			<string>variable.parameter.type.member.firestore</string>
			<key>match</key>
			<string>\.[a-zA-Z0-9_]+</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#punctuation</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>firestore.rules</string>
	</array>
</dict>
</plist>
