<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>COOL</string>
	<key>scopeName</key>
	<string>source.cool</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>name</key>
			<string>comment.line.double-dash</string>
			<key>match</key>
			<string>--(.*)\n</string>
		</dict>
		<dict>
			<key>name</key>
			<string>comment.block.documentation</string>
			<key>begin</key>
			<string>\(\*</string>
			<key>end</key>
			<string>\*\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment.block.documentation</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>name</key>
			<string>support.class</string>
			<key>match</key>
			<string>(Int|String|Bool|Object|IO)</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function</string>
			<key>match</key>
			<string>(abort\(\)|type_name\(\)|copy\(\))</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.control</string>
			<key>match</key>
			<string>\b(if|fi|else|then|loop|pool|while|case|esac)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.operator</string>
			<key>match</key>
			<string>\b(in|inherits|isvoid|let|new|of|new|not)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.language</string>
			<key>match</key>
			<string>\b(true|false)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.numeric</string>
			<key>match</key>
			<string>(?x)\b((?i:( [0-9]+ ( &apos; [0-9]+ )* )))</string>
		</dict>
		<dict>
			<key>name</key>
			<string>entity.name.type</string>
			<key>match</key>
			<string>\b([A-Z]([A-Z]|[a-z]|[0-9]|_)*|SELF_TYPE)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.modifier</string>
			<key>match</key>
			<string>\b(class)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>variable.language</string>
			<key>match</key>
			<string>\b(self)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>variable.parameter</string>
			<key>match</key>
			<string>\b[a-z]([A-z]|[a-z]|[0-9]|_)*\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>entity.name.function</string>
			<key>match</key>
			<string>\b[a-z]*\(.*\)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>string.quoted.double</string>
			<key>begin</key>
			<string>&quot;</string>
			<key>end</key>
			<string>&quot;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string_placeholder</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>

				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>

				</dict>
			</dict>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>formal_param</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\s#variable.parameter : entity.name.type\s</string>
				</dict>
			</array>
		</dict>
		<key>formals</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\s(#formal_param, #formals|#formal_param|)\s</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>cl</string>
	</array>
</dict>
</plist>
