<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>CUDA C++</string>
	<key>scopeName</key>
	<string>source.cuda-c++</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.c++</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.function.qualifier.cuda-c++</string>
			<key>match</key>
			<string>\b__(global|device|host|noinline|forceinline)__\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.modifier.cuda-c++</string>
			<key>match</key>
			<string>\b__(device|constant|managed|shared|restrict)__\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.type.cuda-c++</string>
			<key>match</key>
			<string>\b(dim3|char[1-4]|uchar[1-4]|short[1-4]|ushort[1-4]|int[1-4]|uint[1-4]|long[1-4]|ulong[1-4]|longlong[1-4]|ulonglong[1-4]|float[1-4]|double[1-4])\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>variable.language.cuda-c++</string>
			<key>match</key>
			<string>\b(gridDim|blockIdx|blockDim|threadIdx|warpSize)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.cuda-c++</string>
			<key>match</key>
			<string>\b__(threadfence_system|threadfence_block|threadfence)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.cuda-c++</string>
			<key>match</key>
			<string>\b__(syncthreads_count|syncthreads_and|syncthreads_or|syncthreads)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.cuda-c++</string>
			<key>match</key>
			<string>\b(texCubemapLayered|tex1Dlayered|tex2Dlayered|tex2Dgather|tex1Dfetch|texCubemap|tex1D|tex2D|tex3D)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.cuda-c++</string>
			<key>match</key>
			<string>\b(surfCubemapLayeredwrite|surfCubemapLayeredread|surf1DLayeredwrite|surf2DLayeredwrite|surf1DLayeredread|surf2DLayeredread|surfCubemapwrite|surfCubemapread|surf1Dwrite|surf2Dwrite|surf3Dwrite|surf1Dread|surf2Dread|surf3Dread)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.cuda-c++</string>
			<key>match</key>
			<string>\b__ldg\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.cuda-c++</string>
			<key>match</key>
			<string>\b(clock|clock64)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.cuda-c++</string>
			<key>match</key>
			<string>\b(atomicExch|atomicAdd|atomicSub|atomicMin|atomicMax|atomicInc|atomicDec|atomicCAS|atomicAnd|atomicXor|atomicOr)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.cuda-c++</string>
			<key>match</key>
			<string>\b__(ballot|all|any)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.cuda-c++</string>
			<key>match</key>
			<string>\b__(shfl_down|shfl_xor|shfl_up|shfl)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.cuda-c++</string>
			<key>match</key>
			<string>\b__(prof_trigger)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.cuda-c++</string>
			<key>match</key>
			<string>\bassert\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.cuda-c++</string>
			<key>match</key>
			<string>\bprintf\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.cuda-c++</string>
			<key>match</key>
			<string>\b(malloc|free|memcpy|memset)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.operator.cuda-c++</string>
			<key>begin</key>
			<string>(&lt;&lt;&lt;)</string>
			<key>end</key>
			<string>(&gt;&gt;&gt;)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$base</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.qualifier.cuda-c++</string>
			<key>match</key>
			<string>\b__launch_bounds__\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.cuda-c++</string>
			<key>match</key>
			<string>\b__(fdividef|sincosf|log10f|exp10f|log2f|logf|expf|powf|sinf|cosf|tanf)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.cuda-c++</string>
			<key>match</key>
			<string>\b__((fsqrt|frcp|fadd|fsub|fmul|fmaf|fdiv)_(rn|rz|ru|rd)|frsqrt_rn)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.cuda-c++</string>
			<key>match</key>
			<string>\b__(dsqrt|dadd|dsub|dmul|ddiv|drcp|fma)_(rn|rz|ru|rd)\b</string>
		</dict>
	</array>
	<key>fileTypes</key>
	<array>
		<string>cu</string>
		<string>cuh</string>
	</array>
</dict>
</plist>
