<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>objdump C++</string>
	<key>scopeName</key>
	<string>objdump.x86asm</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>name</key>
			<string>meta.embedded.x86asm</string>
			<key>begin</key>
			<string>^(.*):\s+file format (.*)$</string>
			<key>end</key>
			<string>^</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>comment.x86.assembly</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.x86.assembly</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.embedded.x86asm</string>
			<key>begin</key>
			<string>^Disassembly of section (.*):$</string>
			<key>end</key>
			<string>^</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>comment.x86.assembly</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.x86.assembly</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.embedded.x86asm</string>
			<key>begin</key>
			<string>^[0-9A-Za-z]+ &lt;(.*)&gt;:$</string>
			<key>end</key>
			<string>^</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>comment.x86.assembly</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.x86.assembly</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.embedded.x86asm</string>
			<key>begin</key>
			<string>^\s*[0-9A-Za-z]+:(?:\t[0-9A-Za-z]{2}\s+){0,1}(?:\t|$)</string>
			<key>end</key>
			<string>^</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.x86asm</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>comment.x86.assembly</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>include</key>
			<string>#special_block</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.c</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.c++</string>
		</dict>
	</array>
	<key>fileTypes</key>
	<array>
		<string>d-objdump</string>
	</array>
</dict>
</plist>
