<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>DenizenScript</string>
	<key>scopeName</key>
	<string>source.denizenscript</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#todo_comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#header_comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keys</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#commands</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#double_quotes</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#single_quotes</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#tags</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#def_brackets</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#not_script_keys</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>commands</key>
		<dict>
			<key>begin</key>
			<string>^\s*(-)\s([^\s&lt;&gt;&quot;&apos;:]+)</string>
			<key>end</key>
			<string>\s</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>operator.dash.denizenscript</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.other.command.denizenscript</string>
				</dict>
			</dict>
		</dict>
		<key>comments</key>
		<dict>
			<key>name</key>
			<string>comment.line.number-sign.denizenscript</string>
			<key>begin</key>
			<string>(?i)^\s*#(?!\s*todo|(?:\s*(?:\||\+|=|#|_|@|\/)))</string>
			<key>end</key>
			<string>\n</string>
		</dict>
		<key>def_brackets</key>
		<dict>
			<key>name</key>
			<string>entity.name.tag.def_brackets.denizenscript</string>
			<key>begin</key>
			<string>(?&lt;=\w|&lt;|&amp;)\[</string>
			<key>end</key>
			<string>\]</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tags</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#def_brackets</string>
				</dict>
			</array>
		</dict>
		<key>double_quotes</key>
		<dict>
			<key>name</key>
			<string>string.quoted.double.denizenscript</string>
			<key>begin</key>
			<string>(?&lt;=\s)&quot;</string>
			<key>end</key>
			<string>(?:&quot;|\n)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tags</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#def_brackets</string>
				</dict>
			</array>
		</dict>
		<key>header_comments</key>
		<dict>
			<key>name</key>
			<string>keyword.header-comment.denizenscript</string>
			<key>begin</key>
			<string>^\s*#\s*(?:\||\+|=|#|_|@|\/)</string>
			<key>end</key>
			<string>\n</string>
		</dict>
		<key>keys</key>
		<dict>
			<key>begin</key>
			<string>(?i)(^(?!^\s*-|#|\n|^\s*(?:interact scripts|default constants|data|constants|text|lore|aliases|slots|enchantments|input|description)(?=:\n)).*?)(?=(:)\s)</string>
			<key>end</key>
			<string>\s</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.heading.key.denizenscript</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>operator.colon.denizenscript</string>
				</dict>
			</dict>
		</dict>
		<key>not_script_keys</key>
		<dict>
			<key>begin</key>
			<string>(?i)(^(?!.*- |#|\n).*(?=interact scripts|default constants|data|constants|text|lore|aliases|slots|enchantments|input|description).*)(?=(:)\n)</string>
			<key>end</key>
			<string>^(?!.*- |\n|\s*#)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tags</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#def_brackets</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#todo_comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#header_comments</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.heading.not_script_key.denizenscript</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>operator.colon.denizenscript</string>
				</dict>
			</dict>
		</dict>
		<key>single_quotes</key>
		<dict>
			<key>name</key>
			<string>string.quoted.single.denizenscript</string>
			<key>begin</key>
			<string>(?&lt;=\s)&apos;</string>
			<key>end</key>
			<string>(?:&apos;|\n)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tags</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#def_brackets</string>
				</dict>
			</array>
		</dict>
		<key>tags</key>
		<dict>
			<key>name</key>
			<string>constant.language.tag.denizenscript</string>
			<key>begin</key>
			<string>&lt;(?!-|\s|=)</string>
			<key>end</key>
			<string>&gt;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#def_brackets</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tags</string>
				</dict>
			</array>
		</dict>
		<key>todo_comments</key>
		<dict>
			<key>name</key>
			<string>variable.todo-comment.denizenscript</string>
			<key>begin</key>
			<string>(?i)^\s*#\s*(?:todo)</string>
			<key>end</key>
			<string>\n</string>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>dsc</string>
	</array>
</dict>
</plist>
