<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Dream Maker</string>
	<key>scopeName</key>
	<string>source.dm</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#preprocessor-rule-enabled</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#preprocessor-rule-disabled</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#preprocessor-rule-other</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.initialization.dm</string>
			<key>match</key>
			<string>(?x)
(var)[\/ ]
(?:(static|global|tmp|const)\/)?
(?:(datum|atom(?:\/movable)?|obj|mob|turf|area|savefile|list|client|sound|image|database|matrix|regex|exception)\/)?
(?:
	([a-zA-Z0-9_\-$]*)\/
)*

([A-Za-z0-9_$]*)\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.dm</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.dm</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.dm</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>variable.other.dm</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.numeric.dm</string>
			<key>match</key>
			<string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.control.dm</string>
			<key>match</key>
			<string>\b(sleep|spawn|break|continue|do|else|for|goto|if|return|switch|while)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.other.dm</string>
			<key>match</key>
			<string>\b(del|new)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.type.dm</string>
			<key>match</key>
			<string>\b(proc|verb|datum|atom(/movable)?|obj|mob|turf|area|savefile|list|client|sound|image|database|matrix|regex|exception)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.modifier.dm</string>
			<key>match</key>
			<string>\b(as|const|global|set|static|tmp)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>variable.language.dm</string>
			<key>match</key>
			<string>\b(usr|world|src|args)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.operator.dm</string>
			<key>match</key>
			<string>(\?|(&gt;|&lt;)(=)?|\.|:|/(=)?|~|\+(\+|=)?|-(-|=)?|\*(\*|=)?|%|&gt;&gt;|&lt;&lt;|=(=)?|!(=)?|&lt;&gt;|&amp;|&amp;&amp;|\^|\||\|\||\bto\b|\bin\b|\bstep\b)</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.language.dm</string>
			<key>match</key>
			<string>\b([A-Z_][A-Z_0-9]*)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.language.dm</string>
			<key>match</key>
			<string>\bnull\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>string.quoted.triple.dm</string>
			<key>begin</key>
			<string>{&quot;</string>
			<key>end</key>
			<string>&quot;}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string_escaped_char</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string_embedded_expression</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.dm</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.dm</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>string.quoted.double.dm</string>
			<key>begin</key>
			<string>&quot;</string>
			<key>end</key>
			<string>&quot;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string_escaped_char</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string_embedded_expression</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.dm</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.dm</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>string.quoted.single.dm</string>
			<key>begin</key>
			<string>&apos;</string>
			<key>end</key>
			<string>&apos;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string_escaped_char</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.dm</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.dm</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.preprocessor.macro.dm</string>
			<key>begin</key>
			<string>(?x)
^\s* ((\#)\s*define) \s+     # define
((?&lt;id&gt;[a-zA-Z_][a-zA-Z0-9_]*))  # macro name
(?:
	(\()
		(
			\s* \g&lt;id&gt; \s*         # first argument
			((,) \s* \g&lt;id&gt; \s*)*  # additional arguments
			(?:\.\.\.)?            # varargs ellipsis?
		)
	(\))
)</string>
			<key>end</key>
			<string>(?=(?://|/\*))|(?&lt;!\\)(?=\n)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$base</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.directive.define.dm</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.directive.dm</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.preprocessor.dm</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.dm</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.preprocessor.dm</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.parameters.dm</string>
				</dict>
				<key>9</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.end.dm</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.preprocessor.macro.dm</string>
			<key>begin</key>
			<string>(?x)
^\s* ((\#)\s*define) \s+     # define
((?&lt;id&gt;[a-zA-Z_][a-zA-Z0-9_]*))  # macro name</string>
			<key>end</key>
			<string>(?=(?://|/\*))|(?&lt;!\\)(?=\n)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$base</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.directive.define.dm</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.directive.dm</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.other.preprocessor.dm</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.preprocessor.diagnostic.dm</string>
			<key>begin</key>
			<string>^\s*(#\s*(error|warn))\b</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>punctuation.separator.continuation.dm</string>
					<key>match</key>
					<string>(?&gt;\\\s*\n)</string>
				</dict>
			</array>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.import.error.dm</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.preprocessor.dm</string>
			<key>begin</key>
			<string>^\s*(?:((#)\s*(?:elif|else|if|ifdef|ifndef))|((#)\s*(undef|include)))\b</string>
			<key>end</key>
			<string>(?=(?://|/\*))|(?&lt;!\\)(?=\n)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>punctuation.separator.continuation.dm</string>
					<key>match</key>
					<string>(?&gt;\\\s*\n)</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.directive.conditional.dm</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.directive.dm</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.control.directive.$5.dm</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.directive.dm</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>include</key>
			<string>#block</string>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.function.dm</string>
			<key>begin</key>
			<string>(?x)
				(?:  ^                                 # begin-of-line
					|
						 (?: (?= \s )           (?&lt;!else|new|return) (?&lt;=\w)      #  or word + space before name
							 | (?= \s*[A-Za-z_] ) (?&lt;!&amp;&amp;)       (?&lt;=[*&amp;&gt;])   #  or type modifier before name
						 )
				)
				(\s*) (?!(while|for|do|if|else|switch|catch|enumerate|return|r?iterate)\s*\()
				(
					(?: [A-Za-z_][A-Za-z0-9_]*+ | :: )++ |                  # actual name
					(?: (?&lt;=operator) (?: [-*&amp;&lt;&gt;=+!]+ | \(\) | \[\] ) )  # if it is a C++ operator
				)
				 \s*(?=\()</string>
			<key>end</key>
			<string>(?&lt;=\})|(?=#)|(;)?</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#parens</string>
				</dict>
				<dict>
					<key>name</key>
					<string>storage.modifier.dm</string>
					<key>match</key>
					<string>\bconst\b</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.function.leading.dm</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.dm</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.dm</string>
				</dict>
			</dict>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>access</key>
		<dict>
			<key>name</key>
			<string>variable.other.dot-access.dm</string>
			<key>match</key>
			<string>\.[a-zA-Z_][a-zA-Z_0-9]*\b(?!\s*\()</string>
		</dict>
		<key>block</key>
		<dict>
			<key>name</key>
			<string>meta.block.dm</string>
			<key>begin</key>
			<string>\{</string>
			<key>end</key>
			<string>\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#block_innards</string>
				</dict>
			</array>
		</dict>
		<key>block_innards</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#preprocessor-rule-enabled-block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#preprocessor-rule-disabled-block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#preprocessor-rule-other-block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#access</string>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.function-call.dm</string>
					<key>match</key>
					<string>(?x) (?: (?= \s )  (?:(?&lt;=else|new|return) | (?&lt;!\w)) (\s+))?
			(\b
				(?!(while|for|do|if|else|switch|catch|enumerate|return|r?iterate)\s*\()(?:(?!NS)[A-Za-z_][A-Za-z0-9_]*+\b | :: )++                  # actual name
			)
			 \s*(\()</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.whitespace.function-call.leading.dm</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.function.any-method.dm</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.dm</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>include</key>
					<string>#block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$base</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>comment.block.dm</string>
					<key>match</key>
					<string>^/\* =(\s*.*?)\s*= \*/$\n?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.toc-list.banner.block.dm</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>comment.block.dm</string>
					<key>begin</key>
					<string>/\*</string>
					<key>end</key>
					<string>\*/</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
					</array>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.dm</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>invalid.illegal.stray-comment-end.dm</string>
					<key>match</key>
					<string>\*/.*\n</string>
				</dict>
				<dict>
					<key>name</key>
					<string>comment.line.banner.dm</string>
					<key>match</key>
					<string>^// =(\s*.*?)\s*=\s*$\n?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.toc-list.banner.line.dm</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>comment.line.double-slash.dm</string>
					<key>begin</key>
					<string>//</string>
					<key>end</key>
					<string>$\n?</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>punctuation.separator.continuation.dm</string>
							<key>match</key>
							<string>(?&gt;\\\s*\n)</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.dm</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>disabled</key>
		<dict>
			<key>begin</key>
			<string>^\s*#\s*if(n?def)?\b.*$</string>
			<key>end</key>
			<string>^\s*#\s*endif\b.*$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#disabled</string>
				</dict>
			</array>
		</dict>
		<key>parens</key>
		<dict>
			<key>name</key>
			<string>meta.parens.dm</string>
			<key>begin</key>
			<string>\(</string>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$base</string>
				</dict>
			</array>
		</dict>
		<key>preprocessor-rule-disabled</key>
		<dict>
			<key>begin</key>
			<string>^\s*(#(if)\s+(0)\b).*</string>
			<key>end</key>
			<string>^\s*(#\s*(endif)\b)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(#\s*(else)\b)</string>
					<key>end</key>
					<string>(?=^\s*#\s*endif\b.*$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$base</string>
						</dict>
					</array>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.preprocessor.dm</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.import.else.dm</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>comment.block.preprocessor.if-branch</string>
					<key>end</key>
					<string>(?=^\s*#\s*(else|endif)\b.*$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#disabled</string>
						</dict>
					</array>
				</dict>
			</array>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.preprocessor.dm</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.import.if.dm</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.preprocessor.dm</string>
				</dict>
			</dict>
		</dict>
		<key>preprocessor-rule-disabled-block</key>
		<dict>
			<key>begin</key>
			<string>^\s*(#(if)\s+(0)\b).*</string>
			<key>end</key>
			<string>^\s*(#\s*(endif)\b)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(#\s*(else)\b)</string>
					<key>end</key>
					<string>(?=^\s*#\s*endif\b.*$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#block_innards</string>
						</dict>
					</array>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.preprocessor.dm</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.import.else.dm</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>comment.block.preprocessor.if-branch.in-block</string>
					<key>end</key>
					<string>(?=^\s*#\s*(else|endif)\b.*$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#disabled</string>
						</dict>
					</array>
				</dict>
			</array>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.preprocessor.dm</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.import.if.dm</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.preprocessor.dm</string>
				</dict>
			</dict>
		</dict>
		<key>preprocessor-rule-enabled</key>
		<dict>
			<key>begin</key>
			<string>^\s*(#(if)\s+(0*1)\b)</string>
			<key>end</key>
			<string>^\s*(#\s*(endif)\b)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>contentName</key>
					<string>comment.block.preprocessor.else-branch</string>
					<key>begin</key>
					<string>^\s*(#\s*(else)\b).*</string>
					<key>end</key>
					<string>(?=^\s*#\s*endif\b.*$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#disabled</string>
						</dict>
					</array>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.preprocessor.dm</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.import.else.dm</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>end</key>
					<string>(?=^\s*#\s*(else|endif)\b.*$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$base</string>
						</dict>
					</array>
				</dict>
			</array>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.preprocessor.dm</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.import.if.dm</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.preprocessor.dm</string>
				</dict>
			</dict>
		</dict>
		<key>preprocessor-rule-enabled-block</key>
		<dict>
			<key>begin</key>
			<string>^\s*(#(if)\s+(0*1)\b)</string>
			<key>end</key>
			<string>^\s*(#\s*(endif)\b)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>contentName</key>
					<string>comment.block.preprocessor.else-branch.in-block</string>
					<key>begin</key>
					<string>^\s*(#\s*(else)\b).*</string>
					<key>end</key>
					<string>(?=^\s*#\s*endif\b.*$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#disabled</string>
						</dict>
					</array>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.preprocessor.dm</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.import.else.dm</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>end</key>
					<string>(?=^\s*#\s*(else|endif)\b.*$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#block_innards</string>
						</dict>
					</array>
				</dict>
			</array>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.preprocessor.dm</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.import.if.dm</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.preprocessor.dm</string>
				</dict>
			</dict>
		</dict>
		<key>preprocessor-rule-other</key>
		<dict>
			<key>begin</key>
			<string>^\s*((#\s*(if(n?def)?))\b.*?(?:(?=(?://|/\*))|$))</string>
			<key>end</key>
			<string>^\s*((#\s*(endif))\b).*$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$base</string>
				</dict>
			</array>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.preprocessor.dm</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.import.dm</string>
				</dict>
			</dict>
		</dict>
		<key>preprocessor-rule-other-block</key>
		<dict>
			<key>begin</key>
			<string>^\s*(#\s*(if(n?def)?)\b.*?(?:(?=(?://|/\*))|$))</string>
			<key>end</key>
			<string>^\s*(#\s*(endif)\b).*$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#block_innards</string>
				</dict>
			</array>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.preprocessor.dm</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.import.dm</string>
				</dict>
			</dict>
		</dict>
		<key>string_embedded_expression</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>string.interpolated.dm</string>
					<key>begin</key>
					<string>(?&lt;!\\)\[</string>
					<key>end</key>
					<string>\]</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>string_escaped_char</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.character.escape.dm</string>
					<key>match</key>
					<string>(?x)
\\
(
	h(?:(?:er|im)self|ers|im)
	|([tTsS]?he) # Weird regex to match The, the, She, she and he at once.
	|He
	|[Hh]is
	|[aA]n?
	|(?:im)?proper
	|\.\.\.
	|(?:icon|ref|[Rr]oman)(?=\[) # Macros which need a [] after them.
	|[s&lt;&gt;&quot;n\n \[]
)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>invalid.illegal.unknown-escape.dm</string>
					<key>match</key>
					<string>\\.</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>dm</string>
	</array>
</dict>
</plist>
