<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Ecmarkup</string>
	<key>scopeName</key>
	<string>text.html.ecmarkup</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>\A(?=\s*(?:\d+\.|\*)(?=$|\s))</string>
			<key>end</key>
			<string>(?=A)B</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#list</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#main</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#main</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>code-blocks</key>
		<dict>
			<key>name</key>
			<string>meta.tag.opaque-element.${2:/downcase}.html.ecmarkup</string>
			<key>begin</key>
			<string>(?i)\s*(&lt;(pre|code)(?=$|\s|&gt;))</string>
			<key>end</key>
			<string>(?i)\s*(&lt;/\2\s*&gt;)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-opening-rest</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#main</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tag-opening-start</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tag-closing</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>emu-alg</key>
		<dict>
			<key>name</key>
			<string>meta.emu-alg.html.ecmarkup</string>
			<key>begin</key>
			<string>(?i)\s*(&lt;emu-alg(?=$|\s|&gt;))</string>
			<key>end</key>
			<string>(?i)\s*(&lt;/emu-alg\s*&gt;)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-opening-rest</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;=&gt;)</string>
					<key>end</key>
					<string>(?i)(?=\s*(&lt;/emu-alg\s*&gt;))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#list</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#main</string>
						</dict>
					</array>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tag-opening-start</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tag-closing</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>emu-element</key>
		<dict>
			<key>name</key>
			<string>meta.${2:/downcase}.html.ecmarkup</string>
			<key>begin</key>
			<string>(?i)\s*(&lt;(emu-[\w][-\w]*)(?=$|\s|&gt;))</string>
			<key>end</key>
			<string>(?i)\s*(&lt;/\2\s*&gt;)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-opening-rest</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag-body</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tag-opening-start</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tag-closing</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>emu-grammar</key>
		<dict>
			<key>name</key>
			<string>meta.emu-grammar.html.ecmarkup</string>
			<key>begin</key>
			<string>(?i)\s*(&lt;emu-grammar(?=$|\s|&gt;))</string>
			<key>end</key>
			<string>(?i)\s*(&lt;/emu-grammar\s*&gt;)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-opening-rest</string>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.grammar.ecmarkup</string>
					<key>contentName</key>
					<string>text.embedded.grammarkdown</string>
					<key>begin</key>
					<string>(?&lt;=&gt;)</string>
					<key>end</key>
					<string>(?i)(?=\s*(&lt;/emu-grammar\s*&gt;))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.grammarkdown</string>
						</dict>
					</array>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tag-opening-start</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tag-closing</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>escape</key>
		<dict>
			<key>name</key>
			<string>constant.character.escape.ecmarkup</string>
			<key>match</key>
			<string>(\\)[*_`&lt;|~\\]</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.escape.backslash.ecmarkup</string>
				</dict>
			</dict>
		</dict>
		<key>formatting</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>variable.reference.ecmarkup</string>
					<key>match</key>
					<string>(?&lt;![\w*_`&lt;|~])(_)((?:\\_|[^\s_])++)(_)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.begin.ecmarkup</string>
						</dict>
						<key>2</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#escape</string>
								</dict>
							</array>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.end.ecmarkup</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.other.value.ecmarkup</string>
					<key>match</key>
					<string>(?&lt;![\w*_`&lt;|~])(\*)(?=\S)((?:\\\*|[^*])++)(?&lt;=\S)(\*)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.value.begin.ecmarkup</string>
						</dict>
						<key>2</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#escape</string>
								</dict>
							</array>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.value.end.ecmarkup</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>markup.raw.code.monospace.ecmarkup</string>
					<key>match</key>
					<string>(\`)(?=\S)((?:\\`|[^`])++)(?&lt;=\S)(\`)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.value.begin.ecmarkup</string>
						</dict>
						<key>2</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#escape</string>
								</dict>
							</array>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.value.end.ecmarkup</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>support.constant.spec-level.ecmarkup</string>
					<key>match</key>
					<string>(?&lt;![\w*_`&lt;|~])(~)(?=\S)((?:\\~|[^~])++)(?&lt;=\S)(~)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.begin.ecmarkup</string>
						</dict>
						<key>2</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#escape</string>
								</dict>
							</array>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.end.ecmarkup</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>include</key>
					<string>#nonterminal</string>
				</dict>
			</array>
		</dict>
		<key>list</key>
		<dict>
			<key>name</key>
			<string>meta.list.ecmarkup</string>
			<key>begin</key>
			<string>^(\s*)((\d+\.|\*))(?=$|\s)(?:\s*(Assert(:)))?[ \t]*</string>
			<key>end</key>
			<string>(?=\s*&lt;/(?i:emu-alg)\s*&gt;)|(?!\G)^(?=\s*(?:$|(?:\d+\.|\*)(?:$|\s)))</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\G(?=\[)</string>
					<key>end</key>
					<string>(?&lt;=\])(?:\s*(Assert(:)))?</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>meta.attributes.ecmarkup</string>
							<key>begin</key>
							<string>\G(\[)</string>
							<key>end</key>
							<string>(\])</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>name</key>
									<string>meta.attribute.ecmarkup</string>
									<key>begin</key>
									<string>(\w[-\w]*)\s*(=)\s*(?=&quot;)</string>
									<key>end</key>
									<string>(?!\G)</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>etc#strDouble</string>
										</dict>
										<dict>
											<key>include</key>
											<string>etc#comma</string>
										</dict>
									</array>
									<key>beginCaptures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>entity.other.attribute-name.ecmarkup</string>
										</dict>
										<key>2</key>
										<dict>
											<key>patterns</key>
											<array>
												<dict>
													<key>include</key>
													<string>etc#eql</string>
												</dict>
											</array>
										</dict>
									</dict>
									<key>applyEndPatternLast</key>
									<true />
								</dict>
							</array>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.list.begin.ecmarkup</string>
								</dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>brackethighlighter.square</string>
								</dict>
							</dict>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.list.end.ecmarkup</string>
								</dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>brackethighlighter.square</string>
								</dict>
							</dict>
						</dict>
					</array>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant.assertion.ecmarkup</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>puncutation.definition.constant.ecmarkup</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>include</key>
					<string>#main</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.list.marker.ecmarkup</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.list.ecmarkup</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>support.constant.assertion.ecmarkup</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>puncutation.definition.constant.ecmarkup</string>
				</dict>
			</dict>
		</dict>
		<key>main</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#emu-alg</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#emu-grammar</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#emu-element</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#metadata-block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#code-blocks</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#escape</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#formatting</string>
				</dict>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
			</array>
		</dict>
		<key>metadata-block</key>
		<dict>
			<key>name</key>
			<string>meta.tag.block.pre.front-matter.html.ecmarkup</string>
			<key>contentName</key>
			<string>source.embedded.yaml.front-matter.ecmarkup</string>
			<key>begin</key>
			<string>(?ix) \s*
((&lt;)(pre)
(
	\s+[^&gt;]*?(?&lt;=\s)
	class \s* = \s*
	(?:&quot;metadata&quot;|&apos;metadata&apos;|metadata)
	(?=\s|&gt;) [^&gt;]*
)
(&gt;))</string>
			<key>end</key>
			<string>(?i)\s*((&lt;/)(pre)\s*(&gt;))</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.yaml</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.tag.other.html.ecmarkup</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.html.ecmarkup</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.block.pre.html</string>
				</dict>
				<key>4</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.html.basic#tag-stuff</string>
						</dict>
					</array>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.html</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.tag.block.pre.html</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.html</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.block.pre.html</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.html</string>
				</dict>
			</dict>
		</dict>
		<key>nonterminal</key>
		<dict>
			<key>name</key>
			<string>meta.nonterminal.ecmarkup</string>
			<key>match</key>
			<string>(?x) (?&lt;![\w*_`&lt;|~])
((\|))
([A-Za-z0-9]+)
(\[ [^\]]* \])?
(?: (\?) | ((_)opt))?
((\|))</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.nonterminal.begin.ecmarkup</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>brackethighlighter.tag</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.other.nonterminal.ecmarkup</string>
				</dict>
				<key>4</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#nonterminal-params</string>
						</dict>
					</array>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.optional.question-mark.ecmarkup</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.optional.english.ecmarkup</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.suffix.ecmarkup</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.nonterminal.end.ecmarkup</string>
				</dict>
				<key>9</key>
				<dict>
					<key>name</key>
					<string>brackethighlighter.tag</string>
				</dict>
			</dict>
		</dict>
		<key>nonterminal-params</key>
		<dict>
			<key>name</key>
			<string>meta.parameters.ecmarkup</string>
			<key>begin</key>
			<string>(\[)</string>
			<key>end</key>
			<string>(\])</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>variable.parameter.nonterminal.ecmarkup</string>
					<key>match</key>
					<string>\w[-\w]*</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.optional.question-mark.ecmarkup</string>
					<key>match</key>
					<string>\?</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#escape</string>
				</dict>
				<dict>
					<key>include</key>
					<string>etc#comma</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.list.begin.ecmarkup</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>brackethighlighter.square</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.list.end.ecmarkup</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>brackethighlighter.square</string>
				</dict>
			</dict>
		</dict>
		<key>tag-body</key>
		<dict>
			<key>name</key>
			<string>meta.tag-contents.html.ecmarkup</string>
			<key>begin</key>
			<string>(?&lt;=&gt;)</string>
			<key>end</key>
			<string>(?=\s*&lt;/emu-[-\w]*\s*&gt;)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#main</string>
				</dict>
			</array>
		</dict>
		<key>tag-closing</key>
		<dict>
			<key>name</key>
			<string>meta.tag.other.html.ecmarkup</string>
			<key>match</key>
			<string>(?i)(?:^|\G)(&lt;/)(\w[-\w]*)\s*(&gt;)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.html.ecmarkup</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.other.html.ecmarkup</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.html.ecmarkup</string>
				</dict>
			</dict>
		</dict>
		<key>tag-opening-rest</key>
		<dict>
			<key>begin</key>
			<string>\G</string>
			<key>end</key>
			<string>\s*(&gt;)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.basic#tag-stuff</string>
				</dict>
			</array>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.html.ecmarkup</string>
				</dict>
			</dict>
		</dict>
		<key>tag-opening-start</key>
		<dict>
			<key>name</key>
			<string>meta.tag.other.html.ecmarkup</string>
			<key>match</key>
			<string>(?:^|\G)(&lt;)(\w[-\w]*)(?=$|\s|&gt;)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.html.ecmarkup</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.other.html.ecmarkup</string>
				</dict>
			</dict>
		</dict>
	</dict>
	<key>injections</key>
	<dict>
		<key>L:(source.embedded.yaml.front-matter.ecmarkup - (comment | embedded))</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.basic#character-reference</string>
				</dict>
			</array>
		</dict>
		<key>L:(text.html.ecmarkup meta.tag.opaque-element - (meta.emu-alg | meta.emu-grammar))</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[*_`|~\\]</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>html</string>
	</array>
</dict>
</plist>
