<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Elvish</string>
	<key>scopeName</key>
	<string>source.elvish</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>name</key>
			<string>string.quoted.double.elvish</string>
			<key>begin</key>
			<string>&quot;</string>
			<key>end</key>
			<string>&quot;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.character.escape.elvish</string>
					<key>match</key>
					<string>\\.</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>name</key>
			<string>string.quoted.single.elvish</string>
			<key>begin</key>
			<string>&apos;</string>
			<key>end</key>
			<string>&apos;</string>
		</dict>
		<dict>
			<key>name</key>
			<string>comment.line.number-sign.elvish</string>
			<key>begin</key>
			<string>#</string>
			<key>end</key>
			<string>$</string>
		</dict>
		<dict>
			<key>name</key>
			<string>variable.other.elvish</string>
			<key>match</key>
			<string>\$[\w\d_:~-]+</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=\G|^|\{ |\{	|\(|\||\;)\s*(var|set|tmp|del)((\s+[\w\d_:~-]+)+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.elvish</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other.elvish</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=\G|^|\{ |\{	|\(|\||\;)\s*(for)\s+([\w\d_:~-]+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.elvish</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other.elvish</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=})\s+(catch|except)\s+([\w\d_:~-]+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.elvish</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other.elvish</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=\G|^|\{ |\{	|\(|\||\;)\s*(nop|!=|!=s|%|\*|\+|-gc|-ifaddrs|-log|-override-wcwidth|-stack|-|/|&lt;|&lt;=|&lt;=s|&lt;s|==|==s|&gt;|&gt;=|&gt;=s|&gt;s|all|assoc|base|bool|break|call|cd|compare|constantly|continue|count|defer|deprecate|dissoc|drop|each|eawk|echo|eq|eval|exact-num|exec|exit|external|fail|fg|float64|from-json|from-lines|from-terminated|get-env|has-env|has-external|has-key|has-value|is|keys|kind-of|make-map|multi-error|nop|not-eq|not|ns|num|one|only-bytes|only-values|order|peach|pprint|print|printf|put|rand|randint|range|read-line|read-upto|repeat|repr|resolve|return|run-parallel|search-external|set-env|show|sleep|slurp|src|styled|styled-segment|take|tilde-abbr|time|to-json|to-lines|to-string|to-terminated|unset-env|use-mod|wcswidth)(?=[\s)}&lt;&gt;;|&amp;])</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.elvish</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=\G|^|\{ |\{	|\(|\||\;)\s*(and|or|coalesce)(?=[\s)}&lt;&gt;;|&amp;])</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.elvish</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=\G|^|\{ |\{	|\(|\||\;)\s*(use|var|set|tmp|del|pragma|fn)(?=[\s)}&lt;&gt;;|&amp;])</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.elvish</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=\G|^|\{ |\{	|\(|\||\;)\s*(while|for|try|if)(?=[\s)}&lt;&gt;;|&amp;])</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.elvish</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=})\s+(elif|else|catch|except|finally)(?=[\s)}&lt;&gt;;|&amp;])</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.elvish</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.operator.elvish</string>
			<key>match</key>
			<string>[*?|&amp;;&lt;&gt;()\[\]{}]</string>
		</dict>
	</array>
	<key>fileTypes</key>
	<array>
		<string>elv</string>
	</array>
</dict>
</plist>
