<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Fortran - Punchcard</string>
	<key>scopeName</key>
	<string>source.fortran</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#preprocessor-rule-enabled</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#preprocessor-rule-disabled</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#preprocessor-rule-other</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.language.fortran</string>
			<key>match</key>
			<string>(?i:(r8|r4|\.TRUE\.|\.FALSE\.))</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.numeric.fortran</string>
			<key>match</key>
			<string>\b[\+\-]?[0-9]+\.?[0-9a-zA-Z_]*\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.function.fortran</string>
			<key>begin</key>
			<string>(?x:								# extended mode
					^
					\s*									# start of line and possibly some space
					([a-zA-Z\(\)]*)(?&lt;!end)				# 1: possibly some type specification but not the word end
					\s*									# possibly some space
					(?i:(function|subroutine))\b		# 2: function or subroutine
					\s+									# some space
					([A-Za-z_][A-Za-z0-9_]*)			# 3: name
					)</string>
			<key>end</key>
			<string>(?x:									# extended mode
					((?i:end))							# 1: the word end
					(									# followed by
						$								# end of line
					|									# or
						\s*								# possibly some space
						(?i:(function|subroutine))		# 2: function or subroutine
						((\s+[A-Za-z_][A-Za-z0-9_]*)?)	# 3: possibly the name
					)
					)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\G\s*(\()</string>
					<key>end</key>
					<string>\)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>([^\s),]*)\s*(,)?</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>variable.parameter.fortran</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.separator.arguments.fortan</string>
								</dict>
							</dict>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.begin.fortran</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.end.fortran</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>include</key>
					<string>$base</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.fortran</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.fortran</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.fortran</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.fortran</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.fortran</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.end.fortran</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.specification.fortran</string>
			<key>begin</key>
			<string>\b(?i:(integer|real|double\s+precision|complex|logical|character))\b(?=.*::)</string>
			<key>end</key>
			<string>(?=!)|$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$base</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.fortran</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.control.fortran</string>
			<key>match</key>
			<string>\b(?i:(go\s*to|assign|to|if|then|else|elseif|end\s*if|continue|stop|pause|do|end\s*do|while|cycle))\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.control.programming-units.fortran</string>
			<key>match</key>
			<string>\b(?i:(program|end\s+program|entry|block\s+data|call|return|contains|include))\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.control.io.fortran</string>
			<key>match</key>
			<string>\b(?i:(open|close|read|write|print|inquire|backspace|endfile|format))\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.operator.fortran</string>
			<key>match</key>
			<string>((?&lt;!\=)\=(?!\=)|\-|\+|\/\/|\/|(?!^)\*|::)</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.operator.logical.fortran</string>
			<key>match</key>
			<string>(?i:(\.and\.|\.or\.|\.eq\.|\.lt\.|\.le\.|\.gt\.|\.ge\.|\.ne\.|\.not\.|\.eqv\.|\.neqv\.))</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.other.instrisic.argument.fortran</string>
			<key>match</key>
			<string>\b(?i:(present)(?=\())</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.other.instrisic.numeric.fortran</string>
			<key>match</key>
			<string>\b(?i:(abs|aimag|aint|anint|cmplx|conjg|dble|dim|dprod|int|max|min|mod|nint|real|sign|digits|epsilon|huge|maxexponent|minexponent|precision|radix|range|tiny)(?=\())</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.other.instrisic.string.fortran</string>
			<key>match</key>
			<string>\b(?i:(achar|adjustl|adjustr|char|iachar|ichar|index|len_trim|repeat|scan|string|trim|verify|len)(?=\())</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.other.instrisic.math.fortran</string>
			<key>match</key>
			<string>\b(?i:(((acos|asin|atan|atan2|cos|cosh|exp|log|log10|sin|sinh|sqrt|tan|tanh)(?=\())|(random_number|random_seed)))\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.other.instrisic.data.fortran</string>
			<key>match</key>
			<string>\b(?i:(kind|selected_int_kind|selected_real_kind|transfer)(?=\())</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.other.instrisic.logical.fortran</string>
			<key>match</key>
			<string>\b(?i:(logical)(?=\())</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.other.instrisic.bit.fortran</string>
			<key>match</key>
			<string>\b(?i:(((bit_size|btest|iand|ibclr|ibits|ibset|ieor|ior|ishift|ishiftc|not)(?=\())|mvbits))\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.other.instrisic.floating-point.fortran</string>
			<key>match</key>
			<string>\b(?i:(exponent|fraction|nearest|rrspacing|scale|set_exponent|spacing)(?=\())</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.other.instrisic.array.fortran</string>
			<key>match</key>
			<string>\b(?i:(((dot_product|sum|matmul|transpose|all|any|count|maxval|minval|maxloc|minloc|product|sum|lbound|ubound|shape|size|merge|pack|unpack|reshape|spread|cshift|eoshift)(?=\())|(where|elsewhere|end\s*where)))\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.other.instrisic.fortran</string>
			<key>match</key>
			<string>\b(?i:(((dtime)(?=\())|(date_and_time|system_clock)))\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.type.fortran</string>
			<key>match</key>
			<string>\b(?i:(integer|real|double\s+precision|complex|logical|character|block\sdata|operator|assignment))\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.modifier.fortran</string>
			<key>match</key>
			<string>\b(?i:(dimension|common|equivalence|parameter|external|intrinsic|save|data|implicit\s*none|implicit|intent|in|out|inout))\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>string.quoted.single.fortran</string>
			<key>begin</key>
			<string>&apos;</string>
			<key>end</key>
			<string>&apos;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.character.escape.apostrophe.fortran</string>
					<key>match</key>
					<string>&apos;&apos;</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.fortran</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.fortran</string>
				</dict>
			</dict>
			<key>applyEndPatternLast</key>
			<true />
		</dict>
		<dict>
			<key>name</key>
			<string>string.quoted.double.fortran</string>
			<key>begin</key>
			<string>&quot;</string>
			<key>end</key>
			<string>&quot;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.character.escape.quote.fortran</string>
					<key>match</key>
					<string>&quot;&quot;</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.fortran</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.fortran</string>
				</dict>
			</dict>
			<key>applyEndPatternLast</key>
			<true />
		</dict>
		<dict>
			<key>name</key>
			<string>meta.preprocessor.diagnostic.fortran</string>
			<key>begin</key>
			<string>^\s*#\s*(error|warning)\b</string>
			<key>end</key>
			<string>$\n?</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>punctuation.separator.continuation.fortran</string>
					<key>match</key>
					<string>(?&gt;\\\s*\n)</string>
				</dict>
			</array>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.import.error.fortran</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.preprocessor.fortran.include</string>
			<key>begin</key>
			<string>^\s*#\s*(include|import)\b\s+</string>
			<key>end</key>
			<string>(?=(?://|/\*))|$\n?</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>punctuation.separator.continuation.fortran</string>
					<key>match</key>
					<string>(?&gt;\\\s*\n)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>string.quoted.double.include.fortran</string>
					<key>begin</key>
					<string>&quot;</string>
					<key>end</key>
					<string>&quot;</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.fortran</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.fortran</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>string.quoted.other.lt-gt.include.fortran</string>
					<key>begin</key>
					<string>&lt;</string>
					<key>end</key>
					<string>&gt;</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.fortran</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.fortran</string>
						</dict>
					</dict>
				</dict>
			</array>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.import.include.fortran</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>include</key>
			<string>#pragma-mark</string>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.preprocessor.fortran</string>
			<key>begin</key>
			<string>^\s*#\s*(define|defined|elif|else|if|ifdef|ifndef|line|pragma|undef)\b</string>
			<key>end</key>
			<string>(?=(?://|/\*))|$\n?</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>punctuation.separator.continuation.fortran</string>
					<key>match</key>
					<string>(?&gt;\\\s*\n)</string>
				</dict>
			</array>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.import.fortran</string>
				</dict>
			</dict>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>disabled</key>
		<dict>
			<key>begin</key>
			<string>^\s*#\s*if(n?def)?\b.*$</string>
			<key>end</key>
			<string>^\s*#\s*endif\b.*$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#disabled</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#pragma-mark</string>
				</dict>
			</array>
		</dict>
		<key>pragma-mark</key>
		<dict>
			<key>name</key>
			<string>meta.section</string>
			<key>match</key>
			<string>^\s*(#\s*(pragma\s+mark)\s+(.*))</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.preprocessor.fortran</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.import.pragma.fortran</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>meta.toc-list.pragma-mark.fortran</string>
				</dict>
			</dict>
		</dict>
		<key>preprocessor-rule-disabled</key>
		<dict>
			<key>begin</key>
			<string>^\s*(#(if)\s+(0)\b).*</string>
			<key>end</key>
			<string>^\s*(#\s*(endif)\b)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(#\s*(else)\b)</string>
					<key>end</key>
					<string>(?=^\s*#\s*endif\b.*$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$base</string>
						</dict>
					</array>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.preprocessor.fortran</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.import.else.fortran</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>comment.block.preprocessor.if-branch</string>
					<key>end</key>
					<string>(?=^\s*#\s*(else|endif)\b.*$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#disabled</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#pragma-mark</string>
						</dict>
					</array>
				</dict>
			</array>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.preprocessor.fortran</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.import.if.fortran</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.preprocessor.fortran</string>
				</dict>
			</dict>
		</dict>
		<key>preprocessor-rule-enabled</key>
		<dict>
			<key>begin</key>
			<string>^\s*(#(if)\s+(0*1)\b)</string>
			<key>end</key>
			<string>^\s*(#\s*(endif)\b)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>contentName</key>
					<string>comment.block.preprocessor.else-branch</string>
					<key>begin</key>
					<string>^\s*(#\s*(else)\b).*</string>
					<key>end</key>
					<string>(?=^\s*#\s*endif\b.*$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#disabled</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#pragma-mark</string>
						</dict>
					</array>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.preprocessor.fortran</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.import.else.fortran</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>end</key>
					<string>(?=^\s*#\s*(else|endif)\b.*$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$base</string>
						</dict>
					</array>
				</dict>
			</array>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.preprocessor.fortran</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.import.if.fortran</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.preprocessor.fortran</string>
				</dict>
			</dict>
		</dict>
		<key>preprocessor-rule-other</key>
		<dict>
			<key>begin</key>
			<string>^\s*(#\s*(if(n?def)?)\b.*?(?:(?=(?://|/\*))|$))</string>
			<key>end</key>
			<string>^\s*(#\s*(endif)\b).*$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$base</string>
				</dict>
			</array>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.preprocessor.fortran</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.import.fortran</string>
				</dict>
			</dict>
		</dict>
	</dict>
	<key>injections</key>
	<dict>
		<key>source.fortran - (source.fortran.modern)</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>comment.line.c.fortran</string>
					<key>begin</key>
					<string>^[Cc](?=\b|[Cc])</string>
					<key>end</key>
					<string>$\n?</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\\s*\n</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.fortran</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>comment.line.asterisk.fortran</string>
					<key>begin</key>
					<string>^\*</string>
					<key>end</key>
					<string>$\n?</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\\s*\n</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.fortran</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>f</string>
		<string>f77</string>
		<string>for</string>
		<string>fpp</string>
	</array>
</dict>
</plist>
