<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>VSCode GCode Syntax</string>
	<key>scopeName</key>
	<string>source.gcode</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#all</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>all</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bracket-expression</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#speedsfeeds</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#prognumbers</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#coords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tools</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#modifiers</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#macrovars</string>
				</dict>
			</array>
		</dict>
		<key>bracket-expression</key>
		<dict>
			<key>name</key>
			<string>expression.group</string>
			<key>begin</key>
			<string>\[</string>
			<key>end</key>
			<string>\]</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#all</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.paren.open</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.paren.close</string>
				</dict>
			</dict>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>comment.gcode</string>
					<key>match</key>
					<string>(\(.+\))</string>
				</dict>
				<dict>
					<key>name</key>
					<string>comment.gcode</string>
					<key>begin</key>
					<string>;</string>
					<key>end</key>
					<string>\n</string>
				</dict>
			</array>
		</dict>
		<key>coords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>string.gcode</string>
					<key>match</key>
					<string>([xX])\s?(\-?\d*\.?\d+\.?|\-?\.?(?=[#\[]))</string>
				</dict>
				<dict>
					<key>name</key>
					<string>string.gcode</string>
					<key>match</key>
					<string>([yY])\s?(\-?\d*\.?\d+\.?|\-?\.?(?=[#\[]))</string>
				</dict>
				<dict>
					<key>name</key>
					<string>invalid.gcode</string>
					<key>match</key>
					<string>([zZ])\s?(\-?\d*\.?\d+\.?|\-?\.?(?=[#\[]))</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.escape.gcode</string>
					<key>match</key>
					<string>([aAbBcC])\s?(\-*\d?\.?\d+\.?|\-?\.?(?=[#\[]))</string>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.control.gcode</string>
					<key>match</key>
					<string>(GOTO(?&gt;\d+))|(IF)|(EQ)|(NE)|(LT)|(GT)|(LE)|(GE)|(DO ?(?&gt;\d+))|(WHILE)|(WH)|(END ?(?&gt;\d+))|(AND)|(OR)|(XOR)|(THEN)|(ELSE)|(ENDIF)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.gcode</string>
					<key>match</key>
					<string>[gG](1)?5[4-9](.1)?\s?(P[0-9]{1,3})?</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.gcode</string>
					<key>match</key>
					<string>[gG]1[1-2][0-9]</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.gcode</string>
					<key>match</key>
					<string>[gG]15\s?(H[0-9]{1,2})?</string>
				</dict>
				<dict>
					<key>name</key>
					<string>markup.bold.gcode</string>
					<key>match</key>
					<string>[gG][0-9]{1,3}(\.[0-9])?</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.quantifier.regexp.gcode</string>
					<key>match</key>
					<string>[mM][0-9]{1,3}</string>
				</dict>
				<dict>
					<key>name</key>
					<string>string.gcode</string>
					<key>match</key>
					<string>([\%])</string>
				</dict>
			</array>
		</dict>
		<key>macrovars</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>variable.other.gcode</string>
					<key>match</key>
					<string>[#][0-9]+</string>
				</dict>
				<dict>
					<key>name</key>
					<string>variable.other.gcode</string>
					<key>match</key>
					<string>[#][\[].+[\]]</string>
				</dict>
			</array>
		</dict>
		<key>modifiers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.character.escape.gcode</string>
					<key>match</key>
					<string>([iIjJkK])(\-?\d*\.?\d+\.?|\-?\.?(?=[#\[]))</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.constant.math.gcode</string>
					<key>match</key>
					<string>([qQrR])(\-?\d*\.?\d+\.?|\-?\.?(?=[#\[]]))</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.constant.math.gcode</string>
					<key>match</key>
					<string>([uUwW])(\-?\d*\.?\d+\.?|\-?\.?(?=[#\[]]))</string>
				</dict>
			</array>
		</dict>
		<key>operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>support.constant.math.gcode</string>
					<key>match</key>
					<string>(SIN)|(COS)|(TAN)|(ASIN)|(ACOS)|(ATAN)|(FIX)|(FUP)|(LN)|(ROUND)|(SQRT)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.constant.math.gcode</string>
					<key>match</key>
					<string>(FIX)|(FUP)|(ROUND)|(ABS)|(MOD)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.constant.math.gcode</string>
					<key>match</key>
					<string>(\+)|(\*)|(\/)|(\*\*)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>invalid.gcode</string>
					<key>match</key>
					<string>(\-)</string>
				</dict>
			</array>
		</dict>
		<key>prognumbers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.numeric.gcode</string>
					<key>match</key>
					<string>(^[nN])(\d+)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>string.regexp.gcode</string>
					<key>match</key>
					<string>(^[oO])(\d+)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>string.regexp.gcode</string>
					<key>match</key>
					<string>([pP])\s?(\d?\.?\d+\.?|\.?(?=[#\[]))</string>
				</dict>
			</array>
		</dict>
		<key>speedsfeeds</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.language.gcode</string>
					<key>match</key>
					<string>([sS])\s?(\d+|(?=[#\[]))</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.gcode</string>
					<key>match</key>
					<string>([eEfF])\s?(\d*\.?\d+\.?|\.?(?=[#\[]))</string>
				</dict>
			</array>
		</dict>
		<key>tools</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.character.gcode</string>
					<key>match</key>
					<string>([dD])\s?(\d*\.?\d*|(?=[#\[]))</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.gcode</string>
					<key>match</key>
					<string>([hH])\s?(\d*\.?\d*|(?=[#\[]))</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.gcode</string>
					<key>match</key>
					<string>([tT])\s?(\d*\.?\d*|(?=[#\[]))</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>g</string>
		<string>cnc</string>
		<string>gco</string>
		<string>gcode</string>
	</array>
</dict>
</plist>
