<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>GDScript</string>
	<key>scopeName</key>
	<string>source.gdscript</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#base_expression</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#logic_op</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#compare_op</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#arithmetic_op</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#assignment_op</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#self</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#const_def</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#type_declear</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#class_def</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#class_name</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#builtin_func</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#builtin_get_node_shorthand</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#builtin_classes</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#const_vars</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#class_new</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#class_is</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#class_enum</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#function-declaration</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#function-return-type</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#any-method</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#any-property</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#extends</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#pascal_case_class</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>annotated-parameter</key>
		<dict>
			<key>begin</key>
			<string>(?x)
  \b
  ([[:alpha:]_]\w*) \s* (:)
</string>
			<key>end</key>
			<string>(,)|(?=\))</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.gdscript</string>
					<key>match</key>
					<string>=(?!=)</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.function.language.gdscript</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.annotation.gdscript</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.parameters.gdscript</string>
				</dict>
			</dict>
		</dict>
		<key>any-method</key>
		<dict>
			<key>name</key>
			<string>support.function.any-method.gdscript</string>
			<key>match</key>
			<string>\b([A-Za-z_]\w*)\b(?=\s*(?:[(]))</string>
		</dict>
		<key>any-property</key>
		<dict>
			<key>name</key>
			<string>variable.other.property.gdscript</string>
			<key>match</key>
			<string>(?&lt;=[^.]\.)\b([A-Za-z_]\w*)\b(?![(])</string>
		</dict>
		<key>arithmetic_op</key>
		<dict>
			<key>name</key>
			<string>keyword.operator.arithmetic.gdscript</string>
			<key>match</key>
			<string>\+=|-=|\*=|/=|%=|&amp;=|\|=|\*|/|%|\+|-|&lt;&lt;|&gt;&gt;|&amp;|\||\^|~</string>
		</dict>
		<key>assignment_op</key>
		<dict>
			<key>name</key>
			<string>keyword.operator.assignment.gdscript</string>
			<key>match</key>
			<string>=</string>
		</dict>
		<key>base_expression</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#letter</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numbers</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#line-continuation</string>
				</dict>
			</array>
		</dict>
		<key>builtin_classes</key>
		<dict>
			<key>name</key>
			<string>support.class.library.gdscript</string>
			<key>match</key>
			<string>(?&lt;![^.]\.|:)\b(Vector2|Vector3|Color|Rect2|Array|Basis|Dictionary|Plane|Quat|RID|Rect3|Transform|Transform2D|AABB|String|Color|NodePath|RID|Object|Dictionary|Array|PoolByteArray|PoolIntArray|PoolRealArray|PoolStringArray|PoolVector2Array|PoolVector3Array|PoolColorArray)\b</string>
		</dict>
		<key>builtin_func</key>
		<dict>
			<key>name</key>
			<string>support.function.builtin.gdscript</string>
			<key>match</key>
			<string>(?&lt;![^.]\.|:)\b(sin|cos|tan|sinh|cosh|tanh|asin|acos|atan|atan2|sqrt|fmod|fposmod|floor|ceil|round|abs|sign|pow|log|exp|is_nan|is_inf|ease|decimals|stepify|lerp|dectime|randomize|randi|randf|rand_range|seed|rand_seed|deg2rad|rad2deg|linear2db|db2linear|max|min|clamp|nearest_po2|weakref|funcref|convert|typeof|type_exists|char|str|print|printt|prints|printerr|printraw|var2str|str2var|var2bytes|bytes2var|range|load|inst2dict|dict2inst|hash|Color8|print_stack|instance_from_id|preload|yield|assert)\b(?=(\()([^)]*)(\)))</string>
		</dict>
		<key>builtin_get_node_shorthand</key>
		<dict>
			<key>name</key>
			<string>support.function.builtin.shorthand.gdscript</string>
			<key>match</key>
			<string>\$((\&quot;(\.\.\/)+|\&quot;\/|\&quot;[0-9]+|\&quot;)([0-9A-Za-z\_]+\/)*[A-Za-z0-9\_]+\&quot;|[A-Za-z\_]+(\/[A-Za-z\_]+)*)</string>
		</dict>
		<key>class_def</key>
		<dict>
			<key>match</key>
			<string>(?&lt;=^class)\s+([a-zA-Z_]\w*)\s*(?=:)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.class.gdscript</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>class.other.gdscript</string>
				</dict>
			</dict>
		</dict>
		<key>class_enum</key>
		<dict>
			<key>match</key>
			<string>\b([A-Z][a-zA-Z_0-9]*)\.([A-Z_0-9]+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.class.gdscript</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language.gdscript</string>
				</dict>
			</dict>
		</dict>
		<key>class_is</key>
		<dict>
			<key>match</key>
			<string>\s+(is)\s+([a-zA-Z_][a-zA-Z_0-9]*)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.is.gdscript</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.class.gdscript</string>
				</dict>
			</dict>
		</dict>
		<key>class_name</key>
		<dict>
			<key>match</key>
			<string>(?&lt;=class_name)\s+([a-zA-Z_][a-zA-Z_0-9]*(\.([a-zA-Z_][a-zA-Z_0-9]*))?)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.class.gdscript</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>class.other.gdscript</string>
				</dict>
			</dict>
		</dict>
		<key>class_new</key>
		<dict>
			<key>match</key>
			<string>\b([a-zA-Z_][a-zA-Z_0-9]*).(new)\(</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.class.gdscript</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.new.gdscript</string>
				</dict>
			</dict>
		</dict>
		<key>comment</key>
		<dict>
			<key>name</key>
			<string>comment.line.number-sign.gdscript</string>
			<key>match</key>
			<string>(#).*$\n?</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.number-sign.gdscript</string>
				</dict>
			</dict>
		</dict>
		<key>compare_op</key>
		<dict>
			<key>name</key>
			<string>keyword.operator.comparison.gdscript</string>
			<key>match</key>
			<string>&lt;=|&gt;=|==|&lt;|&gt;|!=</string>
		</dict>
		<key>const_def</key>
		<dict>
			<key>match</key>
			<string>\b(?i:(const))\s+([a-zA-Z_][a-zA-Z_0-9]*)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.const.gdscript</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language.gdscript</string>
				</dict>
			</dict>
		</dict>
		<key>const_vars</key>
		<dict>
			<key>name</key>
			<string>constant.language.gdscript</string>
			<key>match</key>
			<string>\b([A-Z_0-9]+)\b</string>
		</dict>
		<key>extends</key>
		<dict>
			<key>name</key>
			<string>entity.other.inherited-class.gdscript</string>
			<key>match</key>
			<string>(?&lt;=extends)\s+[a-zA-Z_][a-zA-Z_0-9]*(\.([a-zA-Z_][a-zA-Z_0-9]*))?</string>
		</dict>
		<key>function-declaration</key>
		<dict>
			<key>name</key>
			<string>meta.function.gdscript</string>
			<key>begin</key>
			<string>(?x)
  \s*
  (?:\b(static) \s+)? \b(func|signal)\s+
    (?=
      [[:alpha:]_][[:word:]]* \s* \(
    )
</string>
			<key>end</key>
			<string>(:|(?=[#&apos;&quot;\n]))</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#function-def-name</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#parameters</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#line-continuation</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#return-annotation</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.static.gdscript</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.gdscript</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.function.begin.gdscript</string>
				</dict>
			</dict>
		</dict>
		<key>function-def-name</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>entity.name.function.gdscript</string>
					<key>match</key>
					<string>(?x)
  \b ([[:alpha:]_]\w*) \b
</string>
				</dict>
			</array>
		</dict>
		<key>function-return-type</key>
		<dict>
			<key>match</key>
			<string>\)\s*\-\&gt;\s*([a-zA-Z_][a-zA-Z_0-9]*)\s*\:</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.class.gdscript</string>
				</dict>
			</dict>
		</dict>
		<key>keywords</key>
		<dict>
			<key>name</key>
			<string>keyword.language.gdscript</string>
			<key>match</key>
			<string>\b(?i:if|elif|else|for|while|break|continue|pass|return|match|func|class|class_name|extends|is|in|onready|tool|static|export|setget|const|var|as|void|enum|preload|assert|yield|signal|breakpoint|rpc|sync|remote|master|puppet|slave|remotesync|mastersync|puppetsync|in)\b</string>
		</dict>
		<key>letter</key>
		<dict>
			<key>name</key>
			<string>constant.language.gdscript</string>
			<key>match</key>
			<string>\b(?i:true|false|null)\b</string>
		</dict>
		<key>line-continuation</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(\\)\s*(\S.*$\n?)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.continuation.line.gdscript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.line.continuation.gdscript</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\\)\s*$\n?</string>
					<key>end</key>
					<string>(?x)
  (?=^\s*$)
  |
  (?! (\s* [rR]? (\&apos;\&apos;\&apos;|\&quot;\&quot;\&quot;|\&apos;|\&quot;))
      |
      (\G $)  (?# &apos;\G&apos; is necessary for ST)
  )
</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#base_expression</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.continuation.line.gdscript</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>logic_op</key>
		<dict>
			<key>name</key>
			<string>keyword.operator.logical.gdscript</string>
			<key>match</key>
			<string>\b(and|or|not)\b</string>
		</dict>
		<key>loose-default</key>
		<dict>
			<key>begin</key>
			<string>(=)</string>
			<key>end</key>
			<string>(,)|(?=\))</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#base_expression</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.gdscript</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.parameters.gdscript</string>
				</dict>
			</dict>
		</dict>
		<key>numbers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.numeric.integer.hexadecimal.gdscript</string>
					<key>match</key>
					<string>\b(?i:0x[[:xdigit:]]*)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.float.gdscript</string>
					<key>match</key>
					<string>\b(?i:(\d+\.\d*(e[\-\+]?\d+)?))\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.float.gdscript</string>
					<key>match</key>
					<string>\b(?i:(\.\d+(e[\-\+]?\d+)?))\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.float.gdscript</string>
					<key>match</key>
					<string>\b(?i:(\d+e[\-\+]?\d+))\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.integer.gdscript</string>
					<key>match</key>
					<string>\b\d+\b</string>
				</dict>
			</array>
		</dict>
		<key>parameter-special</key>
		<dict>
			<key>match</key>
			<string>(?x)
  \b ((self)|(cls)) \b \s*(?:(,)|(?=\)))
</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.function.language.gdscript</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.function.language.special.self.gdscript</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.function.language.special.cls.gdscript</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.parameters.gdscript</string>
				</dict>
			</dict>
		</dict>
		<key>parameters</key>
		<dict>
			<key>name</key>
			<string>meta.function.parameters.gdscript</string>
			<key>begin</key>
			<string>(\()</string>
			<key>end</key>
			<string>(\))</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.operator.unpacking.parameter.gdscript</string>
					<key>match</key>
					<string>(\*\*|\*)</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#parameter-special</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?x)
  ([[:alpha:]_]\w*)
    \s* (?: (,) | (?=[)#\n=]))
</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.function.language.gdscript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.parameters.gdscript</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#loose-default</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#annotated-parameter</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.gdscript</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.end.gdscript</string>
				</dict>
			</dict>
		</dict>
		<key>pascal_case_class</key>
		<dict>
			<key>match</key>
			<string>\b([A-Z][a-zA-Z_0-9]*)\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.class.gdscript</string>
				</dict>
			</dict>
		</dict>
		<key>self</key>
		<dict>
			<key>name</key>
			<string>variable.language.gdscript</string>
			<key>match</key>
			<string>\bself\b</string>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>string.quoted.double.gdscript</string>
					<key>begin</key>
					<string>&quot;</string>
					<key>end</key>
					<string>&quot;</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>constant.character.escape.untitled</string>
							<key>match</key>
							<string>\\.</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>name</key>
					<string>string.quoted.single.gdscript</string>
					<key>begin</key>
					<string>&apos;</string>
					<key>end</key>
					<string>&apos;</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>constant.character.escape.untitled</string>
							<key>match</key>
							<string>\\.</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>name</key>
					<string>string.nodepath.gdscript</string>
					<key>begin</key>
					<string>@&quot;</string>
					<key>end</key>
					<string>&quot;</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>constant.character.escape.untitled</string>
							<key>match</key>
							<string>\.</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>type_declear</key>
		<dict>
			<key>match</key>
			<string>\:\s*([a-zA-Z_][a-zA-Z_0-9]*)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.class.gdscript</string>
				</dict>
			</dict>
		</dict>
		<key>var_def</key>
		<dict>
			<key>match</key>
			<string>\b(?i:(var))\s+([a-zA-Z_][a-zA-Z_0-9]*)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.var.gdscript</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.language.gdscript</string>
				</dict>
			</dict>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>gd</string>
	</array>
</dict>
</plist>
