<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Gemfile.lock</string>
	<key>scopeName</key>
	<string>source.gemfile-lock</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#dependencies-sections</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#other-sections</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>dependencies-sections</key>
		<dict>
			<key>name</key>
			<string>section.gemfile-lock</string>
			<key>begin</key>
			<string>^(GEM|PATH|GIT|DEPENDENCIES)$</string>
			<key>end</key>
			<string>^$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#entries</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dependency-specs</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.section.gemfile-lock</string>
				</dict>
			</dict>
		</dict>
		<key>dependency-specs</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>dependency.gemfile-lock</string>
					<key>begin</key>
					<string>^ {2,6}([^ !]+)\s*(\()?</string>
					<key>end</key>
					<string>($|\))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#versions</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.package.gemfile-lock</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.parenthesis.begin.gemfile-lock</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.parenthesis.end.gemfile-lock</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>entries</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>entry.gemfile-lock</string>
					<key>match</key>
					<string>^ +([a-z]+:) ?(.*)$</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.property-name.gemfile-lock</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.gemfile-lock</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>other-sections</key>
		<dict>
			<key>name</key>
			<string>section.gemfile-lock</string>
			<key>begin</key>
			<string>^[A-Z ]+$</string>
			<key>end</key>
			<string>^$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>^\s+(.*)$</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.gemfile-lock</string>
						</dict>
					</dict>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.section.gemfile-lock</string>
				</dict>
			</dict>
		</dict>
		<key>versions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>version.gemfile-lock</string>
					<key>match</key>
					<string>(?:(&lt;=|&gt;=|=|~&gt;|&lt;|&gt;|!=) )?([0-9A-Za-z_\-\.]+)(,)?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.comparison.gemfile-lock</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.gemfile-lock</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.gemfile-lock</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>Gemfile.lock</string>
	</array>
</dict>
</plist>
