<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Genero Forms</string>
	<key>scopeName</key>
	<string>source.genero-forms</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#Comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#GridLayout</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#Keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#Layout</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.type.per</string>
			<key>match</key>
			<string>\b(DECIMAL|CHAR|DATE|INTEGER)\b</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#StringDoubleQuote</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#StringSingleQuote</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#FormAttributes</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#ComparisonOperators</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#Groups</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#Tables</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.amp.per</string>
			<key>match</key>
			<string>(&amp;)</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>Comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>comment.line.number-sign.per</string>
					<key>match</key>
					<string>#.*</string>
				</dict>
				<dict>
					<key>name</key>
					<string>comment.line.double-dash.per</string>
					<key>match</key>
					<string>--.*</string>
				</dict>
			</array>
		</dict>
		<key>ComparisonOperators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.operator.per</string>
					<key>match</key>
					<string>(\=|\&lt;|\&gt;|\!)</string>
				</dict>
			</array>
		</dict>
		<key>EscapeCharacters</key>
		<dict>
			<key>name</key>
			<string>constant.character.escape.4gl</string>
			<key>match</key>
			<string>\\.{1}</string>
		</dict>
		<key>FormAttributes</key>
		<dict>
			<key>match</key>
			<string>(?i)\s*\b(AGGREGATE|BUTTON|BUTTONEDIT|CANVAS|CHECKBOX|COMBOBOX|DATEEDIT|EDIT|FIELD|IMAGE|LABEL|PROGRESSBAR|RADIOGROUP|SCROLLGRID|SLIDER|SPINEDIT|TABLE|TEXTEDIT|TIMEEDIT|TREE|WEBCOMPONENT|SCREEN RECORD|PHANTOM)\b\s+(\w+)\s*(?:(\:|\=)|(?:\())</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.class.per</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.per</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.per</string>
				</dict>
			</dict>
		</dict>
		<key>FormFields</key>
		<dict>
			<key>name</key>
			<string>variable.parameter.per</string>
			<key>begin</key>
			<string>\[</string>
			<key>end</key>
			<string>\]</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#StringDoubleQuote</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#StringSingleQuote</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.constant.field.divide.per</string>
					<key>match</key>
					<string>(\||:)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>variable.parameter.form.grid.per</string>
					<key>match</key>
					<string>(?i)\b([a-z0-9\#\/\&apos;\_]+)\b</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.form.grid.field.brackes.per</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.form.grid.field.brackets.per</string>
				</dict>
			</dict>
		</dict>
		<key>FormatStrings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>support.type.format.per</string>
					<key>match</key>
					<string>[\#\&lt;\&gt;\*\-\+]{2,}</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.lanauge.format.per</string>
					<key>match</key>
					<string>\&amp;</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.per</string>
					<key>match</key>
					<string>\,</string>
				</dict>
			</array>
		</dict>
		<key>GridLayout</key>
		<dict>
			<key>name</key>
			<string>meta.form.grid.per</string>
			<key>begin</key>
			<string>\{</string>
			<key>end</key>
			<string>\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#FormFields</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#Tags</string>
				</dict>
			</array>
		</dict>
		<key>Groups</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)\b(GROUP)\b\s+(\w+)\s*(\:)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.class.per</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.per</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.per</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>Keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.per</string>
					<key>match</key>
					<string>(?i)\b(DATABASE|SCREEN SIZE|BY|END|ATTRIBUTES|TYPE|INSTRUCTIONS|DELIMITERS|COMMENTS)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.per</string>
					<key>match</key>
					<string>(?i)\b(ACCELERATOR|ACCELERATOR2|ACCELERATOR3|ACCELERATOR4|ACTION|AGGREGATETEXT|AGGREGATETYPE|AUTOSCALE|AUTONEXT|BUTTONTEXTHIDDEN|CENTURY|CLASS|COLOR|COLOR WHERE|CONFIG|CONTEXTMENU|COMMENT|COMPONENTTYPE|DEFAULT|DEFAULTVIEW|DISPLAY LIKE|DOUBLECLICK|DOWNSHIFT|EXPANDEDCOLUMN|FONTPITCH|FORMAT|GRIDCHILDRENINPARENT|HIDDEN|HEIGHT|IDCOLUMN|IMAGE|IMAGECOLUMN|IMAGECOLLAPSED|IMAGEEXPANDED|IMAGELEAF|INCLUDE|INITIALIZER|INVISIBLE|ISNODECOLUMN|ITEMS|JUSTIFY|KEY|MINHEIGHT|MINWIDTH|NOENTRY|NOT NULL|NOTEDITABLE|OPTIONS|ORIENTATION|PARENTIDCOLUMN|PICTURE|PROGRAM|PROPERTIES|QUERYEDITABLE|REQUIRED|REVERSE|SAMPLE|SCROLL|SCROLLBARS|SIZEPOLICY|SPACING|SPLITTER|STEP|STRETCH|STYLE|TABINDEX|TAG|TEXT|TITLE|UNSORTABLE|UNSORTABLECOLUMNS|UNSIZABLE|UNSIZABLECOLUMNS|UNHIDABLE|UNHIDABLECOLUMNS|UNMOVABLE|UNMOVABLECOLUMNS|UPSHIFT|VALIDATE|VALIDATE LIKE|VALUEMIN|VALUEMAX|VALUECHECKED|VALUEUNCHECKED|VERIFY|VERSION|WANTFIXEDPAGESIZE|WANTNORETURNS|WANTTABS|WIDGET|WIDTH|WINDOWSTYLE|WORDWRAP)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.per</string>
					<key>match</key>
					<string>(?i)\b(FORMONLY|FIXED)\b</string>
				</dict>
			</array>
		</dict>
		<key>Layout</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.layout.per</string>
					<key>match</key>
					<string>(?i)\b(GRID|TABLE|HBOX|VBOX|LAYOUT|FORM)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.layout.per</string>
					<key>match</key>
					<string>(?i)\b(TABLE|FOLDER)\b</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)(GROUP|TABLE|PAGE)\s*(\w*)\s*\(</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.layout.per</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.type.class.per</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>StringDoubleQuote</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>string.quoted.double.content.per</string>
					<key>begin</key>
					<string>&quot;</string>
					<key>end</key>
					<string>&quot;</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#EscapeCharacters</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#FormatStrings</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.per</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.per</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>StringSingleQuote</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>string.quoted.single.content.per</string>
					<key>begin</key>
					<string>&apos;</string>
					<key>end</key>
					<string>&apos;</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#EscapeCharacters</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#FormatStrings</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>string.quoted.single.per</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>string.quoted.single.per</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>Tables</key>
		<dict>
			<key>name</key>
			<string>support.class.table.per</string>
			<key>begin</key>
			<string>(?i)\bTABLES\b</string>
			<key>end</key>
			<string>(?i)\bEND\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.per</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.per</string>
				</dict>
			</dict>
		</dict>
		<key>Tags</key>
		<dict>
			<key>begin</key>
			<string>\&lt;</string>
			<key>end</key>
			<string>\&gt;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)\b(G|GROUP|T|TABLE|TREE|S|SCROLLGRID)\b\s+(\w+)</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>support.function.per</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.variable.per</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>include</key>
					<string>#StringDoubleQuote</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#StringSingleQuote</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.form.grid.group.brackes.per</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.form.grid.group.brackes.per</string>
				</dict>
			</dict>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>per</string>
	</array>
</dict>
</plist>
