<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Gerber Image</string>
	<key>scopeName</key>
	<string>source.gerber</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>contentName</key>
			<string>comment.block.gerber</string>
			<key>begin</key>
			<string>G04</string>
			<key>end</key>
			<string>(?=\*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.begin-comment.gerber</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.command.block.gerber</string>
			<key>begin</key>
			<string>%</string>
			<key>end</key>
			<string>%</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#extendedCommands</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.begin.extended.command.gerber</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.end.extended.command.gerber</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>punctuation.separator.list.comma.gerber</string>
			<key>match</key>
			<string>,</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.operator.terminator.gerber</string>
			<key>match</key>
			<string>\*</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.control.eof.gerber</string>
			<key>match</key>
			<string>M02</string>
		</dict>
		<dict>
			<key>name</key>
			<string>entity.name.function.${1:/downcase}.command.gerber</string>
			<key>match</key>
			<string>(?x)
(FS|MO|AD|AM|AB|D[0-9]+|G01|G02|G03|G74|G75|LP|LM|LR|LS|G36|G37
|SR|G04|TF|TA|TO|TD|M02|G54|G55|G70|G71|G90|G91|M00|M01|IP|AS
|IR|MI|OF|SF|IN|LN)</string>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.${1:/downcase}.ordinate.gerber</string>
			<key>match</key>
			<string>(X|Y)([-+]?[0-9]+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.name.var.${1:/downcase}.gerber</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.decimal.gerber</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.numeric.decimal.gerber</string>
			<key>match</key>
			<string>[-+]?(?:[0-9]*\.[0-9]+|[0-9]+)</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>extendedCommands</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\G(AM)([A-Za-z_.0-9$]+)</string>
					<key>end</key>
					<string>(?=%)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#macroInnards</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.function.macro.gerber</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.macro.gerber</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.aperture.definition.gerber</string>
					<key>begin</key>
					<string>\G(AD)(D[0-9]+)([^,%*\s]+)</string>
					<key>end</key>
					<string>(?=%)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>\G(?=,)</string>
							<key>end</key>
							<string>(?=%)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>match</key>
									<string>(X)?([^*%X]+)</string>
									<key>captures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>punctuation.delimiter.modifiers.list.gerber</string>
										</dict>
										<key>2</key>
										<dict>
											<key>patterns</key>
											<array>
												<dict>
													<key>include</key>
													<string>$self</string>
												</dict>
											</array>
										</dict>
									</dict>
								</dict>
								<dict>
									<key>include</key>
									<string>$self</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.function.aperture.gerber</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.d-code.gerber</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.aperture-name.gerber</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.attribute.gerber</string>
					<key>begin</key>
					<string>\G(TF|TA|TO)([^,*%]+)(,)</string>
					<key>end</key>
					<string>(?=\*|%)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>punctuation.separator.list.comma.gerber</string>
							<key>match</key>
							<string>,</string>
						</dict>
						<dict>
							<key>name</key>
							<string>string.unquoted.attribute.gerber</string>
							<key>match</key>
							<string>[^,%*]</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.attribute.gerber</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.gerber</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>\G(TD)([^,*%]+)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.delete.attribute.gerber</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.gerber</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>\G(FS)([LT][AI])</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.format-spec.gerber</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.language.option.modes.gerber</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>\G(OF)(A)([-+]?[0-9]+)(B)([-+]?[0-9]+)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.offset.gerber</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.name.var.offset.a-axis.gerber</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.decimal.gerber</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>storage.name.var.offset.b-axis.gerber</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.decimal.gerber</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>\G(MO)(IN|MM)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.unit-mode.gerber</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.language.unit-type.gerber</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>\G(IP)(POS|NEG)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.image-polarity.gerber</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.language.image-polarity.gerber</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>\G(LP)(C|D)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.load-polarity.gerber</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.language.polarity-type.gerber</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>\G(LM)(N|XY|X|Y)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.load-mirroring.gerber</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.language.mirror-type.gerber</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>contentName</key>
					<string>variable.parameter.gerber</string>
					<key>begin</key>
					<string>\G(LN)</string>
					<key>end</key>
					<string>(?=\*|%)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.load-name.gerber</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>macroInnards</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>comment.line.primitive.gerber</string>
					<key>match</key>
					<string>^\s*(0)(\s+([^*%]+)(?=\*|%|$))</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.primitive.gerber</string>
						</dict>
						<key>2</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#unicodeEscape</string>
								</dict>
							</array>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.gerber</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.logical.arithmetic.gerber</string>
					<key>match</key>
					<string>\+|-|x|X|/</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\()|(\))</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.equation.begin.gerber</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.equation.end.gerber</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>variable.positional.parameter.gerber</string>
					<key>match</key>
					<string>(\$)[1-9][0-9]*</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.gerber</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.gerber</string>
					<key>match</key>
					<string>=</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>unicodeEscape</key>
		<dict>
			<key>name</key>
			<string>constant.character.escape.unicode.gerber</string>
			<key>match</key>
			<string>(\\)u[0-9A-Fa-f]{4}</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.escape.backslash.gerber</string>
				</dict>
			</dict>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>gbr</string>
		<string>cmp</string>
		<string>gbl</string>
		<string>gbo</string>
		<string>gbp</string>
		<string>gbs</string>
		<string>gko</string>
		<string>gml</string>
		<string>gpb</string>
		<string>gpt</string>
		<string>gtl</string>
		<string>gto</string>
		<string>gtp</string>
		<string>gts</string>
		<string>ncl</string>
		<string>sol</string>
	</array>
</dict>
</plist>
