<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>.gitattributes</string>
	<key>scopeName</key>
	<string>source.gitattributes</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#main</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>attribute</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.attribute.gitattributes</string>
					<key>match</key>
					<string>([-!](?=\S))?+([^-A-Za-z0-9_.\s]\S*)|([-!])(?=\s|$)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#attributePrefix</string>
								</dict>
							</array>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.syntax.bad-name.gitattributes</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.syntax.bad-name.gitattributes</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.attribute.gitattributes</string>
					<key>match</key>
					<string>(-|!)?([^\s=]+)(?:(=)([^\s]*))?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#attributePrefix</string>
								</dict>
							</array>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.attribute.gitattributes</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.assignment.equals-sign.gitattributes</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.language.other.gitattributes</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>attributePrefix</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.operator.logical.not.negation.gitattributes</string>
					<key>match</key>
					<string>-</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.unset.delete.gitattributes</string>
					<key>match</key>
					<string>!</string>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>name</key>
			<string>comment.line.number-sign.gitattributes</string>
			<key>begin</key>
			<string>#</string>
			<key>end</key>
			<string>$</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.gitattributes</string>
				</dict>
			</dict>
		</dict>
		<key>macro</key>
		<dict>
			<key>name</key>
			<string>meta.definition.gitattributes</string>
			<key>contentName</key>
			<string>meta.attribute-list.gitattributes</string>
			<key>begin</key>
			<string>(?:^|\G)(\[)(attr)(\])([-\w.]+)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#attribute</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>etc#bracket</string>
						</dict>
					</array>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.attribute.gitattributes</string>
				</dict>
				<key>3</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>etc#bracket</string>
						</dict>
					</array>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.attribute.gitattributes</string>
				</dict>
			</dict>
		</dict>
		<key>main</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#macro</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#pattern</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.gitignore#escape</string>
				</dict>
			</array>
		</dict>
		<key>pattern</key>
		<dict>
			<key>name</key>
			<string>meta.pattern.gitattributes</string>
			<key>begin</key>
			<string>(?=[^#\s])</string>
			<key>end</key>
			<string>$|(?=#)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.gitignore#patternInnards</string>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.attribute-list.gitattributes</string>
					<key>begin</key>
					<string>\s</string>
					<key>end</key>
					<string>(?=$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#attribute</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>.gitattributes</string>
	</array>
</dict>
</plist>
