<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>.gitconfig</string>
	<key>scopeName</key>
	<string>source.gitconfig</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#main</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>alias</key>
		<dict>
			<key>name</key>
			<string>meta.alias.gitconfig</string>
			<key>begin</key>
			<string>(?:^|(?&lt;=\])\G)\s*([A-Za-z][-A-Za-z]*)\s*(=)</string>
			<key>end</key>
			<string>(?&lt;!\\)$|(?=#|;)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#aliasInnards</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.assignment.gitconfig</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.key-value.gitconfig</string>
				</dict>
			</dict>
		</dict>
		<key>aliasInnards</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.quoted.shell.command.gitconfig</string>
					<key>begin</key>
					<string>\G\s*(?:(&quot;)(!)|(!)(&quot;))\s*+</string>
					<key>end</key>
					<string>(?&lt;!\\)(?:(&quot;)|(?=$))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.shell</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.gitconfig</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.shell-script.gitconfig</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.shell-script.gitconfig</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.gitconfig</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.gitconfig</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.unquoted.shell.command.gitconfig</string>
					<key>begin</key>
					<string>\G\s*(!)</string>
					<key>end</key>
					<string>(?&lt;!\\)(?=$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.shell</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.shell-script.gitconfig</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.git.subcommands.gitconfig</string>
					<key>contentName</key>
					<string>string.unquoted.source.gitconfig</string>
					<key>begin</key>
					<string>\G\s*([^\s&quot;#;!]+)</string>
					<key>end</key>
					<string>(?&lt;!\\)(?=$|#|;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escapes</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.source.gitconfig</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>aliasSection</key>
		<dict>
			<key>name</key>
			<string>meta.aliases.section.gitconfig</string>
			<key>begin</key>
			<string>(?i)(?:^|\G)\s*(\[)\s*(alias)\s*(\])</string>
			<key>end</key>
			<string>(?!\G)(?=^\s*\[)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#alias</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variables</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.section.header.gitconfig</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.bracket.square.begin.gitconfig</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.section.name.gitconfig</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.bracket.square.end.gitconfig</string>
				</dict>
			</dict>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>comment.line.number-sign.gitconfig</string>
					<key>begin</key>
					<string>#</string>
					<key>end</key>
					<string>$</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.gitconfig</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>comment.line.semicolon.gitconfig</string>
					<key>begin</key>
					<string>;</string>
					<key>end</key>
					<string>$</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.gitconfig</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>escapedNewline</key>
		<dict>
			<key>name</key>
			<string>constant.character.escape.newline.gitconfig</string>
			<key>match</key>
			<string>(\\)$\s*</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.escape.backslash.gitconfig</string>
				</dict>
			</dict>
		</dict>
		<key>escapes</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.character.escape.backslash.gitconfig</string>
					<key>match</key>
					<string>(\\)\\</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.escape.backslash.gitconfig</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.escape.quote.gitconfig</string>
					<key>match</key>
					<string>(\\)&quot;</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.escape.backslash.gitconfig</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.escape.newline.gitconfig</string>
					<key>match</key>
					<string>(\\)n</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.escape.backslash.gitconfig</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.escape.tab.gitconfig</string>
					<key>match</key>
					<string>(\\)t</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.escape.backslash.gitconfig</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.escape.backspace.gitconfig</string>
					<key>match</key>
					<string>(\\)b</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.escape.backslash.gitconfig</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>include</key>
					<string>#escapedNewline</string>
				</dict>
				<dict>
					<key>name</key>
					<string>invalid.illegal.syntax.escape.gitconfig</string>
					<key>match</key>
					<string>\\.</string>
				</dict>
			</array>
		</dict>
		<key>includeInnards</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.operator.tilde.gitconfig</string>
					<key>match</key>
					<string>(?:^|\G)~(?=/)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.config-path.gitconfig</string>
					<key>match</key>
					<string>(?:^|\G)\.(?=/)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.glob.wildcard.globstar.gitconfig</string>
					<key>match</key>
					<string>\*\*</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.glob.wildcard.gitconfig</string>
					<key>match</key>
					<string>[*?]</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.directory.separator.meta.gitconfig</string>
					<key>match</key>
					<string>/</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#escapes</string>
				</dict>
			</array>
		</dict>
		<key>includePath</key>
		<dict>
			<key>name</key>
			<string>meta.included-file.gitconfig</string>
			<key>begin</key>
			<string>(?:^|(?&lt;=\])\G)\s*(path)\s*(=)[ \t]*</string>
			<key>end</key>
			<string>(?=\s*(?:(?&lt;!\\)$|#|;))</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>string.quoted.double.pathspec.gitconfig</string>
					<key>contentName</key>
					<string>string.other.link.pathspec.gitconfig</string>
					<key>begin</key>
					<string>\G\s*&quot;</string>
					<key>end</key>
					<string>&quot;|(?&lt;!\\)(?=\s*$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#includeInnards</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.gitconfig</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.gitconfig</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>([^&quot;\s;#][^;#]*?)(?&lt;=\S)(?=\s*(?:$|;|#))</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.other.link.pathspec.gitconfig</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#includeInnards</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variables</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.assignment.gitconfig</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.key-value.gitconfig</string>
				</dict>
			</dict>
		</dict>
		<key>includeSection</key>
		<dict>
			<key>name</key>
			<string>meta.include.section.gitconfig</string>
			<key>begin</key>
			<string>(?ix)
(?:^|\G) \s*
(\[) #1
\s*
(include(?:If)?) #2
(?:
	\s*
	(&quot;) #3
	(   #4
		(?: [^\\&quot;]
		|   \\.
		)*+
	)
	(&quot;) #5
)?+
\s* (\]) #6</string>
			<key>end</key>
			<string>(?!\G)(?=^\s*\[)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#includePath</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variables</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.section.header.gitconfig</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.bracket.square.begin.gitconfig</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.directive.${2:/downcase}.gitconfig</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.condition.begin.gitconfig</string>
				</dict>
				<key>4</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>meta.condition.match-directory.gitconfig</string>
							<key>contentName</key>
							<string>string.other.link.gitconfig</string>
							<key>begin</key>
							<string>(gitdir)((/)i)?(:)</string>
							<key>end</key>
							<string>(?=\s*(?:$|&quot;))</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#sectionEscapes</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#includeInnards</string>
								</dict>
							</array>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.name.condition-type.gitconfig</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>storage.modifier.ignore-case.gitconfig</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>punctuation.separator.modifier.slash.gitconfig</string>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>punctuation.separator.key-value.gitconfig</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>name</key>
							<string>meta.condition.match-worktree.gitconfig</string>
							<key>contentName</key>
							<string>string.other.file.name.gitconfig</string>
							<key>begin</key>
							<string>(onbranch)(:)</string>
							<key>end</key>
							<string>(?=\s*(?:$|&quot;))</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#sectionEscapes</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#includeInnards</string>
								</dict>
							</array>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.name.condition-type.gitconfig</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.separator.key-value.gitconfig</string>
								</dict>
							</dict>
						</dict>
					</array>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.condition.end.gitconfig</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.bracket.square.end.gitconfig</string>
				</dict>
			</dict>
		</dict>
		<key>main</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#includeSection</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#aliasSection</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#urlSection</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#section</string>
				</dict>
			</array>
		</dict>
		<key>section</key>
		<dict>
			<key>name</key>
			<string>meta.section.gitconfig</string>
			<key>begin</key>
			<string>(?x)
(?:^|\G) \s*
(?:
	(\[)\s*(\]) #1, #2
	|
	(\[) #3
	\s*
	(?:
		([-.A-Za-z0-9]+?) #4
		(?:
			(\.)           #5
			([-A-Za-z0-9]+) #6
		)?
	)
	(?:
		\s*
		(&quot;) #7
		(   #8
			(?: [^\\&quot;]
			|   \\.
			)*+
		)
		(&quot;) #9
	)?+
	\s* (\]) #10
)</string>
			<key>end</key>
			<string>(?!\G)(?=^\s*\[)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variables</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.section.header.gitconfig</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.bracket.square.begin.gitconfig</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.bracket.square.end.gitconfig</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.bracket.square.begin.gitconfig</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.section.name.gitconfig</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.delimiter.separator.meta.dot.period.gitconfig</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>entity.subsection.name.deprecated-syntax.gitconfig</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.subsection.begin.gitconfig</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>entity.subsection.name.gitconfig</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#sectionEscapes</string>
						</dict>
					</array>
				</dict>
				<key>9</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.subsection.end.gitconfig</string>
				</dict>
				<key>10</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.bracket.square.end.gitconfig</string>
				</dict>
			</dict>
		</dict>
		<key>sectionEscapes</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.character.escape.backslash.gitconfig</string>
					<key>match</key>
					<string>(\\)[\\&quot;]</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.escape.backslash.gitconfig</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.escape.unknown.gitconfig</string>
					<key>match</key>
					<string>\\(?=[^\\&quot;])</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.escape.backslash.ignored.gitconfig</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>urlInnards</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>string.other.link.gitconfig</string>
					<key>begin</key>
					<string>&quot;</string>
					<key>end</key>
					<string>&quot;|(?=\s*$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escapes</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>string.quoted.string.begin.gitconfig</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>string.quoted.string.end.gitconfig</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>string.other.link.gitconfig</string>
					<key>match</key>
					<string>(?:[^\s&quot;;#\\]|\\.)+</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#escapes</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>urlSection</key>
		<dict>
			<key>name</key>
			<string>meta.url.section.gitconfig</string>
			<key>begin</key>
			<string>(?ix)
(?:^|\G) \s*
(\[) #1
\s*
(url|https?|core.(?:git)?proxy) #2
(?:
	\s*
	(&quot;) #3
	(   #4
		(?: [^\\&quot;]
		|   \\.
		)*+
	)
	(&quot;) #5
)?+
\s* (\]) #6</string>
			<key>end</key>
			<string>(?!\G)(?=^\s*\[)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variables</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.section.header.gitconfig</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.bracket.square.begin.gitconfig</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.section.name.gitconfig</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.subsection.begin.gitconfig</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.other.link.gitconfig</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#sectionEscapes</string>
						</dict>
					</array>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.subsection.end.gitconfig</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.bracket.square.end.gitconfig</string>
				</dict>
			</dict>
		</dict>
		<key>variableInnards</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\G\s*(=)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.assignment.key-value.gitconfig</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.logical.boolean.$1.gitconfig</string>
					<key>match</key>
					<string>(?i)\b(true|false|on|off|1|0|yes|no)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.decimal.integer.int.gitconfig</string>
					<key>match</key>
					<string>[-+]?[0-9]+(?=$|[\s#;])</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.decimal.float.gitconfig</string>
					<key>match</key>
					<string>[-+]?(?:[0-9]+\.[0-9]*|\.[0-9]+)(?=$|\s#;)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>string.quoted.double.argument.gitconfig</string>
					<key>match</key>
					<string>(&quot;)((?:[^\\&quot;]|\\.)*?)(?&lt;!\\)(?=\s*$)</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.syntax.unclosed-string.gitconfig</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.gitconfig</string>
						</dict>
						<key>2</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#escapes</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>string.quoted.double.argument.gitconfig</string>
					<key>begin</key>
					<string>&quot;</string>
					<key>end</key>
					<string>&quot;|(?&lt;!\\)(?=\s*$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escapes</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.gitconfig</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.gitconfig</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>string.unquoted.argument.gitconfig</string>
					<key>match</key>
					<string>(?:[^\\\s&quot;;#]|\\.)+</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#escapes</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>include</key>
					<string>#escapedNewline</string>
				</dict>
			</array>
		</dict>
		<key>variables</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.variable-field.gitconfig</string>
					<key>begin</key>
					<string>(?i)\b(signingkey)(?=\s|$)</string>
					<key>end</key>
					<string>(?=\s*(?:$|#|;))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>constant.other.signing-key.hex.gitconfig</string>
							<key>match</key>
							<string>\w+</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#variableInnards</string>
						</dict>
					</array>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.assignment.gitconfig</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.assignment.key-value.gitconfig</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.variable-field.gitconfig</string>
					<key>begin</key>
					<string>(?i)\b(email|url)\s*(=)</string>
					<key>end</key>
					<string>(?=\s*(?:$|#|;))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#urlInnards</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.assignment.gitconfig</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.assignment.key-value.gitconfig</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.variable-field.gitconfig</string>
					<key>begin</key>
					<string>(?i)\b(textconv)\s*(=)</string>
					<key>end</key>
					<string>(?=\s*(?:$|#|;))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#aliasInnards</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.assignment.gitconfig</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.assignment.key-value.gitconfig</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.variable-field.gitconfig</string>
					<key>begin</key>
					<string>[A-Za-z][-A-Za-z]*</string>
					<key>end</key>
					<string>(?=\s*(?:$|#|;))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#variableInnards</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.assignment.gitconfig</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>gitconfig</string>
	</array>
</dict>
</plist>
