<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Gleam</string>
	<key>scopeName</key>
	<string>source.gleam</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constant</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#entity</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>binary_number</key>
		<dict>
			<key>name</key>
			<string>constant.numeric.binary.gleam</string>
			<key>match</key>
			<string>\b0b[0-1]+\b</string>
		</dict>
		<key>boolean</key>
		<dict>
			<key>name</key>
			<string>constant.language.boolean.gleam</string>
			<key>match</key>
			<string>\b(True|False)\b</string>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>comment.line.gleam</string>
					<key>match</key>
					<string>//.*</string>
				</dict>
			</array>
		</dict>
		<key>constant</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#binary_number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#octal_number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#hexadecimal_number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#decimal_number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
				<dict>
					<key>name</key>
					<string>entity.name.type.gleam</string>
					<key>match</key>
					<string>[[:upper:]][[:word:]]*</string>
				</dict>
			</array>
		</dict>
		<key>decimal_number</key>
		<dict>
			<key>name</key>
			<string>constant.numeric.decimal.gleam</string>
			<key>match</key>
			<string>\b[[:digit:]][[:digit:]_]*(\.[[:digit:]]*)?\b</string>
		</dict>
		<key>entity</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b([[:lower:]][[:word:]]*)([[:space:]]*)?\(</string>
					<key>end</key>
					<string>\)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.gleam</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>variable.parameter.gleam</string>
					<key>match</key>
					<string>\b([[:lower:]][[:word:]]*):\s</string>
				</dict>
				<dict>
					<key>name</key>
					<string>entity.name.namespace.gleam</string>
					<key>match</key>
					<string>\b([[:lower:]][[:word:]]*):</string>
				</dict>
			</array>
		</dict>
		<key>hexadecimal_number</key>
		<dict>
			<key>name</key>
			<string>constant.numeric.hexadecimal.gleam</string>
			<key>match</key>
			<string>\b0x[[:xdigit:]]+\b</string>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.control.gleam</string>
					<key>match</key>
					<string>\b(as|use|case|if|fn|import|let|assert|pub|type|opaque|const|todo|panic)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.arrow.gleam</string>
					<key>match</key>
					<string>(&lt;\-|\-&gt;)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.pipe.gleam</string>
					<key>match</key>
					<string>\|&gt;</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.splat.gleam</string>
					<key>match</key>
					<string>\.\.</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.comparison.float.gleam</string>
					<key>match</key>
					<string>(&lt;=\.|&gt;=\.|==\.|!=\.|&lt;\.|&gt;\.)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.comparison.int.gleam</string>
					<key>match</key>
					<string>(&lt;=|&gt;=|==|!=|&lt;|&gt;)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.logical.gleam</string>
					<key>match</key>
					<string>(&amp;&amp;|\|\|)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.string.gleam</string>
					<key>match</key>
					<string>&lt;&gt;</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.other.gleam</string>
					<key>match</key>
					<string>\|</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.arithmetic.float.gleam</string>
					<key>match</key>
					<string>(\+\.|\-\.|/\.|\*\.|%\.)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.arithmetic.int.gleam</string>
					<key>match</key>
					<string>(\+|\-|/|\*|%)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.gleam</string>
					<key>match</key>
					<string>=</string>
				</dict>
			</array>
		</dict>
		<key>octal_number</key>
		<dict>
			<key>name</key>
			<string>constant.numeric.octal.gleam</string>
			<key>match</key>
			<string>\b0o[0-7]+\b</string>
		</dict>
		<key>strings</key>
		<dict>
			<key>name</key>
			<string>string.quoted.double.gleam</string>
			<key>begin</key>
			<string>&quot;</string>
			<key>end</key>
			<string>&quot;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.character.escape.gleam</string>
					<key>match</key>
					<string>\\.</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>gleam</string>
	</array>
</dict>
</plist>
