<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>scopeName</key>
	<string>go.sum</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#checksum</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#semver</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#unquoted_string</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>checksum</key>
		<dict>
			<key>match</key>
			<string>h1:([^\s]+)=</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>string.unquoted.go.sum</string>
							<key>match</key>
							<string>[a-zA-Z\d+\/]{43}</string>
						</dict>
						<dict>
							<key>name</key>
							<string>invalid.illegal.unknown-hash.go.sum</string>
							<key>match</key>
							<string>.*</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>semver</key>
		<dict>
			<key>name</key>
			<string>constant.language.go.sum</string>
			<key>match</key>
			<string>v(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)(?:-[\da-z-]+(?:\.[\da-z-]+)*)?(?:\+[\da-z-]+(?:\.[\da-z-]+)*)?</string>
		</dict>
		<key>unquoted_string</key>
		<dict>
			<key>name</key>
			<string>string.unquoted.go.sum</string>
			<key>match</key>
			<string>[^\s]+</string>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>go.sum</string>
		<string>go.work.sum</string>
	</array>
</dict>
</plist>
