<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>scopeName</key>
	<string>source.gdresource</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#embedded_shader</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#embedded_gdscript</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#heading</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#key_value</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>name</key>
			<string>comment.line.gdresource</string>
			<key>match</key>
			<string>(;).*$\n?</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.gdresource</string>
				</dict>
			</dict>
		</dict>
		<key>data</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;!\w)(\{)\s*</string>
					<key>end</key>
					<string>\s*(\})(?!\w)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#key_value</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#data</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.table.inline.gdresource</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.table.inline.gdresource</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;!\w)(\[)\s*</string>
					<key>end</key>
					<string>\s*(\])(?!\w)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#data</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.array.gdresource</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.array.gdresource</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>string.quoted.triple.basic.block.gdresource</string>
					<key>begin</key>
					<string>&quot;&quot;&quot;</string>
					<key>end</key>
					<string>&quot;&quot;&quot;</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>constant.character.escape.gdresource</string>
							<key>match</key>
							<string>\\([btnfr&quot;\\\n/ ]|u[0-9A-Fa-f]{4}|U[0-9A-Fa-f]{8})</string>
						</dict>
						<dict>
							<key>name</key>
							<string>invalid.illegal.escape.gdresource</string>
							<key>match</key>
							<string>\\[^btnfr/&quot;\\\n]</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>name</key>
					<string>support.function.any-method.gdresource</string>
					<key>match</key>
					<string>&quot;res:\/\/[^&quot;\\]*(?:\\.[^&quot;\\]*)*&quot;</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.class.library.gdresource</string>
					<key>match</key>
					<string>(?&lt;=type=)&quot;[^&quot;\\]*(?:\\.[^&quot;\\]*)*&quot;</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.escape.gdresource</string>
					<key>match</key>
					<string>(?&lt;=NodePath\(|parent=|name=)&quot;[^&quot;\\]*(?:\\.[^&quot;\\]*)*&quot;</string>
				</dict>
				<dict>
					<key>name</key>
					<string>string.quoted.double.basic.line.gdresource</string>
					<key>match</key>
					<string>&quot;[^&quot;\\]*(?:\\.[^&quot;\\]*)*&quot;</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>constant.character.escape.gdresource</string>
							<key>match</key>
							<string>\\([btnfr&quot;\\\n/ ]|u[0-9A-Fa-f]{4}|U[0-9A-Fa-f]{8})</string>
						</dict>
						<dict>
							<key>name</key>
							<string>invalid.illegal.escape.gdresource</string>
							<key>match</key>
							<string>\\[^btnfr/&quot;\\\n]</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>name</key>
					<string>invalid.illegal.escape.gdresource</string>
					<key>begin</key>
					<string>&apos;&apos;&apos;</string>
					<key>end</key>
					<string>&apos;&apos;&apos;</string>
				</dict>
				<dict>
					<key>name</key>
					<string>string.quoted.single.literal.line.gdresource</string>
					<key>match</key>
					<string>&apos;.*?&apos;</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;!\w)(true|false)(?!\w)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.language.gdresource</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;!\w)([\+\-]?(0|([1-9](([0-9]|_[0-9])+)?))(?:(?:\.(0|([1-9](([0-9]|_[0-9])+)?)))?[eE][\+\-]?[1-9]_?[0-9]*|(?:\.[0-9_]*)))(?!\w)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.float.gdresource</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;!\w)((?:[\+\-]?(0|([1-9](([0-9]|_[0-9])+)?))))(?!\w)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.integer.gdresource</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;!\w)([\+\-]?inf)(?!\w)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.inf.gdresource</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;!\w)([\+\-]?nan)(?!\w)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.nan.gdresource</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;!\w)((?:0x(([0-9a-fA-F](([0-9a-fA-F]|_[0-9a-fA-F])+)?))))(?!\w)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.hex.gdresource</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;!\w)(0o[0-7](_?[0-7])*)(?!\w)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.oct.gdresource</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;!\w)(0b[01](_?[01])*)(?!\w)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.bin.gdresource</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;!\w)(Vector2|Vector2i|Vector3|Vector3i|Color|Rect2|Rect2i|Array|Basis|Dictionary|Plane|Quat|RID|Rect3|Transform|Transform2D|Transform3D|AABB|String|Color|NodePath|Object|PoolByteArray|PoolIntArray|PoolRealArray|PoolStringArray|PoolVector2Array|PoolVector3Array|PoolColorArray|bool|int|float|StringName|Quaternion|PackedByteArray|PackedInt32Array|PackedInt64Array|PackedFloat32Array|PackedFloat64Array|PackedStringArray|PackedVector2Array|PackedVector2iArray|PackedVector3Array|PackedVector3iArray|PackedColorArray)(\()\s?</string>
					<key>end</key>
					<string>\s?(\))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#key_value</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#data</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.class.library.gdresource</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;!\w)(ExtResource|SubResource)(\()\s?</string>
					<key>end</key>
					<string>\s?(\))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#key_value</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#data</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.gdresource</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>embedded_gdscript</key>
		<dict>
			<key>begin</key>
			<string>(script/source) = &quot;</string>
			<key>end</key>
			<string>&quot;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.gdscript</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.property.gdresource</string>
				</dict>
			</dict>
		</dict>
		<key>embedded_shader</key>
		<dict>
			<key>name</key>
			<string>meta.embedded.block.gdshader</string>
			<key>begin</key>
			<string>(code) = &quot;</string>
			<key>end</key>
			<string>&quot;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.gdshader</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.property.gdresource</string>
				</dict>
			</dict>
		</dict>
		<key>heading</key>
		<dict>
			<key>begin</key>
			<string>\[([a-z_]*)\s?</string>
			<key>end</key>
			<string>\]</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#heading_properties</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#data</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.gdresource</string>
				</dict>
			</dict>
		</dict>
		<key>heading_properties</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>invalid.deprecated.noValue.gdresource</string>
					<key>match</key>
					<string>(\s*[A-Za-z_\-][A-Za-z0-9_\-]*\s*=)(?=\s*$)</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\s*([A-Za-z_-][^\s]*|&quot;.+&quot;|&apos;.+&apos;|[0-9]+)\s*(=)\s*</string>
					<key>end</key>
					<string>($|(?==)|\,?|\s*(?=\}))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#data</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.other.property.gdresource</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyValue.gdresource</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>key_value</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>invalid.deprecated.noValue.gdresource</string>
					<key>match</key>
					<string>(\s*[A-Za-z_\-][A-Za-z0-9_\-]*\s*=)(?=\s*$)</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\s*([A-Za-z_-][^\s]*|&quot;.+&quot;|&apos;.+&apos;|[0-9]+)\s*(=)\s*</string>
					<key>end</key>
					<string>($|(?==)|\,|\s*(?=\}))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#data</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.other.property.gdresource</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyValue.gdresource</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>gdnlib</string>
		<string>gdns</string>
		<string>tres</string>
		<string>tscn</string>
	</array>
</dict>
</plist>
