<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Golo</string>
	<key>scopeName</key>
	<string>source.golo</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>name</key>
			<string>comment.line.number-sign.golo</string>
			<key>match</key>
			<string>(#).*$
?</string>
		</dict>
		<dict>
			<key>name</key>
			<string>comment.block.golo</string>
			<key>begin</key>
			<string>----</string>
			<key>end</key>
			<string>----</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.golo</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>comment.block.golo</string>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.golo</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>string.quoted.third.golo</string>
			<key>begin</key>
			<string>&quot;&quot;&quot;</string>
			<key>end</key>
			<string>&quot;&quot;&quot;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>variable.parameter.template.golo</string>
					<key>match</key>
					<string>(\$\w+|\$\{[^\}]+\})</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.escape.golo</string>
					<key>match</key>
					<string>\\.</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.golo</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.golo</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>string.quoted.double.golo</string>
			<key>begin</key>
			<string>&quot;</string>
			<key>end</key>
			<string>&quot;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>variable.parameter.template.golo</string>
					<key>match</key>
					<string>(\$\w+|\$\{[^\}]+\})</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.escape.golo</string>
					<key>match</key>
					<string>\\.</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.golo</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.golo</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>string.quoted.single.golo</string>
			<key>begin</key>
			<string>&apos;</string>
			<key>end</key>
			<string>&apos;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.character.escape.golo</string>
					<key>match</key>
					<string>\\.</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.golo</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.golo</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.language.golo</string>
			<key>match</key>
			<string>\b(true|false|null|super|)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.numeric.golo</string>
			<key>match</key>
			<string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)([LlFfUuDd]|UL|ul)?\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.other.golo</string>
			<key>match</key>
			<string>\b([A-Z][A-Z0-9_]+)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.other.golo</string>
			<key>match</key>
			<string>\b(this|checkResult|checkArguments|withContext)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.modifier.golo</string>
			<key>match</key>
			<string>\b(var|let|val|local|extends|implements|overrides|interfaces)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.control.catch-exception.golo</string>
			<key>match</key>
			<string>\b(try|catch|finally|throw|raise)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.control.golo</string>
			<key>match</key>
			<string>\b(if|then|else|match|while|for|foreach|do|return|when|otherwise|where|break|continue)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.other.golo</string>
			<key>match</key>
			<string>\b(println|print|readln|readpwd|function|fun|pimp|spawn|send|shutdown|augment|AdapterFabric|DynamicObject|Thread|Promise|promise|Observable|DynamicVariable|defaultContext|module|import|fileToText|textToFile|mapEntry|compile|TemplateEngine|EvaluationEnvironment|asInterfaceInstance|)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.js</string>
			<key>match</key>
			<string>\b(define|fail|onSet|onFail|onChange|invokeWithArguments|stringify|value|get|set|future|times|each|filter|map)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.operator.golo</string>
			<key>match</key>
			<string>\b(in|not|and|or|is|isnt|as|andThen|bindTo|bindAt|\?:|orIfNull|oftype)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.operator.comparison.golo</string>
			<key>match</key>
			<string>(==|!=|&lt;=|&gt;=|&lt;&gt;|&lt;|&gt;|\?:)</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.operator.assignment.golo</string>
			<key>match</key>
			<string>(=)</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.operator.declaration.golo</string>
			<key>match</key>
			<string>(:|\||)</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.operator.dot.golo</string>
			<key>match</key>
			<string>(\.)</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.operator.increment-decrement.golo</string>
			<key>match</key>
			<string>(\-\-|\+\+)</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.operator.arithmetic.golo</string>
			<key>match</key>
			<string>(\-|\+|\*|\/|%)</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.operator.logical.golo</string>
			<key>match</key>
			<string>(!|&amp;&amp;|\|\|)</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.class.golo</string>
			<key>match</key>
			<string>\b(struct|range\[|tuple\[|array\[|map\[|set\[|vector\[|list\[)|\[|\]|\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.class.golo</string>
			<key>match</key>
			<string>(\{|\}|@|\(|\))</string>
		</dict>
	</array>
	<key>fileTypes</key>
	<array>
		<string>golo</string>
	</array>
</dict>
</plist>
