<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Grammatical Framework</string>
	<key>scopeName</key>
	<string>source.gf</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>name</key>
			<string>keyword.module.gf</string>
			<key>match</key>
			<string>\b(abstract|concrete|interface|instance|resource|incomplete|of|with|open|in)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.judgement.gf</string>
			<key>match</key>
			<string>\b(cat|fun|def|data|lincat|lin|lindef|linref|printname|printname|param|oper|flags)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.other.gf</string>
			<key>match</key>
			<string>\b(table|pre|case|variants|let|in|where)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.gf</string>
			<key>match</key>
			<string>(=&gt;|-&gt;|:|=|\.|\+|\*|!|\||\\)</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.gf</string>
			<key>match</key>
			<string>(;|,)</string>
		</dict>
		<dict>
			<key>name</key>
			<string>string.quoted.double.gf</string>
			<key>begin</key>
			<string>&quot;</string>
			<key>end</key>
			<string>&quot;</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.string.begin.gf</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.string.end.gf</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>comment.line.gf</string>
			<key>begin</key>
			<string>--</string>
			<key>end</key>
			<string>$</string>
		</dict>
		<dict>
			<key>name</key>
			<string>comment.block.gf</string>
			<key>begin</key>
			<string>{-</string>
			<key>end</key>
			<string>-}</string>
		</dict>
	</array>
	<key>fileTypes</key>
	<array>
		<string>gf</string>
	</array>
</dict>
</plist>
