<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>HOCON</string>
	<key>scopeName</key>
	<string>source.hocon</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#duration-long</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#bytesize-long</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#duration-short</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#bytesize-short</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#variables</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constant</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#mstring</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#number</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#ustring</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?:[ 	]*([\w-]+)\s*?({|=|:))</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.hocon</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.key-value.hocon</string>
				</dict>
			</dict>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>bytesize-long</key>
		<dict>
			<key>name</key>
			<string>constant.numeric.byte.long.hocon</string>
			<key>match</key>
			<string>\b\d+((kilo|mega|giga|tera|peta|exa|zetta|yotta|kibi|mebi|gibi|tebi|pebi|exbi|zebo|yobi)?byte[s]?)\b</string>
		</dict>
		<key>bytesize-short</key>
		<dict>
			<key>name</key>
			<string>constant.numeric.byte.short.hocon</string>
			<key>match</key>
			<string>\b\d+(([kMGTPEZY]B)|([KMGTPEZY]B?)|([KMGTPEZY]iB?)|([kmgtpezybB]))\b</string>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>comment.line.double-slash.hocon</string>
					<key>match</key>
					<string>(//).*$\n?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.hocon</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>comment.line.pound.hocon</string>
					<key>match</key>
					<string>(#).*$\n?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.hocon</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>constant</key>
		<dict>
			<key>match</key>
			<string>[^-]\b((?:true|false|null|on|off|yes|no))\b[^-]</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language.hocon</string>
				</dict>
			</dict>
		</dict>
		<key>duration-long</key>
		<dict>
			<key>name</key>
			<string>constant.numeric.duration.long.hocon</string>
			<key>match</key>
			<string>\b\d+(day|hour|minute|millisecond|microsecond|nanosecond|second)[s]?\b</string>
		</dict>
		<key>duration-short</key>
		<dict>
			<key>name</key>
			<string>constant.numeric.duration.short.hocon</string>
			<key>match</key>
			<string>\b(\d+)(d|h|ns|ms|us|s)\b</string>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.other.source.hocon</string>
					<key>match</key>
					<string>\b(include|url|file|classpath)\b</string>
				</dict>
			</array>
		</dict>
		<key>mstring</key>
		<dict>
			<key>name</key>
			<string>string.quoted.triple.hocon</string>
			<key>begin</key>
			<string>&quot;&quot;&quot;</string>
			<key>end</key>
			<string>&quot;&quot;&quot;</string>
		</dict>
		<key>number</key>
		<dict>
			<key>name</key>
			<string>constant.numeric.zzz.simple.numbers.hocon</string>
			<key>match</key>
			<string>(\b\-?\d+(\.\d+)?([eE]\d+)?\b)</string>
		</dict>
		<key>string</key>
		<dict>
			<key>name</key>
			<string>string.quoted.double.hocon</string>
			<key>begin</key>
			<string>&quot;</string>
			<key>end</key>
			<string>&quot;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.character.escape.hocon</string>
					<key>match</key>
					<string>(\\(?:[&quot;\\/bfnrt]|u[0-9a-fA-F]{4}))</string>
				</dict>
				<dict>
					<key>name</key>
					<string>invalid.illegal.unrecognized-string-escape.hocon</string>
					<key>match</key>
					<string>\\.</string>
				</dict>
			</array>
		</dict>
		<key>ustring</key>
		<dict>
			<key>name</key>
			<string>string.other.zzz.unquoted.hocon</string>
			<key>match</key>
			<string>([^:=\{\}\[\]\s,][^0-9:=\{\}\[\],][^=:\{\}\[\]\s,]*)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.hocon</string>
				</dict>
			</dict>
		</dict>
		<key>variables</key>
		<dict>
			<key>name</key>
			<string>storage.type.source.hocon</string>
			<key>match</key>
			<string>\$\{[^\}]*\}</string>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>hocon</string>
	</array>
</dict>
</plist>
