<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>ASP.NET Razor</string>
	<key>scopeName</key>
	<string>text.html.cshtml</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#razor-directives</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#razor-code-block</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#razor-else-if</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#razor-if</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#razor-else</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#razor-foreach</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#razor-for</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#explicit-razor-expression</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#implicit-razor-expression</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>name</key>
			<string>comment.block.cshtml</string>
			<key>begin</key>
			<string>@\*</string>
			<key>end</key>
			<string>\*@</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.source.cshtml</string>
				</dict>
			</dict>
		</dict>
		<key>csharp-namespace-identifier</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>entity.name.type.namespace.cs</string>
					<key>match</key>
					<string>[_[:alpha:]][_[:alnum:]]*</string>
				</dict>
			</array>
		</dict>
		<key>csharp-type-name</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>([_[:alpha:]][_[:alnum:]]*)\s*(\:\:)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.alias.cs</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.coloncolon.cs</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>([_[:alpha:]][_[:alnum:]]*)\s*(\.)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.cs</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.accessor.cs</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>(\.)\s*([_[:alpha:]][_[:alnum:]]*)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.accessor.cs</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.type.cs</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>storage.type.cs</string>
					<key>match</key>
					<string>[_[:alpha:]][_[:alnum:]]*</string>
				</dict>
			</array>
		</dict>
		<key>explicit-razor-expression</key>
		<dict>
			<key>name</key>
			<string>meta.expression.explicit.cshtml</string>
			<key>begin</key>
			<string>(@)\(</string>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.cs</string>
				</dict>
			</array>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.cshtml</string>
				</dict>
			</dict>
		</dict>
		<key>functions-directive</key>
		<dict>
			<key>name</key>
			<string>meta.directive.functions.cshtml</string>
			<key>match</key>
			<string>(@functions)</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.cshtml</string>
				</dict>
			</dict>
		</dict>
		<key>implements-directive</key>
		<dict>
			<key>name</key>
			<string>meta.directive.implements.cshtml</string>
			<key>begin</key>
			<string>(@implements)\s+</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#csharp-type-name</string>
				</dict>
			</array>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.cshtml</string>
				</dict>
			</dict>
		</dict>
		<key>implicit-razor-expression</key>
		<dict>
			<key>name</key>
			<string>meta.expression.implicit.cshtml</string>
			<key>match</key>
			<string>(?&lt;!@)(@)([a-zA-Z0-9\.\_\(\)]+)</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.cshtml</string>
				</dict>
			</dict>
		</dict>
		<key>inherits-directive</key>
		<dict>
			<key>name</key>
			<string>meta.directive.inherits.cshtml</string>
			<key>begin</key>
			<string>(@inherits)\s+</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#csharp-type-name</string>
				</dict>
			</array>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.cshtml</string>
				</dict>
			</dict>
		</dict>
		<key>inject-directive</key>
		<dict>
			<key>name</key>
			<string>meta.directive.inject.cshtml</string>
			<key>begin</key>
			<string>(@inject)\s+</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#csharp-type-name</string>
				</dict>
			</array>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.cshtml</string>
				</dict>
			</dict>
		</dict>
		<key>layout-directive</key>
		<dict>
			<key>name</key>
			<string>meta.directive.layout.cshtml</string>
			<key>begin</key>
			<string>(@layout)\s+</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#csharp-type-name</string>
				</dict>
			</array>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.cshtml</string>
				</dict>
			</dict>
		</dict>
		<key>model-directive</key>
		<dict>
			<key>name</key>
			<string>meta.directive.model.cshtml</string>
			<key>begin</key>
			<string>(@model)\s+</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#csharp-type-name</string>
				</dict>
			</array>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.cshtml</string>
				</dict>
			</dict>
		</dict>
		<key>page-directive</key>
		<dict>
			<key>name</key>
			<string>meta.directive.page.cshtml</string>
			<key>begin</key>
			<string>(@page)\s+</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.cs</string>
				</dict>
			</array>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.cshtml</string>
				</dict>
			</dict>
		</dict>
		<key>razor-code-block</key>
		<dict>
			<key>begin</key>
			<string>@?\{</string>
			<key>end</key>
			<string>\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.cshtml</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.cs</string>
				</dict>
			</array>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.cshtml</string>
				</dict>
			</dict>
		</dict>
		<key>razor-directives</key>
		<dict>
			<key>name</key>
			<string>meta.directive.cshtml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#using-directive</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#model-directive</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inherits-directive</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inject-directive</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#implements-directive</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#layout-directive</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#page-directive</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#functions-directive</string>
				</dict>
			</array>
		</dict>
		<key>razor-else</key>
		<dict>
			<key>begin</key>
			<string>(else)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.cs</string>
				</dict>
			</array>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.cshtml</string>
				</dict>
			</dict>
		</dict>
		<key>razor-else-if</key>
		<dict>
			<key>begin</key>
			<string>(else\s+if)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.cs</string>
				</dict>
			</array>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.cshtml</string>
				</dict>
			</dict>
		</dict>
		<key>razor-for</key>
		<dict>
			<key>begin</key>
			<string>(@for)\s*\(</string>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.cs</string>
				</dict>
			</array>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.cshtml</string>
				</dict>
			</dict>
		</dict>
		<key>razor-foreach</key>
		<dict>
			<key>begin</key>
			<string>(@foreach)\s*\(</string>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.cs</string>
				</dict>
			</array>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.cshtml</string>
				</dict>
			</dict>
		</dict>
		<key>razor-if</key>
		<dict>
			<key>begin</key>
			<string>(@if)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.cs</string>
				</dict>
			</array>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.cshtml</string>
				</dict>
			</dict>
		</dict>
		<key>using-directive</key>
		<dict>
			<key>name</key>
			<string>meta.directive.using.cshtml</string>
			<key>begin</key>
			<string>(@)(?=using)(.*)</string>
			<key>end</key>
			<string>(?=$)</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.cshtml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.cs</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>cshtml</string>
		<string>razor</string>
	</array>
</dict>
</plist>
