<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Ignore List</string>
	<key>scopeName</key>
	<string>source.gitignore</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#main</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>bazaarPrefixes</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>storage.modifier.bazaar.re-prefix.gitignore</string>
					<key>match</key>
					<string>^RE(:)(?=\S)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.logical.not.negation.elevated.bazaar.gitignore</string>
					<key>match</key>
					<string>^!!(?=\S)</string>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>name</key>
			<string>comment.line.number-sign.gitignore</string>
			<key>begin</key>
			<string>#</string>
			<key>end</key>
			<string>$</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.gitignore</string>
				</dict>
			</dict>
		</dict>
		<key>cvsSyntax</key>
		<dict>
			<key>match</key>
			<string>\A(syntax)(:)\s+(glob)$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.assignment.glob-syntax.cvs.gitignore</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.separator.key-value.cvs.gitignore</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.constant.language.syntax-type.cvs.gitignore</string>
				</dict>
			</dict>
		</dict>
		<key>escape</key>
		<dict>
			<key>name</key>
			<string>constant.character.escape.backslash.gitignore</string>
			<key>match</key>
			<string>(\\).</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.escape.backslash.gitignore</string>
				</dict>
			</dict>
		</dict>
		<key>magic</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.magic-signature.long.gitignore</string>
					<key>begin</key>
					<string>^(:)(\()(?=.*?\))</string>
					<key>end</key>
					<string>(?&lt;!\\)\)|(?=\s*$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escape</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#magicInnards</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.signature.begin.gitignore</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.signature.begin.gitignore</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.signature.end.gitignore</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.magic-signature.short.gitignore</string>
					<key>match</key>
					<string>^(:)([!^]+)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.signature.begin.gitignore</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.mnemonic.gitignore</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>magicInnards</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#comma</string>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.attribute-list.gitignore</string>
					<key>begin</key>
					<string>(?:\G|(?&lt;=,|\())(attr)(:)</string>
					<key>end</key>
					<string>(?=,|\)|$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>meta.attribute.gitignore</string>
							<key>match</key>
							<string>(-|!)?((?:[^\\\s=\(\),]|\\.)++)(?:(=)((?:[^\\\s=\(\),]|\\.)*+))?</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#magicMnemonic</string>
										</dict>
									</array>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>variable.parameter.attribute.gitignore</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#escape</string>
										</dict>
									</array>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.assignment.equals-sign.gitignore</string>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>constant.language.other.gitignore</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#escape</string>
										</dict>
									</array>
								</dict>
							</dict>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.magic-signature.$1.gitignore</string>
						</dict>
						<key>2</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>etc#colon</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.$1-attribute.gitignore</string>
					<key>match</key>
					<string>(?:\G|(?&lt;=,|\())(-|!)?(attr|exclude|glob|icase|literal|top)(?=,|\))</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#magicMnemonic</string>
								</dict>
							</array>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.magic-signature.$2.gitignore</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.unknown-attribute.gitignore</string>
					<key>match</key>
					<string>(?:\G|(?&lt;=,|\())(-|!)?((?:[^\\=\s,:\)]|\\.)++)(?=,|\))</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#magicMnemonic</string>
								</dict>
							</array>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.magic-signature.unknown.gitignore</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>magicMnemonic</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.operator.logical.not.negation.gitignore</string>
					<key>match</key>
					<string>-</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.unset.delete.gitignore</string>
					<key>match</key>
					<string>!</string>
				</dict>
			</array>
		</dict>
		<key>main</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cvsSyntax</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#magic</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#pattern</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#escape</string>
				</dict>
			</array>
		</dict>
		<key>pattern</key>
		<dict>
			<key>name</key>
			<string>meta.pattern.gitignore</string>
			<key>begin</key>
			<string>(?=[^#\s])</string>
			<key>end</key>
			<string>$|(?=#)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#bazaarPrefixes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#patternInnards</string>
				</dict>
			</array>
		</dict>
		<key>patternInnards</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escape</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#range</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.logical.not.negation.gitignore</string>
					<key>match</key>
					<string>\G!</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.glob.wildcard.globstar.gitignore</string>
					<key>match</key>
					<string>\*\*</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.glob.wildcard.gitignore</string>
					<key>match</key>
					<string>[*?]</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.directory.separator.meta.gitignore</string>
					<key>match</key>
					<string>/</string>
				</dict>
				<dict>
					<key>name</key>
					<string>entity.other.file.name.gitignore</string>
					<key>match</key>
					<string>[^\[\]\\*?#/\s]+</string>
				</dict>
			</array>
		</dict>
		<key>range</key>
		<dict>
			<key>name</key>
			<string>meta.character-range.gitignore</string>
			<key>contentName</key>
			<string>constant.character.class.gitignore</string>
			<key>begin</key>
			<string>\[</string>
			<key>end</key>
			<string>\]|(?=$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escape</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.delimiter.range.character-set.gitignore</string>
					<key>match</key>
					<string>-</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.square.bracket.begin.gitignore</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.square.bracket.end.gitignore</string>
				</dict>
			</dict>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>gitignore</string>
	</array>
</dict>
</plist>
