<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Jison Lex</string>
	<key>scopeName</key>
	<string>source.jisonlex</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>%%</string>
			<key>end</key>
			<string>\z</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^%%</string>
					<key>end</key>
					<string>\z</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>meta.section.user-code.jisonlex</string>
							<key>contentName</key>
							<string>source.js.embedded.jison</string>
							<key>begin</key>
							<string>\G</string>
							<key>end</key>
							<string>\z</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#user_code_section</string>
								</dict>
							</array>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.separator.section.jisonlex</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.section.rules.jisonlex</string>
					<key>begin</key>
					<string>\G</string>
					<key>end</key>
					<string>(?=^%%)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#rules_section</string>
						</dict>
					</array>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.separator.section.jisonlex</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.section.definitions.jisonlex</string>
			<key>begin</key>
			<string>^</string>
			<key>end</key>
			<string>(?=%%)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#definitions_section</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>definitions_section</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.jison#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.jison#include_declarations</string>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.definition.jisonlex</string>
					<key>begin</key>
					<string>\b[[:alpha:]_](?:[\w-]*\w)?\b</string>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.jison#comments</string>
						</dict>
						<dict>
							<key>name</key>
							<string>string.regexp.jisonlex</string>
							<key>begin</key>
							<string>(?=\S)</string>
							<key>end</key>
							<string>(?=\s)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#regexp</string>
								</dict>
							</array>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>entity.name.other.definition.jisonlex</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.start-condition.jisonlex</string>
					<key>begin</key>
					<string>%[sx]\b</string>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.jison#comments</string>
						</dict>
						<dict>
							<key>name</key>
							<string>entity.name.function.jisonlex</string>
							<key>match</key>
							<string>\b[[:alpha:]_](?:[\w-]*\w)?\b</string>
						</dict>
						<dict>
							<key>name</key>
							<string>invalid.illegal.jisonlex</string>
							<key>match</key>
							<string>\S</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.other.start-condition.jisonlex</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>include</key>
					<string>source.jison#options_declarations</string>
				</dict>
				<dict>
					<key>name</key>
					<string>invalid.unimplemented.jisonlex</string>
					<key>match</key>
					<string>%(?:array|pointer)</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.jison#user_code_blocks</string>
				</dict>
			</array>
		</dict>
		<key>name_uses</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.other.name-use.jisonlex</string>
					<key>match</key>
					<string>(\{)[[:alpha:]_](?:[\w-]*\w)?(\})</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.name-use.begin.jisonlex</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.name-use.end.jisonlex</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>regexp</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.jison#comments</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.other.character-class.any.regexp.jisonlex</string>
					<key>match</key>
					<string>\.</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.other.anchor.word-boundary.regexp.jisonlex</string>
					<key>match</key>
					<string>\\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.other.anchor.non-word-boundary.regexp.jisonlex</string>
					<key>match</key>
					<string>\\B</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.other.anchor.start-of-input.regexp.jisonlex</string>
					<key>match</key>
					<string>\^</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.other.anchor.end-of-input.regexp.jisonlex</string>
					<key>match</key>
					<string>\$</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.other.back-reference.regexp.jisonlex</string>
					<key>match</key>
					<string>\\[1-9]\d*</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.quantifier.regexp.jisonlex</string>
					<key>match</key>
					<string>(?:[+*?]|\{(?:\d+(?:,(?:\d+)?)?|,\d+)\})\??</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.alternation.regexp.jisonlex</string>
					<key>match</key>
					<string>\|</string>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.non-capturing.group.regexp.jisonlex</string>
					<key>begin</key>
					<string>\(\?:</string>
					<key>end</key>
					<string>\)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#regexp</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.group.begin.regexp.jisonlex</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.group.end.regexp.jisonlex</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.lookahead.assertion.regexp.jisonlex</string>
					<key>begin</key>
					<string>\(\?=</string>
					<key>end</key>
					<string>\)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#regexp</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.group.begin.regexp.jisonlex</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.group.end.regexp.jisonlex</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.negative.lookahead.assertion.regexp.jisonlex</string>
					<key>begin</key>
					<string>\(\?!</string>
					<key>end</key>
					<string>\)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#regexp</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.group.begin.regexp.jisonlex</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.group.end.regexp.jisonlex</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.group.regexp.jisonlex</string>
					<key>begin</key>
					<string>\(</string>
					<key>end</key>
					<string>\)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#regexp</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.group.begin.regexp.jisonlex</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.group.end.regexp.jisonlex</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.other.character-class.set.regexp.jisonlex</string>
					<key>begin</key>
					<string>(\[)(\^)?</string>
					<key>end</key>
					<string>\]</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#name_uses</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#regexp_character_class</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.character-class.begin.regexp.jisonlex</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.negation.regexp.jisonlex</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.character-class.end.regexp.jisonlex</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>include</key>
					<string>#regexp_character_class</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#name_uses</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.jison#quoted_strings</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.other.eof.regexp.jisonlex</string>
					<key>match</key>
					<string>&lt;&lt;EOF&gt;&gt;</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.negative.lookahead.regexp.jisonlex</string>
					<key>match</key>
					<string>/!</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.lookahead.regexp.jisonlex</string>
					<key>match</key>
					<string>/</string>
				</dict>
			</array>
		</dict>
		<key>regexp_character_class</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.character.escape.character-class.word.regexp.jisonlex</string>
					<key>match</key>
					<string>\\w</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.escape.character-class.non-word.regexp.jisonlex</string>
					<key>match</key>
					<string>\\W</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.escape.character-class.space.regexp.jisonlex</string>
					<key>match</key>
					<string>\\s</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.escape.character-class.non-space.regexp.jisonlex</string>
					<key>match</key>
					<string>\\S</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.escape.character-class.digit.regexp.jisonlex</string>
					<key>match</key>
					<string>\\d</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.escape.character-class.non-digit.regexp.jisonlex</string>
					<key>match</key>
					<string>\\D</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.escape.character-class.control.regexp.jisonlex</string>
					<key>match</key>
					<string>\\c[A-Z]</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.js#string_escapes</string>
				</dict>
			</array>
		</dict>
		<key>rules_section</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.jison#comments</string>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.start-conditions.jisonlex</string>
					<key>begin</key>
					<string>(?:^|(?&lt;=%\}))&lt;(?!&lt;EOF&gt;&gt;)</string>
					<key>end</key>
					<string>&gt;</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>keyword.other.jisonlex</string>
							<key>match</key>
							<string>\bINITIAL\b</string>
						</dict>
						<dict>
							<key>name</key>
							<string>entity.name.function.jisonlex</string>
							<key>match</key>
							<string>\b[[:alpha:]_](?:[\w-]*\w)?\b</string>
						</dict>
						<dict>
							<key>name</key>
							<string>punctuation.separator.start-condition.jisonlex</string>
							<key>match</key>
							<string>,</string>
						</dict>
						<dict>
							<key>name</key>
							<string>keyword.other.any-start-condition.jisonlex</string>
							<key>match</key>
							<string>(?&lt;=&lt;)\*(?=&gt;)</string>
						</dict>
						<dict>
							<key>name</key>
							<string>invalid.illegal.jisonlex</string>
							<key>match</key>
							<string>.</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.start-conditions.begin.jisonlex</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.start-conditions.end.jisonlex</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.rule.action.jisonlex</string>
					<key>begin</key>
					<string>(?=%\{)</string>
					<key>end</key>
					<string>(?&lt;=%\})</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.jison#user_code_blocks</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>name</key>
					<string>string.regexp.jisonlex</string>
					<key>begin</key>
					<string>(?:^|(?&lt;=&gt;|%\}))(?=\S)</string>
					<key>end</key>
					<string>(?=\s|%\{)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#regexp</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.rule.action.jisonlex</string>
					<key>contentName</key>
					<string>source.js.embedded.jison</string>
					<key>begin</key>
					<string>(?=\S)</string>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.jison#include_declarations</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>user_code_section</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.jison#user_code_include_declarations</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>jisonlex</string>
	</array>
</dict>
</plist>
