<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Jison</string>
	<key>scopeName</key>
	<string>source.jison</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>%%</string>
			<key>end</key>
			<string>\z</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>%%</string>
					<key>end</key>
					<string>\z</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>meta.section.epilogue.jison</string>
							<key>contentName</key>
							<string>source.js.embedded.jison</string>
							<key>begin</key>
							<string>\G</string>
							<key>end</key>
							<string>\z</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#epilogue_section</string>
								</dict>
							</array>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.separator.section.jison</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.section.rules.jison</string>
					<key>begin</key>
					<string>\G</string>
					<key>end</key>
					<string>(?=%%)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#rules_section</string>
						</dict>
					</array>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.separator.section.jison</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.section.declarations.jison</string>
			<key>begin</key>
			<string>^</string>
			<key>end</key>
			<string>(?=%%)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#declarations_section</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>actions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.action.jison</string>
					<key>contentName</key>
					<string>source.js.embedded.jison</string>
					<key>begin</key>
					<string>\{\{</string>
					<key>end</key>
					<string>\}\}</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.action.begin.jison</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.action.end.jison</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.action.jison</string>
					<key>begin</key>
					<string>(?=%\{)</string>
					<key>end</key>
					<string>(?&lt;=%\})</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#user_code_blocks</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>comment.line.double-slash.jison</string>
					<key>begin</key>
					<string>//</string>
					<key>end</key>
					<string>$</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.jison</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>comment.block.jison</string>
					<key>begin</key>
					<string>/\*</string>
					<key>end</key>
					<string>\*/</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.begin.jison</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.end.jison</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>declarations_section</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>^\s*(%lex)\s*$</string>
					<key>end</key>
					<string>^\s*(/lex)\b</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>%%</string>
							<key>end</key>
							<string>(?=/lex)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>begin</key>
									<string>^%%</string>
									<key>end</key>
									<string>(?=/lex)</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>name</key>
											<string>meta.section.user-code.jisonlex</string>
											<key>contentName</key>
											<string>source.js.embedded.jisonlex</string>
											<key>begin</key>
											<string>\G</string>
											<key>end</key>
											<string>(?=/lex)</string>
											<key>patterns</key>
											<array>
												<dict>
													<key>include</key>
													<string>source.jisonlex#user_code_section</string>
												</dict>
											</array>
										</dict>
									</array>
									<key>beginCaptures</key>
									<dict>
										<key>0</key>
										<dict>
											<key>name</key>
											<string>meta.separator.section.jisonlex</string>
										</dict>
									</dict>
								</dict>
								<dict>
									<key>name</key>
									<string>meta.section.rules.jisonlex</string>
									<key>begin</key>
									<string>\G</string>
									<key>end</key>
									<string>^(?=%%|/lex)</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>source.jisonlex#rules_section</string>
										</dict>
									</array>
								</dict>
							</array>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>meta.separator.section.jisonlex</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>name</key>
							<string>meta.section.definitions.jisonlex</string>
							<key>begin</key>
							<string>^</string>
							<key>end</key>
							<string>(?=%%|/lex)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.jisonlex#definitions_section</string>
								</dict>
							</array>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.lexer.begin.jison</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.lexer.end.jison</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.section.prologue.jison</string>
					<key>begin</key>
					<string>(?=%\{)</string>
					<key>end</key>
					<string>(?&lt;=%\})</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#user_code_blocks</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#options_declarations</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.other.declaration.$1.jison</string>
					<key>match</key>
					<string>%(ebnf|left|nonassoc|parse-param|right|start)\b</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#include_declarations</string>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.code.jison</string>
					<key>begin</key>
					<string>%(code)\b</string>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#rule_actions</string>
						</dict>
						<dict>
							<key>name</key>
							<string>keyword.other.code-qualifier.$1.jison</string>
							<key>match</key>
							<string>(init|required)</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#quoted_strings</string>
						</dict>
						<dict>
							<key>name</key>
							<string>string.unquoted.jison</string>
							<key>match</key>
							<string>\b[[:alpha:]_](?:[\w-]*\w)?\b</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.other.declaration.$1.jison</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.parser-type.jison</string>
					<key>begin</key>
					<string>%(parser-type)\b</string>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#quoted_strings</string>
						</dict>
						<dict>
							<key>name</key>
							<string>string.unquoted.jison</string>
							<key>match</key>
							<string>\b[[:alpha:]_](?:[\w-]*\w)?\b</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.other.declaration.$1.jison</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.token.jison</string>
					<key>begin</key>
					<string>%(token)\b</string>
					<key>end</key>
					<string>$|(%%|;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#numbers</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#quoted_strings</string>
						</dict>
						<dict>
							<key>name</key>
							<string>invalid.unimplemented.jison</string>
							<key>match</key>
							<string>&lt;[[:alpha:]_](?:[\w-]*\w)?&gt;</string>
						</dict>
						<dict>
							<key>name</key>
							<string>entity.other.token.jison</string>
							<key>match</key>
							<string>\S+</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.other.declaration.$1.jison</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.terminator.declaration.token.jison</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.other.declaration.$1.jison</string>
					<key>match</key>
					<string>%(debug|import)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>invalid.illegal.jison</string>
					<key>match</key>
					<string>%prec\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>invalid.unimplemented.jison</string>
					<key>match</key>
					<string>%[[:alpha:]_](?:[\w-]*\w)?\b</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numbers</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#quoted_strings</string>
				</dict>
			</array>
		</dict>
		<key>epilogue_section</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#user_code_include_declarations</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<key>include_declarations</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.include.jison</string>
					<key>begin</key>
					<string>(%(include))\s*</string>
					<key>end</key>
					<string>(?&lt;=[&apos;&quot;])|(?=\s)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#include_paths</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.declaration.$2.jison</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>include_paths</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#quoted_strings</string>
				</dict>
				<dict>
					<key>name</key>
					<string>string.unquoted.jison</string>
					<key>begin</key>
					<string>(?=\S)</string>
					<key>end</key>
					<string>(?=\s)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.js#string_escapes</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>numbers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(0[Xx])([0-9A-Fa-f]+)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.number.jison</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.integer.hexadecimal.jison</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.integer.decimal.jison</string>
					<key>match</key>
					<string>\d+</string>
				</dict>
			</array>
		</dict>
		<key>options_declarations</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.options.jison</string>
					<key>begin</key>
					<string>%options\b</string>
					<key>end</key>
					<string>^(?=\S|\s*$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>name</key>
							<string>entity.name.constant.jison</string>
							<key>match</key>
							<string>\b[[:alpha:]_](?:[\w-]*\w)?\b</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>(=)\s*</string>
							<key>end</key>
							<string>(?&lt;=[&apos;&quot;])|(?=\s)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#comments</string>
								</dict>
								<dict>
									<key>name</key>
									<string>constant.language.boolean.$1.jison</string>
									<key>match</key>
									<string>\b(true|false)\b</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#numbers</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#quoted_strings</string>
								</dict>
								<dict>
									<key>name</key>
									<string>string.unquoted.jison</string>
									<key>match</key>
									<string>\S+</string>
								</dict>
							</array>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.option.assignment.jison</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>include</key>
							<string>#quoted_strings</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.other.options.jison</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>quoted_strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>string.quoted.double.jison</string>
					<key>begin</key>
					<string>&quot;</string>
					<key>end</key>
					<string>&quot;</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.js#string_escapes</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>name</key>
					<string>string.quoted.single.jison</string>
					<key>begin</key>
					<string>&apos;</string>
					<key>end</key>
					<string>&apos;</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.js#string_escapes</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>rule_actions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#actions</string>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.action.jison</string>
					<key>contentName</key>
					<string>source.js.embedded.jison</string>
					<key>begin</key>
					<string>\{</string>
					<key>end</key>
					<string>\}</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.action.begin.jison</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.action.end.jison</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>include</key>
					<string>#include_declarations</string>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.action.jison</string>
					<key>contentName</key>
					<string>source.js.embedded.jison</string>
					<key>begin</key>
					<string>-&gt;|→</string>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.action.arrow.jison</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>rules_section</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#actions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#include_declarations</string>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.rule.jison</string>
					<key>begin</key>
					<string>\b[[:alpha:]_](?:[\w-]*\w)?\b</string>
					<key>end</key>
					<string>;</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>name</key>
							<string>meta.rule-components.jison</string>
							<key>begin</key>
							<string>:</string>
							<key>end</key>
							<string>(?=;)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#comments</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#quoted_strings</string>
								</dict>
								<dict>
									<key>match</key>
									<string>(\[)([[:alpha:]_](?:[\w-]*\w)?)(\])</string>
									<key>captures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.named-reference.begin.jison</string>
										</dict>
										<key>2</key>
										<dict>
											<key>name</key>
											<string>entity.name.other.reference.jison</string>
										</dict>
										<key>3</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.named-reference.end.jison</string>
										</dict>
									</dict>
								</dict>
								<dict>
									<key>name</key>
									<string>meta.prec.jison</string>
									<key>begin</key>
									<string>(%(prec))\s*</string>
									<key>end</key>
									<string>(?&lt;=[&apos;&quot;])|(?=\s)</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#comments</string>
										</dict>
										<dict>
											<key>include</key>
											<string>#quoted_strings</string>
										</dict>
										<dict>
											<key>name</key>
											<string>constant.other.token.jison</string>
											<key>begin</key>
											<string>(?=\S)</string>
											<key>end</key>
											<string>(?=\s)</string>
										</dict>
									</array>
									<key>beginCaptures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>keyword.other.$2.jison</string>
										</dict>
									</dict>
								</dict>
								<dict>
									<key>name</key>
									<string>keyword.operator.rule-components.separator.jison</string>
									<key>match</key>
									<string>\|</string>
								</dict>
								<dict>
									<key>name</key>
									<string>keyword.other.$0.jison</string>
									<key>match</key>
									<string>\b(?:EOF|error)\b</string>
								</dict>
								<dict>
									<key>name</key>
									<string>keyword.other.empty.jison</string>
									<key>match</key>
									<string>(?:%(?:e(?:mpty|psilon))|\b[Ɛɛεϵ])\b</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#rule_actions</string>
								</dict>
							</array>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.rule-components.assignment.jison</string>
								</dict>
							</dict>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>entity.name.constant.rule-result.jison</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.terminator.rule.jison</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>user_code_blocks</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.user-code-block.jison</string>
					<key>contentName</key>
					<string>source.js.embedded.jison</string>
					<key>begin</key>
					<string>%\{</string>
					<key>end</key>
					<string>%\}</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.user-code-block.begin.jison</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.user-code-block.end.jison</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>user_code_include_declarations</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.include.jison</string>
					<key>begin</key>
					<string>^(%(include))\s*</string>
					<key>end</key>
					<string>(?&lt;=[&apos;&quot;])|(?=\s)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#include_paths</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.declaration.$2.jison</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
	</dict>
	<key>injections</key>
	<dict>
		<key>L:(meta.action.jison - (comment | string)), source.js.embedded.jison - (comment | string), source.js.embedded.source - (comment | string.quoted.double | string.quoted.single)</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>variable.language.semantic-value.jison</string>
					<key>match</key>
					<string>\${2}</string>
				</dict>
				<dict>
					<key>name</key>
					<string>variable.language.result-location.jison</string>
					<key>match</key>
					<string>@\$</string>
				</dict>
				<dict>
					<key>name</key>
					<string>variable.language.stack-index-0.jison</string>
					<key>match</key>
					<string>##\$|\byysp\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.variable.token-reference.jison</string>
					<key>match</key>
					<string>#\S+#</string>
				</dict>
				<dict>
					<key>name</key>
					<string>variable.language.result-id.jison</string>
					<key>match</key>
					<string>#\$</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.variable.token-value.jison</string>
					<key>match</key>
					<string>\$(?:-?\d+|[[:alpha:]_](?:[\w-]*\w)?)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.variable.token-location.jison</string>
					<key>match</key>
					<string>@(?:-?\d+|[[:alpha:]_](?:[\w-]*\w)?)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.variable.stack-index.jison</string>
					<key>match</key>
					<string>##(?:-?\d+|[[:alpha:]_](?:[\w-]*\w)?)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.variable.token-id.jison</string>
					<key>match</key>
					<string>#(?:-?\d+|[[:alpha:]_](?:[\w-]*\w)?)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>variable.language.jison</string>
					<key>match</key>
					<string>\byy(?:l(?:eng|ineno|oc|stack)|rulelength|s(?:tate|s?tack)|text|vstack)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.other.jison</string>
					<key>match</key>
					<string>\byy(?:clearin|erro[kr])\b</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>jison</string>
	</array>
</dict>
</plist>
