<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Jolie</string>
	<key>scopeName</key>
	<string>source.jolie</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#code</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>block_comments</key>
		<dict>
			<key>name</key>
			<string>comment.block.jolie</string>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
		</dict>
		<key>code</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#block_comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#line_comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constants_language</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constants_numeric</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords_control</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords_with_colon</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords_other</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords_types</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords_modifiers</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#invocations</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#definitions</string>
				</dict>
			</array>
		</dict>
		<key>constants_language</key>
		<dict>
			<key>name</key>
			<string>constant.language.jolie</string>
			<key>match</key>
			<string>\b(true|false)\b</string>
		</dict>
		<key>constants_numeric</key>
		<dict>
			<key>name</key>
			<string>constant.numeric.jolie</string>
			<key>match</key>
			<string>\b\d+\b</string>
		</dict>
		<key>definitions</key>
		<dict>
			<key>match</key>
			<string>\b(inputPort|outputPort|interface|type|define|service)\s+(\w+)\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.jolie</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.class.identifier.jolie</string>
				</dict>
			</dict>
		</dict>
		<key>invocations</key>
		<dict>
			<key>match</key>
			<string>\b(\w+)\s*(@)\s*(\w+)\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.method.jolie</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.jolie</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>meta.class.jolie</string>
				</dict>
			</dict>
		</dict>
		<key>keywords_control</key>
		<dict>
			<key>name</key>
			<string>keyword.control.jolie</string>
			<key>match</key>
			<string>\b(if|else|while|for|foreach|provide|until|throw|forward|scope)\b</string>
		</dict>
		<key>keywords_modifiers</key>
		<dict>
			<key>name</key>
			<string>storage.modifiers.jolie</string>
			<key>match</key>
			<string>\b(csets|global)\b</string>
		</dict>
		<key>keywords_other</key>
		<dict>
			<key>name</key>
			<string>keyword.other.jolie</string>
			<key>match</key>
			<string>\b(constants|cH|instanceof|execution|comp|concurrent|nullProcess|single|sequential|main|init|cset|is_defined|embedded|extender|courier|forward|install|undef|include|synchronized|throws|throw)\b</string>
		</dict>
		<key>keywords_types</key>
		<dict>
			<key>name</key>
			<string>storage.type.jolie</string>
			<key>match</key>
			<string>\b(void|bool|int|string|long|double|any|raw)\b</string>
		</dict>
		<key>keywords_with_colon</key>
		<dict>
			<key>name</key>
			<string>keyword.other.with_colon.jolie</string>
			<key>match</key>
			<string>\b(location|Location|protocol|Protocol|interfaces|Interfaces|aggregates|Aggregates|redirects|Redirects|Jolie|JavaScript|Java|OneWay|RequestResponse)\b\s*:</string>
		</dict>
		<key>line_comments</key>
		<dict>
			<key>name</key>
			<string>comment.line.double-slash.jolie</string>
			<key>begin</key>
			<string>//</string>
			<key>end</key>
			<string>\n</string>
		</dict>
		<key>operators</key>
		<dict>
			<key>name</key>
			<string>keyword.operator.jolie</string>
			<key>match</key>
			<string>\b(&lt;&lt;|&amp;&amp;|\|\||\+|\-|/|\*|=|==|\+\+|--|\+=|-=|\*=|/=|!|%|%=)\b</string>
		</dict>
		<key>strings</key>
		<dict>
			<key>name</key>
			<string>string.quoted.double.jolie</string>
			<key>begin</key>
			<string>&quot;</string>
			<key>end</key>
			<string>&quot;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.character.escape.jolie</string>
					<key>match</key>
					<string>\\.</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>ol</string>
		<string>iol</string>
	</array>
</dict>
</plist>
