<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Jsonnet</string>
	<key>scopeName</key>
	<string>source.jsonnet</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>name</key>
			<string>constant.numeric.jsonnet</string>
			<key>match</key>
			<string>\b(\d+([Ee][+-]?\d+)?)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.numeric.jsonnet</string>
			<key>match</key>
			<string>\b\d+[.]\d*([Ee][+-]?\d+)?\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.numeric.jsonnet</string>
			<key>match</key>
			<string>\b[.]\d+([Ee][+-]?\d+)?\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.jsonnet</string>
			<key>match</key>
			<string>\bstd[.]is(String|Number|Boolean|Object|Array|Function)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.jsonnet</string>
			<key>match</key>
			<string>\bstd[.](acos|asin|atan|ceil|char|codepoint|cos|exp|exponent)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.jsonnet</string>
			<key>match</key>
			<string>\bstd[.](filter|floor|force|length|log|makeArray|mantissa|sign)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.jsonnet</string>
			<key>match</key>
			<string>\bstd[.](objectFields(All)?|objectHas(All)?|equals|prune)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.jsonnet</string>
			<key>match</key>
			<string>\bstd[.](pow|sin|sqrt|tan|type|max|min|mod|thisFile)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.jsonnet</string>
			<key>match</key>
			<string>\bstd[.](abs|assertEqual|escapeString(Bash|Dollars|Json|Python))\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.jsonnet</string>
			<key>match</key>
			<string>\bstd[.](filterMap|flattenArrays|foldl|foldr|format|join)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.jsonnet</string>
			<key>match</key>
			<string>\bstd[.](mapWithIndex|mapWithKey|deepJoin|mergePatch)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.jsonnet</string>
			<key>match</key>
			<string>\bstd[.]manifest(Ini|Python(Vars)?|Json(Ex)?|Yaml(Doc|Stream)|XmlJsonml)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.jsonnet</string>
			<key>match</key>
			<string>\bstd[.](lines|map|find|findSubstr|splitLimit|strReplace|ascii(Upper|Lower))\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.jsonnet</string>
			<key>match</key>
			<string>\bstd[.](set|set(Diff|Inter|Member|Union)|sort|resolvePath)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.jsonnet</string>
			<key>match</key>
			<string>\bstd[.]base64(Decode(Bytes)?)?\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.jsonnet</string>
			<key>match</key>
			<string>\bstd[.](split|stringChars|substr|toString|startsWith|endsWith)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.jsonnet</string>
			<key>match</key>
			<string>\bstd[.](parseInt|parseOctal|parseHex|range|uniq|slice|count)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>variable.language.jsonnet</string>
			<key>match</key>
			<string>\b[$]\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>string.double.jsonnet</string>
			<key>begin</key>
			<string>&quot;</string>
			<key>end</key>
			<string>&quot;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.character.escape.jsonnet</string>
					<key>match</key>
					<string>\\[&apos;&quot;\\/bfnrt]</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.escape.jsonnet</string>
					<key>match</key>
					<string>\\u[0-9a-fA-F]{4}</string>
				</dict>
				<dict>
					<key>name</key>
					<string>invalid.illegal.jsonnet</string>
					<key>match</key>
					<string>\\[^&apos;&quot;\\/bfnrtu]</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>name</key>
			<string>string.single.jsonnet</string>
			<key>begin</key>
			<string>&apos;</string>
			<key>end</key>
			<string>&apos;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.character.escape.jsonnet</string>
					<key>match</key>
					<string>\\[&apos;&quot;\\/bfnrt]</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.escape.jsonnet</string>
					<key>match</key>
					<string>\\u[0-9a-fA-F]{4}</string>
				</dict>
				<dict>
					<key>name</key>
					<string>invalid.illegal.jsonnet</string>
					<key>match</key>
					<string>\\[^&apos;&quot;\\/bfnrtu]</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>name</key>
			<string>string.double.verbatim.jsonnet</string>
			<key>begin</key>
			<string>@&quot;</string>
			<key>end</key>
			<string>&quot;(?!&quot;)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.character.escape.jsonnet</string>
					<key>match</key>
					<string>&quot;&quot;</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>name</key>
			<string>string.single.verbatim.jsonnet</string>
			<key>begin</key>
			<string>@&apos;</string>
			<key>end</key>
			<string>&apos;(?!&apos;)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.character.escape.jsonnet</string>
					<key>match</key>
					<string>&apos;&apos;</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>contentName</key>
			<string>string.block.jsonnet</string>
			<key>begin</key>
			<string>^(\s*)(.*)(\|\|\|)</string>
			<key>end</key>
			<string>^(?!$)(\1)(\|\|\|)</string>
			<key>beginCaptures</key>
			<dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.block.jsonnet</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.block.jsonnet</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>comment.block.jsonnet</string>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
		</dict>
		<dict>
			<key>name</key>
			<string>comment.line.jsonnet</string>
			<key>match</key>
			<string>//.*$</string>
		</dict>
		<dict>
			<key>name</key>
			<string>comment.block.jsonnet</string>
			<key>match</key>
			<string>#.*$</string>
		</dict>
		<dict>
			<key>name</key>
			<string>entity.name.function.jsonnet</string>
			<key>match</key>
			<string>\b[a-zA-Z_][a-z0-9A-Z_]*\s*(\([^)]*\))?\s*\+?::?:?</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.type.jsonnet</string>
			<key>match</key>
			<string>\b(import|importstr)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.other.jsonnet</string>
			<key>match</key>
			<string>\b(function)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>variable.language.jsonnet</string>
			<key>match</key>
			<string>\b(self|super)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.control.jsonnet</string>
			<key>match</key>
			<string>\b(if|then|else|for|in)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.other.jsonnet</string>
			<key>match</key>
			<string>\b(local|tailstrict)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.language.jsonnet</string>
			<key>match</key>
			<string>\b(true|false|null)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.control.jsonnet</string>
			<key>match</key>
			<string>\b(error|assert)\b</string>
		</dict>
	</array>
	<key>fileTypes</key>
	<array>
		<string>jsonnet</string>
		<string>libsonnet</string>
	</array>
</dict>
</plist>
