<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Just</string>
	<key>scopeName</key>
	<string>source.just</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#interpolate</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#scripts</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#assignments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#recipeDefinition</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>assignments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>^(export[\s]?)?([a-zA-Z_][a-zA-Z0-9_-]*)=</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.just</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.name.just</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>comment.line.just</string>
					<key>match</key>
					<string>^#[^!].*</string>
				</dict>
			</array>
		</dict>
		<key>interpolate</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>string.interpolated.just</string>
					<key>begin</key>
					<string>\{\{</string>
					<key>end</key>
					<string>\}\}</string>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.control.just</string>
					<key>match</key>
					<string>\b(arch|os|os_family|env_var|env_var_or_default)\b</string>
				</dict>
			</array>
		</dict>
		<key>recipeDefinition</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>^(@)?([a-zA-Z_][a-zA-Z0-9_-]*)([a-zA-Z0-9=\s_-`&apos;&quot;]*):([\sa-zA-Z0-9_-]*).*$</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.just</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.just</string>
						</dict>
						<key>3</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>name</key>
									<string>constant.character.escape.just</string>
									<key>match</key>
									<string>[\s]*[a-zA-Z0-9-_]*(=?)(.*)</string>
									<key>captures</key>
									<dict>
										<key>0</key>
										<dict>
											<key>name</key>
											<string>variable.name.just</string>
										</dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>constant.other.just</string>
										</dict>
										<key>2</key>
										<dict>
											<key>name</key>
											<string>variable.parameter.just</string>
										</dict>
									</dict>
								</dict>
							</array>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>support.type.property-name.just</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>scripts</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>support.type.property-name.just</string>
					<key>begin</key>
					<string>\s#\!</string>
					<key>end</key>
					<string>$</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>string.quoted.triple.just</string>
					<key>begin</key>
					<string>`</string>
					<key>end</key>
					<string>`</string>
				</dict>
				<dict>
					<key>name</key>
					<string>string.quoted.double.just</string>
					<key>begin</key>
					<string>&quot;</string>
					<key>end</key>
					<string>&quot;</string>
				</dict>
				<dict>
					<key>name</key>
					<string>string.quoted.single.just</string>
					<key>begin</key>
					<string>&apos;</string>
					<key>end</key>
					<string>&apos;</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>JUSTFILE</string>
		<string>Justfile</string>
		<string>justfile</string>
	</array>
</dict>
</plist>
