<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>KerboScript</string>
	<key>scopeName</key>
	<string>source.kerboscript</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>name</key>
			<string>constant.numeric.kerboscript</string>
			<key>match</key>
			<string>\b(([0-9]+\.?[0-9]*)|(\.[0-9]+))\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>string.quoted.double.kerboscript</string>
			<key>begin</key>
			<string>\&quot;</string>
			<key>end</key>
			<string>\&quot;</string>
		</dict>
		<dict>
			<key>name</key>
			<string>comment.line.double-slash.kerboscript</string>
			<key>begin</key>
			<string>//</string>
			<key>end</key>
			<string>\n</string>
		</dict>
		<dict>
			<key>name</key>
			<string>punctuation.terminator.kerboscript</string>
			<key>match</key>
			<string>(\.)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.control.conditional.kerboscript</string>
			<key>match</key>
			<string>\b(?i:(if|else|when|then|on))\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.control.repeat.kerboscript</string>
			<key>match</key>
			<string>\b(?i:(for|until))\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.control.statement.kerboscript</string>
			<key>match</key>
			<string>\b(?i:(break|preserve))\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.operator.logical.kerboscript</string>
			<key>match</key>
			<string>\b(?i:(and|or|not))\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.operator.comparison.kerboscript</string>
			<key>match</key>
			<string>(&lt;\=|&gt;\=|&lt;|&gt;|&lt;&gt;|\=)</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.operator.arithmetic.kerboscript</string>
			<key>match</key>
			<string>(\+|\-|\*|/|\^|\(|\))</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.constant.kerboscript</string>
			<key>match</key>
			<string>\b(?i:(e|g|pi))\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.constant.kerboscript</string>
			<key>match</key>
			<string>\b(?i:(true|false|red|green|blue|yellow|cyan|magenta|purple|white|black))\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.operator.assignment.kerboscript</string>
			<key>match</key>
			<string>\b(?i:(set|to|lock|unlock|declare|parameter|toggle|on|off))\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.modifier.kerboscript</string>
			<key>match</key>
			<string>\b(?i:(global|local|parameter))\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.kerboscript</string>
			<key>match</key>
			<string>\b(?i:(add|remove|stage|clearscreen|log|copy|rename|delete|edit|run|compile|reboot|shutdown|batch|deploy))\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.language.kerboscript</string>
			<key>match</key>
			<string>\b(?i:(rgb|rgba|waypoint|allwaypoints|nextnode|ship|soi|mapview|version|sessiontime|time|config|terminal|eta|addons))\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>variable.parameter.kerboscript</string>
			<key>match</key>
			<string>\b(?i:(major|minor))</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.language.kerboscript</string>
			<key>match</key>
			<string>\b(?i:(throttle|steering|wheelthrottle|wheelsteering|ship|target|encounter|alt|heading|prograde|retrograde|facing|maxthrust|velocity|geoposition|latitude|longitude|up|north|body|angularmomentum|angularvel|angularvelocity|commrange|mass|verticalspeed|surfacespeed|airspeed|vesselname|altitude|apoapsis|periapsis|sensor|srfprograde|srfrerograde|obt|status|vesselname))\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.language.kerboscript</string>
			<key>match</key>
			<string>\b(?i:(sas|rcs|gear|legs|chutes|lights|panels|brakes|abort|ag[1-9][0-9]|ag[0-9]))\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>variable.parameter.kerboscript</string>
			<key>match</key>
			<string>\:(?i:(tostring|hassuffix|suffixnames|isserializable|typename|istype|inheritance))\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>variable.parameter.kerboscript</string>
			<key>match</key>
			<string>\:(?i:(apoapsis|periapsis|radar))\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>variable.parameter.kerboscript</string>
			<key>match</key>
			<string>\:(?i:(apoapsis|periapsis|transition))\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.kerboscript</string>
			<key>match</key>
			<string>\b(?i:(list|bodies|targets|resources|parts|engines|sensors|elements|dockingports|files|volumes))\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.kerboscript</string>
			<key>match</key>
			<string>\b(?i:(r|q|heading|lookdirup|angleaxis|rotatefromto))\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>variable.parameter.kerboscript</string>
			<key>match</key>
			<string>\:(?i:(vector|forevector|topvector|upvector|starvector|rightvector|inverse))</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.kerboscript</string>
			<key>match</key>
			<string>\b(?i:(vdot|vectordotproduct|vcrs|vectorcrossproduct|vang|vectorangle|vxcl|vectorexclude))\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>variable.parameter.kerboscript</string>
			<key>match</key>
			<string>\:(?i:(x|y|z|normalized|sqrmagnitude|direction|vec))\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>variable.parameter.kerboscript</string>
			<key>match</key>
			<string>\:(?i:(lat|lng|distance|terrainheight|heading|bearing|position|altitudeposition))</string>
		</dict>
		<dict>
			<key>name</key>
			<string>variable.parameter.kerboscript</string>
			<key>match</key>
			<string>\:(?i:(name|apoapsis|periapsis|body|period|inclination|eccentricity|semimajoraxis|semiminoraxis|lan|longitudeofascendingnode|argumentofperiapsis|trueanomaly|meananomalyatepoch|transition|position|velocity|nextpatch|hasnextpatch))\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>variable.parameter.kerboscript</string>
			<key>match</key>
			<string>\:(?i:(orbit|surface|name|body|hasbody|hasorbit|hasobt|obt|up|north|prograde|srfprograde|retrograde|srfretrograde|position|velocity|distance|direction|latitude|longitude|altitude|geoposition|patches))\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>variable.parameter.kerboscript</string>
			<key>match</key>
			<string>\:(?i:(body|exists|oxygen|scale|sealevelpressure|height))\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>variable.parameter.kerboscript</string>
			<key>match</key>
			<string>\:(?i:(name|description|mass|altitude|rotationperiod|radius|mu|atm|angularvel|geopositionof|altitudeof))\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>variable.parameter.kerboscript</string>
			<key>match</key>
			<string>\:(?i:(name|amount|capacity|parts))\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>variable.parameter.kerboscript</string>
			<key>match</key>
			<string>\:(?i:(aquirerange|aquireforce|aquire|torque|reengageddistance|dockedshipname|portfacing|state|targetable))\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.kerboscript</string>
			<key>match</key>
			<string>\:(?i:(undock))</string>
		</dict>
		<dict>
			<key>name</key>
			<string>variable.parameter.kerboscript</string>
			<key>match</key>
			<string>\:(?i:(thrustlimit|maxthrust|thrust|fuelflow|isp|flameout|ignition|allowrestart|allowshutdown|throttlelock))\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.kerboscript</string>
			<key>match</key>
			<string>\:(?i:(activate|shutdown))</string>
		</dict>
		<dict>
			<key>name</key>
			<string>variable.parameter.kerboscript</string>
			<key>match</key>
			<string>\:(?i:(range|responsespeed|pitchangle|yawangle|rollangle|lock))\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>variable.parameter.kerboscript</string>
			<key>match</key>
			<string>\:(?i:(deltav|burnvector|eta|prograde|radialout|normal|orbit))\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>variable.parameter.kerboscript</string>
			<key>match</key>
			<string>\:(?i:(name|title|mass|drymass|wetmass|tag|controlfrom|stage|uid|rotation|position|facing|resources|targetable|ship|modules|allmodules|parent|hasparent|hasphysics|children))\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.kerboscript</string>
			<key>match</key>
			<string>\:(?i:(getmodule))</string>
		</dict>
		<dict>
			<key>name</key>
			<string>variable.parameter.kerboscript</string>
			<key>match</key>
			<string>\:(?i:(name|part|allfields|allevents|allactions|hasfield|hasevent|hasaction))\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.kerboscript</string>
			<key>match</key>
			<string>\b(?i:(getfield|setfield|doevent|doaction))</string>
		</dict>
		<dict>
			<key>name</key>
			<string>variable.parameter.kerboscript</string>
			<key>match</key>
			<string>\:(?i:(active|type|readout|powerconsumption))\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.kerboscript</string>
			<key>match</key>
			<string>\b(?i:(toggle))</string>
		</dict>
		<dict>
			<key>name</key>
			<string>variable.parameter.kerboscript</string>
			<key>match</key>
			<string>\:(?i:(ready|number|resources))\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>variable.parameter.kerboscript</string>
			<key>match</key>
			<string>\:(?i:(control|bearing|heading|maxthrust|facing|mass|wetmass|drymass|verticalspeed|surfacespeed|airspeeed|termvelocity|shipname|name|angularmomentum|angularvel|sensors|loaded|patches|rootpart|parts|resources|partsnamed|partstitled|partstagged|partsdubbed|modulesnamed|partsingroup|modulesingroup|allpartstagged))\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>variable.parameter.kerboscript</string>
			<key>match</key>
			<string>\:(?i:(acc|pres|temp|grav|light))\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>variable.parameter.kerboscript</string>
			<key>match</key>
			<string>\:(?i:(name|amount|capacity|toggleable|enabled))\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>variable.parameter.kerboscript</string>
			<key>match</key>
			<string>\:(?i:(name|body|geoposition|position|altitude|agl|nearsurface|grounded|index|clustered))\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>variable.parameter.kerboscript</string>
			<key>match</key>
			<string>\:(?i:(r|red|g|green|b|blue|a|alpha|html|hex))\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.kerboscript</string>
			<key>match</key>
			<string>\b(?i:(positionat|velocityat|orbitat))</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.kerboscript</string>
			<key>match</key>
			<string>\b(?i:(abs|ceiling|floor|ln|log10|mod|min|max|round|sqrt|sin|cos|tan|arcsin|arccos|arctan|arctan2))\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.type.kerboscript</string>
			<key>match</key>
			<string>\b(?i:(v|vector|direction|latlng))\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.other.kerboscript</string>
			<key>match</key>
			<string>\b(?i:(print|at|from|volume|in|all|readjson|writejson))\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.function.kerboscript</string>
			<key>match</key>
			<string>\b(?i:(function))\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>variable.parameter.kerboscript</string>
			<key>match</key>
			<string>\:(?i:(width|height|reverse|visualbeep|brightness|charwidth|charheight))\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>variable.parameter.kerboscript</string>
			<key>match</key>
			<string>\:(?i:(clock|calendar|second|minute|hour|day|year|seconds))\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.type.kerboscript</string>
			<key>match</key>
			<string>\b(?i:(lexicon|list|queue|range|stack))\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>variable.parameter.kerboscript</string>
			<key>match</key>
			<string>\:(?i:(add|casesensitive|case|clear|copy|dump|haskey|hasvalue|keys|values|length|remove))\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>variable.parameter.kerboscript</string>
			<key>match</key>
			<string>\:(?i:(add|insert|clear|copy|sublist|join|remove))\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>variable.parameter.kerboscript</string>
			<key>match</key>
			<string>\:(?i:(push|pop|peek|clear|copy))\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>variable.parameter.kerboscript</string>
			<key>match</key>
			<string>\:(?i:(start|stop|step))\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>variable.parameter.kerboscript</string>
			<key>match</key>
			<string>\:(?i:(push|pop|peek|clear|copy))\b</string>
		</dict>
	</array>
	<key>fileTypes</key>
	<array>
		<string>ks</string>
	</array>
</dict>
</plist>
