<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>KiCad Schematic</string>
	<key>scopeName</key>
	<string>source.pcb.schematic</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>contentName</key>
			<string>source.eagle.pcb.board</string>
			<key>begin</key>
			<string>\A(?=&lt;\?xml\s+version=&quot;[\d.]+&quot;\s)</string>
			<key>end</key>
			<string>(?=A)B</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.xml</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>contentName</key>
			<string>source.pcb.sexp</string>
			<key>begin</key>
			<string>\A\s*(?=\(kicad_sch(?:\s|$|\())</string>
			<key>end</key>
			<string>(?=A)B</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.pcb.sexp</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>contentName</key>
			<string>source.scheme</string>
			<key>begin</key>
			<string>\A\s*(?=;|\()</string>
			<key>end</key>
			<string>(?=A)B</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.scheme</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.header.pcb.schematic</string>
			<key>begin</key>
			<string>^\s*(EESchema(?:\s+Schematic|-(?:DOCLIB|LIBRARY))\s+\S+.*)\s*$</string>
			<key>end</key>
			<string>(?&lt;=\$EndDescr)(?=\s|$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>^\s*(LIBS(:))\s*(.+)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.assignment.libs.pcb.schematic</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.key-value.pcb.schematic</string>
						</dict>
						<key>3</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>name</key>
									<string>punctuation.delimiter.list.comma.pcb.schematic</string>
									<key>match</key>
									<string>,</string>
								</dict>
								<dict>
									<key>name</key>
									<string>constant.other.lib-name.pcb.schematic</string>
									<key>match</key>
									<string>[^\s,]+</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.eelayer.pcb.schematic</string>
					<key>begin</key>
					<string>^\s*(EELAYER)((?:\s+[-+]?[\d.]+)*)\s*$</string>
					<key>end</key>
					<string>^\s*(EELAYER)\s+(END)\s*$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.var.pcb.schematic</string>
						</dict>
						<key>2</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#numbers</string>
								</dict>
							</array>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.var.pcb.schematic</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.pcb.schematic</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.description.pcb.schematic</string>
					<key>begin</key>
					<string>^\s*((\$)Descr)(?=\s)</string>
					<key>end</key>
					<string>^\s*((\$)EndDescr)(?=\s)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\G\s+([A-E][0-9]?)(?=\s)</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>constant.language.paper-size.pcb.schematic</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.section.pcb.schematic</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.begin.pcb.schematic</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.section.pcb.schematic</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.end.pcb.schematic</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.header.pcb.schematic</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.header.pcb.schematic</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.header.pcb.schematic</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.bitmap.pcb.schematic</string>
			<key>begin</key>
			<string>^\s*((\$)Bitmap)\s*$</string>
			<key>end</key>
			<string>^\s*((\$)EndBitmap)(?=\s|$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>contentName</key>
					<string>string.unquoted.heredoc.bytestream.pcb.schematic</string>
					<key>begin</key>
					<string>^\s*(Data)\s*$</string>
					<key>end</key>
					<string>^\s*(EndData)\s*$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>comment.ignored.pcb.schematic</string>
							<key>match</key>
							<string>\s+((\$)EndBitmap)\s*$</string>
						</dict>
						<dict>
							<key>name</key>
							<string>invalid.illegal.syntax.pcb.schematic</string>
							<key>match</key>
							<string>(?&lt;=\s|^)(?![A-Fa-f0-9]{2}(?:\s|$))(\S+)</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.data.section.begin.pcb.schematic</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.data.section.end.pcb.schematic</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.section.pcb.schematic</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.begin.pcb.schematic</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.section.pcb.schematic</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.end.pcb.schematic</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.component.${1:/downcase}.pcb.schematic</string>
			<key>begin</key>
			<string>^\s*(DEF|DRAW)(?:\s+(\S+)\s+(.+))?\s*$</string>
			<key>end</key>
			<string>^\s*(END\1)(?=\s|$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#params</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.class.definition.pcb.schematic</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.var.pcb.schematic</string>
				</dict>
				<key>3</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#params</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.class.definition.pcb.schematic</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.aliases.pcb.schematic</string>
			<key>match</key>
			<string>^\s*(ALIAS)\s+(.+)\s*$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.class.alias.pcb.schematic</string>
				</dict>
				<key>2</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#quotedString</string>
						</dict>
						<dict>
							<key>name</key>
							<string>entity.name.var.pcb.schematic</string>
							<key>match</key>
							<string>\S+</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.${3:/downcase}.pcb.schematic</string>
			<key>begin</key>
			<string>^\s*((\$)([A-Za-z]\w+))\s*$</string>
			<key>end</key>
			<string>^\s*((\$)[Ee]nd\3)(?=\s|$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.section.pcb.schematic</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.begin.pcb.schematic</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.section.pcb.schematic</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.end.pcb.schematic</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.wire.pcb.schematic</string>
			<key>match</key>
			<string>^\s*(Wire)\s+(Wire|Bus|Line)\s+(Line)\s*$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.var.pcb.schematic</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.pcb.schematic</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.language.other.pch.schematic</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.text.pcb.schematic</string>
			<key>begin</key>
			<string>^\s*(Text)\s+(\w+)\s+(.+)\s+(?:(~)|(\w+))\s*$</string>
			<key>end</key>
			<string>^\s*(\S.*)$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.var.pcb.schematic</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.pcb.schematic</string>
				</dict>
				<key>3</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
				<key>4</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tilde</string>
						</dict>
					</array>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>constant.language.other.pch.schematic</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.herestring.pcb.schematic</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*([A-Za-z]\w*)(?=\s)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#params</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.var.pcb.schematic</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>include</key>
			<string>#shared</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>match</key>
			<string>^\s*((#).*$)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.number-sign.pcb.schematic</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.pcb.board</string>
				</dict>
			</dict>
		</dict>
		<key>lowerCaseName</key>
		<dict>
			<key>name</key>
			<string>variable.parameter.identifier.pcb.schematic</string>
			<key>match</key>
			<string>(?&lt;=\s)[A-Za-z_][-\w]+(?=\s|$)</string>
		</dict>
		<key>numbers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.numeric.integer.decimal.pcb.schematic</string>
					<key>match</key>
					<string>(?&lt;![-\w])[-+]?\d+(?=\s|$)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.float.decimal.pcb.schematic</string>
					<key>match</key>
					<string>(?&lt;![-\w])[-+]?\d*\.\d+</string>
				</dict>
			</array>
		</dict>
		<key>params</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#upperCaseName</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lowerCaseName</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>quotedString</key>
		<dict>
			<key>name</key>
			<string>string.quoted.double.pcb.schematic</string>
			<key>begin</key>
			<string>&quot;</string>
			<key>end</key>
			<string>&quot;|^|$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.pcb.sexp#stringInnards</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.pcb.schematic</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.pcb.schematic</string>
				</dict>
			</dict>
		</dict>
		<key>shared</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tilde</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#quotedString</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numbers</string>
				</dict>
			</array>
		</dict>
		<key>tilde</key>
		<dict>
			<key>name</key>
			<string>keyword.operator.pcb.schematic</string>
			<key>match</key>
			<string>~</string>
		</dict>
		<key>upperCaseName</key>
		<dict>
			<key>name</key>
			<string>constant.language.other.pcb.schematic</string>
			<key>match</key>
			<string>(?&lt;=\s)([+#])?[A-Z0-9_]+(?:\s|$)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.constant.pcb.schematic</string>
				</dict>
			</dict>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>kicad_sch</string>
		<string>sch</string>
	</array>
</dict>
</plist>
