<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Less</string>
	<key>scopeName</key>
	<string>source.css.less</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\.[_a-zA-Z][a-zA-Z0-9_-]*(?=\())</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.class.mixin.css</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>((\.)([_a-zA-Z]|(@{[a-zA-Z0-9_-]+}))[a-zA-Z0-9_-]*)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.class.css</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.entity.css</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.other.interpolation.less</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>(&amp;)[a-zA-Z0-9_-]*</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.parent-selector.css</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.entity.css</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>begin</key>
			<string>(format|local|url|attr|counter|counters)\s*(\()</string>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>string.quoted.single.css</string>
					<key>begin</key>
					<string>&apos;</string>
					<key>end</key>
					<string>&apos;</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>constant.character.escape.css</string>
							<key>match</key>
							<string>\\.</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.css</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.css</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>string.quoted.double.css</string>
					<key>begin</key>
					<string>&quot;</string>
					<key>end</key>
					<string>&quot;</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>constant.character.escape.css</string>
							<key>match</key>
							<string>\\(\d{1,6}|.)</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.css</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.css</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>variable.parameter.misc.css</string>
					<key>match</key>
					<string>[^&apos;&quot;) \t]+</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.misc.css</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.function.css</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.function.css</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.other.rgb-value.css</string>
			<key>match</key>
			<string>(#)([0-9a-fA-F]{3}|[0-9a-fA-F]{6})\b(?!.*?(?&lt;!@){)</string>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.selector.css</string>
			<key>match</key>
			<string>((#)([_a-zA-Z]|(@{[a-zA-Z0-9_-]+}))[a-zA-Z0-9_-]*)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.id</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.entity.css</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.other.interpolation.less</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>comment.block.css</string>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.begin.css</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.end.css</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>include</key>
			<string>source.css#numeric-values</string>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.attribute-selector.css</string>
			<key>match</key>
			<string>(?i)(\[)\s*(-?[_a-z\\[[:^ascii:]]][_a-z0-9\-\\[[:^ascii:]]]*)(?:\s*([~|^$*]?=)\s*(?:(-?[_a-z\\[[:^ascii:]]][_a-z0-9\-\\[[:^ascii:]]]*)|((?&gt;([&apos;&quot;])(?:[^\\]|\\.)*?(\6)))))?\s*(\])</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.begin.entity.css</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.attribute.css</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.operator.css</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.attribute-value.css</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.attribute-value.css</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.css</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.css</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.end.entity.css</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.at-rule.import.css</string>
			<key>begin</key>
			<string>((@)import\b)</string>
			<key>end</key>
			<string>;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.control.import.option.less</string>
					<key>match</key>
					<string>(?&lt;=\(|,|\s)\b(reference|optional|once|multiple|less|inline)\b(?=\)|,)</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#brace_round</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.css#commas</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.at-rule.import.less</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.keyword.less</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.terminator.rule.css</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.at-rule.fontface.css</string>
			<key>match</key>
			<string>^\s*((@)font-face\b)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.at-rule.fontface.css</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.keyword.css</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.at-rule.media.css</string>
			<key>match</key>
			<string>^\s*((@)media\b)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.at-rule.media.css</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.keyword.css</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>include</key>
			<string>source.css#media-features</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.constant.media-type.media.css</string>
			<key>match</key>
			<string>\b(tv|tty|screen|projection|print|handheld|embossed|braille|aural|all)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.constant.property-value.media-property.media.css</string>
			<key>match</key>
			<string>\b(portrait|landscape)\b</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\.[a-zA-Z0-9_-]+)\s*(;|\()</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.less</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^[ \t]+)?(?=//)</string>
			<key>end</key>
			<string>(?!\G)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>comment.line.double-slash.less</string>
					<key>begin</key>
					<string>//</string>
					<key>end</key>
					<string>\n</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.less</string>
						</dict>
					</dict>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.comment.leading.less</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>variable.other.less</string>
			<key>match</key>
			<string>(@|\-\-)[\w-]+(?=\s*)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.less</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>include</key>
			<string>#variable_interpolation</string>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.property-list.css</string>
			<key>begin</key>
			<string>{</string>
			<key>end</key>
			<string>}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.css#pseudo-elements</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.css#pseudo-classes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.css#tag-names</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.css#commas</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable_interpolation</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.css#property-names</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#property_values</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.property-list.begin.bracket.curly.css</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.property-list.end.bracket.curly.css</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.other.important.css</string>
			<key>match</key>
			<string>\!\s*important</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.operator.less</string>
			<key>match</key>
			<string>\*|\/|\-|\+|~|=|&lt;=|&gt;=|&lt;|&gt;</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.control.logical.operator.less</string>
			<key>match</key>
			<string>\b(not|and|when)\b</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.css#tag-names</string>
		</dict>
		<dict>
			<key>name</key>
			<string>entity.name.tag.custom.css</string>
			<key>match</key>
			<string>(?&lt;![\w-])[a-z][\w&amp;&amp;[^A-Z]]*+-[\w-&amp;&amp;[^A-Z]]+</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.css#pseudo-elements</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.css#pseudo-classes</string>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.brace.curly.css</string>
			<key>match</key>
			<string>(\{)(\})</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.property-list.begin.css</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.property-list.end.css</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.brace.curly.css</string>
			<key>match</key>
			<string>\{|\}</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#brace_round</string>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.brace.square.less</string>
			<key>match</key>
			<string>\[|\]</string>
		</dict>
		<dict>
			<key>name</key>
			<string>punctuation.terminator.rule.css</string>
			<key>match</key>
			<string>;</string>
		</dict>
		<dict>
			<key>name</key>
			<string>punctuation.separator.key-value.css</string>
			<key>match</key>
			<string>:</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.language.boolean.less</string>
			<key>match</key>
			<string>\btrue\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.default.less</string>
			<key>match</key>
			<string>\bdefault\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.type-checking.less</string>
			<key>match</key>
			<string>\b(isurl|isstring|isnumber|iskeyword|iscolor)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.unit-checking.less</string>
			<key>match</key>
			<string>\b(isunit|ispixel|ispercentage|isem)\b</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.css#property-keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.css#color-keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.css#commas</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#less_builtin_functions</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.css#functions</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>brace_round</key>
		<dict>
			<key>name</key>
			<string>meta.brace.round.css</string>
			<key>match</key>
			<string>\(|\)</string>
		</dict>
		<key>less_builtin_functions</key>
		<dict>
			<key>name</key>
			<string>support.function.any-method.builtin.less</string>
			<key>match</key>
			<string>\b(abs|acos|alpha|argb|asin|atan|average|blue|calc|ceil|color|contrast|convert|convert|cos|darken|data-uri|desaturate|difference|e|escape|exclusion|extract|fade|fadein|fadeout|floor|format|green|greyscale|hardlight|hsl|hsla|hsv|hsva|hsvhue|hsvsaturation|hsvvalue|hue|length|lighten|lightness|luma|max|min|mix|mod|multiply|negation|overlay|percentage|pi|pow|red|replace|round|saturate|saturation|screen|sin|softlight|spin|sqrt|tan|unit)\b</string>
		</dict>
		<key>property_values</key>
		<dict>
			<key>contentName</key>
			<string>meta.property-value.css</string>
			<key>begin</key>
			<string>(?&lt;!&amp;)(:)\s*(?!(\s*{))(?!.*(?&lt;!@){)</string>
			<key>end</key>
			<string>\s*(;)|\s*(?=})</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>support.function.any-method.builtin.url.css</string>
					<key>begin</key>
					<string>url(\()</string>
					<key>end</key>
					<string>\)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#strings</string>
						</dict>
						<dict>
							<key>name</key>
							<string>string.url.css</string>
							<key>match</key>
							<string>(\b|\.{0,2}/)[^)]*\b</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.brace.round.css</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.brace.round.css</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>include</key>
					<string>source.css#property-keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.css#color-keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.css#commas</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#less_builtin_functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.css#functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.key-value.css</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.terminator.rule.css</string>
				</dict>
			</dict>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>string.quoted.double.css</string>
					<key>begin</key>
					<string>&quot;</string>
					<key>end</key>
					<string>&quot;</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>constant.character.escape.css</string>
							<key>match</key>
							<string>\\([0-9A-Fa-f]{1,6}|.)</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#variable_interpolation</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.css</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.css</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>string.quoted.single.css</string>
					<key>begin</key>
					<string>&apos;</string>
					<key>end</key>
					<string>&apos;</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>constant.character.escape.css</string>
							<key>match</key>
							<string>\\([0-9A-Fa-f]{1,6}|.)</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#variable_interpolation</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.css</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.css</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>variable_interpolation</key>
		<dict>
			<key>name</key>
			<string>variable.other.interpolation.less</string>
			<key>match</key>
			<string>@{[a-zA-Z0-9_-]+}</string>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>less</string>
	</array>
</dict>
</plist>
