<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Lex</string>
	<key>scopeName</key>
	<string>source.lex</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#main</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>comment.block.lex</string>
					<key>begin</key>
					<string>/\*</string>
					<key>end</key>
					<string>\*/</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.begin.comment.lex</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.end.comment.lex</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>comment.line.double-slash.lex</string>
					<key>begin</key>
					<string>//</string>
					<key>end</key>
					<string>(?=$)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.lex</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>definition</key>
		<dict>
			<key>name</key>
			<string>meta.definition.lex</string>
			<key>begin</key>
			<string>^\s*([A-Za-z_][A-Za-z0-9_-]*)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.pattern.lex</string>
					<key>match</key>
					<string>(?&lt;=\s)\S.*</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.lex.regexp</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.definition.lex</string>
				</dict>
			</dict>
		</dict>
		<key>definitions</key>
		<dict>
			<key>name</key>
			<string>meta.definitions.lex</string>
			<key>begin</key>
			<string>\A(?!\s*%%)</string>
			<key>end</key>
			<string>^(?=\s*(?:%%|(?:package|import)\s+\w))</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#directives</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#passthrough</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#definition</string>
				</dict>
			</array>
		</dict>
		<key>directives</key>
		<dict>
			<key>name</key>
			<string>meta.directive.lex</string>
			<key>begin</key>
			<string>^\s*((%)\w+)(?=\s|$)</string>
			<key>end</key>
			<string>(?=$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.other.lex</string>
					<key>match</key>
					<string>\S+</string>
				</dict>
			</array>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.directive.lex</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.directive.lex</string>
				</dict>
			</dict>
		</dict>
		<key>jflex</key>
		<dict>
			<key>name</key>
			<string>meta.jflex.lex</string>
			<key>begin</key>
			<string>^(?=\s*(?:package|import)\s+\w)</string>
			<key>end</key>
			<string>(?=A)B</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.jflex</string>
				</dict>
			</array>
		</dict>
		<key>main</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#jflex</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#definitions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#rules</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.c++</string>
				</dict>
			</array>
		</dict>
		<key>passthrough</key>
		<dict>
			<key>name</key>
			<string>meta.code-chunk.lex</string>
			<key>begin</key>
			<string>^%{</string>
			<key>end</key>
			<string>^%}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.c++</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.begin.lex</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.end.lex</string>
				</dict>
			</dict>
		</dict>
		<key>rule.action</key>
		<dict>
			<key>name</key>
			<string>meta.action.lex</string>
			<key>begin</key>
			<string>(?&lt;!^)(?=\S)</string>
			<key>end</key>
			<string>(?=\s*$|^)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?={)</string>
					<key>end</key>
					<string>(?&lt;=})</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.c++</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>([^{\s][^{]*?)\s*$</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.c++</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>rule.pattern</key>
		<dict>
			<key>name</key>
			<string>meta.pattern.lex</string>
			<key>begin</key>
			<string>(?&lt;=^|\n)(?=\S)</string>
			<key>end</key>
			<string>(?=\s|$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.lex.regexp</string>
				</dict>
			</array>
		</dict>
		<key>rules</key>
		<dict>
			<key>begin</key>
			<string>^\s*(%%)\s*(?:$\s*|(?=/\*))</string>
			<key>end</key>
			<string>^\s*(%%)\s*(?:$\s*|(?=/\*))</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#passthrough</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#rule.pattern</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#rule.action</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.section.begin.lex</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.section.end.lex</string>
				</dict>
			</dict>
		</dict>
		<key>user-code</key>
		<dict>
			<key>name</key>
			<string>meta.user-code.lex</string>
			<key>contentName</key>
			<string>source.embedded.cpp</string>
			<key>begin</key>
			<string>(?&lt;=^%%|\s%%)</string>
			<key>end</key>
			<string>(?=A)B</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.c++</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>l</string>
		<string>lex</string>
	</array>
</dict>
</plist>
