<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>ligo</string>
	<key>scopeName</key>
	<string>source.ligo</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#string</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#block_comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#line_comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#attribute</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#macro</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#controlkeywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#function</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operators</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#typedefinition</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#module</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#identifierconstructor</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constorvar</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#numericliterals</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>attribute</key>
		<dict>
			<key>name</key>
			<string>keyword.control.attribute.ligo</string>
			<key>match</key>
			<string>\[@.*\]</string>
		</dict>
		<key>block_comment</key>
		<dict>
			<key>name</key>
			<string>comment.block.ligo</string>
			<key>begin</key>
			<string>\(\*</string>
			<key>end</key>
			<string>\*\)</string>
		</dict>
		<key>constorvar</key>
		<dict>
			<key>match</key>
			<string>\b(const|var)\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.ligo</string>
				</dict>
			</dict>
		</dict>
		<key>controlkeywords</key>
		<dict>
			<key>name</key>
			<string>keyword.control.ligo</string>
			<key>match</key>
			<string>\b(case|with|if|then|else|assert|failwith|begin|end|in|is|from|skip|block|contains|to|step|of|while|for|remove)\b</string>
		</dict>
		<key>function</key>
		<dict>
			<key>match</key>
			<string>\b(function)\b\s*\b([a-zA-Z$_][a-zA-Z0-9$_]*)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.ligo</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.ligo</string>
				</dict>
			</dict>
		</dict>
		<key>identifierconstructor</key>
		<dict>
			<key>match</key>
			<string>\b([A-Z][a-zA-Z0-9_$]*)\s+</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.enummember.ligo</string>
				</dict>
			</dict>
		</dict>
		<key>line_comment</key>
		<dict>
			<key>name</key>
			<string>comment.block.ligo</string>
			<key>match</key>
			<string>\/\/.*$</string>
		</dict>
		<key>macro</key>
		<dict>
			<key>name</key>
			<string>meta.preprocessor.ligo</string>
			<key>match</key>
			<string>^\#[a-zA-Z]+</string>
		</dict>
		<key>module</key>
		<dict>
			<key>match</key>
			<string>\b([A-Z][a-zA-Z0-9_$]*)\.([a-z][a-zA-Z0-9_$]*)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.class.ligo</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.var.ligo</string>
				</dict>
			</dict>
		</dict>
		<key>numericliterals</key>
		<dict>
			<key>name</key>
			<string>constant.numeric.ligo</string>
			<key>match</key>
			<string>(\+|\-)?[0-9]+(n|tz|tez|mutez|)\b</string>
		</dict>
		<key>operators</key>
		<dict>
			<key>name</key>
			<string>keyword.operator.ligo</string>
			<key>match</key>
			<string>\s+(\-|\+|mod|land|lor|lxor|lsl|lsr|&amp;&amp;|\|\||&gt;|=/=|&lt;=|=&gt;|&lt;|&gt;)\s+</string>
		</dict>
		<key>string</key>
		<dict>
			<key>name</key>
			<string>string.quoted.double.ligo</string>
			<key>begin</key>
			<string>\&quot;</string>
			<key>end</key>
			<string>\&quot;</string>
		</dict>
		<key>typedefinition</key>
		<dict>
			<key>name</key>
			<string>entity.name.type.ligo</string>
			<key>match</key>
			<string>\b(type)\b</string>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>ligo</string>
	</array>
</dict>
</plist>
