<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Logos</string>
	<key>scopeName</key>
	<string>source.logos</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>name</key>
			<string>keyword.source.logos</string>
			<key>match</key>
			<string>%(init|hook|subclass|group|class|new|ctor|end|config|orig|log|hookf|dtor|property|c)</string>
		</dict>
		<dict>
			<key>match</key>
			<string>%c\(([A-Za-z$_]+)\)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.logos</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>include</key>
			<string>source.objc</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.c++</string>
		</dict>
	</array>
	<key>fileTypes</key>
	<array>
		<string>xm</string>
		<string>x</string>
		<string>xi</string>
	</array>
</dict>
</plist>
