<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Marko</string>
	<key>scopeName</key>
	<string>text.marko</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>name</key>
			<string>meta.embedded.css</string>
			<key>contentName</key>
			<string>source.css</string>
			<key>begin</key>
			<string>^\s*(style)\s+(\{)</string>
			<key>end</key>
			<string>\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.css</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.marko.css</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.begin.marko.css</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.end.marko.css</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.embedded.less</string>
			<key>contentName</key>
			<string>source.less</string>
			<key>begin</key>
			<string>^\s*(style)\.(less)\s+(\{)</string>
			<key>end</key>
			<string>\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.css.less</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.marko.css</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.marko.css</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.begin.marko.css</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.end.marko.css</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.embedded.scss</string>
			<key>contentName</key>
			<string>source.scss</string>
			<key>begin</key>
			<string>^\s*(style)\.(scss)\s+(\{)</string>
			<key>end</key>
			<string>\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.css.scss</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.marko.css</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.marko.css</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.begin.marko.css</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.end.marko.css</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.embedded.js</string>
			<key>contentName</key>
			<string>source.js</string>
			<key>begin</key>
			<string>^\s*(?:(static )|(?=(?:class|import|export) ))</string>
			<key>end</key>
			<string>(?=\n|$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#javascript-statement</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.static.marko</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>include</key>
			<string>#content-concise-mode</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>attrs</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.marko-attribute</string>
					<key>begin</key>
					<string>(?:\s+|,)(?:(key|on[a-zA-Z0-9_$-]+|[a-zA-Z0-9_$]+Change|no-update(?:-body)?(?:-if)?)|([a-zA-Z0-9_$][a-zA-Z0-9_$-]*))(:[a-zA-Z0-9_$][a-zA-Z0-9_$-]*)?</string>
					<key>end</key>
					<string>(?=.|$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#html-args-or-method</string>
						</dict>
						<dict>
							<key>name</key>
							<string>meta.embedded.js</string>
							<key>contentName</key>
							<string>source.js</string>
							<key>begin</key>
							<string>\s*(:?=)\s*</string>
							<key>end</key>
							<string>(?=.|$)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#javascript-expression</string>
								</dict>
							</array>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>source.js</string>
										</dict>
									</array>
								</dict>
							</dict>
							<key>applyEndPatternLast</key>
							<true />
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.type.attribute-name.marko</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.marko</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.function.attribute-name.marko</string>
						</dict>
					</dict>
					<key>applyEndPatternLast</key>
					<true />
				</dict>
				<dict>
					<key>name</key>
					<string>meta.marko-spread-attribute</string>
					<key>contentName</key>
					<string>source.js</string>
					<key>begin</key>
					<string>(?:\s+|,)\.\.\.</string>
					<key>end</key>
					<string>(?=.|$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#javascript-expression</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.spread.marko</string>
						</dict>
					</dict>
					<key>applyEndPatternLast</key>
					<true />
				</dict>
				<dict>
					<key>begin</key>
					<string>\s*(,(?!,))</string>
					<key>end</key>
					<string>(?!\S)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.js</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>include</key>
					<string>#javascript-comment-multiline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#invalid</string>
				</dict>
			</array>
		</dict>
		<key>concise-html-block</key>
		<dict>
			<key>name</key>
			<string>meta.section.marko-html-block</string>
			<key>begin</key>
			<string>\s*(--+)\s*$</string>
			<key>end</key>
			<string>\1</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#content-html-mode</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.begin.marko</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.end.marko</string>
				</dict>
			</dict>
		</dict>
		<key>concise-html-line</key>
		<dict>
			<key>name</key>
			<string>meta.section.marko-html-line</string>
			<key>match</key>
			<string>\s*(--+)(?=\s+\S)(.*$)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.begin.marko</string>
				</dict>
				<key>2</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#html-comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#tag-html</string>
						</dict>
						<dict>
							<key>name</key>
							<string>string</string>
							<key>match</key>
							<string>\\.</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#placeholder</string>
						</dict>
						<dict>
							<key>name</key>
							<string>string</string>
							<key>match</key>
							<string>.+?</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>concise-open-tag-content</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-before-attrs</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\s*\[</string>
					<key>end</key>
					<string>]</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#attrs</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#invalid</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.scope.begin.marko</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.scope.end.marko</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?!^)(?= )</string>
					<key>end</key>
					<string>(?=--)|(?&lt;!,)(?=\n)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#attrs</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#invalid</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>concise-script-block</key>
		<dict>
			<key>name</key>
			<string>meta.section.marko-script-block</string>
			<key>begin</key>
			<string>(\s+)(--+)\s*$</string>
			<key>end</key>
			<string>(\2)|(?=^(?!\1)\s*\S)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#content-embedded-script</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.begin.marko</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.end.marko</string>
				</dict>
			</dict>
		</dict>
		<key>concise-script-line</key>
		<dict>
			<key>name</key>
			<string>meta.section.marko-script-line</string>
			<key>begin</key>
			<string>\s*(--+)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#content-embedded-script</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.begin.marko</string>
				</dict>
			</dict>
			<key>applyEndPatternLast</key>
			<true />
		</dict>
		<key>concise-style-block</key>
		<dict>
			<key>name</key>
			<string>meta.section.marko-style-block</string>
			<key>contentName</key>
			<string>source.css</string>
			<key>begin</key>
			<string>(\s+)(--+)\s*$</string>
			<key>end</key>
			<string>(\2)|(?=^(?!\1)\s*\S)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#content-embedded-style</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.begin.marko</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.end.marko</string>
				</dict>
			</dict>
		</dict>
		<key>concise-style-block-less</key>
		<dict>
			<key>name</key>
			<string>meta.section.marko-style-block</string>
			<key>contentName</key>
			<string>source.less</string>
			<key>begin</key>
			<string>(\s+)(--+)\s*$</string>
			<key>end</key>
			<string>(\2)|(?=^(?!\1)\s*\S)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#content-embedded-style-less</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.begin.marko</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.end.marko</string>
				</dict>
			</dict>
		</dict>
		<key>concise-style-block-scss</key>
		<dict>
			<key>name</key>
			<string>meta.section.marko-style-block</string>
			<key>contentName</key>
			<string>source.scss</string>
			<key>begin</key>
			<string>(\s+)(--+)\s*$</string>
			<key>end</key>
			<string>(\2)|(?=^(?!\1)\s*\S)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#content-embedded-style-scss</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.begin.marko</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.end.marko</string>
				</dict>
			</dict>
		</dict>
		<key>concise-style-line</key>
		<dict>
			<key>name</key>
			<string>meta.section.marko-style-line</string>
			<key>contentName</key>
			<string>source.css</string>
			<key>begin</key>
			<string>\s*(--+)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#content-embedded-style</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.begin.marko</string>
				</dict>
			</dict>
			<key>applyEndPatternLast</key>
			<true />
		</dict>
		<key>concise-style-line-less</key>
		<dict>
			<key>name</key>
			<string>meta.section.marko-style-line</string>
			<key>contentName</key>
			<string>source.less</string>
			<key>begin</key>
			<string>\s*(--+)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#content-embedded-style-less</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.begin.marko</string>
				</dict>
			</dict>
			<key>applyEndPatternLast</key>
			<true />
		</dict>
		<key>concise-style-line-scss</key>
		<dict>
			<key>name</key>
			<string>meta.section.marko-style-line</string>
			<key>contentName</key>
			<string>source.scss</string>
			<key>begin</key>
			<string>\s*(--+)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#content-embedded-style-scss</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.begin.marko</string>
				</dict>
			</dict>
			<key>applyEndPatternLast</key>
			<true />
		</dict>
		<key>content-concise-mode</key>
		<dict>
			<key>name</key>
			<string>meta.marko-concise-content</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#scriptlet</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#javascript-comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#html-comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#concise-html-block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#concise-html-line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag-html</string>
				</dict>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>^(\s*)(?=style\.less\b)</string>
							<key>while</key>
							<string>(?=^\1\s+(\S|$))</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#concise-open-tag-content</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#concise-style-block-less</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#concise-style-line-less</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>^(\s*)(?=style\.scss\b)</string>
							<key>while</key>
							<string>(?=^\1\s+(\S|$))</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#concise-open-tag-content</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#concise-style-block-scss</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#concise-style-line-scss</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>^(\s*)(?=style\b)</string>
							<key>while</key>
							<string>(?=^\1\s+(\S|$))</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#concise-open-tag-content</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#concise-style-block</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#concise-style-line</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>^(\s*)(?=script\b)</string>
							<key>while</key>
							<string>(?=^\1\s+(\S|$))</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#concise-open-tag-content</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#concise-script-block</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#concise-script-line</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>^(\s*)(?=[a-zA-Z0-9_$@])</string>
							<key>while</key>
							<string>(?=^\1\s+(\S|$))</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#concise-open-tag-content</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#content-concise-mode</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#invalid</string>
				</dict>
			</array>
		</dict>
		<key>content-embedded-script</key>
		<dict>
			<key>name</key>
			<string>meta.embedded.js</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#placeholder</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<key>content-embedded-style</key>
		<dict>
			<key>name</key>
			<string>meta.embedded.css</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#placeholder</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.css</string>
				</dict>
			</array>
		</dict>
		<key>content-embedded-style-less</key>
		<dict>
			<key>name</key>
			<string>meta.embedded.css.less</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#placeholder</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.css.less</string>
				</dict>
			</array>
		</dict>
		<key>content-embedded-style-scss</key>
		<dict>
			<key>name</key>
			<string>meta.embedded.css.scss</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#placeholder</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.css.scss</string>
				</dict>
			</array>
		</dict>
		<key>content-html-mode</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#scriptlet</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#html-comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag-html</string>
				</dict>
				<dict>
					<key>name</key>
					<string>string</string>
					<key>match</key>
					<string>\\.</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#placeholder</string>
				</dict>
				<dict>
					<key>name</key>
					<string>string</string>
					<key>match</key>
					<string>.+?</string>
				</dict>
			</array>
		</dict>
		<key>html-args-or-method</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#javascript-args</string>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.embedded.js</string>
					<key>contentName</key>
					<string>source.js</string>
					<key>begin</key>
					<string>(?&lt;=\))\s*(?=\{)</string>
					<key>end</key>
					<string>(?&lt;=\})</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>html-comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>comment.block.marko</string>
					<key>begin</key>
					<string>\s*(&lt;!(--)?)</string>
					<key>end</key>
					<string>\2&gt;</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.marko</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.marko</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>comment.block.marko</string>
					<key>begin</key>
					<string>\s*(&lt;html-comment&gt;)</string>
					<key>end</key>
					<string>&lt;/html-comment&gt;</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.marko</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.marko</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>invalid</key>
		<dict>
			<key>name</key>
			<string>invalid.illegal.character-not-allowed-here.marko</string>
			<key>match</key>
			<string>[^\s]</string>
		</dict>
		<key>javascript-args</key>
		<dict>
			<key>name</key>
			<string>meta.embedded.js</string>
			<key>contentName</key>
			<string>source.js</string>
			<key>begin</key>
			<string>(?=\()</string>
			<key>end</key>
			<string>(?&lt;=\))</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<key>javascript-comment-line</key>
		<dict>
			<key>contentName</key>
			<string>source.js</string>
			<key>match</key>
			<string>\s*//.*$</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>javascript-comment-multiline</key>
		<dict>
			<key>contentName</key>
			<string>source.js</string>
			<key>begin</key>
			<string>\s*(?=/\*)</string>
			<key>end</key>
			<string>(?&lt;=\*/)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<key>javascript-comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#javascript-comment-multiline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#javascript-comment-line</string>
				</dict>
			</array>
		</dict>
		<key>javascript-enclosed</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#javascript-comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#javascript-args</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?={)</string>
					<key>end</key>
					<string>(?&lt;=})</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?=\[)</string>
					<key>end</key>
					<string>(?&lt;=])</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?=&quot;)</string>
					<key>end</key>
					<string>(?&lt;=&quot;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?=&apos;)</string>
					<key>end</key>
					<string>(?&lt;=&apos;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?=`)</string>
					<key>end</key>
					<string>(?&lt;=`)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>contentName</key>
					<string>source.js</string>
					<key>begin</key>
					<string>/(?!&lt;[\]})A-Z0-9.&lt;%]\s*/)(?!/?&gt;|$)</string>
					<key>end</key>
					<string>/[gimsuy]*</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.js#regexp</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>string.regexp.js</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?x)\s*(?:
								(?:\b(?:new|typeof|instanceof|in)\b)| # Keyword operators
								\&amp;\&amp;|\|\|| # Logical operators
								[\^|&amp;]| # Bitwise operators
								[!=]=|[!=]==|&lt;|&lt;[=&lt;]|=&gt;| # Comparison operators (Note you cannot use * or ? here)
								[?:]| # Ternary operators
								[-+*%](?!-) # Arithmetic operators
							)</string>
					<key>end</key>
					<string>(?=\S)</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.js</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>javascript-expression</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#javascript-enclosed</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[0-9a-zA-Z$_.]+</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.js</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>javascript-statement</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#javascript-enclosed</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<key>open-tag-content</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-before-attrs</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?= )</string>
					<key>end</key>
					<string>(?=/?&gt;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#attrs</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>placeholder</key>
		<dict>
			<key>contentName</key>
			<string>source.js</string>
			<key>begin</key>
			<string>\$!?{</string>
			<key>end</key>
			<string>}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.template-expression.begin.js</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.template-expression.end.js</string>
				</dict>
			</dict>
		</dict>
		<key>scriptlet</key>
		<dict>
			<key>name</key>
			<string>meta.embedded.js</string>
			<key>contentName</key>
			<string>source.js</string>
			<key>begin</key>
			<string>^\s*(\$)\s+</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#javascript-statement</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.scriptlet.marko</string>
				</dict>
			</dict>
		</dict>
		<key>tag-before-attrs</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-name</string>
				</dict>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.marko</string>
					<key>match</key>
					<string>[#.][a-zA-Z0-9_$][a-zA-Z0-9_$-]*</string>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.embedded.js</string>
					<key>contentName</key>
					<string>source.js</string>
					<key>begin</key>
					<string>/(?!/)</string>
					<key>end</key>
					<string>(?=:?\=|\s|&gt;|$|\||\(|/)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>variable.other.constant.object.js</string>
							<key>match</key>
							<string>[a-zA-Z$_][0-9a-zA-Z$_]*</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.js#object-binding-pattern</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.js#array-binding-pattern</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.js#var-single-variable</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#javascript-expression</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.key-value.marko</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.embedded.js</string>
					<key>contentName</key>
					<string>source.js</string>
					<key>begin</key>
					<string>\s*(:?=)\s*</string>
					<key>end</key>
					<string>(?=.|$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#javascript-expression</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.js</string>
								</dict>
							</array>
						</dict>
					</dict>
					<key>applyEndPatternLast</key>
					<true />
				</dict>
				<dict>
					<key>begin</key>
					<string>\|</string>
					<key>end</key>
					<string>\|</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.js#function-parameters-body</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.scope.begin.marko</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.scope.end.marko</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>include</key>
					<string>#html-args-or-method</string>
				</dict>
			</array>
		</dict>
		<key>tag-html</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(&lt;)(?=(area|base|br|col|embed|hr|img|input|link|meta|param|source|track|wbr)\b)</string>
					<key>end</key>
					<string>/?&gt;</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#open-tag-content</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.marko</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.marko</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>begin</key>
					<string>\s*(&lt;)(?=style\.less\b)</string>
					<key>end</key>
					<string>/&gt;|(?&lt;=\&gt;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#open-tag-content</string>
						</dict>
						<dict>
							<key>contentName</key>
							<string>source.less</string>
							<key>begin</key>
							<string>&gt;</string>
							<key>end</key>
							<string>\s*(&lt;/)(style)?(&gt;)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#content-embedded-style-less</string>
								</dict>
							</array>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.end.marko</string>
								</dict>
							</dict>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.end.marko</string>
								</dict>
								<key>2</key>
								<dict>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#tag-name</string>
										</dict>
									</array>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.end.marko</string>
								</dict>
							</dict>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.marko</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.marko</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>begin</key>
					<string>\s*(&lt;)(?=style\.scss\b)</string>
					<key>end</key>
					<string>/&gt;|(?&lt;=\&gt;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#open-tag-content</string>
						</dict>
						<dict>
							<key>contentName</key>
							<string>source.less</string>
							<key>begin</key>
							<string>&gt;</string>
							<key>end</key>
							<string>\s*(&lt;/)(style)?(&gt;)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#content-embedded-style-scss</string>
								</dict>
							</array>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.end.marko</string>
								</dict>
							</dict>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.end.marko</string>
								</dict>
								<key>2</key>
								<dict>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#tag-name</string>
										</dict>
									</array>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.end.marko</string>
								</dict>
							</dict>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.marko</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.marko</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>begin</key>
					<string>\s*(&lt;)(?=style\b)</string>
					<key>end</key>
					<string>/&gt;|(?&lt;=\&gt;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#open-tag-content</string>
						</dict>
						<dict>
							<key>contentName</key>
							<string>source.css</string>
							<key>begin</key>
							<string>&gt;</string>
							<key>end</key>
							<string>\s*(&lt;/)(style)?(&gt;)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#content-embedded-style</string>
								</dict>
							</array>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.end.marko</string>
								</dict>
							</dict>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.end.marko</string>
								</dict>
								<key>2</key>
								<dict>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#tag-name</string>
										</dict>
									</array>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.end.marko</string>
								</dict>
							</dict>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.marko</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.marko</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>begin</key>
					<string>\s*(&lt;)(?=script\b)</string>
					<key>end</key>
					<string>/&gt;|(?&lt;=\&gt;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#open-tag-content</string>
						</dict>
						<dict>
							<key>contentName</key>
							<string>source.js</string>
							<key>begin</key>
							<string>&gt;</string>
							<key>end</key>
							<string>\s*(&lt;/)(script)?(&gt;)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#content-embedded-script</string>
								</dict>
							</array>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.end.marko</string>
								</dict>
							</dict>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.end.marko</string>
								</dict>
								<key>2</key>
								<dict>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#tag-name</string>
										</dict>
									</array>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.end.marko</string>
								</dict>
							</dict>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.marko</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.marko</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>begin</key>
					<string>\s*(&lt;)(?=[a-zA-Z0-9_$@])</string>
					<key>end</key>
					<string>/&gt;|(?&lt;=\&gt;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#open-tag-content</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>&gt;</string>
							<key>end</key>
							<string>\s*(&lt;/)([a-zA-Z0-9_$:@-]+)?(.*?)(&gt;)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#content-html-mode</string>
								</dict>
							</array>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.end.marko</string>
								</dict>
							</dict>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.end.marko</string>
								</dict>
								<key>2</key>
								<dict>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#tag-name</string>
										</dict>
									</array>
								</dict>
								<key>3</key>
								<dict>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#invalid</string>
										</dict>
									</array>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.end.marko</string>
								</dict>
							</dict>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.marko</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.marko</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>tag-name</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\${</string>
					<key>end</key>
					<string>}</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.template-expression.begin.js</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.template-expression.end.js</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>(style)\.([a-zA-Z0-9$_-]+(?:\.[a-zA-Z0-9$_-]+)*)|([a-zA-Z0-9_$@][a-zA-Z0-9_$@:-]*)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.marko</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.type.marko.css</string>
						</dict>
						<key>3</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>name</key>
									<string>support.type.builtin.marko</string>
									<key>match</key>
									<string>(attrs|return|import)(?=\b)</string>
								</dict>
								<dict>
									<key>name</key>
									<string>support.function.marko</string>
									<key>match</key>
									<string>(for|if|while|else-if|else|macro|tag|await|let|const|effect|set|get|id|lifecycle)(?=\b)</string>
								</dict>
								<dict>
									<key>name</key>
									<string>entity.other.attribute-name.marko</string>
									<key>match</key>
									<string>@.+</string>
								</dict>
								<dict>
									<key>name</key>
									<string>entity.name.tag.marko</string>
									<key>match</key>
									<string>.+</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>marko</string>
	</array>
</dict>
</plist>
