<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Mermaid</string>
	<key>scopeName</key>
	<string>source.mermaid</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#main</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>a11y</key>
		<dict>
			<key>name</key>
			<string>meta.a11y-option.${1:/downcase}.mermaid</string>
			<key>begin</key>
			<string>(?:\G|^|(?&lt;=\s|;|%%))acc(Title|Descr)(?:(?=\s*[:{])|[ \t]*$)</string>
			<key>end</key>
			<string>(?!\G)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#a11y-innards</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\G$</string>
					<key>end</key>
					<string>(?!\G)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>\G</string>
							<key>end</key>
							<string>(?=\S)</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?=:|{)</string>
							<key>end</key>
							<string>(?!\G)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#a11y-innards</string>
								</dict>
							</array>
						</dict>
					</array>
					<key>applyEndPatternLast</key>
					<true />
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.accessibility.mermaid</string>
				</dict>
			</dict>
		</dict>
		<key>a11y-innards</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>contentName</key>
					<string>string.unquoted.directive-value.single-line.mermaid</string>
					<key>begin</key>
					<string>\G\s*(:)[ \t]*</string>
					<key>end</key>
					<string>[ \t]*$</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.assignment.key-value.colon</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>contentName</key>
					<string>string.quoted.other.curly.brackets.directive-value.multi-line.mermaid</string>
					<key>begin</key>
					<string>\G\s*({)[ \t]*</string>
					<key>end</key>
					<string>[ \t]*(})</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.curly.bracket.begin.mermaid</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.curly.bracket.end.mermaid</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>br</key>
		<dict>
			<key>name</key>
			<string>text.embedded.html.basic</string>
			<key>match</key>
			<string>(?i)&lt;br\s*/?&gt;</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.html.basic</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>brace</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>punctuation.definition.class.block.begin.mermaid</string>
					<key>match</key>
					<string>{</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>sublimelinter.gutter-mark</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.definition.class.block.end.mermaid</string>
					<key>match</key>
					<string>}</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>sublimelinter.gutter-mark</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>c4c-diagram</key>
		<dict>
			<key>name</key>
			<string>meta.c4c-diagram.c4-${2:/downcase}.mermaid</string>
			<key>begin</key>
			<string>^[ \t]*(C4(Component|Container|Context|Deployment|Dynamic))(?=$|\s|;)</string>
			<key>end</key>
			<string>(?=A)B|(?=^[ \t]*(?:`{3,}|~{3,})\s*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.mermaid.c4c-diagram</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.c4c-diagram.begin.mermaid</string>
				</dict>
			</dict>
		</dict>
		<key>class-diagram</key>
		<dict>
			<key>name</key>
			<string>meta.class-diagram.mermaid</string>
			<key>begin</key>
			<string>^[ \t]*(classDiagram(?:-v2)?)(?=$|\s|;)</string>
			<key>end</key>
			<string>(?=A)B|(?=^[ \t]*(?:`{3,}|~{3,})\s*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.mermaid.class-diagram</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.class-diagram.begin.mermaid</string>
				</dict>
			</dict>
		</dict>
		<key>colon</key>
		<dict>
			<key>name</key>
			<string>keyword.operator.assignment.mermaid</string>
			<key>match</key>
			<string>:</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.message.key-value.mermaid</string>
				</dict>
			</dict>
		</dict>
		<key>comma</key>
		<dict>
			<key>name</key>
			<string>punctuation.delimiter.comma.mermaid</string>
			<key>match</key>
			<string>,</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>sublimelinter.gutter-mark.mermaid</string>
				</dict>
			</dict>
		</dict>
		<key>comment</key>
		<dict>
			<key>name</key>
			<string>comment.line.percentage.mermaid</string>
			<key>begin</key>
			<string>(?:\G|^|(?&lt;=\s|;|%%))(%%)</string>
			<key>end</key>
			<string>$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.mermaid</string>
				</dict>
			</dict>
		</dict>
		<key>direction</key>
		<dict>
			<key>name</key>
			<string>meta.direction.statement.mermaid</string>
			<key>match</key>
			<string>(?:\G|^|(?&lt;=\s|;|%%))(direction)(?:\s+(BT|LR|RL|TB|TD))?(?=$|\s|;)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.direction.mermaid</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language.orientation.diagram.mermaid</string>
				</dict>
			</dict>
		</dict>
		<key>directive</key>
		<dict>
			<key>name</key>
			<string>meta.directive.mermaid</string>
			<key>contentName</key>
			<string>source.embedded.js</string>
			<key>begin</key>
			<string>%%(?={)</string>
			<key>end</key>
			<string>%%$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.directive.begin.mermaid</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.directive.end.mermaid</string>
				</dict>
			</dict>
		</dict>
		<key>entity</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.character.entity.codepoint.mermaid</string>
					<key>match</key>
					<string>(#)\d+(;)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entity.begin.mermaid</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entity.end.mermaid</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.entity.named.mermaid</string>
					<key>match</key>
					<string>(#)[a-zA-Z0-9]+(;)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entity.begin.mermaid</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entity.end.mermaid</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>er-diagram</key>
		<dict>
			<key>name</key>
			<string>meta.er-diagram.mermaid</string>
			<key>begin</key>
			<string>^[ \t]*(erDiagram)(?=$|\s|;)</string>
			<key>end</key>
			<string>(?=A)B|(?=^[ \t]*(?:`{3,}|~{3,})\s*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.mermaid.er-diagram</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.er-diagram.begin.mermaid</string>
				</dict>
			</dict>
		</dict>
		<key>flowchart</key>
		<dict>
			<key>name</key>
			<string>meta.flowchart.mermaid</string>
			<key>begin</key>
			<string>^[ \t]*(flowchart(?:-v2)?|graph)(?!-)\b</string>
			<key>end</key>
			<string>(?=A)B|(?=^[ \t]*(?:`{3,}|~{3,})\s*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\G\s+(BT|LR|RL|TB|TD)(?=$|\s)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.language.orientation.flowchart.mermaid</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>include</key>
					<string>source.mermaid.flowchart</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.flowchart.begin.mermaid</string>
				</dict>
			</dict>
		</dict>
		<key>gantt</key>
		<dict>
			<key>name</key>
			<string>meta.gantt-chart.mermaid</string>
			<key>begin</key>
			<string>(?i)^[ \t]*(gantt)(?=$|\s)</string>
			<key>end</key>
			<string>(?=A)B|(?=^[ \t]*(?:`{3,}|~{3,})\s*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.mermaid.gantt</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.gantt-chart.begin.mermaid</string>
				</dict>
			</dict>
		</dict>
		<key>gitgraph</key>
		<dict>
			<key>name</key>
			<string>meta.gitgraph.mermaid</string>
			<key>begin</key>
			<string>(?i)^[ \t]*(gitGraph)(?:\s+(LR|BT))?(?:\s*(:))?(?=$|\s)</string>
			<key>end</key>
			<string>(?=A)B|(?=^[ \t]*(?:`{3,}|~{3,})\s*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.mermaid.gitgraph</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.gitgraph.begin.mermaid</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language.orientation.flowchart.mermaid</string>
				</dict>
				<key>3</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.mermaid#colon</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>inline-css</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>source.embedded.css</string>
					<key>match</key>
					<string>(?=\S)(?:[^,;\r\n%]|(?&lt;!%)%(?!%))++</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.css#rule-list-innards</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>include</key>
					<string>#comma</string>
				</dict>
			</array>
		</dict>
		<key>main</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#directive</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#flowchart</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#sequence-diagram</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#class-diagram</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#state-diagram</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#er-diagram</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#user-journey</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#gantt</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#pie-chart</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#requirement-diagram</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#gitgraph</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#c4c-diagram</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#mindmap</string>
				</dict>
			</array>
		</dict>
		<key>mindmap</key>
		<dict>
			<key>name</key>
			<string>meta.mindmap.mermaid</string>
			<key>begin</key>
			<string>(?i)^[ \t]*(mindmap)(?=$|\s)</string>
			<key>end</key>
			<string>(?=A)B|(?=^[ \t]*(?:`{3,}|~{3,})\s*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.mermaid.mindmap</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.mindmap.begin.mermaid</string>
				</dict>
			</dict>
		</dict>
		<key>pie-chart</key>
		<dict>
			<key>name</key>
			<string>meta.pie-chart.mermaid</string>
			<key>begin</key>
			<string>(?i)^[ \t]*(pie)(?=$|\s)</string>
			<key>end</key>
			<string>(?=A)B|(?=^[ \t]*(?:`{3,}|~{3,})\s*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.mermaid.pie-chart</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.pie-chart.begin.mermaid</string>
				</dict>
			</dict>
		</dict>
		<key>requirement-diagram</key>
		<dict>
			<key>name</key>
			<string>meta.requirement-diagram.mermaid</string>
			<key>begin</key>
			<string>(?i)^[ \t]*(requirementDiagram)(?=$|\s)</string>
			<key>end</key>
			<string>(?=A)B|(?=^[ \t]*(?:`{3,}|~{3,})\s*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.mermaid.requirement-diagram</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.requirement-diagram.begin.mermaid</string>
				</dict>
			</dict>
		</dict>
		<key>sequence-diagram</key>
		<dict>
			<key>name</key>
			<string>meta.sequence-diagram.mermaid</string>
			<key>begin</key>
			<string>(?i)^[ \t]*(sequenceDiagram)(?=$|\s|;)</string>
			<key>end</key>
			<string>(?=A)B|(?=^[ \t]*(?:`{3,}|~{3,})\s*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.mermaid.sequence-diagram</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.sequence-diagram.begin.mermaid</string>
				</dict>
			</dict>
		</dict>
		<key>state-diagram</key>
		<dict>
			<key>name</key>
			<string>meta.state-diagram.mermaid</string>
			<key>begin</key>
			<string>(?i)^[ \t]*(stateDiagram(?:-v2)?)(?=$|\s|;)</string>
			<key>end</key>
			<string>(?=A)B|(?=^[ \t]*(?:`{3,}|~{3,})\s*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.mermaid.state-diagram</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.state-diagram.begin.mermaid</string>
				</dict>
			</dict>
		</dict>
		<key>terminator</key>
		<dict>
			<key>name</key>
			<string>punctuation.terminator.statement.mermaid</string>
			<key>match</key>
			<string>;</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>sublimelinter.gutter-mark.mermaid</string>
				</dict>
			</dict>
		</dict>
		<key>user-journey</key>
		<dict>
			<key>name</key>
			<string>meta.user-journey.mermaid</string>
			<key>begin</key>
			<string>(?i)^[ \t]*(journey)(?=$|\s)</string>
			<key>end</key>
			<string>(?=A)B|(?=^[ \t]*(?:`{3,}|~{3,})\s*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.mermaid.user-journey</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.user-journey.begin.mermaid</string>
				</dict>
			</dict>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>mmd</string>
		<string>mermaid</string>
	</array>
</dict>
</plist>
