<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>MiniYAML</string>
	<key>scopeName</key>
	<string>source.miniyaml</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#node</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>block-pair</key>
		<dict>
			<key>name</key>
			<string>entity.name.tag.yaml</string>
			<key>match</key>
			<string>^\t*(\S+?)(?=@|:)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#node-identifier</string>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>name</key>
			<string>comment.line.number-sign.yaml</string>
			<key>begin</key>
			<string>(?&lt;=^|\s)#(?!{)</string>
			<key>end</key>
			<string>$</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.yaml</string>
				</dict>
			</dict>
		</dict>
		<key>constants</key>
		<dict>
			<key>name</key>
			<string>constant.language.yaml</string>
			<key>match</key>
			<string>(?::\s)(true|false|True|False|TRUE|FALSE|~)(?=\s*$)</string>
		</dict>
		<key>node</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#node-removal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block-pair</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#node-identifier</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#scalar-content</string>
				</dict>
			</array>
		</dict>
		<key>node-identifier</key>
		<dict>
			<key>name</key>
			<string>support.yaml</string>
			<key>match</key>
			<string>(?&lt;=\S)(@\S+)(?=:\s)</string>
		</dict>
		<key>node-removal</key>
		<dict>
			<key>name</key>
			<string>entity.yaml</string>
			<key>match</key>
			<string>^\t+(-.+?)(?=@|:\s)</string>
		</dict>
		<key>numeric</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.numeric.integer.yaml</string>
					<key>match</key>
					<string>(?::\s)[-+]?[0-9]+(?=\s*($|#(?!#{)))</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.octal.yaml</string>
					<key>match</key>
					<string>(?::\s)0o[0-7]+(?=\s*($|#(?!#{)))</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.hexadecimal.yaml</string>
					<key>match</key>
					<string>(?::\s)0x[0-9a-fA-F]+(?=\s*($|#(?!#{)))</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.float.yaml</string>
					<key>match</key>
					<string>(?::\s)[-+]?(.[0-9]+|[0-9]+(.[0-9]*)?)([eE][-+]?[0-9]+)?(?=\s*($|#(?!#{)))</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.float.yaml</string>
					<key>match</key>
					<string>(?::\s)[-+]?(.inf|.Inf|.INF)(?=\s*($|#(?!#{)))</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.float.yaml</string>
					<key>match</key>
					<string>(?::\s)(.nan|.NaN|.NAN)(?=\s*($|#(?!#{)))</string>
				</dict>
			</array>
		</dict>
		<key>scalar-content</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numeric</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>string.unquoted.yaml</string>
					<key>match</key>
					<string>[^\s&quot;&apos;\n](?!\s*#(?!{))([^#\n]|((?&lt;!\s)#))*</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>yaml</string>
		<string>yml</string>
	</array>
</dict>
</plist>
