<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Modelica</string>
	<key>scopeName</key>
	<string>source.modelica</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>name</key>
			<string>comment.block</string>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
		</dict>
		<dict>
			<key>name</key>
			<string>comment.line</string>
			<key>match</key>
			<string>(//).*$\n?</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.language</string>
			<key>match</key>
			<string>\b(true|false)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.numeric</string>
			<key>match</key>
			<string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.type</string>
			<key>match</key>
			<string>\b(Real|Integer|Boolean|String)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.modifier</string>
			<key>match</key>
			<string>\b(constant|final|parameter|expandable|replaceable|redeclare|constrainedby|import|flow|stream|input|output|discrete|connector)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword</string>
			<key>match</key>
			<string>\b\s*([A-Z])(?:([^ ;$]+)(;)?)([.]([A-Z])(?:([^ ;$]+)(;)?)?)++\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.control</string>
			<key>match</key>
			<string>\b(for|if|when|while|then|loop|end if|end when|end for|end while|else|elsewhen|and|break|each|elseif)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.operator.logical</string>
			<key>match</key>
			<string>\b(and|or|not)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.operator.comparison</string>
			<key>match</key>
			<string>&lt;|&lt;\=|&gt;|&gt;\=|\=\=|&lt;&gt;</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.operator.arithmetic</string>
			<key>match</key>
			<string>\+|\-|\.\+|\.\-|\*|\.\*|/|\./|\^</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.operator.assignment</string>
			<key>match</key>
			<string>\=|\:\=</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword</string>
			<key>match</key>
			<string>\b(algorithm|equation|initial equation|protected|public|register|end)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.other</string>
			<key>match</key>
			<string>\b(inner|outer)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.mathematical</string>
			<key>match</key>
			<string>\b(acos|asin|atan|atan2|cos|cosh|exp|log|log10|sin|sinh|tan|tanh|abs|sign|sqrt|max|min|product|sum)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.array</string>
			<key>match</key>
			<string>\b(scalar|vector|matrix|identity|diagonal|zeros|ones|fill|linspace|transpose|outerProduct|symmetric|cross|skew)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.event</string>
			<key>match</key>
			<string>\b(ceil|div|fill|floor|integer|max|min|mod|rem|pre|noEvent|change|edge|initial|terminal|reinit|sample|smooth|terminate)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.special</string>
			<key>match</key>
			<string>\b(connect|der|inStream|actualStream|semiLinear|spatialDistribution|getInstanceName|homotopy|delay|assert|ndims|size|cardinality|isPresent)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.type</string>
			<key>match</key>
			<string>\b(extends|partial|within)\b</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((model|class|record|block|package)\s+\w+\s*(&quot;.*&quot;)*)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>comment.line</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>((function)\s+\w+\s*(&quot;.*&quot;)*)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>comment.line</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>comment.block</string>
			<key>begin</key>
			<string>annotation</string>
			<key>end</key>
			<string>;\s*\n</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>comment.block</string>
					<key>begin</key>
					<string>&quot;</string>
					<key>end</key>
					<string>&quot;</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>[&quot;\w\)](\s+&quot;.*&quot;\s*);</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.string</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.string</string>
			<key>begin</key>
			<string>&quot;</string>
			<key>end</key>
			<string>&quot;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.character.escaped</string>
					<key>match</key>
					<string>\\.</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>fileTypes</key>
	<array>
		<string>mo</string>
	</array>
</dict>
</plist>
