<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Assembly (m68k)</string>
	<key>scopeName</key>
	<string>source.m68k</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>name</key>
			<string>comment.m68k</string>
			<key>match</key>
			<string>(;|\B\*).*$</string>
		</dict>
		<dict>
			<key>name</key>
			<string>string.quoted.m68k</string>
			<key>begin</key>
			<string>&quot;</string>
			<key>end</key>
			<string>&quot;</string>
		</dict>
		<dict>
			<key>name</key>
			<string>entity.name.function.m68k</string>
			<key>match</key>
			<string>^[a-zA-Z_][a-zA-Z0-9_]*:</string>
		</dict>
		<dict>
			<key>name</key>
			<string>entity.name.section.m68k</string>
			<key>match</key>
			<string>^(\.|_)[a-zA-Z_][a-zA-Z0-9_]*:?</string>
		</dict>
		<dict>
			<key>name</key>
			<string>entity.variable.m68k</string>
			<key>match</key>
			<string>^[a-zA-Z_][a-zA-Z0-9_]*</string>
		</dict>
		<dict>
			<key>name</key>
			<string>string.char.m68k</string>
			<key>match</key>
			<string>\&apos;\S\&apos;</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.numeric.dec.m68k</string>
			<key>match</key>
			<string>-?\b[0-9]+\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.numeric.hex.m68k</string>
			<key>match</key>
			<string>-?\$[0-9a-fA-F]+\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.other.register.m68k</string>
			<key>match</key>
			<string>\b(?i)([ad]([0-7])|sr|sp|pc)(?-i)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.other.register.privileged.m68k</string>
			<key>match</key>
			<string>\b(?i)(usp|dfc|sfc|vbr|cacr|caar|msp|isp)(?-i)\b</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i)((moves|movec)(\.[bwl])?)\s+([ad]([0-7])|(.+)),((usp|dfc|sfc|vbr|cacr|caar|msp|isp)|(.+))?(?-i)\b</string>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.mnemonic.privileged.m68k</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.mnemonic.size.m68k</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>storage.other.register.m68k</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.m68k</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.m68k</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>storage.other.register.privileged.m68k</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i)(reset|rte|stop(\s+(#.+)?))(?-i)\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.mnemonic.privileged.m68k</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.mnemonic.immediate.m68k</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i)(move(\.[bwl])?\s+((#.+)?(.+)?,(sr|usp)))(?-i)\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.mnemonic.privileged.m68k</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.mnemonic.size.m68k</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>support.mnemonic.immediate.m68k</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.m68k</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>storage.other.register.privileged.m68k</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i)(move(\.[bwl])?\s+(sr|usp),([^\s]+))(?-i)\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.mnemonic.privileged.m68k</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.mnemonic.size.m68k</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.other.register.m68k</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>storage.other.register.privileged.m68k</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i)(cinv[lp]|cpush[lp])\s+(dc|ic|bc),\((a[0-7])(?-i)\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.mnemonic.privileged.m68k</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.other.register.privileged.m68k</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.other.register.m68k</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i)(cinva|cpusha)\s+(dc|ic|bc)(?-i)\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.mnemonic.privileged.m68k</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.other.register.privileged.m68k</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i)((andi|eori|ori)(\.w)?(\s+(.+),(sr)))(?-i)\b</string>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.mnemonic.privileged.m68k</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.mnemonic.size.m68k</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>support.mnemonic.immediate.m68k</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>storage.other.register.privileged.m68k</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i)(pflusha|pflushan)(?-i)\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.mnemonic.privileged.m68k</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i)(pflush|pflushn)\s+\((a[0-7]|sp)(?-i)\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.mnemonic.privileged.m68k</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.other.register.m68k</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i)(pmove)\s+((crp|srp|tc|tt0|tt1)|.+),((crp|srp|tc|tt0|tt1)|.+)(?-i)\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.mnemonic.privileged.m68k</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.m68k</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.other.register.privileged.m68k</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.m68k</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>storage.other.register.privileged.m68k</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>support.mnemonic.m68k</string>
			<key>match</key>
			<string>\b(?i)([as]bcd(\.b)?|(add|sub)[iqx]?(\.[bwl])?|adda(\.[wl])?|(and|eor|or)(i)?(\.[bwl])?|(rox?|[al]s)[lr](\.[bwl])?|b(chg|clr|set|tst)(\.[bl])?|bf(chg|clr|extu|exts|ffo|ins|set|tst)|chk(\.[wl])?|chk2(\.[bwl])?|clr(\.[bwl])?|cas(\.[bwl])?|cas2(\.[wl])?|cmp[im2]?(\.[bwl])?|cmpa(\.[wl])?|divs|divu|exg(\.l)?|ext(\.[wl])?|extb.l|illegal|lea(\.l)?|link|muls|mulu|nbcd(\.b)?|(negx?|not)(\.[bwl])?|nop|pea(\.l)?|reset|rte|rtri|rtd|rts|s(f|t|cc|hs|cs|lo|eq|ge|gt|hi|le|ls|lt|mi|ne|pl|vc|vs)(\.b)?|stop|swap(\.l)?|tas(\.b)?|trap|trapv|trap(f|t|cc|hs|cs|lo|eq|ge|gt|hi|le|ls|lt|mi|ne|pl|vc|vs)|tst|tst\.b|tst\.w|tst\.l|unlk|pack|unpk)(?-i)\b</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i)(move(\.[bwl])?|movea(\.[wl])?)(?-i)\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.mnemonic.m68k</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.mnemonic.size.m68k</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.mnemonic.size.m68k</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i)(movem|movep)(\.[wl])?|(move16)(\.l)?(?-i)\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.mnemonic.m68k</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.mnemonic.size.m68k</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.m68k</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i)(moveq)(\.l)?\s+#((\$-?[0-9a-f]{1,3})|(%[0-1]{1,8})|-?([0-9]{1,3})),(d[0-7])(?-i)\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.mnemonic.m68k</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.mnemonic.size.m68k</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.mnemonic.operand.source.constant.m68k</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>support.mnemonic.operand.source.constant.hex.m68k</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>support.mnemonic.operand.source.constant.binary.m68k</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>support.mnemonic.operand.source.constant.decimal.m68k</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>storage.other.register.m68k</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i)(b(ra|cc|hs|cs|lo|eq|ge|gt|hi|le|ls|lt|mi|ne|pl|vc|vs|sr)(\.[sw])?)(?-i)\s+(\.?[a-zA-Z_][a-zA-Z0-9_]*)\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.mnemonic.branch.m68k</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.m68k</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i)(j(sr|mp))(?-i)\s+((\.?[a-zA-Z_][a-zA-Z0-9_]*)|\$?\d*\((sp|pc|a[0-7])(,(d|a)[0-7](.(w|l))?(\*[248])?)?\))</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.mnemonic.branch.m68k</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.other.register.m68k</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.m68k</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i)(db(ra|f|t|cc|hs|cs|lo|eq|ge|gt|hi|le|ls|lt|mi|ne|pl|vc|vs))(?-i)\s+(d[0-7])\s*,\s*\.*([a-zA-Z_][a-zA-Z0-9_]*)\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.mnemonic.loop.m68k</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.other.register.m68k</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.m68k</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i)(f(s|d)?(abs|acos|add|atan|atanh|asin|sub|asub|tst|cmp|div|mul|move|neg|sqrt|int|intrz|getexp|getman|mod|rem|scale|sgldiv|sglmul|etox|etoxm1|logn|lognp1|log10|log2|tentox|twotox|cos|sin|cosh|sinh|sincos|tan|tanh|))(\.[xbwlsd])?\s+((fp[0-7])|.+)(,((fp[0-7])|.+))?(?-i)\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.mnemonic.m68k</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>support.mnemonic.size.m68k</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>support.mnemonic.operand.source</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.m68k</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.m68k</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i)(fmovem)(\.[xl])?\s+(.+),(.+)(?-i)\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.mnemonic.m68k</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.mnemonic.size.m68k</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.mnemonic.operand.source</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.m68k</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>support.mnemonic.m68k</string>
			<key>match</key>
			<string>\b(?i)fnop(?-i)\b</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i)(fmovecr)(\.x)?\s+(#.+),(fp[0-7])(?-i)\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.mnemonic.m68k</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.mnemonic.size.m68k</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.mnemonic.operand.source</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.m68k</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i)(fsave|frestore)\s+((\(a[0-7]|sp]\))|.+)(?-i)\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.mnemonic.privileged.m68k</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.mnemonic.operand.source</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i)(f([bs])?(f|eq|ogt|oge|olt|ole|ogl|or|un|ueq|ugt|uge|ult|ule|ne|t|seq|gt|ge|lt|le|gl|gle|ngle|ngl|nle|nlt|nge|ngt|sne|st|sf|seq|sogt))(?-i)\s+(\.?([a-zA-Z_][a-zA-Z0-9_]*))\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.mnemonic.branch.m68k</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.m68k</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i)(fd([bs])?(f|eq|ogt|oge|olt|ole|ogl|or|un|ueq|ugt|uge|ult|ule|ne|t|seq|gt|ge|lt|le|gl|gle|ngle|ngl|nle|nlt|nge|ngt|sne|st|sf|seq|sogt))(?-i)\s+((d[0-7])),(\.?([a-zA-Z_][a-zA-Z0-9_]*))\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.mnemonic.branch.m68k</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>storage.other.register.m68k</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.m68k</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i)(ftrap(f|eq|ogt|oge|olt|ole|ogl|or|un|ueq|ugt|uge|ult|ule|ne|t|seq|gt|ge|lt|le|gl|gle|ngle|ngl|nle|nlt|nge|ngt|sne|st|sf|seq|sogt))(?-i)\s+(fp[0-7]),(\.?[a-zA-Z_][a-zA-Z0-9_]*)\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.mnemonic.branch.m68k</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.other.register.m68k</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.m68k</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.control.define.m68k</string>
			<key>match</key>
			<string>\b(?i)(rsreset|rsset|rs(.[bwl])?|equ|fequ|include|incbin|set|reg|cargs|fequ|xref|xdef)(?-i)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.control.directive.m68k</string>
			<key>match</key>
			<string>\b(?i)((d[cs]|dcb)(.[sbwl])?|even|ifeq|ifne|ifgt|ifge|iflt|ifle|endif|endc|rept|endr|macro|endm|section|text|data|bss|end|cnop|opt|machine|fpu|comment)(?-i)\b</string>
		</dict>
	</array>
	<key>fileTypes</key>
	<array>
		<string>asm</string>
		<string>i</string>
		<string>inc</string>
		<string>s</string>
		<string>x68</string>
	</array>
</dict>
</plist>
