<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>.nanorc</string>
	<key>scopeName</key>
	<string>source.nanorc</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>injections.etc#scopeHack</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#main</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>colours</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.colour.nanorc</string>
					<key>begin</key>
					<string>^\s*(i?color)(?=\s|$)</string>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\G\s*(,)(\S+)</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.separator.delimiter.meta.comma.nanorc</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.background.colour.name.nanorc</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>match</key>
							<string>\G\s*((?!,)\S+)(,)(\S+)</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.foreground.colour.name.nanorc</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.separator.delimiter.meta.comma.nanorc</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>entity.background.colour.name.nanorc</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>match</key>
							<string>\G\s*([^\s,]+)(,?)(?=\s|$)</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.foreground.colour.name.nanorc</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.separator.delimiter.meta.comma.nanorc</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>name</key>
							<string>meta.$1-pattern.nanorc</string>
							<key>match</key>
							<string>(?&lt;=\s|\G)(start|end)(=)(?=\s|$)</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>variable.parameter.attribute.nanorc</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.assignment.equals-sign.nanorc</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>name</key>
							<string>meta.$1-pattern.nanorc</string>
							<key>begin</key>
							<string>(?&lt;=\s|\G)(start|end)(=)(?=&quot;)</string>
							<key>end</key>
							<string>(?&lt;=&quot;)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#regexp</string>
								</dict>
							</array>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>variable.parameter.attribute.nanorc</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.assignment.equals-sign.nanorc</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>include</key>
							<string>#regexp</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.var.colour.name.nanorc</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>name</key>
			<string>comment.line.number-sign.nanorc</string>
			<key>begin</key>
			<string>#</string>
			<key>end</key>
			<string>$</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.nanorc</string>
				</dict>
			</dict>
		</dict>
		<key>main</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#colours</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#syntax</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#options</string>
				</dict>
			</array>
		</dict>
		<key>options</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.option.$2.nanorc</string>
					<key>begin</key>
					<string>^\s*(set)\s+(fill|tabsize)(?=\s|$)</string>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>constant.numeric.integer.int.decimal.nanorc</string>
							<key>match</key>
							<string>[0-9]+</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.$1.nanorc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.option.name.nanorc</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.option.$2.nanorc</string>
					<key>begin</key>
					<string>(?x) ^ \s*
(set|unset) \s+
(autoindent|backup|backwards|boldtext|casesensitive|const|cut
|historylog|morespace|mouse|multibuffer|noconvert|nofollow|nohelp
|nonewlines|nowrap|preserve|quickblank|rebinddelete|rebindkeypad
|regexp|smarthome|smooth|suspend|tabstospaces|tempfile|view
|wordbounds) (?=\s|$)</string>
					<key>end</key>
					<string>$</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.$1.nanorc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.option.name.nanorc</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.option.$2.nanorc</string>
					<key>begin</key>
					<string>(?x) ^ \s*
(set) \s+
(backupdir|brackets|matchbrackets|operatingdir
|punct|speller|whitespace) (?=\s|$)</string>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.$1.nanorc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.option.name.nanorc</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.preprocessor.include.nanorc</string>
					<key>contentName</key>
					<string>storage.modifier.import.file-name.nanorc</string>
					<key>begin</key>
					<string>^\s*(include)(?=\s|$)\s*</string>
					<key>end</key>
					<string>$</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.directive.include.nanorc</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.option.$2.nanorc</string>
					<key>begin</key>
					<string>^\s*(set)\s+(quotestr)(?=\s|$)</string>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#regexp</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.$1.nanorc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.option.name.nanorc</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.option.custom.nanorc</string>
					<key>begin</key>
					<string>^\s*(?:(set|unset)\s+)?(\S+)</string>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>constant.logical.boolean.$1.nanorc</string>
							<key>match</key>
							<string>\b(true|false|on|off|yes|no)\b</string>
						</dict>
						<dict>
							<key>name</key>
							<string>constant.numeric.decimal.nanorc</string>
							<key>match</key>
							<string>[-+]?(?:\d+(?:\.\d*)?|\.\d+)(?=\s|$)</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#regexp</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.$1.nanorc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.option.name.nanorc</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>quotedString</key>
		<dict>
			<key>name</key>
			<string>string.quoted.double.nanorc</string>
			<key>begin</key>
			<string>&quot;</string>
			<key>end</key>
			<string>&quot;(?=[^&quot;]*$)|(?=$)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.nanorc</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.nanorc</string>
				</dict>
			</dict>
		</dict>
		<key>regexp</key>
		<dict>
			<key>name</key>
			<string>string.regexp.embedded.nanorc</string>
			<key>begin</key>
			<string>(&quot;)&quot;?+</string>
			<key>end</key>
			<string>&quot;(?=\s|$)|(?=$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?:&quot;(?!\s|$))+</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.regexp</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.nanorc</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.nanorc</string>
				</dict>
			</dict>
		</dict>
		<key>string</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#quotedString</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#unquotedString</string>
				</dict>
			</array>
		</dict>
		<key>syntax</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.syntax.nanorc</string>
					<key>match</key>
					<string>^\s*(syntax)\s+(none|default)(?=\s|$)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.var.syntax.name.nanorc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant.language.$2.nanorc</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.syntax.nanorc</string>
					<key>begin</key>
					<string>^\s*(syntax)(?:\s+((&quot;)[^&quot;]+(&quot;)|\S+)(?:\s+(.*))?)?\s*$\s*</string>
					<key>end</key>
					<string>^(?=\s*syntax)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#main</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.var.syntax.name.nanorc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.syntax.name.nanorc</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.name.begin.nanorc</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.name.end.nanorc</string>
						</dict>
						<key>5</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#regexp</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>unquotedString</key>
		<dict>
			<key>name</key>
			<string>string.unquoted.bareword.nanorc</string>
			<key>match</key>
			<string>\S+</string>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>nanorc</string>
	</array>
</dict>
</plist>
