<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>nesC</string>
	<key>scopeName</key>
	<string>source.nesc</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.c</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.control.nesc</string>
			<key>match</key>
			<string>\b(abstract|as|async|atomic|call|command|components|configuration|event|implementation|includes|interface|generic|module|new|norace|post|provides|signal|task|uses|nx_struct)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.type.nesc</string>
			<key>match</key>
			<string>\b(result_t|error_t|nx_uint8_t|nx_uint16_t|nx_uint32_t|nx_int8_t|nx_int16_t|nx_int32_t|message_t|void)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.language.nesc</string>
			<key>match</key>
			<string>\b(SUCCESS|FAIL)\b</string>
		</dict>
	</array>
	<key>fileTypes</key>
	<array>
		<string>nc</string>
	</array>
</dict>
</plist>
