<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Nextflow</string>
	<key>scopeName</key>
	<string>source.nextflow</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#nfl-rules</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>code-block</key>
		<dict>
			<key>name</key>
			<string>code.block.nextflow</string>
			<key>begin</key>
			<string>{</string>
			<key>end</key>
			<string>}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#nfl-rules</string>
				</dict>
			</array>
		</dict>
		<key>nfl-rules</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#process-def</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#code-block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.nextflow-groovy</string>
				</dict>
			</array>
		</dict>
		<key>process-body</key>
		<dict>
			<key>name</key>
			<string>process.body.nextflow</string>
			<key>begin</key>
			<string>{</string>
			<key>end</key>
			<string>(?=})</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>process.directive.type.nextflow</string>
					<key>match</key>
					<string>(?:accelerator|afterScript|beforeScript|cache|cpus|conda|container|containerOptions|clusterOptions|disk|echo|errorStrategy|executor|ext|label|machineType|maxErrors|maxForks|maxRetries|memory|module|penv|pod|publishDir|queue|scratch|stageInMode|stageOutMode|storeDir|tag|time|validExitStatus)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.block.nextflow</string>
					<key>match</key>
					<string>(?:input|output|when|script|shell|exec):</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.nextflow-groovy#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.nextflow-groovy#support-functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.nextflow-groovy#keyword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.nextflow-groovy#values</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.nextflow-groovy#anonymous-classes-and-new</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.nextflow-groovy#types</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.nextflow-groovy#parens</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.nextflow-groovy#closures</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.nextflow-groovy#braces</string>
				</dict>
			</array>
		</dict>
		<key>process-def</key>
		<dict>
			<key>name</key>
			<string>process.nextflow</string>
			<key>begin</key>
			<string>^\s*(process)\s+(\w+|&quot;[^&quot;]+&quot;|&apos;[^&apos;]+&apos;)\s*</string>
			<key>end</key>
			<string>}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#process-body</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.nextflow</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>function.nextflow</string>
				</dict>
			</dict>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>nf</string>
	</array>
</dict>
</plist>
