<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Ninja</string>
	<key>scopeName</key>
	<string>source.ninja</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>name</key>
			<string>comment.line.number-sign.ninja</string>
			<key>begin</key>
			<string>#</string>
			<key>end</key>
			<string>$</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.ninja</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.$1.ninja</string>
			<key>begin</key>
			<string>^(rule|pool)\s+(\S+)</string>
			<key>end</key>
			<string>^(?=\S)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.$1.ninja</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.$1.ninja</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escapes</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.build.ninja</string>
			<key>begin</key>
			<string>(?x)
^ (build) \s+
((?:[^\s:|$]|\$.)+)
(?:
  (\|{1,2})
  ((?:[^:$]|\$.)*)
  (?=:)
)?</string>
			<key>end</key>
			<string>(?&lt;!\$)$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.operator.build.ninja</string>
					<key>match</key>
					<string>\|{2}</string>
				</dict>
				<dict>
					<key>name</key>
					<string>variable.reference.ninja</string>
					<key>match</key>
					<string>(?:[^\s:|$]|\$.)+</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.build.ninja</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.build.ninja</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escapes</string>
						</dict>
					</array>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.build.ninja</string>
				</dict>
				<key>4</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escapes</string>
						</dict>
						<dict>
							<key>name</key>
							<string>variable.reference.ninja</string>
							<key>match</key>
							<string>(?:[^\s:|$]|\$.)+</string>
							<key>captures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#escapes</string>
										</dict>
									</array>
								</dict>
							</dict>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=:)\s*(phony)\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.phony.build.ninja</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;==)\s*(\.\d+|\d+(?:\.\d+)?)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.ninja</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.default.ninja</string>
			<key>begin</key>
			<string>^(default)(?=\s|$)</string>
			<key>end</key>
			<string>(?&lt;!\$)$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>entity.name.function.build.ninja</string>
					<key>match</key>
					<string>\S+</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.build.default.ninja</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.command.ninja</string>
			<key>begin</key>
			<string>^\s*(command)\s*(=)</string>
			<key>end</key>
			<string>(?&lt;!\$)$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?:\G|^)(.+)(?=$)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>embedded.source.shell</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.shell</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language.rule.ninja</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.ninja</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.property.ninja</string>
			<key>match</key>
			<string>(?x) ^ \s* (depfile|deps|msvc_deps_prefix|description|generator|in |in_newline|out|restat|rspfile|rspfile_content) \s* (=)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.variable.language.rule.ninja</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.ninja</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.$1.ninja</string>
			<key>contentName</key>
			<string>string.unquoted.filename.ninja</string>
			<key>begin</key>
			<string>^(subninja|include)\s+</string>
			<key>end</key>
			<string>(?&lt;!\$)$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.$1.ninja</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>punctuation.separator.dictionary.key-value.ninja</string>
			<key>match</key>
			<string>:</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(\w+)\s*(=)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.reference.ninja</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.ninja</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>variable.parameter.reference.ninja</string>
			<key>match</key>
			<string>(\$)\w+</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.ninja</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.character.escape.newline.ninja</string>
			<key>match</key>
			<string>\$$\n?</string>
		</dict>
		<dict>
			<key>name</key>
			<string>variable.other.bracket.ninja</string>
			<key>match</key>
			<string>(\${)\s*[^{}]+\s*(})</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.begin.ninja</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.end.ninja</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>include</key>
			<string>#escapes</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>escapes</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.character.escape.dollar-sign.ninja</string>
					<key>match</key>
					<string>\${2}</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.escape.whitespace.ninja</string>
					<key>match</key>
					<string>\$[ \t]</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.escape.colon.ninja</string>
					<key>match</key>
					<string>\$:</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>ninja</string>
	</array>
</dict>
</plist>
