<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Object Data Instance Notation</string>
	<key>scopeName</key>
	<string>source.odin-ehr</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#main</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>attribute</key>
		<dict>
			<key>name</key>
			<string>entity.other.attribute-name.odin-ehr</string>
			<key>match</key>
			<string>\b(?=[a-z])[A-Za-z0-9_]+</string>
		</dict>
		<key>block</key>
		<dict>
			<key>name</key>
			<string>meta.block.odin-ehr</string>
			<key>begin</key>
			<string>&lt;</string>
			<key>end</key>
			<string>&gt;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#main</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.block.begin.odin-ehr</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.block.end.odin-ehr</string>
				</dict>
			</dict>
		</dict>
		<key>boolean</key>
		<dict>
			<key>name</key>
			<string>constant.language.boolean.${1:/downcase}.odin-ehr</string>
			<key>match</key>
			<string>(?i)\b(False|True)\b</string>
		</dict>
		<key>comment</key>
		<dict>
			<key>name</key>
			<string>comment.line.double-dash.odin-ehr</string>
			<key>begin</key>
			<string>--</string>
			<key>end</key>
			<string>$</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.odin-ehr</string>
				</dict>
			</dict>
		</dict>
		<key>date</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>((\d{4})(-)(\d{2}|\?{2})(-)(\d{2}|\?{2})(T))((\d{2}|\?{2})(:)(\d{2}|\?{2})(:)(\d{2}|\?{2}))</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.date.partial.odin-ehr</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.year.odin-ehr</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.date.dash.odin-ehr</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.month.odin-ehr</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.date.dash.odin-ehr</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.day.odin-ehr</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>constant.language.datetime-separator.odin-ehr</string>
						</dict>
						<key>8</key>
						<dict>
							<key>name</key>
							<string>meta.time.partial.odin-ehr</string>
						</dict>
						<key>9</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.hour.odin-ehr</string>
						</dict>
						<key>10</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.time.colon.odin-ehr</string>
						</dict>
						<key>11</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.minute.odin-ehr</string>
						</dict>
						<key>12</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.time.colon.odin-ehr</string>
						</dict>
						<key>13</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.second.odin-ehr</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.time.partial.odin-ehr</string>
					<key>match</key>
					<string>(\d{2})(:)(\d{2}|\?{2})(:)(\?{2})</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.hour.odin-ehr</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.time.colon.odin-ehr</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.minute.odin-ehr</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.time.colon.odin-ehr</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.second.odin-ehr</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.date.partial.odin-ehr</string>
					<key>match</key>
					<string>(\d{4})(-)(\d{2}|\?{2})(-)(\?{2})</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.year.odin-ehr</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.date.dash.odin-ehr</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.month.odin-ehr</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.date.dash.odin-ehr</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.day.odin-ehr</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.time.odin-ehr</string>
					<key>match</key>
					<string>(\d{2})(:)(\d{2})(:)(\d{2})((,)(\d+))?(Z|([-+])\d{4})?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.hour.odin-ehr</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.time.colon.odin-ehr</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.minute.odin-ehr</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.time.colon.odin-ehr</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.second.odin-ehr</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>meta.time.fraction.odin-ehr</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.time.comma.odin-ehr</string>
						</dict>
						<key>8</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.second.odin-ehr</string>
						</dict>
						<key>9</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.timezone.odin-ehr</string>
						</dict>
						<key>10</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.timezone.odin-ehr</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>((\d{4})(-)(\d{2})(-)(\d{2})(T))((\d{2})(?:(:)(\d{2}))?)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.date.partial.odin-ehr</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.year.odin-ehr</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.date.dash.odin-ehr</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.month.odin-ehr</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.date.dash.odin-ehr</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.day.odin-ehr</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>constant.language.datetime-separator.odin-ehr</string>
						</dict>
						<key>8</key>
						<dict>
							<key>name</key>
							<string>meta.time.partial.odin-ehr</string>
						</dict>
						<key>9</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.hour.odin-ehr</string>
						</dict>
						<key>10</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.time.colon.odin-ehr</string>
						</dict>
						<key>11</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.minute.odin-ehr</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.date.odin-ehr</string>
					<key>match</key>
					<string>(\d{4})(-)(\d{2})(-)(\d{2})(T(?=\d{2}))?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.year.odin-ehr</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.date.dash.odin-ehr</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.month.odin-ehr</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.date.dash.odin-ehr</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.day.odin-ehr</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>constant.language.datetime-separator.odin-ehr</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.date.partial.odin-ehr</string>
					<key>match</key>
					<string>(\d{4})(-)(\d{2})</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.year.odin-ehr</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.date.dash.odin-ehr</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.month.odin-ehr</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.time.partial.odin-ehr</string>
					<key>match</key>
					<string>(\d{2})(:)(\d{2})</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.hour.odin-ehr</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.time.colon.odin-ehr</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.minute.odin-ehr</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.other.duration.odin-ehr</string>
					<key>match</key>
					<string>P(?:T?\d+T?[YMWDHMS])+</string>
				</dict>
			</array>
		</dict>
		<key>escape</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.character.escape.odin-ehr</string>
					<key>match</key>
					<string>(\\)[rnt\\&quot;&apos;]</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.escape.backslash.odin-ehr</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.escape.codepoint.odin-ehr</string>
					<key>match</key>
					<string>(\\)u(?:[0-9A-Fa-f]{4}){1,2}</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.escape.backslash.odin-ehr</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.entity.odin-ehr</string>
					<key>match</key>
					<string>(&amp;)\w+(;)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entity.begin.odin-ehr</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entity.end.odin-ehr</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>invalid.illegal.bad-escape.odin-ehr</string>
					<key>match</key>
					<string>\\.</string>
				</dict>
			</array>
		</dict>
		<key>infinity</key>
		<dict>
			<key>name</key>
			<string>constant.language.numeric.infinity.odin-ehr</string>
			<key>match</key>
			<string>(?i)(?:-|\b)infinity\b|\*</string>
		</dict>
		<key>interval</key>
		<dict>
			<key>name</key>
			<string>meta.interval.odin-ehr</string>
			<key>begin</key>
			<string>\|</string>
			<key>end</key>
			<string>\|</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>([-+]?(?:[\de]|\.(?=[-+\de]))+)(\.\.)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>etc#num</string>
								</dict>
							</array>
						</dict>
						<key>2</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>etc#dotPair</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.comparison.odin-ehr</string>
					<key>match</key>
					<string>&gt;=|&lt;=|&gt;|&lt;</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.variance.odin-ehr</string>
					<key>match</key>
					<string>\+/-</string>
				</dict>
				<dict>
					<key>name</key>
					<string>invalid.illegal.unexpected-comma.odin-ehr</string>
					<key>match</key>
					<string>,</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#infinity</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#date</string>
				</dict>
				<dict>
					<key>include</key>
					<string>etc#dotPair</string>
				</dict>
				<dict>
					<key>include</key>
					<string>etc#num</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.interval.begin.odin─ehr</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.interval.end.odin─ehr</string>
				</dict>
			</dict>
		</dict>
		<key>key</key>
		<dict>
			<key>name</key>
			<string>meta.key.member.item-access.odin-ehr</string>
			<key>begin</key>
			<string>\[</string>
			<key>end</key>
			<string>\]</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#main</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>etc#bracket</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>etc#bracket</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>main</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#date</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#path</string>
				</dict>
				<dict>
					<key>include</key>
					<string>etc#num</string>
				</dict>
				<dict>
					<key>include</key>
					<string>etc#url</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#interval</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#schema</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#attribute</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#type</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#plugin</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#typedef</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#term</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#key</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#escape</string>
				</dict>
				<dict>
					<key>include</key>
					<string>etc#ellipsis</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.delimiter.comma.odin-ehr</string>
					<key>match</key>
					<string>,</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.odin-ehr</string>
					<key>match</key>
					<string>=</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.terminator.statement.odin-ehr</string>
					<key>match</key>
					<string>;</string>
				</dict>
			</array>
		</dict>
		<key>path</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.path-segment.odin-ehr</string>
					<key>contentName</key>
					<string>meta.object-id.odin-ehr</string>
					<key>begin</key>
					<string>(?x)
(?:(//?)([A-Za-z0-9_]+)|(//?))
((\[))</string>
					<key>end</key>
					<string>(\])</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#main</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#pathSep</string>
								</dict>
							</array>
						</dict>
						<key>2</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#attribute</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#type</string>
								</dict>
							</array>
						</dict>
						<key>3</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#pathSep</string>
								</dict>
							</array>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>meta.object-id.odin-ehr</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.object-id.begin.odin-ehr</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.object-id.odin-ehr</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.object-id.end.odin-ehr</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.path-segment.odin-ehr</string>
					<key>match</key>
					<string>(//?)([A-Za-z0-9_]+)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#pathSep</string>
								</dict>
							</array>
						</dict>
						<key>2</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#attribute</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#type</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>include</key>
					<string>#pathSep</string>
				</dict>
			</array>
		</dict>
		<key>pathSep</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>punctuation.separator.path.double-slash.odin-ehr</string>
					<key>match</key>
					<string>//</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.separator.path.slash.odin-ehr</string>
					<key>match</key>
					<string>/</string>
				</dict>
			</array>
		</dict>
		<key>plugin</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>markup.code.other.odin-ehr</string>
					<key>contentName</key>
					<string>source.embedded.${3:/downcase}.odin-ehr</string>
					<key>begin</key>
					<string>((\()\s*(\w+)\s*(\)))\s*((&lt;#))</string>
					<key>end</key>
					<string>(#&gt;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#pluginInnards</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.type.odin-ehr</string>
						</dict>
						<key>2</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>etc#bracket</string>
								</dict>
							</array>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>storage.type.class.syntax.odin-ehr</string>
						</dict>
						<key>4</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>etc#bracket</string>
								</dict>
							</array>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>meta.block.plugin.odin-ehr</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.plugin.block.begin.odin-ehr</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.block.plugin.odin-ehr</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.plugin.block.end.odin-ehr</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.block.plugin.odin-ehr</string>
					<key>contentName</key>
					<string>markup.raw.code.other.odin-ehr</string>
					<key>begin</key>
					<string>&lt;#</string>
					<key>end</key>
					<string>#&gt;</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#pluginInnards</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.block.begin.odin-ehr</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.block.end.odin-ehr</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>pluginInnards</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>match</key>
					<string>{|}</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>etc#bracket</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>schema</key>
		<dict>
			<key>name</key>
			<string>variable.other.schema.odin-ehr</string>
			<key>match</key>
			<string>(@)[A-Za-z0-9_]+</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.schema.odin-ehr</string>
				</dict>
			</dict>
		</dict>
		<key>string</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>string.quoted.double.odin-ehr</string>
					<key>begin</key>
					<string>&quot;</string>
					<key>end</key>
					<string>&quot;</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escape</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.odin-ehr</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.odin-ehr</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>string.quoted.single.odin-ehr</string>
					<key>begin</key>
					<string>&apos;</string>
					<key>end</key>
					<string>&apos;</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escape</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.odin-ehr</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.odin-ehr</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>term</key>
		<dict>
			<key>name</key>
			<string>meta.coded-term.odin-ehr</string>
			<key>begin</key>
			<string>\[(?=[^\]:]+::)</string>
			<key>end</key>
			<string>\]</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.other.coded-term.name.odin-ehr</string>
					<key>match</key>
					<string>\G\s*([-\w]+)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.separator.key-value.odin-ehr</string>
					<key>match</key>
					<string>::</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.other.coded-term.code.odin-ehr</string>
					<key>match</key>
					<string>[-.\w]+</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#termVersion</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#main</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.coded-term.begin.odin-ehr</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.coded-term.end.odin-ehr</string>
				</dict>
			</dict>
		</dict>
		<key>termVersion</key>
		<dict>
			<key>name</key>
			<string>meta.term-version.odin-ehr</string>
			<key>begin</key>
			<string>\(</string>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#num</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#termVersion</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>etc#bracket</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>etc#bracket</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>type</key>
		<dict>
			<key>name</key>
			<string>storage.type.name.odin-ehr</string>
			<key>match</key>
			<string>\b(?=[A-Z])[A-Za-z0-9_]+</string>
		</dict>
		<key>typedef</key>
		<dict>
			<key>name</key>
			<string>meta.type.odin-ehr</string>
			<key>begin</key>
			<string>\(</string>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#main</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>etc#bracket</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>etc#bracket</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>odin</string>
	</array>
</dict>
</plist>
