<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Oz</string>
	<key>scopeName</key>
	<string>source.oz</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>name</key>
			<string>comment.line.percentage.oz</string>
			<key>match</key>
			<string>(%).*$\n?</string>
		</dict>
		<dict>
			<key>name</key>
			<string>comment.block.documentation.oz</string>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.control.oz</string>
			<key>match</key>
			<string>(?x)\b(
                andthen|at|attr|case|catch|class|choice|cond|
                declare|define|do|dis|else|elsecase|elseif|
                end|export|feat|finally|for|from|fun|functor|
                if|in|import|lex|local|lock|meth|mode|not|of|
                or|orelse|parser|prepare|proc|prod|prop|raise|require|
                scanner|skip|syn|then|thread|token|try)\b
            |
                ^\s*\[\]</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.operator.assignement.oz</string>
			<key>match</key>
			<string>=|:=</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.operator.comparison.oz</string>
			<key>match</key>
			<string>&lt;|=&lt;|==|\\=|&gt;=|&gt;</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.operator.arithmetic.oz</string>
			<key>match</key>
			<string>(\*|\+|\-|/|~)|\b(div|mod)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.numeric.oz</string>
			<key>match</key>
			<string>\b(\d+)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.language.oz</string>
			<key>match</key>
			<string>\b(nil|true|false)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.operator.list.oz</string>
			<key>match</key>
			<string>\b\|\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.function.oz</string>
			<key>match</key>
			<string>(?x)
			         \b(fun|proc)\b\s+
			         \{(\w+)
			            ((?:\s\w+)*)
			         \}</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.proc.oz</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.oz</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.function.oz</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>punctuation.section.array.oz</string>
			<key>match</key>
			<string>\[|\]</string>
		</dict>
		<dict>
			<key>name</key>
			<string>string.quoted.simple.oz</string>
			<key>begin</key>
			<string>&apos;</string>
			<key>end</key>
			<string>&apos;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.character.escape.oz</string>
					<key>match</key>
					<string>\\.</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>name</key>
			<string>variable.other.readwrite.cell.oz</string>
			<key>match</key>
			<string>(@)[A-Z]\w*</string>
		</dict>
	</array>
	<key>fileTypes</key>
	<array>
		<string>oz</string>
	</array>
</dict>
</plist>
