<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Pact</string>
	<key>scopeName</key>
	<string>source.pact</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#sexp</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#reserved</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#type</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#list</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#object</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#literal</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#symbol</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#metas</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#let</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>arglist</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;=\()</string>
			<key>end</key>
			<string>(?=\))</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>variable.name.arg.pact</string>
					<key>match</key>
					<string>([\w%#+\-_&amp;\$@&lt;&gt;=\?\*!\|/]+)</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#type</string>
				</dict>
			</array>
		</dict>
		<key>atom</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>([\w%#+-_&amp;\$@&lt;&gt;=\?\*!\|/]+)</string>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>name</key>
			<string>comment.line.semicolon.pact</string>
			<key>match</key>
			<string>(;).*$\n?</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.pact</string>
				</dict>
			</dict>
		</dict>
		<key>deflam</key>
		<dict>
			<key>name</key>
			<string>meta.definition.global.pact</string>
			<key>begin</key>
			<string>(?&lt;=\()(defun|defpact|defcap)\s+([\w%#+\-_&amp;\$@&lt;&gt;=\?\*!\|/]+)</string>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#arglist</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#type</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.reserved.pact</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.function.name.pact</string>
				</dict>
			</dict>
		</dict>
		<key>defsimple</key>
		<dict>
			<key>name</key>
			<string>meta.definition.global.pact</string>
			<key>begin</key>
			<string>(?&lt;=\()(defconst|defschema|deftable|module|interface)\s+([\w%#+-_&amp;\$@&lt;&gt;=\?\*!\|/]+)\b</string>
			<key>end</key>
			<string>(?=\))</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.reserved.pact</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.function.name.pact</string>
				</dict>
			</dict>
		</dict>
		<key>let</key>
		<dict>
			<key>name</key>
			<string>meta.let.declaration.pact</string>
			<key>begin</key>
			<string>\((let\*?)\s</string>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.let.bindings.pact</string>
					<key>begin</key>
					<string>\(</string>
					<key>end</key>
					<string>(?=\))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>meta.let.binding.pact</string>
							<key>begin</key>
							<string>\(([\w%#+\-_&amp;\$@&lt;&gt;=\?\*!\|/]+)\b</string>
							<key>end</key>
							<string>\)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>$self</string>
								</dict>
							</array>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>variable.let.pact</string>
								</dict>
							</dict>
						</dict>
					</array>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.let.pact</string>
				</dict>
			</dict>
		</dict>
		<key>list</key>
		<dict>
			<key>name</key>
			<string>meta.list.pact</string>
			<key>begin</key>
			<string>(\[)</string>
			<key>end</key>
			<string>(\](?=[\}\]\)\s]*(?:;|$)))|(\])</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.list.begin.pact</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.list.end.trailing.pact</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.list.end.pact</string>
				</dict>
			</dict>
		</dict>
		<key>literal</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.language.boolean.pact</string>
					<key>match</key>
					<string>(true|false)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.double.pact</string>
					<key>match</key>
					<string>\b(-?\d+\.\d+)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.integer.pact</string>
					<key>match</key>
					<string>\b(-?\d+)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.binder.pact</string>
					<key>match</key>
					<string>(:=?)</string>
				</dict>
			</array>
		</dict>
		<key>metas</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>variable.language.metas.pact</string>
					<key>match</key>
					<string>@\w+</string>
				</dict>
			</array>
		</dict>
		<key>object</key>
		<dict>
			<key>name</key>
			<string>meta.object.pact</string>
			<key>begin</key>
			<string>(\{)</string>
			<key>end</key>
			<string>(\}(?=[\}\]\)\s]*(?:;|$)))|(\})</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(:=)</string>
					<key>end</key>
					<string>([\w%#+\-_&amp;\$@&lt;&gt;=\?\*!\|/]+)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.binder.pact</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.binder.pact</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.object.begin.pact</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.object.end.trailing.pact</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.object.end.pact</string>
				</dict>
			</dict>
		</dict>
		<key>reserved</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.reserved.pact</string>
					<key>match</key>
					<string>\b(module|interface|list|let|let\*|defun|defpact|defconst|defschema|deftable|defcap|step|use|step-with-rollback|invariants?|properties|property|defproperty|bless|implements)\b</string>
				</dict>
			</array>
		</dict>
		<key>sexp</key>
		<dict>
			<key>name</key>
			<string>meta.expression.pact</string>
			<key>begin</key>
			<string>(\()</string>
			<key>end</key>
			<string>(\))(\n)|(\)(?=[\}\]\)\s]*(?:;|$)))|(\))</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#deflam</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#defsimple</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#reserved</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#list</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#object</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#let</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#sexp</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=\()(.+?)(?=\s|\))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.pact</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.expression.begin.pact</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.expression.end.trailing.pact</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.after-expression.pact</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.expression.end.trailing.pact</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.expression.end.pact</string>
				</dict>
			</dict>
		</dict>
		<key>string</key>
		<dict>
			<key>name</key>
			<string>string.quoted.double.pact</string>
			<key>begin</key>
			<string>(?&lt;!\\)(&quot;)</string>
			<key>end</key>
			<string>(?&lt;!\\)(&quot;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.pact</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.pact</string>
				</dict>
			</dict>
		</dict>
		<key>symbol</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>string.quoted.symbol.pact</string>
					<key>begin</key>
					<string>&apos;</string>
					<key>end</key>
					<string>(?=\s|[],:&quot;&apos;.)])</string>
				</dict>
			</array>
		</dict>
		<key>type</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?:[:])(integer|decimal|time|bool|string|list|value|keyset|guard|(object|table)?\{[\w%#+\-\._&amp;\$@&lt;&gt;=\?\*!\|/]+\}|object|table)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.reserved.type.pact</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>pact</string>
	</array>
</dict>
</plist>
