<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Pike</string>
	<key>scopeName</key>
	<string>source.pike</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>name</key>
			<string>storage.modifier.pike</string>
			<key>match</key>
			<string>\b(public|nomask|private|optional|local|final|static)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.control.pike</string>
			<key>match</key>
			<string>\b(import|inherit|this|foreach|break|continue|while|do|return|if|else|case|switch)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.type.pike</string>
			<key>match</key>
			<string>\b(constant|int|float|string|array|mapping|multiset|program|class|object|mixed|void)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.language.pike</string>
			<key>match</key>
			<string>\b(UNDEFINED)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.numeric.pike</string>
			<key>match</key>
			<string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>string.quoted.double.pike</string>
			<key>begin</key>
			<string>&quot;</string>
			<key>end</key>
			<string>&quot;</string>
		</dict>
		<dict>
			<key>name</key>
			<string>string.quoted.single.pike</string>
			<key>begin</key>
			<string>&apos;</string>
			<key>end</key>
			<string>&apos;</string>
		</dict>
		<dict>
			<key>name</key>
			<string>comment.block.pike</string>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
		</dict>
		<dict>
			<key>name</key>
			<string>comment.line.double-slash.pike</string>
			<key>match</key>
			<string>//.*$</string>
		</dict>
		<dict>
			<key>name</key>
			<string>other.preprocessor.pike</string>
			<key>match</key>
			<string>^[ \t]*#[a-zA-Z]+</string>
		</dict>
	</array>
	<key>fileTypes</key>
	<array>
		<string>pike</string>
		<string>pmod</string>
	</array>
</dict>
</plist>
