<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>PostScript</string>
	<key>scopeName</key>
	<string>source.postscript</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>name</key>
			<string>meta.document.pdf</string>
			<key>begin</key>
			<string>\A(?=%PDF)</string>
			<key>end</key>
			<string>(?=A)B</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#main</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.ai-prefs.postscript</string>
			<key>begin</key>
			<string>\A(?=/(?:(?:Menus|collection1|precision) {|textImportantVisualLinesSnapping \d)(?:\r|$))</string>
			<key>end</key>
			<string>(?=A)B</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#main</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#main</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>array</key>
		<dict>
			<key>name</key>
			<string>meta.array.postscript</string>
			<key>begin</key>
			<string>\[</string>
			<key>end</key>
			<string>\]</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#main</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.array.begin.postscript</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.array.end.postscript</string>
				</dict>
			</dict>
		</dict>
		<key>base85</key>
		<dict>
			<key>name</key>
			<string>string.other.base85.postscript</string>
			<key>begin</key>
			<string>&lt;~</string>
			<key>end</key>
			<string>~&gt;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>invalid.illegal.base85.char.postscript</string>
					<key>match</key>
					<string>(?:[^!-uz\s]|~(?!&gt;))++</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.postscript</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.postscript</string>
				</dict>
			</dict>
		</dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.comment.leading.postscript</string>
					<key>match</key>
					<string>^[ \t]+(?=%)</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dsc</string>
				</dict>
				<dict>
					<key>name</key>
					<string>comment.line.percentage.postscript</string>
					<key>begin</key>
					<string>%</string>
					<key>end</key>
					<string>(?=$|\r|\f)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.postscript</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>dictionary</key>
		<dict>
			<key>name</key>
			<string>meta.dictionary.postscript</string>
			<key>begin</key>
			<string>&lt;&lt;</string>
			<key>end</key>
			<string>&gt;&gt;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#main</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.dictionary.begin.postscript</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.dictionary.end.postscript</string>
				</dict>
			</dict>
		</dict>
		<key>dsc</key>
		<dict>
			<key>name</key>
			<string>meta.Document-Structuring-Comment.postscript</string>
			<key>contentName</key>
			<string>string.unquoted.DSC.postscript</string>
			<key>begin</key>
			<string>(?x) ^ (%%)
( BeginBinary
| BeginCustomColor
| BeginData
| BeginDefaults
| BeginDocument
| BeginEmulation
| BeginExitServer
| BeginFeature
| BeginFile
| BeginFont
| BeginObject
| BeginPageSetup
| BeginPaperSize
| BeginPreview
| BeginProcSet
| BeginProcessColor
| BeginProlog
| BeginResource
| BeginSetup
| BoundingBox
| CMYKCustomColor
| ChangeFont
| Copyright
| CreationDate
| Creator
| DocumentCustomColors
| DocumentData
| DocumentFonts
| DocumentMedia
| DocumentNeededFiles
| DocumentNeededFonts
| DocumentNeededProcSets
| DocumentNeededResources
| DocumentPaperColors
| DocumentPaperForms
| DocumentPaperSizes
| DocumentPaperWeights
| DocumentPrinterRequired
| DocumentProcSets
| DocumentProcessColors
| DocumentSuppliedFiles
| DocumentSuppliedFonts
| DocumentSuppliedProcSets
| DocumentSuppliedResources
| EOF
| Emulation
| EndBinary
| EndComments
| EndCustomColor
| EndData
| EndDefaults
| EndDocument
| EndEmulation
| EndExitServer
| EndFeature
| EndFile
| EndFont
| EndObject
| EndPageSetup
| EndPaperSize
| EndPreview
| EndProcSet
| EndProcessColor
| EndProlog
| EndResource
| EndSetup
| ExecuteFile
| Extensions
| Feature
| For
| IncludeDocument
| IncludeFeature
| IncludeFile
| IncludeFont
| IncludeProcSet
| IncludeResource
| LanguageLevel
| OperatorIntervention
| OperatorMessage
| Orientation
| PageBoundingBox
| PageCustomColors
| PageFiles
| PageFonts
| PageMedia
| PageOrder
| PageOrientation
| PageProcessColors
| PageRequirements
| PageResources
| PageTrailer
| Pages
| Page
| PaperColor
| PaperForm
| PaperSize
| PaperWeight
| ProofMode
| RGBCustomColor
| Requirements
| Routing
| Title
| Trailer
| VMlocation
| VMusage
| Version
| \+
| \?BeginFeatureQuery
| \?BeginFileQuery
| \?BeginFontListQuery
| \?BeginFontQuery
| \?BeginPrinterQuery
| \?BeginProcSetQuery
| \?BeginQuery
| \?BeginResourceListQuery
| \?BeginResourceQuery
| \?BeginVMStatus
| \?EndFeatureQuery
| \?EndFileQuery
| \?EndFontListQuery
| \?EndFontQuery
| \?EndPrinterQuery
| \?EndProcSetQuery
| \?EndQuery
| \?EndResourceListQuery
| \?EndResourceQuery
| \?EndVMStatus
) (:)? [^\S\r\n]*</string>
			<key>end</key>
			<string>(?=$|\r|\f)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.other.DSC.postscript</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.keyword.DSC.postscript</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.key-value.colon.postscript</string>
				</dict>
			</dict>
		</dict>
		<key>embedded</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>contentName</key>
					<string>string.unquoted.heredoc.postscript</string>
					<key>begin</key>
					<string>(?&lt;![^/\s{}()&lt;&gt;\[\]%])\b(currentfile)\s+((?=\S)[^{}%]+?)\s+(readline)(?!\s*})\b(?![^/\s{}()&lt;&gt;\[\]%])(?:$\s*)?</string>
					<key>end</key>
					<string>(?!\G)$</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.postscript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#main</string>
								</dict>
							</array>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.postscript</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.encrypted-source.base85.postscript</string>
					<key>contentName</key>
					<string>string.other.base85.postscript</string>
					<key>begin</key>
					<string>(?&lt;![^/\s{}()&lt;&gt;\[\]%])\b(currentfile)\s*((/)ASCII85Decode)\s+(filter)\b(?![^/\s{}()&lt;&gt;\[\]%])([^}&gt;\]%]*?(?:exec|image|readstring)\s*)$\s*+</string>
					<key>end</key>
					<string>~&gt;|(?=cleartomark|closefile)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.postscript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.literal.postscript</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.name.postscript</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.postscript</string>
						</dict>
						<key>5</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#main</string>
								</dict>
							</array>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.postscript</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.encrypted-source.eexec.postscript</string>
					<key>begin</key>
					<string>(?&lt;![^/\s{}()&lt;&gt;\[\]%])\b(currentfile)\s+(eexec)(?:$|(?=.*[\0-\x08\x14-\x31\x7F\x80-\x9F])(?=.{0,3}?[^A-Fa-f0-9]|\b[A-Fa-f0-9]))</string>
					<key>end</key>
					<string>(cleartomark|closefile)\b(?![^/\s{}()&lt;&gt;\[\]%])|(?&lt;=\G)(?=[^\s0-9A-Fa-f])</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>\G(?=\s*$)</string>
							<key>end</key>
							<string>(?=\s*\S)</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?:\G|(?&lt;=\n|^))\s*(?=\S)</string>
							<key>end</key>
							<string>(?!\G)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>name</key>
									<string>string.other.raw.binary.postscript</string>
									<key>contentName</key>
									<string>sublimelinter.gutter-mark</string>
									<key>begin</key>
									<string>\G(?!cleartomark|closefile)(?=.{0,3}?[^A-Fa-f0-9])</string>
									<key>end</key>
									<string>(?=\s*(?:cleartomark|closefile))</string>
								</dict>
								<dict>
									<key>name</key>
									<string>string.other.hexadecimal.postscript</string>
									<key>begin</key>
									<string>\G(?!cleartomark|closefile)(?=\s{0,3}?(?:[A-Fa-f0-9]))</string>
									<key>end</key>
									<string>(?=\s*[^A-Fa-f0-9\s]|cleartomark|closefile)</string>
								</dict>
							</array>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.postscript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.postscript</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.postscript</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>embeddedRow</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>string.other.base85.postscript</string>
					<key>match</key>
					<string>^[!-uz]{0,78}(~&gt;)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.postscript</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>string.other.base85.postscript</string>
					<key>begin</key>
					<string>(?x) ^
(?= [^%\[]*? \]
|   [^%(]*?   \)
|   [^%&lt;]*?   &gt;
|   .*? &lt;(?!~|&lt;) [A-Fa-f0-9]* [^~&gt;A-Fa-f0-9]
) [!-uz]{60,80} [^\S\r\n]* $</string>
					<key>end</key>
					<string>^[!-uz]{0,78}(~&gt;)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.postscript</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>extensions</key>
		<dict>
			<key>name</key>
			<string>keyword.operator.ghostscript.postscript</string>
			<key>match</key>
			<string>(?x) (?&lt;![^/\s{}()&lt;&gt;\[\]%]) (?:\b|(?=\.))
( \.activatepathcontrol
| \.addcontrolpath
| \.begintransparencygroup
| \.begintransparencymaskgroup
| \.bind
| \.bindnow
| \.currentalphaisshape
| \.currentblendmode
| \.currentfillconstantalpha
| \.currentopacityalpha
| \.currentoverprintmode
| \.currentpathcontrolstate
| \.currentshapealpha
| \.currentstrokeconstantalpha
| \.currenttextknockout
| \.dicttomark
| \.endtransparencygroup
| \.endtransparencymask
| \.fileposition
| \.genordered
| \.knownget
| \.locksafe
| \.popdf14devicefilter
| \.pushpdf14devicefilter
| \.setalphaisshape
| \.setblendmode
| \.setdebug
| \.setfillconstantalpha
| \.setopacityalpha
| \.setoverprintmode
| \.setsafe
| \.setshapealpha
| \.setstrokeconstantalpha
| \.settextknockout
| \.shellarguments
| \.tempfile
| %Type1BuildChar
| %Type1BuildGlyph
| arccos
| arcsin
| copydevice
| copyscanlines
| currentdevice
| finddevice
| findlibfile
| findprotodevice
| getdeviceprops
| getenv
| makeimagedevice
| max
| min
| putdeviceprops
| setdevice
) \b (?![^/\s{}()&lt;&gt;\[\]%])</string>
		</dict>
		<key>hex</key>
		<dict>
			<key>name</key>
			<string>string.other.hexadecimal.postscript</string>
			<key>begin</key>
			<string>&lt;</string>
			<key>end</key>
			<string>&gt;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>invalid.illegal.hexadecimal.char.postscript</string>
					<key>match</key>
					<string>[^&gt;0-9A-Fa-f\s]+</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.postscript</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.postscript</string>
				</dict>
			</dict>
		</dict>
		<key>main</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dictionary</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#array</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#procedure</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#base85</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#hex</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#radix</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#extensions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embeddedRow</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#names</string>
				</dict>
			</array>
		</dict>
		<key>names</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>variable.other.constant.immediately-evaluated.postscript</string>
					<key>match</key>
					<string>(//)[^()&lt;&gt;\[\]{}/%\s]*</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.name.postscript</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>variable.other.constant.literal.postscript</string>
					<key>match</key>
					<string>(/)[^()&lt;&gt;\[\]{}/%\s]*</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.name.postscript</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>variable.other.executable.postscript</string>
					<key>match</key>
					<string>[^()&lt;&gt;\[\]{}/%\s]+</string>
				</dict>
			</array>
		</dict>
		<key>number</key>
		<dict>
			<key>name</key>
			<string>constant.numeric.postscript</string>
			<key>match</key>
			<string>[-+]?(?:\d+(?:\.\d*)?|\.\d+)(?:[Ee][-+]?\d+)?(?=$|[\s\[\]{}(/%&lt;])</string>
		</dict>
		<key>operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.operator.level-3.postscript</string>
					<key>match</key>
					<string>(?x) (?&lt;![^/\s{}()&lt;&gt;\[\]%]) \b
( GetHalftoneName
| GetPageDeviceName
| GetSubstituteCRD
| StartData
| StartData
| addglyph
| beginbfchar
| beginbfrange
| begincidchar
| begincidrange
| begincmap
| begincodespacerange
| beginnotdefchar
| beginnotdefrange
| beginrearrangedfont
| beginusematrix
| cliprestore
| clipsave
| composefont
| currentsmoothness
| currenttrapparams
| endbfchar
| endbfrange
| endcidchar
| endcidrange
| endcmap
| endcodespacerange
| endnotdefchar
| endnotdefrange
| endrearrangedfont
| endusematrix
| findcolorrendering
| removeall
| removeglyphs
| setsmoothness
| settrapparams
| settrapzone
| shfill
| usecmap
| usefont
) \b (?![^/\s{}()&lt;&gt;\[\]%])</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.level-2.postscript</string>
					<key>match</key>
					<string>(?x) (?&lt;![^/\s{}()&lt;&gt;\[\]%]) \b
( GlobalFontDirectory
| ISOLatin1Encoding
| SharedFontDirectory
| UserObjects
| arct
| colorimage
| configurationerror
| cshow
| currentblackgeneration
| currentcacheparams
| currentcmykcolor
| currentcolorrendering
| currentcolorscreen
| currentcolorspace
| currentcolortransfer
| currentcolor
| currentdevparams
| currentglobal
| currentgstate
| currenthalftone
| currentobjectformat
| currentoverprint
| currentpacking
| currentpagedevice
| currentshared
| currentstrokeadjust
| currentsystemparams
| currentundercolorremoval
| currentuserparams
| defineresource
| defineuserobject
| deletefile
| execform
| execuserobject
| filenameforall
| fileposition
| filter
| findencoding
| findresource
| gcheck
| globaldict
| glyphshow
| gstate
| ineofill
| infill
| instroke
| inueofill
| inufill
| inustroke
| languagelevel
| makepattern
| packedarray
| printobject
| product
| realtime
| rectclip
| rectfill
| rectstroke
| renamefile
| resourceforall
| resourcestatus
| revision
| rootfont
| scheck
| selectfont
| serialnumber
| setbbox
| setblackgeneration
| setcachedevice2
| setcacheparams
| setcmykcolor
| setcolorrendering
| setcolorscreen
| setcolorspace
| setcolortransfer
| setcolor
| setdevparams
| setfileposition
| setglobal
| setgstate
| sethalftone
| setobjectformat
| setoverprint
| setpacking
| setpagedevice
| setpattern
| setshared
| setstrokeadjust
| setsystemparams
| setucacheparams
| setundercolorremoval
| setuserparams
| setvmthreshold
| shareddict
| startjob
| uappend
| ucachestatus
| ucache
| ueofill
| ufill
| undefinedresource
| undefinefont
| undefineresource
| undefineuserobject
| undef
| upath
| ustrokepath
| ustroke
| vmreclaim
| writeobject
| xshow
| xyshow
| yshow
) \b (?![^/\s{}()&lt;&gt;\[\]%])</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.level-1.postscript</string>
					<key>match</key>
					<string>(?x) (?&lt;![^/\s{}()&lt;&gt;\[\]%]) \b
( FontDirectory
| StandardEncoding
| VMerror
| abs
| add
| aload
| anchorsearch
| and
| arcn
| arcto
| arc
| array
| ashow
| astore
| atan
| awidthshow
| begin
| bind
| bitshift
| bytesavailable
| cachestatus
| ceiling
| charpath
| cleardictstack
| cleartomark
| clear
| clippath
| clip
| closefile
| closepath
| colorimage
| concatmatrix
| concat
| condition
| copypage
| copy
| cos
| countdictstack
| countexecstack
| counttomark
| count
| currentcontext
| currentdash
| currentdict
| currentfile
| currentflat
| currentfont
| currentgray
| currenthalftonephase
| currenthsbcolor
| currentlinecap
| currentlinejoin
| currentlinewidth
| currentmatrix
| currentmiterlimit
| currentpoint
| currentrgbcolor
| currentscreen
| currenttransfer
| curveto
| cvi
| cvlit
| cvn
| cvrs
| cvr
| cvs
| cvx
| defaultmatrix
| definefont
| defineusername
| def
| detach
| deviceinfo
| dictfull
| dictstackoverflow
| dictstackunderflow
| dictstack
| dict
| div
| dtransform
| dup
| echo
| eexec
| end
| eoclip
| eofill
| eoviewclip
| eq
| erasepage
| errordict
| exch
| execstackoverflow
| execstack
| executeonly
| executive
| exec
| exitserver
| exit
| exp
| false
| file
| fill
| findfont
| flattenpath
| floor
| flushfile
| flush
| forall
| fork
| for
| getinterval
| get
| ge
| grestoreall
| grestore
| gsave
| gt
| handleerror
| identmatrix
| idiv
| idtransform
| ifelse
| if
| imagemask
| image
| index
| initclip
| initgraphics
| initmatrix
| initviewclip
| internaldict
| interrupt
| invalidaccess
| invalidcontext
| invalidexit
| invalidfileaccess
| invalidfont
| invalidid
| invalidrestore
| invertmatrix
| ioerror
| itransform
| known
| kshow
| length
| le
| limitcheck
| lineto
| ln
| load
| lock
| log
| loop
| lt
| makefont
| mark
| matrix
| maxlength
| mod
| monitor
| moveto
| mul
| neg
| newpath
| ne
| noaccess
| nocurrentpoint
| notify
| not
| nulldevice
| null
| or
| pathbbox
| pathforall
| pdfmark
| pop
| print
| prompt
| pstack
| putinterval
| put
| quit
| rand
| rangecheck
| rcheck
| rcurveto
| readhexstring
| readline
| readonly
| readstring
| read
| rectviewclip
| repeat
| resetfile
| restore
| reversepath
| rlineto
| rmoveto
| roll
| rotate
| round
| rrand
| run
| save
| scalefont
| scale
| search
| serverdict
| setcachedevice
| setcachelimit
| setcharwidth
| setdash
| setflat
| setfont
| setgray
| sethalftonephase
| sethsbcolor
| setlinecap
| setlinejoin
| setlinewidth
| setmatrix
| setmiterlimit
| setrgbcolor
| setscreen
| settransfer
| showpage
| show
| sin
| sqrt
| srand
| stackoverflow
| stackunderflow
| stack
| start
| statusdict
| status
| stopped
| stop
| store
| stringwidth
| string
| strokepath
| stroke
| sub
| syntaxerror
| systemdict
| timeout
| token
| transform
| translate
| true
| truncate
| typecheck
| type
| undefinedfilename
| undefinedresult
| undefined
| unmatchedmark
| unregistered
| userdict
| usertime
| version
| viewclippath
| viewclip
| vmstatus
| wait
| wcheck
| where
| widthshow
| writehexstring
| writestring
| write
| wtranslation
| xcheck
| xor
| yield
) \b (?![^/\s{}()&lt;&gt;\[\]%])
|
# Stuff that starts with a non-word character
(?&lt;=^|[/\s{}()&lt;&gt;\[\]%])
(=?=|\$error)
(?=$|[/\s{}()&lt;&gt;\[\]%])</string>
				</dict>
			</array>
		</dict>
		<key>procedure</key>
		<dict>
			<key>name</key>
			<string>meta.procedure.postscript</string>
			<key>begin</key>
			<string>{</string>
			<key>end</key>
			<string>}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#main</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.procedure.begin.postscript</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.procedure.end.postscript</string>
				</dict>
			</dict>
		</dict>
		<key>radix</key>
		<dict>
			<key>name</key>
			<string>constant.numeric.radix.postscript</string>
			<key>match</key>
			<string>[0-3]?[0-9]#[0-9a-zA-Z]+</string>
		</dict>
		<key>specialFiles</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.language.device-name.$2-device.postscript</string>
					<key>match</key>
					<string>\G(%)([-\w]+)(?=%|\)|$)(%)?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.device-name.begin.postscript</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.device-name.end.postscript</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.special-file.stdio.$2.postscript</string>
					<key>match</key>
					<string>\G(%)(stderr|stdin|stdout)(?=\)|$)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.special-file.begin.postscript</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.special-file.end.postscript</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.special-file.interactive.$2.postscript</string>
					<key>match</key>
					<string>\G(%)(lineedit|statementedit)(?=\)|$)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.special-file.begin.postscript</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.special-file.end.postscript</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>name</key>
			<string>string.other.postscript</string>
			<key>begin</key>
			<string>\(</string>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#stringInnards</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.postscript</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.postscript</string>
				</dict>
			</dict>
		</dict>
		<key>stringInnards</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#specialFiles</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.octal.postscript</string>
					<key>match</key>
					<string>\\[0-7]{1,3}</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.escape.postscript</string>
					<key>match</key>
					<string>\\(\\|[bfnrt()]|[0-7]{1,3}|\r?\n)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>invalid.illegal.unknown-escape.postscript.ignored</string>
					<key>match</key>
					<string>\\</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\(</string>
					<key>end</key>
					<string>\)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#stringInnards</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>injections</key>
	<dict>
		<key>L:source.postscript meta.ai-prefs.postscript - (comment | string | source.embedded | text.embedded)</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.obfuscated-setting.ai-prefs.postscript</string>
					<key>contentName</key>
					<string>meta.array.postscript</string>
					<key>begin</key>
					<string>^\s*(/(?:\\.|[^()&lt;&gt;\[\]{}/%\s])*) ((\[) (?!0\b)(\d+)(?:$|\r))</string>
					<key>end</key>
					<string>^\s*(\])|\G(?!$)|(?!\G)^(?!\s*(?:\]|[A-Fa-f0-9]+$))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>string.other.hexadecimal.postscript</string>
							<key>match</key>
							<string>[A-Fa-f0-9]+</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>$self</string>
								</dict>
							</array>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.array.postscript</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.array.begin.postscript</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.postscript</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.array.postscript</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.array.end.postscript</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>variable.other.constant.literal.postscript</string>
					<key>match</key>
					<string>(/)((?:\\.|[^()&lt;&gt;\[\]{}/%\s])*)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.name.postscript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>name</key>
									<string>constant.character.escape.postscript</string>
									<key>match</key>
									<string>(\\).</string>
									<key>captures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.escape.backslash.postscript</string>
										</dict>
									</dict>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.integer.long.postscript</string>
					<key>match</key>
					<string>[0-9]+L</string>
				</dict>
			</array>
		</dict>
		<key>L:source.postscript meta.document.pdf - (meta.encrypted-source | source.embedded | text.embedded)</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.encrypted-source.stream.pdf</string>
					<key>begin</key>
					<string>(?:^|(?&lt;=&gt;&gt;)\s*)(?=stream$)</string>
					<key>end</key>
					<string>endstream|(?=endobj\b)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>\G(stream)\s*$\s*</string>
							<key>end</key>
							<string>(?=endstream|(?=endobj\b))</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>contentName</key>
									<string>text.embedded.xml</string>
									<key>begin</key>
									<string>(&lt;\?xpacket(?=\s)[^&gt;]+\?&gt;)(?=$|&lt;x:xmpmeta)</string>
									<key>end</key>
									<string>(&lt;\?xpacket(?=\s)[^&gt;]*end\b[^&gt;]*\?&gt;)|(?=\s*(?:endstream|endobj\b))</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>text.xml</string>
										</dict>
									</array>
									<key>beginCaptures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>text.embedded.xml</string>
											<key>patterns</key>
											<array>
												<dict>
													<key>include</key>
													<string>text.xml</string>
												</dict>
											</array>
										</dict>
									</dict>
									<key>endCaptures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>text.embedded.xml</string>
											<key>patterns</key>
											<array>
												<dict>
													<key>include</key>
													<string>text.xml</string>
												</dict>
											</array>
										</dict>
									</dict>
								</dict>
								<dict>
									<key>name</key>
									<string>string.other.base85.pdf</string>
									<key>begin</key>
									<string>(?!endstream)[!-uz]{50,80}\s*$</string>
									<key>end</key>
									<string>~&gt;|(?=\s*(?:endstream|endobj\b))</string>
									<key>endCaptures</key>
									<dict>
										<key>0</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.string.end.pdf</string>
										</dict>
									</dict>
								</dict>
								<dict>
									<key>name</key>
									<string>string.other.raw.binary.pdf</string>
									<key>contentName</key>
									<string>sublimelinter.gutter-mark</string>
									<key>begin</key>
									<string>(?!endstream|[!-uz]{50,80}\s*$)(?:(?&lt;=[\n\r]|\G|^))(?=.)</string>
									<key>end</key>
									<string>(?=\s*(?:endstream|endobj\b))</string>
								</dict>
							</array>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.control.stream.begin.pdf</string>
								</dict>
							</dict>
						</dict>
					</array>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.stream.end.pdf</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;![^/\s{}()&lt;&gt;\[\]%])\b(obj)\s*(?=&lt;&lt;|$)|(?&lt;=^|\n|&gt;&gt;)(endobj)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.object.begin.pdf</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.object.end.pdf</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.control.$1.pdf</string>
					<key>match</key>
					<string>(?&lt;![^/\s{}()&lt;&gt;\[\]%])\b(trailer|startxref)(?![^/\s{}()&lt;&gt;\[\]%])</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>ps</string>
		<string>eps</string>
		<string>epsi</string>
		<string>pfa</string>
	</array>
</dict>
</plist>
