<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>POV-Ray SDL</string>
	<key>scopeName</key>
	<string>source.pov-ray sdl</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>name</key>
			<string>string.quoted.double.povray</string>
			<key>begin</key>
			<string>&quot;</string>
			<key>end</key>
			<string>&quot;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.character.escape.povray</string>
					<key>match</key>
					<string>\\.</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>name</key>
			<string>comment.block.povray</string>
			<key>begin</key>
			<string>\/\*</string>
			<key>end</key>
			<string>\*\/</string>
		</dict>
		<dict>
			<key>name</key>
			<string>comment.line.povray</string>
			<key>match</key>
			<string>\/\/.*</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.numeric.povray</string>
			<key>match</key>
			<string>\b([0-9]+(\.[0-9]*)?|\.[0-9]+)([eE][+-]?[0-9]+)?\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.operator.povray</string>
			<key>match</key>
			<string>[\+\-\*\/\&lt;\=\&gt;\{\}\(\)\[\]\.\,\;\:\?\!]</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.language.povray</string>
			<key>match</key>
			<string>\b(on|off|yes|no|true|false|pi)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.shape.povray</string>
			<key>match</key>
			<string>\b(box|cone|cylinder|difference|height_field|intersection|isosurface|julia_fractal|merge|mesh2?|object|plane|sphere|superellipsoid|text|torus|union)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.block.povray</string>
			<key>match</key>
			<string>\b(camera|clipped_by|colou?r_map|contained_by|default|density|face_indices|finish|fog|global_settings|interior|light_source|material|media|normal(_vectors)?|pigment(_map)?|photons|radiosity|reflection|scattering|texture|uv_vectors|vertex_vectors|warp)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.parameter.povray</string>
			<key>match</key>
			<string>\b(adaptive|adc_bailout|agate|ambient|angle|area_light|array|assumed_gamma|blue|bozo|brightness|bumps|checker|circular|collect|colou?r|conserve_energy|count|crackle|cylindrical|diffuse|direction|distance|dist_exp|error_bound|exponent|extinction|fade_color|fade_distance|fade_power|falloff|filter|fog_alt|fog_offset|fog_type|function|fresnel|gradient|granite|gr[ae]y_threshold|gr[ae]y|green|hollow|intervals|inverse|ior|jitter|lambda|location|look_at|low_error_factor|marble|max_gradient|max_iteration|max_trace_level|media_attenuation|media_interaction|metallic|method|minimum_reuse|nearest_count|noise_generator|no_shadow|octaves|omega|orient(ation)?|pass_through|planar|point_at|poly_wave|precision|pretrace_end|pretrace_start|quaternion|radius|ramp_wave|recursion_limit|repeat|rgbf?t?|red|refraction|right|roughness|samples|shadowless|sky|spacing|specular|spherical|spotlight|srgbf?t?|target|transmit|turbulence|uv_mapping|up|water_level|wrinkles|x|y|z)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.function.povray</string>
			<key>match</key>
			<string>\b(abs|concat|dimension_size|internal|max|min|mod|pow|rand|seed|sin|sqrt|vcross|vlength|vrotate|vnormalize)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.modifier.povray</string>
			<key>match</key>
			<string>\b(rotate|scale|translate)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.control.povray</string>
			<key>match</key>
			<string>\#(break|case|declare|debug|else(if)?|end|error|fopen|for|if(n?def)?|include|local|macro|range|read|switch|version|while|write)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>invalid.deprecated.keyword.control.povray</string>
			<key>match</key>
			<string>\#(default)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>invalid.illegal.povray</string>
			<key>match</key>
			<string>\#[_a-zA-Z0-9]*\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>variable.language.povray</string>
			<key>match</key>
			<string>\b(image_height|image_width)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>invalid.deprecated.future-keyword.povray</string>
			<key>match</key>
			<string>\b([_a-z][_a-z0-9]*)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>variable.parameter.povray</string>
			<key>match</key>
			<string>\b[_a-zA-Z][_a-zA-Z0-9]*\b</string>
		</dict>
	</array>
	<key>fileTypes</key>
	<array>
		<string>pov</string>
		<string>inc</string>
	</array>
</dict>
</plist>
