<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Jade</string>
	<key>scopeName</key>
	<string>text.jade</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>name</key>
			<string>meta.tag.sgml.doctype.html</string>
			<key>match</key>
			<string>^(!!!|doctype)(\s*[a-zA-Z0-9-_]+)?</string>
		</dict>
		<dict>
			<key>name</key>
			<string>comment.unbuffered.block.jade</string>
			<key>begin</key>
			<string>^(\s*)//-</string>
			<key>end</key>
			<string>^(?!(\1\s)|\s*$)</string>
		</dict>
		<dict>
			<key>name</key>
			<string>string.comment.buffered.block.jade</string>
			<key>begin</key>
			<string>^(\s*)//</string>
			<key>end</key>
			<string>^(?!(\1\s)|\s*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>string.comment.buffered.block.jade</string>
					<key>match</key>
					<string>^\s*(//)(?!-)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.comment.comment.block.jade</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<dict>
			<key>name</key>
			<string>comment.unbuffered.block.jade</string>
			<key>begin</key>
			<string>&lt;!--</string>
			<key>end</key>
			<string>--\s*&gt;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>invalid.illegal.comment.comment.block.jade</string>
					<key>match</key>
					<string>--</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>name</key>
			<string>source.js</string>
			<key>begin</key>
			<string>^(\s*)-$</string>
			<key>end</key>
			<string>^(?!(\1\s)|\s*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.tag.other</string>
			<key>begin</key>
			<string>^(\s*)(script)((\.$)|(?=[^\n]*(text|application)/javascript.*\.$))</string>
			<key>end</key>
			<string>^(?!(\1\s)|\s*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\G(?=\()</string>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tag_attributes</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\G(?=[.#])</string>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#complete_tag</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.jade</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.tag.other</string>
			<key>begin</key>
			<string>^(\s*)(style)((\.$)|(?=[.#(].*\.$))</string>
			<key>end</key>
			<string>^(?!(\1\s)|\s*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\G(?=\()</string>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tag_attributes</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\G(?=[.#])</string>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#complete_tag</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>source.css</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.jade</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>source.sass.filter.jade</string>
			<key>begin</key>
			<string>^(\s*):(sass)(?=\(|$)</string>
			<key>end</key>
			<string>^(?!(\1\s)|\s*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag_attributes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.sass</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language.name.sass.filter.jade</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>source.less.filter.jade</string>
			<key>begin</key>
			<string>^(\s*):(less)(?=\(|$)</string>
			<key>end</key>
			<string>^(?!(\1\s)|\s*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag_attributes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.css.less</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language.name.less.filter.jade</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(\s*):(stylus)(?=\(|$)</string>
			<key>end</key>
			<string>^(?!(\1\s)|\s*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag_attributes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.stylus</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language.name.stylus.filter.jade</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>source.coffeescript.filter.jade</string>
			<key>begin</key>
			<string>^(\s*):(coffee(-?script)?)(?=\(|$)</string>
			<key>end</key>
			<string>^(?!(\1\s)|\s*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag_attributes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.coffee</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language.name.coffeescript.filter.jade</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(\s*)((:(?=.))|(:$))</string>
			<key>end</key>
			<string>^(?!(\1\s)|\s*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>name.generic.filter.jade</string>
					<key>begin</key>
					<string>\G(?&lt;=:)(?=.)</string>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>invalid.illegal.name.generic.filter.jade</string>
							<key>match</key>
							<string>\G\(</string>
						</dict>
						<dict>
							<key>name</key>
							<string>constant.language.name.generic.filter.jade</string>
							<key>match</key>
							<string>[\w-]</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#tag_attributes</string>
						</dict>
						<dict>
							<key>name</key>
							<string>invalid.illegal.name.generic.filter.jade</string>
							<key>match</key>
							<string>\W</string>
						</dict>
					</array>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.empty.generic.filter.jade</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(\s*)(?=[\w.#].*?\.$)(?=(?:(?:(?:(?:(?:#[\w-]+)|(?:\.[\w-]+))|(?:(?:[#!]\{[^}]*\})|(?:\w(?:(?:[\w:-]+[\w-])|(?:[\w-]*)))))(?:(?:#[\w-]+)|(?:\.[\w-]+)|(?:\((?:[^()\&apos;\&quot;]*(?:(?:\&apos;(?:[^\&apos;]|(?:(?&lt;!\\)\\\&apos;))*\&apos;)|(?:\&quot;(?:[^\&quot;]|(?:(?&lt;!\\)\\\&quot;))*\&quot;)))*[^()]*\))*)*)(?:(?:(?::\s+)|(?&lt;=\)))(?:(?:(?:(?:#[\w-]+)|(?:\.[\w-]+))|(?:(?:[#!]\{[^}]*\})|(?:\w(?:(?:[\w:-]+[\w-])|(?:[\w-]*)))))(?:(?:#[\w-]+)|(?:\.[\w-]+)|(?:\((?:[^()\&apos;\&quot;]*(?:(?:\&apos;(?:[^\&apos;]|(?:(?&lt;!\\)\\\&apos;))*\&apos;)|(?:\&quot;(?:[^\&quot;]|(?:(?&lt;!\\)\\\&quot;))*\&quot;)))*[^()]*\))*)*))*)\.$)(?:(?:(#[\w-]+)|(\.[\w-]+))|((?:[#!]\{[^}]*\})|(?:\w(?:(?:[\w:-]+[\w-])|(?:[\w-]*)))))</string>
			<key>end</key>
			<string>^(?!(\1\s)|\s*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag_attributes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#complete_tag</string>
				</dict>
				<dict>
					<key>name</key>
					<string>text.block.jade</string>
					<key>begin</key>
					<string>^(?=.)</string>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline_jade</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#embedded_html</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#html_entity</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#interpolated_value</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#interpolated_error</string>
						</dict>
					</array>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.id.jade</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.class.jade</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>meta.tag.other entity.name.tag.jade</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline_jade</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#blocks_and_includes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#unbuffered_code</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#mixin_definition</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#mixin_call</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#flow_control</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#case_conds</string>
				</dict>
				<dict>
					<key>name</key>
					<string>text.block.pipe.jade</string>
					<key>begin</key>
					<string>\|</string>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline_jade</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#embedded_html</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#html_entity</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#interpolated_value</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#interpolated_error</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#printed_expression</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\G(?=(#[^\{\w-])|[^\w.#])</string>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>&lt;/?(?=[!#])</string>
							<key>end</key>
							<string>&gt;|$</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#inline_jade</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#interpolated_value</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#interpolated_error</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>include</key>
							<string>#inline_jade</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#embedded_html</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#html_entity</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#interpolated_value</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#interpolated_error</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#complete_tag</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>babel_parens</key>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>end</key>
			<string>\)|(({\s*)?$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#babel_parens</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<key>blocks_and_includes</key>
		<dict>
			<key>name</key>
			<string>meta.first-class.jade</string>
			<key>match</key>
			<string>(extends|include|yield|append|prepend|block( (append|prepend))?)\s+(.*)$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.import.include.jade</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.control.import.include.jade</string>
				</dict>
			</dict>
		</dict>
		<key>case_conds</key>
		<dict>
			<key>name</key>
			<string>meta.control.flow.jade</string>
			<key>begin</key>
			<string>(default|when)((\s+|(?=:))|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>js.embedded.control.flow.jade</string>
					<key>begin</key>
					<string>\G(?!:)</string>
					<key>end</key>
					<string>(?=:\s+)|$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#case_when_paren</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>name</key>
					<string>tag.case.control.flow.jade</string>
					<key>begin</key>
					<string>:\s+</string>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#complete_tag</string>
						</dict>
					</array>
				</dict>
			</array>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.jade</string>
				</dict>
			</dict>
		</dict>
		<key>case_when_paren</key>
		<dict>
			<key>name</key>
			<string>js.when.control.flow.jade</string>
			<key>begin</key>
			<string>\(</string>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#case_when_paren</string>
				</dict>
				<dict>
					<key>name</key>
					<string>invalid.illegal.name.tag.jade</string>
					<key>match</key>
					<string>:</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<key>complete_tag</key>
		<dict>
			<key>begin</key>
			<string>(?=[\w.#])|(:\s*)</string>
			<key>end</key>
			<string>(\.?$)|(?=:.)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#blocks_and_includes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#unbuffered_code</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#mixin_call</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#flow_control</string>
				</dict>
				<dict>
					<key>name</key>
					<string>invalid.illegal.name.tag.jade</string>
					<key>match</key>
					<string>(?&lt;=:)\w.*$</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag_name</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag_id</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag_classes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag_attributes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag_mixin_attributes</string>
				</dict>
				<dict>
					<key>match</key>
					<string>((\.)\s+$)|((:)\s*$)</string>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.end.tag.jade</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.end.tag.jade</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>include</key>
					<string>#printed_expression</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag_text</string>
				</dict>
			</array>
		</dict>
		<key>embedded_html</key>
		<dict>
			<key>name</key>
			<string>html</string>
			<key>begin</key>
			<string>(?=&lt;[^&gt;]*&gt;)</string>
			<key>end</key>
			<string>$|(?=&gt;)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#interpolated_value</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#interpolated_error</string>
				</dict>
			</array>
		</dict>
		<key>flow_control</key>
		<dict>
			<key>name</key>
			<string>meta.control.flow.jade</string>
			<key>begin</key>
			<string>(for|if|else if|else|each|until|while|unless|case)(\s+|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>js.embedded.control.flow.jade</string>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
				</dict>
			</array>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.jade</string>
				</dict>
			</dict>
		</dict>
		<key>html_entity</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.character.entity.html.text.jade</string>
					<key>match</key>
					<string>(&amp;)([a-zA-Z0-9]+|#[0-9]+|#x[0-9a-fA-F]+)(;)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>invalid.illegal.html_entity.text.jade</string>
					<key>match</key>
					<string>[&lt;&gt;&amp;]</string>
				</dict>
			</array>
		</dict>
		<key>inline_jade</key>
		<dict>
			<key>name</key>
			<string>inline.jade</string>
			<key>begin</key>
			<string>(?&lt;!\\)(#\[)</string>
			<key>end</key>
			<string>(\])</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline_jade</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#mixin_call</string>
				</dict>
				<dict>
					<key>name</key>
					<string>tag.inline.jade</string>
					<key>begin</key>
					<string>(?&lt;!\])(?=[\w.#])|(:\s*)</string>
					<key>end</key>
					<string>(?=\]|(:.)|=|\s)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tag_name</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#tag_id</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#tag_classes</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#tag_attributes</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#tag_mixin_attributes</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#inline_jade</string>
						</dict>
						<dict>
							<key>name</key>
							<string>invalid.illegal.tag.jade</string>
							<key>match</key>
							<string>\[</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#unbuffered_code</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#printed_expression</string>
				</dict>
				<dict>
					<key>name</key>
					<string>invalid.illegal.tag.jade</string>
					<key>match</key>
					<string>\[</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline_jade_text</string>
				</dict>
			</array>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.jade</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.jade</string>
				</dict>
			</dict>
		</dict>
		<key>inline_jade_text</key>
		<dict>
			<key>end</key>
			<string>(?=\])</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\[</string>
					<key>end</key>
					<string>\]</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline_jade_text</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline_jade</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded_html</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#html_entity</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#interpolated_value</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#interpolated_error</string>
				</dict>
			</array>
		</dict>
		<key>interpolated_error</key>
		<dict>
			<key>name</key>
			<string>invalid.illegal.tag.jade</string>
			<key>match</key>
			<string>(?&lt;!\\)[#!]\{(?=[^}]*$)</string>
		</dict>
		<key>interpolated_value</key>
		<dict>
			<key>name</key>
			<string>string.interpolated.jade</string>
			<key>begin</key>
			<string>(?&lt;!\\)[#!]\{(?=.*?\})</string>
			<key>end</key>
			<string>\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>invalid.illegal.tag.jade</string>
					<key>match</key>
					<string>{</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<key>js_braces</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>end</key>
			<string>\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#js_braces</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<key>js_brackets</key>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>end</key>
			<string>\]</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#js_brackets</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<key>js_parens</key>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#js_parens</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<key>mixin_call</key>
		<dict>
			<key>begin</key>
			<string>((?:mixin\s+)|\+)([\w-]+)</string>
			<key>end</key>
			<string>(?!\()|$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>args.mixin.jade</string>
					<key>begin</key>
					<string>(?&lt;!\))\(</string>
					<key>end</key>
					<string>\)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#js_parens</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#string</string>
						</dict>
						<dict>
							<key>match</key>
							<string>([^\s(),=/]+)\s*=\s*</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>meta.tag.other entity.other.attribute-name.tag.jade</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag_attributes</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.jade</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.tag.other entity.name.function.jade</string>
				</dict>
			</dict>
		</dict>
		<key>mixin_definition</key>
		<dict>
			<key>match</key>
			<string>(mixin\s+)([\w-]+)(?:(\()\s*((?:[a-zA-Z_]\w*\s*)(?:,\s*[a-zA-Z_]\w*\s*)*)(\)))?$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.jade</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.tag.other entity.name.function.jade</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.js</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.function.js</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.js</string>
				</dict>
			</dict>
		</dict>
		<key>printed_expression</key>
		<dict>
			<key>name</key>
			<string>source.js</string>
			<key>begin</key>
			<string>(!?\=)\s*</string>
			<key>end</key>
			<string>(?=\])|$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#js_brackets</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant</string>
				</dict>
			</dict>
		</dict>
		<key>string</key>
		<dict>
			<key>name</key>
			<string>string.quoted.jade</string>
			<key>begin</key>
			<string>([&apos;&quot;])</string>
			<key>end</key>
			<string>(?&lt;!\\)\1</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.character.quoted.jade</string>
					<key>match</key>
					<string>\\((x[0-9a-fA-F]{2})|(u[0-9]{4})|.)</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#interpolated_value</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#interpolated_error</string>
				</dict>
			</array>
		</dict>
		<key>tag_attribute_name</key>
		<dict>
			<key>match</key>
			<string>([^\s(),=/!]+)\s*</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.tag.jade</string>
				</dict>
			</dict>
		</dict>
		<key>tag_attribute_name_paren</key>
		<dict>
			<key>name</key>
			<string>entity.other.attribute-name.tag.jade</string>
			<key>begin</key>
			<string>\(\s*</string>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag_attribute_name_paren</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag_attribute_name</string>
				</dict>
			</array>
		</dict>
		<key>tag_attributes</key>
		<dict>
			<key>name</key>
			<string>meta.tag.other</string>
			<key>begin</key>
			<string>(\(\s*)</string>
			<key>end</key>
			<string>(\))</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag_attribute_name_paren</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag_attribute_name</string>
				</dict>
				<dict>
					<key>name</key>
					<string>invalid.illegal.tag.jade</string>
					<key>match</key>
					<string>!(?!=)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>attribute_value</string>
					<key>begin</key>
					<string>=\s*</string>
					<key>end</key>
					<string>$|(?=,|(?:\s+[^!%&amp;*-+~|&lt;&gt;:?/])|\))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#js_parens</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#js_brackets</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#js_braces</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>name</key>
					<string>attribute_value2</string>
					<key>begin</key>
					<string>(?&lt;=[%&amp;*-+~|&lt;&gt;:?/])\s+</string>
					<key>end</key>
					<string>$|(?=,|(?:\s+[^!%&amp;*-+~|&lt;&gt;:?/])|\))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#js_parens</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#js_brackets</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#js_braces</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
				</dict>
			</array>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.name.attribute.tag.jade</string>
				</dict>
			</dict>
		</dict>
		<key>tag_classes</key>
		<dict>
			<key>name</key>
			<string>entity.other.attribute-name.class.jade</string>
			<key>match</key>
			<string>\.([^\w-])?[\w-]*</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.tag.jade</string>
				</dict>
			</dict>
		</dict>
		<key>tag_id</key>
		<dict>
			<key>name</key>
			<string>entity.other.attribute-name.id.jade</string>
			<key>match</key>
			<string>#[\w-]+</string>
		</dict>
		<key>tag_mixin_attributes</key>
		<dict>
			<key>name</key>
			<string>meta.tag.other</string>
			<key>begin</key>
			<string>(&amp;attributes\()</string>
			<key>end</key>
			<string>(\))</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>storage.type.keyword.jade</string>
					<key>match</key>
					<string>attributes(?=\))</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.jade</string>
				</dict>
			</dict>
		</dict>
		<key>tag_name</key>
		<dict>
			<key>name</key>
			<string>meta.tag.other entity.name.tag.jade</string>
			<key>begin</key>
			<string>([#!]\{(?=.*?\}))|(\w(([\w:-]+[\w-])|([\w-]*)))</string>
			<key>end</key>
			<string>(\G(?&lt;!\5[^\w-]))|\}|$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.tag.other entity.name.tag.jade</string>
					<key>begin</key>
					<string>\G(?&lt;=\{)</string>
					<key>end</key>
					<string>(?=\})</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>invalid.illegal.tag.jade</string>
							<key>match</key>
							<string>{</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>tag_text</key>
		<dict>
			<key>begin</key>
			<string>(?=.)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline_jade</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded_html</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#html_entity</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#interpolated_value</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#interpolated_error</string>
				</dict>
			</array>
		</dict>
		<key>unbuffered_code</key>
		<dict>
			<key>name</key>
			<string>source.js</string>
			<key>begin</key>
			<string>(-|(([a-zA-Z0-9_]+)\s+=))</string>
			<key>end</key>
			<string>(?=\])|(({\s*)?$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#js_brackets</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#babel_parens</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.javascript.embedded.jade</string>
				</dict>
			</dict>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>jade</string>
		<string>pug</string>
	</array>
</dict>
</plist>
