<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>PureScript</string>
	<key>scopeName</key>
	<string>source.purescript</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>name</key>
			<string>keyword.operator.function.infix.purescript</string>
			<key>match</key>
			<string>(`)(?:[\p{Lu}\p{Lt}][\p{Ll}_\p{Lu}\p{Lt}\p{Nd}&apos;]*(?:\.[\p{Lu}\p{Lt}][\p{Ll}_\p{Lu}\p{Lt}\p{Nd}&apos;]*)*\.)?[\p{Ll}_][\p{Ll}_\p{Lu}\p{Lt}\p{Nd}&apos;]*(`)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.entity.purescript</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.entity.purescript</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.declaration.module.purescript</string>
			<key>begin</key>
			<string>^\s*\b(module)(?!&apos;)\b</string>
			<key>end</key>
			<string>(where)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#module_name</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#module_exports</string>
				</dict>
				<dict>
					<key>name</key>
					<string>invalid.purescript</string>
					<key>match</key>
					<string>[a-z]+</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.purescript</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.purescript</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.declaration.typeclass.purescript</string>
			<key>begin</key>
			<string>^\s*\b(class)(?!&apos;)\b</string>
			<key>end</key>
			<string>\b(where)\b|$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#type_signature</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.class.purescript</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.purescript</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.declaration.instance.purescript</string>
			<key>contentName</key>
			<string>meta.type-signature.purescript</string>
			<key>begin</key>
			<string>^\s*\b(else\s+)?(derive\s+)?(newtype\s+)?(instance)(?!&apos;)\b</string>
			<key>end</key>
			<string>\b(where)\b|$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#type_signature</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.purescript</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.purescript</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.other.purescript</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.other.purescript</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.purescript</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.foreign.data.purescript</string>
			<key>contentName</key>
			<string>meta.kind-signature.purescript</string>
			<key>begin</key>
			<string>^(\s*)(foreign)\s+(import)\s+(data)\s+([\p{Lu}\p{Lt}][\p{Ll}_\p{Lu}\p{Lt}\p{Nd}&apos;]*)</string>
			<key>end</key>
			<string>^(?!\1[ \t]|[ \t]*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#double_colon</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#kind_signature</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.purescript</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.other.purescript</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.other.purescript</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.purescript</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>keyword.other.double-colon.purescript</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.foreign.purescript</string>
			<key>contentName</key>
			<string>meta.type-signature.purescript</string>
			<key>begin</key>
			<string>^(\s*)(foreign)\s+(import)\s+([\p{Ll}_][\p{Ll}_\p{Lu}\p{Lt}\p{Nd}&apos;]*)</string>
			<key>end</key>
			<string>^(?!\1[ \t]|[ \t]*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#double_colon</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#type_signature</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.purescript</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.other.purescript</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.purescript</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.import.purescript</string>
			<key>begin</key>
			<string>^\s*\b(import)(?!&apos;)\b</string>
			<key>end</key>
			<string>($|(?=--))</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#module_name</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#module_exports</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(as|hiding)\b</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.purescript</string>
						</dict>
					</dict>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.purescript</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.declaration.type.data.purescript</string>
			<key>begin</key>
			<string>^(\s)*(data|newtype)\s+(.+?)\s*(?=\=|$)</string>
			<key>end</key>
			<string>^(?!\1[ \t]|[ \t]*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>match</key>
					<string>=</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.assignment.purescript</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>(?:(?:\b([\p{Lu}\p{Lt}][\p{Ll}_\p{Lu}\p{Lt}\p{Nd}&apos;]*(?:\.[\p{Lu}\p{Lt}][\p{Ll}_\p{Lu}\p{Lt}\p{Nd}&apos;]*)*)\s+)(?:(?&lt;ctorArgs&gt;(?:(?:[\p{Lu}\p{Lt}][\p{Ll}_\p{Lu}\p{Lt}\p{Nd}&apos;]*(?:\.[\p{Lu}\p{Lt}][\p{Ll}_\p{Lu}\p{Lt}\p{Nd}&apos;]*)*|(?:[\p{Lu}\p{Lt}][\p{Ll}_\p{Lu}\p{Lt}\p{Nd}&apos;]*(?:\.[\p{Lu}\p{Lt}][\p{Ll}_\p{Lu}\p{Lt}\p{Nd}&apos;]*)*\.)?[\p{Ll}_][\p{Ll}_\p{Lu}\p{Lt}\p{Nd}&apos;]*|(?:(?:[\w()&apos;→⇒\[\],]|-&gt;|=&gt;)+\s*)+))(?:\s*(?:\s+)\s*\g&lt;ctorArgs&gt;)?)?))</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#data_ctor</string>
								</dict>
							</array>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.type-signature.purescript</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#type_signature</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>\|</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.pipe.purescript</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>include</key>
					<string>#record_types</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.data.purescript</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>meta.type-signature.purescript</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#type_signature</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.declaration.type.type.purescript</string>
			<key>contentName</key>
			<string>meta.type-signature.purescript</string>
			<key>begin</key>
			<string>^(\s)*(type)\s+(.+?)\s*(?=\=|$)</string>
			<key>end</key>
			<string>^(?!\1[ \t]|[ \t]*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>=</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.assignment.purescript</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>include</key>
					<string>#type_signature</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#record_types</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.data.purescript</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>meta.type-signature.purescript</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#type_signature</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.other.purescript</string>
			<key>match</key>
			<string>^\s*\b(derive|where|data|type|newtype|infix[lr]?|foreign(\s+import)?(\s+data)?)(?!&apos;)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>entity.name.function.typed-hole.purescript</string>
			<key>match</key>
			<string>\?(?:[\p{Ll}_][\p{Ll}_\p{Lu}\p{Lt}\p{Nd}&apos;]*|[\p{Lu}\p{Lt}][\p{Ll}_\p{Lu}\p{Lt}\p{Nd}&apos;]*)</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.type.purescript</string>
			<key>match</key>
			<string>^\s*\b(data|type|newtype)(?!&apos;)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.control.purescript</string>
			<key>match</key>
			<string>\b(do|ado|if|then|else|case|of|let|in)(?!(&apos;|\s*(:|=)))\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.numeric.hex.purescript</string>
			<key>match</key>
			<string>\b(?&lt;!\$)0(x|X)[0-9a-fA-F]+\b(?!\$)</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.numeric.decimal.purescript</string>
			<key>match</key>
			<string>(?x)
(?&lt;!\$)(?:
  (?:\b[0-9]+(\.)[0-9]+[eE][+-]?[0-9]+\b)| # 1.1E+3
  (?:\b[0-9]+[eE][+-]?[0-9]+\b)|            # 1E+3
  (?:\b[0-9]+(\.)[0-9]+\b)|                # 1.1
  (?:\b[0-9]+\b(?!\.))                     # 1
)(?!\$)</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.decimal.purescript</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.delimiter.decimal.period.purescript</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.delimiter.decimal.period.purescript</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>meta.delimiter.decimal.period.purescript</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>meta.delimiter.decimal.period.purescript</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>meta.delimiter.decimal.period.purescript</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>meta.delimiter.decimal.period.purescript</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.language.boolean.purescript</string>
			<key>match</key>
			<string>\b(true|false)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.numeric.purescript</string>
			<key>match</key>
			<string>\b(([0-9]+_?)*[0-9]+|0([xX][0-9a-fA-F]+|[oO][0-7]+))\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>string.quoted.triple.purescript</string>
			<key>begin</key>
			<string>&quot;&quot;&quot;</string>
			<key>end</key>
			<string>&quot;&quot;&quot;</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.purescript</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.purescript</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>string.quoted.double.purescript</string>
			<key>begin</key>
			<string>&quot;</string>
			<key>end</key>
			<string>&quot;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#characters</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\\\s</string>
					<key>end</key>
					<string>\\</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>invalid.illegal.character-not-allowed-here.purescript</string>
							<key>match</key>
							<string>\S+</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>markup.other.escape.newline.begin.purescript</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>markup.other.escape.newline.end.purescript</string>
						</dict>
					</dict>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.purescript</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.purescript</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>markup.other.escape.newline.purescript</string>
			<key>match</key>
			<string>\\$</string>
		</dict>
		<dict>
			<key>name</key>
			<string>string.quoted.single.purescript</string>
			<key>match</key>
			<string>(&apos;)((?:[ -\[\]-~]|(\\(?:NUL|SOH|STX|ETX|EOT|ENQ|ACK|BEL|BS|HT|LF|VT|FF|CR|SO|SI|DLE|DC1|DC2|DC3|DC4|NAK|SYN|ETB|CAN|EM|SUB|ESC|FS|GS|RS|US|SP|DEL|[abfnrtv\\\&quot;&apos;\&amp;]))|(\\o[0-7]+)|(\\x[0-9A-Fa-f]+)|(\^[A-Z@\[\]\\\^_])))(&apos;)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.purescript</string>
				</dict>
				<key>2</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#characters</string>
						</dict>
					</array>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.purescript</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>include</key>
			<string>#function_type_declaration</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\((?&lt;paren&gt;(?:[^()]|\(\g&lt;paren&gt;\))*)(::|∷)(?&lt;paren2&gt;(?:[^()]|\(\g&lt;paren2&gt;\))*)\)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.double-colon.purescript</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>meta.type-signature.purescript</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#type_signature</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(\s*)(?:(::|∷))</string>
			<key>end</key>
			<string>^(?!\1[ \t]*|[ \t]*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#type_signature</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.double-colon.purescript</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>include</key>
			<string>#data_ctor</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#infix_op</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.other.arrow.purescript</string>
			<key>match</key>
			<string>\&lt;-|-\&gt;</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.operator.purescript</string>
			<key>match</key>
			<string>[\p{S}\p{P}&amp;&amp;[^(),;\[\]`{}_&quot;&apos;]]+</string>
		</dict>
		<dict>
			<key>name</key>
			<string>punctuation.separator.comma.purescript</string>
			<key>match</key>
			<string>,</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>block_comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>comment.block.documentation.purescript</string>
					<key>begin</key>
					<string>\{-\s*\|</string>
					<key>end</key>
					<string>-\}</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#block_comment</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.documentation.purescript</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.documentation.purescript</string>
						</dict>
					</dict>
					<key>applyEndPatternLast</key>
					<true />
				</dict>
				<dict>
					<key>name</key>
					<string>comment.block.purescript</string>
					<key>begin</key>
					<string>\{-</string>
					<key>end</key>
					<string>-\}</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#block_comment</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.purescript</string>
						</dict>
					</dict>
					<key>applyEndPatternLast</key>
					<true />
				</dict>
			</array>
		</dict>
		<key>characters</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?:[ -\[\]-~]|(\\(?:NUL|SOH|STX|ETX|EOT|ENQ|ACK|BEL|BS|HT|LF|VT|FF|CR|SO|SI|DLE|DC1|DC2|DC3|DC4|NAK|SYN|ETB|CAN|EM|SUB|ESC|FS|GS|RS|US|SP|DEL|[abfnrtv\\\&quot;&apos;\&amp;]))|(\\o[0-7]+)|(\\x[0-9A-Fa-f]+)|(\^[A-Z@\[\]\\\^_]))</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.character.escape.purescript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.character.escape.octal.purescript</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.character.escape.hexadecimal.purescript</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.character.escape.control.purescript</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>class_constraint</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.class-constraint.purescript</string>
					<key>match</key>
					<string>(?:(?:([\p{Lu}\p{Lt}][\p{Ll}_\p{Lu}\p{Lt}\p{Nd}&apos;]*(?:\.[\p{Lu}\p{Lt}][\p{Ll}_\p{Lu}\p{Lt}\p{Nd}&apos;]*)*)\s+)(?:(?&lt;classConstraint&gt;(?:[\p{Lu}\p{Lt}][\p{Ll}_\p{Lu}\p{Lt}\p{Nd}&apos;]*(?:\.[\p{Lu}\p{Lt}][\p{Ll}_\p{Lu}\p{Lt}\p{Nd}&apos;]*)*|(?:[\p{Lu}\p{Lt}][\p{Ll}_\p{Lu}\p{Lt}\p{Nd}&apos;]*(?:\.[\p{Lu}\p{Lt}][\p{Ll}_\p{Lu}\p{Lt}\p{Nd}&apos;]*)*\.)?[\p{Ll}_][\p{Ll}_\p{Lu}\p{Lt}\p{Nd}&apos;]*)(?:\s*(?:\s+)\s*\g&lt;classConstraint&gt;)?)))</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>name</key>
									<string>entity.name.type.purescript</string>
									<key>match</key>
									<string>\b[\p{Lu}\p{Lt}][\p{Ll}_\p{Lu}\p{Lt}\p{Nd}&apos;]*(?:\.[\p{Lu}\p{Lt}][\p{Ll}_\p{Lu}\p{Lt}\p{Nd}&apos;]*)*</string>
								</dict>
							</array>
						</dict>
						<key>2</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#type_name</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#generic_type</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(^[ \t]+)?(?=--+\s+\|)</string>
					<key>end</key>
					<string>(?!\G)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>comment.line.double-dash.documentation.purescript</string>
							<key>begin</key>
							<string>(--+)\s+(\|)</string>
							<key>end</key>
							<string>\n</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.comment.purescript</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.comment.documentation.purescript</string>
								</dict>
							</dict>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.whitespace.comment.leading.purescript</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>begin</key>
					<string>(^[ \t]+)?(?=--+(?![\p{S}\p{P}&amp;&amp;[^(),;\[\]`{}_&quot;&apos;]]))</string>
					<key>end</key>
					<string>(?!\G)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>comment.line.double-dash.purescript</string>
							<key>begin</key>
							<string>--</string>
							<key>end</key>
							<string>\n</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.comment.purescript</string>
								</dict>
							</dict>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.whitespace.comment.leading.purescript</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>include</key>
					<string>#block_comment</string>
				</dict>
			</array>
		</dict>
		<key>data_ctor</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>entity.name.tag.purescript</string>
					<key>match</key>
					<string>\b[\p{Lu}\p{Lt}][\p{Ll}_\p{Lu}\p{Lt}\p{Nd}&apos;]*(?:\.[\p{Lu}\p{Lt}][\p{Ll}_\p{Lu}\p{Lt}\p{Nd}&apos;]*)*</string>
				</dict>
			</array>
		</dict>
		<key>double_colon</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.other.double-colon.purescript</string>
					<key>match</key>
					<string>(?:::|∷)</string>
				</dict>
			</array>
		</dict>
		<key>function_type_declaration</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.function.type-declaration.purescript</string>
					<key>contentName</key>
					<string>meta.type-signature.purescript</string>
					<key>begin</key>
					<string>^(\s*)([\p{Ll}_][\p{Ll}_\p{Lu}\p{Lt}\p{Nd}&apos;]*)\s*(?:(::|∷)(?!.*&lt;-))</string>
					<key>end</key>
					<string>^(?!\1[ \t]|[ \t]*$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#double_colon</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#type_signature</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.purescript</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.other.double-colon.purescript</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>generic_type</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>variable.other.generic-type.purescript</string>
					<key>match</key>
					<string>\b(?:[\p{Lu}\p{Lt}][\p{Ll}_\p{Lu}\p{Lt}\p{Nd}&apos;]*(?:\.[\p{Lu}\p{Lt}][\p{Ll}_\p{Lu}\p{Lt}\p{Nd}&apos;]*)*\.)?[\p{Ll}_][\p{Ll}_\p{Lu}\p{Lt}\p{Nd}&apos;]*</string>
				</dict>
			</array>
		</dict>
		<key>infix_op</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>entity.name.function.infix.purescript</string>
					<key>match</key>
					<string>(?:\((?!--+\))[\p{S}\p{P}&amp;&amp;[^(),;\[\]`{}_&quot;&apos;]]+\))</string>
				</dict>
			</array>
		</dict>
		<key>kind_signature</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.other.star.purescript</string>
					<key>match</key>
					<string>\*</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.other.exclaimation-point.purescript</string>
					<key>match</key>
					<string>!</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.other.pound-sign.purescript</string>
					<key>match</key>
					<string>#</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.other.arrow.purescript</string>
					<key>match</key>
					<string>-&gt;|→</string>
				</dict>
			</array>
		</dict>
		<key>module_exports</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.declaration.exports.purescript</string>
					<key>begin</key>
					<string>\(</string>
					<key>end</key>
					<string>\)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>name</key>
							<string>entity.name.function.purescript</string>
							<key>match</key>
							<string>\b(?:[\p{Lu}\p{Lt}][\p{Ll}_\p{Lu}\p{Lt}\p{Nd}&apos;]*(?:\.[\p{Lu}\p{Lt}][\p{Ll}_\p{Lu}\p{Lt}\p{Nd}&apos;]*)*\.)?[\p{Ll}_][\p{Ll}_\p{Lu}\p{Lt}\p{Nd}&apos;]*</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#type_name</string>
						</dict>
						<dict>
							<key>name</key>
							<string>punctuation.separator.comma.purescript</string>
							<key>match</key>
							<string>,</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#infix_op</string>
						</dict>
						<dict>
							<key>name</key>
							<string>meta.other.constructor-list.purescript</string>
							<key>match</key>
							<string>\(.*?\)</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>module_name</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>support.other.module.purescript</string>
					<key>match</key>
					<string>(?:[\p{Lu}\p{Lt}][\p{Ll}_\p{Lu}\p{Lt}\p{Nd}&apos;]*(?:\.[\p{Lu}\p{Lt}][\p{Ll}_\p{Lu}\p{Lt}\p{Nd}&apos;]*)*\.)*[\p{Lu}\p{Lt}][\p{Ll}_\p{Lu}\p{Lt}\p{Nd}&apos;]*(?:\.[\p{Lu}\p{Lt}][\p{Ll}_\p{Lu}\p{Lt}\p{Nd}&apos;]*)*\.?</string>
				</dict>
			</array>
		</dict>
		<key>record_field_declaration</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.record-field.type-declaration.purescript</string>
					<key>contentName</key>
					<string>meta.type-signature.purescript</string>
					<key>begin</key>
					<string>([\p{Ll}_][\p{Ll}_\p{Lu}\p{Lt}\p{Nd}&apos;]*)\s*(::|∷)</string>
					<key>end</key>
					<string>(?=([\p{Ll}_][\p{Ll}_\p{Lu}\p{Lt}\p{Nd}&apos;]*)\s*(::|∷)|})</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#type_signature</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#record_types</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>name</key>
									<string>entity.other.attribute-name.purescript</string>
									<key>match</key>
									<string>(?:[\p{Lu}\p{Lt}][\p{Ll}_\p{Lu}\p{Lt}\p{Nd}&apos;]*(?:\.[\p{Lu}\p{Lt}][\p{Ll}_\p{Lu}\p{Lt}\p{Nd}&apos;]*)*\.)?[\p{Ll}_][\p{Ll}_\p{Lu}\p{Lt}\p{Nd}&apos;]*</string>
								</dict>
							</array>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.double-colon.purescript</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>record_types</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.type.record.purescript</string>
					<key>begin</key>
					<string>\{</string>
					<key>end</key>
					<string>\}</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>punctuation.separator.comma.purescript</string>
							<key>match</key>
							<string>,</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#record_field_declaration</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.type.record.begin.purescript</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.type.record.end.purescript</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>type_name</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>entity.name.type.purescript</string>
					<key>match</key>
					<string>\b[\p{Lu}\p{Lt}][\p{Ll}_\p{Lu}\p{Lt}\p{Nd}&apos;]*(?:\.[\p{Lu}\p{Lt}][\p{Ll}_\p{Lu}\p{Lt}\p{Nd}&apos;]*)*</string>
				</dict>
			</array>
		</dict>
		<key>type_signature</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.class-constraints.purescript</string>
					<key>match</key>
					<string>(?:(?:\()(?:(?&lt;classConstraints&gt;(?:(?:(?:([\p{Lu}\p{Lt}][\p{Ll}_\p{Lu}\p{Lt}\p{Nd}&apos;]*(?:\.[\p{Lu}\p{Lt}][\p{Ll}_\p{Lu}\p{Lt}\p{Nd}&apos;]*)*)\s+)(?:(?&lt;classConstraint&gt;(?:[\p{Lu}\p{Lt}][\p{Ll}_\p{Lu}\p{Lt}\p{Nd}&apos;]*(?:\.[\p{Lu}\p{Lt}][\p{Ll}_\p{Lu}\p{Lt}\p{Nd}&apos;]*)*|(?:[\p{Lu}\p{Lt}][\p{Ll}_\p{Lu}\p{Lt}\p{Nd}&apos;]*(?:\.[\p{Lu}\p{Lt}][\p{Ll}_\p{Lu}\p{Lt}\p{Nd}&apos;]*)*\.)?[\p{Ll}_][\p{Ll}_\p{Lu}\p{Lt}\p{Nd}&apos;]*)(?:\s*(?:\s+)\s*\g&lt;classConstraint&gt;)?))))(?:\s*(?:,)\s*\g&lt;classConstraints&gt;)?))(?:\))(?:\s*(=&gt;|&lt;=|⇐|⇒)))</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#class_constraint</string>
								</dict>
							</array>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>keyword.other.big-arrow.purescript</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.class-constraints.purescript</string>
					<key>match</key>
					<string>((?:(?:([\p{Lu}\p{Lt}][\p{Ll}_\p{Lu}\p{Lt}\p{Nd}&apos;]*(?:\.[\p{Lu}\p{Lt}][\p{Ll}_\p{Lu}\p{Lt}\p{Nd}&apos;]*)*)\s+)(?:(?&lt;classConstraint&gt;(?:[\p{Lu}\p{Lt}][\p{Ll}_\p{Lu}\p{Lt}\p{Nd}&apos;]*(?:\.[\p{Lu}\p{Lt}][\p{Ll}_\p{Lu}\p{Lt}\p{Nd}&apos;]*)*|(?:[\p{Lu}\p{Lt}][\p{Ll}_\p{Lu}\p{Lt}\p{Nd}&apos;]*(?:\.[\p{Lu}\p{Lt}][\p{Ll}_\p{Lu}\p{Lt}\p{Nd}&apos;]*)*\.)?[\p{Ll}_][\p{Ll}_\p{Lu}\p{Lt}\p{Nd}&apos;]*)(?:\s*(?:\s+)\s*\g&lt;classConstraint&gt;)?))))\s*(=&gt;|&lt;=|⇐|⇒)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#class_constraint</string>
								</dict>
							</array>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>keyword.other.big-arrow.purescript</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.other.arrow.purescript</string>
					<key>match</key>
					<string>-&gt;|→</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.other.big-arrow.purescript</string>
					<key>match</key>
					<string>=&gt;|⇒</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.other.big-arrow-left.purescript</string>
					<key>match</key>
					<string>&lt;=|⇐</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.other.forall.purescript</string>
					<key>match</key>
					<string>forall|∀</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#generic_type</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#type_name</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>purs</string>
	</array>
</dict>
</plist>
