<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Python Traceback</string>
	<key>scopeName</key>
	<string>text.python.traceback</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>^  File (&quot;[^&quot;]+&quot;), line (\d+)(?:, in (.+))?$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.python.traceback</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.python.traceback</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.python.traceback</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>^    (.+)$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.python</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>^([^\s:]+):(?: (.+))?$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.class.python.traceback</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.python.traceback</string>
				</dict>
			</dict>
		</dict>
	</array>
	<key>fileTypes</key>
	<array>
		<string>pytb</string>
	</array>
</dict>
</plist>
