<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>qsharp</string>
	<key>scopeName</key>
	<string>source.qsharp</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#library</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operations</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#types</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constants</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>comment.line.double-slash</string>
					<key>match</key>
					<string>\/\/.*$</string>
				</dict>
				<dict>
					<key>name</key>
					<string>comment.documentation</string>
					<key>match</key>
					<string>\/\/\/.*$</string>
				</dict>
			</array>
		</dict>
		<key>constants</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.language.qsharp</string>
					<key>match</key>
					<string>\b(true|false|Pauli(I|X|Y|Z)|One|Zero)\b</string>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.control.qsharp</string>
					<key>match</key>
					<string>\b(use|using|borrow|borrowing|mutable|let|set|if|elif|else|repeat|until|fixup|for|in|while|return|fail|within|apply)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.other.qsharp</string>
					<key>match</key>
					<string>\b(new|not|and|or|w/)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>invalid.illegal.ad.qsharp</string>
					<key>match</key>
					<string>\b(abstract|base|bool|break|byte|case|catch|char|checked|class|const|continue|decimal|default|delegate|do|double)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>invalid.illegal.el.qsharp</string>
					<key>match</key>
					<string>\b(enum|event|explicit|extern|finally|fixed|float|foreach|goto|implicit|int|interface|lock|long)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>invalid.illegal.ns.qsharp</string>
					<key>match</key>
					<string>\b(null|object|operator|out|override|params|private|protected|public|readonly|ref|sbyte|sealed|short|sizeof|stackalloc)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>invalid.illegal.sv.qsharp</string>
					<key>match</key>
					<string>\b(static|string|struct|switch|this|throw|try|typeof|unit|ulong|unchecked|unsafe|ushort|virtual|void|volatile)\b</string>
				</dict>
			</array>
		</dict>
		<key>library</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>support.function.quantum.qsharp</string>
					<key>match</key>
					<string>\b(X|Y|Z|H|HY|S|T|SWAP|CNOT|CCNOT|MultiX|R|RFrac|Rx|Ry|Rz|R1|R1Frac|Exp|ExpFrac|Measure|M|MultiM)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.function.builtin.qsharp</string>
					<key>match</key>
					<string>\b(Message|Length|Floor)\b</string>
				</dict>
			</array>
		</dict>
		<key>operations</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.other.qsharp</string>
					<key>match</key>
					<string>\b(namespace|open|as|internal|newtype|operation|function|body|(a|A)djoint|(c|C)ontrolled|self|auto|distribute|invert|intrinsic)\b</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>string.quoted.double.qsharp</string>
					<key>begin</key>
					<string>(\$|)&quot;</string>
					<key>end</key>
					<string>&quot;</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>constant.character.escape.qsharp</string>
							<key>match</key>
							<string>\\.</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>types</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>storage.type.qsharp</string>
					<key>match</key>
					<string>\b(Int|BigInt|Double|Bool|Qubit|Pauli|Result|Range|String|Unit|Ctl|Adj|is)\b</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>qs</string>
	</array>
</dict>
</plist>
