<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>QML</string>
	<key>scopeName</key>
	<string>source.qml</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>name</key>
			<string>comment.block.documentation.qml</string>
			<key>begin</key>
			<string>/\*(?!/)</string>
			<key>end</key>
			<string>\*/</string>
		</dict>
		<dict>
			<key>name</key>
			<string>comment.line.double-slash.qml</string>
			<key>match</key>
			<string>//.*$</string>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.import.qml</string>
			<key>begin</key>
			<string>\b(import)\s+</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.import.namespace.qml</string>
					<key>match</key>
					<string>([\w\d\.]+)\s+(\d+\.\d+)(?:\s+(as)\s+([A-Z][\w\d]*))?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.class.qml</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.qml</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.other.import.qml</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.name.class.qml</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.import.dirjs.qml</string>
					<key>match</key>
					<string>(\&quot;[^\&quot;]+\&quot;)(?:\s+(as)\s+([A-Z][\w\d]*))?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.qml</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.import.qml</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.class.qml</string>
						</dict>
					</dict>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.import.qml</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>support.class.qml</string>
			<key>match</key>
			<string>\b[A-Z]\w*\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.class.qml</string>
			<key>match</key>
			<string>(((^|\{)\s*)|\b)on[A-Z]\w*\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.id.qml</string>
			<key>match</key>
			<string>(?:^|\{)\s*(id)\s*\:\s*([^;\s]+)\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.qml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.qml</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.propertydef.qml</string>
			<key>match</key>
			<string>^\s*(?:(default|readonly)\s+)?(property)\s+(?:(alias)|([\w\&lt;\&gt;]+))\s+(\w+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.qml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.qml</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.other.qml</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>storage.type.qml</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.qml</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.signal.qml</string>
			<key>begin</key>
			<string>\b(signal)\s+(\w+)\s*</string>
			<key>end</key>
			<string>;|(?=/)|$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.signal.parameters.qml</string>
					<key>match</key>
					<string>(\w+)\s+(\w+)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.qml</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.qml</string>
						</dict>
					</dict>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.qml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.qml</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.keyword.qml</string>
			<key>match</key>
			<string>(?:\b|\s+)(?:(true|false|null|undefined)|(var|void)|(on|as|enum|connect|break|case|catch|continue|debugger|default|delete|do|else|finally|for|if|in|instanceof|new|return|switch|this|throw|try|typeof|while|with))\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language.qml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.qml</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.control.qml</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.function.qml</string>
			<key>match</key>
			<string>\b(function)\s+([\w_]+)\s*(?=\()</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.qml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.untitled</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.qml</string>
			<key>match</key>
			<string>\b[\w_]+\s*(?=\()</string>
		</dict>
		<dict>
			<key>name</key>
			<string>entity.other.attribute-name.qml</string>
			<key>match</key>
			<string>(?:^|\{|;)\s*[a-z][\w\.]*\s*(?=\:)</string>
		</dict>
		<dict>
			<key>name</key>
			<string>entity.other.attribute-name.qml</string>
			<key>match</key>
			<string>(?&lt;=\.)\b\w*</string>
		</dict>
		<dict>
			<key>name</key>
			<string>variable.parameter</string>
			<key>match</key>
			<string>\b([a-z_]\w*)\b</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.js</string>
		</dict>
	</array>
	<key>fileTypes</key>
	<array>
		<string>qml</string>
		<string>qbs</string>
	</array>
</dict>
</plist>
