<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Record Jar</string>
	<key>scopeName</key>
	<string>source.record-jar</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#main</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>escape</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\\$\s*</string>
					<key>end</key>
					<string>(?&lt;=[^\s#%&quot;&apos;])(?!\G)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>constant.character.escape.newline.record-jar</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.escape.backslash.record-jar</string>
					<key>match</key>
					<string>\\.</string>
				</dict>
			</array>
		</dict>
		<key>field</key>
		<dict>
			<key>name</key>
			<string>meta.field.record-jar</string>
			<key>begin</key>
			<string>(?:\G|^)(\s*)((?!%%|#)\S.*?)\s*(:)\s*</string>
			<key>end</key>
			<string>(?!\G)^(?!\1\s)(?=\S)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.other.date.record-jar</string>
					<key>match</key>
					<string>\G([0-9]{4})(-)(0[0-9]|1[0-2])(-)([0-2][0-9]|3[01])(?=\s|$)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.integer.year.record-jar</string>
						</dict>
						<key>2</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>etc#dash</string>
								</dict>
							</array>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.integer.month.record-jar</string>
						</dict>
						<key>4</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>etc#dash</string>
								</dict>
							</array>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.integer.day.record-jar</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.list.record-jar</string>
					<key>begin</key>
					<string>\G\s*(?=&quot;|&apos;)</string>
					<key>end</key>
					<string>(?=^)(?! |\t)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string</string>
						</dict>
						<dict>
							<key>include</key>
							<string>etc#comma</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#lineContinuation</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>contentName</key>
					<string>string.unquoted.record-jar</string>
					<key>begin</key>
					<string>\G\s*(?=[^&quot;&apos;#%\s])</string>
					<key>end</key>
					<string>(?=^)(?! |\t)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escape</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.leading.field.record-jar</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.field-name.record-jar</string>
				</dict>
				<key>3</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>etc#kolon</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>main</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#record</string>
				</dict>
				<dict>
					<key>include</key>
					<string>etc#commentHash</string>
				</dict>
			</array>
		</dict>
		<key>record</key>
		<dict>
			<key>name</key>
			<string>meta.record.record-jar</string>
			<key>begin</key>
			<string>\A|(?:^|\G)(%%)(?:\s*(\S.*?))?[ \t]*$</string>
			<key>end</key>
			<string>(?=^%%)(?!\G)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#field</string>
				</dict>
				<dict>
					<key>include</key>
					<string>etc#commentHash</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.separator.record-jar</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment.line.ignored.record-jar</string>
				</dict>
			</dict>
		</dict>
		<key>string</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>string.quoted.double.record-jar</string>
					<key>begin</key>
					<string>&quot;</string>
					<key>end</key>
					<string>&quot;|(?=\s*(?&lt;!\\)$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escape</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.record-jar</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.record-jar</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>string.quoted.single.record-jar</string>
					<key>begin</key>
					<string>&apos;</string>
					<key>end</key>
					<string>&apos;(?=\s*(?&lt;!\\)$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escape</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.record-jar</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.record-jar</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>language-subtag-registry.txt</string>
	</array>
</dict>
</plist>
