<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Redirect Rules</string>
	<key>scopeName</key>
	<string>source.redirects</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#main</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>code</key>
		<dict>
			<key>name</key>
			<string>string.unquoted.code.redirects</string>
			<key>match</key>
			<string>(?&lt;==)[a-z]{2}(?:-[A-Z]{2})?(?=\s|$)</string>
		</dict>
		<key>comment</key>
		<dict>
			<key>name</key>
			<string>comment.line.hash.redirects</string>
			<key>begin</key>
			<string>#</string>
			<key>end</key>
			<string>$</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.redirects</string>
				</dict>
			</dict>
		</dict>
		<key>main</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#uri</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#query</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#code</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#punct</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#text</string>
				</dict>
			</array>
		</dict>
		<key>number</key>
		<dict>
			<key>match</key>
			<string>(\d+)(!)?</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.integer.redirects</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.character.force.redirects</string>
				</dict>
			</dict>
		</dict>
		<key>punct</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>punctuation.accessor.redirects</string>
					<key>match</key>
					<string>:|=</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.separator.redirects</string>
					<key>match</key>
					<string>,(?!\s)</string>
				</dict>
			</array>
		</dict>
		<key>query</key>
		<dict>
			<key>name</key>
			<string>keyword.other.query-selector.redirects</string>
			<key>match</key>
			<string>[^\s]+(?==)</string>
		</dict>
		<key>splat</key>
		<dict>
			<key>name</key>
			<string>variable.other.splat.redirects</string>
			<key>match</key>
			<string>:\w+</string>
		</dict>
		<key>text</key>
		<dict>
			<key>name</key>
			<string>string.unquoted.text.redirects</string>
			<key>match</key>
			<string>(?&lt;==)[^\s]+</string>
		</dict>
		<key>uri</key>
		<dict>
			<key>name</key>
			<string>string.unquoted.uri.redirects</string>
			<key>begin</key>
			<string>(?:[a-z]+:)?\/</string>
			<key>end</key>
			<string>[\s$]</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#wildcard</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#splat</string>
				</dict>
			</array>
		</dict>
		<key>wildcard</key>
		<dict>
			<key>name</key>
			<string>constant.character.wildcard.redirects</string>
			<key>match</key>
			<string>\*</string>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>_redirects</string>
	</array>
</dict>
</plist>
