<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>RTF</string>
	<key>scopeName</key>
	<string>text.rtf</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>\{\\\*</string>
			<key>end</key>
			<string>}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.begin-ignorable-destination-group.rtf</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.end-ignorable-destination-group.rtf</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>end</key>
			<string>}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.begin-group.rtf</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.end-group.rtf</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.character.escape.rtf</string>
			<key>match</key>
			<string>\\[\\{}]</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.operator.formula.rtf</string>
			<key>match</key>
			<string>\\\|</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.character.escape.non-breaking-space.rtf</string>
			<key>match</key>
			<string>\\~</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.character.escape.optional-hyphen.rtf</string>
			<key>match</key>
			<string>\\-</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.character.escape.non-breaking-hyphen.rtf</string>
			<key>match</key>
			<string>\\_</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.operator.index-subentry.rtf</string>
			<key>match</key>
			<string>\\:</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.operator.ignorable-destination.rtf</string>
			<key>match</key>
			<string>\\\*</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.par.rtf</string>
			<key>match</key>
			<string>\\[\n\r]</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.character.entity.rtf</string>
			<key>match</key>
			<string>(\\&apos;)[0-9A-Fa-f]{2}</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.constant.rtf</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>contentName</key>
			<string>markup.bold.rtf</string>
			<key>begin</key>
			<string>\\b\b</string>
			<key>end</key>
			<string>(?=\\(?:b0(?:\b|[^\d])|plain\b)|})</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>support.function.rtf</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>contentName</key>
			<string>markup.italic.rtf</string>
			<key>begin</key>
			<string>\\i\b</string>
			<key>end</key>
			<string>(?=\\(?:i0(?:\b|[^\d])|plain\b)|})</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>support.function.rtf</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>contentName</key>
			<string>markup.strike.rtf</string>
			<key>begin</key>
			<string>\\strike\b</string>
			<key>end</key>
			<string>(?=\\(?:strike0(?:\b|[^\d])|plain\b)|})</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>support.function.rtf</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>(\\[A-Za-z]+)(?:(-?)(\d+))?</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.rtf</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.rtf</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.rtf</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>invalid.unimplemented.rtf</string>
			<key>match</key>
			<string>\\[^A-Za-z]</string>
		</dict>
	</array>
	<key>fileTypes</key>
	<array>
		<string>rtf</string>
	</array>
</dict>
</plist>
