<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>RPMSpec</string>
	<key>scopeName</key>
	<string>source.rpm-spec</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>name</key>
			<string>keyword.rpm-spec</string>
			<key>match</key>
			<string>^# norootforbuild</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#conditionals</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#commands</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#macros</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#metadata</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#sections</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#modifiers</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#variables</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#architectures</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#licenses</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constants</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operators</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>architectures</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.language.rpm-spec</string>
					<key>match</key>
					<string>\b(?:noarch|i386|i586|x86_64|ia64|local)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.rpm-spec</string>
					<key>match</key>
					<string>\b(?:s390x|s390|armv6l|armv7hl|armv7l)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.rpm-spec</string>
					<key>match</key>
					<string>\b(?:ppc64p7|ppc64le|ppc64|ppc|aarch64)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.rpm-spec</string>
					<key>match</key>
					<string>\b(?:alpha|sparc64|sparcv9|sparc)\b</string>
				</dict>
			</array>
		</dict>
		<key>changelogs</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.changelogs.rpm-spec</string>
				</dict>
			</array>
		</dict>
		<key>commands</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>support.constant.rpm-spec</string>
					<key>match</key>
					<string>^%__(?:aclocal|ar|as|autoconf)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.constant.rpm-spec</string>
					<key>match</key>
					<string>^%__(?:autoheader|automake|awk)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.constant.rpm-spec</string>
					<key>match</key>
					<string>^%__(?:bzip2|bzip|cat|cc|chgrp_Rhf|chgrp)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.constant.rpm-spec</string>
					<key>match</key>
					<string>^%__(?:chmod|chown_Rhf|chown|cpio|cp)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.constant.rpm-spec</string>
					<key>match</key>
					<string>^%__(?:cpp|cxx|grep|gzip|patch)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.constant.rpm-spec</string>
					<key>match</key>
					<string>^%__(?:id_u|id|install|ld|libtoolize)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.constant.rpm-spec</string>
					<key>match</key>
					<string>^%__(?:ln_s|make|mkdir_p|mkdir|mv)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.constant.rpm-spec</string>
					<key>match</key>
					<string>^%__(?:nm|objcopy|objdump|perl)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.constant.rpm-spec</string>
					<key>match</key>
					<string>^%__(?:pgp|prelink_undo_cmd|python)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.constant.rpm-spec</string>
					<key>match</key>
					<string>^%__(?:ranlib|rm|sed|strip|tar|unzip)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.constant.rpm-spec</string>
					<key>match</key>
					<string>^%\{__(?:aclocal|ar|as|autoconf)\}</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.constant.rpm-spec</string>
					<key>match</key>
					<string>^%\{__(?:autoheader|automake|awk)\}</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.constant.rpm-spec</string>
					<key>match</key>
					<string>^%\{__(?:bzip2|bzip|cat|cc|chgrp_Rhf|chgrp)\}</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.constant.rpm-spec</string>
					<key>match</key>
					<string>^%\{__(?:chmod|chown_Rhf|chown|cpio|cp)\}</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.constant.rpm-spec</string>
					<key>match</key>
					<string>^%\{__(?:cpp|cxx|grep|gzip|patch)\}</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.constant.rpm-spec</string>
					<key>match</key>
					<string>^%\{__(?:id_u|id|install|ld|libtoolize)\}</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.constant.rpm-spec</string>
					<key>match</key>
					<string>^%\{__(?:ln_s|make|mkdir_p|mkdir|mv)\}</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.constant.rpm-spec</string>
					<key>match</key>
					<string>^%\{__(?:nm|objcopy|objdump|perl)\}</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.constant.rpm-spec</string>
					<key>match</key>
					<string>^%\{__(?:pgp|prelink_undo_cmd|python)\}</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.constant.rpm-spec</string>
					<key>match</key>
					<string>^%\{__(?:ranlib|rm|sed|strip|tar|unzip)\}</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(#)(?&lt;!C#|F#|M#)(.*)$</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.comment.rpm-spec</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>comment.line.rpm-spec</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>conditionals</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.control.rpm-spec</string>
					<key>match</key>
					<string>%(?:ifarch|ifnarch|ifnos|ifos|if|else|endif)</string>
				</dict>
			</array>
		</dict>
		<key>constants</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>contstant.numeric.rpm-spec</string>
					<key>match</key>
					<string>[0-9]+</string>
				</dict>
			</array>
		</dict>
		<key>licenses</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.language.rpm-spec</string>
					<key>match</key>
					<string>(?:AFL-2.1|AGPL-3.0|AGPL-3.0\+|Apache-1.1|Apache-2.0)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.rpm-spec</string>
					<key>match</key>
					<string>(?:X11|xinetd|Zlib|ZPL-2.0|ZPL-2.1)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.rpm-spec</string>
					<key>match</key>
					<string>(?:Apache-2.0+|APL-1.0|BSD-2-Clause|BSD-3-Clause|BSD-4-Clause)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.rpm-spec</string>
					<key>match</key>
					<string>(?:Artistic-1.0|Artistic-1.0+|Artistic-2.0|Beerware)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.rpm-spec</string>
					<key>match</key>
					<string>(?:CC-BY-ND-4.0|CC-BY-SA-2.5|CC-BY-SA-3.0)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.rpm-spec</string>
					<key>match</key>
					<string>(?:CC-BY-SA-3.0|CC-BY-SA-4.0|CDDL-1.0|CPL-1.0|EPL-1.0)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.rpm-spec</string>
					<key>match</key>
					<string>(?:ErlPL-1.1|GFDL-1.1|GFDL-1.1\+|GFDL-1.2|GFDL-1.2\+|GFDL-1.3)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.rpm-spec</string>
					<key>match</key>
					<string>(?:GFDL-1.3\+|GPL-1.0\+|GPL-2.0|GPL-2.0\+|GPL-3.0|GPL-3.0\+|IJG)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.rpm-spec</string>
					<key>match</key>
					<string>(?:LGPL-2.0\+|LGPL-2.1|LGPL-2.1\+|LGPL-3.0\+|LPPL-1.3c)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.rpm-spec</string>
					<key>match</key>
					<string>(?:IPA|IPL-1.0|IPL-1.0|ISC|JSON|LGPL-2.0|MakeIndex|MIT)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.rpm-spec</string>
					<key>match</key>
					<string>(?:MPL-1.0|MPL-1.1|MPL-1.1\+|MS-PL|NetCDF|OFL-1.1|OLDAP-2.8)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.rpm-spec</string>
					<key>match</key>
					<string>(?:OSL-1.1|PHP-3.01|Python-2.0|Qhull|QPL-1.0|QPL-1.0|Ruby)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.rpm-spec</string>
					<key>match</key>
					<string>(?:SUSE-BSD-3-Clause-with-non-nuclear-addition)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.rpm-spec</string>
					<key>match</key>
					<string>(?:SUSE-GPL-2.0\+-with-sane-exception|SUSE-GPL-3.0-with-FLOSS-exception)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.rpm-spec</string>
					<key>match</key>
					<string>(?:SUSE-GPL-3.0-with-font-exception|SUSE-GPL-3.0-with-openssl-exception)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.rpm-spec</string>
					<key>match</key>
					<string>(?:SUSE-GPL-3.0-with-template-exception|SUSE-GPL-3.0+-with-autoconf-exception)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.rpm-spec</string>
					<key>match</key>
					<string>(?:SUSE-GPL-3.0\+-with-font-exception|SUSE-GPL-3.0\+-with-openssl-exception)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.rpm-spec</string>
					<key>match</key>
					<string>(?:SUSE-IBPL-1.0|SUSE-IDPL-1.0|SUSE-IEEE|SUSE-Innernet-2.0|SUSE-Innernet-2.00)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.rpm-spec</string>
					<key>match</key>
					<string>(?:SUSE-LDPL-2.0|SUSE-LGPL-2.0-with-linking-exception)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.rpm-spec</string>
					<key>match</key>
					<string>(?:SUSE-LGPL-2.1-with-digia-exception-1.1)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.rpm-spec</string>
					<key>match</key>
					<string>(?:SUSE-LGPL-2.1-with-nokia-exception-1.1)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.rpm-spec</string>
					<key>match</key>
					<string>(?:SUSE-LGPL-2.1\+-with-GCC-exception|SUSE-LGPL-3.0-with-openssl-exception)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.rpm-spec</string>
					<key>match</key>
					<string>(?:SUSE-Liberation|SUSE-Manpages|SUSE-Matplotlib|SUSE-MgOpen|SUSE-mirror)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.rpm-spec</string>
					<key>match</key>
					<string>(?:SUSE-mplus|SUSE-NonFree|SUSE-Oasis-Specification-Notice)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.rpm-spec</string>
					<key>match</key>
					<string>(?:SUSE-OpenPublication-1.0|SUSE-OldFSFDocLicense|SUSE-Permissive)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.rpm-spec</string>
					<key>match</key>
					<string>(?:SUSE-Permissive-Modify-By-Patch|SUSE-PHP-2.02|SUSE-Public-Domain)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.rpm-spec</string>
					<key>match</key>
					<string>(?:SUSE-Python-1.6|SUSE-QWT-1.0|SUSE-Redistributable-Content|SUSE-Repoze)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.rpm-spec</string>
					<key>match</key>
					<string>(?:SUSE-Scrot|SUSE-Sendmail|SUSE-SGI-FreeB-2.0|SUSE-SIP|SUSE-SLIB)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.rpm-spec</string>
					<key>match</key>
					<string>(?:SUSE-SNIA-1.0|SUSE-SNIA-1.1|SUSE-Sun-Laboratories|SUSE-TeX|SUSE-TGPPL-1.0)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.rpm-spec</string>
					<key>match</key>
					<string>(?:SUSE-Ubuntu-Font-License-1.0|SUSE-Xano|SUSE-Xenonsoft-1.00)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.rpm-spec</string>
					<key>match</key>
					<string>(?:SUSE-XFree86-with-font-exception|SUSE-XSL-Lint|TCL|Unicode|Vim|W3C|WTFPL)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.rpm-spec</string>
					<key>match</key>
					<string>(?:SUSE-Bitstream-Vera|OML|OPL-1.0|SUSE-Arphic)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.rpm-spec</string>
					<key>match</key>
					<string>(?:SUSE-BSD-Mark-Modifications|SUSE-CacertRoot)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.rpm-spec</string>
					<key>match</key>
					<string>(?:SUSE-Copyleft-Next-0.3.0|SUSE-CPL-0.5|SUSE-Curb|SUSE-DMTF)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.rpm-spec</string>
					<key>match</key>
					<string>(?:SUSE-Docbook-XSL|SUSE-Egenix-1.1.0|SUSE-EULA|SUSE-FHS)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.rpm-spec</string>
					<key>match</key>
					<string>(?:SUSE-Firmware|SUSE-FLTK|SUSE-Free-Art-1.3|SUSE-Freetype)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.rpm-spec</string>
					<key>match</key>
					<string>(?:SUSE-Gitslave|SUSE-GL2PS-2.0|SUSE-Gnuplot)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.rpm-spec</string>
					<key>match</key>
					<string>(?:SUSE-GPL-2.0-with-FLOSS-exception)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.rpm-spec</string>
					<key>match</key>
					<string>(?:SUSE-CC-Sampling-Plus-1.0|SUSE-GPL-2.0-with-linking-exception)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.rpm-spec</string>
					<key>match</key>
					<string>(?:SUSE-GPL-2.0-with-openssl-exception)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.rpm-spec</string>
					<key>match</key>
					<string>(?:SUSE-GPL-2.0-with-OSI-exception)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.rpm-spec</string>
					<key>match</key>
					<string>(?:SUSE-GPL-2.0-with-plugin-exception)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.rpm-spec</string>
					<key>match</key>
					<string>(?:SUSE-GPL-2.0\+-with-openssl-exception)</string>
				</dict>
			</array>
		</dict>
		<key>macros</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>^(%(?:setup|patch[0-9]*|configure|autosetup))</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.rpm-spec</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>support.function.rpm-spec</string>
					<key>match</key>
					<string>^%\{?(?:desktop_database_postun|desktop_database_post)\}?</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.function.rpm-spec</string>
					<key>match</key>
					<string>^%\{?(?:fillup_and_insserv|fillup_only|find_lang)\}?</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.function.rpm-spec</string>
					<key>match</key>
					<string>^%\{?(?:icon_theme_cache_postun|icon_theme_cache_post)\}?</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.function.rpm-spec</string>
					<key>match</key>
					<string>^%\{?(?:insserv_cleanup|insserv_force_if_yast)\}?</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.function.rpm-spec</string>
					<key>match</key>
					<string>^%\{?(?:install_info_delete|install_info|gpg_verify)\}?</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.function.rpm-spec</string>
					<key>match</key>
					<string>^%\{?(?:perl_archlib|perl_gen_filelist)\}?</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.function.rpm-spec</string>
					<key>match</key>
					<string>^%\{?(?:perl_make_install|perl_process_packlist)\}?</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.function.rpm-spec</string>
					<key>match</key>
					<string>^%\{?(?:perl_sitearch|perl_sitelib)\}?</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.function.rpm-spec</string>
					<key>match</key>
					<string>^%\{?(?:perl_vendorarch|perl_vendorlib|perl_version)\}?</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.function.rpm-spec</string>
					<key>match</key>
					<string>^%\{?(?:py_incdir|py_libdir|py_requires|py_sitedir|py_ver)\}?</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.function.rpm-spec</string>
					<key>match</key>
					<string>^%\{?(?:remove_and_set|restart_on_update)\}?</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.function.rpm-spec</string>
					<key>match</key>
					<string>^%\{?(?:run_ldconfig|run_permissions)\}?</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.function.rpm-spec</string>
					<key>match</key>
					<string>^%\{?(?:service_add_pre|service_add_post)\}?</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.function.rpm-spec</string>
					<key>match</key>
					<string>^%\{?(?:service_del_preun|service_del_postun)\}?</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.function.rpm-spec</string>
					<key>match</key>
					<string>^%\{?(?:set_permissions|stop_on_removal)\}?</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.function.rpm-spec</string>
					<key>match</key>
					<string>^%\{?(?:suse_update_config|suse_update_desktop_file)\}?</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.function.rpm-spec</string>
					<key>match</key>
					<string>^%\{?(?:tcl_version|ul_version|verify_permissions)\}?</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.function.rpm-spec</string>
					<key>match</key>
					<string>^%\{?(?:create_subdir_filelist|create_exclude_filelist)\}?</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.function.rpm-spec</string>
					<key>match</key>
					<string>^%\{?(?:makeinstall|make_jobs|update_menus|clean_menus)\}?</string>
				</dict>
			</array>
		</dict>
		<key>metadata</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.rpm-spec</string>
					<key>match</key>
					<string>^(?:Icon|ExclusiveOs|ExcludeOs|NoSource|NoPatch):</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.rpm-spec</string>
					<key>match</key>
					<string>^(?:Conflicts|Obsoletes|Provides):</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.rpm-spec</string>
					<key>match</key>
					<string>^(?:Requires\((?:preun|postun|pre|post)\)|Requires):</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.rpm-spec</string>
					<key>match</key>
					<string>^(Enhances|Suggests|BuildConflicts|BuildRequires|Recommends):</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.rpm-spec</string>
					<key>match</key>
					<string>^(PreReq|Supplements|Epoch|Serial|Nosource|Nopatch):</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.rpm-spec</string>
					<key>match</key>
					<string>^(AutoReq|AutoProv|AutoReqProv):</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.rpm-spec</string>
					<key>match</key>
					<string>^(Copyright|Summary|Summary\(.*\)|Distribution):</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.rpm-spec</string>
					<key>match</key>
					<string>^(Vendor|Packager|Group|Source\d*|Patch\d*|BuildRoot|Prefix):</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.rpm-spec</string>
					<key>match</key>
					<string>^(Name|Version|Release|Url|URL):</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.rpm-spec</string>
					<key>match</key>
					<string>^(Source|Patch)[0-9]*:</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>^((?:BuildArch|BuildArchitectures|ExclusiveArch|ExcludeArch):)</string>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#architectures</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.rpm-spec</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>begin</key>
					<string>^(License:)[ \t]*</string>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#licenses</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.rpm-spec</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>modifiers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>storage.modifier.rpm-spec</string>
					<key>match</key>
					<string>^%(?:define|global|undefine|docdir|doc)</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^(%config(?:\(noreplace\))?)[ \t]+</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.rpm-spec</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>^(%defattr\(.*\))</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.rpm-spec</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>(%(?:attrib|attr|verify|noverify)\(.*\)) </string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.rpm-spec</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>(%(?:lang|caps)\(.*\)) </string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.rpm-spec</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.operator.logical.rpm-spec</string>
					<key>match</key>
					<string>(?:[&gt;=]?=|!=?|&lt;|&gt;|&amp;&amp;|\|\|)</string>
				</dict>
			</array>
		</dict>
		<key>sections</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>entity.name.section.rpm-spec</string>
					<key>match</key>
					<string>^%(?:description|package)</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>^(%changelog)</string>
					<key>end</key>
					<string>Z</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#changelogs</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.section.rpm-spec</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>begin</key>
					<string>^(%files)</string>
					<key>end</key>
					<string>^$|Z</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#std_section</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.section.rpm-spec</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>begin</key>
					<string>^(%(?:build|check|clean|install|verifyscript))$</string>
					<key>end</key>
					<string>^$|Z</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#std_section</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.section.rpm-spec</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>entity.name.section.rpm-spec</string>
					<key>match</key>
					<string>^%(?:triggerin|triggerpostun|triggerun|trigger) --</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>^(%(?:preun|prep|pretrans|pre|posttrans|postun|post|packagepreun))</string>
					<key>end</key>
					<string>^$|Z</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#std_section</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.section.rpm-spec</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>shell_syntax</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.shell</string>
				</dict>
			</array>
		</dict>
		<key>std_section</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#metadata</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#conditionals</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#commands</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#macros</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#modifiers</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variables</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#licenses</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#shell_syntax</string>
				</dict>
			</array>
		</dict>
		<key>variables</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(%\{with) ([a-zA-Z_][a-zA-Z0-9_:]*)(\})</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.other.bracket.rpm-spec</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.rpm-spec</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.other.bracket.rpm-spec</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>(%\{defined) ([a-zA-Z_][a-zA-Z0-9_:]*)(\})</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.other.bracket.rpm-spec</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.rpm-spec</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.other.bracket.rpm-spec</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>(%\{[!?]+)(_?[a-zA-Z]+[a-zA-Z0-9:_]*)(\})</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.other.bracket.rpm-spec</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.rpm-spec</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.other.bracket.rpm-spec</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>(%\{)(_?[a-zA-Z][a-zA-Z0-9_:]*)(\})</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.other.bracket.rpm-spec</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.rpm-spec</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.other.bracket.rpm-spec</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>(%[!?]+)(_?[a-zA-Z][a-zA-Z0-9_:]*)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.other.bracket.rpm-spec</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.rpm-spec</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>(%)(_?[a-zA-Z][a-zA-Z0-9_:]*)?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.other.bracket.rpm-spec</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.rpm-spec</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>spec</string>
	</array>
</dict>
</plist>
