<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>RUNOFF</string>
	<key>scopeName</key>
	<string>text.runoff</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#main</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>arguments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.numeric.runoff</string>
					<key>match</key>
					<string>[-+]?\d+(?:\.\d+)?</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.separator.comma.runoff</string>
					<key>match</key>
					<string>,</string>
				</dict>
				<dict>
					<key>name</key>
					<string>string.quoted.runoff</string>
					<key>begin</key>
					<string>&quot;</string>
					<key>end</key>
					<string>&quot;</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.runoff</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.runoff</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>variable.parameter.runoff</string>
					<key>match</key>
					<string>(?!\.)([^\s;,]+)</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.runoff</string>
						</dict>
						<key>1</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#name-innards</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>commands</key>
		<dict>
			<key>name</key>
			<string>meta.control-line.runoff</string>
			<key>begin</key>
			<string>^*(?=\.)</string>
			<key>end</key>
			<string>$|;(?!\.)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>comment.line.runoff</string>
					<key>begin</key>
					<string>!</string>
					<key>end</key>
					<string>$</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.runoff</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.condition.runoff</string>
					<key>begin</key>
					<string>(?i)(?:^|(?&lt;=;))((\.)(?:IF|ELSE|ENDIF))(?=$|\s|;)</string>
					<key>end</key>
					<string>$|(;)|(?=!)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#arguments</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.runoff</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.runoff</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.terminator.statement.runoff</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>contentName</key>
					<string>markup.raw.runoff</string>
					<key>begin</key>
					<string>(?i)((\.)LITERAL\s*)(?:$|\R)</string>
					<key>end</key>
					<string>(?i)((\.)END\s+LITERAL)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.function.name.runoff</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.runoff</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.runoff</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.function.name.runoff</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.runoff</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.runoff</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>contentName</key>
					<string>markup.raw.runoff</string>
					<key>begin</key>
					<string>(?i)((\.)LIT)\s*(?:$|\R)</string>
					<key>end</key>
					<string>(?i)^(?=\.(?:EL|END\s+LIT)(?:$|[\s;!]))</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.function.name.runoff</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.runoff</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.runoff</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.function.debugging-comment.runoff</string>
					<key>contentName</key>
					<string>string.unquoted.runoff</string>
					<key>begin</key>
					<string>(?i)((\.)COMMENT)\b</string>
					<key>end</key>
					<string>$|(;)|(?=!)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.function.name.runoff</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.runoff</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.runoff</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.terminator.statement.runoff</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.function.runoff</string>
					<key>begin</key>
					<string>(?i)((\.)(?:END\s+)?([^;\s\-+]+))</string>
					<key>end</key>
					<string>(?x)
$               | # EOL
(;)?\s*(?=\.) | # Followed by another command
(?=;\s*[^.])     # No more commands, don’t highlight trailing text as arguments</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#arguments</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.function.name.runoff</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.runoff</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.runoff</string>
						</dict>
						<key>3</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#name-innards</string>
								</dict>
							</array>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.terminator.statement.runoff</string>
						</dict>
					</dict>
				</dict>
			</array>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.terminator.statement.runoff</string>
				</dict>
			</dict>
		</dict>
		<key>comment</key>
		<dict>
			<key>name</key>
			<string>comment.line.runoff</string>
			<key>begin</key>
			<string>^\.[!*~]</string>
			<key>end</key>
			<string>$</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.runoff</string>
				</dict>
			</dict>
		</dict>
		<key>main</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#underline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#commands</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#special-characters</string>
				</dict>
			</array>
		</dict>
		<key>name-innards</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#special-characters</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.delimiter.period.full-stop.runoff</string>
					<key>match</key>
					<string>\.</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.separator.comma.runoff</string>
					<key>match</key>
					<string>\,</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.runoff</string>
					<key>match</key>
					<string>\d+(?=$|\R|,|\.(?!\d))</string>
				</dict>
			</array>
		</dict>
		<key>special-characters</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.character.escape.special-character.runoff</string>
					<key>match</key>
					<string>(_)[!^\\#&amp;_.]</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.escape.runoff</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.end-footnote.runoff</string>
					<key>match</key>
					<string>^!</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.escape.uppercase.runoff</string>
					<key>match</key>
					<string>\^{1,2}</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.escape.runoff</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.escape.lowercase.runoff</string>
					<key>match</key>
					<string>\\{1,2}</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.escape.runoff</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>(&amp;)([!^\\#&amp;_.]*)(\S+)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entity.runoff</string>
						</dict>
						<key>2</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#special-characters</string>
								</dict>
							</array>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>markup.underline.link.runoff</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.escape.space.runoff</string>
					<key>match</key>
					<string>#</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.escape.runoff</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>underline</key>
		<dict>
			<key>name</key>
			<string>markup.underline.link.runoff</string>
			<key>match</key>
			<string>[^_](?=_)|(?&lt;=_)[^_]</string>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>rnh</string>
		<string>rno</string>
	</array>
</dict>
</plist>
