<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Sass</string>
	<key>scopeName</key>
	<string>source.sass</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>name</key>
			<string>meta.variable-declaration.sass</string>
			<key>begin</key>
			<string>(?:(!)|(\$))([a-zA-Z0-9_-]+)\s*(?=(\|\|)?=|:\s+)</string>
			<key>end</key>
			<string>(;)?$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.property-value.sass</string>
					<key>begin</key>
					<string>(?:(:)\s+)|((\|\|)?=)</string>
					<key>end</key>
					<string>(?=;?$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#property-value</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.key-value.css</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.deprecated.sass</string>
						</dict>
					</dict>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.deprecated.sass</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.entity.sass</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.other.sass</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.punctuation.sass</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.at-rule.if.sass</string>
			<key>begin</key>
			<string>\s*((@)if\b)\s+</string>
			<key>end</key>
			<string>(;)?$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#property-value</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.if.sass</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.entity.sass</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.punctuation.sass</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.at-rule.else.sass</string>
			<key>begin</key>
			<string>\s*((@)(?:(?:else(?=\s*$))|(?:else\s+if\s+(?=\S+))))</string>
			<key>end</key>
			<string>(;)?$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#property-value</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.else.sass</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.entity.sass</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.punctuation.sass</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.at-rule.while.sass</string>
			<key>begin</key>
			<string>\s*((@)while\b)\s+</string>
			<key>end</key>
			<string>(;)?$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#property-value</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.while.sass</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.entity.sass</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.punctuation.sass</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.at-rule.for.sass</string>
			<key>begin</key>
			<string>\s*((@)for\b)\s+</string>
			<key>end</key>
			<string>(;)?$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#property-value</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.for.sass</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.entity.sass</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.punctuation.sass</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.at-rule.each.sass</string>
			<key>begin</key>
			<string>\s*((@)each\b)\s+</string>
			<key>end</key>
			<string>(;)?$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#property-value</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.each.sass</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.entity.sass</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.punctuation.sass</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.at-rule.function.sass</string>
			<key>begin</key>
			<string>^((@)function\b)\s*([a-zA-Z0-9_-]+)</string>
			<key>end</key>
			<string>(;)?$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#property-value</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.at-rule.function.sass</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.entity.sass</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.function.misc.sass</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.punctuation.sass</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.at-rule.return.sass</string>
			<key>begin</key>
			<string>\s*((@)return\b)\s+</string>
			<key>end</key>
			<string>(;)?$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#property-value</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.return.sass</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.entity.sass</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.punctuation.sass</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.variable-declaration.sass.mixin</string>
			<key>begin</key>
			<string>^(=\s*|(?:(@)mixin))\s+([a-zA-Z0-9_-]+)</string>
			<key>end</key>
			<string>(;)?$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#property-value</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.at-rule.mixin.sass</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.entity.sass</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.other.sass</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.punctuation.sass</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.at-rule.content.sass</string>
			<key>begin</key>
			<string>\s*((@)content)\s*$</string>
			<key>end</key>
			<string>(;)?$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#property-value</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.content.sass</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.entity.sass</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.punctuation.sass</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.function.include.sass</string>
			<key>begin</key>
			<string>^\s*(\+(?!\s+)|(?:(@)include(?=\s+)))\s*(?:([\w-]+)(\.))?([a-zA-Z0-9_-]+)</string>
			<key>end</key>
			<string>(;)?$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#property-value</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.at-rule.include.sass</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.entity.sass</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.sass</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.access.module.sass</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>variable.other.sass</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.punctuation.sass</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.function.extend.sass</string>
			<key>match</key>
			<string>^\s*(@extend)\s+([.*&amp;#%a-zA-Z][-_:.*&amp;#a-zA-Z]*)\s*(;)?\s*$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.at-rule.extend.sass</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other.sass</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.punctuation.sass</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.at-rule.warn.sass</string>
			<key>begin</key>
			<string>\s*((@)(warn|debug|error)\b)\s*</string>
			<key>end</key>
			<string>(;)?$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string-single</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-double</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.warn.sass</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.entity.sass</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.punctuation.sass</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.at-rule.at-root.sass</string>
			<key>begin</key>
			<string>^\s*((@)at-root)(?!(?:\s+[^.\(])|(?:\s+\((?!with)))</string>
			<key>end</key>
			<string>(;)?$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?:(\((?:with(?:out)?)\s*:\s*[a-zA-Z ]+\))|((?:[.*&amp;#a][:*&amp;#a-zA-Z]+)+))</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.misc.sass</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>.entity.other.attribute-name</string>
						</dict>
					</dict>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.at-root.sass</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.entity.sass</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.punctuation.sass</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.at-rule.use.sass</string>
			<key>begin</key>
			<string>^\s*((@)use\b)\s*</string>
			<key>end</key>
			<string>(;)?$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.control.operator</string>
					<key>match</key>
					<string>\b(as|with)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>variable.sass</string>
					<key>match</key>
					<string>\b[\w-]+\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>variable.language.expanded-namespace.sass</string>
					<key>match</key>
					<string>\*</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-single</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-double</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\(</string>
					<key>end</key>
					<string>\)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#property-value</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.module.begin.bracket.round.sass</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.module.end.bracket.round.sass</string>
						</dict>
					</dict>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.at-rule.use.sass</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.keyword.sass</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.punctuation.sass</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.at-rule.forward.sass</string>
			<key>begin</key>
			<string>\s*((@)forward\b)\s*</string>
			<key>end</key>
			<string>\s*(?=;)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.control.operator</string>
					<key>match</key>
					<string>\b(as|hide|show)\b</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b([\w-]+)(\*)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.module.sass</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.wildcard.sass</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>entity.name.function.sass</string>
					<key>match</key>
					<string>\b[\w-]+\b</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable-usage</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-single</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-double</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
			</array>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.at-rule.forward.sass</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.keyword.sass</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.variable-usage.sass</string>
			<key>begin</key>
			<string>^\s*(\+)([a-zA-Z0-9_-]+)</string>
			<key>end</key>
			<string>(;)?$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.variable-usage.sass</string>
					<key>match</key>
					<string>(!|\$)([a-zA-Z0-9_-]+)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entity.css</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.sass</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-single</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-double</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.entity.sass</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other.sass</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.entity.sass</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.punctuation.sass</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.selector.css</string>
			<key>begin</key>
			<string>(?=[.*&amp;#\[a-zA-Z][:.*&amp;#a-zA-Z]*)</string>
			<key>end</key>
			<string>(;)?$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(&amp;)([a-zA-Z0-9_-]*)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.parent-reference.sass</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.parent-selector-suffix.sass</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.class.sass</string>
					<key>match</key>
					<string>(\.)[a-zA-Z0-9_-]+</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entity.css</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>include</key>
					<string>source.css#tag-names</string>
				</dict>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.id.css.sass</string>
					<key>match</key>
					<string>(#)[a-zA-Z][a-zA-Z0-9_-]*</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entity.sass</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>entity.name.tag.wildcard.sass</string>
					<key>match</key>
					<string>\*</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.css#pseudo-classes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.css#pseudo-elements</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.css#functional-pseudo-classes</string>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.attribute-selector.css.sass</string>
					<key>match</key>
					<string>(?i)(\[)\s*(-?[_a-z\\[[:^ascii:]]][-_a-z0-9\\[[:^ascii:]]]*)(?:\s*([~|^$*]?=)\s*(?:(-?[_a-z\\[[:^ascii:]]][-_a-z0-9\\[[:^ascii:]]]*)|((?&gt;([&apos;&quot;])(?:[^\\]|\\.)*?(\6)))))?\s*(])</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.attribute-selector.begin.bracket.square.sass</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.attribute.sass</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.sass</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.attribute-value.sass</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.attribute-value.sass</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.sass</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.sass</string>
						</dict>
						<key>8</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.attribute-selector.end.bracket.square.sass</string>
						</dict>
					</dict>
				</dict>
			</array>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.punctuation.sass</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.variable-declaration.sass.mixin</string>
			<key>begin</key>
			<string>^(=|@keyframes\s+)([a-zA-Z0-9_-]+)</string>
			<key>end</key>
			<string>(;)?$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#property-value</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.at-rule.keyframes.sass</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other.sass</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.punctuation.sass</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.at-rule.import.sass</string>
			<key>begin</key>
			<string>^\s*((@)import\b)</string>
			<key>end</key>
			<string>(;)?$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string-double</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(url)\s*(\()\s*</string>
					<key>end</key>
					<string>\s*(\))\s*</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>variable.parameter.url.sass</string>
							<key>match</key>
							<string>[^&apos;&quot;) \t]+</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#string-single</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#string-double</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.url.sass</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.function.sass</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.function.sass</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>variable.parameter.url.sass</string>
					<key>match</key>
					<string>([^&quot;&apos;\n;]+)</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.at-rule.import.sass</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.keyword.sass</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.punctuation.sass</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.at-rule.media.sass</string>
			<key>begin</key>
			<string>^\s*((@)media)\b</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.control.operator.css.sass</string>
					<key>match</key>
					<string>\b(only)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.property-list.media-query.sass</string>
					<key>begin</key>
					<string>\(</string>
					<key>end</key>
					<string>\)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>meta.property-name.media-query.sass</string>
							<key>begin</key>
							<string>(?&lt;![-a-z])(?=[-a-z])</string>
							<key>end</key>
							<string>$|(?![-a-z])</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.css#media-features</string>
								</dict>
								<dict>
									<key>include</key>
									<string>source.css#property-names</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>contentName</key>
							<string>meta.property-value.media-query.sass</string>
							<key>begin</key>
							<string>(:)\s*</string>
							<key>end</key>
							<string>\s*(?=\))</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#property-value</string>
								</dict>
							</array>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.separator.key-value.sass</string>
								</dict>
							</dict>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.media-query.begin.bracket.round.sass</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.media-query.end.bracket.round.sass</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable-usage</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#conditional-operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.css#media-types</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.at-rule.media.sass</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.keyword.sass</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s+(:)(?=[-a-z])</string>
			<key>end</key>
			<string>(;)?$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#property-name</string>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.property-value.sass</string>
					<key>begin</key>
					<string>\s+</string>
					<key>end</key>
					<string>(?=;?$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#property-value</string>
						</dict>
					</array>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.key-value.css</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.punctuation.sass</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s+([-A-Za-z]+)\s*(?=(\|\|)?=|:[ \t]+)</string>
			<key>end</key>
			<string>(;)?$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.property-value.sass</string>
					<key>begin</key>
					<string>(?:(:)\s+)|((\|\|)?=)</string>
					<key>end</key>
					<string>(?=;?$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#property-value</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.key-value.css</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.deprecated.sass</string>
						</dict>
					</dict>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#property-name</string>
						</dict>
					</array>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.key-value.css</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.deprecated.sass</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.punctuation.sass</string>
				</dict>
			</dict>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\w+\s*((//|/\*).*)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.sass</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>comment.block.documentation.sass</string>
					<key>begin</key>
					<string>^(\s*)(///)</string>
					<key>end</key>
					<string>^(?!\s\1)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.sassdoc</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.sass</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>comment.block.sass</string>
					<key>begin</key>
					<string>^(\s*)(/\*)</string>
					<key>end</key>
					<string>(\*/)|^(?!\s\1)</string>
					<key>beginCaptures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.sass</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.sass</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>comment.line.sass</string>
					<key>begin</key>
					<string>^(\s*)(//)</string>
					<key>end</key>
					<string>^(?!\s\1)</string>
					<key>beginCaptures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.sass</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>conditional-operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.operator.comparison.sass</string>
					<key>match</key>
					<string>==|!=|&lt;=|&gt;=|&lt;|&gt;</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.logical.sass</string>
					<key>match</key>
					<string>\b(not|or|and)\b</string>
				</dict>
			</array>
		</dict>
		<key>property-name</key>
		<dict>
			<key>name</key>
			<string>meta.property-name.sass</string>
			<key>begin</key>
			<string>(?=[-A-Za-z]+)</string>
			<key>end</key>
			<string>(?!\G)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.css#property-names</string>
				</dict>
			</array>
		</dict>
		<key>property-value</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.css#numeric-values</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.css</string>
					<key>match</key>
					<string>[-+*/](?!\s*[-+*/])</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable-usage</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.constant.property-value.css.sass</string>
					<key>match</key>
					<string>\b(true|false)\b</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.css#property-keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.css#color-keywords</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.other.color.rgb-value.css</string>
					<key>match</key>
					<string>(#)([0-9a-fA-F]{3}|[0-9a-fA-F]{6})\b</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.css</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-double</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-single</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>([\w-]+)(\.)([\w-]+)(\()</string>
					<key>end</key>
					<string>(\))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string-double</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#string-single</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#variable-usage</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.css#numeric-values</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.sass</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.access.module.sass</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.function.misc.sass</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.function.sass</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.function.sass</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>begin</key>
					<string>(rgb|url|attr|counter|counters|local|format)\s*(\()</string>
					<key>end</key>
					<string>(\))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string-single</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#string-double</string>
						</dict>
						<dict>
							<key>name</key>
							<string>constant.other.color.rgb-value.sass</string>
							<key>match</key>
							<string>(\b0*((1?[0-9]{1,2})|(2([0-4][0-9]|5[0-5])))\s*,\s*)(0*((1?[0-9]{1,2})|(2([0-4][0-9]|5[0-5])))\s*,\s*)(0*((1?[0-9]{1,2})|(2([0-4][0-9]|5[0-5])))\b)</string>
						</dict>
						<dict>
							<key>name</key>
							<string>constant.other.color.rgb-percentage.sass</string>
							<key>match</key>
							<string>\b([0-9]{1,2}|100)\s*%,\s*([0-9]{1,2}|100)\s*%,\s*([0-9]{1,2}|100)\s*%</string>
						</dict>
						<dict>
							<key>name</key>
							<string>variable.parameter.misc.sass</string>
							<key>match</key>
							<string>[^&apos;&quot;) \t]+</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.misc.sass</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.function.sass</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.function.sass</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.other.important.sass</string>
					<key>match</key>
					<string>!\s*important</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.control.sass</string>
					<key>match</key>
					<string>(from|to|through|in)</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#conditional-operators</string>
				</dict>
			</array>
		</dict>
		<key>string-double</key>
		<dict>
			<key>name</key>
			<string>string.quoted.double.sass</string>
			<key>begin</key>
			<string>&quot;</string>
			<key>end</key>
			<string>&quot;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.character.escape.sass</string>
					<key>match</key>
					<string>\\([[:xdigit:]]{1,6}|.)</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.sass</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.sass</string>
				</dict>
			</dict>
		</dict>
		<key>string-single</key>
		<dict>
			<key>name</key>
			<string>string.quoted.single.sass</string>
			<key>begin</key>
			<string>&apos;</string>
			<key>end</key>
			<string>&apos;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.character.escape.sass</string>
					<key>match</key>
					<string>\\([[:xdigit:]]{1,6}|.)</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.sass</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.sass</string>
				</dict>
			</dict>
		</dict>
		<key>variable-usage</key>
		<dict>
			<key>name</key>
			<string>meta.variable-usage.sass</string>
			<key>match</key>
			<string>(?:([\w-]+)(\.)(?=\$))?(!|\$)([a-zA-Z0-9_-]+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.sass</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.access.module.sass</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.entity.css</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.other.sass</string>
				</dict>
			</dict>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>sass</string>
	</array>
</dict>
</plist>
