<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>sed</string>
	<key>scopeName</key>
	<string>source.sed</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>name</key>
			<string>comment.line.number-sign.hashbang.sed</string>
			<key>begin</key>
			<string>\A#!</string>
			<key>end</key>
			<string>$</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.sed</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>include</key>
			<string>#main</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>addresses</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.address.numbered.range.sed</string>
					<key>match</key>
					<string>([0-9]+)\s*(,)\s*([0-9]+)(?:\s*(!))?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.integer.start-index.sed</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.address.range.comma.sed</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.integer.end-index.sed</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.logical.not.negation.sed</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.address.numbered.range.step.gnu.sed</string>
					<key>match</key>
					<string>([0-9]+)\s*(~)\s*([0-9]+)(?:\s*(!))?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.integer.start-index.sed</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.address.range.tilde.gnu.sed</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.integer.step-size.sed</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.logical.not.negation.sed</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.address.numbered.sed</string>
					<key>match</key>
					<string>([0-9]+)(?:\s*(!))?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.integer.line-index.sed</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.logical.not.negation.sed</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.address.last-line.sed</string>
					<key>match</key>
					<string>\$</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>constant.language.anchor.last-line.sed</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.address.pattern.sed</string>
					<key>contentName</key>
					<string>string.regexp.address.sed</string>
					<key>begin</key>
					<string>/</string>
					<key>end</key>
					<string>(/)([IM]*)(?:\s*(!))?|$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#regexp</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.delimiter.pattern.begin.sed</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.delimiter.pattern.end.sed</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.flags.sed</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#flags</string>
								</dict>
							</array>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.logical.not.negation.sed</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.address.pattern.custom-delimiter.sed</string>
					<key>contentName</key>
					<string>string.regexp.address.sed</string>
					<key>begin</key>
					<string>\\(.)</string>
					<key>end</key>
					<string>(\1)([IM]*)(?:\s*(!))?|$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#regexp</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.delimiter.address.begin.sed</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.delimiter.address.end.sed</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.modifier.flags.sed</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#flags</string>
								</dict>
							</array>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.logical.not.negation.sed</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>(,)(\s*(?:(\+)|(~)))?\s*([0-9]*)(?:\s*(!))?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.address.range.comma.sed</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.address.range.nth-line.gnu.sed</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.arithmetic.plus.gnu.sed</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.arithmetic.tilde.gnu.sed</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.integer.line-index.sed</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.logical.not.negation.sed</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>braces</key>
		<dict>
			<key>name</key>
			<string>meta.group.sed</string>
			<key>begin</key>
			<string>{</string>
			<key>end</key>
			<string>}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#main</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.begin.sed</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.end.sed</string>
				</dict>
			</dict>
		</dict>
		<key>commands</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.control.delete.command.sed</string>
					<key>match</key>
					<string>[Dd]</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.control.print.command.sed</string>
					<key>match</key>
					<string>[Pp]</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.control.replace-hold.command.sed</string>
					<key>match</key>
					<string>[Hh]</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.control.replace-pattern.command.sed</string>
					<key>match</key>
					<string>[Gg]</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.control.exchange.command.sed</string>
					<key>match</key>
					<string>x</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.control.print.filename.gnu.sed</string>
					<key>match</key>
					<string>F</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.control.skip.command.sed</string>
					<key>match</key>
					<string>n</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.control.print.newline.sed</string>
					<key>match</key>
					<string>N</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.control.print.line-number.sed</string>
					<key>match</key>
					<string>=</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.control.zap.gnu.sed</string>
					<key>match</key>
					<string>z</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(l)(?:\s*([0-9]+))?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.print.unambiguously.sed</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.line-length.gnu.sed</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>(?:(q)|(Q))(?:\s*([0-9]+))?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.quit.command.sed</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.quit.silently.command.gnu.sed</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.exit-code.gnu.sed</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>(?:(r)|(R))\s*(\S.*)$</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.read.file.command.sed</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.read.file.line.command.gnu.sed</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.filename.sed</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>(?:(w)|(W))\s*(\S.*)$</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.write.file.command.sed</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.write.file.command.gnu.sed</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.filename.sed</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.label.sed</string>
					<key>match</key>
					<string>(:)\s*([^\s;#}]+)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.function.label.sed</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.label.sed</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.branch.sed</string>
					<key>match</key>
					<string>(?:([bt])|(T))(?:\s*([^\s;#}]+))?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.branch.sed</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.branch.inverse.gnu.sed</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.label.sed</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.execution.sed</string>
					<key>contentName</key>
					<string>string.unquoted.herestring.sed</string>
					<key>begin</key>
					<string>(e)\s*</string>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escape</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.execute.sed</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>(v)(?:\s*([^\s;#}]+))?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.version.gnu.sed</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.other.version-string.sed</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>contentName</key>
					<string>comment.line.number-sign.sed</string>
					<key>begin</key>
					<string>\A(#)n</string>
					<key>end</key>
					<string>$</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.directive.no-autoprint.sed</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.directive.sed</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>comment.line.number-sign.sed</string>
					<key>begin</key>
					<string>#</string>
					<key>end</key>
					<string>$</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.sed</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>escape</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.character.escape.newline.sed</string>
					<key>begin</key>
					<string>\\$\s*</string>
					<key>end</key>
					<string>^</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.tab.sed</string>
					<key>match</key>
					<string>\\t</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.newline.sed</string>
					<key>match</key>
					<string>\\n</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.escape.sed</string>
					<key>match</key>
					<string>\\.</string>
				</dict>
			</array>
		</dict>
		<key>flags</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.operator.modifier.global.sed</string>
					<key>match</key>
					<string>g</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.modifier.print.sed</string>
					<key>match</key>
					<string>p</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.modifier.limit-match.sed</string>
					<key>match</key>
					<string>[0-9]+</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(w)\s*([^;#}]*)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.modifier.write.file.sed</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.filename.sed</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.modifier.exec-shell.gnu.sed</string>
					<key>match</key>
					<string>e</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.modifier.ignore-case.gnu.sed</string>
					<key>match</key>
					<string>I|i</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.modifier.multi-line.gnu.sed</string>
					<key>match</key>
					<string>M|m</string>
				</dict>
				<dict>
					<key>name</key>
					<string>invalid.illegal.unknown.flag.sed</string>
					<key>match</key>
					<string>[^;\s#}gp0-9eIiMm]+</string>
				</dict>
			</array>
		</dict>
		<key>insertion</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.insertion.sed</string>
					<key>contentName</key>
					<string>string.unquoted.herestring.sed</string>
					<key>begin</key>
					<string>[aic](\\)$\s*</string>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escape</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.insertion.command.sed</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.character.escape.newline.sed</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.insertion.gnu.sed</string>
					<key>contentName</key>
					<string>string.unquoted.herestring.sed</string>
					<key>begin</key>
					<string>[aic]</string>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escape</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.insertion.command.sed</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>main</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#substitution</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#transliteration</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#insertion</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#addresses</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#semicolon</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#braces</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#commands</string>
				</dict>
			</array>
		</dict>
		<key>reference</key>
		<dict>
			<key>name</key>
			<string>variable.language.reference.sed</string>
			<key>match</key>
			<string>\\[0-9]</string>
		</dict>
		<key>regexp</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.language.wildcard.dot.match.any.sed</string>
					<key>match</key>
					<string>\.</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.anchor.line-start.sed</string>
					<key>match</key>
					<string>\^</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.anchor.line-end.sed</string>
					<key>match</key>
					<string>\$</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.quantifier.min-0.sed</string>
					<key>match</key>
					<string>\*</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.quantifier.min-1.sed</string>
					<key>match</key>
					<string>\\?\+</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.quantifier.max-1.sed</string>
					<key>match</key>
					<string>\\?\?</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.alternation.disjunction.sed</string>
					<key>match</key>
					<string>\\?\|</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.group.begin.sed</string>
					<key>match</key>
					<string>\\?\(</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.group.end.sed</string>
					<key>match</key>
					<string>\\?\)</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#reference</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#regexp.miscEscapes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#regexp.quantiferRanges</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#regexp.bracketExpression</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#regexp.gnuCharacterEscapes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#regexp.gnuEscapes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#escape</string>
				</dict>
			</array>
		</dict>
		<key>regexp.bracketExpression</key>
		<dict>
			<key>name</key>
			<string>string.regexp.character-class.sed</string>
			<key>begin</key>
			<string>(\[)(\^)?\]?</string>
			<key>end</key>
			<string>\]|(?=$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>punctuation.separator.range.dash.sed</string>
					<key>match</key>
					<string>(?&lt;!\G)-(?!$|\])</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.named.character-class.sed</string>
					<key>match</key>
					<string>(\[:)(?:(alnum|alpha|blank|cntrl|digit|graph|lower|print|punct|space|upper|xdigit)|(.*?))(\:])</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.character-class.begin.sed</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant.posix-class.sed</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.unknown.character-class.sed</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.character-class.end.sed</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.collating-symbol.sed</string>
					<key>begin</key>
					<string>\[\.</string>
					<key>end</key>
					<string>\.\]|(?=$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escape</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.collating-symbol.begin.sed</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.collating-symbol.end.sed</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.equivalence-class.sed</string>
					<key>begin</key>
					<string>\[=</string>
					<key>end</key>
					<string>=\]</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escape</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.equivalence-class.begin.sed</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.equivalence-class.end.sed</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>include</key>
					<string>#escape</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.character-class.begin.sed</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.logical.not.sed</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.character-class.end.sed</string>
				</dict>
			</dict>
		</dict>
		<key>regexp.gnuCharacterEscapes</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.character.escape.alert.gnu.sed</string>
					<key>match</key>
					<string>\\a</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.escape.form-feed.gnu.sed</string>
					<key>match</key>
					<string>\\f</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.escape.carriage-return.gnu.sed</string>
					<key>match</key>
					<string>\\r</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.escape.tab.gnu.sed</string>
					<key>match</key>
					<string>\\t</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.escape.vertical-tab.gnu.sed</string>
					<key>match</key>
					<string>\\v</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.escape.control-x.gnu.sed</string>
					<key>match</key>
					<string>\\c.</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.escape.decimal.codepoint.gnu.sed</string>
					<key>match</key>
					<string>\\d[0-9]{3}</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.escape.octal.codepoint.gnu.sed</string>
					<key>match</key>
					<string>\\o[0-7]{3}</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.escape.hex.codepoint.gnu.sed</string>
					<key>match</key>
					<string>\\x[0-9A-Fa-f]{2}</string>
				</dict>
			</array>
		</dict>
		<key>regexp.gnuEscapes</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.operator.lowercase.conversion.gnu.sed</string>
					<key>match</key>
					<string>\\[Ll]</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.uppercase.conversion.gnu.sed</string>
					<key>match</key>
					<string>\\[Uu]</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.end.conversion.gnu.sed</string>
					<key>match</key>
					<string>\\E</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.word-character.gnu.sed</string>
					<key>match</key>
					<string>\\w</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.word-character.negated.gnu.sed</string>
					<key>match</key>
					<string>\\W</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.word-boundary.gnu.sed</string>
					<key>match</key>
					<string>\\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.word-boundary.negated.gnu.sed</string>
					<key>match</key>
					<string>\\B</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.whitespace-character.gnu.sed</string>
					<key>match</key>
					<string>\\s</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.whitespace-character.negated.gnu.sed</string>
					<key>match</key>
					<string>\\S</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.anchor.beginning-of-word.gnu.sed</string>
					<key>match</key>
					<string>\\&lt;</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.anchor.end-of-word.gnu.sed</string>
					<key>match</key>
					<string>\\&gt;</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.anchor.start-of-pattern.gnu.sed</string>
					<key>match</key>
					<string>\\`</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.anchor.end-of-pattern.gnu.sed</string>
					<key>match</key>
					<string>\\&apos;</string>
				</dict>
			</array>
		</dict>
		<key>regexp.miscEscapes</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.character.escape.dollar-sign.sed</string>
					<key>match</key>
					<string>\\\$</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.escape.asterisk.sed</string>
					<key>match</key>
					<string>\\\*</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.escape.dot.period.sed</string>
					<key>match</key>
					<string>\\\.</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.escape.square.bracket.sed</string>
					<key>match</key>
					<string>\\\[</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.escape.backslash.sed</string>
					<key>match</key>
					<string>\\{2}</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.escape.caret.sed</string>
					<key>match</key>
					<string>\\\^</string>
				</dict>
			</array>
		</dict>
		<key>regexp.quantiferRanges</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.escaped.quantifier.specific.range.sed</string>
					<key>match</key>
					<string>(\\{)([0-9]+)(?:(,)([0-9]+)?)?(\\})</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.quantifier.bracket.curly.begin.sed</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.integer.sed</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.range.comma.sed</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.integer.sed</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.quantifier.bracket.curly.end.sed</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.unescaped.quantifier.specific.range.sed</string>
					<key>match</key>
					<string>({)([0-9]+)(?:(,)([0-9]+)?)?(})</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.quantifier.bracket.curly.begin.sed</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.integer.sed</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.range.comma.sed</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.integer.sed</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.quantifier.bracket.curly.end.sed</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>replacement.innards</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>variable.language.input.sed</string>
					<key>match</key>
					<string>&amp;</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#reference</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#escape</string>
				</dict>
			</array>
		</dict>
		<key>semicolon</key>
		<dict>
			<key>name</key>
			<string>punctuation.terminator.statement.semicolon.sed</string>
			<key>match</key>
			<string>;</string>
		</dict>
		<key>substitution</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.substitution.pound-delimiter.sed</string>
					<key>begin</key>
					<string>(s)(#)</string>
					<key>end</key>
					<string>(#)([^;#}]*+)|(?=$|[;#}])</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>meta.match-pattern.sed</string>
							<key>contentName</key>
							<string>string.regexp.substitution.search.sed</string>
							<key>begin</key>
							<string>\G</string>
							<key>end</key>
							<string>#|(?=$)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#regexp</string>
								</dict>
							</array>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.delimiter.pattern.middle.sed</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>name</key>
							<string>meta.replacement.sed</string>
							<key>contentName</key>
							<string>string.quoted.double.sed</string>
							<key>begin</key>
							<string>(?&lt;=#)</string>
							<key>end</key>
							<string>(?!\G)(?=#)|(?=$)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#replacement.innards</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>include</key>
							<string>#escape</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.command.sed</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.delimiter.pattern.begin.sed</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.delimiter.pattern.end.sed</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.options.sed</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#flags</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.substitution.semicolon-delimiter.sed</string>
					<key>begin</key>
					<string>(s)(;)</string>
					<key>end</key>
					<string>(;)([^;#}]*+)|(?=$|[;#}])</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>meta.match-pattern.sed</string>
							<key>contentName</key>
							<string>string.regexp.substitution.search.sed</string>
							<key>begin</key>
							<string>\G</string>
							<key>end</key>
							<string>;|(?=$)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#regexp</string>
								</dict>
							</array>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.delimiter.pattern.middle.sed</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>name</key>
							<string>meta.replacement.sed</string>
							<key>contentName</key>
							<string>string.quoted.double.sed</string>
							<key>begin</key>
							<string>(?&lt;=;)</string>
							<key>end</key>
							<string>(?!\G)(?=;)|(?=$)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#replacement.innards</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>include</key>
							<string>#escape</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.command.sed</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.delimiter.pattern.begin.sed</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.delimiter.pattern.end.sed</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.options.sed</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#flags</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.substitution.brace-delimiter.sed</string>
					<key>begin</key>
					<string>(s)(})</string>
					<key>end</key>
					<string>(})([^;#}]*+)|(?=$|[;#}])</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>meta.match-pattern.sed</string>
							<key>contentName</key>
							<string>string.regexp.substitution.search.sed</string>
							<key>begin</key>
							<string>\G</string>
							<key>end</key>
							<string>}|(?=$)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#regexp</string>
								</dict>
							</array>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.delimiter.pattern.middle.sed</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>name</key>
							<string>meta.replacement.sed</string>
							<key>contentName</key>
							<string>string.quoted.double.sed</string>
							<key>begin</key>
							<string>(?&lt;=})</string>
							<key>end</key>
							<string>(?!\G)(?=})|(?=$)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#replacement.innards</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>include</key>
							<string>#escape</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.command.sed</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.delimiter.pattern.begin.sed</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.delimiter.pattern.end.sed</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.options.sed</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#flags</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.substitution.sed</string>
					<key>begin</key>
					<string>s</string>
					<key>end</key>
					<string>$|(?&lt;=^)|(?=[;#}])</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>meta.match-pattern.sed</string>
							<key>contentName</key>
							<string>string.regexp.substitution.search.sed</string>
							<key>begin</key>
							<string>\G(.)</string>
							<key>end</key>
							<string>-?(?=\1|$)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#regexp</string>
								</dict>
							</array>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.delimiter.pattern.begin.sed</string>
								</dict>
							</dict>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>string.quoted.double.sed</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>name</key>
							<string>meta.replacement.sed</string>
							<key>contentName</key>
							<string>string.quoted.double.sed</string>
							<key>begin</key>
							<string>([^;#}])</string>
							<key>end</key>
							<string>(\1)([^;#}]*+)|(?=$)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#replacement.innards</string>
								</dict>
							</array>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.delimiter.pattern.middle.sed</string>
								</dict>
							</dict>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.delimiter.pattern.end.sed</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>meta.options.sed</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#flags</string>
										</dict>
									</array>
								</dict>
							</dict>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.command.sed</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>transliteration</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>invalid.illegal.syntax.transliteration.sed</string>
					<key>match</key>
					<string>y {2}[^ ]*(?: |$)|y\t{2}[^\t]*(?:\t|$)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.transliteration.space-delimiter.sed</string>
					<key>begin</key>
					<string>(y)( )</string>
					<key>end</key>
					<string>( )([^#;}]*)|$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>meta.source-characters.sed</string>
							<key>contentName</key>
							<string>string.quoted.double.sed</string>
							<key>begin</key>
							<string>\G</string>
							<key>end</key>
							<string>(-)?( )|(?=$)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#transliteration.ranges</string>
								</dict>
							</array>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>string.quoted.double.sed</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.delimiter.whitespace.middle.sed</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>name</key>
							<string>meta.replacement-characters.sed</string>
							<key>contentName</key>
							<string>string.quoted.double.sed</string>
							<key>begin</key>
							<string>(?&lt;= )</string>
							<key>end</key>
							<string>(?!\G)-?(?= )|(?=$)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#transliteration.ranges</string>
								</dict>
							</array>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>string.quoted.double.sed</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>include</key>
							<string>#escape</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.command.sed</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.delimiter.whitespace.begin.sed</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.delimiter.whitespace.end.sed</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.extra-characters.sed</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.transliteration.tab-delimiter.sed</string>
					<key>begin</key>
					<string>(y)(\t)</string>
					<key>end</key>
					<string>(\t)([^#;}]*)|$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>meta.source-characters.sed</string>
							<key>contentName</key>
							<string>string.quoted.double.sed</string>
							<key>begin</key>
							<string>\G</string>
							<key>end</key>
							<string>(-)?(\t)|(?=$)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#transliteration.ranges</string>
								</dict>
							</array>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>string.quoted.double.sed</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.delimiter.whitespace.middle.sed</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>name</key>
							<string>meta.replacement-characters.sed</string>
							<key>contentName</key>
							<string>string.quoted.double.sed</string>
							<key>begin</key>
							<string>(?&lt;=\t)</string>
							<key>end</key>
							<string>(?!\G)-?(?=\t)|(?=$)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#transliteration.ranges</string>
								</dict>
							</array>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>string.quoted.double.sed</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>include</key>
							<string>#escape</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.command.sed</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.delimiter.whitespace.begin.sed</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.delimiter.whitespace.end.sed</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.extra-characters.sed</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.transliteration.semicolon-delimiter.sed</string>
					<key>begin</key>
					<string>(y)(;)</string>
					<key>end</key>
					<string>(;)([^#;}]*)|$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>meta.source-characters.sed</string>
							<key>contentName</key>
							<string>string.quoted.double.sed</string>
							<key>begin</key>
							<string>\G</string>
							<key>end</key>
							<string>(-)?(;)|(?=$)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#transliteration.ranges</string>
								</dict>
							</array>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>string.quoted.double.sed</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.delimiter.pattern.middle.sed</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>name</key>
							<string>meta.replacement-characters.sed</string>
							<key>contentName</key>
							<string>string.quoted.double.sed</string>
							<key>begin</key>
							<string>(?&lt;=;)</string>
							<key>end</key>
							<string>(?!\G)-?(?=;)|(?=$)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#transliteration.ranges</string>
								</dict>
							</array>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>string.quoted.double.sed</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>include</key>
							<string>#escape</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.command.sed</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.delimiter.pattern.begin.sed</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.delimiter.pattern.end.sed</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.extra-characters.sed</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.transliteration.brace-delimiter.sed</string>
					<key>begin</key>
					<string>(y)(})</string>
					<key>end</key>
					<string>(})([^#;}]*)|$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>meta.source-characters.sed</string>
							<key>contentName</key>
							<string>string.quoted.double.sed</string>
							<key>begin</key>
							<string>\G</string>
							<key>end</key>
							<string>(-)?(})|(?=$)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#transliteration.ranges</string>
								</dict>
							</array>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>string.quoted.double.sed</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.delimiter.pattern.middle.sed</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>name</key>
							<string>meta.replacement-characters.sed</string>
							<key>contentName</key>
							<string>string.quoted.double.sed</string>
							<key>begin</key>
							<string>(?&lt;=})</string>
							<key>end</key>
							<string>(?!\G)-?(?=})|(?=$)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#transliteration.ranges</string>
								</dict>
							</array>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>string.quoted.double.sed</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>include</key>
							<string>#escape</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.command.sed</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.delimiter.pattern.begin.sed</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.delimiter.pattern.end.sed</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.extra-characters.sed</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.transliteration.pound-delimiter.sed</string>
					<key>begin</key>
					<string>(y)(#)</string>
					<key>end</key>
					<string>(#)([^#;}]*)|$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>meta.source-characters.sed</string>
							<key>contentName</key>
							<string>string.quoted.double.sed</string>
							<key>begin</key>
							<string>\G</string>
							<key>end</key>
							<string>(-)?(#)|(?=$)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#transliteration.ranges</string>
								</dict>
							</array>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>string.quoted.double.sed</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.delimiter.pattern.middle.sed</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>name</key>
							<string>meta.replacement-characters.sed</string>
							<key>contentName</key>
							<string>string.quoted.double.sed</string>
							<key>begin</key>
							<string>(?&lt;=#)</string>
							<key>end</key>
							<string>(?!\G)-?(?=#)|(?=$)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#transliteration.ranges</string>
								</dict>
							</array>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>string.quoted.double.sed</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>include</key>
							<string>#escape</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.command.sed</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.delimiter.pattern.begin.sed</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.delimiter.pattern.end.sed</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.extra-characters.sed</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.transliteration.dash-delimiter.sed</string>
					<key>begin</key>
					<string>(y)(-)</string>
					<key>end</key>
					<string>(-)([^#;}]*)|$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>meta.source-characters.sed</string>
							<key>contentName</key>
							<string>string.quoted.double.sed</string>
							<key>begin</key>
							<string>\G</string>
							<key>end</key>
							<string>-|(?=$)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#escape</string>
								</dict>
							</array>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.delimiter.pattern.middle.sed</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>name</key>
							<string>meta.replacement-characters.sed</string>
							<key>contentName</key>
							<string>string.quoted.double.sed</string>
							<key>begin</key>
							<string>(?&lt;=-)</string>
							<key>end</key>
							<string>(?=$|-)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#escape</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>include</key>
							<string>#escape</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.command.sed</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.delimiter.pattern.begin.sed</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.delimiter.pattern.end.sed</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.extra-characters.sed</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.transliteration.sed</string>
					<key>begin</key>
					<string>y</string>
					<key>end</key>
					<string>$|(?=[\s#;}])|(?&lt;=^)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>meta.source-characters.sed</string>
							<key>contentName</key>
							<string>string.quoted.double.sed</string>
							<key>begin</key>
							<string>\G(.)</string>
							<key>end</key>
							<string>-?(?=\1|$)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#transliteration.ranges</string>
								</dict>
							</array>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.delimiter.pattern.begin.sed</string>
								</dict>
							</dict>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>string.quoted.double.sed</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>name</key>
							<string>meta.replacement-characters.sed</string>
							<key>contentName</key>
							<string>string.quoted.double.sed</string>
							<key>begin</key>
							<string>(.)</string>
							<key>end</key>
							<string>(-)?(\1)([^#;}]*+)|(?=$)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#transliteration.ranges</string>
								</dict>
							</array>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.delimiter.pattern.middle.sed</string>
								</dict>
							</dict>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>string.quoted.double.sed</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.delimiter.pattern.end.sed</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>invalid.illegal.extra-characters.sed</string>
								</dict>
							</dict>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.command.sed</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>transliteration.ranges</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\G-</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.range.dash.sed</string>
					<key>match</key>
					<string>-</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#escape</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>sed</string>
	</array>
</dict>
</plist>
