<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Shell Session</string>
	<key>scopeName</key>
	<string>text.shell-session</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>(?x) ^ (?: ( (?:\(\S+\)\s*)? (?: sh\S*?                       | \w+\S+[@:]\S+(?:\s+\S+)? | \[\S+?[@:][^\n]+?\].*? ) ) \s* )? ( [&gt;$#%❯➜] | \p{Greek} ) \s+ (.*) $</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.prompt-prefix.shell-session</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.prompt.shell-session</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>source.shell</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.shell</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.output.shell-session</string>
			<key>match</key>
			<string>^.+$</string>
		</dict>
	</array>
	<key>fileTypes</key>
	<array>
		<string>sh-session</string>
	</array>
</dict>
</plist>
