<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Shen</string>
	<key>scopeName</key>
	<string>source.shen</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#expressions</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>atoms</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>string.quoted.double</string>
					<key>begin</key>
					<string>(\&quot;)</string>
					<key>end</key>
					<string>(\&quot;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>constant.character.escape</string>
							<key>match</key>
							<string>(~A|~R|~S|~%|c#\d+;)</string>
						</dict>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
							<key>match</key>
							<string>(c#[^;]*;)</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric</string>
					<key>match</key>
					<string>(?&lt;=^|[\s()\[\]])[+-]*\d+\.?\d*(?=$|[\s;()\[\]])</string>
				</dict>
				<dict>
					<key>name</key>
					<string>invalid.illegal</string>
					<key>match</key>
					<string>(?&lt;=^|[\s()\[\]])[+-]*\d+\.?\d*[^\s;()\[\]]+(?=$|[\s;()\[\]])</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.control</string>
					<key>match</key>
					<string>(?&lt;=\()(and|or|if|do|lambda|freeze|let|cond|cases|trap-error|where|package|defun|/.|define|defmacro|defcc|defprolog|datatype)(?=$|[\s;()\[\]{}])</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.control</string>
					<key>match</key>
					<string>(?&lt;=^|[\s()\[\]{}])(-&gt;|&lt;-|--&gt;|&lt;--|==&gt;|&lt;==|:=|__+)(?=$|[\s;()\[\]{}])</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
					<key>match</key>
					<string>(?&lt;=^|[\s()\[\]{}])(=|==|&lt;|&gt;|&lt;=|&gt;=|\+|-|\*|/)(?=$|[\s;()\[\]{}])</string>
				</dict>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
					<key>match</key>
					<string>(?&lt;=\(define\s)([^\s()\[\]{}]*)(?=$|[\s;()\[\]{}])</string>
				</dict>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
					<key>match</key>
					<string>(?&lt;=\(defmacro\s)([^\s()\[\]{}]*)(?=$|[\s;()\[\]{}])</string>
				</dict>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
					<key>match</key>
					<string>(?&lt;=\(defprolog\s)([^\s()\[\]{}]*)(?=$|[\s;()\[\]{}])</string>
				</dict>
				<dict>
					<key>name</key>
					<string>entity.name.section</string>
					<key>match</key>
					<string>(?&lt;=\(package\s)([^\s()\[\]{}]*)(?=$|[\s;()\[\]{}])</string>
				</dict>
				<dict>
					<key>name</key>
					<string>entity.name.type</string>
					<key>match</key>
					<string>(?&lt;=\(datatype\s)([^\s()\[\]{}]*)(?=$|[\s;()\[\]{}])</string>
				</dict>
				<dict>
					<key>name</key>
					<string>variable.language</string>
					<key>match</key>
					<string>(?&lt;=^|[\s()\[\]{}])([A-Z][^\s()\[\];{}]*)(?=$|[\s;()\[\]{}])</string>
				</dict>
				<dict>
					<key>name</key>
					<string>entity.name.tag</string>
					<key>match</key>
					<string>(?&lt;=^|[\s()\[\]])(&lt;[^\s()\[\]]*&gt;)(?=$|[\s;()\[\]])</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language</string>
					<key>match</key>
					<string>(?&lt;=^|[\s)\[\]{}])([^A-Z\s()\[\]:;\|{}][^\s()\[\];{}]*)(?=$|[\s;()\[\]{}])</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language</string>
					<key>match</key>
					<string>(\(\)|\[\])</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>comment.line</string>
					<key>match</key>
					<string>(\\\\.*$)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>comment.block</string>
					<key>begin</key>
					<string>(\\\*)</string>
					<key>end</key>
					<string>(\*\\)</string>
				</dict>
			</array>
		</dict>
		<key>expressions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#atoms</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#parens</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#squares</string>
				</dict>
			</array>
		</dict>
		<key>parens</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.group</string>
					<key>begin</key>
					<string>(\()</string>
					<key>end</key>
					<string>(\))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#expressions</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>squares</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.group</string>
					<key>begin</key>
					<string>(\[)</string>
					<key>end</key>
					<string>(\])</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#expressions</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>shen</string>
	</array>
</dict>
</plist>
