<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Ruby Slim</string>
	<key>scopeName</key>
	<string>text.slim</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>name</key>
			<string>text.ruby.filter.slim</string>
			<key>begin</key>
			<string>^(\s*)(ruby):$</string>
			<key>end</key>
			<string>^(?!(\1\s)|\s*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.ruby</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language.name.ruby.filter.slim</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>source.js.filter.slim</string>
			<key>begin</key>
			<string>^(\s*)(javascript):$</string>
			<key>end</key>
			<string>^(?!(\1\s)|\s*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language.name.javascript.filter.slim</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>source.yaml.meta.slim</string>
			<key>begin</key>
			<string>^(---)\s*\n</string>
			<key>end</key>
			<string>^(---)\s*\n</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.yaml</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.frontmatter.slim</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.frontmatter.slim</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>text.coffeescript.filter.slim</string>
			<key>begin</key>
			<string>^(\s*)(coffee):$</string>
			<key>end</key>
			<string>^(?!(\1\s)|\s*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.coffee</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language.name.coffeescript.filter.slim</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>text.markdown.filter.slim</string>
			<key>begin</key>
			<string>^(\s*)(markdown):$</string>
			<key>end</key>
			<string>^(?!(\1\s)|\s*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.gfm</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language.name.markdown.filter.slim</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>text.css.filter.slim</string>
			<key>begin</key>
			<string>^(\s*)(css):$</string>
			<key>end</key>
			<string>^(?!(\1\s)|\s*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.css</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language.name.css.filter.slim</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>text.sass.filter.slim</string>
			<key>begin</key>
			<string>^(\s*)(sass):$</string>
			<key>end</key>
			<string>^(?!(\1\s)|\s*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.sass</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language.name.sass.filter.slim</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>text.scss.filter.slim</string>
			<key>begin</key>
			<string>^(\s*)(scss):$</string>
			<key>end</key>
			<string>^(?!(\1\s)|\s*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.css.scss</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language.name.scss.filter.slim</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>text.less.filter.slim</string>
			<key>begin</key>
			<string>^(\s*)(less):$</string>
			<key>end</key>
			<string>^(?!(\1\s)|\s*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.css.less</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language.name.less.filter.slim</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>text.erb.filter.slim</string>
			<key>begin</key>
			<string>^(\s*)(erb):$</string>
			<key>end</key>
			<string>^(?!(\1\s)|\s*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.erb</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language.name.erb.filter.slim</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.prolog.slim</string>
			<key>match</key>
			<string>^(! )($|\s.*)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.prolog.slim</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>comment.block.slim</string>
			<key>begin</key>
			<string>^(\s*)(/)\s*.*$</string>
			<key>end</key>
			<string>^(?!(\1\s)|\s*$)</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment.line.slash.slim</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(?=-)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#rubyline</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?==+|~)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#rubyline</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#tag-attribute</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#embedded-ruby</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(\s*)(\||&apos;)\s*</string>
			<key>end</key>
			<string>^(?!(\1\s)|\s*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded-ruby</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.tag</string>
			<key>begin</key>
			<string>^\s*(\.|#|[-a-zA-Z0-9]+)([\w-]+)?</string>
			<key>end</key>
			<string>$|(?!\.|#|:|-|~|/|\}|\]|\*|\s?[\*\{])</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>entity.name.tag.slim</string>
					<key>begin</key>
					<string>(:[\w\d]+)+</string>
					<key>end</key>
					<string>$|\s</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(:\s)(\.|#|[a-zA-Z0-9]+)([\w-]+)?</string>
					<key>end</key>
					<string>$|(?!\.|#|=|-|~|/|\}|\]|\*|\s?[\*\{])</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#root-class-id-tag</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#tag-attribute</string>
						</dict>
					</array>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.slim</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.slim</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.event.slim</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>source.ruby.embedded.slim</string>
					<key>begin</key>
					<string>(\*\{)(?=.*\}|.*\|\s*$)</string>
					<key>end</key>
					<string>(\})|$|^(?!.*\|\s*$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#embedded-ruby</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.ruby</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.ruby</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>include</key>
					<string>#root-class-id-tag</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#rubyline</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.terminator.tag.slim</string>
					<key>match</key>
					<string>/</string>
				</dict>
			</array>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.slim</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.event.slim</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(\\.)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.escape.slim</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(?=\||&apos;)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#embedded-ruby</string>
				</dict>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?=&lt;[\w\d\:]+)</string>
			<key>end</key>
			<string>$|\/\&gt;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>continuation</key>
		<dict>
			<key>match</key>
			<string>([\\,])\s*\n</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.continuation.slim</string>
				</dict>
			</dict>
		</dict>
		<key>delimited-ruby-a</key>
		<dict>
			<key>name</key>
			<string>source.ruby.embedded.slim</string>
			<key>begin</key>
			<string>=\(</string>
			<key>end</key>
			<string>\)(?=( \w|$))</string>
			<key>patterns</key>
			<array>
				<dict>

				</dict>
			</array>
		</dict>
		<key>delimited-ruby-b</key>
		<dict>
			<key>name</key>
			<string>source.ruby.embedded.slim</string>
			<key>begin</key>
			<string>=\[</string>
			<key>end</key>
			<string>\](?=( \w|$))</string>
			<key>patterns</key>
			<array>
				<dict>

				</dict>
			</array>
		</dict>
		<key>delimited-ruby-c</key>
		<dict>
			<key>name</key>
			<string>source.ruby.embedded.slim</string>
			<key>begin</key>
			<string>=\{</string>
			<key>end</key>
			<string>\}(?=( \w|$))</string>
			<key>patterns</key>
			<array>
				<dict>

				</dict>
			</array>
		</dict>
		<key>embedded-ruby</key>
		<dict>
			<key>name</key>
			<string>source.ruby.embedded.html</string>
			<key>begin</key>
			<string>(?&lt;!\\)#\{{1,2}</string>
			<key>end</key>
			<string>\}{1,2}</string>
			<key>patterns</key>
			<array>
				<dict>

				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.ruby</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.ruby</string>
				</dict>
			</dict>
		</dict>
		<key>entities</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.character.entity.html</string>
					<key>match</key>
					<string>(&amp;)([a-zA-Z0-9]+|#[0-9]+|#x[0-9a-fA-F]+)(;)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entity.html</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entity.html</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>invalid.illegal.bad-ampersand.html</string>
					<key>match</key>
					<string>&amp;</string>
				</dict>
			</array>
		</dict>
		<key>interpolated-ruby</key>
		<dict>
			<key>name</key>
			<string>source.ruby.embedded.html</string>
			<key>begin</key>
			<string>=(?=\b)</string>
			<key>end</key>
			<string>\s|\w$</string>
		</dict>
		<key>root-class-id-tag</key>
		<dict>
			<key>match</key>
			<string>(\.|#)([\w\d\-]+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.key-value.html</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.html</string>
				</dict>
			</dict>
		</dict>
		<key>rubyline</key>
		<dict>
			<key>name</key>
			<string>meta.line.ruby.slim</string>
			<key>contentName</key>
			<string>source.ruby.embedded.slim</string>
			<key>begin</key>
			<string>(==|=)(&lt;&gt;|&gt;&lt;|&lt;&apos;|&apos;&lt;|&lt;|&gt;)?|-</string>
			<key>end</key>
			<string>(do\s*\n$)|(?&lt;!\\|,|,\n|\\\n)$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>comment.line.number-sign.ruby</string>
					<key>match</key>
					<string>#.*$</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#continuation</string>
				</dict>
				<dict>

				</dict>
			</array>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.start-block.ruby</string>
				</dict>
			</dict>
		</dict>
		<key>string-double-quoted</key>
		<dict>
			<key>name</key>
			<string>string.quoted.double.html</string>
			<key>contentName</key>
			<string>meta.toc-list.id.html</string>
			<key>begin</key>
			<string>(&quot;)(?=.*&quot;)</string>
			<key>end</key>
			<string>&quot;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#embedded-ruby</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#entities</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.html</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.html</string>
				</dict>
			</dict>
		</dict>
		<key>string-single-quoted</key>
		<dict>
			<key>name</key>
			<string>string.quoted.single.html</string>
			<key>contentName</key>
			<string>meta.toc-list.id.html</string>
			<key>begin</key>
			<string>(&apos;)(?=.*&apos;)</string>
			<key>end</key>
			<string>&apos;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#embedded-ruby</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#entities</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.html</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.html</string>
				</dict>
			</dict>
		</dict>
		<key>tag-attribute</key>
		<dict>
			<key>name</key>
			<string>meta.attribute-with-value.slim</string>
			<key>begin</key>
			<string>([\w.#_-]+)(=)(?!\s)(true|false|nil)?(\s*\(|\{)?</string>
			<key>end</key>
			<string>\}|\)|$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-stuff</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-double-quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-single-quoted</string>
				</dict>
			</array>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.event.slim</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.key-value.html</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.language.slim</string>
				</dict>
			</dict>
		</dict>
		<key>tag-stuff</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-attribute</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#interpolated-ruby</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#delimited-ruby-a</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#delimited-ruby-b</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#delimited-ruby-c</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#rubyline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded-ruby</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>slim</string>
	</array>
</dict>
</plist>
