<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>SmPL</string>
	<key>scopeName</key>
	<string>source.smpl</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#main</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>comment.line.triple-slash.smpl</string>
					<key>begin</key>
					<string>///</string>
					<key>end</key>
					<string>$</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.smpl</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>comment.line.double-slash.smpl</string>
					<key>begin</key>
					<string>//</string>
					<key>end</key>
					<string>$</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.smpl</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>control</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>storage.modifier.required.dots.smpl</string>
					<key>match</key>
					<string>&lt;\+(?=\.{3})|(?&lt;=\.{3})\+&gt;</string>
				</dict>
				<dict>
					<key>name</key>
					<string>storage.modifier.optional.dots.smpl</string>
					<key>match</key>
					<string>&lt;(?=\.{3})|(?&lt;=\.{3})&gt;</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.control.flow.dots.smpl</string>
					<key>match</key>
					<string>\.{3}</string>
				</dict>
			</array>
		</dict>
		<key>include</key>
		<dict>
			<key>name</key>
			<string>meta.preprocessor.$1.smpl</string>
			<key>match</key>
			<string>^\s*(include|using)\s+(?:(&quot;[^&quot;]*&quot;)|(&lt;.*&gt;))</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.directive.$1.smpl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>etc#str</string>
						</dict>
					</array>
				</dict>
				<key>3</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#isoPath</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>isoPath</key>
		<dict>
			<key>name</key>
			<string>string.quoted.other.lt-gt.include.smpl</string>
			<key>begin</key>
			<string>&lt;</string>
			<key>end</key>
			<string>&gt;</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.smpl</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.smpl</string>
				</dict>
			</dict>
		</dict>
		<key>lineAdded</key>
		<dict>
			<key>name</key>
			<string>markup.inserted.diff.smpl</string>
			<key>match</key>
			<string>^(\+).*</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.inserted.diff.smpl</string>
				</dict>
			</dict>
		</dict>
		<key>lineDeleted</key>
		<dict>
			<key>name</key>
			<string>markup.deleted.diff.smpl</string>
			<key>match</key>
			<string>^(-).*</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.deleted.diff.smpl</string>
				</dict>
			</dict>
		</dict>
		<key>lineMatched</key>
		<dict>
			<key>match</key>
			<string>^(\*)\s*(\S.*)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.semantic-match.diff.smpl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.changed.diff.smpl</string>
				</dict>
			</dict>
		</dict>
		<key>main</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#include</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#virtual</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#control</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#scripts</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#metavariables</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variables</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lineAdded</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lineDeleted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lineMatched</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#when</string>
				</dict>
			</array>
		</dict>
		<key>metavariables</key>
		<dict>
			<key>name</key>
			<string>meta.diff.header.metavariables.smpl</string>
			<key>begin</key>
			<string>^(@).*(@)\s*$</string>
			<key>end</key>
			<string>^(@@)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.diff.range.smpl</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.range.diff.begin.smpl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.range.diff.end.smpl</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.diff.range.smpl</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.range.diff.smpl</string>
				</dict>
			</dict>
		</dict>
		<key>scripts</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(^(@).*?(?&lt;=\s|@)(script|initialize|finalize):python(?=\s|@).*?(@)\s*$)</string>
					<key>end</key>
					<string>^(?=@(?!@\s*$))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>meta.diff.header.metavariables.smpl</string>
							<key>begin</key>
							<string>^</string>
							<key>end</key>
							<string>^(@@)</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>meta.diff.range.smpl</string>
								</dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.range.diff.smpl</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>contentName</key>
							<string>source.embedded.python</string>
							<key>begin</key>
							<string>(?&lt;=@@)\s*$\n?</string>
							<key>end</key>
							<string>^(?=@)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#comment</string>
								</dict>
								<dict>
									<key>include</key>
									<string>source.python</string>
								</dict>
							</array>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.diff.header.metavariables.smpl</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.diff.range.smpl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.range.diff.begin.smpl</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.range.diff.end.smpl</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>begin</key>
					<string>(^(@).*?(?&lt;=\s|@)(script|initialize|finalize):ocaml(?=\s|@).*?(@)\s*$)</string>
					<key>end</key>
					<string>^(?=@(?!@\s*$))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>meta.diff.header.metavariables.smpl</string>
							<key>begin</key>
							<string>^</string>
							<key>end</key>
							<string>^(@@)</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>meta.diff.range.smpl</string>
								</dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.range.diff.smpl</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>contentName</key>
							<string>source.embedded.ocaml</string>
							<key>begin</key>
							<string>(?&lt;=@@)\s*$\n?</string>
							<key>end</key>
							<string>^(?=@)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#comment</string>
								</dict>
								<dict>
									<key>include</key>
									<string>source.ocaml</string>
								</dict>
							</array>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.diff.header.metavariables.smpl</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.diff.range.smpl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.range.diff.begin.smpl</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.range.diff.end.smpl</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>variables</key>
		<dict>
			<key>name</key>
			<string>variable.at-prefix.smpl</string>
			<key>match</key>
			<string>(?&lt;!^)(@)[\w]+</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.variable.smpl</string>
				</dict>
			</dict>
		</dict>
		<key>virtual</key>
		<dict>
			<key>match</key>
			<string>^\s*(virtual)\s+(.*)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.virtual.smpl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>entity.name.rule.smpl</string>
							<key>match</key>
							<string>[^\s,]+</string>
						</dict>
						<dict>
							<key>include</key>
							<string>etc#comma</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>when</key>
		<dict>
			<key>match</key>
			<string>(?&lt;=\s|\.{3})(when)\s*(any(?:\s|$)|!=)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.flow.when.smpl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.comparison.smpl</string>
				</dict>
			</dict>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>cocci</string>
	</array>
</dict>
</plist>
