<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Spline Font Database</string>
	<key>scopeName</key>
	<string>text.sfd</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#main</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>address</key>
		<dict>
			<key>name</key>
			<string>constant.numeric.hexadecimal.sfd</string>
			<key>match</key>
			<string>\d+[xX][A-Fa-f0-9]+</string>
		</dict>
		<key>colour</key>
		<dict>
			<key>name</key>
			<string>constant.other.hex.colour.sfd</string>
			<key>match</key>
			<string>(#)[A-Fa-f0-9]{3,}|(?&lt;=\s)[A-Fa-f0-9]{6,8}</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.colour.sfd</string>
				</dict>
			</dict>
		</dict>
		<key>comment</key>
		<dict>
			<key>name</key>
			<string>meta.user-comments.sfd</string>
			<key>contentName</key>
			<string>comment.line.field.sfd</string>
			<key>begin</key>
			<string>^(U?Comments?)(:)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#source.fontforge#stringEscapes</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.property.sfd</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.dictionary.key-value.sfd</string>
				</dict>
			</dict>
		</dict>
		<key>control</key>
		<dict>
			<key>name</key>
			<string>keyword.control.${1:/downcase}.sfd</string>
			<key>match</key>
			<string>\b(Fore|Back|SplineSet|^End\w+)\b</string>
		</dict>
		<key>copyright</key>
		<dict>
			<key>name</key>
			<string>meta.copyright-string.sfd</string>
			<key>contentName</key>
			<string>string.unquoted.copyright.info.sfd</string>
			<key>begin</key>
			<string>^(Copyright)(:)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.fontforge#stringEscapes</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.property.sfd</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.dictionary.key-value.sfd</string>
				</dict>
			</dict>
		</dict>
		<key>encoding</key>
		<dict>
			<key>name</key>
			<string>constant.language.encoding.sfd</string>
			<key>match</key>
			<string>(?i)\b(ISO[-\w]+)(?&lt;=\d)(?=\s|$)</string>
		</dict>
		<key>gaspTable</key>
		<dict>
			<key>name</key>
			<string>meta.gasp-table.sfd</string>
			<key>begin</key>
			<string>^(GaspTable)(:|(?=\s))</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#main</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.property.sfd</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.dictionary.key-value.sfd</string>
				</dict>
			</dict>
		</dict>
		<key>header</key>
		<dict>
			<key>name</key>
			<string>meta.header.sfd</string>
			<key>match</key>
			<string>^(SplineFontDB)(:)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.start.file.afm</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.dictionary.key-value.sfd</string>
				</dict>
			</dict>
		</dict>
		<key>image</key>
		<dict>
			<key>name</key>
			<string>meta.image.sfd</string>
			<key>contentName</key>
			<string>string.unquoted.raw.data.sfd</string>
			<key>begin</key>
			<string>^(Image)(?=:)(.+)$</string>
			<key>end</key>
			<string>^(EndImage)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.begin.image.sfd</string>
				</dict>
				<key>2</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#main</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.end.image.sfd</string>
				</dict>
			</dict>
		</dict>
		<key>main</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#punctuation</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#private</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#header</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#names</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#image</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#pickleData</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#sections</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#copyright</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#gaspTable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#property</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#control</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#address</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#encoding</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.fontforge#shared</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#colour</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#unquoted</string>
				</dict>
			</array>
		</dict>
		<key>names</key>
		<dict>
			<key>name</key>
			<string>meta.dictionary.key-value.sfd</string>
			<key>match</key>
			<string>^((\w+)Name)(:)\s*(\S+.*?)\s$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.property.sfd</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.dictionary.key-value.sfd</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.${2:/downcase},sfd</string>
				</dict>
			</dict>
		</dict>
		<key>pickleData</key>
		<dict>
			<key>name</key>
			<string>meta.pickle-data.sfd</string>
			<key>begin</key>
			<string>^(PickledData)(:)\s*(&quot;)</string>
			<key>end</key>
			<string>&quot;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.character.escape.sfd</string>
					<key>match</key>
					<string>\\.</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.property.sfd</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.dictionary.key-value.sfd</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.sfd</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.sfd</string>
				</dict>
			</dict>
		</dict>
		<key>private</key>
		<dict>
			<key>name</key>
			<string>meta.section.private.sfd</string>
			<key>begin</key>
			<string>^BeginPrivate(?=:)</string>
			<key>end</key>
			<string>^EndPrivate\b</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>entity.name.private.property.sfd</string>
					<key>match</key>
					<string>^\S+</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#main</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.begin.private.sfd</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.end.private.sfd</string>
				</dict>
			</dict>
		</dict>
		<key>property</key>
		<dict>
			<key>name</key>
			<string>meta.dictionary.key-value.sfd</string>
			<key>match</key>
			<string>^([^:]+)(:)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.property.sfd</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.dictionary.key-value.sfd</string>
				</dict>
			</dict>
		</dict>
		<key>punctuation</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>punctuation.definition.brackets.angle.sfd</string>
					<key>match</key>
					<string>&lt;|&gt;</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.definition.brackets.curly.sfd</string>
					<key>match</key>
					<string>[{}]</string>
				</dict>
			</array>
		</dict>
		<key>sections</key>
		<dict>
			<key>name</key>
			<string>meta.section.${2:/downcase}.sfd</string>
			<key>begin</key>
			<string>^(Start|Begin)([A-Z]\w+)(?=:)</string>
			<key>end</key>
			<string>^(End\2)\b</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#main</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.begin.${2:/downcase}.sfd</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.end.${2:/downcase}.sfd</string>
				</dict>
			</dict>
		</dict>
		<key>unquoted</key>
		<dict>
			<key>name</key>
			<string>string.unquoted.property.sfd</string>
			<key>match</key>
			<string>\S+</string>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>sfd</string>
	</array>
</dict>
</plist>
