<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>STL</string>
	<key>scopeName</key>
	<string>source.stl</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#main</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>facet</key>
		<dict>
			<key>name</key>
			<string>meta.facet.stl</string>
			<key>begin</key>
			<string>(?:^|\G|(?&lt;=\s))[ \t]*(facet)(?:$|[ \t]+)</string>
			<key>end</key>
			<string>(?:^|\G|(?&lt;=\s))[ \t]*(endfacet)(?=$|\s)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#normal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#loop</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#vertex</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.begin.facet.stl</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.end.facet.stl</string>
				</dict>
			</dict>
		</dict>
		<key>loop</key>
		<dict>
			<key>name</key>
			<string>meta.loop.stl</string>
			<key>begin</key>
			<string>(?:^|\G|(?&lt;=\s))[ \t]*(outer[ \t]+loop)(?=$|\s)</string>
			<key>end</key>
			<string>(?:^|\G|(?&lt;=\s))[ \t]*(endloop)(?=$|\s)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#vertex</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.begin.loop.stl</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.end.loop.stl</string>
				</dict>
			</dict>
		</dict>
		<key>main</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#solid</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#facet</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#loop</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#vertex</string>
				</dict>
			</array>
		</dict>
		<key>normal</key>
		<dict>
			<key>name</key>
			<string>meta.normal.stl</string>
			<key>begin</key>
			<string>(?:^|\G|(?&lt;=\s))normal(?=$|\s)</string>
			<key>end</key>
			<string>(?=[ \t]*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#num</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>storage.type.normal.stl</string>
				</dict>
			</dict>
		</dict>
		<key>solid</key>
		<dict>
			<key>name</key>
			<string>meta.solid.stl</string>
			<key>begin</key>
			<string>(?:^﻿?|\G|(?&lt;=\s))[ \t]*(solid)(?:[ \t]+(\S+)(?:[ \t]+(\S.*))?)?[ \t]*$</string>
			<key>end</key>
			<string>(?:^﻿?|\G|(?&lt;=\s))[ \t]*(endsolid)(?:[ \t]+(\2)(?=$|\s))?(?:[ \t]+(\S.*))?[ \t]*$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#facet</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.definition.header.stl</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.start.solid.stl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.solid.stl</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>comment.line.ignored.stl</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.definition.footer.stl</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.end.solid.stl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.solid.stl</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>comment.line.ignored.stl</string>
				</dict>
			</dict>
		</dict>
		<key>vertex</key>
		<dict>
			<key>name</key>
			<string>meta.vertex.stl</string>
			<key>begin</key>
			<string>(?:^|\G|(?&lt;=\s))[ \t]*(vertex)(?=$|\s)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#num</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.vertex.stl</string>
				</dict>
			</dict>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>stl</string>
	</array>
</dict>
</plist>
