<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>StringTemplate</string>
	<key>scopeName</key>
	<string>source.string-template</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>\A(?=\s*$)</string>
			<key>end</key>
			<string>(?=\S)</string>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.document.dollar-delimiters.string-template</string>
			<key>begin</key>
			<string>(?xi)(?=
	&lt;(abbr|acronym|address|applet|area|article|aside|audio|a|basefont|base
	| bdi|bdo|bgsound|big|blink|blockquote|body|br|button|b|canvas|caption
	| center|cite|code|colgroup|col|content|datalist|data|dd|del|details|dfn
	| dialog|dir|div|dl|dt|embed|em|fieldset|figcaption|figure|font|footer
	| form|frameset|frame|h1|h2|h3|h4|h5|h6|header|head|hgroup|hr|html|iframe
	| image|img|input|ins|isindex|i|kbd|keygen|label|legend|link|listing|li
	| main|map|mark|marquee|math|menuitem|menu|meta|meter|multicol|nav|nextid
	| nobr|noembed|noframes|noscript|object|ol|optgroup|option|output|param
	| picture|plaintext|portal|pre|progress|p|q|rb|rp|rtc|rt|ruby|samp|script
	| section|select|shadow|slot|small|source|spacer|span|strike|strong|style
	| sub|summary|sup|svg|s|table|tbody|td|template|textarea|tfoot|thead|th
	| time|title|track|tr|tt|ul|u|var|video|wbr|xmp
	) (?=\\s|/?&gt;)[^&gt;]*&gt;
	| &lt;!DOCTYPE
	| &lt;!--.*?--&gt;
	| &amp;(?:amp|lt|gt|quot|nbsp|\#(?:[xX][\dA-Fa-f]+|\d+));
	| \$! .+? !\$
)</string>
			<key>end</key>
			<string>(?=A)B</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#main$</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.document.angle-delimiters.string-template</string>
			<key>begin</key>
			<string>(?&lt;!\\)(?=&lt;[\a-zA-Z].*?&gt;|&lt;!.*?!&gt;)</string>
			<key>end</key>
			<string>(?=A)B</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#main</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>attribute</key>
		<dict>
			<key>name</key>
			<string>meta.embedded.section.string-template</string>
			<key>begin</key>
			<string>&lt;</string>
			<key>end</key>
			<string>&gt;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#expression</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.section.begin.string-template</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.section.end.string-template</string>
				</dict>
			</dict>
		</dict>
		<key>attribute$</key>
		<dict>
			<key>name</key>
			<string>meta.embedded.section.string-template</string>
			<key>begin</key>
			<string>\$</string>
			<key>end</key>
			<string>([^$]*+)(\$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#expression</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.section.begin.string-template</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#expression</string>
						</dict>
					</array>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.section.end.string-template</string>
				</dict>
			</dict>
		</dict>
		<key>bareword</key>
		<dict>
			<key>name</key>
			<string>variable.identifier.string-template</string>
			<key>match</key>
			<string>[-\w.]+</string>
		</dict>
		<key>comment</key>
		<dict>
			<key>name</key>
			<string>comment.block.string-template</string>
			<key>begin</key>
			<string>&lt;!</string>
			<key>end</key>
			<string>!&gt;</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.begin.string-template</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.end.string-template</string>
				</dict>
			</dict>
		</dict>
		<key>comment$</key>
		<dict>
			<key>name</key>
			<string>comment.block.string-template</string>
			<key>begin</key>
			<string>\$!</string>
			<key>end</key>
			<string>!\$</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.begin.string-template</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.end.string-template</string>
				</dict>
			</dict>
		</dict>
		<key>condition</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.operator.logical.string-template</string>
					<key>match</key>
					<string>\|\||&amp;&amp;|!</string>
				</dict>
				<dict>
					<key>name</key>
					<string>variable.identifier.string-template</string>
					<key>match</key>
					<string>\G([-\w.]+)</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#expression</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bareword</string>
				</dict>
			</array>
		</dict>
		<key>conditional</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.embedded.conditional.$2.string-template</string>
					<key>contentName</key>
					<string>meta.condition.string-template</string>
					<key>begin</key>
					<string>(&lt;)(if|elseif|else|endif)(\()</string>
					<key>end</key>
					<string>(\))(&gt;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#condition</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.section.begin.string-template</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.flow.$2.string-template</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.conditional.begin.string-template</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.conditional.end.string-template</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.section.end.string-template</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>conditional$</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.embedded.conditional.$2.string-template</string>
					<key>contentName</key>
					<string>meta.condition.string-template</string>
					<key>begin</key>
					<string>(\$)(if|elseif|else|endif)(\()</string>
					<key>end</key>
					<string>(\))(\$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#condition</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.section.begin.string-template</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.flow.$2.string-template</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.conditional.begin.string-template</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.conditional.end.string-template</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.section.end.string-template</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>escape</key>
		<dict>
			<key>name</key>
			<string>constant.character.escape.delimiter.string-template</string>
			<key>match</key>
			<string>\\[&lt;&gt;]</string>
		</dict>
		<key>escape$</key>
		<dict>
			<key>name</key>
			<string>constant.character.escape.delimiter.string-template</string>
			<key>match</key>
			<string>\\\$</string>
		</dict>
		<key>expression</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.language.boolean.$1.string-template</string>
					<key>match</key>
					<string>\b(true|false)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.iteration-index.string-template</string>
					<key>match</key>
					<string>(?:\G|^)i0?\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.whitespace.string-template</string>
					<key>match</key>
					<string>\\[ ntr]</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.escape.codepoint.hex.string-template</string>
					<key>match</key>
					<string>\\u[0-9A-Fa-f]{4}</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.escape.line-continuation.string-template</string>
					<key>match</key>
					<string>\\{2}</string>
				</dict>
				<dict>
					<key>include</key>
					<string>etc#strDouble</string>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.function-call.indirect.string-template</string>
					<key>begin</key>
					<string>(?:\G|^|:)(?=\()</string>
					<key>end</key>
					<string>(?&lt;=\))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#expressionGroup</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.separator.string-template</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.argument-list.string-template</string>
					<key>begin</key>
					<string>(?&lt;=\))(?=\()</string>
					<key>end</key>
					<string>(?&lt;=\))(?!\G)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#expressionGroup</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.list.array.string-template</string>
					<key>begin</key>
					<string>(?:\G|^)\[</string>
					<key>end</key>
					<string>\]</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#bareword</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#expression</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.array.begin.string-template</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.array.end.string-template</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>include</key>
					<string>#subtemplate</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?:\G|^)[-\w.]+(?=\s*;\s*\w[-\w.]*=)</string>
					<key>end</key>
					<string>(?=[^\s;])</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(;)\s*([-\w.]+)(=)([-\w.]+)</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>etc#semi</string>
										</dict>
									</array>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.other.attribute-name.string-template</string>
								</dict>
								<key>3</key>
								<dict>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>etc#eql</string>
										</dict>
									</array>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>constant.other.attribute-value.string-template</string>
								</dict>
							</dict>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.attribute.string-template</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.function-call.string-template</string>
					<key>begin</key>
					<string>(?:\G|^|(?&lt;!\))(:))([-\w.]+)(?=\()</string>
					<key>end</key>
					<string>(?&lt;=\))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#expressionGroup</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.separator.string-template</string>
						</dict>
						<key>2</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#functionName</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?:\G|^)[-\w.]+(?=(\.\())</string>
					<key>end</key>
					<string>(?&lt;=\))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>meta.subscript.property.indirect-lookup.string-template</string>
							<key>begin</key>
							<string>\G\.(?=\()</string>
							<key>end</key>
							<string>(?!\G)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#expressionGroup</string>
								</dict>
							</array>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>etc#dot</string>
										</dict>
									</array>
								</dict>
							</dict>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.attribute.string-template</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?:\G|^)([-\w.]+)(?=\,)|(?&lt;=\))(?=\s*,)</string>
					<key>end</key>
					<string>(?=[^-\w.\s,])</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>\s*(,)\s*([-\w.]+)(?=\()</string>
							<key>end</key>
							<string>(?&lt;=\))</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#expressionGroup</string>
								</dict>
							</array>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>etc#comma</string>
										</dict>
									</array>
								</dict>
								<key>2</key>
								<dict>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#functionName</string>
										</dict>
									</array>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>match</key>
							<string>\s*(,)\s*([-\w.]+)</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>etc#comma</string>
										</dict>
									</array>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.name.tag.attribute.string-template</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>include</key>
							<string>#expression</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.attribute.string-template</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>(?:\G|^)([-\w.]+)((\.)([-\w.]+))?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.attribute.string-template</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.subscript.property.direct-lookup.string-template</string>
						</dict>
						<key>3</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>etc#dot</string>
								</dict>
							</array>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>variable.member.property.string-template</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>meta.subscript.property.indirect-lookup.string-template</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>include</key>
					<string>etc#kolon</string>
				</dict>
				<dict>
					<key>include</key>
					<string>etc#comma</string>
				</dict>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>etc#semi</string>
				</dict>
			</array>
		</dict>
		<key>expressionGroup</key>
		<dict>
			<key>name</key>
			<string>meta.expression.string-template</string>
			<key>begin</key>
			<string>\(</string>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#bareword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#expression</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.expression.begin.string-template</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.expression.end.string-template</string>
				</dict>
			</dict>
		</dict>
		<key>functionName</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>support.function.$1.string-template</string>
					<key>match</key>
					<string>(?:\G|^)(first|last|length|rest|reverse|strip|strlen|trim|trunc)$</string>
				</dict>
				<dict>
					<key>name</key>
					<string>entity.name.function.string-template</string>
					<key>match</key>
					<string>(?:\G|^)(.+)</string>
				</dict>
			</array>
		</dict>
		<key>main</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escape</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#conditional</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#attribute</string>
				</dict>
			</array>
		</dict>
		<key>main$</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escape$</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment$</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#conditional$</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#attribute$</string>
				</dict>
			</array>
		</dict>
		<key>subtemplate</key>
		<dict>
			<key>name</key>
			<string>meta.subtemplate.string-template</string>
			<key>begin</key>
			<string>{</string>
			<key>end</key>
			<string>}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.operator.separator.string-template</string>
					<key>match</key>
					<string>\|</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#main</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bareword</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.subtemplate.begin.string-template</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.subtemplate.end.string-template</string>
				</dict>
			</dict>
		</dict>
	</dict>
	<key>injections</key>
	<dict>
		<key>L:source.string-template meta.document.dollar-delimiters.string-template - comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>&lt;|&gt;</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#main$</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>st</string>
	</array>
</dict>
</plist>
