<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>SRT Subtitle</string>
	<key>scopeName</key>
	<string>text.srt</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#subtitle</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>bold</key>
		<dict>
			<key>name</key>
			<string>markup.bold.srt</string>
			<key>begin</key>
			<string>(?i)&lt;b&gt;</string>
			<key>end</key>
			<string>(?i)&lt;/b&gt;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#sound</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#person</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bold</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#italic</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#underline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#font</string>
				</dict>
			</array>
		</dict>
		<key>font</key>
		<dict>
			<key>name</key>
			<string>markup.link.font.srt</string>
			<key>begin</key>
			<string>(?i)&lt;font\b.*?&gt;</string>
			<key>end</key>
			<string>(?i)&lt;/font&gt;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#sound</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#person</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bold</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#italic</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#underline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#font</string>
				</dict>
			</array>
		</dict>
		<key>italic</key>
		<dict>
			<key>name</key>
			<string>markup.italic.srt</string>
			<key>begin</key>
			<string>(?i)&lt;i&gt;</string>
			<key>end</key>
			<string>(?i)&lt;/i&gt;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#sound</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#person</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bold</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#italic</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#underline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#font</string>
				</dict>
			</array>
		</dict>
		<key>person</key>
		<dict>
			<key>name</key>
			<string>entity.name.tag.srt</string>
			<key>match</key>
			<string>^\w+:</string>
		</dict>
		<key>sound</key>
		<dict>
			<key>name</key>
			<string>string.quoted.other.sound.srt</string>
			<key>match</key>
			<string>\[.*?\]|\(.*?\)</string>
		</dict>
		<key>subtitle</key>
		<dict>
			<key>name</key>
			<string>meta.subtitle.srt</string>
			<key>begin</key>
			<string>\b\d+$</string>
			<key>end</key>
			<string>^\s*$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#time</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#sound</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#person</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bold</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#italic</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#underline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#font</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>entity.name.section.srt</string>
				</dict>
			</dict>
		</dict>
		<key>time</key>
		<dict>
			<key>match</key>
			<string>^(\d{2}:\d{2}:\d{2},\d{3})\s*(--&gt;)\s*(\d{2}:\d{2}:\d{2},\d{3})$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.time.srt</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.separator.srt</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.time.srt</string>
				</dict>
			</dict>
		</dict>
		<key>underline</key>
		<dict>
			<key>name</key>
			<string>markup.underline.srt</string>
			<key>begin</key>
			<string>(?i)&lt;u&gt;</string>
			<key>end</key>
			<string>(?i)&lt;/u&gt;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#sound</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#person</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bold</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#italic</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#underline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#font</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>srt</string>
	</array>
</dict>
</plist>
