<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>SuperCollider</string>
	<key>scopeName</key>
	<string>source.supercollider</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>name</key>
			<string>keyword.control.supercollider</string>
			<key>match</key>
			<string>\b(arg|var|classvar|const|this|thisThread|thisMethod|thisFunction|thisFunctionDef|thisProcess|true|false|inf|nil)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>string.quoted.double.supercollider</string>
			<key>begin</key>
			<string>&quot;</string>
			<key>end</key>
			<string>&quot;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.character.escape.supercollider</string>
					<key>match</key>
					<string>\\.</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>name</key>
			<string>entity.name.symbol.supercollider</string>
			<key>begin</key>
			<string>&apos;</string>
			<key>end</key>
			<string>&apos;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.character.escape.supercollider</string>
					<key>match</key>
					<string>\\.</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>name</key>
			<string>support.name.tag.supercollider</string>
			<key>match</key>
			<string>[a-z][a-zA-Z0-9_]*\:</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*\+*\s*([A-Z]{1}[a-zA-Z0-9_]*)\s*\:{1}\s*([A-Z]{1}[a-zA-Z0-9_]*)\s*\{</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.supercollider</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>^([A-Z_]{1}[a-zA-Z0-9_]*)[^a-zA-Z0-9_]</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.supercollider</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>variable.parameter.function.supercollider</string>
			<key>match</key>
			<string>\|[a-zA-Z0-9\#\[\]\&quot;\_\=\.\(\)[[:space:]]\,]+\|</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[^a-zA-Z0-9\\]([A-Z_]{1}[a-zA-Z0-9_]*)[^a-zA-Z0-9_]</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.supercollider</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>entity.name.symbol.supercollider</string>
			<key>match</key>
			<string>\\[a-zA-Z0-9\_]+</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(\**[a-z]{1}[a-zA-Z0-9_]+)\s*\{</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.supercollider</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>variable.language.supercollider</string>
			<key>match</key>
			<string>\~[a-z][a-zA-Z0-9_]*</string>
		</dict>
		<dict>
			<key>name</key>
			<string>comment.single.supercollider</string>
			<key>match</key>
			<string>\/\/.*</string>
		</dict>
		<dict>
			<key>name</key>
			<string>comment.multiline.supercollider</string>
			<key>begin</key>
			<string>\/\*</string>
			<key>end</key>
			<string>\*\/</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.numeric.supercollider</string>
			<key>match</key>
			<string>\b(0[xX][0-9A-Fa-f](?&gt;_?[0-9A-Fa-f])*|\d(?&gt;_?\d)*(\.(?![^[:space:][:digit:]])(?&gt;_?\d)*)?([eE][-+]?\d(?&gt;_?\d)*)?|0[bB][01]+)\b</string>
		</dict>
	</array>
	<key>fileTypes</key>
	<array>
		<string>sc</string>
		<string>scd</string>
	</array>
</dict>
</plist>
