<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Sway</string>
	<key>scopeName</key>
	<string>source.sway</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(&lt;)(\[)</string>
			<key>end</key>
			<string>&gt;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#block-comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#gtypes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lvariables</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lifetimes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#punctuation</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#types</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.brackets.angle.sway</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.brackets.square.sway</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.brackets.angle.sway</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.attribute.sway</string>
			<key>begin</key>
			<string>(#)(\!?)(\[)</string>
			<key>end</key>
			<string>\]</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#block-comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lifetimes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#punctuation</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#gtypes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#types</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.attribute.sway</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.attribute.inner.sway</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.brackets.attribute.sway</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.brackets.attribute.sway</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>(dep)\s+((?:r#(?!crate|[Ss]elf|super))?[a-z][A-Za-z0-9_]*)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.sway</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.dependency.sway</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.import.sway</string>
			<key>begin</key>
			<string>\b(extern)\s+(crate)</string>
			<key>end</key>
			<string>;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#block-comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#punctuation</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.sway</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.crate.sway</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.semi.sway</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.use.sway</string>
			<key>begin</key>
			<string>\b(use)\s</string>
			<key>end</key>
			<string>;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#block-comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#namespaces</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#punctuation</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#types</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lvariables</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.sway</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.semi.sway</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>include</key>
			<string>#block-comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#lvariables</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constants</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#gtypes</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#functions</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#types</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#lifetimes</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#macros</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#namespaces</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#punctuation</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#variables</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>block-comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>comment.block.sway</string>
					<key>match</key>
					<string>/\*\*/</string>
				</dict>
				<dict>
					<key>name</key>
					<string>comment.block.documentation.sway</string>
					<key>begin</key>
					<string>/\*\*</string>
					<key>end</key>
					<string>\*/</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#block-comments</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>name</key>
					<string>comment.block.sway</string>
					<key>begin</key>
					<string>/\*(?!\*)</string>
					<key>end</key>
					<string>\*/</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#block-comments</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>comment.line.documentation.sway</string>
					<key>match</key>
					<string>^\s*///.*</string>
				</dict>
				<dict>
					<key>name</key>
					<string>comment.line.double-slash.sway</string>
					<key>match</key>
					<string>\s*//.*</string>
				</dict>
			</array>
		</dict>
		<key>constants</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.other.caps.sway</string>
					<key>match</key>
					<string>\b[A-Z]{2}[A-Z0-9_]*\b</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(const)\s+([A-Z][A-Za-z0-9_]*)\b</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.sway</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.other.caps.sway</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.decimal.sway</string>
					<key>match</key>
					<string>\b\d[\d_]*(\.?)[\d_]*(?:(E)([+-])([\d_]+))?(f32|f64|i128|i16|i32|i64|i8|isize|u128|u16|u32|u64|u8|usize)?\b</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.dot.decimal.sway</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.exponent.sway</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.exponent.sign.sway</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.decimal.exponent.mantissa.sway</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.numeric.sway</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.hex.sway</string>
					<key>match</key>
					<string>\b0x[\da-fA-F_]+(i128|i16|i32|i64|i8|isize|u128|u16|u32|u64|u8|usize)?\b</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.numeric.sway</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.oct.sway</string>
					<key>match</key>
					<string>\b0o[0-7_]+(i128|i16|i32|i64|i8|isize|u128|u16|u32|u64|u8|usize)?\b</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.numeric.sway</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.bin.sway</string>
					<key>match</key>
					<string>\b0b[01_]+(i128|i16|i32|i64|i8|isize|u128|u16|u32|u64|u8|usize)?\b</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.numeric.sway</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.bool.sway</string>
					<key>match</key>
					<string>\b(true|false)\b</string>
				</dict>
			</array>
		</dict>
		<key>escapes</key>
		<dict>
			<key>name</key>
			<string>constant.character.escape.sway</string>
			<key>match</key>
			<string>(\\)(?:(?:(x[0-7][0-7a-fA-F])|(u(\{)[\da-fA-F]{4,6}(\}))|.))</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.character.escape.backslash.sway</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.character.escape.bit.sway</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.character.escape.unicode.sway</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant.character.escape.unicode.punctuation.sway</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>constant.character.escape.unicode.punctuation.sway</string>
				</dict>
			</dict>
		</dict>
		<key>functions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(pub)(\()</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.sway</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.brackets.round.sway</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.asm.definition.sway</string>
					<key>begin</key>
					<string>\b(asm)((\())</string>
					<key>end</key>
					<string>\{|;</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#block-comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#keywords</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#lvariables</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#constants</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#gtypes</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#functions</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#lifetimes</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#macros</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#namespaces</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#punctuation</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#strings</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#types</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#variables</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.attribute.asm.sway</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.brackets.round.sway</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.brackets.curly.sway</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.function.definition.sway</string>
					<key>begin</key>
					<string>\b(fn)\s+((?:r#(?!crate|[Ss]elf|super))?[A-Za-z0-9_]+)((\()|(&lt;))</string>
					<key>end</key>
					<string>\{|;</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#block-comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#keywords</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#lvariables</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#constants</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#gtypes</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#functions</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#lifetimes</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#macros</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#namespaces</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#punctuation</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#strings</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#types</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#variables</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.fn.sway</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.sway</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.brackets.round.sway</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>punctuation.brackets.angle.sway</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.brackets.curly.sway</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.function.call.sway</string>
					<key>begin</key>
					<string>((?:r#(?!crate|[Ss]elf|super))?[A-Za-z0-9_]+)(\()</string>
					<key>end</key>
					<string>\)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#block-comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#keywords</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#lvariables</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#constants</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#gtypes</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#functions</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#lifetimes</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#macros</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#namespaces</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#punctuation</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#strings</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#types</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#variables</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.sway</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.brackets.round.sway</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.brackets.round.sway</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.function.call.sway</string>
					<key>begin</key>
					<string>((?:r#(?!crate|[Ss]elf|super))?[A-Za-z0-9_]+)(?=::&lt;.*&gt;\()</string>
					<key>end</key>
					<string>\)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#block-comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#keywords</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#lvariables</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#constants</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#gtypes</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#functions</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#lifetimes</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#macros</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#namespaces</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#punctuation</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#strings</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#types</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#variables</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.sway</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.brackets.round.sway</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>gtypes</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>entity.name.type.option.sway</string>
					<key>match</key>
					<string>\b(Some|None)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>entity.name.type.result.sway</string>
					<key>match</key>
					<string>\b(Ok|Err)\b</string>
				</dict>
			</array>
		</dict>
		<key>interpolations</key>
		<dict>
			<key>name</key>
			<string>meta.interpolation.sway</string>
			<key>match</key>
			<string>({)[^&quot;{}]*(})</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.interpolation.sway</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.interpolation.sway</string>
				</dict>
			</dict>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.control.sway</string>
					<key>match</key>
					<string>\b(await|break|continue|do|else|for|if|loop|match|return|try|while|yield)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.other.sway storage.type.sway</string>
					<key>match</key>
					<string>\b(extern|macro|dep)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>storage.modifier.sway</string>
					<key>match</key>
					<string>\b(const)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>storage.modifier.sway</string>
					<key>match</key>
					<string>\b(let)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.declaration.type.sway storage.type.sway</string>
					<key>match</key>
					<string>\b(type)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.declaration.enum.sway storage.type.sway</string>
					<key>match</key>
					<string>\b(enum)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.declaration.trait.sway storage.type.sway</string>
					<key>match</key>
					<string>\b(trait)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.declaration.abi.sway storage.type.sway</string>
					<key>match</key>
					<string>\b(abi)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.declaration.struct.sway</string>
					<key>match</key>
					<string>\b(struct)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>storage.modifier.sway</string>
					<key>match</key>
					<string>\b(abstract|static)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.other.sway</string>
					<key>match</key>
					<string>\b(as|async|become|box|dyn|move|final|impl|in|override|priv|pub|ref|typeof|union|unsafe|unsized|use|virtual|where)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.other.fn.sway</string>
					<key>match</key>
					<string>\bfn\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.attribute.asm.sway</string>
					<key>match</key>
					<string>\basm\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.other.crate.sway</string>
					<key>match</key>
					<string>\bcrate\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>storage.modifier.mut.sway</string>
					<key>match</key>
					<string>\bmut\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.logical.sway</string>
					<key>match</key>
					<string>(\^|\||\|\||&amp;&amp;|&lt;&lt;|&gt;&gt;|!)(?!=)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.borrow.and.sway</string>
					<key>match</key>
					<string>&amp;(?![&amp;=])</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.sway</string>
					<key>match</key>
					<string>(\+=|-=|\*=|/=|%=|\^=|&amp;=|\|=|&lt;&lt;=|&gt;&gt;=)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.equal.sway</string>
					<key>match</key>
					<string>(?&lt;![&lt;&gt;])=(?!=|&gt;)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.comparison.sway</string>
					<key>match</key>
					<string>(=(=)?(?!&gt;)|!=|&lt;=|(?&lt;!=)&gt;=)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.math.sway</string>
					<key>match</key>
					<string>(([+%]|(\*(?!\w)))(?!=))|(-(?!&gt;))|(/(?!/))</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?:\b|(?:(\))|(\])|(\})))[ \t]+([&lt;&gt;])[ \t]+(?:\b|(?:(\()|(\[)|(\{)))</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.brackets.round.sway</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.brackets.square.sway</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.brackets.curly.sway</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.comparison.sway</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>punctuation.brackets.round.sway</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>punctuation.brackets.square.sway</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>punctuation.brackets.curly.sway</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.namespace.sway</string>
					<key>match</key>
					<string>::</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\*)(?=\w+)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.dereference.sway</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.subpattern.sway</string>
					<key>match</key>
					<string>@</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.access.dot.sway</string>
					<key>match</key>
					<string>\.(?!\.)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.range.sway</string>
					<key>match</key>
					<string>\.{2}(=|\.)?</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.key-value.sway</string>
					<key>match</key>
					<string>:(?!:)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.arrow.skinny.sway</string>
					<key>match</key>
					<string>-&gt;</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.arrow.fat.sway</string>
					<key>match</key>
					<string>=&gt;</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.macro.dollar.sway</string>
					<key>match</key>
					<string>\$</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.question.sway</string>
					<key>match</key>
					<string>\?</string>
				</dict>
			</array>
		</dict>
		<key>lifetimes</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>([&apos;])([a-zA-Z_][0-9a-zA-Z_]*)(?![&apos;])\b</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.lifetime.sway</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.lifetime.sway</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>(\&amp;)([&apos;])([a-zA-Z_][0-9a-zA-Z_]*)(?![&apos;])\b</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.borrow.sway</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.lifetime.sway</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.lifetime.sway</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>lvariables</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>variable.language.self.sway</string>
					<key>match</key>
					<string>\b[Ss]elf\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>variable.language.super.sway</string>
					<key>match</key>
					<string>\bsuper\b</string>
				</dict>
			</array>
		</dict>
		<key>macros</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.macro.sway</string>
					<key>match</key>
					<string>(([a-z_][A-Za-z0-9_]*!)|([A-Z_][A-Za-z0-9_]*!))</string>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.macro.sway</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.macro.sway</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>namespaces</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;![A-Za-z0-9_])([a-z0-9_]+)((?&lt;!super|self)::)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.namespace.sway</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.namespace.sway</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>punctuation</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>punctuation.comma.sway</string>
					<key>match</key>
					<string>,</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.brackets.curly.sway</string>
					<key>match</key>
					<string>[{}]</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.brackets.round.sway</string>
					<key>match</key>
					<string>[()]</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.semi.sway</string>
					<key>match</key>
					<string>;</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.brackets.square.sway</string>
					<key>match</key>
					<string>[\[\]]</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.brackets.angle.sway</string>
					<key>match</key>
					<string>(?&lt;!=)[&lt;&gt;]</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>string.quoted.double.sway</string>
					<key>begin</key>
					<string>(b?)(&quot;)</string>
					<key>end</key>
					<string>&quot;</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escapes</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#interpolations</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.quoted.byte.raw.sway</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.sway</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.sway</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>string.quoted.double.sway</string>
					<key>begin</key>
					<string>(b?r)(#*)(&quot;)</string>
					<key>end</key>
					<string>(&quot;)(\2)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.quoted.byte.raw.sway</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.raw.sway</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.sway</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.sway</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.raw.sway</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>string.quoted.single.char.sway</string>
					<key>begin</key>
					<string>(b)?(&apos;)</string>
					<key>end</key>
					<string>&apos;</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escapes</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.quoted.byte.raw.sway</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.char.sway</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.char.sway</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>types</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;![A-Za-z])(f32|f64|i128|i16|i32|i64|i8|isize|u128|u16|u32|u64|u8|usize)\b</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.numeric.sway</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>begin</key>
					<string>\b([A-Z][A-Za-z0-9]*)(&lt;)</string>
					<key>end</key>
					<string>&gt;</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#block-comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#keywords</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#lvariables</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#lifetimes</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#punctuation</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#types</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#variables</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.sway</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.brackets.angle.sway</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.brackets.angle.sway</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>entity.name.type.primitive.sway</string>
					<key>match</key>
					<string>\b(bool|char|str)\b</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(trait)\s+([A-Z][A-Za-z0-9]*)\b</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.declaration.trait.sway storage.type.sway</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.trait.sway</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(abi)\s+([A-Z][A-Za-z0-9]*)\b</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.declaration.abi.sway storage.type.sway</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.abi.sway</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(struct)\s+([A-Z][A-Za-z0-9]*)\b</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.declaration.struct.sway</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.struct.sway</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(enum)\s+([A-Z][A-Za-z0-9_]*)\b</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.declaration.enum.sway</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.enum.sway</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(type)\s+([A-Z][A-Za-z0-9_]*)\b</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.declaration.type.sway storage.type.sway</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.declaration.sway</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>entity.name.type.sway</string>
					<key>match</key>
					<string>\b[A-Z][A-Za-z0-9]*\b(?!!)</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\b(library)\s+([a-zA-Z_][a-zA-Z0-9_]*)</string>
					<key>end</key>
					<string>[\{\(;]</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#block-comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#keywords</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#namespaces</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#punctuation</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#types</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#lvariables</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>source.sway meta.attribute.sway</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.sway</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>(contract|script|predicate);</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>source.sway meta.attribute.sway</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>variables</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>variable.other.sway</string>
					<key>match</key>
					<string>\b(?&lt;!(?&lt;!\.)\.)(?:r#(?!(crate|[Ss]elf|super)))?[a-z0-9_]+\b</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>sw</string>
	</array>
</dict>
</plist>
