<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>TalonScript</string>
	<key>scopeName</key>
	<string>source.talon</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#body-header</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#header</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#body-noheader</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#settings</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>action</key>
		<dict>
			<key>name</key>
			<string>variable.parameter.talon</string>
			<key>begin</key>
			<string>([a-zA-Z0-9._]+)(\()</string>
			<key>end</key>
			<string>(\))</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#action</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#qstring-long</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#qstring</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#argsep</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#varname</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.talon</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>punctuation.separator.talon</string>
							<key>match</key>
							<string>\.</string>
						</dict>
					</array>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.talon</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.end.talon</string>
				</dict>
			</dict>
		</dict>
		<key>action-gamepad</key>
		<dict>
			<key>name</key>
			<string>entity.name.function.talon</string>
			<key>match</key>
			<string>(deck|gamepad|action|face|parrot)(\()(.*)(\))</string>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.talon</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.talon</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#key-mods</string>
						</dict>
					</array>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.key.talon</string>
				</dict>
			</dict>
		</dict>
		<key>action-key</key>
		<dict>
			<key>name</key>
			<string>entity.name.function.talon</string>
			<key>match</key>
			<string>key(\()(.*)(\))</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.talon</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.talon</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#key-prefixes</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#key-mods</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#keystring</string>
						</dict>
					</array>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.key.talon</string>
				</dict>
			</dict>
		</dict>
		<key>argsep</key>
		<dict>
			<key>name</key>
			<string>punctuation.separator.talon</string>
			<key>match</key>
			<string>,</string>
		</dict>
		<key>assignment</key>
		<dict>
			<key>match</key>
			<string>(\S*)(\s?=\s?)(.*)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.talon</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.talon</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.other.talon</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#expression</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>body-header</key>
		<dict>
			<key>begin</key>
			<string>^-$</string>
			<key>end</key>
			<string>(?=not)possible</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#body-noheader</string>
				</dict>
			</array>
		</dict>
		<key>body-noheader</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#other-rule-definition</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#speech-rule-definition</string>
				</dict>
			</array>
		</dict>
		<key>capture</key>
		<dict>
			<key>name</key>
			<string>variable.parameter.talon</string>
			<key>match</key>
			<string>(\&lt;[a-zA-Z0-9._]+\&gt;)</string>
		</dict>
		<key>comment</key>
		<dict>
			<key>name</key>
			<string>comment.line.number-sign.talon</string>
			<key>match</key>
			<string>(\s*#.*)$</string>
		</dict>
		<key>context</key>
		<dict>
			<key>match</key>
			<string>(.*): (.*)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.talon</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>keyword.operator.talon</string>
							<key>match</key>
							<string>(and |or )</string>
						</dict>
					</array>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.talon</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#regexp</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>expression</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#qstring-long</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#action-key</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#action</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#qstring</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#varname</string>
				</dict>
			</array>
		</dict>
		<key>fstring</key>
		<dict>
			<key>name</key>
			<string>constant.character.format.placeholder.talon</string>
			<key>match</key>
			<string>{(.+?)}</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#action</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#operator</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#number</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#varname</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#qstring</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>header</key>
		<dict>
			<key>begin</key>
			<string>(?=^app:|title:|os:|tag:|list:|language:)</string>
			<key>end</key>
			<string>(?=^-$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#context</string>
				</dict>
			</array>
		</dict>
		<key>key-mods</key>
		<dict>
			<key>name</key>
			<string>keyword.operator.talon</string>
			<key>match</key>
			<string>(:)(up|down|change|repeat|start|stop|\d+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.talon</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.talon</string>
				</dict>
			</dict>
		</dict>
		<key>key-prefixes</key>
		<dict>
			<key>match</key>
			<string>(ctrl|shift|cmd|alt|win|super)(-)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.talon</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.talon</string>
				</dict>
			</dict>
		</dict>
		<key>keystring</key>
		<dict>
			<key>name</key>
			<string>string.quoted.double.talon</string>
			<key>begin</key>
			<string>(&quot;|&apos;)</string>
			<key>end</key>
			<string>(\1)|$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string-body</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#key-mods</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#key-prefixes</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.talon</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.talon</string>
				</dict>
			</dict>
		</dict>
		<key>list</key>
		<dict>
			<key>name</key>
			<string>string.interpolated.talon</string>
			<key>match</key>
			<string>({[a-zA-Z0-9._]+?})</string>
		</dict>
		<key>number</key>
		<dict>
			<key>name</key>
			<string>constant.numeric.talon</string>
			<key>match</key>
			<string>(?&lt;=\b)\d+(\.\d+)?</string>
		</dict>
		<key>operator</key>
		<dict>
			<key>name</key>
			<string>keyword.operator.talon</string>
			<key>match</key>
			<string>\s(\+|-|\*|/|or)\s</string>
		</dict>
		<key>other-rule-definition</key>
		<dict>
			<key>begin</key>
			<string>^([a-z]+\(.*[^\-]\)|[a-z]+\(.*--\)|[a-z]+\(-\)|[a-z]+\(\)):</string>
			<key>end</key>
			<string>(?=^[^\s#])</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#statement</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.talon</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#action-key</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#action-gamepad</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#rule-specials</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>qstring</key>
		<dict>
			<key>name</key>
			<string>string.quoted.double.talon</string>
			<key>begin</key>
			<string>(&quot;|&apos;)</string>
			<key>end</key>
			<string>(\1)|$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string-body</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.talon</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.talon</string>
				</dict>
			</dict>
		</dict>
		<key>qstring-long</key>
		<dict>
			<key>name</key>
			<string>string.quoted.double.talon</string>
			<key>begin</key>
			<string>(&quot;&quot;&quot;|&apos;&apos;&apos;)</string>
			<key>end</key>
			<string>(\1)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string-body</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.talon</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.talon</string>
				</dict>
			</dict>
		</dict>
		<key>regexp</key>
		<dict>
			<key>name</key>
			<string>string.regexp.talon</string>
			<key>begin</key>
			<string>(/)</string>
			<key>end</key>
			<string>(/)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>support.other.match.any.regexp</string>
					<key>match</key>
					<string>\.</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.other.match.end.regexp</string>
					<key>match</key>
					<string>\$</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.other.match.begin.regexp</string>
					<key>match</key>
					<string>\^</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.escape.talon</string>
					<key>match</key>
					<string>\\\.|\\\*|\\\^|\\\$|\\\+|\\\?</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.other.set.regexp</string>
					<key>match</key>
					<string>\[(\\\]|[^\]])*\]</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.quantifier.regexp</string>
					<key>match</key>
					<string>\*|\+|\?</string>
				</dict>
			</array>
		</dict>
		<key>rule-specials</key>
		<dict>
			<key>match</key>
			<string>(settings|tag)(\()(\))</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.talon</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.talon</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.end.talon</string>
				</dict>
			</dict>
		</dict>
		<key>speech-rule-definition</key>
		<dict>
			<key>begin</key>
			<string>^(.*?):</string>
			<key>end</key>
			<string>(?=^[^\s#])</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#statement</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.talon</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>string.regexp.talon</string>
							<key>match</key>
							<string>^\^</string>
						</dict>
						<dict>
							<key>name</key>
							<string>string.regexp.talon</string>
							<key>match</key>
							<string>\$$</string>
						</dict>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.begin.talon</string>
							<key>match</key>
							<string>\(</string>
						</dict>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.end.talon</string>
							<key>match</key>
							<string>\)</string>
						</dict>
						<dict>
							<key>name</key>
							<string>punctuation.separator.talon</string>
							<key>match</key>
							<string>\|</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#capture</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#list</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>statement</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#qstring-long</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#action-key</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#action</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#qstring</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#assignment</string>
				</dict>
			</array>
		</dict>
		<key>string-body</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>string.quoted.double.talon</string>
					<key>match</key>
					<string>{{|}}</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.escape.python</string>
					<key>match</key>
					<string>\\\\|\\n|\\t|\\r|\\&quot;|\\&apos;</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#fstring</string>
				</dict>
			</array>
		</dict>
		<key>varname</key>
		<dict>
			<key>name</key>
			<string>variable.parameter.talon</string>
			<key>match</key>
			<string>([a-zA-Z0-9._])(_(list|\d+))?</string>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.talon</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>keyword.operator.talon</string>
							<key>match</key>
							<string>_</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>talon</string>
	</array>
</dict>
</plist>
