<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Tea</string>
	<key>scopeName</key>
	<string>source.tea</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>&lt;%</string>
			<key>end</key>
			<string>%&gt;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#language</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.js</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.xml</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>functions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>support.function.tea</string>
					<key>match</key>
					<string>\b(setLocale|getLocale|getAvailableLocales|nullFormat|getNullFormat|getDateFormat|getAvailableTimeZones|getDataFormatTimeZone|numberFormat|getNumberFormat|getNumberFormatInfinity|getNumberFormatNaN|currentDate|startsWith|endsWith|find|findFirst|substring|toLowerCase|toUpperCase|trim|trimLeading|trimTrailing|replace|replaceFirst|replaceLast|shortOrdinal|ordinal|cardinal)\b(?=\()</string>
				</dict>
			</array>
		</dict>
		<key>language</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#functions</string>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.template.tea</string>
					<key>begin</key>
					<string>\b(template)\s+([a-zA-Z_$]\w*)?\s*(\()</string>
					<key>end</key>
					<string>(\))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\s*([a-zA-Z_$][\w.]*)\s+(\w*)(?:,\s*)?</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>storage.type.tea</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>variable.parameter.template.tea</string>
								</dict>
							</dict>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.template.tea</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.class.tea</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.template-call.tea</string>
					<key>begin</key>
					<string>\b(call)\s+(.*?)\(.*?</string>
					<key>end</key>
					<string>\)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#functions</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#strings</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.tea</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.tea</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.control.tea</string>
					<key>match</key>
					<string>\?:|\?\.|\b(break|else|foreach|if|in|reverse)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.tea</string>
					<key>match</key>
					<string>#|##|\.\.|\.\.\.|&amp;|\*\.</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.arithmetic.tea</string>
					<key>match</key>
					<string>(\-|\+|\*|%)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.tea</string>
					<key>match</key>
					<string>(=)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.comparison.tea</string>
					<key>match</key>
					<string>(==|!=|&lt;|&gt;|&lt;=|&gt;=|&lt;=&gt;|\b(and|not|or|isa)\b)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.logical.tea</string>
					<key>match</key>
					<string>(!)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.other.tea</string>
					<key>match</key>
					<string>\b(call|as|define)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.boolean.true.tea</string>
					<key>match</key>
					<string>\b(true)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.boolean.false.tea</string>
					<key>match</key>
					<string>\b(false)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.null.tea</string>
					<key>match</key>
					<string>\b(null)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.tea</string>
					<key>match</key>
					<string>\b((0(x|X)[0-9a-fA-F]+)|([0-9]+(\.[0-9]+)?))\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>comment.line.double-slash.tea</string>
					<key>match</key>
					<string>(//).*$\n?</string>
				</dict>
				<dict>
					<key>name</key>
					<string>comment.block.tea</string>
					<key>begin</key>
					<string>/\*</string>
					<key>end</key>
					<string>\*/</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.terminator.statement.tea</string>
					<key>match</key>
					<string>\;</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>string.quoted.double.tea</string>
					<key>begin</key>
					<string>&quot;</string>
					<key>end</key>
					<string>&quot;</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>constant.character.escape.tea</string>
							<key>match</key>
							<string>\\(x[[:xdigit:]]{2}|[0-2][0-7]{,2}|3[0-6][0-7]?|37[0-7]?|[4-7][0-7]?|.)</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>name</key>
					<string>string.quoted.single.tea</string>
					<key>begin</key>
					<string>&apos;</string>
					<key>end</key>
					<string>&apos;</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>constant.character.escape.tea</string>
							<key>match</key>
							<string>\\(x[[:xdigit:]]{2}|[0-2][0-7]{,2}|3[0-6][0-7]?|37[0-7]?|[4-7][0-7]?|.)</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>tea</string>
	</array>
</dict>
</plist>
