<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Texinfo</string>
	<key>scopeName</key>
	<string>text.texinfo</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\A\s*((\\)input)\s+([^@\s\x7F]+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.general.tex</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.function.tex</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.constant.language.other.tex</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>include</key>
			<string>#main</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>alias</key>
		<dict>
			<key>name</key>
			<string>meta.command.alias.texinfo</string>
			<key>match</key>
			<string>((@)alias)\s+([^=\s]+)\s*(=)\s*([^=\s]+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.command.alias.texinfo</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.function.texinfo</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.alias.texinfo</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.separator.texinfo</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.source.texinfo</string>
				</dict>
			</dict>
		</dict>
		<key>blockCommands</key>
		<dict>
			<key>name</key>
			<string>meta.command.$3.block.texinfo</string>
			<key>begin</key>
			<string>(?x) ((@)
(cartouche|copying|direntry|display|documentdescription|enumerate
|float|flushleft|flushright|format|ftable|group|itemize|multitable
|raggedright|smalldisplay|smallformat|smallindentedblock|table
|titlepage|vtable))
(?=\s|$)(.*)</string>
			<key>end</key>
			<string>((@)end\s+\3)\b</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#main</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.command.$3.texinfo</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.function.texinfo</string>
				</dict>
				<key>4</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#param</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#main</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.command.end-$3.texinfo</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.function.texinfo</string>
				</dict>
			</dict>
		</dict>
		<key>boldText</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.command.$3.braced.texinfo</string>
					<key>contentName</key>
					<string>markup.bold.texinfo</string>
					<key>begin</key>
					<string>((@)(b|strong))({)</string>
					<key>end</key>
					<string>}</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#main</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.command.$3.texinfo</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.texinfo</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.scope.begin.texinfo</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.scope.end.texinfo</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.command.$3.line.texinfo</string>
					<key>contentName</key>
					<string>markup.heading.string.unquoted.texinfo</string>
					<key>begin</key>
					<string>(?x) ^ ((@)
(appendixsection|appendixsec|appendixsubsec|appendixsubsubsec|appendix
|chapheading|chapter|heading|majorheading|section|subheading|subsection
|subsubheading|subsubsection|top|unnumberedsec|unnumberedsubsec
|unnumberedsubsubsec|unnumbered))
(?=\s|$)</string>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#main</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>markup.bold.texinfo</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.command.$3.texinfo</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.texinfo</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>booleanCommands</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.command.headings.texinfo</string>
					<key>match</key>
					<string>((@)headings)\s+(?:(on)|(off)|(single|double))\b</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.command.headings.texinfo</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.defining.function.texinfo</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.language.boolean.true.texinfo</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.language.boolean.false.texinfo</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>constant.language.heading-type.$5.texinfo</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.command.setchapternewpage.texinfo</string>
					<key>match</key>
					<string>((@)setchapternewpage)\s+(?:(on)|(off)|(odd))\b</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.command.headings.texinfo</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.defining.function.texinfo</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.language.boolean.true.texinfo</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.language.boolean.false.texinfo</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>constant.language.odd.texinfo</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.command.$3.texinfo</string>
					<key>match</key>
					<string>((@)(allowcodebreaks))\s+(true|false)(?=\s|$)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.command.$3.texinfo</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.texinfo</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.language.boolean.$4.texinfo</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.command.$3.texinfo</string>
					<key>match</key>
					<string>(?x) ((@)
(codequotebacktick|codequoteundirected|deftypefnnewline
|frenchspacing|validatemenus|xrefautomaticsectiontitle))
\s+ (?:(on)|(off)) \b</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.command.$3.texinfo</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.texinfo</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.language.boolean.true.texinfo</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>constant.language.boolean.false.texinfo</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>codeBlocks</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.command.$3.block.texinfo</string>
					<key>contentName</key>
					<string>source.embedded.emacs.lisp</string>
					<key>begin</key>
					<string>((@)(lisp|smalllisp))(?=\s|$)</string>
					<key>end</key>
					<string>((@)end\s+\3)\b</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.emacs.lisp</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#main</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.command.$3.texinfo</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.texinfo</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.command.end-$3.texinfo</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.texinfo</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.command.$3.block.texinfo</string>
					<key>contentName</key>
					<string>markup.raw.texinfo</string>
					<key>begin</key>
					<string>((@)(example|smallexample|verbatim))(?=\s|$)</string>
					<key>end</key>
					<string>((@)end\s+\3)\b</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#main</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.command.$3.texinfo</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.texinfo</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.command.end-$3.texinfo</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.texinfo</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>comma</key>
		<dict>
			<key>name</key>
			<string>punctuation.separator.delimiter.comma.texinfo</string>
			<key>match</key>
			<string>,</string>
		</dict>
		<key>command</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.command.braced.texinfo</string>
					<key>begin</key>
					<string>((@)(\w+))({)</string>
					<key>end</key>
					<string>}</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#param</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comma</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#main</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.command.$3.texinfo</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.texinfo</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.scope.begin.texinfo</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.scope.end.texinfo</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.command.$2.texinfo</string>
					<key>match</key>
					<string>(@)(\w+)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.texinfo</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>comment.line.at-sign.texinfo</string>
					<key>begin</key>
					<string>((@)c(?:omment)?)(?=$|[^-A-Za-z0-9])</string>
					<key>end</key>
					<string>$</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.command.start-comment.texinfo</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.texinfo</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>comment.line.tex-style.texinfo</string>
					<key>begin</key>
					<string>\x7F</string>
					<key>end</key>
					<string>$</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.whitespace.delete.texinfo</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>conditionals</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.command.$3.conditional.block.texinfo</string>
					<key>begin</key>
					<string>((@)(ifclear|ifcommanddefined|ifcommandnotdefined|ifset))\s+(\S+)</string>
					<key>end</key>
					<string>((@)end\s+\3)\b</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#main</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.command.$3.texinfo</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.texinfo</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.texinfo</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.command.end-$3.texinfo</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.texinfo</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.command.$3.conditional.block.texinfo</string>
					<key>begin</key>
					<string>(?x) ((@)
(ifdocbook|ifhtml|ifinfo|ifnotdocbook|ifnothtml|ifnotinfo|ifnotplaintext
|ifnottex|ifnotxml|ifplaintext|iftex|ifxml))
(?=\s|$)</string>
					<key>end</key>
					<string>((@)end\s+\3)\b</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#main</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.command.$3.texinfo</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.texinfo</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.texinfo</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.command.end-$3.texinfo</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.texinfo</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>dashes</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.character.dash.em-dash.texinfo</string>
					<key>match</key>
					<string>---</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.dash.en-dash.texinfo</string>
					<key>match</key>
					<string>--</string>
				</dict>
			</array>
		</dict>
		<key>definitions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.command.$3.line.texinfo</string>
					<key>begin</key>
					<string>((@)(defcodeindex|defindex|defopt|defoptx|defvar|defvarx))(?=\s|$)</string>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>entity.name.var.texinfo</string>
							<key>match</key>
							<string>\G\s*(?:({)[^}]*(})|\S+)</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.begin.texinfo</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.end.texinfo</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>include</key>
							<string>#main</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.command.$3.texinfo</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.texinfo</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.command.$3.line.texinfo</string>
					<key>begin</key>
					<string>((@)(defcvx|defcv|defopx|defop))(?=\s|$)</string>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(?x)
\G \s* (({)[^}]*(})|\S+)
(?: \s+ (({)[^}]*(})|\S+))?
(?: \s+ (({)[^}]*(})|\S+))?</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>storage.type.var.texinfo</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.begin.texinfo</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.end.texinfo</string>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>entity.other.inherited-class.texinfo</string>
								</dict>
								<key>5</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.begin.texinfo</string>
								</dict>
								<key>6</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.end.texinfo</string>
								</dict>
								<key>7</key>
								<dict>
									<key>name</key>
									<string>entity.name.var.texinfo</string>
								</dict>
								<key>8</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.begin.texinfo</string>
								</dict>
								<key>9</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.end.texinfo</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>include</key>
							<string>#param</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#main</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.command.$3.texinfo</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.texinfo</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.command.$3.line.texinfo</string>
					<key>begin</key>
					<string>((@)(deffnx|deffn|deftpx|deftp|defvrx|defvr))(?=\s|$)</string>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(?x)
\G \s* (({)[^}]*(})|\S+)
(?: \s+ (({)[^}]*(})|\S+))?</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>storage.type.var.texinfo</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.begin.texinfo</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.end.texinfo</string>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>entity.name.var.texinfo</string>
								</dict>
								<key>5</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.begin.texinfo</string>
								</dict>
								<key>6</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.end.texinfo</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>include</key>
							<string>#param</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#main</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.command.$3.texinfo</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.texinfo</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.command.$3.line.texinfo</string>
					<key>begin</key>
					<string>((@)(definfoenclose))(?=\s|$)</string>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\G\s*(({)[^}]*(})|[^\s,]+)</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.name.var.texinfo</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.begin.texinfo</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.end.texinfo</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>name</key>
							<string>string.unquoted.texinfo</string>
							<key>match</key>
							<string>[^\s,@]+</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comma</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.command.$3.texinfo</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.texinfo</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.command.$3.line.texinfo</string>
					<key>begin</key>
					<string>((@)(defivarx|defivar|defmethodx|defmethod))(?=\s|$)</string>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(?x)
\G \s* (({)[^}]*(})|\S+)
(?: \s+ (({)[^}]*(})|\S+))?</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.other.inherited-class.texinfo</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.begin.texinfo</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.end.texinfo</string>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>entity.name.var.texinfo</string>
								</dict>
								<key>5</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.begin.texinfo</string>
								</dict>
								<key>6</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.end.texinfo</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>include</key>
							<string>#param</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#main</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.command.$3.texinfo</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.texinfo</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.command.$3.line.texinfo</string>
					<key>begin</key>
					<string>((@)(defmacx|defmac|defunx|defun|defspecx|defspec))(?=\s|$)</string>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>entity.name.function.texinfo</string>
							<key>match</key>
							<string>\G\s*(?:({)[^}]*(})|\S+)</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.begin.texinfo</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.end.texinfo</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>include</key>
							<string>#param</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#main</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.command.$3.texinfo</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.texinfo</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.command.$3.line.texinfo</string>
					<key>begin</key>
					<string>((@)(deftypecvx|deftypecv|deftypevrx|deftypevr))(?=\s|$)</string>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(?x)
\G \s* (({)[^}]*(})|\S+)
(?: \s+ (({)[^}]*(})|\S+))?
(?: \s+ (({)[^}]*(})|\S+))?
(?: \s+ (({)[^}]*(})|\S+))?</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>storage.type.var.category.texinfo</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.begin.texinfo</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.end.texinfo</string>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>entity.other.inherited-class.texinfo</string>
								</dict>
								<key>5</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.begin.texinfo</string>
								</dict>
								<key>6</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.end.texinfo</string>
								</dict>
								<key>7</key>
								<dict>
									<key>name</key>
									<string>storage.type.var.data-type.texinfo</string>
								</dict>
								<key>8</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.begin.texinfo</string>
								</dict>
								<key>9</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.end.texinfo</string>
								</dict>
								<key>10</key>
								<dict>
									<key>name</key>
									<string>entity.name.var.texinfo</string>
								</dict>
								<key>11</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.begin.texinfo</string>
								</dict>
								<key>12</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.end.texinfo</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>include</key>
							<string>#param</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#main</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.command.$3.texinfo</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.texinfo</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.command.$3.line.texinfo</string>
					<key>begin</key>
					<string>((@)(deftypefnx|deftypefn))(?=\s|$)</string>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(?x)
\G \s* (({)[^}]*(})|\S+)
(?: \s+ (({)[^}]*(})|\S+))?
(?: \s+ (({)[^}]*(})|\S+))?</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>storage.type.var.category.texinfo</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.begin.texinfo</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.end.texinfo</string>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>storage.type.var.data-type.texinfo</string>
								</dict>
								<key>5</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.begin.texinfo</string>
								</dict>
								<key>6</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.end.texinfo</string>
								</dict>
								<key>7</key>
								<dict>
									<key>name</key>
									<string>entity.name.var.texinfo</string>
								</dict>
								<key>8</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.begin.texinfo</string>
								</dict>
								<key>9</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.end.texinfo</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>include</key>
							<string>#param</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#main</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.command.$3.texinfo</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.texinfo</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.command.$3.line.texinfo</string>
					<key>begin</key>
					<string>((@)(deftypefunx|deftypefun))(?=\s|$)</string>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(?x)
\G \s* (({)[^}]*(})|\S+)
(?: \s+ (({)[^}]*(})|\S+))?</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>storage.type.var.data-type.texinfo</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.begin.texinfo</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.end.texinfo</string>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>entity.name.var.texinfo</string>
								</dict>
								<key>5</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.begin.texinfo</string>
								</dict>
								<key>6</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.end.texinfo</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>include</key>
							<string>#param</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#main</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.command.$3.texinfo</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.texinfo</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.command.$3.line.texinfo</string>
					<key>begin</key>
					<string>((@)(deftypemethodx|deftypemethod|deftypeivarx|deftypeivar))(?=\s|$)</string>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(?x)
\G \s* (({)[^}]*(})|\S+)
(?: \s+ (({)[^}]*(})|\S+))?
(?: \s+ (({)[^}]*(})|\S+))?</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.other.inherited-class.texinfo</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.begin.texinfo</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.end.texinfo</string>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>storage.type.var.data-type.texinfo</string>
								</dict>
								<key>5</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.begin.texinfo</string>
								</dict>
								<key>6</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.end.texinfo</string>
								</dict>
								<key>7</key>
								<dict>
									<key>name</key>
									<string>entity.name.var.texinfo</string>
								</dict>
								<key>8</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.begin.texinfo</string>
								</dict>
								<key>9</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.end.texinfo</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>include</key>
							<string>#param</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#main</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.command.$3.texinfo</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.texinfo</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.command.$3.line.texinfo</string>
					<key>begin</key>
					<string>((@)(deftypeopx|deftypeop))(?=\s|$)</string>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(?x)
\G \s* (({)[^}]*(})|\S+)
(?: \s+ (({)[^}]*(})|\S+))?
(?: \s+ (({)[^}]*(})|\S+))?
(?: \s+ (({)[^}]*(})|\S+))?</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>storage.type.var.category.texinfo</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.begin.texinfo</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.end.texinfo</string>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>entity.other.inherited-class.texinfo</string>
								</dict>
								<key>5</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.begin.texinfo</string>
								</dict>
								<key>6</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.end.texinfo</string>
								</dict>
								<key>7</key>
								<dict>
									<key>name</key>
									<string>storage.type.var.data-type.texinfo</string>
								</dict>
								<key>8</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.begin.texinfo</string>
								</dict>
								<key>9</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.end.texinfo</string>
								</dict>
								<key>10</key>
								<dict>
									<key>name</key>
									<string>entity.name.var.texinfo</string>
								</dict>
								<key>11</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.begin.texinfo</string>
								</dict>
								<key>12</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.end.texinfo</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>include</key>
							<string>#param</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#main</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.command.$3.texinfo</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.texinfo</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.command.$3.line.texinfo</string>
					<key>begin</key>
					<string>((@)(deftypevarx|deftypevar))(?=\s|$)</string>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(?x)
\G \s* (({)[^}]*(})|\S+)
(?: \s+ (({)[^}]*(})|\S+))?</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>storage.type.var.data-type.texinfo</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.begin.texinfo</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.end.texinfo</string>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>entity.name.var.texinfo</string>
								</dict>
								<key>5</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.begin.texinfo</string>
								</dict>
								<key>6</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.end.texinfo</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>include</key>
							<string>#param</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#main</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.command.$3.texinfo</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.texinfo</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>ignored</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.command.ignore.block.texinfo</string>
					<key>contentName</key>
					<string>comment.block.ignored.texinfo</string>
					<key>begin</key>
					<string>((@)ignore)(?=\s|$)</string>
					<key>end</key>
					<string>((@)end\s+ignore)\b</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#main</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.command.ignore.texinfo</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.texinfo</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.command.end-ignore.texinfo</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.texinfo</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.command.bye.block.texinfo</string>
					<key>contentName</key>
					<string>comment.block.ignored.texinfo</string>
					<key>begin</key>
					<string>^((@)bye)(?=\s|$)</string>
					<key>end</key>
					<string>(?=A)B</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#main</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.command.bye.texinfo</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.texinfo</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>italicText</key>
		<dict>
			<key>name</key>
			<string>meta.command.$3.braced.texinfo</string>
			<key>contentName</key>
			<string>markup.italic.texinfo</string>
			<key>begin</key>
			<string>((@)(i|emph|sc|slanted))({)</string>
			<key>end</key>
			<string>}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#main</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.command.$3.texinfo</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.function.texinfo</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.begin.texinfo</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.end.texinfo</string>
				</dict>
			</dict>
		</dict>
		<key>lineCommands</key>
		<dict>
			<key>name</key>
			<string>meta.command.$3.line.texinfo</string>
			<key>contentName</key>
			<string>markup.raw.texinfo</string>
			<key>begin</key>
			<string>(?x) ^ ((@)
(author|centerchap|center|cindex|clear|defcodeindex|defcvx|defcv|deffnx
|deffn|defindex|definfoenclose|defivarx|defivar|defmacx|defmac|defmethodx
|defmethod|defoptx|defopt|defopx|defop|defspecx|defspec|deftpx|deftp
|deftypecvx|deftypecv|deftypefnx|deftypefn|deftypefunx|deftypefun
|deftypeivarx|deftypeivar|deftypemethodx|deftypemethod|deftypeopx
|deftypeop|deftypevarx|deftypevar|deftypevrx|deftypevr|defunx|defun
|defvarx|defvar|defvrx|defvr|dircategory|documentencoding|documentlanguage
|enumerate|evenfooting|even|everyfooting|everyexampleindent|exdent|findex
|firstparagraphindent|fonttextsize|footnotestyle|ftable|include|itemize
|kbdinputstyle|kindex|macro|multitable|need|node|oddfooting|oddpagesizes
|paragraphindent|part|pindex|printindex|setfilename|settitle|set
|shorttitlepage|sortas|sp|strong|subtitle|sub|sup|syncodeindex|synindex
|table|tindex|title|unmacro|urefbreakstyle|verbatiminclude|vindex|vskip|vtable))
(?=\s|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>entity.name.function.macro.texinfo</string>
					<key>match</key>
					<string>\G(?&lt;=@macro)\s*(\S+)</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\G(?:\s*[-+]?[0-9]+(?:\.[0-9]+)?,?)+(?=\s*$)</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>name</key>
									<string>constant.numeric.float.texinfo</string>
									<key>match</key>
									<string>[-+]?\d+(?:\.\d+)</string>
								</dict>
								<dict>
									<key>name</key>
									<string>constant.numeric.int.texinfo</string>
									<key>match</key>
									<string>[-+]?\d+</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#comma</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.command.separator.texinfo</string>
					<key>match</key>
					<string>(@)\|</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.texinfo</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>include</key>
					<string>#param</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comma</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#main</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.command.$3.texinfo</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.function.texinfo</string>
				</dict>
			</dict>
		</dict>
		<key>main</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dashes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#texLine</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#alias</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#menu</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#booleanCommands</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#symbolCommands</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#set</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#definitions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#quotation</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boldText</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#italicText</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#verbatim</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#codeBlocks</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#conditionals</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#blockCommands</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lineCommands</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#ignored</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#rawTex</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#rawHTML</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#rawXML</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#command</string>
				</dict>
			</array>
		</dict>
		<key>menu</key>
		<dict>
			<key>name</key>
			<string>meta.command.$3.block.texinfo</string>
			<key>begin</key>
			<string>((@)(detailmenu|direntry|menu))(?=\s|$)</string>
			<key>end</key>
			<string>((@)end\s+\3)\b</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>markup.list.texinfo</string>
					<key>begin</key>
					<string>^\*\s</string>
					<key>end</key>
					<string>^(?=\S)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>contentName</key>
							<string>entity.name.tag.entry-name.texinfo</string>
							<key>begin</key>
							<string>\G</string>
							<key>end</key>
							<string>::?|(?=\s*$)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#main</string>
								</dict>
							</array>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.separator.key-value.menu.texinfo</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>contentName</key>
							<string>entity.name.node-name.texinfo</string>
							<key>begin</key>
							<string>(?&lt;=[^:]:)\s*</string>
							<key>end</key>
							<string>(\.)|(?=\s*$)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#main</string>
								</dict>
							</array>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.terminator.full-stop.period.texinfo</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>name</key>
							<string>string.unquoted.description.texinfo</string>
							<key>begin</key>
							<string>(?&lt;=::|\.)</string>
							<key>end</key>
							<string>^(?=\S)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#main</string>
								</dict>
							</array>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.list.menu.texinfo</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.other.menu-comment.texinfo</string>
					<key>begin</key>
					<string>^(?=[^\s*])(?!@end\s)</string>
					<key>end</key>
					<string>$|(?=\s*@end\s)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#main</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#main</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.command.$3.texinfo</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.function.texinfo</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.command.end-$3.texinfo</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.function.texinfo</string>
				</dict>
			</dict>
		</dict>
		<key>param</key>
		<dict>
			<key>name</key>
			<string>variable.parameter.texinfo</string>
			<key>match</key>
			<string>[^\s{}@,]+|(?&lt;=\s)({)[^\s{}@,]+(})</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.begin.texinfo</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.end.texinfo</string>
				</dict>
			</dict>
		</dict>
		<key>quotation</key>
		<dict>
			<key>name</key>
			<string>meta.command.$3.block.texinfo</string>
			<key>contentName</key>
			<string>markup.quote.texinfo</string>
			<key>begin</key>
			<string>((@)(quotation|smallquotation))(?=\s|$)</string>
			<key>end</key>
			<string>((@)end\s+\3)\b</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#main</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.command.$3.texinfo</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.function.texinfo</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.command.end-$3.texinfo</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.function.texinfo</string>
				</dict>
			</dict>
		</dict>
		<key>rawHTML</key>
		<dict>
			<key>name</key>
			<string>meta.command.raw-html.block.texinfo</string>
			<key>contentName</key>
			<string>source.embedded.html</string>
			<key>begin</key>
			<string>((@)html)(?=\s|$)</string>
			<key>end</key>
			<string>((@)end\s+html)\b</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#main</string>
				</dict>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.command.html.texinfo</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.function.texinfo</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.command.end-html.texinfo</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.function.texinfo</string>
				</dict>
			</dict>
		</dict>
		<key>rawTex</key>
		<dict>
			<key>name</key>
			<string>meta.command.raw-tex.block.texinfo</string>
			<key>contentName</key>
			<string>source.embedded.tex</string>
			<key>begin</key>
			<string>((@)tex)(?=\s|$)</string>
			<key>end</key>
			<string>((@)end\s+tex)\b</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#main</string>
				</dict>
				<dict>
					<key>include</key>
					<string>text.tex.latex</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.command.tex.texinfo</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.function.texinfo</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.command.end-tex.texinfo</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.function.texinfo</string>
				</dict>
			</dict>
		</dict>
		<key>rawXML</key>
		<dict>
			<key>name</key>
			<string>meta.command.raw-$3.block.texinfo</string>
			<key>contentName</key>
			<string>source.embedded.xml</string>
			<key>begin</key>
			<string>((@)(docbook|xml))(?=\s|$)</string>
			<key>end</key>
			<string>((@)end\s+\3)\b</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#main</string>
				</dict>
				<dict>
					<key>include</key>
					<string>text.xml</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.command.$3.texinfo</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.function.texinfo</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.command.end-$3.texinfo</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.function.texinfo</string>
				</dict>
			</dict>
		</dict>
		<key>set</key>
		<dict>
			<key>begin</key>
			<string>((@)set)(?=\s|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\G\s*(\S+)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.var.texinfo</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#main</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>include</key>
					<string>#param</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#main</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.command.set.texinfo</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.function.texinfo</string>
				</dict>
			</dict>
		</dict>
		<key>symbolCommands</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.operator.command.non-alphabetic.texinfo</string>
					<key>match</key>
					<string>(@)[-!&quot;&apos;&amp;*./:=?@\\^`{}~]</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.texinfo</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.command.whitespace.texinfo</string>
					<key>match</key>
					<string>(@)(?:( |\t)|$)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.texinfo</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.command.braced.texinfo</string>
					<key>begin</key>
					<string>((@),)({)</string>
					<key>end</key>
					<string>}</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>constant.character.texinfo</string>
							<key>match</key>
							<string>[^\s{}@,]+</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comma</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#main</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.command.cedilla-accent.texinfo</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.texinfo</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.scope.begin.texinfo</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.scope.end.texinfo</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>verbatim</key>
		<dict>
			<key>name</key>
			<string>meta.command.braced.verb.texinfo</string>
			<key>contentName</key>
			<string>string.quoted.other.verbatim.texinfo</string>
			<key>begin</key>
			<string>((@)verb)({)([^}])</string>
			<key>end</key>
			<string>(\4)(})</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.command.verb.texinfo</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.function.texinfo</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.begin.texinfo</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.arbitrary.delimiter.begin.texinfo</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.end.texinfo</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.arbitrary.delimiter.end.texinfo</string>
				</dict>
			</dict>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>texinfo</string>
		<string>texi</string>
		<string>txi</string>
	</array>
</dict>
</plist>
