<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Turing</string>
	<key>scopeName</key>
	<string>source.turing</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#main</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>boolean</key>
		<dict>
			<key>name</key>
			<string>constant.language.boolean.$1.turing</string>
			<key>match</key>
			<string>\b(true|false)\b</string>
		</dict>
		<key>case</key>
		<dict>
			<key>name</key>
			<string>meta.scope.case-block.turing</string>
			<key>begin</key>
			<string>^\s*(case)\s+(\w+)\s+(of)\b</string>
			<key>end</key>
			<string>^\s*(end\s+case)\b</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#label</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.scope.begin.turing</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.case.turing</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.turing</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.of.turing</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.scope.end.turing</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.end.case.turing</string>
				</dict>
			</dict>
		</dict>
		<key>cc</key>
		<dict>
			<key>name</key>
			<string>meta.preprocessor.$3.turing</string>
			<key>match</key>
			<string>^\s*((#)((?:end\s+)?if|elsif|else))</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.directive.conditional.turing</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.directive.turing</string>
				</dict>
			</dict>
		</dict>
		<key>class</key>
		<dict>
			<key>name</key>
			<string>meta.scope.$1-block.turing</string>
			<key>begin</key>
			<string>^\s*(class|module|monitor)\s+(\w+)</string>
			<key>end</key>
			<string>\b(end)\s+(\2)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#class-innards</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.scope.begin.turing</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.$1.turing</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.class.turing</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.scope.end.turing</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.end.turing</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.class.turing</string>
				</dict>
			</dict>
		</dict>
		<key>class-innards</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(import|export)\b</string>
					<key>end</key>
					<string>(?=$|%|/\*)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#list</string>
						</dict>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.$1.turing</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.other.inherited-class.turing</string>
					<key>begin</key>
					<string>\b(inherit)\b</string>
					<key>end</key>
					<string>\w+</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.inherit.turing</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>entity.other.inherited-class.turing</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.other.$1.turing</string>
					<key>begin</key>
					<string>\b(implement(?:\s+by)?)\b</string>
					<key>end</key>
					<string>\w+</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.implements.turing</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>entity.other.inherited-class.turing</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>comment.line.percentage.turing</string>
					<key>begin</key>
					<string>%</string>
					<key>end</key>
					<string>$</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.turing</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>comment.block.bracketed.turing</string>
					<key>begin</key>
					<string>/\*</string>
					<key>end</key>
					<string>\*/</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.turing</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.turing</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>escapes</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.character.escape.double-quote.turing</string>
					<key>match</key>
					<string>\\&quot;</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.escape.single-quote.turing</string>
					<key>match</key>
					<string>\\&apos;</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.escape.newline.turing</string>
					<key>match</key>
					<string>\\[nN]</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.escape.tab.turing</string>
					<key>match</key>
					<string>\\[tT]</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.escape.form-feed.turing</string>
					<key>match</key>
					<string>\\[fF]</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.escape.return.turing</string>
					<key>match</key>
					<string>\\[rR]</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.escape.backspace.turing</string>
					<key>match</key>
					<string>\\[bB]</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.escape.esc.turing</string>
					<key>match</key>
					<string>\\[eE]</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.escape.backslash.turing</string>
					<key>match</key>
					<string>\\\\</string>
				</dict>
			</array>
		</dict>
		<key>for</key>
		<dict>
			<key>name</key>
			<string>meta.scope.for-loop.turing</string>
			<key>begin</key>
			<string>^\s*(for)\b(?:\s+(decreasing)\b)?</string>
			<key>end</key>
			<string>^\s*(end)\s+(for)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\G(.*?)\b(by)\b</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>$self</string>
								</dict>
							</array>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.by.turing</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.scope.begin.turing</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.for.turing</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.decreasing.turing</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.scope.end.turing</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.end.turing</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.for.turing</string>
				</dict>
			</dict>
		</dict>
		<key>forward</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.$1.procedure.turing</string>
					<key>begin</key>
					<string>^\s*\b(deferred|forward)\s+(procedure|proc)\s+(\w+)</string>
					<key>end</key>
					<string>(?=$|%|/\*)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#parameters</string>
						</dict>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.$1.turing</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.type.function.turing</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.turing</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.$1.function.turing</string>
					<key>begin</key>
					<string>^\s*\b(deferred|forward)\s+(function|fcn)\s+(\w+)</string>
					<key>end</key>
					<string>(?=$|%|/\*)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#parameters</string>
						</dict>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.$1.turing</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.type.function.turing</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.turing</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>function</key>
		<dict>
			<key>name</key>
			<string>meta.function.turing</string>
			<key>begin</key>
			<string>(?x)
\b
(?:
	(body)          # 1: storage.modifier.body.turing
	\s+
)?
(function|fcn)      # 2: storage.type.turing
(?:
	\s+
	(pervasive|\*) # 3: storage.modifier.pervasive.turing
)?
\s+
(\w+)              # 4: entity.name.function.turing
\s*
(                   # 5: meta.function.parameters.turing
	(\()           # 6: punctuation.definition.parameters.begin.turing
	(.*)            # 7: include: “#param-declarations”
	(\))           # 8: punctuation.definition.parameters.end.turing
)
\s*
(:)                 # 9: punctuation.separator.key-value.turing
\s*
(\w+)              # 10: storage.type.type-spec.turing</string>
			<key>end</key>
			<string>\b(end)\s+(\4)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.$1-function.turing</string>
					<key>begin</key>
					<string>^\s*(pre|init|post)(?=\s|$)</string>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.function.$1.turing</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.body.turing</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.turing</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.pervasive.turing</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.turing</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>meta.function.parameters.turing</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.turing</string>
				</dict>
				<key>7</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#param-declarations</string>
						</dict>
					</array>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.end.turing</string>
				</dict>
				<key>9</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.key-value.turing</string>
				</dict>
				<key>10</key>
				<dict>
					<key>name</key>
					<string>storage.type.type-spec.turing</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.end.turing</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.turing</string>
				</dict>
			</dict>
		</dict>
		<key>function-call</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.function-call.turing</string>
					<key>contentName</key>
					<string>meta.function-call.arguments.turing</string>
					<key>begin</key>
					<string>(([\w.]+))\s*(\()</string>
					<key>end</key>
					<string>\)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.function.name.turing</string>
						</dict>
						<key>2</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#function-name</string>
								</dict>
							</array>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.arguments.begin.turing</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.arguments.end.turing</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.function-call.turing</string>
					<key>match</key>
					<string>^\s*(([\w.]+))\s*(?=$|%|/\*)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.function.name.turing</string>
						</dict>
						<key>2</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#function-name</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>function-name</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#stdlib</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.separator.method.turing</string>
					<key>match</key>
					<string>\.</string>
				</dict>
			</array>
		</dict>
		<key>handler</key>
		<dict>
			<key>name</key>
			<string>meta.scope.handler.turing</string>
			<key>begin</key>
			<string>^\s*(handler)\s*(\()\s*(\w+)\s*(\))</string>
			<key>end</key>
			<string>^\s*(end)\s+(handler)\b</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.scope.begin.turing</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.handler.turing</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.arguments.begin.turing</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.handler.turing</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.arguments.end.turing</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.scope.end.turing</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.end.turing</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.handler.turing</string>
				</dict>
			</dict>
		</dict>
		<key>if</key>
		<dict>
			<key>name</key>
			<string>meta.scope.if-block.turing</string>
			<key>begin</key>
			<string>^\s*(if)\b</string>
			<key>end</key>
			<string>^\s*(end\s+if)\b</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.scope.begin.turing</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.conditional.turing</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.scope.end.turing</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.conditional.turing</string>
				</dict>
			</dict>
		</dict>
		<key>keyboard-constants</key>
		<dict>
			<key>name</key>
			<string>support.constant.keyboard.turing</string>
			<key>match</key>
			<string>(?x)\b(?:
(?:KEY|ORD)_(?:
	F1[0-2]|F[1-9]|CTRL_[A-Z]|ALT_[A-Z0-9]|(?:CTRL|ALT|SHIFT)_(?:F1[0-2]|F[1-9])|
	ALT(?:_EQUALS|_MINUS)?|BACK_TAB|BACKSPACE|CTRL|DELETE|END|ENTER|ESC|HOME|INSERT|KEYPAD_5|PGDN|PGUP|SHIFT|SHIFT_TAB|TAB|
	CTRL_(?:BACKSLASH|BACKSPACE|CARET|(?:UP|RIGHT|LEFT|DOWN)_ARROW|CLOSE_BRACKET|DELETE|END|HOME|INSERT|OPEN_BRACKET|PGDN|PGUP|UNDERSCORE)|
	(?:UP|RIGHT|LEFT|DOWN)_ARROW)
|
ORD_(?:
	AMPERSAND|APOSTROPHE|ASTERISK|BACKSLASH|BAR|CARET|COLON|COMMA|DOT|EQUALS|(?:GREATER|LESS)_THAN|
	(?:CLOSE|OPEN)_(?:BRACE|BRACKET|PARENTHESIS)|(?:EXCALAMATION|HAS|QUESTION|QUOTATION)_MARK|MINUS|
	(?:AT|DOLLAR|PERCENT)_SIGN|PERIOD|PLUS|SEMICOLON|SINGLE_QUOTE|SLASH|SPACE|TILDE|UNDERSCORE|[A-Z0-9]|LOWER_[A-Z])
)\b</string>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.control.$1.turing</string>
					<key>match</key>
					<string>(?:^\s*)?+\b((?:end\s+)?if|then|elsif|else|(?:end\s+)?loop|exit|when|include|in|end)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.logical.$1.turing</string>
					<key>match</key>
					<string>\b(and|not|x?or)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.$1.turing</string>
					<key>match</key>
					<string>\b(all|bits|div|lower|mod|nil|rem|shl|shr|unit|upper)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.other.statement.$1.turing</string>
					<key>match</key>
					<string>\b(assert|begin|break|close|exit|fork|free|get|init|invariant|new|objectclass|open|pause|put|quit|read|result|return|seek|signal|tag|tell|wait|write)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>storage.type.$3-char.turing</string>
					<key>match</key>
					<string>\b(char)\s*(\()(\d+)(\))</string>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.arguments.begin.turing</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.arguments.end.turing</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.other.colour.turing</string>
					<key>match</key>
					<string>(?x)\b
(black|blue|brightblue|brightcyan|brightgreen|brightmagenta|brightpurple|brightred
|brightwhite|brown|colou?r[bf]g|cyan|darkgr[ae]y|gr[ae]y|green|magenta|purple|red
|white|yellow)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.$1.turing</string>
					<key>match</key>
					<string>\b(skip|self)\b</string>
				</dict>
			</array>
		</dict>
		<key>label</key>
		<dict>
			<key>name</key>
			<string>meta.label.turing</string>
			<key>begin</key>
			<string>\b(label)\b</string>
			<key>end</key>
			<string>:</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#list</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.statement.label.turing</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.key-value.turing</string>
				</dict>
			</dict>
		</dict>
		<key>list</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>variable.name.turing</string>
					<key>match</key>
					<string>\w+</string>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.delimiter.object.comma.turing</string>
					<key>match</key>
					<string>,</string>
				</dict>
			</array>
		</dict>
		<key>main</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numbers</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#for</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cc</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#if</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#case</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#types</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#modifiers</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variables</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#punctuation</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#forward</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#procedure</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#process</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#handler</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#class</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#type</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#record</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#union</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function-call</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#stdlib</string>
				</dict>
			</array>
		</dict>
		<key>math-routines</key>
		<dict>
			<key>name</key>
			<string>support.function.${1:/downcase}.turing</string>
			<key>match</key>
			<string>\b(abs|arccos|arccosd|arcsin|arcsind|arctan|arctand|cos|cosd|exp|ln|max|min|sign|sin|sind|tan|tand|sqrt)\b</string>
		</dict>
		<key>modifiers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>storage.modifier.$1.compiler-directive.oot.turing</string>
					<key>match</key>
					<string>\b(unchecked|checked)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>storage.modifier.unqualified.turing</string>
					<key>match</key>
					<string>\b(unqualified|~\.)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>storage.modifier.$1.turing</string>
					<key>match</key>
					<string>\b(external|flexible|opaque|register)\b</string>
				</dict>
			</array>
		</dict>
		<key>modules</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(Concurrency)\b(?:(\.)(empty|[gs]etpriority|simutime)?\b)?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.class.${1:/downcase}.turing</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.delimiter.property.period.turing</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.function.$3.turing</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(Config)\b(?:(\.)(Display|Lang|Machine)?\b)?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.class.${1:/downcase}.turing</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.delimiter.property.period.turing</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.function.${3:/downcase}.turing</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(Dir)\b(?:(\.)(Change|Close|Create|Current|Delete|Get|GetLong|Open)?\b)?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.class.${1:/downcase}.turing</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.delimiter.property.period.turing</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.function.${3:/downcase}.turing</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(Draw)\b(?:(\.)(Arc|Box|Cls|Dot|Fill|FillArc|FillBox|FillMapleLeaf|FillOval|FillPolygon|FillStar|Line|MapleLeaf|Oval|Polygon|Star|Text)?\b)?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.class.${1:/downcase}.turing</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.delimiter.property.period.turing</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.function.${3:/downcase}.turing</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(Error)\b(?:(\.)(Last|LastMsg|LastStr|Msg|Str|Trip)?\b)?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.class.${1:/downcase}.turing</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.delimiter.property.period.turing</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.function.${3:/downcase}.turing</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(ErrorNum|Exceptions)\b(?:(\.)(\w+)?\b)?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.class.${1:/downcase}.turing</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.delimiter.property.period.turing</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.function.${3:/downcase}.turing</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(File)\b(?:(\.)(Copy|Delete|DiskFree|Exists|Rename|Status)?\b)?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.class.${1:/downcase}.turing</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.delimiter.property.period.turing</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.function.${3:/downcase}.turing</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(Font)\b(?:(\.)(Draw|Free|GetName|GetSize|GetStyle|Name|New|Sizes|StartName|StartSize|Width)?\b)?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.class.${1:/downcase}.turing</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.delimiter.property.period.turing</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.function.${3:/downcase}.turing</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>(?x)\b(GUI)\b(?:(\.)
(AddLine|AddText|Alert|Alert2|Alert3|AlertFull|Choose|ChooseFull|ClearText|CloseWindow|CreateButton|CreateButtonFull
|CreateCanvas|CreateCanvasFull|CreateCheckBox|CreateCheckBoxFull|CreateFrame|CreateHorizontalScrollBar|CreateHorizontalScrollBarFull
|CreateHorizontalSlider|CreateLabel|CreateLabelFull|CreateLabelledFrame|CreateLine|CreateMenu|CreateMenuItem|CreateMenuItemFull
|CreatePicture|CreatePictureButton|CreatePictureButtonFull|CreatePictureRadioButton|CreatePictureRadioButtonFull|CreateRadioButton
|CreateRadioButtonFull|CreateTextBox|CreateTextBoxFull|CreateTextField|CreateTextFieldFull|CreateVerticalScrollBar|CreateVerticalScrollBarFull
|CreateVerticalSlider|Disable|Dispose|DrawArc|DrawBox|DrawCls|DrawDot|DrawFill|DrawFillArc|DrawFillBox|DrawFillMapleLeaf|DrawFillOval
|DrawFillPolygon|DrawFillStar|DrawLine|DrawMapleLeaf|DrawOval|DrawPolygon|DrawStar|DrawText|Enable|FontDraw|GetCheckBox|GetEventTime
|GetEventWidgetID|GetEventWindow|GetHeight|GetMenuBarHeight|GetScrollBarWidth|GetSliderValue|GetText|GetVersion|GetWidth|GetX|GetY|Hide
|HideMenuBar|OpenFile|OpenFileFull|PicDraw|PicNew|PicScreenLoad|PicScreenSave|ProcessEvent|Quit|Refresh|SaveFile|SaveFileFull|SelectRadio
|SetActive|SetBackgroundColor|SetBackgroundColour|SetCheckBox|SetDefault|SetDisplayWhenCreated|SetKeyEventHandler|SetLabel|SetMouseEventHandler
|SetNullEventHandler|SetPosition|SetPositionAndSize|SetScrollAmount|SetSelection|SetSize|SetSliderMinMax|SetSliderReverse|SetSliderSize
|SetSliderValue|SetText|SetXOR|Show|ShowMenuBar)?\b)?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.class.${1:/downcase}.turing</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.delimiter.property.period.turing</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.function.${3:/downcase}.turing</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(Input)\b(?:(\.)(getch|getchar|hasch|KeyDown|Pause)?\b)?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.class.${1:/downcase}.turing</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.delimiter.property.period.turing</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.function.${3:/downcase}.turing</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(Joystick)\b(?:(\.)(GetInfo)?\b)?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.class.${1:/downcase}.turing</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.delimiter.property.period.turing</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.function.${3:/downcase}.turing</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(Keyboard)\b(?:(\.)(\w+)?\b)?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.class.${1:/downcase}.turing</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.delimiter.property.period.turing</string>
						</dict>
						<key>3</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#keyboard-constants</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(Limits)\b(?:(\.)(DefaultFW|DefaultEW|minint|maxint|minnat|maxnat)?\b)?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.class.${1:/downcase}.turing</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.delimiter.property.period.turing</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.function.${3:/downcase}.turing</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>(?x)\b(Math)\b(?:(\.)(?:(PI|E)|(Distance|DistancePointLine)|(\w+))?\b)?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.class.${1:/downcase}.turing</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.delimiter.property.period.turing</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant.${3:/downcase}.turing</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>support.function.${4:/downcase}.turing</string>
						</dict>
						<key>5</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#math-routines</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(Mouse)\b(?:(\.)(ButtonChoose|ButtonMoved|ButtonWait|Where)?\b)?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.class.${1:/downcase}.turing</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.delimiter.property.period.turing</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.function.${3:/downcase}.turing</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(Music)\b(?:(\.)(Play|PlayFile|PlayFileStop|Sound|SoundOff)?\b)?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.class.${1:/downcase}.turing</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.delimiter.property.period.turing</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.function.${3:/downcase}.turing</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>(?x)
\b(Net)\b(?:(\.)
(BytesAvailable|CharAvailable|CloseConnection|HostAddressFromName|HostNameFromAddress
|LineAvailable|LocalAddress|LocalName|OpenConnection|OpenURLConnection|TokenAvailable
|WaitForConnection)?\b)?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.class.${1:/downcase}.turing</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.delimiter.property.period.turing</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.function.${3:/downcase}.turing</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(PC)\b(?:(\.)(ParallelGet|ParallelPut)?\b)?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.class.${1:/downcase}.turing</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.delimiter.property.period.turing</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.function.${3:/downcase}.turing</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>(?x)
\b(Pic)\b(?:(\.)
(Blend|Blur|Draw|DrawFrames|DrawFramesBack|DrawSpecial|DrawSpecialBack|FileNew
|FileNewFrames|Flip|Frames|Free|Height|Mirror|New|Rotate|Save|Scale|ScreenLoad
|ScreenSave|SetTransparentColou?r|Width)?
\b)?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.class.${1:/downcase}.turing</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.delimiter.property.period.turing</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.function.${3:/downcase}.turing</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(Rand)\b(?:(\.)(Int|Next|Real|Reset|Seed|Set)?\b)?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.class.${1:/downcase}.turing</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.delimiter.property.period.turing</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.function.${3:/downcase}.turing</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(RGB)\b(?:(\.)(AddColou?r|[GS]etColou?r|maxcolou?r)?\b)?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.class.${1:/downcase}.turing</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.delimiter.property.period.turing</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.function.${3:/downcase}.turing</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(Sprite)\b(?:(\.)(Animate|ChangePic|Free|Hide|New|SetFrameRate|SetHeight|SetPosition|Show)?\b)?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.class.${1:/downcase}.turing</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.delimiter.property.period.turing</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.function.${3:/downcase}.turing</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(Stream)\b(?:(\.)(eof|Flush|FlushAll)?\b)?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.class.${1:/downcase}.turing</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.delimiter.property.period.turing</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.function.${3:/downcase}.turing</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(Str)\b(?:(\.)(\w+)?\b)?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.class.${1:/downcase}.turing</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.delimiter.property.period.turing</string>
						</dict>
						<key>3</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#str-routines</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(Sys)\b(?:(\.)(Exec|FetchArg|GetComputerName|GetEnv|GetPid|GetUserName|Nargs)?\b)?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.class.${1:/downcase}.turing</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.delimiter.property.period.turing</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.function.${3:/downcase}.turing</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(Text)\b(?:(\.)(Cls|Colou?r|Colou?rBack|Locate|LocateXY|maxcol|maxrow|WhatCol|WhatColou?r|WhatColou?rBack|WhatRow)?\b)?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.class.${1:/downcase}.turing</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.delimiter.property.period.turing</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.function.${3:/downcase}.turing</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(Time)\b(?:(\.)(Date|DateSec|Delay|Elapsed|ElapsedCPU|PartsSec|Sec|SecDate|SecParts)?\b)?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.class.${1:/downcase}.turing</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.delimiter.property.period.turing</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.function.${3:/downcase}.turing</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(TypeConv)\b(?:(\.)(\w+)?\b)?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.class.${1:/downcase}.turing</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.delimiter.property.period.turing</string>
						</dict>
						<key>3</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#typeconv-routines</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(View)\b(?:(\.)(ClipAdd|ClipOff|ClipSet|maxcolou?r|maxx|maxy|Set|Update|WhatDotColou?r)?\b)?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.class.${1:/downcase}.turing</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.delimiter.property.period.turing</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.function.${3:/downcase}.turing</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(Window)\b(?:(\.)(Close|GetActive|GetPosition|GetSelect|Hide|Open|Select|Set|SetActive|SetPosition|Show|Update)?\b)?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.class.${1:/downcase}.turing</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.delimiter.property.period.turing</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.function.${3:/downcase}.turing</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>numbers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.numeric.base-16.hex.turing</string>
					<key>match</key>
					<string>16#[A-Fa-f0-9]+</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.base-$1.turing</string>
					<key>match</key>
					<string>(\d+)#\d+</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.float.turing</string>
					<key>match</key>
					<string>\b\d+\.\d+(?:[Ee][\+\-]?\d+)?\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.int.turing</string>
					<key>match</key>
					<string>\b\d+\b</string>
				</dict>
			</array>
		</dict>
		<key>param-declarations</key>
		<dict>
			<key>match</key>
			<string>\b(\w+)\s+(:)\s+((\w+))</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.function.turing</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.turing</string>
				</dict>
				<key>3</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#types</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>parameters</key>
		<dict>
			<key>name</key>
			<string>meta.function.parameters.turing</string>
			<key>begin</key>
			<string>\G\s*(\()</string>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>name</key>
					<string>variable.parameter.function.turing</string>
					<key>match</key>
					<string>\w+</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.arguments.begin.turing</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.arguments.end.turing</string>
				</dict>
			</dict>
		</dict>
		<key>procedure</key>
		<dict>
			<key>name</key>
			<string>meta.scope.procedure.turing</string>
			<key>begin</key>
			<string>^\s*(?:(body)\s+)?(procedure|proc)\s+(\w+)</string>
			<key>end</key>
			<string>^\s*(end)\s+(\3)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#parameters</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.scope.begin.turing</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.$1.turing</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.turing</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.turing</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.scope.end.turing</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.end.turing</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.turing</string>
				</dict>
			</dict>
		</dict>
		<key>process</key>
		<dict>
			<key>name</key>
			<string>meta.scope.process.turing</string>
			<key>begin</key>
			<string>^\s*(process)(?:\s+(pervasive|\*)(?=\s))?\s+(\w+)</string>
			<key>end</key>
			<string>^\s*(end)\s+(\3)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#parameters</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.scope.begin.turing</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.turing</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.pervasive.turing</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.turing</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.scope.end.turing</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.end.turing</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.turing</string>
				</dict>
			</dict>
		</dict>
		<key>punctuation</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>punctuation.definition.range.turing</string>
					<key>match</key>
					<string>\.\.</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.separator.key-value.assignment.turing</string>
					<key>match</key>
					<string>:=</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.separator.class.accessor.turing</string>
					<key>match</key>
					<string>-&gt;</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.arithmetic.add.turing</string>
					<key>match</key>
					<string>\+</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.arithmetic.subtract.turing</string>
					<key>match</key>
					<string>-</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.arithmetic.multiply.turing</string>
					<key>match</key>
					<string>\*</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.arithmetic.divide.turing</string>
					<key>match</key>
					<string>\/</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.logical.equal-or-less.subset.turing</string>
					<key>match</key>
					<string>&lt;=</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.logical.equal-or-greater.superset.turing</string>
					<key>match</key>
					<string>&gt;=</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.logical.less.turing</string>
					<key>match</key>
					<string>&lt;</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.logical.greater.turing</string>
					<key>match</key>
					<string>&gt;</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.logical.equal.turing</string>
					<key>match</key>
					<string>=</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.logical.not.turing</string>
					<key>match</key>
					<string>not=|~=</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.pointer-following.turing</string>
					<key>match</key>
					<string>\^</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.type-cheat.turing</string>
					<key>match</key>
					<string>#</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.indirection.turing</string>
					<key>match</key>
					<string>@</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.separator.key-value.turing</string>
					<key>match</key>
					<string>:</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.definition.arguments.begin.turing</string>
					<key>match</key>
					<string>\(</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.definition.arguments.end.turing</string>
					<key>match</key>
					<string>\)</string>
				</dict>
			</array>
		</dict>
		<key>record</key>
		<dict>
			<key>name</key>
			<string>meta.scope.record-block.turing</string>
			<key>begin</key>
			<string>^\s*(record)\b</string>
			<key>end</key>
			<string>^\s*(end)\s+(record)\b</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>((\s*\w+\s*,?)+)(:)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#list</string>
								</dict>
							</array>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.record.key-value.turing</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.scope.begin.turing</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.record.turing</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.scope.end.turing</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.end.turing</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.record.turing</string>
				</dict>
			</dict>
		</dict>
		<key>stdlib</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#modules</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#stdproc</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.class.anyclass.turing</string>
					<key>match</key>
					<string>\b(anyclass)\b</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keyboard-constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#math-routines</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#str-routines</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#typeconv-routines</string>
				</dict>
			</array>
		</dict>
		<key>stdproc</key>
		<dict>
			<key>name</key>
			<string>support.function.${1:/downcase}.turing</string>
			<key>match</key>
			<string>(?x)\b
(addr|buttonchoose|buttonmoved|buttonwait|clock|cls|colou?r|colou?rback|date|delay|drawarc|drawbox|drawdot
|drawfill|drawfillarc|drawfillbox|drawfillmapleleaf|drawfilloval|drawfillpolygon|drawfillstar|drawline
|drawmapleleaf|drawoval|drawpic|drawpolygon|drawstar|empty|eof|fetcharg|getch|getchar|getenv|getpid
|getpriority|hasch|locate|locatexy|maxcol|maxcolou?r|maxint|maxnat|maxrow|maxx|maxy|minint|minnat
|mousewhere|nargs|parallelget|parallelput|play|playdone|pred|rand|randint|randnext|randomize
|randseed|setpriority|setscreen|simutime|sizeof|sizepic|sound|succ|sysclock|takepic|time|wallclock
|whatcol|whatcolou?r|whatcolou?rback|whatdotcolou?r|whatrow)\b</string>
		</dict>
		<key>str-routines</key>
		<dict>
			<key>name</key>
			<string>support.function.${1:/downcase}.turing</string>
			<key>match</key>
			<string>\b(Lower|Upper|Trim|index|length|repeat)\b</string>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>string.quoted.double.turing</string>
					<key>begin</key>
					<string>&quot;</string>
					<key>end</key>
					<string>&quot;</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escapes</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>name</key>
					<string>string.quoted.single.turing</string>
					<key>begin</key>
					<string>&apos;</string>
					<key>end</key>
					<string>&apos;</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escapes</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>type</key>
		<dict>
			<key>match</key>
			<string>\b(type)(?:\s+(pervasive|\*)(?=\s))?\s+(\w+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.turing</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.pervasive.turing</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.turing</string>
				</dict>
			</dict>
		</dict>
		<key>typeconv-routines</key>
		<dict>
			<key>name</key>
			<string>support.function.${1:/downcase}.turing</string>
			<key>match</key>
			<string>\b(ceil|chr|erealstr|floor|frealstr|intreal|intstr|natreal|natstr|ord|realstr|round|strint|strintok|strnat|strnatok|strreal|strrealok)\b</string>
		</dict>
		<key>types</key>
		<dict>
			<key>name</key>
			<string>storage.type.$1-type.turing</string>
			<key>match</key>
			<string>\b(addressint|array|boolean|char|collection|enum|int[124]?|nat[124]?|real[48]?|pointer\s+to|set\s+of|string)\b</string>
		</dict>
		<key>union</key>
		<dict>
			<key>name</key>
			<string>meta.scope.union.turing</string>
			<key>begin</key>
			<string>^\s*(union)\s+(\w+)\s*(:)(.*)\b(of)\b</string>
			<key>end</key>
			<string>^\s*(end)\s+(union)\b</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#label</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.scope.begin.turing</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.union.turing</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.union.turing</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.key-value.turing</string>
				</dict>
				<key>4</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.of.turing</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.scope.end.turing</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.end.turing</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.union.turing</string>
				</dict>
			</dict>
		</dict>
		<key>variables</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.variable-declaration.turing</string>
					<key>begin</key>
					<string>\b(var|const)\s+</string>
					<key>end</key>
					<string>(:=?)\s*((?!\d)((?:\w+(?:\s+to)?)(?:\s*\(\s*\d+\s*\))?))?\s*(:=)?</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\G(?:\s*(pervasive|\*)(?=\s))?\s*(register)(?=\s)</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>storage.modifier.pervasive.oot.turing</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>storage.modifier.register.oot.turing</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>include</key>
							<string>#types</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#list</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.$1.turing</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.key-value.turing</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.type.type-spec.turing</string>
						</dict>
						<key>3</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#types</string>
								</dict>
							</array>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.key-value.turing</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.variable-assignment.turing</string>
					<key>begin</key>
					<string>(\w+)\s*(:=)</string>
					<key>end</key>
					<string>(?=\S)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.name.turing</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.key-value.turing</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.binding.turing</string>
					<key>begin</key>
					<string>\b(bind)\b</string>
					<key>end</key>
					<string>(?=$|%|/\*)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>\b(var)\b</string>
							<key>end</key>
							<string>\b(to)\b</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#list</string>
								</dict>
							</array>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>storage.type.$1.turing</string>
								</dict>
							</dict>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.to.turing</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>include</key>
							<string>#list</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.bind.turing</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>t</string>
		<string>tu</string>
	</array>
</dict>
</plist>
