<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>HTML (Twig)</string>
	<key>scopeName</key>
	<string>text.html.twig</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>name</key>
			<string>meta.tag.any.html</string>
			<key>begin</key>
			<string>(&lt;)([a-zA-Z0-9:]++)(?=[^&gt;]*&gt;&lt;/\2&gt;)</string>
			<key>end</key>
			<string>(&gt;(&lt;)/)(\2)(&gt;)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-stuff</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.html</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.html</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.html</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.scope.between-tag-pair.html</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.html</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.html</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.tag.preprocessor.xml.html</string>
			<key>begin</key>
			<string>(&lt;\?)(xml)</string>
			<key>end</key>
			<string>(\?&gt;)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-generic-attribute</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-double-quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-single-quoted</string>
				</dict>
			</array>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.html</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.xml.html</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>comment.block.html</string>
			<key>begin</key>
			<string>&lt;!--</string>
			<key>end</key>
			<string>--\s*&gt;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>invalid.illegal.bad-comments-or-CDATA.html</string>
					<key>match</key>
					<string>--</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded-code</string>
				</dict>
			</array>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.html</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.tag.sgml.html</string>
			<key>begin</key>
			<string>&lt;!</string>
			<key>end</key>
			<string>&gt;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.tag.sgml.doctype.html</string>
					<key>begin</key>
					<string>(?i:DOCTYPE)</string>
					<key>end</key>
					<string>(?=&gt;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>string.quoted.double.doctype.identifiers-and-DTDs.html</string>
							<key>match</key>
							<string>&quot;[^&quot;&gt;]*&quot;</string>
						</dict>
					</array>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.doctype.html</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.other.inline-data.html</string>
					<key>begin</key>
					<string>\[CDATA\[</string>
					<key>end</key>
					<string>]](?=&gt;)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>invalid.illegal.bad-comments-or-CDATA.html</string>
					<key>match</key>
					<string>(\s*)(?!--|&gt;)\S(\s*)</string>
				</dict>
			</array>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.html</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>include</key>
			<string>#embedded-code</string>
		</dict>
		<dict>
			<key>name</key>
			<string>source.css.embedded.html</string>
			<key>begin</key>
			<string>(?:^\s+)?(&lt;)((?i:style))\b(?![^&gt;]*/&gt;)</string>
			<key>end</key>
			<string>(&lt;/)((?i:style))(&gt;)(?:\s*\n)?</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-stuff</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(&gt;)</string>
					<key>end</key>
					<string>(?=&lt;/(?i:style))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#embedded-code</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.css</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.html</string>
						</dict>
					</dict>
				</dict>
			</array>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.html</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.style.html</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.html</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>source.js.embedded.html</string>
			<key>begin</key>
			<string>(?:^\s+)?(&lt;)((?i:script))\b(?![^&gt;]*/&gt;)</string>
			<key>end</key>
			<string>(?&lt;=&lt;/(script|SCRIPT))(&gt;)(?:\s*\n)?</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-stuff</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;!&lt;/(?:script|SCRIPT))(&gt;)</string>
					<key>end</key>
					<string>(&lt;/)((?i:script))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>comment.line.double-slash.js</string>
							<key>match</key>
							<string>(//).*?((?=&lt;/script)|$\n?)</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.comment.js</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>name</key>
							<string>comment.block.js</string>
							<key>begin</key>
							<string>/\*</string>
							<key>end</key>
							<string>\*/|(?=&lt;/script)</string>
							<key>captures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.comment.js</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>include</key>
							<string>#php</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#twig-print-tag</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#twig-statement-tag</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#twig-comment-tag</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.html</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.script.html</string>
						</dict>
					</dict>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.html</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.script.html</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.html</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.tag.structure.any.html</string>
			<key>begin</key>
			<string>(&lt;/?)((?i:body|head|html)\b)</string>
			<key>end</key>
			<string>(&gt;)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-stuff</string>
				</dict>
			</array>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.html</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.structure.any.html</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.tag.block.any.html</string>
			<key>begin</key>
			<string>(&lt;/?)((?i:address|blockquote|dd|div|dl|dt|fieldset|form|frame|frameset|h1|h2|h3|h4|h5|h6|iframe|noframes|object|ol|p|ul|applet|center|dir|hr|menu|pre)\b)</string>
			<key>end</key>
			<string>(&gt;)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-stuff</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.html</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.block.any.html</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.html</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.tag.inline.any.html</string>
			<key>begin</key>
			<string>(&lt;/?)((?i:a|abbr|acronym|area|b|base|basefont|bdo|big|br|button|caption|cite|code|col|colgroup|del|dfn|em|font|head|html|i|img|input|ins|isindex|kbd|label|legend|li|link|map|meta|noscript|optgroup|option|param|q|s|samp|script|select|small|span|strike|strong|style|sub|sup|table|tbody|td|textarea|tfoot|th|thead|title|tr|tt|u|var)\b)</string>
			<key>end</key>
			<string>((?: ?/)?&gt;)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-stuff</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.html</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.inline.any.html</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.html</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.tag.other.html</string>
			<key>begin</key>
			<string>(&lt;/?)([a-zA-Z0-9:]+)</string>
			<key>end</key>
			<string>(&gt;)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-stuff</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.html</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.other.html</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.html</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>include</key>
			<string>#entities</string>
		</dict>
		<dict>
			<key>name</key>
			<string>invalid.illegal.incomplete.html</string>
			<key>match</key>
			<string>&lt;&gt;</string>
		</dict>
		<dict>
			<key>name</key>
			<string>invalid.illegal.bad-angle-bracket.html</string>
			<key>match</key>
			<string>&lt;</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#twig-print-tag</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#twig-statement-tag</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#twig-comment-tag</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>embedded-code</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#ruby</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#php</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-print-tag</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-statement-tag</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-comment-tag</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#python</string>
				</dict>
			</array>
		</dict>
		<key>entities</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.character.entity.html</string>
					<key>match</key>
					<string>(&amp;)([a-zA-Z0-9]+|#[0-9]+|#x[0-9a-fA-F]+)(;)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entity.html</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entity.html</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>invalid.illegal.bad-ampersand.html</string>
					<key>match</key>
					<string>&amp;</string>
				</dict>
			</array>
		</dict>
		<key>php</key>
		<dict>
			<key>begin</key>
			<string>(?=(^\s*)?&lt;\?)</string>
			<key>end</key>
			<string>(?!(^\s*)?&lt;\?)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.php</string>
				</dict>
			</array>
		</dict>
		<key>python</key>
		<dict>
			<key>name</key>
			<string>source.python.embedded.html</string>
			<key>begin</key>
			<string>(?:^\s*)&lt;\?python(?!.*\?&gt;)</string>
			<key>end</key>
			<string>\?&gt;(?:\s*$\n)?</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.python</string>
				</dict>
			</array>
		</dict>
		<key>ruby</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>comment.block.erb</string>
					<key>begin</key>
					<string>&lt;%+#</string>
					<key>end</key>
					<string>%&gt;</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.erb</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>source.ruby.embedded.html</string>
					<key>begin</key>
					<string>&lt;%+(?!&gt;)=?</string>
					<key>end</key>
					<string>-?%&gt;</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>comment.line.number-sign.ruby</string>
							<key>match</key>
							<string>(#).*?(?=-?%&gt;)</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.comment.ruby</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>include</key>
							<string>source.ruby</string>
						</dict>
					</array>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.ruby</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>source.ruby.nitro.embedded.html</string>
					<key>begin</key>
					<string>&lt;\?r(?!&gt;)=?</string>
					<key>end</key>
					<string>-?\?&gt;</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>comment.line.number-sign.ruby.nitro</string>
							<key>match</key>
							<string>(#).*?(?=-?\?&gt;)</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.comment.ruby.nitro</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>include</key>
							<string>source.ruby</string>
						</dict>
					</array>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.ruby.nitro</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>string-double-quoted</key>
		<dict>
			<key>name</key>
			<string>string.quoted.double.html</string>
			<key>begin</key>
			<string>&quot;</string>
			<key>end</key>
			<string>&quot;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#embedded-code</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#entities</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.html</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.html</string>
				</dict>
			</dict>
		</dict>
		<key>string-single-quoted</key>
		<dict>
			<key>name</key>
			<string>string.quoted.single.html</string>
			<key>begin</key>
			<string>&apos;</string>
			<key>end</key>
			<string>&apos;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#embedded-code</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#entities</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.html</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.html</string>
				</dict>
			</dict>
		</dict>
		<key>tag-generic-attribute</key>
		<dict>
			<key>name</key>
			<string>entity.other.attribute-name.html</string>
			<key>match</key>
			<string>\b([a-zA-Z\-:]+)</string>
		</dict>
		<key>tag-id-attribute</key>
		<dict>
			<key>name</key>
			<string>meta.attribute-with-value.id.html</string>
			<key>begin</key>
			<string>\b(id)\b\s*(=)</string>
			<key>end</key>
			<string>(?&lt;=&apos;|&quot;)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>string.quoted.double.html</string>
					<key>contentName</key>
					<string>meta.toc-list.id.html</string>
					<key>begin</key>
					<string>&quot;</string>
					<key>end</key>
					<string>&quot;</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#embedded-code</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#entities</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.html</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.html</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>string.quoted.single.html</string>
					<key>contentName</key>
					<string>meta.toc-list.id.html</string>
					<key>begin</key>
					<string>&apos;</string>
					<key>end</key>
					<string>&apos;</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#embedded-code</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#entities</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.html</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.html</string>
						</dict>
					</dict>
				</dict>
			</array>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.id.html</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.key-value.html</string>
				</dict>
			</dict>
		</dict>
		<key>tag-stuff</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-id-attribute</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag-generic-attribute</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-double-quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-single-quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded-code</string>
				</dict>
			</array>
		</dict>
		<key>twig-arrays</key>
		<dict>
			<key>name</key>
			<string>meta.array.twig</string>
			<key>begin</key>
			<string>(?&lt;=[\s\(\{\[:,])\[</string>
			<key>end</key>
			<string>\]</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#twig-arrays</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-hashes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-functions-warg</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-macros</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-objects</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-properties</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-filters-warg</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-filters</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-filters-warg-ud</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-filters-ud</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.separator.object.twig</string>
					<key>match</key>
					<string>,</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.array.begin.twig</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.array.end.twig</string>
				</dict>
			</dict>
		</dict>
		<key>twig-comment-tag</key>
		<dict>
			<key>name</key>
			<string>comment.block.twig</string>
			<key>begin</key>
			<string>\{#-?</string>
			<key>end</key>
			<string>-?#\}</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.begin.twig</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.end.twig</string>
				</dict>
			</dict>
		</dict>
		<key>twig-constants</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.language.twig</string>
					<key>match</key>
					<string>(?i)(?&lt;=[\s\[\(\{:,])(?:true|false|null|none)(?=[\s\)\]\}\,])</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.twig</string>
					<key>match</key>
					<string>(?&lt;=[\s\[\(\{:,]|\.\.|\*\*)[0-9]+(?:\.[0-9]+)?(?=[\s\)\]\}\,]|\.\.|\*\*)</string>
				</dict>
			</array>
		</dict>
		<key>twig-filters</key>
		<dict>
			<key>match</key>
			<string>(?&lt;=(?:[a-zA-Z0-9_\x{7f}-\x{ff}\]\)\&apos;\&quot;]\|)|\{%\sfilter\s)(abs|capitalize|e(?:scape)?|first|join|(?:json|url)_encode|keys|last|length|lower|nl2br|number_format|raw|reverse|round|sort|striptags|title|trim|upper)(?=[\s\|\]\}\):,]|\.\.|\*\*)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.twig</string>
				</dict>
			</dict>
		</dict>
		<key>twig-filters-ud</key>
		<dict>
			<key>match</key>
			<string>(?&lt;=(?:[a-zA-Z0-9_\x{7f}-\x{ff}\]\)\&apos;\&quot;]\|)|\{%\sfilter\s)([a-zA-Z_\x{7f}-\x{ff}][a-zA-Z0-9_\x{7f}-\x{ff}]*)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.function-call.other.twig</string>
				</dict>
			</dict>
		</dict>
		<key>twig-filters-warg</key>
		<dict>
			<key>contentName</key>
			<string>meta.function.arguments.twig</string>
			<key>begin</key>
			<string>(?&lt;=(?:[a-zA-Z0-9_\x{7f}-\x{ff}\]\)\&apos;\&quot;]\|)|\{%\sfilter\s)(batch|convert_encoding|date|date_modify|default|e(?:scape)?|format|join|merge|number_format|replace|round|slice|split|trim)(\()</string>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#twig-constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-functions-warg</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-macros</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-objects</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-properties</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-filters-warg</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-filters</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-filters-warg-ud</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-filters-ud</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-arrays</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-hashes</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.twig</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.twig</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.end.twig</string>
				</dict>
			</dict>
		</dict>
		<key>twig-filters-warg-ud</key>
		<dict>
			<key>contentName</key>
			<string>meta.function.arguments.twig</string>
			<key>begin</key>
			<string>(?&lt;=(?:[a-zA-Z0-9_\x{7f}-\x{ff}\]\)\&apos;\&quot;]\|)|\{%\sfilter\s)([a-zA-Z_\x{7f}-\x{ff}][a-zA-Z0-9_\x{7f}-\x{ff}]*)(\()</string>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#twig-constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-functions-warg</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-macros</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-objects</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-properties</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-filters-warg</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-filters</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-filters-warg-ud</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-filters-ud</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-arrays</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-hashes</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.function-call.other.twig</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.twig</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.end.twig</string>
				</dict>
			</dict>
		</dict>
		<key>twig-functions</key>
		<dict>
			<key>match</key>
			<string>(?&lt;=is\s)(defined|empty|even|iterable|odd)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.twig</string>
				</dict>
			</dict>
		</dict>
		<key>twig-functions-warg</key>
		<dict>
			<key>contentName</key>
			<string>meta.function.arguments.twig</string>
			<key>begin</key>
			<string>(?&lt;=[\s\(\[\{:,])(attribute|block|constant|cycle|date|divisible by|dump|include|max|min|parent|random|range|same as|source|template_from_string)(\()</string>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#twig-constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-functions-warg</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-macros</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-objects</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-properties</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-filters-warg</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-filters</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-filters-warg-ud</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-filters-ud</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-arrays</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.twig</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.twig</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.end.twig</string>
				</dict>
			</dict>
		</dict>
		<key>twig-hashes</key>
		<dict>
			<key>name</key>
			<string>meta.hash.twig</string>
			<key>begin</key>
			<string>(?&lt;=[\s\(\{\[:,])\{</string>
			<key>end</key>
			<string>\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#twig-hashes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-arrays</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-functions-warg</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-macros</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-objects</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-properties</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-filters-warg</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-filters</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-filters-warg-ud</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-filters-ud</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.separator.key-value.twig</string>
					<key>match</key>
					<string>:</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.separator.object.twig</string>
					<key>match</key>
					<string>,</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.hash.begin.twig</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.hash.end.twig</string>
				</dict>
			</dict>
		</dict>
		<key>twig-keywords</key>
		<dict>
			<key>name</key>
			<string>keyword.control.twig</string>
			<key>match</key>
			<string>(?&lt;=\s)((?:end)?(?:autoescape|block|embed|filter|for|if|macro|raw|sandbox|set|spaceless|trans|verbatim)|as|do|else|elseif|extends|flush|from|ignore missing|import|include|only|use|with)(?=\s)</string>
		</dict>
		<key>twig-macros</key>
		<dict>
			<key>contentName</key>
			<string>meta.function.arguments.twig</string>
			<key>begin</key>
			<string>(?x)
                    (?&lt;=[\s\(\[\{:,])
                    ([a-zA-Z_\x{7f}-\x{ff}][a-zA-Z0-9_\x{7f}-\x{ff}]*)
                    (?:
                        (\.)([a-zA-Z_\x{7f}-\x{ff}][a-zA-Z0-9_\x{7f}-\x{ff}]*)
                    )?
                    (\()
            </string>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#twig-constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-functions-warg</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-macros</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-objects</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-properties</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-filters-warg</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-filters</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-filters-warg-ud</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-filters-ud</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-arrays</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-hashes</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.function-call.twig</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.property.twig</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.other.property.twig</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.twig</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.end.twig</string>
				</dict>
			</dict>
		</dict>
		<key>twig-objects</key>
		<dict>
			<key>match</key>
			<string>(?&lt;=[\s\{\[\(:,])([a-zA-Z_\x{7f}-\x{ff}][a-zA-Z0-9_\x{7f}-\x{ff}]*)(?=[\s\}\[\]\(\)\.\|,:])</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.twig</string>
				</dict>
			</dict>
		</dict>
		<key>twig-operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;=\s)(\+|-|//?|%|\*\*?)(?=\s)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.arithmetic.twig</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=\s)(=|~)(?=\s)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.assignment.twig</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=\s)(b-(?:and|or|xor))(?=\s)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.bitwise.twig</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=\s)((?:!|=)=|&lt;=?|&gt;=?|(?:not )?in|is(?: not)?|(?:ends|starts) with|matches)(?=\s)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.comparison.twig</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=\s)(\?|:|and|not|or)(?=\s)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.logical.twig</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=[a-zA-Z0-9_\x{7f}-\x{ff}\]\)&apos;&quot;])\.\.(?=[a-zA-Z0-9_\x{7f}-\x{ff}&apos;&quot;])</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.other.twig</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=[a-zA-Z0-9_\x{7f}-\x{ff}\]\}\)&apos;&quot;])\|(?=[a-zA-Z_\x{7f}-\x{ff}])</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.other.twig</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>twig-print-tag</key>
		<dict>
			<key>name</key>
			<string>meta.tag.template.value.twig</string>
			<key>begin</key>
			<string>\{\{-?</string>
			<key>end</key>
			<string>-?\}\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#twig-constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-functions-warg</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-macros</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-objects</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-properties</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-filters-warg</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-filters</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-filters-warg-ud</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-filters-ud</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-arrays</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-hashes</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.tag.twig</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.tag.twig</string>
				</dict>
			</dict>
		</dict>
		<key>twig-properties</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?x)
                        (?&lt;=[a-zA-Z0-9_\x{7f}-\x{ff}])
                        (\.)([a-zA-Z_\x{7f}-\x{ff}][a-zA-Z0-9_\x{7f}-\x{ff}]*)
                        (?=[\.\s\|\[\)\]\}:,])
                    </string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.property.twig</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.property.twig</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>contentName</key>
					<string>meta.function.arguments.twig</string>
					<key>begin</key>
					<string>(?x)
                        (?&lt;=[a-zA-Z0-9_\x{7f}-\x{ff}])
                        (\.)([a-zA-Z_\x{7f}-\x{ff}][a-zA-Z0-9_\x{7f}-\x{ff}]*)
                        (\()
                    </string>
					<key>end</key>
					<string>\)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#twig-constants</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#twig-functions-warg</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#twig-functions</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#twig-macros</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#twig-objects</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#twig-properties</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#twig-filters-warg</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#twig-filters</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#twig-filters-warg-ud</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#twig-filters-ud</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#twig-strings</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#twig-arrays</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.property.twig</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.property.twig</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.begin.twig</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.end.twig</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>(?x)
                        (?&lt;=[a-zA-Z0-9_\x{7f}-\x{ff}\]])
                        (?:
                            (\[)(&apos;[a-zA-Z_\x{7f}-\x{ff}][a-zA-Z0-9_\x{7f}-\x{ff}]*&apos;)(\])
                            |(\[)(&quot;[a-zA-Z_\x{7f}-\x{ff}][a-zA-Z0-9_\x{7f}-\x{ff}]*&quot;)(\])
                            |(\[)([a-zA-Z_\x{7f}-\x{ff}][a-zA-Z0-9_\x{7f}-\x{ff}]*)(\])
                        )
                    </string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.array.begin.twig</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.property.twig</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.array.end.twig</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.array.begin.twig</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>variable.other.property.twig</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.array.end.twig</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.array.begin.twig</string>
						</dict>
						<key>8</key>
						<dict>
							<key>name</key>
							<string>variable.other.property.twig</string>
						</dict>
						<key>9</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.array.end.twig</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>twig-statement-tag</key>
		<dict>
			<key>name</key>
			<string>meta.tag.template.block.twig</string>
			<key>begin</key>
			<string>\{%-?</string>
			<key>end</key>
			<string>-?%\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#twig-constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-functions-warg</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-macros</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-filters-warg</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-filters</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-filters-warg-ud</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-filters-ud</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-objects</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-properties</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-arrays</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#twig-hashes</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.tag.twig</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.tag.twig</string>
				</dict>
			</dict>
		</dict>
		<key>twig-strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>string.quoted.single.twig</string>
					<key>begin</key>
					<string>(?:(?&lt;!\\)|(?&lt;=\\\\))&apos;</string>
					<key>end</key>
					<string>(?:(?&lt;!\\)|(?&lt;=\\\\))&apos;</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.twig</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.twig</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>string.quoted.double.twig</string>
					<key>begin</key>
					<string>(?:(?&lt;!\\)|(?&lt;=\\\\))&quot;</string>
					<key>end</key>
					<string>(?:(?&lt;!\\)|(?&lt;=\\\\))&quot;</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.twig</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.twig</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>twig</string>
	</array>
</dict>
</plist>
