<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>TXL</string>
	<key>scopeName</key>
	<string>source.txl</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>name</key>
			<string>keyword.control</string>
			<key>match</key>
			<string>\b(?&lt;!&apos;)(define|end|function|keys|compounds|tokens|comments|replace|construct|by|replace|rule|deconstruct|not|where|all|not|assert|export|import|redefine|external|match|skipping|include|then)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.preprocessor</string>
			<key>match</key>
			<string>(?&lt;!&apos;)#\s*(pragma|endif|else|define|undef|undefine|ifn|elifn|elifdef|elifndef|ifndef|ifdef|if|end)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>comment</string>
			<key>begin</key>
			<string>(?&lt;!&apos;)%[\({]</string>
			<key>end</key>
			<string>(?&lt;!&apos;)[\)}]%</string>
		</dict>
		<dict>
			<key>name</key>
			<string>comment</string>
			<key>match</key>
			<string>(?&lt;!&apos;)%.*</string>
		</dict>
		<dict>
			<key>name</key>
			<string>entity.name.function</string>
			<key>match</key>
			<string>(?&lt;!&apos;)\[(not|opt|repeat|list|see|push|pop|\+|-|/|\*|=|&lt;|&gt;|\^|\.|div|rem|:|#|index|_|length|select|head|tail|,|~=|&gt;=|&lt;=|grep|\$|quote|unquote|parse|unparse|reparse|typeof|istype|read|write|fget|getp|fput|putp|fputp|fputs|fclose|fopen|fgets|message|pragma|quit|system|pipe|attr) .+?\]</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.language</string>
			<key>match</key>
			<string>(?&lt;!&apos;)\[(NL|EX(_\d+)?|IN(_\d+)?|SP(_\d+)?|TAB(_\d+)?|SPON|SPOFF|\!|round|trunc|toupper|tolower|get|put|gets|print|printattr|debug|breakpoint)\]</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.type</string>
			<key>match</key>
			<string>(?&lt;!&apos;)\[.+?\]</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.numeric</string>
			<key>match</key>
			<string>\b(\d+)|(\d+\.\d+([\+-][Ee]\d+)?)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>string.quoted.double</string>
			<key>match</key>
			<string>&quot;.*&quot;</string>
		</dict>
	</array>
	<key>fileTypes</key>
	<array>
		<string>txl</string>
	</array>
</dict>
</plist>
