<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>typst</string>
	<key>scopeName</key>
	<string>source.typst</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#markup</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>arguments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>variable.parameter.typst</string>
					<key>match</key>
					<string>\b[[:alpha:]_][[:alnum:]_-]*(?=:)</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#code</string>
				</dict>
			</array>
		</dict>
		<key>code</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#common</string>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.block.code.typst</string>
					<key>begin</key>
					<string>{</string>
					<key>end</key>
					<string>}</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#code</string>
						</dict>
					</array>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.block.code.typst</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.block.content.typst</string>
					<key>begin</key>
					<string>\[</string>
					<key>end</key>
					<string>\]</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#markup</string>
						</dict>
					</array>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.block.content.typst</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>comment.line.double-slash.typst</string>
					<key>begin</key>
					<string>//</string>
					<key>end</key>
					<string>
</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.typst</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.separator.colon.typst</string>
					<key>match</key>
					<string>:</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.separator.comma.typst</string>
					<key>match</key>
					<string>,</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.typst</string>
					<key>match</key>
					<string>=&gt;|\.\.</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.relational.typst</string>
					<key>match</key>
					<string>==|!=|&lt;=|&lt;|&gt;=|&gt;</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.typst</string>
					<key>match</key>
					<string>\+=|-=|\*=|/=|=</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.arithmetic.typst</string>
					<key>match</key>
					<string>\+|\|/|(?&lt;![[:alpha:]])(?&lt;!\w)(?&lt;!\d)-(?![[:alnum:]-][[:alpha:]_])</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.word.typst</string>
					<key>match</key>
					<string>\b(and|or|not)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.other.typst</string>
					<key>match</key>
					<string>\b(let|as|in|set|show)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.control.conditional.typst</string>
					<key>match</key>
					<string>\b(if|else)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.control.loop.typst</string>
					<key>match</key>
					<string>\b(for|while|break|continue)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.control.import.typst</string>
					<key>match</key>
					<string>\b(import|include|export)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.control.flow.typst</string>
					<key>match</key>
					<string>\b(return)\b</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constants</string>
				</dict>
				<dict>
					<key>name</key>
					<string>entity.name.function.typst</string>
					<key>match</key>
					<string>\b[[:alpha:]_][[:alnum:]_-]*!?(?=\[|\()</string>
				</dict>
				<dict>
					<key>name</key>
					<string>entity.name.function.typst</string>
					<key>match</key>
					<string>(?:\bshow\s*\b([[:alpha:]][[:alnum:]-])(?=\s[:.]))</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?:\b([[:alpha:]][[:alnum:]-]*!?)\()</string>
					<key>end</key>
					<string>\)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#arguments</string>
						</dict>
					</array>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.group.typst</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>variable.other.typst</string>
					<key>match</key>
					<string>\b[[:alpha:]_][[:alnum:]_-]*\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.group.typst</string>
					<key>begin</key>
					<string>\(</string>
					<key>end</key>
					<string>\)|(?=;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#code</string>
						</dict>
					</array>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.group.typst</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>comment.block.typst</string>
					<key>begin</key>
					<string>/\*</string>
					<key>end</key>
					<string>\*/</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
					</array>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.typst</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>comment.line.double-slash.typst</string>
					<key>begin</key>
					<string>(?&lt;!:)//</string>
					<key>end</key>
					<string>
</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.typst</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>common</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
			</array>
		</dict>
		<key>constants</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.language.none.typst</string>
					<key>match</key>
					<string>\bnone\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.auto.typst</string>
					<key>match</key>
					<string>\bauto\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.boolean.typst</string>
					<key>match</key>
					<string>\b(true|false)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.length.typst</string>
					<key>match</key>
					<string>\b(\d*)?\.?\d+([eE][+-]?\d+)?(mm|pt|cm|in|em)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.angle.typst</string>
					<key>match</key>
					<string>\b(\d*)?\.?\d+([eE][+-]?\d+)?(rad|deg)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.percentage.typst</string>
					<key>match</key>
					<string>\b(\d*)?\.?\d+([eE][+-]?\d+)?%</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.fr.typst</string>
					<key>match</key>
					<string>\b(\d*)?\.?\d+([eE][+-]?\d+)?fr</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.integer.typst</string>
					<key>match</key>
					<string>\b\d+\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.float.typst</string>
					<key>match</key>
					<string>\b(\d*)?\.?\d+([eE][+-]?\d+)?\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>string.quoted.double.typst</string>
					<key>begin</key>
					<string>&quot;</string>
					<key>end</key>
					<string>&quot;</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>constant.character.escape.string.typst</string>
							<key>match</key>
							<string>\\([\\&quot;nrt]|u\{?[0-9a-zA-Z]*\}?)</string>
						</dict>
					</array>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.typst</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>string.other.math.typst</string>
					<key>begin</key>
					<string>\$</string>
					<key>end</key>
					<string>\$</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.math.typst</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>markup</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#common</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.escape.content.typst</string>
					<key>match</key>
					<string>\\([\\/\[\]{}#*_=~`$-.]|u\{[0-9a-zA-Z]*\}?)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.definition.linebreak.typst</string>
					<key>match</key>
					<string>\\</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.definition.nonbreaking-space.typst</string>
					<key>match</key>
					<string>~</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.definition.shy.typst</string>
					<key>match</key>
					<string>-\?</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.definition.em-dash.typst</string>
					<key>match</key>
					<string>---</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.definition.en-dash.typst</string>
					<key>match</key>
					<string>--</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.definition.ellipsis.typst</string>
					<key>match</key>
					<string>\.\.\.</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.symbol.typst</string>
					<key>match</key>
					<string>:([a-zA-Z0-9]+:)+</string>
				</dict>
				<dict>
					<key>name</key>
					<string>markup.bold.typst</string>
					<key>begin</key>
					<string>(^\*|\*$|((?&lt;=\W|_)\*)|(\*(?=\W|_)))</string>
					<key>end</key>
					<string>(^\*|\*$|((?&lt;=\W|_)\*)|(\*(?=\W|_)))|
|(?=\])</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#markup</string>
						</dict>
					</array>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.bold.typst</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>markup.italic.typst</string>
					<key>begin</key>
					<string>(^_|_$|((?&lt;=\W|_)_)|(_(?=\W|_)))</string>
					<key>end</key>
					<string>(^_|_$|((?&lt;=\W|_)_)|(_(?=\W|_)))|
|(?=\])</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#markup</string>
						</dict>
					</array>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.italic.typst</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>markup.underline.link.typst</string>
					<key>match</key>
					<string>https?://[0-9a-zA-Z~/%#&amp;=&apos;,;\.\+\?]*</string>
				</dict>
				<dict>
					<key>name</key>
					<string>markup.raw.block.typst</string>
					<key>begin</key>
					<string>`{3,}</string>
					<key>end</key>
					<string>\0</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.raw.typst</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>markup.raw.inline.typst</string>
					<key>begin</key>
					<string>`</string>
					<key>end</key>
					<string>`</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.raw.typst</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>string.other.math.typst</string>
					<key>begin</key>
					<string>\$</string>
					<key>end</key>
					<string>\$</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.math.typst</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>markup.heading.typst</string>
					<key>contentName</key>
					<string>entity.name.section.typst</string>
					<key>begin</key>
					<string>^\s*=+\s+</string>
					<key>end</key>
					<string>
|(?=&lt;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#markup</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.heading.typst</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.definition.list.unnumbered.typst</string>
					<key>match</key>
					<string>^\s*-\s+</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.definition.list.numbered.typst</string>
					<key>match</key>
					<string>^\s*([0-9]*\.|\+)\s+</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^\s*(/)\s+([^:]*:)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.list.description.typst</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>markup.list.term.typst</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>entity.other.label.typst</string>
					<key>match</key>
					<string>&lt;[[:alpha:]_][[:alnum:]_-]*&gt;</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.label.typst</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>entity.other.reference.typst</string>
					<key>match</key>
					<string>(@)[[:alpha:]_][[:alnum:]_-]*</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.reference.typst</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>begin</key>
					<string>(#)(let|set|show)\b</string>
					<key>end</key>
					<string>
|(;)|(?=])</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#code</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.other.typst</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.typst</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.terminator.statement.typst</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.other.typst</string>
					<key>match</key>
					<string>(#)(as|in)\b</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.typst</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?:(#)if|(?:}(?:\s*)|](?:\s*))else)\b</string>
					<key>end</key>
					<string>
|(?=])|(?&lt;=}|])</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#code</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.conditional.typst</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.typst</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>begin</key>
					<string>(#)(for|while)\b</string>
					<key>end</key>
					<string>
|(?=])|(?&lt;=}|])</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#code</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.loop.typst</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.typst</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.control.loop.typst</string>
					<key>match</key>
					<string>(#)(break|continue)\b</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.typst</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>begin</key>
					<string>(#)(import|include|export)\b</string>
					<key>end</key>
					<string>
|(;)|(?=])</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#code</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.import.typst</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.typst</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.terminator.statement.typst</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.control.flow.typst</string>
					<key>match</key>
					<string>(#)(return)\b</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.typst</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>entity.name.function.typst</string>
					<key>match</key>
					<string>((#)[[:alpha:]_][[:alnum:]_-]*!?)(?=\[|\()</string>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.typst</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?:#)([[A-Za-z]_][[0-9]_-]*!?(?=\())\(</string>
					<key>end</key>
					<string>\)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#arguments</string>
						</dict>
					</array>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.group.typst</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>entity.other.interpolated.typst</string>
					<key>match</key>
					<string>(#)[[:alpha:]_][.[:alnum:]_-]*</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.typst</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.block.content.typst</string>
					<key>begin</key>
					<string>#</string>
					<key>end</key>
					<string>\s</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#code</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>typ</string>
	</array>
</dict>
</plist>
