<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>KeyValues</string>
	<key>scopeName</key>
	<string>source.keyvalues</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#main</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>block</key>
		<dict>
			<key>name</key>
			<string>meta.structure.block.keyvalues</string>
			<key>begin</key>
			<string>{</string>
			<key>end</key>
			<string>}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#main</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.block.begin.keyvalues</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.block.end.keyvalues</string>
				</dict>
			</dict>
		</dict>
		<key>comment</key>
		<dict>
			<key>name</key>
			<string>comment.line.slash.keyvalues</string>
			<key>begin</key>
			<string>/</string>
			<key>end</key>
			<string>$</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.keyvalues</string>
				</dict>
			</dict>
		</dict>
		<key>main</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
			</array>
		</dict>
		<key>number</key>
		<dict>
			<key>name</key>
			<string>constant.numeric.integer.keyvalues</string>
			<key>match</key>
			<string>\b\d+\b$</string>
		</dict>
		<key>string</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string_parts</string>
				</dict>
				<dict>
					<key>name</key>
					<string>string.quoted.double.keyvalues</string>
					<key>begin</key>
					<string>&quot;</string>
					<key>end</key>
					<string>&quot;</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string_parts</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.keyvalues</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.keyvalues</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>string.unquoted.keyvalues</string>
					<key>match</key>
					<string>[^\s{}]+</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string_parts</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>string_parts</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>entity.name.tag.include.keyvalues</string>
					<key>match</key>
					<string>(?&lt;!\w)(#)\w+</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.include.keyvalues</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>string.unquoted.file-path.keyvalues</string>
					<key>match</key>
					<string>(\|)(\S+)(\|)</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>constant.language.directory.keyvalues</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.directory.begin.keyvalues</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.directory.end.keyvalues</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.escape.keyvalues</string>
					<key>match</key>
					<string>\\[\\nt&quot;]</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>vdf</string>
	</array>
</dict>
</plist>
