<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Vim Help</string>
	<key>scopeName</key>
	<string>text.vim-help</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>name</key>
			<string>meta.file-header.vim-help</string>
			<key>match</key>
			<string>(?i)\A(\*[#-)!+-~]+\*)[ \t]+(For\s+Vim\s+version\s*[\d.]+)[ \t]+Last\s+changed?:\s*(\S.*?)\s*$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tag</string>
						</dict>
					</array>
				</dict>
				<key>2</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#vimVersion</string>
						</dict>
					</array>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.date.last-changed.vim-help</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>include</key>
			<string>#main</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>codeBlock</key>
		<dict>
			<key>name</key>
			<string>meta.example.vim-help</string>
			<key>contentName</key>
			<string>markup.raw.code.verbatim.vim-help</string>
			<key>begin</key>
			<string>(?:(?&lt;=\s)|^)(&gt;)$</string>
			<key>end</key>
			<string>^(&lt;)|(?=^\S)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.example.begin.vim-help</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.example.end.vim-help</string>
				</dict>
			</dict>
		</dict>
		<key>columnHeading</key>
		<dict>
			<key>name</key>
			<string>markup.heading.column-title.vim-help</string>
			<key>match</key>
			<string>^\s*\S.*(~)$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.column-marker.tilde.vim-help</string>
				</dict>
			</dict>
		</dict>
		<key>command</key>
		<dict>
			<key>name</key>
			<string>markup.raw.command.vim-help</string>
			<key>match</key>
			<string>(`)([^` \t]+)(`)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.link.begin.vim-help</string>
				</dict>
				<key>2</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.viml</string>
						</dict>
					</array>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.link.end.vim-help</string>
				</dict>
			</dict>
		</dict>
		<key>link</key>
		<dict>
			<key>name</key>
			<string>meta.link.vim-help</string>
			<key>match</key>
			<string>(\|)([^&quot;*|]+)(\|)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.separator.punctuation.link.begin.vim-help</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.other.link.vim-help</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>meta.separator.punctuation.link.end.vim-help</string>
				</dict>
			</dict>
		</dict>
		<key>main</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#special</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#option</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#command</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#codeBlock</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#manualTitle</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#columnHeading</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#sectionDelimiter</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#vimVersion</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#url</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#other</string>
				</dict>
			</array>
		</dict>
		<key>manualTitle</key>
		<dict>
			<key>name</key>
			<string>markup.heading.manual-title.vim-help</string>
			<key>match</key>
			<string>^[ \t]+(VIM REFERENCE.*)\s*$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.other.title-text.vim-help</string>
				</dict>
			</dict>
		</dict>
		<key>option</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>entity.name.tag.option.vim-help</string>
					<key>match</key>
					<string>(&apos;)[a-z]{2,}(&apos;)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.begin.option.vim-help</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.end.option.vim-help</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>other</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>markup.changed.${1:/downcase}.vim-help</string>
					<key>match</key>
					<string>\b(DEPRECATED|WARNING|(?:Deprecated|Warning)(?=:))(:|\b)</string>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.assignment.key-value.colon.vim-help</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>invalid.illegal.error.vim-help</string>
					<key>match</key>
					<string>\t[* ]Error\t+[a-z].*</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.list-item.marker.vim-help</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>markup.ignored.todo.vim-help</string>
					<key>match</key>
					<string>\t[* ]Todo\t+[a-z].*</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.list-item.marker.vim-help</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>comment.line.vim-help</string>
					<key>match</key>
					<string>\t[* ](Comment)\t+([a-z].*)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.list-item.marker.vim-help</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.other.reference.link.vim-help</string>
					<key>match</key>
					<string>\t[* ]Underlined\t+[a-z].*</string>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.${2:/downcase}-line.vim-help</string>
					<key>match</key>
					<string>(?x) \t (\*|\x20)
(Boolean|Character|Conditional|Constant|Debug|Define|Delimiter
|Exception|Float|Function|Identifier|Include|Keyword|Label|Macro
|Number|Operator|PreCondit|PreProc|Repeat|SpecialChar
|SpecialComment|Special|Statement|StorageClass|String
|Structure|Tag|Typedef|Type)
(\t+ ([&quot;Aa-z].*))</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.list-item.marker.vim-help</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.type.${2:/downcase}.vim-help</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>meta.output.vim-help</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>${2:/downcase}.vim-help</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>sectionDelimiter</key>
		<dict>
			<key>name</key>
			<string>constant.other.section.delimiter.vim-help</string>
			<key>match</key>
			<string>^===.*===$|^---.*--$</string>
		</dict>
		<key>special</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>entity.name.keyword.vim-help</string>
					<key>match</key>
					<string>(&lt;)N(&gt;)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.bracket.angle.begin.vim-help</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.bracket.angle.end.vim-help</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>entity.name.keyword.vim-help</string>
					<key>match</key>
					<string>(&lt;)N(?=\.(?:$|\s))</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.bracket.angle.begin.vim-help</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>entity.name.keyword.vim-help</string>
					<key>match</key>
					<string>(\()N(&gt;)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.bracket.round.begin.vim-help</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.bracket.angle.end.vim-help</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>entity.name.keyword.vim-help</string>
					<key>match</key>
					<string>(\[)N(\])</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.bracket.square.begin.vim-help</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.bracket.square.end.vim-help</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>(N)  (N)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.keyword.vim-help</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.keyword.vim-help</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>entity.name.keyword.vim-help</string>
					<key>match</key>
					<string>N(?=th|-1)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>entity.name.keyword.vim-help</string>
					<key>match</key>
					<string>({)[-a-zA-Z0-9&apos;&quot;*+/:%#=\[\]&lt;&gt;.,]+(})</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.bracket.curly.begin.vim-help</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.bracket.curly.end.vim-help</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>entity.name.keyword.vim-help</string>
					<key>match</key>
					<string>(?&lt;=\s)(\[)[-a-z^A-Z0-9_]{2,}(\])</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.bracket.square.begin.vim-help</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.bracket.square.end.vim-help</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>entity.name.keyword.vim-help</string>
					<key>match</key>
					<string>(&lt;)[-a-zA-Z0-9_]+(&gt;)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.bracket.angle.begin.vim-help</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.bracket.angle.end.vim-help</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>entity.name.keyword.vim-help</string>
					<key>match</key>
					<string>(&lt;)[SCM]-.(&gt;)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.bracket.angle.begin.vim-help</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.bracket.angle.end.vim-help</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>entity.name.keyword.vim-help</string>
					<key>match</key>
					<string>(\[)(?:\+\+opt|[-+]?num|\+?cmd|addr|arguments|arg|count|group|ident|line|offset|range)(\])</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.bracket.square.begin.vim-help</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.bracket.square.end.vim-help</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>entity.name.keyword.vim-help</string>
					<key>match</key>
					<string>\bCTRL(-)(?:.|Break|Del|Insert|PageDown|PageUp|({)char(}))</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.delimiter.separator.dash.hyphen.vim-help</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.bracket.curly.begin.vim-help</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.bracket.curly.end.vim-help</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>tag</key>
		<dict>
			<key>name</key>
			<string>storage.link.hypertext.vim-help</string>
			<key>match</key>
			<string>(\*)[#-)!+-~]+(\*)(?=\s|$)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.begin.vim-help</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.end.vim-help</string>
				</dict>
			</dict>
		</dict>
		<key>url</key>
		<dict>
			<key>name</key>
			<string>constant.other.reference.link.vim-help</string>
			<key>match</key>
			<string>(?x)
(?:(?:(?:https?|ftp|gopher)://|(?:mailto|file|news):)[^&apos;\x20\t&lt;&gt;&quot;]+
|(?:www|web|w3)[a-z0-9_-]*\.[a-z0-9._-]+\.[^&apos;\x20\t&lt;&gt;&quot;]+)
[a-zA-Z0-9/]</string>
		</dict>
		<key>vimVersion</key>
		<dict>
			<key>name</key>
			<string>entity.other.vim-version.vim-help</string>
			<key>match</key>
			<string>\bVim version [0-9][0-9.a-z]*</string>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>txt</string>
	</array>
</dict>
</plist>
