<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Wavefront Material</string>
	<key>scopeName</key>
	<string>source.wavefront.mtl</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#main</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>colour</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#ka</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#kd</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#ks</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#ke</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tf</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#illum</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#d</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tr</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#ns</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#sharpness</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#ni</string>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>name</key>
			<string>comment.line.number-sign.wavefront.mtl</string>
			<key>begin</key>
			<string>#</string>
			<key>end</key>
			<string>$</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.wavefront.mtl</string>
				</dict>
			</dict>
		</dict>
		<key>d</key>
		<dict>
			<key>name</key>
			<string>meta.dissolve.wavefront.mtl</string>
			<key>match</key>
			<string>^\s*(d)(?:\s+((-)halo))?\s+([-\d.]+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.function.$1.wavefront.mtl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.halo.wavefront.mtl</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.dash.wavefront.mtl</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.value.factor.wavefront.mtl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#number</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>illum</key>
		<dict>
			<key>name</key>
			<string>meta.illumination-model.wavefront.mtl</string>
			<key>match</key>
			<string>^\s*(illum)\s+(\d+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.function.$1.wavefront.mtl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.integer.wavefront.mtl</string>
				</dict>
			</dict>
		</dict>
		<key>ka</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.ambient-reflectivity.spectral-curve.wavefront.mtl</string>
					<key>match</key>
					<string>^\s*(Ka)\s+(spectral)\s+(?!#)(\S+)(?&lt;!#)(?:\s+([-\d.]+))?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.function.$1.wavefront.mtl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.$2.wavefront.mtl</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.filename.wavefront.mtl</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.value.factor.wavefront.mtl</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#number</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.ambient-reflectivity.ciexyz.wavefront.mtl</string>
					<key>match</key>
					<string>^\s*(Ka)\s+(xyz)\s+([-\d.]+)(?:\s+([-\d.]+)\s+([-\d.]+))?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.function.$1.wavefront.mtl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.$2.wavefront.mtl</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.value.red.wavefront.mtl</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#number</string>
								</dict>
							</array>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.value.green.wavefront.mtl</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#number</string>
								</dict>
							</array>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>entity.value.blue.wavefront.mtl</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#number</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.ambient-reflectivity.rgb.wavefront.mtl</string>
					<key>match</key>
					<string>^\s*(Ka)\s+([-\d.]+)(?:\s+([-\d.]+)\s+([-\d.]+))?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.function.$1.wavefront.mtl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.value.red.wavefront.mtl</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#number</string>
								</dict>
							</array>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.value.green.wavefront.mtl</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#number</string>
								</dict>
							</array>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.value.blue.wavefront.mtl</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#number</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>kd</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.diffuse-reflectivity.spectral-curve.wavefront.mtl</string>
					<key>match</key>
					<string>^\s*(Kd)\s+(spectral)\s+(?!#)(\S+)(?&lt;!#)(?:\s+([-\d.]+))?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.function.$1.wavefront.mtl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.$2.wavefront.mtl</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.filename.wavefront.mtl</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.value.factor.wavefront.mtl</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#number</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.diffuse-reflectivity.ciexyz.wavefront.mtl</string>
					<key>match</key>
					<string>^\s*(Kd)\s+(xyz)\s+([-\d.]+)(?:\s+([-\d.]+)\s+([-\d.]+))?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.function.$1.wavefront.mtl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.$2.wavefront.mtl</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.value.red.wavefront.mtl</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#number</string>
								</dict>
							</array>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.value.green.wavefront.mtl</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#number</string>
								</dict>
							</array>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>entity.value.blue.wavefront.mtl</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#number</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.diffuse-reflectivity.rgb.wavefront.mtl</string>
					<key>match</key>
					<string>^\s*(Kd)\s+([-\d.]+)(?:\s+([-\d.]+)\s+([-\d.]+))?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.function.$1.wavefront.mtl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.value.red.wavefront.mtl</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#number</string>
								</dict>
							</array>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.value.green.wavefront.mtl</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#number</string>
								</dict>
							</array>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.value.blue.wavefront.mtl</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#number</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>ke</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.emissive-colour.spectral-curve.wavefront.mtl</string>
					<key>match</key>
					<string>^\s*(Ke)\s+(spectral)\s+(?!#)(\S+)(?&lt;!#)(?:\s+([-\d.]+))?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.function.$1.wavefront.mtl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.$2.wavefront.mtl</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.filename.wavefront.mtl</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.value.factor.wavefront.mtl</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#number</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.emissive-colour.ciexyz.wavefront.mtl</string>
					<key>match</key>
					<string>^\s*(Ke)\s+(xyz)\s+([-\d.]+)(?:\s+([-\d.]+)\s+([-\d.]+))?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.function.$1.wavefront.mtl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.$2.wavefront.mtl</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.value.red.wavefront.mtl</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#number</string>
								</dict>
							</array>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.value.green.wavefront.mtl</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#number</string>
								</dict>
							</array>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>entity.value.blue.wavefront.mtl</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#number</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.emissive-colour.rgb.wavefront.mtl</string>
					<key>match</key>
					<string>^\s*(Ke)\s+([-\d.]+)(?:\s+([-\d.]+)\s+([-\d.]+))?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.function.$1.wavefront.mtl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.value.red.wavefront.mtl</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#number</string>
								</dict>
							</array>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.value.green.wavefront.mtl</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#number</string>
								</dict>
							</array>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.value.blue.wavefront.mtl</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#number</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>ks</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.specular-reflectivity.spectral-curve.wavefront.mtl</string>
					<key>match</key>
					<string>^\s*(Ks)\s+(spectral)\s+(?!#)(\S+)(?&lt;!#)(?:\s+([-\d.]+))?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.function.$1.wavefront.mtl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.$2.wavefront.mtl</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.filename.wavefront.mtl</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.value.factor.wavefront.mtl</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#number</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.specular-reflectivity.ciexyz.wavefront.mtl</string>
					<key>match</key>
					<string>^\s*(Ks)\s+(xyz)\s+([-\d.]+)(?:\s+([-\d.]+)\s+([-\d.]+))?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.function.$1.wavefront.mtl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.$2.wavefront.mtl</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.value.red.wavefront.mtl</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#number</string>
								</dict>
							</array>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.value.green.wavefront.mtl</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#number</string>
								</dict>
							</array>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>entity.value.blue.wavefront.mtl</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#number</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.diffuse-reflectivity.rgb.wavefront.mtl</string>
					<key>match</key>
					<string>^\s*(Ks)\s+([-\d.]+)(?:\s+([-\d.]+)\s+([-\d.]+))?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.function.$1.wavefront.mtl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.value.red.wavefront.mtl</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#number</string>
								</dict>
							</array>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.value.green.wavefront.mtl</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#number</string>
								</dict>
							</array>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.value.blue.wavefront.mtl</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#number</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>main</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#newmtl</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#colour</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#texture</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#reflection</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
			</array>
		</dict>
		<key>newmtl</key>
		<dict>
			<key>name</key>
			<string>meta.constructor.wavefront.mtl</string>
			<key>match</key>
			<string>^\s*(newmtl)(?=\s|$)(?:\s+(\w+))?</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.function.$1.wavefront.mtl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.material-name.wavefront.mtl</string>
				</dict>
			</dict>
		</dict>
		<key>ni</key>
		<dict>
			<key>name</key>
			<string>meta.optical-density.ior.wavefront.mtl</string>
			<key>match</key>
			<string>^\s*(Ni)\s+([-\d.]+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.function.$1.wavefront.mtl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.value.wavefront.mtl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#number</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>ns</key>
		<dict>
			<key>name</key>
			<string>meta.specular-exponent.wavefront.mtl</string>
			<key>match</key>
			<string>^\s*(Ns)\s+([-\d.]+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.function.$1.wavefront.mtl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.value.exponent.wavefront.mtl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#number</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>number</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.numeric.integer.wavefront.mtl</string>
					<key>match</key>
					<string>(?&lt;=[\s,]|^)-?\d+(?![-\d.])</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.float.wavefront.mtl</string>
					<key>match</key>
					<string>(?&lt;=[\s,]|^)-?(\d+)(?:(\.)(\d+))?\b</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>leading.decimal</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>decimal.separator</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>trailing.decimal</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.float.no-leading-digits.wavefront.mtl</string>
					<key>match</key>
					<string>(?&lt;=[\s,]|^)-?(\.)(\d+)\b</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>decimal.separator</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>trailing.decimal</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>reflection</key>
		<dict>
			<key>name</key>
			<string>meta.reflection-map.type-$4.wavefront.mtl</string>
			<key>contentName</key>
			<string>meta.options.wavefront.mtl</string>
			<key>begin</key>
			<string>^\s*(refl)\s+((-)type)\s+(sphere|cube_(?:top|bottom|front|back|left|right))(?=\s|$|#)</string>
			<key>end</key>
			<string>(?=$|#)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#texture-options</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.function.$1.wavefront.mtl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.option.type.wavefront.mtl</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.dash.wavefront.mtl</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant.language.mapping-type.$4.wavefront.mtl</string>
				</dict>
			</dict>
		</dict>
		<key>sharpness</key>
		<dict>
			<key>name</key>
			<string>meta.sharpness.wavefront.mtl</string>
			<key>match</key>
			<string>^\s*(sharpness)\s+([-\d.]+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.function.$1.wavefront.mtl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.value.wavefront.mtl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#number</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>texture</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.texture-map.ambient-reflectivity.wavefront.mtl</string>
					<key>contentName</key>
					<string>meta.options.wavefront.mtl</string>
					<key>begin</key>
					<string>^\s*(map_Ka)(?=\s|$|#)</string>
					<key>end</key>
					<string>(?=$|#)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#texture-options</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.function.$1.wavefront.mtl</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.texture-map.diffuse-reflectivity.wavefront.mtl</string>
					<key>contentName</key>
					<string>meta.options.wavefront.mtl</string>
					<key>begin</key>
					<string>^\s*(map_Kd)(?=\s|$|#)</string>
					<key>end</key>
					<string>(?=$|#)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#texture-options</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.function.$1.wavefront.mtl</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.texture-map.specular-reflectivity.wavefront.mtl</string>
					<key>contentName</key>
					<string>meta.options.wavefront.mtl</string>
					<key>begin</key>
					<string>^\s*(map_Ks)(?=\s|$|#)</string>
					<key>end</key>
					<string>(?=$|#)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#texture-options</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.function.$1.wavefront.mtl</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.texture-map.emissive-colour.wavefront.mtl</string>
					<key>contentName</key>
					<string>meta.options.wavefront.mtl</string>
					<key>begin</key>
					<string>^\s*(map_Ke)(?=\s|$|#)</string>
					<key>end</key>
					<string>(?=$|#)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#texture-options</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.function.$1.wavefront.mtl</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.texture-map.specular-exponent.wavefront.mtl</string>
					<key>contentName</key>
					<string>meta.options.wavefront.mtl</string>
					<key>begin</key>
					<string>^\s*(map_Ns)(?=\s|$|#)</string>
					<key>end</key>
					<string>(?=$|#)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#texture-options</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.function.$1.wavefront.mtl</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.texture-map.dissolve.wavefront.mtl</string>
					<key>contentName</key>
					<string>meta.options.wavefront.mtl</string>
					<key>begin</key>
					<string>^\s*(map_d)(?=\s|$|#)</string>
					<key>end</key>
					<string>(?=$|#)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#texture-options</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.function.$1.wavefront.mtl</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.texture-map.antialiasing.wavefront.mtl</string>
					<key>match</key>
					<string>^\s*(map_aat)(?:\s+(on|off)(?=\s|$|#))?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.function.$1.wavefront.mtl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.language.boolean.$2.wavefront.mtl</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.texture-map.decal.wavefront.mtl</string>
					<key>contentName</key>
					<string>meta.options.wavefront.mtl</string>
					<key>begin</key>
					<string>^\s*(decal)(?=\s|$|#)</string>
					<key>end</key>
					<string>(?=$|#)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#texture-options</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.function.$1.wavefront.mtl</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.texture-map.displacement.wavefront.mtl</string>
					<key>contentName</key>
					<string>meta.options.wavefront.mtl</string>
					<key>begin</key>
					<string>^\s*(disp)(?=\s|$|#)</string>
					<key>end</key>
					<string>(?=$|#)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#texture-options</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.function.$1.wavefront.mtl</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.texture-map.bump.wavefront.mtl</string>
					<key>contentName</key>
					<string>meta.options.wavefront.mtl</string>
					<key>begin</key>
					<string>^\s*(bump)(?=\s|$|#)</string>
					<key>end</key>
					<string>(?=$|#)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#texture-options</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.function.$1.wavefront.mtl</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.texture-map.other.$2.wavefront.mtl</string>
					<key>contentName</key>
					<string>meta.options.wavefront.mtl</string>
					<key>begin</key>
					<string>^\s*(map_([-\w]+))(?=\s|$|#)</string>
					<key>end</key>
					<string>(?=$|#)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#texture-options</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.function.$1.wavefront.mtl</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>texture-options</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.texture-option.horizontal-blending.wavefront.mtl</string>
					<key>match</key>
					<string>(?&lt;=\s|^)((-)blendu)\s+(on|off)(?=\s|$|#)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.option.blendu.wavefront.mtl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.dash.wavefront.mtl</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.language.boolean.$3.wavefront.mtl</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.texture-option.vertical-blending.wavefront.mtl</string>
					<key>match</key>
					<string>(?&lt;=\s|^)((-)blendv)\s+(on|off)(?=\s|$|#)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.option.blendv.wavefront.mtl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.dash.wavefront.mtl</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.language.boolean.$3.wavefront.mtl</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.texture-option.bump-multiplier.wavefront.mtl</string>
					<key>match</key>
					<string>(?&lt;=\s|^)((-)bm)\s+([-\d.]+)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.option.bm.wavefront.mtl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.dash.wavefront.mtl</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.value.wavefront.mtl</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#number</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.texture-option.boost.wavefront.mtl</string>
					<key>match</key>
					<string>(?&lt;=\s|^)((-)boost)\s+([-\d.]+)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.option.boost.wavefront.mtl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.dash.wavefront.mtl</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.value.wavefront.mtl</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#number</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.texture-option.colour-correction.wavefront.mtl</string>
					<key>match</key>
					<string>(?&lt;=\s|^)((-)cc)\s+(on|off)(?=\s|$|#)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.option.cc.wavefront.mtl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.dash.wavefront.mtl</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.language.boolean.$3.wavefront.mtl</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.texture-option.clamping.wavefront.mtl</string>
					<key>match</key>
					<string>(?&lt;=\s|^)((-)clamp)\s+(on|off)(?=\s|$|#)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.option.clamp.wavefront.mtl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.dash.wavefront.mtl</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.language.boolean.$3.wavefront.mtl</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.texture-option.channel.wavefront.mtl</string>
					<key>match</key>
					<string>(?&lt;=\s|^)((-)imfchan)(?:\s+([rgbmlz])(?=\s|$|#))?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.option.imfchan.wavefront.mtl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.dash.wavefront.mtl</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.language.boolean.$3.wavefront.mtl</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.texture-option.modify-range.wavefront.mtl</string>
					<key>match</key>
					<string>(?&lt;=\s|^)((-)mm)\s+([-\d.]+)(?:\s+([-\d.]+))?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.option.mm.wavefront.mtl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.dash.wavefront.mtl</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.value.base.wavefront.mtl</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#number</string>
								</dict>
							</array>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.value.gain.wavefront.mtl</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#number</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.texture-option.offset.wavefront.mtl</string>
					<key>match</key>
					<string>(?&lt;=\s|^)((-)o)\s+([-\d.]+)(?:\s+([-\d.]+))?(?:\s+([-\d.]+))?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.option.o.wavefront.mtl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.dash.wavefront.mtl</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.value.u-offset.wavefront.mtl</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#number</string>
								</dict>
							</array>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.value.v-offset.wavefront.mtl</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#number</string>
								</dict>
							</array>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>entity.value.w-offset.wavefront.mtl</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#number</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.texture-option.scale.wavefront.mtl</string>
					<key>match</key>
					<string>(?&lt;=\s|^)((-)s)\s+([-\d.]+)(?:\s+([-\d.]+))?(?:\s+([-\d.]+))?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.option.s.wavefront.mtl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.dash.wavefront.mtl</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.value.u-scale.wavefront.mtl</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#number</string>
								</dict>
							</array>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.value.v-scale.wavefront.mtl</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#number</string>
								</dict>
							</array>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>entity.value.w-scale.wavefront.mtl</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#number</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.texture-option.turbulence.wavefront.mtl</string>
					<key>match</key>
					<string>(?&lt;=\s|^)((-)t)\s+([-\d.]+)(?:\s+([-\d.]+))?(?:\s+([-\d.]+))?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.option.t.wavefront.mtl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.dash.wavefront.mtl</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.value.u-value.wavefront.mtl</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#number</string>
								</dict>
							</array>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.value.v-value.wavefront.mtl</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#number</string>
								</dict>
							</array>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>entity.value.w-value.wavefront.mtl</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#number</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.texture-option.resolution.wavefront.mtl</string>
					<key>match</key>
					<string>(?&lt;=\s|^)((-)texres)\s+([-\d.]+)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.option.texres.wavefront.mtl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.dash.wavefront.mtl</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.value.wavefront.mtl</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#number</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>string.filename.wavefront.mtl</string>
					<key>match</key>
					<string>(?!#)\S+(?&lt;!#)</string>
				</dict>
			</array>
		</dict>
		<key>tf</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.transmission-filter.spectral-curve.wavefront.mtl</string>
					<key>match</key>
					<string>^\s*(Tf)\s+(spectral)\s+(?!#)(\S+)(?&lt;!#)(?:\s+([-\d.]+))?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.function.$1.wavefront.mtl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.$2.wavefront.mtl</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.filename.wavefront.mtl</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.value.factor.wavefront.mtl</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#number</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.transmission-filter.ciexyz.wavefront.mtl</string>
					<key>match</key>
					<string>^\s*(Tf)\s+(xyz)\s+([-\d.]+)(?:\s+([-\d.]+)\s+([-\d.]+))?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.function.$1.wavefront.mtl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.$2.wavefront.mtl</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.value.red.wavefront.mtl</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#number</string>
								</dict>
							</array>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.value.green.wavefront.mtl</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#number</string>
								</dict>
							</array>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>entity.value.blue.wavefront.mtl</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#number</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.transmission-filter.rgb.wavefront.mtl</string>
					<key>match</key>
					<string>^\s*(Tf)\s+([-\d.]+)(?:\s+([-\d.]+)\s+([-\d.]+))?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.function.$1.wavefront.mtl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.value.red.wavefront.mtl</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#number</string>
								</dict>
							</array>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.value.green.wavefront.mtl</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#number</string>
								</dict>
							</array>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.value.blue.wavefront.mtl</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#number</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>tr</key>
		<dict>
			<key>name</key>
			<string>meta.transparency.wavefront.mtl</string>
			<key>match</key>
			<string>^\s*(Tr)\s+([-\d.]+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.function.$1.wavefront.mtl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.value.factor.wavefront.mtl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#number</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>mtl</string>
	</array>
</dict>
</plist>
