<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>WIT</string>
	<key>scopeName</key>
	<string>source.wit</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#package</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#toplevel-use</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#world</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#interface</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#whitespace</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>block-comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>comment.block.empty.wit</string>
					<key>match</key>
					<string>/\*\*/</string>
				</dict>
				<dict>
					<key>name</key>
					<string>comment.block.documentation.wit</string>
					<key>begin</key>
					<string>/\*\*</string>
					<key>end</key>
					<string>\*/</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#block-comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#markdown</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#whitespace</string>
						</dict>
					</array>
					<key>applyEndPatternLast</key>
					<true />
				</dict>
				<dict>
					<key>name</key>
					<string>comment.block.wit</string>
					<key>begin</key>
					<string>/\*(?!\*)</string>
					<key>end</key>
					<string>\*/</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#block-comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#whitespace</string>
						</dict>
					</array>
					<key>applyEndPatternLast</key>
					<true />
				</dict>
			</array>
		</dict>
		<key>boolean</key>
		<dict>
			<key>name</key>
			<string>entity.name.type.boolean.wit</string>
			<key>match</key>
			<string>\b(bool)\b</string>
		</dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#block-comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#doc-comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#line-comment</string>
				</dict>
			</array>
		</dict>
		<key>container</key>
		<dict>
			<key>name</key>
			<string>meta.container.ty.wit</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tuple</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#list</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#option</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#result</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#handle</string>
				</dict>
			</array>
		</dict>
		<key>doc-comment</key>
		<dict>
			<key>name</key>
			<string>comment.line.documentation.wit</string>
			<key>begin</key>
			<string>^\s*///</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#markdown</string>
				</dict>
			</array>
		</dict>
		<key>enum</key>
		<dict>
			<key>name</key>
			<string>meta.enum-items.wit</string>
			<key>begin</key>
			<string>\b(enum)\b\s+%?((?&lt;![\-\w])([a-z][0-9a-z]*|[A-Z][0-9A-Z]*)(([\-])([a-z][0-9a-z]*|[A-Z][0-9A-Z]*))*)\s*(\{)</string>
			<key>end</key>
			<string>(\})</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#enum-cases</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#whitespace</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.enum.enum-items.wit</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.id.enum-items.wit</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>punctuation.brackets.curly.begin.wit</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.brackets.curly.end.wit</string>
				</dict>
			</dict>
			<key>applyEndPatternLast</key>
			<true />
		</dict>
		<key>enum-cases</key>
		<dict>
			<key>name</key>
			<string>meta.enum-cases.wit</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>name</key>
					<string>variable.other.enummember.id.enum-cases.wit</string>
					<key>match</key>
					<string>\b%?((?&lt;![\-\w])([a-z][0-9a-z]*|[A-Z][0-9A-Z]*)(([\-])([a-z][0-9a-z]*|[A-Z][0-9A-Z]*))*)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.comma.wit</string>
					<key>match</key>
					<string>(\,)</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#whitespace</string>
				</dict>
			</array>
		</dict>
		<key>extern</key>
		<dict>
			<key>name</key>
			<string>meta.extern-type.wit</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.interface-type.wit</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>\b(interface)\b\s*(\{)</string>
							<key>end</key>
							<string>(\})</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#comment</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#interface-items</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#whitespace</string>
								</dict>
							</array>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.other.interface.interface-type.wit</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>ppunctuation.brackets.curly.begin.wit</string>
								</dict>
							</dict>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.brackets.curly.end.wit</string>
								</dict>
							</dict>
							<key>applyEndPatternLast</key>
							<true />
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#function-definition</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#use-path</string>
				</dict>
			</array>
		</dict>
		<key>flags</key>
		<dict>
			<key>name</key>
			<string>meta.flags-items.wit</string>
			<key>begin</key>
			<string>\b(flags)\s+%?((?&lt;![\-\w])([a-z][0-9a-z]*|[A-Z][0-9A-Z]*)(([\-])([a-z][0-9a-z]*|[A-Z][0-9A-Z]*))*)\s*(\{)</string>
			<key>end</key>
			<string>(\})</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#flags-fields</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#whitespace</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.flags.flags-items.wit</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.id.flags-items.wit</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>punctuation.brackets.curly.begin.wit</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.brackets.curly.end.wit</string>
				</dict>
			</dict>
			<key>applyEndPatternLast</key>
			<true />
		</dict>
		<key>flags-fields</key>
		<dict>
			<key>name</key>
			<string>meta.flags-fields.wit</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>name</key>
					<string>variable.other.enummember.id.flags-fields.wit</string>
					<key>match</key>
					<string>\b%?((?&lt;![\-\w])([a-z][0-9a-z]*|[A-Z][0-9A-Z]*)(([\-])([a-z][0-9a-z]*|[A-Z][0-9A-Z]*))*)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.comma.wit</string>
					<key>match</key>
					<string>(\,)</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#whitespace</string>
				</dict>
			</array>
		</dict>
		<key>function</key>
		<dict>
			<key>name</key>
			<string>meta.func-item.wit</string>
			<key>begin</key>
			<string>\b%?((?&lt;![\-\w])([a-z][0-9a-z]*|[A-Z][0-9A-Z]*)(([\-])([a-z][0-9a-z]*|[A-Z][0-9A-Z]*))*)\s*(\:)</string>
			<key>end</key>
			<string>((?&lt;=\n)|(?=\}))</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#function-definition</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#whitespace</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.id.func-item.wit</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.word.wit</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>meta.word-separator.wit</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>meta.word.wit</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.key-value.wit</string>
				</dict>
			</dict>
			<key>applyEndPatternLast</key>
			<true />
		</dict>
		<key>function-definition</key>
		<dict>
			<key>name</key>
			<string>meta.func-type.wit</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.function.wit</string>
					<key>begin</key>
					<string>\b(static\s+)?(func)\b</string>
					<key>end</key>
					<string>((?&lt;=\n)|(?=\}))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#parameter-list</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#result-list</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#whitespace</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.static.func-item.wit</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.func.func-type.wit</string>
						</dict>
					</dict>
					<key>applyEndPatternLast</key>
					<true />
				</dict>
			</array>
		</dict>
		<key>handle</key>
		<dict>
			<key>name</key>
			<string>meta.handle.ty.wit</string>
			<key>match</key>
			<string>\b(borrow)\b(\&lt;)\s*%?((?&lt;![\-\w])([a-z][0-9a-z]*|[A-Z][0-9A-Z]*)(([\-])([a-z][0-9a-z]*|[A-Z][0-9A-Z]*))*)\s*(\&gt;)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.borrow.handle.wit</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.brackets.angle.begin.wit</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.id.handle.wit</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>punctuation.brackets.angle.end.wit</string>
				</dict>
			</dict>
		</dict>
		<key>identifier</key>
		<dict>
			<key>name</key>
			<string>entity.name.type.id.wit</string>
			<key>match</key>
			<string>\b%?((?&lt;![\-\w])([a-z][0-9a-z]*|[A-Z][0-9A-Z]*)(([\-])([a-z][0-9a-z]*|[A-Z][0-9A-Z]*))*)\b</string>
		</dict>
		<key>interface</key>
		<dict>
			<key>name</key>
			<string>meta.interface-item.wit</string>
			<key>begin</key>
			<string>^\b(default\s+)?(interface)\s+%?((?&lt;![\-\w])([a-z][0-9a-z]*|[A-Z][0-9A-Z]*)(([\-])([a-z][0-9a-z]*|[A-Z][0-9A-Z]*))*)\s*(\{)</string>
			<key>end</key>
			<string>(\})</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#interface-items</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#whitespace</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.default.interface-item.wit</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.declaration.interface.interface-item.wit storage.type.wit</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.id.interface-item.wit</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>punctuation.brackets.curly.begin.wit</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.brackets.curly.end.wit</string>
				</dict>
			</dict>
			<key>applyEndPatternLast</key>
			<true />
		</dict>
		<key>interface-items</key>
		<dict>
			<key>name</key>
			<string>meta.interface-items.wit</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#typedef-item</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#use</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function</string>
				</dict>
			</array>
		</dict>
		<key>line-comment</key>
		<dict>
			<key>name</key>
			<string>comment.line.double-slash.wit</string>
			<key>match</key>
			<string>\s*//.*</string>
		</dict>
		<key>list</key>
		<dict>
			<key>name</key>
			<string>meta.list.ty.wit</string>
			<key>begin</key>
			<string>\b(list)\b(\&lt;)</string>
			<key>end</key>
			<string>(\&gt;)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.types.list.wit</string>
					<key>include</key>
					<string>#types</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#whitespace</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.list.wit</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.brackets.angle.begin.wit</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.brackets.angle.end.wit</string>
				</dict>
			</dict>
			<key>applyEndPatternLast</key>
			<true />
		</dict>
		<key>markdown</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\G\s*(#+.*)$</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>markup.heading.markdown</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>\G\s*((\&gt;)\s+)+</string>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.quote.begin.markdown</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>\G\s*(\-)\s+</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.list.begin.markdown</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>\G\s*(([0-9]+\.)\s+)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>markup.list.numbered.markdown</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.list.begin.markdown</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>(`.*?`)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>markup.italic.markdown</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(__.*?__)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>markup.bold.markdown</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(_.*?_)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>markup.italic.markdown</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>(\*\*.*?\*\*)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>markup.bold.markdown</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>(\*.*?\*)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>markup.italic.markdown</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>named-type-list</key>
		<dict>
			<key>name</key>
			<string>meta.named-type-list.wit</string>
			<key>begin</key>
			<string>\b%?((?&lt;![\-\w])([a-z][0-9a-z]*|[A-Z][0-9A-Z]*)(([\-])([a-z][0-9a-z]*|[A-Z][0-9A-Z]*))*)\b\s*(\:)</string>
			<key>end</key>
			<string>((\,)|(?=\))|(?=\n))</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#types</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#whitespace</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.id.named-type.wit</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.key-value.wit</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.comma.wit</string>
				</dict>
			</dict>
			<key>applyEndPatternLast</key>
			<true />
		</dict>
		<key>numeric</key>
		<dict>
			<key>name</key>
			<string>entity.name.type.numeric.wit</string>
			<key>match</key>
			<string>\b(u8|u16|u32|u64|s8|s16|s32|s64|float32|float64)\b</string>
		</dict>
		<key>operator</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>punctuation.equal.wit</string>
					<key>match</key>
					<string>\=</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.comma.wit</string>
					<key>match</key>
					<string>\,</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.key-value.wit</string>
					<key>match</key>
					<string>\:</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.semicolon.wit</string>
					<key>match</key>
					<string>\;</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.brackets.round.begin.wit</string>
					<key>match</key>
					<string>\(</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.brackets.round.end.wit</string>
					<key>match</key>
					<string>\)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.brackets.curly.begin.wit</string>
					<key>match</key>
					<string>\{</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.brackets.curly.end.wit</string>
					<key>match</key>
					<string>\}</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.brackets.angle.begin.wit</string>
					<key>match</key>
					<string>\&lt;</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.brackets.angle.end.wit</string>
					<key>match</key>
					<string>\&gt;</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.star.wit</string>
					<key>match</key>
					<string>\*</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.arrow.skinny.wit</string>
					<key>match</key>
					<string>\-\&gt;</string>
				</dict>
			</array>
		</dict>
		<key>option</key>
		<dict>
			<key>name</key>
			<string>meta.option.ty.wit</string>
			<key>begin</key>
			<string>\b(option)\b(\&lt;)</string>
			<key>end</key>
			<string>(\&gt;)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.types.option.wit</string>
					<key>include</key>
					<string>#types</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#whitespace</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.option.wit</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.brackets.angle.begin.wit</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.brackets.angle.end.wit</string>
				</dict>
			</dict>
			<key>applyEndPatternLast</key>
			<true />
		</dict>
		<key>package</key>
		<dict>
			<key>name</key>
			<string>meta.package-decl.wit</string>
			<key>match</key>
			<string>^(package)\s+([^\s]+)\s*</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.package-decl.wit</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.id.package-decl.wit</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>meta.package-identifier.wit</string>
							<key>match</key>
							<string>([^\:]+)(\:)([^\@]+)((\@)([^\s]+))?</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.name.namespace.package-identifier.wit</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#identifier</string>
										</dict>
									</array>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.namespace.package-identifier.wit</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>entity.name.type.package-identifier.wit</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#identifier</string>
										</dict>
									</array>
								</dict>
								<key>5</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.versioning.package-identifier.wit</string>
								</dict>
								<key>6</key>
								<dict>
									<key>name</key>
									<string>constant.numeric.versioning.package-identifier.wit</string>
								</dict>
							</dict>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>parameter-list</key>
		<dict>
			<key>name</key>
			<string>meta.param-list.wit</string>
			<key>begin</key>
			<string>(\()</string>
			<key>end</key>
			<string>(\))</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#named-type-list</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#whitespace</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.brackets.round.begin.wit</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.brackets.round.end.wit</string>
				</dict>
			</dict>
			<key>applyEndPatternLast</key>
			<true />
		</dict>
		<key>primitive</key>
		<dict>
			<key>name</key>
			<string>meta.primitive.ty.wit</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#numeric</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
			</array>
		</dict>
		<key>record</key>
		<dict>
			<key>name</key>
			<string>meta.record-item.wit</string>
			<key>begin</key>
			<string>\b(record)\b\s+%?((?&lt;![\-\w])([a-z][0-9a-z]*|[A-Z][0-9A-Z]*)(([\-])([a-z][0-9a-z]*|[A-Z][0-9A-Z]*))*)\s*(\{)</string>
			<key>end</key>
			<string>(\})</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#record-fields</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#whitespace</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.declaration.record.record-item.wit</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.id.record-item.wit</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>punctuation.brackets.curly.begin.wit</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.brackets.curly.end.wit</string>
				</dict>
			</dict>
			<key>applyEndPatternLast</key>
			<true />
		</dict>
		<key>record-fields</key>
		<dict>
			<key>name</key>
			<string>meta.record-fields.wit</string>
			<key>begin</key>
			<string>\b%?((?&lt;![\-\w])([a-z][0-9a-z]*|[A-Z][0-9A-Z]*)(([\-])([a-z][0-9a-z]*|[A-Z][0-9A-Z]*))*)\b\s*(\:)</string>
			<key>end</key>
			<string>((\,)|(?=\})|(?=\n))</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.types.record-fields.wit</string>
					<key>include</key>
					<string>#types</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#whitespace</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.declaration.id.record-fields.wit</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.key-value.wit</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.comma.wit</string>
				</dict>
			</dict>
			<key>applyEndPatternLast</key>
			<true />
		</dict>
		<key>resource</key>
		<dict>
			<key>name</key>
			<string>meta.resource-item.wit</string>
			<key>begin</key>
			<string>\b(resource)\b\s+%?((?&lt;![\-\w])([a-z][0-9a-z]*|[A-Z][0-9A-Z]*)(([\-])([a-z][0-9a-z]*|[A-Z][0-9A-Z]*))*)</string>
			<key>end</key>
			<string>((?&lt;=\n)|(?=\}))</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#resource-methods</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#whitespace</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.resource.wit</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.id.resource.wit</string>
				</dict>
			</dict>
			<key>applyEndPatternLast</key>
			<true />
		</dict>
		<key>resource-methods</key>
		<dict>
			<key>name</key>
			<string>meta.resource-methods.wit</string>
			<key>begin</key>
			<string>(\{)</string>
			<key>end</key>
			<string>(\})</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.constructor-type.wit</string>
					<key>begin</key>
					<string>\b(constructor)\b</string>
					<key>end</key>
					<string>((?&lt;=\n)|(?=\}))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#parameter-list</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#whitespace</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.constructor.constructor-type.wit</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.brackets.round.begin.wit</string>
						</dict>
					</dict>
					<key>applyEndPatternLast</key>
					<true />
				</dict>
				<dict>
					<key>include</key>
					<string>#function</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#whitespace</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.brackets.curly.begin.wit</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.brackets.curly.end.wit</string>
				</dict>
			</dict>
			<key>applyEndPatternLast</key>
			<true />
		</dict>
		<key>result</key>
		<dict>
			<key>name</key>
			<string>meta.result.ty.wit</string>
			<key>begin</key>
			<string>\b(result)\b</string>
			<key>end</key>
			<string>((?&lt;=\n)|(?=\,)|(?=\}))</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.inner.result.wit</string>
					<key>begin</key>
					<string>(\&lt;)</string>
					<key>end</key>
					<string>(\&gt;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
						<dict>
							<key>name</key>
							<string>variable.other.inferred-type.result.wit</string>
							<key>match</key>
							<string>(?&lt;!\w)(\_)(?!\w)</string>
						</dict>
						<dict>
							<key>name</key>
							<string>meta.types.result.wit</string>
							<key>include</key>
							<string>#types</string>
						</dict>
						<dict>
							<key>name</key>
							<string>punctuation.comma.wit</string>
							<key>match</key>
							<string>(?&lt;!result)\s*(\,)</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#whitespace</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.brackets.angle.begin.wit</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.brackets.angle.end.wit</string>
						</dict>
					</dict>
					<key>applyEndPatternLast</key>
					<true />
				</dict>
				<dict>
					<key>include</key>
					<string>#whitespace</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.result.wit</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.brackets.angle.begin.wit</string>
				</dict>
			</dict>
			<key>applyEndPatternLast</key>
			<true />
		</dict>
		<key>result-list</key>
		<dict>
			<key>name</key>
			<string>meta.result-list.wit</string>
			<key>begin</key>
			<string>(\-\&gt;)</string>
			<key>end</key>
			<string>((?&lt;=\n)|(?=\}))</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#types</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#parameter-list</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#whitespace</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.arrow.skinny.wit</string>
				</dict>
			</dict>
			<key>applyEndPatternLast</key>
			<true />
		</dict>
		<key>string</key>
		<dict>
			<key>name</key>
			<string>entity.name.type.string.wit</string>
			<key>match</key>
			<string>\b(string|char)\b</string>
		</dict>
		<key>toplevel-use</key>
		<dict>
			<key>name</key>
			<string>meta.toplevel-use-item.wit</string>
			<key>match</key>
			<string>^(use)\s+([^\s]+)(\s+(as)\s+([^\s]+))?\s*</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.use.toplevel-use-item.wit</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.interface.toplevel-use-item.wit</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>entity.name.type.declaration.interface.toplevel-use-item.wit</string>
							<key>match</key>
							<string>\b%?((?&lt;![\-\w])([a-z][0-9a-z]*|[A-Z][0-9A-Z]*)(([\-])([a-z][0-9a-z]*|[A-Z][0-9A-Z]*))*)\b</string>
						</dict>
						<dict>
							<key>name</key>
							<string>meta.versioning.interface.toplevel-use-item.wit</string>
							<key>match</key>
							<string>(\@)((0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?)</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.versioning.interface.toplevel-use-item.wit</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>constant.numeric.versioning.interface.toplevel-use-item.wit</string>
								</dict>
							</dict>
						</dict>
					</array>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.control.as.toplevel-use-item.wit</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.toplevel-use-item.wit</string>
				</dict>
			</dict>
		</dict>
		<key>tuple</key>
		<dict>
			<key>name</key>
			<string>meta.tuple.ty.wit</string>
			<key>begin</key>
			<string>\b(tuple)\b(\&lt;)</string>
			<key>end</key>
			<string>(\&gt;)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.types.tuple.wit</string>
					<key>include</key>
					<string>#types</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.comma.wit</string>
					<key>match</key>
					<string>(\,)</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#whitespace</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.tuple.wit</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.brackets.angle.begin.wit</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.brackets.angle.end.wit</string>
				</dict>
			</dict>
			<key>applyEndPatternLast</key>
			<true />
		</dict>
		<key>type-definition</key>
		<dict>
			<key>name</key>
			<string>meta.type-item.wit</string>
			<key>begin</key>
			<string>\b(type)\b\s+%?((?&lt;![\-\w])([a-z][0-9a-z]*|[A-Z][0-9A-Z]*)(([\-])([a-z][0-9a-z]*|[A-Z][0-9A-Z]*))*)\s*(\=)</string>
			<key>end</key>
			<string>(?&lt;=\n)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.types.type-item.wit</string>
					<key>include</key>
					<string>#types</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#whitespace</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.declaration.type.type-item.wit storage.type.wit</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.id.type-item.wit</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>punctuation.equal.wit</string>
				</dict>
			</dict>
			<key>applyEndPatternLast</key>
			<true />
		</dict>
		<key>typedef-item</key>
		<dict>
			<key>name</key>
			<string>meta.typedef-item.wit</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#resource</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variant</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#record</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#flags</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#enum</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#type-definition</string>
				</dict>
			</array>
		</dict>
		<key>types</key>
		<dict>
			<key>name</key>
			<string>meta.ty.wit</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#primitive</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#container</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#identifier</string>
				</dict>
			</array>
		</dict>
		<key>use</key>
		<dict>
			<key>name</key>
			<string>meta.use-item.wit</string>
			<key>begin</key>
			<string>\b(use)\b\s+([^\s]+)(\.)(\{)</string>
			<key>end</key>
			<string>(\})</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>name</key>
					<string>entity.name.type.declaration.use-names-item.use-item.wit</string>
					<key>match</key>
					<string>\b%?((?&lt;![\-\w])([a-z][0-9a-z]*|[A-Z][0-9A-Z]*)(([\-])([a-z][0-9a-z]*|[A-Z][0-9A-Z]*))*)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.comma.wit</string>
					<key>match</key>
					<string>(\,)</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#whitespace</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.use.use-item.wit</string>
				</dict>
				<key>2</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#use-path</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#whitespace</string>
						</dict>
					</array>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.namespace-separator.use-item.wit</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.brackets.curly.begin.wit</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.brackets.curly.end.wit</string>
				</dict>
			</dict>
			<key>applyEndPatternLast</key>
			<true />
		</dict>
		<key>use-path</key>
		<dict>
			<key>name</key>
			<string>meta.use-path.wit</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>entity.name.namespace.id.use-path.wit</string>
					<key>match</key>
					<string>\b%?((?&lt;![\-\w])([a-z][0-9a-z]*|[A-Z][0-9A-Z]*)(([\-])([a-z][0-9a-z]*|[A-Z][0-9A-Z]*))*)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.versioning.id.use-path.wit</string>
					<key>match</key>
					<string>(\@)((0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.versioning.id.use-path.wit</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.versioning.id.use-path.wit</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.namespace-separator.use-path.wit</string>
					<key>match</key>
					<string>\.</string>
				</dict>
			</array>
		</dict>
		<key>variant</key>
		<dict>
			<key>name</key>
			<string>meta.variant.wit</string>
			<key>begin</key>
			<string>\b(variant)\s+%?((?&lt;![\-\w])([a-z][0-9a-z]*|[A-Z][0-9A-Z]*)(([\-])([a-z][0-9a-z]*|[A-Z][0-9A-Z]*))*)\s*(\{)</string>
			<key>end</key>
			<string>(\})</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variant-cases</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#enum-cases</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#whitespace</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.variant.wit</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.id.variant.wit</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>punctuation.brackets.curly.begin.wit</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.brackets.curly.end.wit</string>
				</dict>
			</dict>
			<key>applyEndPatternLast</key>
			<true />
		</dict>
		<key>variant-cases</key>
		<dict>
			<key>name</key>
			<string>meta.variant-cases.wit</string>
			<key>begin</key>
			<string>\b%?((?&lt;![\-\w])([a-z][0-9a-z]*|[A-Z][0-9A-Z]*)(([\-])([a-z][0-9a-z]*|[A-Z][0-9A-Z]*))*)\b\s*(\()</string>
			<key>end</key>
			<string>(\))\s*(\,)?</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.types.variant-cases.wit</string>
					<key>include</key>
					<string>#types</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#whitespace</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.enummember.id.variant-cases.wit</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>punctuation.brackets.round.begin.wit</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.brackets.round.end.wit</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.comma.wit</string>
				</dict>
			</dict>
			<key>applyEndPatternLast</key>
			<true />
		</dict>
		<key>whitespace</key>
		<dict>
			<key>name</key>
			<string>meta.whitespace.wit</string>
			<key>match</key>
			<string>\s+</string>
		</dict>
		<key>world</key>
		<dict>
			<key>name</key>
			<string>meta.world-item.wit</string>
			<key>begin</key>
			<string>^\b(default\s+)?(world)\s+%?((?&lt;![\-\w])([a-z][0-9a-z]*|[A-Z][0-9A-Z]*)(([\-])([a-z][0-9a-z]*|[A-Z][0-9A-Z]*))*)\s*(\{)</string>
			<key>end</key>
			<string>(\})</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.export-item.wit</string>
					<key>begin</key>
					<string>\b(export)\b\s+([^\s]+)</string>
					<key>end</key>
					<string>((?&lt;=\n)|(?=\}))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#extern</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#whitespace</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.export.export-item.wit</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.id.export-item.wit</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>name</key>
									<string>variable.other.constant.id.export-item.wit</string>
									<key>match</key>
									<string>\b%?((?&lt;![\-\w])([a-z][0-9a-z]*|[A-Z][0-9A-Z]*)(([\-])([a-z][0-9a-z]*|[A-Z][0-9A-Z]*))*)\b</string>
								</dict>
								<dict>
									<key>name</key>
									<string>meta.versioning.id.export-item.wit</string>
									<key>match</key>
									<string>(\@)((0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?)</string>
									<key>captures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>keyword.operator.versioning.id.export-item.wit</string>
										</dict>
										<key>2</key>
										<dict>
											<key>name</key>
											<string>constant.numeric.versioning.id.export-item.wit</string>
										</dict>
									</dict>
								</dict>
							</array>
						</dict>
					</dict>
					<key>applyEndPatternLast</key>
					<true />
				</dict>
				<dict>
					<key>name</key>
					<string>meta.import-item.wit</string>
					<key>begin</key>
					<string>\b(import)\s+([^\s]+)</string>
					<key>end</key>
					<string>((?&lt;=\n)|(?=\}))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#extern</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#whitespace</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.import.import-item.wit</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.id.import-item.wit</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>name</key>
									<string>variable.other.id.import-item.wit</string>
									<key>match</key>
									<string>\b%?((?&lt;![\-\w])([a-z][0-9a-z]*|[A-Z][0-9A-Z]*)(([\-])([a-z][0-9a-z]*|[A-Z][0-9A-Z]*))*)\b</string>
								</dict>
								<dict>
									<key>name</key>
									<string>meta.versioning.id.import-item.wit</string>
									<key>match</key>
									<string>(\@)((0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?)</string>
									<key>captures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>keyword.operator.versioning.id.import-item.wit</string>
										</dict>
										<key>2</key>
										<dict>
											<key>name</key>
											<string>constant.numeric.versioning.id.import-item.wit</string>
										</dict>
									</dict>
								</dict>
							</array>
						</dict>
					</dict>
					<key>applyEndPatternLast</key>
					<true />
				</dict>
				<dict>
					<key>name</key>
					<string>meta.include-item.wit</string>
					<key>begin</key>
					<string>\b(include)\s+([^\s]+)\s*</string>
					<key>end</key>
					<string>(?&lt;=\n)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>meta.with.include-item.wit</string>
							<key>begin</key>
							<string>\b(with)\b\s+(\{)</string>
							<key>end</key>
							<string>(\})</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#comment</string>
								</dict>
								<dict>
									<key>name</key>
									<string>meta.include-names-item.wit</string>
									<key>match</key>
									<string>([^\s]+)\s+(as)\s+([^\s\,]+)</string>
									<key>captures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>variable.other.id.include-names-item.wit</string>
										</dict>
										<key>2</key>
										<dict>
											<key>name</key>
											<string>keyword.control.as.include-names-item.wit</string>
										</dict>
										<key>3</key>
										<dict>
											<key>name</key>
											<string>entity.name.type.include-names-item.wit</string>
										</dict>
									</dict>
								</dict>
								<dict>
									<key>name</key>
									<string>punctuation.comma.wit</string>
									<key>match</key>
									<string>(\,)</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#whitespace</string>
								</dict>
							</array>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.control.with.include-item.wit</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.brackets.curly.begin.wit</string>
								</dict>
							</dict>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.brackets.curly.end.wit</string>
								</dict>
							</dict>
							<key>applyEndPatternLast</key>
							<true />
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.include.include-item.wit</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.use-path.include-item.wit</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#use-path</string>
								</dict>
							</array>
						</dict>
					</dict>
					<key>applyEndPatternLast</key>
					<true />
				</dict>
				<dict>
					<key>include</key>
					<string>#use</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#typedef-item</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#whitespace</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.default.world-item.wit</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.declaration.world.world-item.wit storage.type.wit</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.id.world-item.wit</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>punctuation.brackets.curly.begin.wit</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.brackets.curly.end.wit</string>
				</dict>
			</dict>
			<key>applyEndPatternLast</key>
			<true />
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>wit</string>
	</array>
</dict>
</plist>
