<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>WebVTT</string>
	<key>scopeName</key>
	<string>text.vtt</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>name</key>
			<string>meta.file-body.vtt</string>
			<key>begin</key>
			<string>\A﻿?(WEBVTT)(?=$|[ \t])</string>
			<key>end</key>
			<string>(?=A)B</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.header.vtt</string>
					<key>contentName</key>
					<string>comment.line.ignored.vtt</string>
					<key>begin</key>
					<string>\G</string>
					<key>end</key>
					<string>^[ \t]*$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#setting</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#main</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.start-file.vtt</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>include</key>
			<string>#main</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>badArrow</key>
		<dict>
			<key>name</key>
			<string>invalid.illegal.syntax.unexpected-separator.vtt</string>
			<key>match</key>
			<string>\S*?--&gt;\S*</string>
		</dict>
		<key>charRef</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.basic#character-reference</string>
				</dict>
			</array>
		</dict>
		<key>class</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>support.constant.colour.foreground.$2.vtt</string>
					<key>match</key>
					<string>(\.)(black|blue|cyan|lime|magenta|red|white|yellow)(?=$|[\s&amp;&lt;&gt;.])</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entity.class.vtt</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>support.constant.colour.background.$2.vtt</string>
					<key>match</key>
					<string>(\.)bg_(black|blue|cyan|lime|magenta|red|white|yellow)(?=$|[\s&amp;&lt;&gt;.])</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entity.class.vtt</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.class.vtt</string>
					<key>match</key>
					<string>(\.)[^\s&amp;&lt;&gt;.]+</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entity.class.vtt</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>name</key>
			<string>comment.block.vtt</string>
			<key>begin</key>
			<string>^NOTE(?=$|\s)</string>
			<key>end</key>
			<string>^[ \t]*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>storage.type.start-comment.vtt</string>
				</dict>
			</dict>
		</dict>
		<key>cue</key>
		<dict>
			<key>name</key>
			<string>meta.cue.block.vtt</string>
			<key>begin</key>
			<string>(?x)
(?=
	^
	(?:\d{2,}:)?\d{2}:\d{2}\.\d{3}  # Start time
	[ \t]+ --&gt; [ \t]+                  # Separator
	(?:\d{2,}:)?\d{2}:\d{2}\.\d{3}  # End time
	(?:$|[ \t])
)
|
# Cue identifier
^((?!.*?--&gt;)[^\r\n]+)$</string>
			<key>end</key>
			<string>^[ \t]*$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#cueTimings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cuePayload</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.cue.vtt</string>
				</dict>
			</dict>
		</dict>
		<key>cueComponents</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#cueSpan</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cueTimestamp</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cueDash</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#charRef</string>
				</dict>
			</array>
		</dict>
		<key>cueDash</key>
		<dict>
			<key>name</key>
			<string>markup.quote.quotation-dash.vtt</string>
			<key>match</key>
			<string>(?:^|\G)([-–—―⸺⸻〜〰︱︲﹘﹣－])</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.quote.vtt</string>
				</dict>
			</dict>
		</dict>
		<key>cuePayload</key>
		<dict>
			<key>name</key>
			<string>meta.cue.payload.vtt</string>
			<key>begin</key>
			<string>^(?=[ \t]*\S)</string>
			<key>end</key>
			<string>(?=^[ \t]*$)(?!\G)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#cueComponents</string>
				</dict>
			</array>
		</dict>
		<key>cueSettings</key>
		<dict>
			<key>name</key>
			<string>meta.cue.settings-list.vtt</string>
			<key>begin</key>
			<string>(?&lt;=[ \t]|^)(?!$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#badArrow</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#setting</string>
				</dict>
			</array>
		</dict>
		<key>cueSpan</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.span.class-span.vtt</string>
					<key>begin</key>
					<string>(&lt;)(c)(?=$|\s|/?&gt;|\.)</string>
					<key>end</key>
					<string>(?=^[ \t]*$)|((&lt;/)(c)\s*(&gt;))|(/&gt;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#cueSpanStart</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#cueSpanBody</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.tag.opening.vtt</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.vtt</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.vtt</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.tag.closing.vtt</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.vtt</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.vtt</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.vtt</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.self-closing.vtt</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.span.italics-span.vtt</string>
					<key>begin</key>
					<string>(&lt;)(i)(?=$|\s|/?&gt;|\.)</string>
					<key>end</key>
					<string>(?=^[ \t]*$)|((&lt;/)(i)\s*(&gt;))|(/&gt;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#cueSpanStart</string>
						</dict>
						<dict>
							<key>name</key>
							<string>markup.italic.vtt</string>
							<key>begin</key>
							<string>(?&lt;=&gt;)</string>
							<key>end</key>
							<string>(?=&lt;/[A-Za-z_:]|^[ \t]*$)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#cueComponents</string>
								</dict>
							</array>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.tag.opening.vtt</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.vtt</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.vtt</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.tag.closing.vtt</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.vtt</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.vtt</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.vtt</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.self-closing.vtt</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.span.bold-span.vtt</string>
					<key>begin</key>
					<string>(&lt;)(b)(?=$|\s|/?&gt;|\.)</string>
					<key>end</key>
					<string>(?=^[ \t]*$)|((&lt;/)(b)\s*(&gt;))|(/&gt;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#cueSpanStart</string>
						</dict>
						<dict>
							<key>name</key>
							<string>markup.bold.vtt</string>
							<key>begin</key>
							<string>(?&lt;=&gt;)</string>
							<key>end</key>
							<string>(?=&lt;/[A-Za-z_:]|^[ \t]*$)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#cueComponents</string>
								</dict>
							</array>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.tag.opening.vtt</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.vtt</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.vtt</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.tag.closing.vtt</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.vtt</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.vtt</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.vtt</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.self-closing.vtt</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.span.underline-span.vtt</string>
					<key>begin</key>
					<string>(&lt;)(u)(?=$|\s|/?&gt;|\.)</string>
					<key>end</key>
					<string>(?=^[ \t]*$)|((&lt;/)(u)\s*(&gt;))|(/&gt;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#cueSpanStart</string>
						</dict>
						<dict>
							<key>name</key>
							<string>markup.underline.vtt</string>
							<key>contentName</key>
							<string>string.other.link.vtt</string>
							<key>begin</key>
							<string>(?&lt;=&gt;)</string>
							<key>end</key>
							<string>(?=&lt;/[A-Za-z_:]|^[ \t]*$)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#cueComponents</string>
								</dict>
							</array>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.tag.opening.vtt</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.vtt</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.vtt</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.tag.closing.vtt</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.vtt</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.vtt</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.vtt</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.self-closing.vtt</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.span.ruby-span.vtt</string>
					<key>begin</key>
					<string>(&lt;)(ruby)(?=$|\s|/?&gt;|\.)</string>
					<key>end</key>
					<string>(?=^[ \t]*$)|((&lt;/)(ruby)\s*(&gt;))|(/&gt;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#cueSpanStart</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#cueSpanBody</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.tag.opening.vtt</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.vtt</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.vtt</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.tag.closing.vtt</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.vtt</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.vtt</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.vtt</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.self-closing.vtt</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.span.ruby-text-span.vtt</string>
					<key>begin</key>
					<string>(&lt;)(rt)(?=$|\s|/?&gt;|\.)</string>
					<key>end</key>
					<string>(?=^[ \t]*$)|((&lt;/)(rt)\s*(&gt;))|(/&gt;)|(?=\s*&lt;/ruby\s*&gt;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#cueSpanStart</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#cueSpanBody</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.tag.opening.vtt</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.vtt</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.vtt</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.tag.closing.vtt</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.vtt</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.vtt</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.vtt</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.self-closing.vtt</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.span.voice-span.vtt</string>
					<key>begin</key>
					<string>(&lt;)(v)(?=$|\s|/?&gt;|\.)</string>
					<key>end</key>
					<string>(?=^[ \t]*$)|((&lt;/)(v)\s*(&gt;))|(/&gt;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>meta.tag.opening.vtt</string>
							<key>begin</key>
							<string>\G(?!\s*/&gt;)((?:\.[^\s&amp;&lt;&gt;.]+)*\.?)?</string>
							<key>end</key>
							<string>&gt;|(?=\s*/&gt;|^[ \t]*$)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>name</key>
									<string>meta.annotation.vtt</string>
									<key>contentName</key>
									<string>entity.name.voice.vtt</string>
									<key>begin</key>
									<string>(?:[ \t]|^|\G)(?=\S)(?!&gt;|&amp;)</string>
									<key>end</key>
									<string>(?=$|&gt;|&amp;|^[ \t]*$)</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#charRef</string>
										</dict>
									</array>
								</dict>
							</array>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#class</string>
										</dict>
									</array>
								</dict>
							</dict>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.end.vtt</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>include</key>
							<string>#cueSpanBody</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.tag.opening.vtt</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.vtt</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.vtt</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.tag.closing.vtt</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.vtt</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.vtt</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.vtt</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.self-closing.vtt</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.span.language-span.vtt</string>
					<key>begin</key>
					<string>(&lt;)(lang)(?=$|\s|/?&gt;|\.)</string>
					<key>end</key>
					<string>(?=^[ \t]*$)|((&lt;/)(lang)\s*(&gt;))|(/&gt;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>meta.tag.opening.vtt</string>
							<key>begin</key>
							<string>\G(?!\s*/&gt;)((?:\.[^\s&amp;&lt;&gt;.]+)*\.?)?</string>
							<key>end</key>
							<string>&gt;|(?=\s*/&gt;|^[ \t]*$)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>name</key>
									<string>meta.annotation.vtt</string>
									<key>contentName</key>
									<string>constant.language.locale.bcp47.vtt</string>
									<key>begin</key>
									<string>(?:[ \t]|^|\G)(?=\S)(?!&gt;|&amp;)</string>
									<key>end</key>
									<string>(?=$|&gt;|&amp;|^[ \t]*$)</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#charRef</string>
										</dict>
									</array>
								</dict>
							</array>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#class</string>
										</dict>
									</array>
								</dict>
							</dict>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.end.vtt</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>include</key>
							<string>#cueSpanBody</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.tag.opening.vtt</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.vtt</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.vtt</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.tag.closing.vtt</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.vtt</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.vtt</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.vtt</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.self-closing.vtt</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.span.$2-span.vtt</string>
					<key>begin</key>
					<string>(&lt;)([A-Za-z_:][-\w:]*)(?=$|\s|/?&gt;|\.)</string>
					<key>end</key>
					<string>(?=^[ \t]*$)|((&lt;/)(\2)\s*(&gt;))|(/&gt;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>meta.tag.opening.vtt</string>
							<key>begin</key>
							<string>\G(?!\s*/&gt;)((?:\.[^\s&amp;&lt;&gt;.]+)*\.?)?</string>
							<key>end</key>
							<string>&gt;|(?=\s*/&gt;|^[ \t]*$)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>name</key>
									<string>meta.annotation.vtt</string>
									<key>contentName</key>
									<string>string.unquoted.annotation.vtt</string>
									<key>begin</key>
									<string>(?:[ \t]|^|\G)(?=\S)(?!&gt;|&amp;)</string>
									<key>end</key>
									<string>(?=$|&gt;|&amp;|^[ \t]*$)</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#charRef</string>
										</dict>
									</array>
								</dict>
							</array>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#class</string>
										</dict>
									</array>
								</dict>
							</dict>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.end.vtt</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>include</key>
							<string>#cueSpanBody</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.tag.opening.vtt</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.vtt</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.vtt</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.tag.closing.vtt</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.vtt</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.vtt</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.vtt</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.self-closing.vtt</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>cueSpanBody</key>
		<dict>
			<key>name</key>
			<string>meta.content.vtt</string>
			<key>begin</key>
			<string>(?&lt;=&gt;)</string>
			<key>end</key>
			<string>(?=&lt;/[A-Za-z_:]|^[ \t]*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#cueComponents</string>
				</dict>
			</array>
		</dict>
		<key>cueSpanStart</key>
		<dict>
			<key>name</key>
			<string>meta.tag.opening.vtt</string>
			<key>contentName</key>
			<string>invalid.illegal.unexpected-annotation.vtt</string>
			<key>begin</key>
			<string>\G(?!\s*/&gt;)((?:\.[^\s&amp;&lt;&gt;.]+)*\.?)?</string>
			<key>end</key>
			<string>&gt;|(?=\s*/&gt;|^[ \t]*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#charRef</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#class</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.vtt</string>
				</dict>
			</dict>
		</dict>
		<key>cueTimestamp</key>
		<dict>
			<key>name</key>
			<string>constant.other.cue-timestamp.vtt</string>
			<key>match</key>
			<string>(&lt;)((?:\d{2,}:)?\d{2}:\d{2}\.\d{3})(&gt;)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.timestamp.begin.vtt</string>
				</dict>
				<key>2</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#timestamp</string>
						</dict>
					</array>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.timestamp.end.vtt</string>
				</dict>
			</dict>
		</dict>
		<key>cueTimings</key>
		<dict>
			<key>name</key>
			<string>meta.cue.timings.vtt</string>
			<key>begin</key>
			<string>(?x) (?:^|\G)
((?:\d{2,}:)?\d{2}:\d{2}\.\d{3}) # Start time
[ \t]+ (--&gt;) [ \t]+                 # Separator
((?:\d{2,}:)?\d{2}:\d{2}\.\d{3}) # End time
(?=$|[ \t])  [ \t]*                 # Gap before “#cueSettings”</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#cueSettings</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.start-time.vtt</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#timestamp</string>
						</dict>
					</array>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.timespan.vtt</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>meta.end-time.vtt</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#timestamp</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>main</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#region</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#style</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cue</string>
				</dict>
			</array>
		</dict>
		<key>region</key>
		<dict>
			<key>name</key>
			<string>meta.region-definition.block.vtt</string>
			<key>begin</key>
			<string>^(REGION)[ \t]*$</string>
			<key>end</key>
			<string>^[ \t]*$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.setting.with-value.vtt</string>
					<key>match</key>
					<string>^(id)(:)(?:(.*?--&gt;.*?)|(\S+))</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.assignment.setting-name.vtt</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.assignment.key-value.colon.vtt</string>
						</dict>
						<key>3</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#badArrow</string>
								</dict>
							</array>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.name.region.vtt</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>include</key>
					<string>#setting</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.region.vtt</string>
				</dict>
			</dict>
		</dict>
		<key>setting</key>
		<dict>
			<key>name</key>
			<string>meta.setting.generic.vtt</string>
			<key>begin</key>
			<string>([^\s:]+?)(:)</string>
			<key>end</key>
			<string>(?!\G)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\G(?=[ \t]*\S)</string>
					<key>end</key>
					<string>(?!\G)(?=\s|$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(?&lt;=scroll:)\G([ \t]*)(up)(?=$|\s)</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.whitespace.inline.vtt</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>constant.language.scroll-setting.vtt</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>match</key>
							<string>(?&lt;=vertical:)\G([ \t]*)(rl|lr)(?=$|\s)</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.whitespace.inline.vtt</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>constant.language.vertical-setting.vtt</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>match</key>
							<string>(?&lt;=line:)\G([ \t]*)(start|center|end)(?=$|\s)</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.whitespace.inline.vtt</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>constant.language.line-setting.vtt</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>match</key>
							<string>(?&lt;=position:)\G([ \t]*)([0-9]+%,)(center|line-left|line-right)(?=$|\s)</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.whitespace.inline.vtt</string>
								</dict>
								<key>2</key>
								<dict>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#settingValue</string>
										</dict>
									</array>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>constant.language.position-setting.vtt</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>match</key>
							<string>(?&lt;=align:)\G([ \t]*)(center|end|left|right|start)(?=$|\s)</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.whitespace.inline.vtt</string>
								</dict>
								<key>2</key>
								<dict>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#settingValue</string>
										</dict>
									</array>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>constant.language.align-setting.vtt</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>include</key>
							<string>#settingValue</string>
						</dict>
					</array>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.setting-name.vtt</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.key-value.colon.vtt</string>
				</dict>
			</dict>
		</dict>
		<key>settingValue</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.numeric.percentage.vtt</string>
					<key>match</key>
					<string>[0-9]+(?:\.[0-9]+)?(%)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.percentage.vtt</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.integer.int.vtt</string>
					<key>match</key>
					<string>[0-9]+\b(?!%|\.[0-9])</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.auto.vtt</string>
					<key>match</key>
					<string>\bauto\b(?=$|\s|,)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.separator.delimiter.comma.vtt</string>
					<key>match</key>
					<string>,</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#badArrow</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.other.setting-value.vtt</string>
					<key>match</key>
					<string>.+</string>
				</dict>
			</array>
		</dict>
		<key>style</key>
		<dict>
			<key>name</key>
			<string>meta.style.block.vtt</string>
			<key>contentName</key>
			<string>source.embedded.css</string>
			<key>begin</key>
			<string>^(STYLE)[ \t]*$</string>
			<key>end</key>
			<string>^[ \t]*$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.css</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.style.vtt</string>
				</dict>
			</dict>
		</dict>
		<key>timestamp</key>
		<dict>
			<key>name</key>
			<string>meta.timestamp.vtt</string>
			<key>match</key>
			<string>(?x)
(?:(\d{2,})(:))?            # Hours        (≥ 00)
(?:([0-5]\d)|(\d{2}))(:)   # Minutes      (00-59)
(?:([0-5]\d)|(\d{2}))(\.) # Seconds      (00-59)
(\d{3})                     # Milliseconds (000-999)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.timestamp.unit.hour.vtt</string>
				</dict>
				<key>2</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#timestampColon</string>
						</dict>
					</array>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.timestamp.unit.minute.vtt</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.value.out-of-range.vtt</string>
				</dict>
				<key>5</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#timestampColon</string>
						</dict>
					</array>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.timestamp.unit.second.vtt</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.value.out-of-range.vtt</string>
				</dict>
				<key>8</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#timestampDecimal</string>
						</dict>
					</array>
				</dict>
				<key>9</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.timestamp.unit.millisecond.vtt</string>
				</dict>
			</dict>
		</dict>
		<key>timestampColon</key>
		<dict>
			<key>name</key>
			<string>meta.separator.colon.vtt</string>
			<key>match</key>
			<string>:</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.delimiter.vtt</string>
				</dict>
			</dict>
		</dict>
		<key>timestampDecimal</key>
		<dict>
			<key>name</key>
			<string>meta.separator.decimal.fraction.radix-point.vtt</string>
			<key>match</key>
			<string>\.</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.decimal.vtt</string>
				</dict>
			</dict>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>vtt</string>
	</array>
</dict>
</plist>
