<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>WebVTT</string>
	<key>scopeName</key>
	<string>source.vtt</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#file_body</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>_cue_timings_and_settings_list</key>
		<dict>
			<key>match</key>
			<string>^(.+?\s+--&gt;\s+.+?)(?:\s+(.+))?$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#cue_timings</string>
						</dict>
					</array>
				</dict>
				<key>2</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#cue_settings_list</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>alignment_cue_setting</key>
		<dict>
			<key>name</key>
			<string>meta.alignment-cue-setting.vtt</string>
			<key>match</key>
			<string>(align)(:)([^\s]+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type.alignment-cue-setting.vtt</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.colon.vtt</string>
				</dict>
				<key>3</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>support.constant.alignment-cue-setting.vtt</string>
							<key>match</key>
							<string>(?:^|\G)(?:start|center|end|left|right)(?=$)</string>
						</dict>
						<dict>
							<key>name</key>
							<string>invalid.illegal.vtt</string>
							<key>match</key>
							<string>.+</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>comment_block</key>
		<dict>
			<key>name</key>
			<string>meta.comment-block.vtt</string>
			<key>begin</key>
			<string>^(NOTE)(?:\s(.*))?$</string>
			<key>end</key>
			<string>^$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>comment.line.character.vtt</string>
					<key>match</key>
					<string>.+</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.section.comment.vtt</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment.line.character.vtt</string>
				</dict>
			</dict>
		</dict>
		<key>cue_block</key>
		<dict>
			<key>name</key>
			<string>meta.cue-block.vtt</string>
			<key>begin</key>
			<string>^.+$</string>
			<key>end</key>
			<string>^$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#_cue_timings_and_settings_list</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cue_text</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#cue_identifier</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#_cue_timings_and_settings_list</string>
						</dict>
						<dict>
							<key>name</key>
							<string>invalid.illegal.vtt</string>
							<key>match</key>
							<string>.+</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>cue_bold_span</key>
		<dict>
			<key>name</key>
			<string>meta.cue-bold-span.vtt</string>
		</dict>
		<key>cue_class_span</key>
		<dict>
			<key>name</key>
			<string>meta.cue-class-span.vtt</string>
		</dict>
		<key>cue_components</key>
		<dict>
			<key>name</key>
			<string>meta.cue-components.vtt</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#cue_class_span</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cue_italics_span</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cue_bold_span</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cue_underline_span</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cue_ruby_span</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cue_voice_span</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cue_language_span</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cue_timestamp</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cue_text_span</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#html_character_reference</string>
				</dict>
			</array>
		</dict>
		<key>cue_identifier</key>
		<dict>
			<key>name</key>
			<string>meta.cue-identifier.vtt</string>
			<key>match</key>
			<string>(?:^|\G)(?!.*--&gt;).*$</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>variable.other.cue-identifier.vtt</string>
				</dict>
			</dict>
		</dict>
		<key>cue_italics_span</key>
		<dict>
			<key>name</key>
			<string>meta.cue-italics-span.vtt</string>
		</dict>
		<key>cue_language_span</key>
		<dict>
			<key>name</key>
			<string>meta.cue-language-span.vtt</string>
		</dict>
		<key>cue_ruby_span</key>
		<dict>
			<key>name</key>
			<string>meta.cue-ruby-span.vtt</string>
		</dict>
		<key>cue_settings_list</key>
		<dict>
			<key>name</key>
			<string>meta.cue-settings-list.vtt</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#vertical_text_cue_setting</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#line_cue_setting</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#position_cue_setting</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#size_cue_setting</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#alignment_cue_setting</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#region_cue_setting</string>
				</dict>
			</array>
		</dict>
		<key>cue_text</key>
		<dict>
			<key>name</key>
			<string>meta.cue-text.vtt</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#cue_components</string>
				</dict>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
			</array>
		</dict>
		<key>cue_text_span</key>
		<dict>
			<key>name</key>
			<string>meta.cue-text-span.vtt</string>
		</dict>
		<key>cue_timestamp</key>
		<dict>
			<key>name</key>
			<string>meta.cue-timestamp.vtt</string>
		</dict>
		<key>cue_timings</key>
		<dict>
			<key>name</key>
			<string>meta.cue-timings.vtt</string>
			<key>match</key>
			<string>(?:^|\G)(.+?)\s+(--&gt;)\s+(.+?)(?=$)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#timestamp</string>
						</dict>
						<dict>
							<key>name</key>
							<string>invalid.illegal.vtt</string>
							<key>match</key>
							<string>.+</string>
						</dict>
					</array>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.vtt</string>
				</dict>
				<key>3</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#timestamp</string>
						</dict>
						<dict>
							<key>name</key>
							<string>invalid.illegal.vtt</string>
							<key>match</key>
							<string>.+</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>cue_underline_span</key>
		<dict>
			<key>name</key>
			<string>meta.cue-underline-span.vtt</string>
		</dict>
		<key>cue_voice_span</key>
		<dict>
			<key>name</key>
			<string>meta.cue-voice-span.vtt</string>
		</dict>
		<key>file_body</key>
		<dict>
			<key>name</key>
			<string>meta.file-body.vtt</string>
			<key>begin</key>
			<string>^(WEBVTT)(?:\s+(.*))?$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#region_definition_block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#style_block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment_block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cue_block</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.section.webvtt.vtt</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment.line.character.vtt</string>
				</dict>
			</dict>
		</dict>
		<key>html_character_reference</key>
		<dict>
			<key>name</key>
			<string>meta.html-character-reference.vtt</string>
		</dict>
		<key>line_cue_setting</key>
		<dict>
			<key>name</key>
			<string>meta.line-cue-setting.vtt</string>
			<key>match</key>
			<string>(line)(:)([^\s]+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type.line-cue-setting.vtt</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.colon.vtt</string>
				</dict>
				<key>3</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(?:^|\G)(.+?)(?:(,)(.+))?(?=$)</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>patterns</key>
									<array>
										<dict>
											<key>name</key>
											<string>constant.numeric.line-cue-setting.vtt</string>
											<key>match</key>
											<string>(?:^|\G)-?\d+(?=$)</string>
										</dict>
										<dict>
											<key>include</key>
											<string>#percentage</string>
										</dict>
										<dict>
											<key>name</key>
											<string>invalid.illegal.vtt</string>
											<key>match</key>
											<string>.+</string>
										</dict>
									</array>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.separator.comma.vtt</string>
								</dict>
								<key>3</key>
								<dict>
									<key>patterns</key>
									<array>
										<dict>
											<key>name</key>
											<string>support.constant.line-cue-setting.vtt</string>
											<key>match</key>
											<string>(?:^|\G)(?:start|center|end)(?=$)</string>
										</dict>
										<dict>
											<key>name</key>
											<string>invalid.illegal.vtt</string>
											<key>match</key>
											<string>.+</string>
										</dict>
									</array>
								</dict>
							</dict>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>percentage</key>
		<dict>
			<key>name</key>
			<string>meta.percentage.vtt</string>
			<key>match</key>
			<string>(?:^|\G)\d+(?:\.\d+)?%(?=$)</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.percentage.vtt</string>
				</dict>
			</dict>
		</dict>
		<key>position_cue_setting</key>
		<dict>
			<key>name</key>
			<string>meta.position-cue-setting.vtt</string>
			<key>match</key>
			<string>(position)(:)([^\s]+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type.position-cue-setting.vtt</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.colon.vtt</string>
				</dict>
				<key>3</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(?:^|\G)(.+?)(?:(,)(.+))?(?=$)</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#percentage</string>
										</dict>
										<dict>
											<key>name</key>
											<string>invalid.illegal.vtt</string>
											<key>match</key>
											<string>.+</string>
										</dict>
									</array>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.separator.comma.vtt</string>
								</dict>
								<key>3</key>
								<dict>
									<key>patterns</key>
									<array>
										<dict>
											<key>name</key>
											<string>support.constant.position-cue-setting.vtt</string>
											<key>match</key>
											<string>(?:^|\G)(?:line-left|center|line-right)(?=$)</string>
										</dict>
										<dict>
											<key>name</key>
											<string>invalid.illegal.vtt</string>
											<key>match</key>
											<string>.+</string>
										</dict>
									</array>
								</dict>
							</dict>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>region_anchor_setting</key>
		<dict>
			<key>name</key>
			<string>meta.region-anchor-setting.vtt</string>
			<key>match</key>
			<string>(regionanchor)(:)([^\s]+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type.region-anchor-setting.vtt</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.colon.vtt</string>
				</dict>
				<key>3</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(.+)(,)(.+)</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#percentage</string>
										</dict>
									</array>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.separator.comma.vtt</string>
								</dict>
								<key>3</key>
								<dict>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#percentage</string>
										</dict>
									</array>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>name</key>
							<string>invalid.illegal.vtt</string>
							<key>match</key>
							<string>.+</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>region_cue_setting</key>
		<dict>
			<key>name</key>
			<string>meta.region-cue-setting.vtt</string>
			<key>match</key>
			<string>(region)(:)([^\s]+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type.region-cue-setting.vtt</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.colon.vtt</string>
				</dict>
				<key>3</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>invalid.illegal.vtt</string>
							<key>match</key>
							<string>.*--&gt;.*</string>
						</dict>
						<dict>
							<key>name</key>
							<string>string.unquoted.region-cue-setting.vtt</string>
							<key>match</key>
							<string>[^\s]+</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>region_definition_block</key>
		<dict>
			<key>name</key>
			<string>meta.region-definition-block.vtt</string>
			<key>begin</key>
			<string>^(REGION)\s*</string>
			<key>end</key>
			<string>^$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#region_settings_list</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.section.region.vtt</string>
				</dict>
			</dict>
		</dict>
		<key>region_identifier_setting</key>
		<dict>
			<key>name</key>
			<string>meta.region-identifier-setting.vtt</string>
			<key>match</key>
			<string>(id)(:)([^\s]+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type.region-identifier-setting.vtt</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.colon.vtt</string>
				</dict>
				<key>3</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>invalid.illegal.vtt</string>
							<key>match</key>
							<string>.*--&gt;.*</string>
						</dict>
						<dict>
							<key>name</key>
							<string>string.unquoted.region-identifier-setting.vtt</string>
							<key>match</key>
							<string>[^\s]+</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>region_lines_setting</key>
		<dict>
			<key>name</key>
			<string>meta.region-lines-setting.vtt</string>
			<key>match</key>
			<string>(lines)(:)([^\s]+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type.region-lines-setting.vtt</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.colon.vtt</string>
				</dict>
				<key>3</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>constant.numeric.region-lines-setting.vtt</string>
							<key>match</key>
							<string>\d+</string>
						</dict>
						<dict>
							<key>name</key>
							<string>invalid.illegal.vtt</string>
							<key>match</key>
							<string>.+</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>region_scroll_setting</key>
		<dict>
			<key>name</key>
			<string>meta.region-scroll-setting.vtt</string>
			<key>match</key>
			<string>(scroll)(:)([^\s]+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type.region-scroll-setting.vtt</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.colon.vtt</string>
				</dict>
				<key>3</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>support.constant.region-scroll-setting.vtt</string>
							<key>match</key>
							<string>(?:^|\G)up(?=$)</string>
						</dict>
						<dict>
							<key>name</key>
							<string>invalid.illegal.vtt</string>
							<key>match</key>
							<string>.+</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>region_settings_list</key>
		<dict>
			<key>name</key>
			<string>meta.region-settings-list.vtt</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#region_identifier_setting</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#region_width_setting</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#region_lines_setting</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#region_anchor_setting</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#region_viewport_anchor_setting</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#region_scroll_setting</string>
				</dict>
			</array>
		</dict>
		<key>region_viewport_anchor_setting</key>
		<dict>
			<key>name</key>
			<string>meta.region-viewport-anchor-setting.vtt</string>
			<key>match</key>
			<string>(viewportanchor)(:)([^\s]+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type.region-viewport-anchor-setting.vtt</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.colon.vtt</string>
				</dict>
				<key>3</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(.*)(,)(.*)</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#percentage</string>
										</dict>
									</array>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.separator.comma.vtt</string>
								</dict>
								<key>3</key>
								<dict>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#percentage</string>
										</dict>
									</array>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>name</key>
							<string>invalid.illegal.vtt</string>
							<key>match</key>
							<string>.+</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>region_width_setting</key>
		<dict>
			<key>name</key>
			<string>meta.region-width-setting.vtt</string>
			<key>match</key>
			<string>(width)(:)([^\s]+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type.region-width-setting.vtt</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.colon.vtt</string>
				</dict>
				<key>3</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#percentage</string>
						</dict>
						<dict>
							<key>name</key>
							<string>invalid.illegal.vtt</string>
							<key>match</key>
							<string>.+</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>size_cue_setting</key>
		<dict>
			<key>name</key>
			<string>meta.size-cue-setting.vtt</string>
			<key>match</key>
			<string>(size)(:)([^\s]+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type.size-cue-setting.vtt</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.colon.vtt</string>
				</dict>
				<key>3</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#percentage</string>
						</dict>
						<dict>
							<key>name</key>
							<string>invalid.illegal.vtt</string>
							<key>match</key>
							<string>.+</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>style_block</key>
		<dict>
			<key>name</key>
			<string>meta.style-block.vtt</string>
			<key>begin</key>
			<string>^(STYLE)\s*</string>
			<key>end</key>
			<string>^$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>invalid.illegal.vtt</string>
					<key>match</key>
					<string>.*--&gt;.*</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.css</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.section.style.vtt</string>
				</dict>
			</dict>
		</dict>
		<key>timestamp</key>
		<dict>
			<key>name</key>
			<string>meta.timestamp.vtt</string>
			<key>match</key>
			<string>(?:^|\G)(?:(\d{2,})(:))?([0-5]\d)(:)([0-5]\d\.\d{3})(?=$)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.time.hour.vtt</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.colon.vtt</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.time.minute.vtt</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.colon.vtt</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.time.second.vtt</string>
				</dict>
			</dict>
		</dict>
		<key>vertical_text_cue_setting</key>
		<dict>
			<key>name</key>
			<string>meta.vertical-text-cue-setting.vtt</string>
			<key>match</key>
			<string>(vertical)(:)([^\s]+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type.vertical-text-cue-setting.vtt</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.colon.vtt</string>
				</dict>
				<key>3</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>support.constant.vertical-text-cue-setting.vtt</string>
							<key>match</key>
							<string>(?:^|\G)(?:rl|lr)(?=$)</string>
						</dict>
						<dict>
							<key>name</key>
							<string>invalid.illegal.vtt</string>
							<key>match</key>
							<string>.+</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>vtt</string>
	</array>
</dict>
</plist>
