<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>.wgetrc</string>
	<key>scopeName</key>
	<string>source.wgetrc</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#main</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>addhostdir</key>
		<dict>
			<key>name</key>
			<string>meta.field.addhostdir.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*a[-_]*d[-_]*d[-_]*h[-_]*o[-_]*s[-_]*t[-_]*d[-_]*i[-_]*r[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>adjustextension</key>
		<dict>
			<key>name</key>
			<string>meta.field.adjustextension.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*a[-_]*d[-_]*j[-_]*u[-_]*s[-_]*t[-_]*e[-_]*x[-_]*t[-_]*e[-_]*n[-_]*s[-_]*i[-_]*o[-_]*n[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>askpassword</key>
		<dict>
			<key>name</key>
			<string>meta.field.askpassword.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*a[-_]*s[-_]*k[-_]*p[-_]*a[-_]*s[-_]*s[-_]*w[-_]*o[-_]*r[-_]*d[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>authnochallenge</key>
		<dict>
			<key>name</key>
			<string>meta.field.authnochallenge.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*a[-_]*u[-_]*t[-_]*h[-_]*n[-_]*o[-_]*c[-_]*h[-_]*a[-_]*l[-_]*l[-_]*e[-_]*n[-_]*g[-_]*e[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>background</key>
		<dict>
			<key>name</key>
			<string>meta.field.background.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*b[-_]*a[-_]*c[-_]*k[-_]*g[-_]*r[-_]*o[-_]*u[-_]*n[-_]*d[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>backupconverted</key>
		<dict>
			<key>name</key>
			<string>meta.field.backupconverted.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*b[-_]*a[-_]*c[-_]*k[-_]*u[-_]*p[-_]*c[-_]*o[-_]*n[-_]*v[-_]*e[-_]*r[-_]*t[-_]*e[-_]*d[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>backups</key>
		<dict>
			<key>name</key>
			<string>meta.field.backups.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*b[-_]*a[-_]*c[-_]*k[-_]*u[-_]*p[-_]*s[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>boolean</key>
		<dict>
			<key>name</key>
			<string>constant.logical.boolean.${1:/downcase}.wgetrc</string>
			<key>match</key>
			<string>(?i)\b(on|off)\b</string>
		</dict>
		<key>bytes</key>
		<dict>
			<key>match</key>
			<string>(?i)([-+]?[.e\d]+)(k|m)?</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>etc#num</string>
						</dict>
					</array>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.unit.bytes.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>cache</key>
		<dict>
			<key>name</key>
			<string>meta.field.cache.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*c[-_]*a[-_]*c[-_]*h[-_]*e[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>checkcertificate</key>
		<dict>
			<key>name</key>
			<string>meta.field.checkcertificate.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*c[-_]*h[-_]*e[-_]*c[-_]*k[-_]*c[-_]*e[-_]*r[-_]*t[-_]*i[-_]*f[-_]*i[-_]*c[-_]*a[-_]*t[-_]*e[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>connecttimeout</key>
		<dict>
			<key>name</key>
			<string>meta.field.connecttimeout.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*c[-_]*o[-_]*n[-_]*n[-_]*e[-_]*c[-_]*t[-_]*t[-_]*i[-_]*m[-_]*e[-_]*o[-_]*u[-_]*t[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>contentdisposition</key>
		<dict>
			<key>name</key>
			<string>meta.field.contentdisposition.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*c[-_]*o[-_]*n[-_]*t[-_]*e[-_]*n[-_]*t[-_]*d[-_]*i[-_]*s[-_]*p[-_]*o[-_]*s[-_]*i[-_]*t[-_]*i[-_]*o[-_]*n[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>continue</key>
		<dict>
			<key>name</key>
			<string>meta.field.continue.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*c[-_]*o[-_]*n[-_]*t[-_]*i[-_]*n[-_]*u[-_]*e[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>convertlinks</key>
		<dict>
			<key>name</key>
			<string>meta.field.convertlinks.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*c[-_]*o[-_]*n[-_]*v[-_]*e[-_]*r[-_]*t[-_]*l[-_]*i[-_]*n[-_]*k[-_]*s[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>cookies</key>
		<dict>
			<key>name</key>
			<string>meta.field.cookies.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*c[-_]*o[-_]*o[-_]*k[-_]*i[-_]*e[-_]*s[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>cutdirs</key>
		<dict>
			<key>name</key>
			<string>meta.field.cutdirs.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*c[-_]*u[-_]*t[-_]*d[-_]*i[-_]*r[-_]*s[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>debug</key>
		<dict>
			<key>name</key>
			<string>meta.field.debug.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*d[-_]*e[-_]*b[-_]*u[-_]*g[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>deleteafter</key>
		<dict>
			<key>name</key>
			<string>meta.field.deleteafter.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*d[-_]*e[-_]*l[-_]*e[-_]*t[-_]*e[-_]*a[-_]*f[-_]*t[-_]*e[-_]*r[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>dirstruct</key>
		<dict>
			<key>name</key>
			<string>meta.field.dirstruct.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*d[-_]*i[-_]*r[-_]*s[-_]*t[-_]*r[-_]*u[-_]*c[-_]*t[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>dnscache</key>
		<dict>
			<key>name</key>
			<string>meta.field.dnscache.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*d[-_]*n[-_]*s[-_]*c[-_]*a[-_]*c[-_]*h[-_]*e[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>dnstimeout</key>
		<dict>
			<key>name</key>
			<string>meta.field.dnstimeout.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*d[-_]*n[-_]*s[-_]*t[-_]*i[-_]*m[-_]*e[-_]*o[-_]*u[-_]*t[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>dotbytes</key>
		<dict>
			<key>name</key>
			<string>meta.field.dotbytes.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*d[-_]*o[-_]*t[-_]*b[-_]*y[-_]*t[-_]*e[-_]*s[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bytes</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>dotsinline</key>
		<dict>
			<key>name</key>
			<string>meta.field.dotsinline.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*d[-_]*o[-_]*t[-_]*s[-_]*i[-_]*n[-_]*l[-_]*i[-_]*n[-_]*e[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>dotspacing</key>
		<dict>
			<key>name</key>
			<string>meta.field.dotspacing.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*d[-_]*o[-_]*t[-_]*s[-_]*p[-_]*a[-_]*c[-_]*i[-_]*n[-_]*g[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>encoding</key>
		<dict>
			<key>name</key>
			<string>constant.language.encoding.wgetrc</string>
			<key>match</key>
			<string>(?:\G|^|(?&lt;==))\s*([^=\s#]+)</string>
		</dict>
		<key>followftp</key>
		<dict>
			<key>name</key>
			<string>meta.field.followftp.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*f[-_]*o[-_]*l[-_]*l[-_]*o[-_]*w[-_]*f[-_]*t[-_]*p[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>forcehtml</key>
		<dict>
			<key>name</key>
			<string>meta.field.forcehtml.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*f[-_]*o[-_]*r[-_]*c[-_]*e[-_]*h[-_]*t[-_]*m[-_]*l[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>glob</key>
		<dict>
			<key>name</key>
			<string>meta.field.glob.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*g[-_]*l[-_]*o[-_]*b[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>httpkeepalive</key>
		<dict>
			<key>name</key>
			<string>meta.field.httpkeepalive.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*h[-_]*t[-_]*t[-_]*p[-_]*k[-_]*e[-_]*e[-_]*p[-_]*a[-_]*l[-_]*i[-_]*v[-_]*e[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>httpsonly</key>
		<dict>
			<key>name</key>
			<string>meta.field.httpsonly.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*h[-_]*t[-_]*t[-_]*p[-_]*s[-_]*o[-_]*n[-_]*l[-_]*y[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>ignorecase</key>
		<dict>
			<key>name</key>
			<string>meta.field.ignorecase.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*i[-_]*g[-_]*n[-_]*o[-_]*r[-_]*e[-_]*c[-_]*a[-_]*s[-_]*e[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>ignorelength</key>
		<dict>
			<key>name</key>
			<string>meta.field.ignorelength.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*i[-_]*g[-_]*n[-_]*o[-_]*r[-_]*e[-_]*l[-_]*e[-_]*n[-_]*g[-_]*t[-_]*h[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>inet4only</key>
		<dict>
			<key>name</key>
			<string>meta.field.inet4only.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*i[-_]*n[-_]*e[-_]*t[-_]*4[-_]*o[-_]*n[-_]*l[-_]*y[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>inet6only</key>
		<dict>
			<key>name</key>
			<string>meta.field.inet6only.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*i[-_]*n[-_]*e[-_]*t[-_]*6[-_]*o[-_]*n[-_]*l[-_]*y[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>iri</key>
		<dict>
			<key>name</key>
			<string>meta.field.iri.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*i[-_]*r[-_]*i[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>keepsessioncookies</key>
		<dict>
			<key>name</key>
			<string>meta.field.keepsessioncookies.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*k[-_]*e[-_]*e[-_]*p[-_]*s[-_]*e[-_]*s[-_]*s[-_]*i[-_]*o[-_]*n[-_]*c[-_]*o[-_]*o[-_]*k[-_]*i[-_]*e[-_]*s[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>limitrate</key>
		<dict>
			<key>name</key>
			<string>meta.field.limitrate.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*l[-_]*i[-_]*m[-_]*i[-_]*t[-_]*r[-_]*a[-_]*t[-_]*e[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>localencoding</key>
		<dict>
			<key>name</key>
			<string>meta.field.localencoding.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*l[-_]*o[-_]*c[-_]*a[-_]*l[-_]*e[-_]*n[-_]*c[-_]*o[-_]*d[-_]*i[-_]*n[-_]*g[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#encoding</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>main</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#addhostdir</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#adjustextension</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#askpassword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#authnochallenge</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#background</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#backupconverted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#backups</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cache</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#checkcertificate</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#connecttimeout</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#contentdisposition</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#continue</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#convertlinks</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cookies</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cutdirs</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#debug</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#deleteafter</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dirstruct</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dnscache</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dnstimeout</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dotbytes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dotsinline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dotspacing</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#followftp</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#forcehtml</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#glob</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#httpkeepalive</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#httpsonly</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#ignorecase</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#ignorelength</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inet4only</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inet6only</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#iri</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#limitrate</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#localencoding</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keepsessioncookies</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#maxredirect</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#mirror</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#netrc</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#noclobber</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#noparent</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#pagerequisites</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#passiveftp</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#preferfamily</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#protocoldirectories</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#quiet</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#quota</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#randomwait</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#readtimeout</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#reclevel</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#recursive</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#relativeonly</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#remoteencoding</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#removelisting</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#restrictfilenames</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#retrsymlinks</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#retryconnrefused</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#robots</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#saveheaders</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#secureprotocol</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#serverresponse</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#showalldnsentries</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#spanhosts</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#spider</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strictcomments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#timeout</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#timestamping</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tries</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#trustservernames</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#useproxy</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#useservertimestamps</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#verbose</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#waitretry</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#wait</string>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.field.${1:/downcase}.wgetrc</string>
					<key>match</key>
					<string>^\s*([^#=\s]+)\s*(=)\s*(\S.*)\s*$</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.assignment.parameter.name.wgetrc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>etc#eql</string>
								</dict>
							</array>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.wgetrc</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>etc#url</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>maxredirect</key>
		<dict>
			<key>name</key>
			<string>meta.field.maxredirect.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*m[-_]*a[-_]*x[-_]*r[-_]*e[-_]*d[-_]*i[-_]*r[-_]*e[-_]*c[-_]*t[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>mirror</key>
		<dict>
			<key>name</key>
			<string>meta.field.mirror.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*m[-_]*i[-_]*r[-_]*r[-_]*o[-_]*r[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>netrc</key>
		<dict>
			<key>name</key>
			<string>meta.field.netrc.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*n[-_]*e[-_]*t[-_]*r[-_]*c[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>noclobber</key>
		<dict>
			<key>name</key>
			<string>meta.field.noclobber.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*n[-_]*o[-_]*c[-_]*l[-_]*o[-_]*b[-_]*b[-_]*e[-_]*r[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>noparent</key>
		<dict>
			<key>name</key>
			<string>meta.field.noparent.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*n[-_]*o[-_]*p[-_]*a[-_]*r[-_]*e[-_]*n[-_]*t[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>number</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#num</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.numeric.infinity.wgetrc</string>
					<key>match</key>
					<string>(?i)\binf\b</string>
				</dict>
			</array>
		</dict>
		<key>pagerequisites</key>
		<dict>
			<key>name</key>
			<string>meta.field.pagerequisites.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*p[-_]*a[-_]*g[-_]*e[-_]*r[-_]*e[-_]*q[-_]*u[-_]*i[-_]*s[-_]*i[-_]*t[-_]*e[-_]*s[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>passiveftp</key>
		<dict>
			<key>name</key>
			<string>meta.field.passiveftp.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*p[-_]*a[-_]*s[-_]*s[-_]*i[-_]*v[-_]*e[-_]*f[-_]*t[-_]*p[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>preferfamily</key>
		<dict>
			<key>name</key>
			<string>meta.field.preferfamily.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*p[-_]*r[-_]*e[-_]*f[-_]*e[-_]*r[-_]*f[-_]*a[-_]*m[-_]*i[-_]*l[-_]*y[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.other.family-type.wgetrc</string>
					<key>match</key>
					<string>\S+</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>protocoldirectories</key>
		<dict>
			<key>name</key>
			<string>meta.field.protocoldirectories.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*p[-_]*r[-_]*o[-_]*t[-_]*o[-_]*c[-_]*o[-_]*l[-_]*d[-_]*i[-_]*r[-_]*e[-_]*c[-_]*t[-_]*o[-_]*r[-_]*i[-_]*e[-_]*s[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>quiet</key>
		<dict>
			<key>name</key>
			<string>meta.field.quiet.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*q[-_]*u[-_]*i[-_]*e[-_]*t[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>quota</key>
		<dict>
			<key>name</key>
			<string>meta.field.quota.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*q[-_]*u[-_]*o[-_]*t[-_]*a[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bytes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>randomwait</key>
		<dict>
			<key>name</key>
			<string>meta.field.randomwait.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*r[-_]*a[-_]*n[-_]*d[-_]*o[-_]*m[-_]*w[-_]*a[-_]*i[-_]*t[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>readtimeout</key>
		<dict>
			<key>name</key>
			<string>meta.field.readtimeout.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*r[-_]*e[-_]*a[-_]*d[-_]*t[-_]*i[-_]*m[-_]*e[-_]*o[-_]*u[-_]*t[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>reclevel</key>
		<dict>
			<key>name</key>
			<string>meta.field.reclevel.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*r[-_]*e[-_]*c[-_]*l[-_]*e[-_]*v[-_]*e[-_]*l[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>recursive</key>
		<dict>
			<key>name</key>
			<string>meta.field.recursive.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*r[-_]*e[-_]*c[-_]*u[-_]*r[-_]*s[-_]*i[-_]*v[-_]*e[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>relativeonly</key>
		<dict>
			<key>name</key>
			<string>meta.field.relativeonly.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*r[-_]*e[-_]*l[-_]*a[-_]*t[-_]*i[-_]*v[-_]*e[-_]*o[-_]*n[-_]*l[-_]*y[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>remoteencoding</key>
		<dict>
			<key>name</key>
			<string>meta.field.remoteencoding.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*r[-_]*e[-_]*m[-_]*o[-_]*t[-_]*e[-_]*e[-_]*n[-_]*c[-_]*o[-_]*d[-_]*i[-_]*n[-_]*g[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#encoding</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>removelisting</key>
		<dict>
			<key>name</key>
			<string>meta.field.removelisting.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*r[-_]*e[-_]*m[-_]*o[-_]*v[-_]*e[-_]*l[-_]*i[-_]*s[-_]*t[-_]*i[-_]*n[-_]*g[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>restrictfilenames</key>
		<dict>
			<key>name</key>
			<string>meta.field.removelisting.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*r[-_]*e[-_]*s[-_]*t[-_]*r[-_]*i[-_]*c[-_]*t[-_]*f[-_]*i[-_]*l[-_]*e[-_]*n[-_]*a[-_]*m[-_]*e[-_]*s[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.os-type.wgetrc</string>
					<key>match</key>
					<string>(?i)\b(unix|windows)\b</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>retrsymlinks</key>
		<dict>
			<key>name</key>
			<string>meta.field.retrsymlinks.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*r[-_]*e[-_]*t[-_]*r[-_]*s[-_]*y[-_]*m[-_]*l[-_]*i[-_]*n[-_]*k[-_]*s[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>retryconnrefused</key>
		<dict>
			<key>name</key>
			<string>meta.field.retryconnrefused.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*r[-_]*e[-_]*t[-_]*r[-_]*y[-_]*c[-_]*o[-_]*n[-_]*n[-_]*r[-_]*e[-_]*f[-_]*u[-_]*s[-_]*e[-_]*d[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>robots</key>
		<dict>
			<key>name</key>
			<string>meta.field.robots.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*r[-_]*o[-_]*b[-_]*o[-_]*t[-_]*s[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>saveheaders</key>
		<dict>
			<key>name</key>
			<string>meta.field.saveheaders.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*s[-_]*a[-_]*v[-_]*e[-_]*h[-_]*e[-_]*a[-_]*d[-_]*e[-_]*r[-_]*s[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>secureprotocol</key>
		<dict>
			<key>name</key>
			<string>meta.field.secureprotocol.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*s[-_]*e[-_]*c[-_]*u[-_]*r[-_]*e[-_]*p[-_]*r[-_]*o[-_]*t[-_]*o[-_]*c[-_]*o[-_]*l[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?:\G|^|(?&lt;==))\s*([^\s#]+)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.language.secure-protocol.wgetrc</string>
						</dict>
					</dict>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>serverresponse</key>
		<dict>
			<key>name</key>
			<string>meta.field.serverresponse.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*s[-_]*e[-_]*r[-_]*v[-_]*e[-_]*r[-_]*r[-_]*e[-_]*s[-_]*p[-_]*o[-_]*n[-_]*s[-_]*e[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>showalldnsentries</key>
		<dict>
			<key>name</key>
			<string>meta.field.showalldnsentries.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*s[-_]*h[-_]*o[-_]*w[-_]*a[-_]*l[-_]*l[-_]*d[-_]*n[-_]*s[-_]*e[-_]*n[-_]*t[-_]*r[-_]*i[-_]*e[-_]*s[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>spanhosts</key>
		<dict>
			<key>name</key>
			<string>meta.field.spanhosts.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*s[-_]*p[-_]*a[-_]*n[-_]*h[-_]*o[-_]*s[-_]*t[-_]*s[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>spider</key>
		<dict>
			<key>name</key>
			<string>meta.field.spider.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*s[-_]*p[-_]*i[-_]*d[-_]*e[-_]*r[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>strictcomments</key>
		<dict>
			<key>name</key>
			<string>meta.field.strictcomments.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*s[-_]*t[-_]*r[-_]*i[-_]*c[-_]*t[-_]*c[-_]*o[-_]*m[-_]*m[-_]*e[-_]*n[-_]*t[-_]*s[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>timeout</key>
		<dict>
			<key>name</key>
			<string>meta.field.timeout.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*t[-_]*i[-_]*m[-_]*e[-_]*o[-_]*u[-_]*t[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>timestamping</key>
		<dict>
			<key>name</key>
			<string>meta.field.timestamping.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*t[-_]*i[-_]*m[-_]*e[-_]*s[-_]*t[-_]*a[-_]*m[-_]*p[-_]*i[-_]*n[-_]*g[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>tries</key>
		<dict>
			<key>name</key>
			<string>meta.field.tries.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*t[-_]*r[-_]*i[-_]*e[-_]*s[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>trustservernames</key>
		<dict>
			<key>name</key>
			<string>meta.field.trustservernames.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*t[-_]*r[-_]*u[-_]*s[-_]*t[-_]*s[-_]*e[-_]*r[-_]*v[-_]*e[-_]*r[-_]*n[-_]*a[-_]*m[-_]*e[-_]*s[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>useproxy</key>
		<dict>
			<key>name</key>
			<string>meta.field.useproxy.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*u[-_]*s[-_]*e[-_]*p[-_]*r[-_]*o[-_]*x[-_]*y[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>useservertimestamps</key>
		<dict>
			<key>name</key>
			<string>meta.field.useservertimestamps.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*u[-_]*s[-_]*e[-_]*s[-_]*e[-_]*r[-_]*v[-_]*e[-_]*r[-_]*t[-_]*i[-_]*m[-_]*e[-_]*s[-_]*t[-_]*a[-_]*m[-_]*p[-_]*s[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>verbose</key>
		<dict>
			<key>name</key>
			<string>meta.field.verbose.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*v[-_]*e[-_]*r[-_]*b[-_]*o[-_]*s[-_]*e[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>wait</key>
		<dict>
			<key>name</key>
			<string>meta.field.wait.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*w[-_]*a[-_]*i[-_]*t[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
		<key>waitretry</key>
		<dict>
			<key>name</key>
			<string>meta.field.waitretry.wgetrc</string>
			<key>begin</key>
			<string>(?i)^\s*([-_]*w[-_]*a[-_]*i[-_]*t[-_]*r[-_]*e[-_]*t[-_]*r[-_]*y[-_]*)(?=\s|=|$)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>etc#eql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.parameter.name.wgetrc</string>
				</dict>
			</dict>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>.wgetrc</string>
	</array>
</dict>
</plist>
