<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Windows Message Text</string>
	<key>scopeName</key>
	<string>source.win32-messages</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#main</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>name</key>
			<string>meta.comment.line.semicolon.win32-messages</string>
			<key>begin</key>
			<string>;</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.c</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.win32-messages</string>
				</dict>
			</dict>
		</dict>
		<key>delim</key>
		<dict>
			<key>name</key>
			<string>meta.separator.win32-messages</string>
			<key>match</key>
			<string>^\.$</string>
		</dict>
		<key>insert</key>
		<dict>
			<key>name</key>
			<string>meta.line.insert.win32-messages</string>
			<key>match</key>
			<string>(?x) (%(?:.|\d{1,2})) ((!)(\w+)(!))? </string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language.insert.win32-messages</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.insert.format.win32-messages</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.insert.format.begin.win32-messages</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.insert.format.end.win32-messages</string>
				</dict>
			</dict>
		</dict>
		<key>main</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#insert</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#message</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#statement</string>
				</dict>
			</array>
		</dict>
		<key>message</key>
		<dict>
			<key>name</key>
			<string>string.unquoted.message.win32-messages</string>
			<key>match</key>
			<string>^[^=]+$</string>
		</dict>
		<key>statement</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.control.statement.win32-messages</string>
					<key>match</key>
					<string>[^=()]+(?=(=))</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.statement.win32-messages</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.win32-messages</string>
					<key>match</key>
					<string>(?:0\w)?\d+</string>
				</dict>
				<dict>
					<key>name</key>
					<string>string.unquoted.value.win32-messages</string>
					<key>begin</key>
					<string>(?&lt;==)(?!\()</string>
					<key>end</key>
					<string>$</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.statement.win32-messages</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.block.statement.value.win32-messages</string>
					<key>begin</key>
					<string>(?&lt;==)\(</string>
					<key>end</key>
					<string>\)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#statement</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.block.group.begin.win32-messages</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.block.group.end.win32-messages</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>mc</string>
	</array>
</dict>
</plist>
