<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>REG (Windows Registry)</string>
	<key>scopeName</key>
	<string>source.reg</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>name</key>
			<string>comment.reg</string>
			<key>match</key>
			<string>;.*$</string>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.doctype.reg</string>
			<key>match</key>
			<string>Windows Registry Editor Version \d.\d\d</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^((@)|\&quot;.*\&quot;)(=)((\-)|\s*(0|1)\s*$|)</string>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.reg</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.key-value.reg</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.reg</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>language.constant.boolean.reg</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>(\\)$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.reg</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>string.quoted.double.reg</string>
			<key>begin</key>
			<string>\&quot;</string>
			<key>end</key>
			<string>\&quot;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.character.escape.reg</string>
					<key>match</key>
					<string>\\\\</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.reg</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.reg</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>(hex)(|\(([ABab0-9])\))(:)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.reg</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.reg</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.reg</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>(dword)(:)([ABCDEFabcdef0-9]{1,8})\s*$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.reg</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.reg</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.reg</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>.meta.section.key-path.reg</string>
			<key>begin</key>
			<string>(\[)(\s*\n)*(-){0,1}(\s*\n)*</string>
			<key>end</key>
			<string>\]</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(HKEY_CURRENT_CONFIG|HKCC)\\(Software|System)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.hive-name.reg</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>language.constant.standard-key.reg</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>(HKEY_CURRENT_USER|HKCU)\\(AppEvents|AppXBackupContentType|Console|Control Panel|Environment|EUDC|Keyboard Layout|Network|Printers|Software|System|Volatile Environment)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.hive-name.reg</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>language.constant.standard-key.reg</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>(HKEY_LOCAL_MACHINE|HKLM)\\(BCD00000000|DRIVERS|HARDWARE|SAM|SECURITY|SOFTWARE|SYSTEM)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.hive-name.reg</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>language.constant.standard-key.reg</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>(HKEY_USERS|HKU)\\(.DEFAULT)\\(AppEvents|AppXBackupContentType|Console|Control Panel|Environment|EUDC|Keyboard Layout|Network|Printers|Software|System|Volatile Environment)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.hive-name.reg</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>language.constant.standard-key.reg</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>language.constant.standard-key.reg</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.other.hive-name.reg</string>
					<key>match</key>
					<string>(HKEY_CLASSES_ROOT|HKCR|HKEY_CURRENT_CONFIG|HKCC|HKEY_CURRENT_USER|HKCU|HKEY_DYN_DATA|HKEY_LOCAL_MACHINE|HKLM|HKEY_PERFORMANCE_DATA|HKEY_USERS|HKU)</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.brace.square.reg</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.reg</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.brace.square.reg</string>
				</dict>
			</dict>
		</dict>
	</array>
	<key>fileTypes</key>
	<array>
		<string>reg</string>
	</array>
</dict>
</plist>
