<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Witcher Script</string>
	<key>scopeName</key>
	<string>source.witcherscript</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>name</key>
			<string>comment.block.witcherscript</string>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
		</dict>
		<dict>
			<key>name</key>
			<string>comment.double-slash.witcherscript</string>
			<key>match</key>
			<string>//.*</string>
		</dict>
		<dict>
			<key>name</key>
			<string>string.quoted.double.witcherscript</string>
			<key>begin</key>
			<string>&quot;</string>
			<key>end</key>
			<string>&quot;</string>
		</dict>
		<dict>
			<key>name</key>
			<string>string.quoted.single.witcherscript</string>
			<key>begin</key>
			<string>&apos;</string>
			<key>end</key>
			<string>&apos;</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.control.witcherscript</string>
			<key>match</key>
			<string>\b(break|case|continue|else|for|if|return|switch|while)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.other.witcherscript</string>
			<key>match</key>
			<string>\b(out|inlined|autobind|editable|entry|exec|hint|import|latent|optional|out|quest|saved|statemachine|timer)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.operator.new.witcherscript</string>
			<key>match</key>
			<string>\b(=|!|&lt;|&gt;|&amp;|\+|-|\^|\*|\/|\|)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.numeric.witcherscript</string>
			<key>match</key>
			<string>\b(\d+|\d+.?(f)?)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.rgb-value.witcherscript</string>
			<key>match</key>
			<string>(#)([0-9a-fA-F]{3}|[0-9a-fA-F]{6})\b(?!.*?(?&lt;!@){)</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.language.witcherscript</string>
			<key>match</key>
			<string>\b(false|NULL|true)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.type.witcherscript</string>
			<key>match</key>
			<string>\b(enum|struct|state|array)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.modifier.witcherscript</string>
			<key>match</key>
			<string>\b(abstract|const|final|private|protected|public)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.class.witcherscript</string>
			<key>match</key>
			<string>\b(theGame|theInput|thePlayer|theSound)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>variable.language.witcherscript</string>
			<key>match</key>
			<string>\b(this|parent|super)\b</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(function|event)\s*(\/\*.*\*\/)?\s*(\w+)\s*\(</string>
			<key>end</key>
			<string>\)(\s*:\s*(array\s*&lt;\s*\w+\s*&gt;|\w*))?</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\s*(out|optional)?\s*(\w+)\s*:\s*(array\s*&lt;\s*\w+\s*&gt;|\w*|),?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.witcherscript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.variable.witcherscript</string>
						</dict>
						<key>3</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#witcherscript-var-types</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type.witcherscript</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment.block.witcherscript</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.function.witcherscript</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#witcherscript-var-types</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(var)\b\s*</string>
			<key>end</key>
			<string>:\s*(array\s*&lt;\s*\w+\s*&gt;|\w*)\s*;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>support.variable.witcherscript</string>
					<key>match</key>
					<string>(\w+)\s*,?</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.witcherscript</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#witcherscript-var-types</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>(default)\s*(\w+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.witcherscript</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.variable</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>(extends|class)\s*(\w*)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.witcherscript</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.class.witcherscript</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>\(\s*(\s*[A-Z]\w+\s*)\s*\)\s*\(</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class.witcherscript</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>\(\s*\(\s*([A-Z]\w+)\s*\)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class.witcherscript</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>(new)\s*(\w+)\s*(in)\s*(this)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language.witcherscript</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.class.witcherscript</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.language.witcherscript</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.language.witcherscript</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>include</key>
			<string>#witcherscript-data-types</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>witcherscript-data-types</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>storage.type.witcherscript</string>
					<key>match</key>
					<string>\b(string|int|integer|bool|float|name|range)\b</string>
				</dict>
			</array>
		</dict>
		<key>witcherscript-object-types</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>support.class.witcherscript</string>
					<key>match</key>
					<string>[A-Z]\w+</string>
				</dict>
			</array>
		</dict>
		<key>witcherscript-var-types</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#witcherscript-object-types</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(array)\s*&lt;\s*(\w+)\s*&gt;</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.witcherscript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#witcherscript-object-types</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#witcherscript-data-types</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>include</key>
					<string>#witcherscript-data-types</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>ws</string>
	</array>
</dict>
</plist>
