<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Wren</string>
	<key>scopeName</key>
	<string>source.wren</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#code</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#class</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>block</key>
		<dict>
			<key>name</key>
			<string>meta.block.wren</string>
			<key>begin</key>
			<string>{</string>
			<key>end</key>
			<string>}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#code</string>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.block.parameters.wren</string>
					<key>begin</key>
					<string>\|</string>
					<key>end</key>
					<string>\|</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>variable.parameter.function.wren</string>
							<key>match</key>
							<string>\w+</string>
						</dict>
					</array>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.block.begin.wren</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.block.end.wren</string>
				</dict>
			</dict>
		</dict>
		<key>blockComment</key>
		<dict>
			<key>name</key>
			<string>comment.block.wren</string>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#blockComment</string>
				</dict>
			</array>
		</dict>
		<key>class</key>
		<dict>
			<key>name</key>
			<string>meta.class</string>
			<key>begin</key>
			<string>(?:\b(foreign)\s+)?(\bclass)\s+(\w+)\s+(?:(\bis)\s+(\w+))?</string>
			<key>end</key>
			<string>}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.class.body.wren</string>
					<key>begin</key>
					<string>{</string>
					<key>end</key>
					<string>(?=})</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#blockComment</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#foreignMethod</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#subscriptOperator</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#method</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.class.begin.wren</string>
						</dict>
					</dict>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.wren</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.wren</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.wren</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.wren</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.wren</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.class.end.wren</string>
				</dict>
			</dict>
		</dict>
		<key>code</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#blockComment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keyword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constant</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#static_function</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#static_constant</string>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>name</key>
			<string>comment.line.wren</string>
			<key>match</key>
			<string>//.*</string>
		</dict>
		<key>constant</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.language.wren</string>
					<key>match</key>
					<string>\b(true|false|null)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.wren</string>
					<key>match</key>
					<string>\b(0x[0-9a-fA-F]*|[0-9]+(\.?[0-9]*)?(e(\+|-)?[0-9]+)?)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.hexadecimal.wren</string>
					<key>match</key>
					<string>0x[A-Fa-f0-9]+</string>
				</dict>
			</array>
		</dict>
		<key>foreignMethod</key>
		<dict>
			<key>name</key>
			<string>meta.method.wren</string>
			<key>begin</key>
			<string>\b(foreign)\s+(?:\b(construct|static)\s+)?(\w+=|\w+|\+|-|\*|\/|%|&lt;=?|&gt;=?|==|!=?|&amp;|\||~)</string>
			<key>end</key>
			<string>
</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.method.identifier.wren</string>
					<key>begin</key>
					<string>\(</string>
					<key>end</key>
					<string>\)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>variable.parameter.function.wren</string>
							<key>match</key>
							<string>\w+</string>
						</dict>
					</array>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.wren</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.wren</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.wren</string>
				</dict>
			</dict>
		</dict>
		<key>function</key>
		<dict>
			<key>name</key>
			<string>meta.function.wren</string>
			<key>match</key>
			<string>(?:[.]|\b)(\w+)\(</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.wren</string>
				</dict>
			</dict>
		</dict>
		<key>keyword</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.control.wren</string>
					<key>match</key>
					<string>\b(?:break|else|for|if|import|in|return|while|var)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.wren</string>
					<key>match</key>
					<string>\b(is)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.logical.wren</string>
					<key>match</key>
					<string>!|&amp;&amp;|\|\|</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.range.wren</string>
					<key>match</key>
					<string>(\.\.\.?)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.arithmetic.wren</string>
					<key>match</key>
					<string>(\-|\+|\*|/|%)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.comparison.wren</string>
					<key>match</key>
					<string>(==|!=|&lt;=|&gt;=|&lt;|&gt;)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.wren</string>
					<key>match</key>
					<string>(=)</string>
				</dict>
			</array>
		</dict>
		<key>method</key>
		<dict>
			<key>name</key>
			<string>meta.method.wren</string>
			<key>begin</key>
			<string>(?:\b(construct|static)\s+)?(\w+=|\w+|\+|-|\*|\/|%|&lt;=?|&gt;=?|==|!=?|&amp;|\||~)</string>
			<key>end</key>
			<string>}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.method.identifier.wren</string>
					<key>begin</key>
					<string>\(</string>
					<key>end</key>
					<string>\)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>variable.parameter.function.wren</string>
							<key>match</key>
							<string>\w+</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.method.body.wren</string>
					<key>begin</key>
					<string>{</string>
					<key>end</key>
					<string>(?=})</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#code</string>
						</dict>
					</array>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.wren</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.wren</string>
				</dict>
			</dict>
		</dict>
		<key>static_constant</key>
		<dict>
			<key>name</key>
			<string>meta.static_constant.wren</string>
			<key>match</key>
			<string>\b([A-Z]+\w*)[.](\w+)\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.wren</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other.constant</string>
				</dict>
			</dict>
		</dict>
		<key>static_function</key>
		<dict>
			<key>name</key>
			<string>meta.static_function.wren</string>
			<key>match</key>
			<string>\b([A-Z]+\w*)[.](\w+)\(</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.wren</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.class.wren</string>
				</dict>
			</dict>
		</dict>
		<key>string</key>
		<dict>
			<key>name</key>
			<string>string.quoted.double.wren</string>
			<key>begin</key>
			<string>&quot;</string>
			<key>end</key>
			<string>&quot;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#stringEscapes</string>
				</dict>
			</array>
		</dict>
		<key>stringEscapes</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.character.escape.wren</string>
					<key>match</key>
					<string>\\(?:[0&quot;\abfnrtv]|x[0-9A-Fa-f]{2}|u[0-9A-Fa-f]{4}|U[0-9A-Fa-f]{4})</string>
				</dict>
				<dict>
					<key>name</key>
					<string>invalid.illegal.unknown-escape.wren</string>
					<key>match</key>
					<string>\\(?:x[0-9A-Fa-f]{0,1}|u[0-9A-Fa-f]{0,3}|U[0-9A-Fa-f]{0,7}|.)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.interpolation.wren</string>
					<key>match</key>
					<string>%\((.*?)\)</string>
				</dict>
			</array>
		</dict>
		<key>subscriptOperator</key>
		<dict>
			<key>name</key>
			<string>meta.method.wren</string>
			<key>begin</key>
			<string>\[</string>
			<key>end</key>
			<string>}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.method.identifier.wren</string>
					<key>begin</key>
					<string>\w</string>
					<key>end</key>
					<string>\]</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>variable.parameter.function.wren</string>
							<key>match</key>
							<string>\w+</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.function.wren</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.wren</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.method.body.wren</string>
					<key>begin</key>
					<string>{</string>
					<key>end</key>
					<string>(?=})</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#code</string>
						</dict>
					</array>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.wren</string>
				</dict>
			</dict>
		</dict>
		<key>variable</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>variable.language.wren</string>
					<key>match</key>
					<string>\b(this|super)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>variable.other.class.wren</string>
					<key>match</key>
					<string>\b__\w*</string>
				</dict>
				<dict>
					<key>name</key>
					<string>variable.other.instance.wren</string>
					<key>match</key>
					<string>\b_\w*</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>wren</string>
	</array>
</dict>
</plist>
