<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>X Font Directory Index</string>
	<key>scopeName</key>
	<string>source.fontdir</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#main</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>name</key>
			<string>comment.line.bang.exclamation-mark.fontdir</string>
			<key>begin</key>
			<string>^!</string>
			<key>end</key>
			<string>(?=$)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.fontdir</string>
				</dict>
			</dict>
		</dict>
		<key>entryCount</key>
		<dict>
			<key>name</key>
			<string>constant.numeric.integer.int.decimal.fontdir</string>
			<key>match</key>
			<string>\A([0-9]+)(?=\s|$)</string>
		</dict>
		<key>entryName</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>name</key>
					<string>string.unquoted.font-name.fontdir</string>
					<key>match</key>
					<string>^(?:[^-\s]|\s(?!-|\S+$)|(?&lt;!\s)-)+</string>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>name</key>
			<string>keyword.control.directive.font-name-aliases.fontdir</string>
			<key>match</key>
			<string>^(FILE_NAMES_ALIASES)(?=\s|$)</string>
		</dict>
		<key>main</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#entryCount</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#entryName</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.xlfd#name</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#otherField</string>
				</dict>
			</array>
		</dict>
		<key>otherField</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.other.fontdir</string>
					<key>match</key>
					<string>(?&lt;=\s)\S+$</string>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>name</key>
			<string>string.quoted.double.font-name.fontdir</string>
			<key>begin</key>
			<string>&quot;</string>
			<key>end</key>
			<string>&quot;|(?=$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.character.escape.backslash.fontdir</string>
					<key>match</key>
					<string>(\\).</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.escape.backslash.fontdir</string>
						</dict>
					</dict>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.fontdir</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.fontdir</string>
				</dict>
			</dict>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>encodings.dir</string>
		<string>fonts.alias</string>
		<string>fonts.dir</string>
		<string>fonts.scale</string>
	</array>
</dict>
</plist>
