<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>XCompose</string>
	<key>scopeName</key>
	<string>config.xcompose</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#multikey</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#key</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#quoted</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#function</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#colon</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#unicode</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keyword</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>colon</key>
		<dict>
			<key>name</key>
			<string>entity.function.xcompose</string>
			<key>match</key>
			<string>:</string>
		</dict>
		<key>comment</key>
		<dict>
			<key>name</key>
			<string>comment.block.xcompose</string>
			<key>match</key>
			<string>#.*</string>
		</dict>
		<key>key</key>
		<dict>
			<key>match</key>
			<string>(?x) ( &lt; ) ( \S+ ) ( &gt; )</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.function.xcompose</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.xcompose.xcompose</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.function.xcompose</string>
				</dict>
			</dict>
		</dict>
		<key>keyword</key>
		<dict>
			<key>name</key>
			<string>entity.function.xcompose</string>
			<key>match</key>
			<string>include</string>
		</dict>
		<key>multikey</key>
		<dict>
			<key>match</key>
			<string>(?x) ( &lt; ) ( Multi_key ) ( &gt; )</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.function.xcompose</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>declaror.class.xcompose</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.function.xcompose</string>
				</dict>
			</dict>
		</dict>
		<key>quoted</key>
		<dict>
			<key>name</key>
			<string>string.quoted.double.xcompose</string>
			<key>match</key>
			<string>&quot;.*&quot;</string>
		</dict>
		<key>unicode</key>
		<dict>
			<key>name</key>
			<string>storage.modifier.unicode.xcompose</string>
			<key>match</key>
			<string>U[0-9A-Fa-f]+</string>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>.XCompose</string>
		<string>XCompose</string>
		<string>xcompose</string>
	</array>
</dict>
</plist>
