<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Yacc/Bison</string>
	<key>scopeName</key>
	<string>source.yacc</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#main</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>action</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.predicate.yacc</string>
					<key>begin</key>
					<string>(%\?)({)</string>
					<key>end</key>
					<string>}</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#action-innards</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.predicate.action.yacc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.block.begin.bracket.curly.c</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.block.end.bracket.curly.c</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.action.yacc</string>
					<key>begin</key>
					<string>{</string>
					<key>end</key>
					<string>}</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#action-innards</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.block.begin.bracket.curly.c</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.block.end.bracket.curly.c</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>action-innards</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>{</string>
					<key>end</key>
					<string>}</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#action-innards</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.block.begin.bracket.curly.c</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.block.end.bracket.curly.c</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>include</key>
					<string>#action-vars</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bison-defs</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.c++</string>
				</dict>
			</array>
		</dict>
		<key>action-vars</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.language.predefined-symbol.$2.yacc</string>
					<key>match</key>
					<string>(\$)(undefined|accept|end)(?![-.])\b</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.symbol.yacc</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.predefined-symbol.error.yacc</string>
					<key>match</key>
					<string>(?&lt;![-.$])\b(error)(?![-.])\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>variable.language.midrule-action-symbol.$2.nth.yacc</string>
					<key>match</key>
					<string>(\$@)([0-9]+)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.yacc</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>variable.language.rule-location.lhs.yacc</string>
					<key>match</key>
					<string>(@)\$</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.yacc</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>variable.language.positional.rule-location.rhs.$2.yacc.yacc</string>
					<key>match</key>
					<string>(@)([0-9]+)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.yacc</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>variable.language.rule-value.lhs.yacc</string>
					<key>match</key>
					<string>(\$)\$</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.yacc</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>variable.language.positional.rule-value.rhs.$2.yacc.yacc</string>
					<key>match</key>
					<string>(\$)([0-9]+)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.yacc</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>variable.language.symbol-location.yacc</string>
					<key>match</key>
					<string>(@)[A-Za-z_.][-.\w]*|(@)(\[)\s*[A-Za-z_.][-.\w]*\s*(\])</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.yacc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.yacc</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.begin.brace.bracket.square.yacc</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.end.bbrace.racket.square.yacc</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>variable.language.symbol-value.yacc</string>
					<key>match</key>
					<string>(\$)[A-Za-z_.][-.\w]*|(\$\[)\s*[A-Za-z_.][-.\w]*\s*(\])</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.yacc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.begin.yacc</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.end.yacc</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>bison-defs</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>support.function.$1.yacc</string>
					<key>match</key>
					<string>(?x) (?&lt;![.-]) \b
(YYABORT|YYACCEPT|YYBACKUP|YYDEBUG|YYERROR_VERBOSE|YYERROR|YYFPRINTF|YYINITDEPTH
|YYMAXDEPTH|YYPRINT|YYRECOVERING|YYSTACK_USE_ALLOCA|yyerrok|yyerror|yylex|yyparse
|yypstate_delete|yypstate_new|yypull_parse|yypush_parse)
\b (?![.-])</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.variable.$1.yacc</string>
					<key>match</key>
					<string>(?&lt;![.-])\b(yychar|yyclearin|yydebug|yylloc|yylval|yynerrs)\b(?![.-])</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.type.$1.yacc</string>
					<key>match</key>
					<string>(?&lt;![.-])\b(YYSTYPE|YYLTYPE)\b(?![.-])</string>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>name</key>
			<string>comment.block.yacc</string>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.begin.yacc</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.end.yacc</string>
				</dict>
			</dict>
		</dict>
		<key>constant</key>
		<dict>
			<key>name</key>
			<string>constant.language.other.token.yacc</string>
			<key>match</key>
			<string>\w+</string>
		</dict>
		<key>data-type</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>storage.modifier.type.yacc</string>
					<key>match</key>
					<string>(&lt;)(\*)(&gt;)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.angle.bracket.begin.yacc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.language.default.yacc</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.angle.bracket.end.yacc</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>storage.modifier.type.yacc</string>
					<key>begin</key>
					<string>&lt;</string>
					<key>end</key>
					<string>&gt;</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.angle.bracket.begin.yacc</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.angle.bracket.end.yacc</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>declaration-innards</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#constant</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#data-type</string>
				</dict>
			</array>
		</dict>
		<key>declaration-section</key>
		<dict>
			<key>name</key>
			<string>meta.declarations.yacc</string>
			<key>begin</key>
			<string>(?&lt;=%})</string>
			<key>end</key>
			<string>^(?=\s*%%)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#declarations</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#data-type</string>
				</dict>
			</array>
		</dict>
		<key>declarations</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*((%)union)\b</string>
					<key>end</key>
					<string>^(?=\s*%)|(?&lt;=})</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.c++</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.directive.union.yacc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.token.percentage-sign.yacc</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.code-block.yacc</string>
					<key>begin</key>
					<string>^\s*((%)code)\s+(imports)\s*({)</string>
					<key>end</key>
					<string>}</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.java</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.directive.code.yacc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.token.percentage-sign.yacc</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.language.other.qualifier.yacc</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.curly.bracket.begin.yacc</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.curly.bracket.end.yacc</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.$3-block.yacc</string>
					<key>begin</key>
					<string>^\s*((%)(code|lex-param|parse-param|param|printer))(?:\s+(\w+))?\s*({)</string>
					<key>end</key>
					<string>}</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.c++</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.directive.$3.yacc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.token.percentage-sign.yacc</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.language.other.qualifier.yacc</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.curly.bracket.begin.yacc</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.curly.bracket.end.yacc</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.defines.yacc</string>
					<key>match</key>
					<string>^\s*((%)defines)(?=\s|$|/\*|//)(?:\s+(?!//|/\*)(\S+))?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.directive.defines.yacc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.token.percentage-sign.yacc</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.filename.yacc</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>begin</key>
					<string>^\s*((%)define)(?:\s+([A-Za-z_.][-.\w]*))?\s*({)</string>
					<key>end</key>
					<string>}</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.c++</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.directive.define.yacc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.token.percentage-sign.yacc</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.var.yacc</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.curly.bracket.begin.yacc</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.curly.bracket.end.yacc</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>begin</key>
					<string>^\s*((%)define)(?:\s+([A-Za-z_.][-.\w]*))?</string>
					<key>end</key>
					<string>(?=\s*$)|^(?!\s{2,}(?=\w))|^(?=\s*%%)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#declaration-innards</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.directive.define.yacc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.token.percentage-sign.yacc</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.var.yacc</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>begin</key>
					<string>^\s*((%)option)(?=\s|$)</string>
					<key>end</key>
					<string>$|(?=\s*(?://|/\*))|^(?=\s*%%)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>constant.language.option-name.yacc</string>
							<key>match</key>
							<string>[A-Za-z_.][-.\w]*</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#declaration-innards</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.directive.option.yacc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.token.percentage-sign.yacc</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?x)
^\s* ((%)
(code|debug|destructor|dprec|empty|error-verbose|expect-rr|expect
|file-prefix|glr-parser|initial-action|language|left|lex-param
|locations|merge|name-prefix|no-lines|nonassoc|nterm|output|param
|parse-param|precedence|prec|printer|pure-parser|required?|right|skeleton
|start|token-table|token|type|verbose|yacc))\b</string>
					<key>end</key>
					<string>^(?!\s{2,}(?=\w))|^(?=\s*%%)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#declaration-innards</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.directive.$3.yacc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.token.percentage-sign.yacc</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>begin</key>
					<string>^\s*(%{)</string>
					<key>end</key>
					<string>^\s*(%})</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.c++</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.begin.yacc</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.end.yacc</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>epilogue</key>
		<dict>
			<key>name</key>
			<string>meta.epilogue.yacc</string>
			<key>begin</key>
			<string>(?&lt;=%%)</string>
			<key>end</key>
			<string>(?=A)B</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.c++</string>
				</dict>
			</array>
		</dict>
		<key>main</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#prologue</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#declaration-section</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#rules</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#epilogue</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.c++</string>
				</dict>
			</array>
		</dict>
		<key>prologue</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.begin.yacc</string>
					<key>match</key>
					<string>^\s*(%{)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.end.yacc</string>
					<key>match</key>
					<string>^\s*(%})</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#declarations</string>
				</dict>
			</array>
		</dict>
		<key>rule</key>
		<dict>
			<key>name</key>
			<string>meta.rule.yacc</string>
			<key>begin</key>
			<string>^\s*([A-Za-z_.][-.\w]*)\s*(:)</string>
			<key>end</key>
			<string>\s*(;)\s*</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>entity.name.rule.yacc</string>
					<key>match</key>
					<string>([A-Za-z_.][-.\w]*)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.logical.or.yacc</string>
					<key>match</key>
					<string>\|</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#action</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.rule.yacc</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.key-value.colon.yacc</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.terminator.statement.semicolon.yacc</string>
				</dict>
			</dict>
		</dict>
		<key>rules</key>
		<dict>
			<key>name</key>
			<string>meta.rules.yacc</string>
			<key>begin</key>
			<string>^\s*(%%)</string>
			<key>end</key>
			<string>^\s*(%%)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#rule</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.section.begin.yacc</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.section.end.yacc</string>
				</dict>
			</dict>
		</dict>
		<key>string</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>string.quoted.double.yacc</string>
					<key>begin</key>
					<string>&quot;</string>
					<key>end</key>
					<string>&quot;</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.yacc</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.yacc</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>string.quoted.single.yacc</string>
					<key>begin</key>
					<string>&apos;</string>
					<key>end</key>
					<string>&apos;</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.yacc</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.yacc</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>y</string>
		<string>yacc</string>
		<string>yy</string>
	</array>
</dict>
</plist>
