<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>ZAP</string>
	<key>scopeName</key>
	<string>source.zap</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#whitespace</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#number</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#labels</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#instruction</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#debug_directive</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#directive</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>branch</key>
		<dict>
			<key>name</key>
			<string>meta.branch.zap</string>
			<key>match</key>
			<string>(?x)
(?: (/) | (\\) )
\s*
(?:
    (TRUE | FALSE)
|   ( [A-Za-z?$#&amp;] [A-Za-z0-9\-?$#&amp;.]* )
)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.branch.positive.zap</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.branch.negative.zap</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.control.branch.${3:/downcase}.zap</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.control.branch.label.name.zap</string>
				</dict>
			</dict>
		</dict>
		<key>comment</key>
		<dict>
			<key>name</key>
			<string>comment.line.zap</string>
			<key>match</key>
			<string>(;).*$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.line.zap</string>
				</dict>
			</dict>
		</dict>
		<key>debug_directive</key>
		<dict>
			<key>name</key>
			<string>meta.directive.debug.zap</string>
			<key>begin</key>
			<string>(?x)
(?&lt;=\s|:|^)
(\.)(DEBUG-[-A-Z]+)
(?= \s | ; | $)</string>
			<key>end</key>
			<string>(?=;|$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#operands</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.directive.debug.${2:/downcase}.zap</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.directive.debug.zap</string>
				</dict>
			</dict>
		</dict>
		<key>directive</key>
		<dict>
			<key>name</key>
			<string>meta.directive.zap</string>
			<key>begin</key>
			<string>(?x)
(?&lt;=\s|:|^)
(?!\.DEBUG-)
(?:
    ((\.)(FUNCT))
    \s+
    ([A-Za-z?$#&amp;][A-Za-z0-9\-?$#&amp;.]*)
    (?= \s | [,;] | $)
|
    ((\.)([A-Z]+))
    (?= \s | ; | $)
)</string>
			<key>end</key>
			<string>(?=;|$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#operands</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.directive.${3:/downcase}.zap</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.directive.zap</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.zap</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.directive.${7:/downcase}.zap</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>punctuation.directive.zap</string>
				</dict>
			</dict>
		</dict>
		<key>global_label</key>
		<dict>
			<key>name</key>
			<string>meta.label.global.zap</string>
			<key>match</key>
			<string>([A-Za-z?$#&amp;][A-Za-z0-9\-?$#&amp;.]*)(::)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.definition.label.global.name.zap</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.label.global.zap</string>
				</dict>
			</dict>
		</dict>
		<key>identifier</key>
		<dict>
			<key>name</key>
			<string>meta.variable.zap</string>
			<key>match</key>
			<string>(STACK\b)|([A-Za-z?$#&amp;][A-Za-z0-9\-?$#&amp;.]*)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language.stack.zap</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.zap</string>
				</dict>
			</dict>
		</dict>
		<key>instruction</key>
		<dict>
			<key>name</key>
			<string>meta.instruction.zap</string>
			<key>begin</key>
			<string>(?x)
\b
(?:
    (JUMP)
    \s+
    ([A-Za-z?$#&amp;][A-Za-z0-9\-?$#&amp;.]*)
    (?= \s* (?: ; | $ ) )
|
    (
        ADD | ASHIFT | ASSIGNED\? | BAND | BCOM | BOR | BTST | BUFOUT | CALL | CALL1 | CALL2 |
        CATCH | CHECKU | CLEAR | COLOR | COPYT | CRLF | CURGET | CURSET | DCLEAR | DEC |
        DIRIN | DIROUT | DISPLAY | DIV | DLESS\? | EQUAL\? | ERASE | FCLEAR | FIRST\? | FONT |
        FSET\?? | FSTACK | GET | GETB | GETP | GETPT | GRTR\? | HLIGHT | ICALL | ICALL1 |
        ICALL2 | IGRTR\? | IN\? | INC | INPUT | INTBL\? | IRESTORE | ISAVE | IXCALL | JUMP |
        LESS\? | LEX | LOC | MARGIN | MENU | MOD | MOUSE-INFO | MOUSE-LIMIT | MOVE | MUL |
        NEXT\? | NEXTP | NOOP | ORIGINAL\? | PICINF | PICSET | POP | PRINT | PRINTB | PRINTC |
        PRINTD | PRINTF | PRINTI | PRINTN | PRINTR | PRINTT | PRINTU | PTSIZE | PUSH | PUT |
        PUTB | PUTP | QUIT | RANDOM | READ | REMOVE | RESTART | RESTORE | RETURN | RFALSE |
        RSTACK | RTRUE | SAVE | SCREEN | SCROLL | SET | SHIFT | SOUND | SPLIT | SUB | THROW |
        USL | VALUE | VERIFY | WINATTR | WINGET | WINPOS | WINPUT | WINSIZE | XCALL | XPUSH |
        ZERO\? | XWSTR
    )
    (?= \s | ; | $)
)</string>
			<key>end</key>
			<string>(?=;|$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#opcode</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operands</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#store</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#branch</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.opcode.zap</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.branch.label.name.zap</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.opcode.zap</string>
				</dict>
			</dict>
		</dict>
		<key>labels</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#global_label</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#local_label</string>
				</dict>
			</array>
		</dict>
		<key>local_label</key>
		<dict>
			<key>name</key>
			<string>meta.label.local.zap</string>
			<key>match</key>
			<string>([A-Za-z?$#&amp;][A-Za-z0-9\-?$#&amp;.]*)(:)(?!:)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.definition.label.local.name.zap</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.label.local.zap</string>
				</dict>
			</dict>
		</dict>
		<key>number</key>
		<dict>
			<key>name</key>
			<string>constant.numeric.decimal.zap</string>
			<key>match</key>
			<string>[0-9]+</string>
		</dict>
		<key>operands</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#summation</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#identifier</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
			</array>
		</dict>
		<key>store</key>
		<dict>
			<key>name</key>
			<string>meta.store.zap</string>
			<key>match</key>
			<string>(&gt;)\s*(?:(STACK)|([A-Za-z?$#&amp;][A-Za-z0-9\-?$#&amp;.]*))</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.storage.zap</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.stack.zap</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.variable.zap</string>
				</dict>
			</dict>
		</dict>
		<key>string</key>
		<dict>
			<key>name</key>
			<string>string.quoted.double.zap</string>
			<key>begin</key>
			<string>&quot;</string>
			<key>end</key>
			<string>&quot;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.character.escape.zap</string>
					<key>match</key>
					<string>\\.</string>
				</dict>
			</array>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.zap</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.zap</string>
				</dict>
			</dict>
		</dict>
		<key>summation</key>
		<dict>
			<key>name</key>
			<string>meta.operand.summation.zap</string>
			<key>match</key>
			<string>(?:([0-9]+)|([A-Za-z?$#&amp;][A-Za-z0-9\-?$#&amp;.]*))(?:\s*(\+)\s*(?:([0-9]+)|([A-Za-z?$#&amp;][A-Za-z0-9\-?$#&amp;.]*)))+</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.decimal.zap</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.variable.zap</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.plus.zap</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.decimal.zap</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>entity.name.variable.zap</string>
				</dict>
			</dict>
		</dict>
		<key>whitespace</key>
		<dict>
			<key>match</key>
			<string>\s+</string>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>zap</string>
		<string>xzap</string>
	</array>
</dict>
</plist>
