<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>ZenScript</string>
	<key>scopeName</key>
	<string>source.zenscript</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>name</key>
			<string>constant.numeric.zenscript</string>
			<key>match</key>
			<string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)([LlFfUuDd]|UL|ul)?\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.numeric.zenscript</string>
			<key>match</key>
			<string>\b\-?(0b|0x|0o|0B|0X|0O)(0|[1-9a-fA-F][0-9a-fA-F_]*)[a-zA-Z_]*\b</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#code</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.type.object.array.zenscript</string>
			<key>match</key>
			<string>\b((?:[a-z]\w*\.)*[A-Z]+\w*)(?=\[)</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>brackets</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.other.zenscript</string>
					<key>match</key>
					<string>(&lt;)\b(.*?)(:(.*?(:(\*|\d+)?)?)?)(&gt;)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.zenscript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.zenscript</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.control.zenscript</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>variable.other.zenscript</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>keyword.control.zenscript</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.zenscript</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>keyword.control.zenscript</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>class</key>
		<dict>
			<key>name</key>
			<string>meta.class.zenscript</string>
			<key>match</key>
			<string>(zenClass)\s+(\w+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.zenscript</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.class.zenscript</string>
				</dict>
			</dict>
		</dict>
		<key>code</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#class</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dots</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#quotes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#brackets</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#var</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operators</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>comment.line.double=slash</string>
					<key>match</key>
					<string>//[^
]*</string>
				</dict>
				<dict>
					<key>name</key>
					<string>comment.block</string>
					<key>begin</key>
					<string>\/\*</string>
					<key>end</key>
					<string>\*\/</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>comment.block</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>comment.block</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>dots</key>
		<dict>
			<key>name</key>
			<string>plain.text.zenscript</string>
			<key>match</key>
			<string>\b(\w+)(\.)(\w+)((\.)(\w+))*</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.zenscript</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.zenscript</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.control.zenscript</string>
				</dict>
			</dict>
		</dict>
		<key>functions</key>
		<dict>
			<key>name</key>
			<string>meta.function.zenscript</string>
			<key>match</key>
			<string>function\s+([A-Za-z_$][\w$]*)\s*(?=\()</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.zenscript</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.zenscript</string>
				</dict>
			</dict>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.control.zenscript</string>
					<key>match</key>
					<string>\b(instanceof|get|implements|set|import|function|override|const|if|else|do|while|for|throw|panic|lock|try|catch|finally|return|break|continue|switch|case|default|in|is|as|match|throws|super|new)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>storage.type.zenscript</string>
					<key>match</key>
					<string>\b(zenClass|zenConstructor|alias|class|interface|enum|struct|expand|variant|set|void|bool|byte|sbyte|short|ushort|int|uint|long|ulong|usize|float|double|char|string)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>storage.modifier.zenscript</string>
					<key>match</key>
					<string>\b(variant|abstract|final|private|public|export|internal|static|protected|implicit|virtual|extern|immutable)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name</string>
					<key>match</key>
					<string>\b(Native|Precondition)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language</string>
					<key>match</key>
					<string>\b(null|true|false)\b</string>
				</dict>
			</array>
		</dict>
		<key>operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.control</string>
					<key>match</key>
					<string>\b(\.|\.\.|\.\.\.|,|\+|\+=|\+\+|-|-=|--|~|~=|\*|\*=|/|/=|%|%=|\||\|=|\|\||&amp;|&amp;=|&amp;&amp;|\^|\^=|\?|\?\.|\?\?|&lt;|&lt;=|&lt;&lt;|&lt;&lt;=|&gt;|&gt;=|&gt;&gt;|&gt;&gt;=|&gt;&gt;&gt;|&gt;&gt;&gt;=|=&gt;|=|==|===|!|!=|!==|\$|`)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.control</string>
					<key>match</key>
					<string>\b(;|:)\b</string>
				</dict>
			</array>
		</dict>
		<key>quotes</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>string.quoted.double.zenscript</string>
					<key>begin</key>
					<string>&quot;</string>
					<key>end</key>
					<string>&quot;</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>constant.character.escape.zenscript</string>
							<key>match</key>
							<string>\\.</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.zenscript</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.zenscript</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>string.quoted.single.zenscript</string>
					<key>begin</key>
					<string>&apos;</string>
					<key>end</key>
					<string>&apos;</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>constant.character.escape.zenscript</string>
							<key>match</key>
							<string>\\.</string>
						</dict>
					</array>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.zenscript</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.zenscript</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>var</key>
		<dict>
			<key>name</key>
			<string>storage.type</string>
			<key>match</key>
			<string>\b(val|var)\b</string>
		</dict>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>zs</string>
	</array>
</dict>
</plist>
